# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from tqdm import tqdm

from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

# Loading Datasets

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_stacking_layer_one.parquet')
y_train = pd.read_parquet('../data/interim/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking_layer_one.parquet')

In [4]:
X_train.head()

,lgbm_0,lgbm_1,lgbm_2,xgb_0,xgb_1,xgb_2,cat_0,cat_1,cat_2
0,0.004831,0.002142,0.993027,0.005220,0.002128,0.992652,0.005655,0.000463,0.993882
1,0.998229,0.000143,0.001628,0.997774,0.000322,0.001904,0.994638,0.000368,0.004994
2,0.003982,0.000584,0.995434,0.002362,0.000710,0.996928,0.002327,0.000919,0.996754
3,0.007424,0.001954,0.990622,0.002922,0.003628,0.993450,0.003433,0.002374,0.994194
4,0.993583,0.000012,0.006405,0.997151,0.000013,0.002836,0.994112,0.000005,0.005883

In [5]:
X_test.head()

,lgbm_0,lgbm_1,lgbm_2,xgb_0,xgb_1,xgb_2,cat_0,cat_1,cat_2
0,0.011986,0.002516,0.985498,0.009749,0.003956,0.986295,0.008185,0.005526,0.986288
1,0.469590,0.002922,0.527488,0.344531,0.002104,0.653365,0.530403,0.002094,0.467503
2,0.998492,0.000991,0.000517,0.998555,0.001132,0.000313,0.996306,0.003216,0.000478
3,0.986619,0.000009,0.013372,0.978274,0.000024,0.021702,0.990683,0.000093,0.009224
4,0.008520,0.001975,0.989505,0.005601,0.002080,0.992319,0.003507,0.001947,0.994546

In [6]:
y_train.head()

    health_condition
id
0                  2
1                  0
2                  2
3                  2
4                  0

# Machine Learning

In [7]:
label_encoder = load_pickle('../artifacts/label_encoder.pkl')

In [29]:
def objective(trial, X, y):

    lgbm_w0 = trial.suggest_float('weight_lgbm_class_0', 0.0, 1.0)
    lgbm_w1 = trial.suggest_float('weight_lgbm_class_1', 0.0, 1.0)
    lgbm_w2 = trial.suggest_float('weight_lgbm_class_2', 0.0, 1.0)
    
    xgb_w0 = trial.suggest_float('weight_xgb_class_0', 0.0, 1.0)
    xgb_w1 = trial.suggest_float('weight_xgb_class_1', 0.0, 1.0)
    xgb_w2 = trial.suggest_float('weight_xgb_class_2', 0.0, 1.0)
    
    cat_w0 = trial.suggest_float('weight_cat_class_0', 0.0, 1.0)
    cat_w1 = trial.suggest_float('weight_cat_class_1', 0.0, 1.0)
    cat_w2 = trial.suggest_float('weight_cat_class_2', 0.0, 1.0)
    
    proba_lgbm = X[['lgbm_0', 'lgbm_1', 'lgbm_2']].to_numpy()
    proba_xgb  = X[['xgb_0', 'xgb_1', 'xgb_2']].to_numpy()
    proba_cat  = X[['cat_0', 'cat_1', 'cat_2']].to_numpy()

    w_lgbm = np.array([lgbm_w0, lgbm_w1, lgbm_w2])
    w_xgb  = np.array([xgb_w0, xgb_w1, xgb_w2])
    w_cat  = np.array([cat_w0, cat_w1, cat_w2])
    
    blend_proba = (proba_lgbm * w_lgbm) + (proba_xgb * w_xgb) + (proba_cat * w_cat)
    
    pred = np.argmax(blend_proba, axis=1)
    
    score = balanced_accuracy_score(y, pred)

    return score


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.health_condition), 
    n_trials=2000, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-07-03 10:22:35,846] A new study created in memory with name: no-name-e3ddce24-50c4-4669-9d42-38fab62f9171
Best trial: 5. Best value: 0.933954:   0%|▋                                                                                                                                      | 10/2000 [00:00<01:12, 27.53it/s]

[I 2026-07-03 10:22:36,024] Trial 1 finished with value: 0.8689888641616194 and parameters: {'weight_lgbm_class_0': 0.963272853179441, 'weight_lgbm_class_1': 0.913928441531453, 'weight_lgbm_class_2': 0.19765012096309487, 'weight_xgb_class_0': 0.30442554182296644, 'weight_xgb_class_1': 0.8589030048666338, 'weight_xgb_class_2': 0.9193728544684141, 'weight_cat_class_0': 0.8912555837284181, 'weight_cat_class_1': 0.5577475158449899, 'weight_cat_class_2': 0.045545943321797955}. Best is trial 1 with value: 0.8689888641616194.
[I 2026-07-03 10:22:36,033] Trial 2 finished with value: 0.8609455595018574 and parameters: {'weight_lgbm_class_0': 0.8055997008613686, 'weight_lgbm_class_1': 0.1377182403851992, 'weight_lgbm_class_2': 0.484715367941861, 'weight_xgb_class_0': 0.10574691282929005, 'weight_xgb_class_1': 0.42834695126475353, 'weight_xgb_class_2': 0.6293545638425081, 'weight_cat_class_0': 0.43135243124079115, 'weight_cat_class_1': 0.08858783189058794, 'weight_cat_class_2': 0.09960349978193406}. Best is trial 1 with value: 0.8689888641616194.
[I 2026-07-03 10:22:36,034] Trial 0 finished with value: 0.8602659067735194 and parameters: {'weight_lgbm_class_0': 0.4314134707260411, 'weight_lgbm_class_1': 0.2488341465137751, 'weight_lgbm_class_2': 0.20342021205886496, 'weight_xgb_class_0': 0.9367472395945668, 'weight_xgb_class_1': 0.47297912059287817, 'weight_xgb_class_2': 0.535658793972512, 'weight_cat_class_0': 0.5694802322734459, 'weight_cat_class_1': 0.7343884593613523, 'weight_cat_class_2': 0.2965019531918467}. Best is trial 1 with value: 0.8689888641616194.
[I 2026-07-03 10:22:36,051] Trial 3 finished with value: 0.9171757898954906 and parameters: {'weight_lgbm_class_0': 0.14652104041975078, 'weight_lgbm_class_1': 0.22847690314387237, 'weight_lgbm_class_2': 0.6429565838274584, 'weight_xgb_class_0': 0.022085996209161962, 'weight_xgb_class_1': 0.17331816301024838, 'weight_xgb_class_2': 0.9764309635190281, 'weight_cat_class_0': 0.5489903015654795, 'weight_cat_class_1': 0.7242899798346051, 'weight_cat_class_2': 0.08233527892366443}. Best is trial 3 with value: 0.9171757898954906.
[I 2026-07-03 10:22:36,083] Trial 5 finished with value: 0.933954113621815 and parameters: {'weight_lgbm_class_0': 0.2586674265131027, 'weight_lgbm_class_1': 0.0076491248162171566, 'weight_lgbm_class_2': 0.20627676017130536, 'weight_xgb_class_0': 0.07781218557506686, 'weight_xgb_class_1': 0.2922428560189271, 'weight_xgb_class_2': 0.35876956721757114, 'weight_cat_class_0': 0.08731416029627648, 'weight_cat_class_1': 0.7841473122293294, 'weight_cat_class_2': 0.7203990217670152}. Best is trial 5 with value: 0.933954113621815.
[I 2026-07-03 10:22:36,100] Trial 7 finished with value: 0.8813755008077494 and parameters: {'weight_lgbm_class_0': 0.3064863547443828, 'weight_lgbm_class_1': 0.5724738765474123, 'weight_lgbm_class_2': 0.7280755578996794, 'weight_xgb_class_0': 0.8210248844909442, 'weight_xgb_class_1': 0.9469078925299225, 'weight_xgb_class_2': 0.4023882879326153, 'weight_cat_class_0': 0.7274438607170862, 'weight_cat_class_1': 0.9175746546039176, 'weight_cat_class_2': 0.36998871879241346}. Best is trial 5 with value: 0.933954113621815.
[I 2026-07-03 10:22:36,100] Trial 8 finished with value: 0.8607776883541524 and parameters: {'weight_lgbm_class_0': 0.5192671536363707, 'weight_lgbm_class_1': 0.754009385137665, 'weight_lgbm_class_2': 0.5456016359717903, 'weight_xgb_class_0': 0.8041469722138128, 'weight_xgb_class_1': 0.1821269732595978, 'weight_xgb_class_2': 0.12115420546462408, 'weight_cat_class_0': 0.5371317331112226, 'weight_cat_class_1': 0.6668080898694234, 'weight_cat_class_2': 0.153036369786122}. Best is trial 5 with value: 0.933954113621815.
[I 2026-07-03 10:22:36,106] Trial 6 finished with value: 0.8324770292197535 and parameters: {'weight_lgbm_class_0': 0.6340064311452868, 'weight_lgbm_class_1': 0.11323141025608918, 'weight_lgbm_class_2': 0.5153498139879835, 'weight_xgb_class_0': 0.4511999596141373, 'weight_xgb_class_1': 0.09106840060066357, 'weight_xgb_class_2': 0.46959425303811897, 'weight_cat_class_0': 0.90984085848284, 'weight_cat_class_1': 0.058934537262826825, 'weight_cat_class_2': 0.16339866944309023}. Best is trial 5 with value: 0.933954113621815.
[I 2026-07-03 10:22:36,109] Trial 4 finished with value: 0.8832507975751733 and parameters: {'weight_lgbm_class_0': 0.7107589528951332, 'weight_lgbm_class_1': 0.0028863831901775328, 'weight_lgbm_class_2': 0.8922348753554614, 'weight_xgb_class_0': 0.27889737653424185, 'weight_xgb_class_1': 0.57119299125467, 'weight_xgb_class_2': 0.5831247131621323, 'weight_cat_class_0': 0.5728421654210101, 'weight_cat_class_1': 0.5134945725526222, 'weight_cat_class_2': 0.8440321232264466}. Best is trial 5 with value: 0.933954113621815.
[I 2026-07-03 10:22:36,134] Trial 10 finished with value: 0.8844976662062883 and parameters: {'weight_lgbm_class_0': 0.9220658495870042, 'weight_lgbm_class_1': 0.5028662256303472, 'weight_lgbm_class_2': 0.9641170005252259, 'weight_xgb_class_0': 0.532022444511587, 'weight_xgb_class_1': 0.6375082674831078, 'weight_xgb_class_2': 0.41679660931760165, 'weight_cat_class_0': 0.0986151154877114, 'weight_cat_class_1': 0.5832501582619797, 'weight_cat_class_2': 0.2404624806904515}. Best is trial 5 with value: 0.933954113621815.
[I 2026-07-03 10:22:36,142] Trial 9 finished with value: 0.8942158536495598 and parameters: {'weight_lgbm_class_0': 0.4694525188791089, 'weight_lgbm_class_1': 0.3098164182144806, 'weight_lgbm_class_2': 0.41463714865226553, 'weight_xgb_class_0': 0.0030919778901180583, 'weight_xgb_class_1': 0.633774492053645, 'weight_xgb_class_2': 0.9023941564462107, 'weight_cat_class_0': 0.8980899047793997, 'weight_cat_class_1': 0.7141446920060202, 'weight_cat_class_2': 0.5233437778573887}. Best is trial 5 with value: 0.933954113621815.

Best trial: 19. Best value: 0.948925:   1%|█▏                                                                                                                                    | 18/2000 [00:00<00:58, 34.09it/s]

[I 2026-07-03 10:22:36,149] Trial 11 finished with value: 0.898278591904759 and parameters: {'weight_lgbm_class_0': 0.6526514680791069, 'weight_lgbm_class_1': 0.7125104951727536, 'weight_lgbm_class_2': 0.9374387509179225, 'weight_xgb_class_0': 0.34237101817575444, 'weight_xgb_class_1': 0.4303406746538798, 'weight_xgb_class_2': 0.4060951500742087, 'weight_cat_class_0': 0.27224998332915284, 'weight_cat_class_1': 0.5415014051643281, 'weight_cat_class_2': 0.4244055553623516}. Best is trial 5 with value: 0.933954113621815.
[I 2026-07-03 10:22:36,230] Trial 14 finished with value: 0.8457708044541018 and parameters: {'weight_lgbm_class_0': 0.874082165266185, 'weight_lgbm_class_1': 0.581196955398047, 'weight_lgbm_class_2': 0.39135913796513055, 'weight_xgb_class_0': 0.9161096053404489, 'weight_xgb_class_1': 0.06296622510310745, 'weight_xgb_class_2': 0.5534996173588128, 'weight_cat_class_0': 0.9617765921923006, 'weight_cat_class_1': 0.4285588904175286, 'weight_cat_class_2': 0.39071541675119137}. Best is trial 5 with value: 0.933954113621815.
[I 2026-07-03 10:22:36,233] Trial 12 finished with value: 0.8926090260802981 and parameters: {'weight_lgbm_class_0': 0.06280008118909075, 'weight_lgbm_class_1': 0.25070064785068946, 'weight_lgbm_class_2': 0.7538713784437787, 'weight_xgb_class_0': 0.578009414608399, 'weight_xgb_class_1': 0.3076016450380392, 'weight_xgb_class_2': 0.5912753598373635, 'weight_cat_class_0': 0.25256568824198433, 'weight_cat_class_1': 0.02667699770691556, 'weight_cat_class_2': 0.5263738688391143}. Best is trial 5 with value: 0.933954113621815.
[I 2026-07-03 10:22:36,254] Trial 13 finished with value: 0.8629361399327351 and parameters: {'weight_lgbm_class_0': 0.749562798435996, 'weight_lgbm_class_1': 0.3160998837456772, 'weight_lgbm_class_2': 0.4811978664103419, 'weight_xgb_class_0': 0.5570298605467656, 'weight_xgb_class_1': 0.18766933133866803, 'weight_xgb_class_2': 0.9533334304795013, 'weight_cat_class_0': 0.6600048283163686, 'weight_cat_class_1': 0.7376997889373245, 'weight_cat_class_2': 0.13339593058727295}. Best is trial 5 with value: 0.933954113621815.
[I 2026-07-03 10:22:36,256] Trial 15 finished with value: 0.9190548219938593 and parameters: {'weight_lgbm_class_0': 0.23400128044530122, 'weight_lgbm_class_1': 0.5124118720774176, 'weight_lgbm_class_2': 0.733736580377854, 'weight_xgb_class_0': 0.2571032598893419, 'weight_xgb_class_1': 0.7542956409521175, 'weight_xgb_class_2': 0.8443919273921104, 'weight_cat_class_0': 0.6001171371217434, 'weight_cat_class_1': 0.9176668855864125, 'weight_cat_class_2': 0.5576163311143411}. Best is trial 5 with value: 0.933954113621815.
[I 2026-07-03 10:22:36,309] Trial 16 finished with value: 0.8979405277459115 and parameters: {'weight_lgbm_class_0': 0.7927603111054491, 'weight_lgbm_class_1': 0.9352166075020596, 'weight_lgbm_class_2': 0.43380497589207534, 'weight_xgb_class_0': 0.11310337730284936, 'weight_xgb_class_1': 0.2581406006910534, 'weight_xgb_class_2': 0.24660913025122333, 'weight_cat_class_0': 0.270839565414121, 'weight_cat_class_1': 0.4828800703806584, 'weight_cat_class_2': 0.8505454922815003}. Best is trial 5 with value: 0.933954113621815.
[I 2026-07-03 10:22:36,312] Trial 17 finished with value: 0.9026302225599926 and parameters: {'weight_lgbm_class_0': 0.6043120672252776, 'weight_lgbm_class_1': 0.5897036481413105, 'weight_lgbm_class_2': 0.8646630918435558, 'weight_xgb_class_0': 0.10313797647608369, 'weight_xgb_class_1': 0.5946790933745361, 'weight_xgb_class_2': 0.843563478347342, 'weight_cat_class_0': 0.4067036932257515, 'weight_cat_class_1': 0.09953410837001753, 'weight_cat_class_2': 0.2879872766711895}. Best is trial 5 with value: 0.933954113621815.
[I 2026-07-03 10:22:36,365] Trial 18 finished with value: 0.9474668037286097 and parameters: {'weight_lgbm_class_0': 0.06794939410282363, 'weight_lgbm_class_1': 0.34739864767819284, 'weight_lgbm_class_2': 0.0010412510589855317, 'weight_xgb_class_0': 0.13252310748776897, 'weight_xgb_class_1': 0.2329571716799325, 'weight_xgb_class_2': 0.03332839384874253, 'weight_cat_class_0': 0.003919081248508052, 'weight_cat_class_1': 0.9885260527439139, 'weight_cat_class_2': 0.9935884340635166}. Best is trial 18 with value: 0.9474668037286097.

Best trial: 19. Best value: 0.948925:   1%|█▋                                                                                                                                    | 26/2000 [00:00<00:54, 36.48it/s]

[I 2026-07-03 10:22:36,401] Trial 19 finished with value: 0.9489252170464392 and parameters: {'weight_lgbm_class_0': 0.016585495557653318, 'weight_lgbm_class_1': 0.3481600088733996, 'weight_lgbm_class_2': 0.031678915598186974, 'weight_xgb_class_0': 0.11223098329816114, 'weight_xgb_class_1': 0.25609471537134537, 'weight_xgb_class_2': 0.03715849503827062, 'weight_cat_class_0': 0.014259181152765352, 'weight_cat_class_1': 0.9946712695806814, 'weight_cat_class_2': 0.9795565481609342}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,415] Trial 21 finished with value: 0.9483547350601408 and parameters: {'weight_lgbm_class_0': 0.008280605091453008, 'weight_lgbm_class_1': 0.3172206486051485, 'weight_lgbm_class_2': 0.01841687321878449, 'weight_xgb_class_0': 0.12642437454262623, 'weight_xgb_class_1': 0.271675534380428, 'weight_xgb_class_2': 0.08770093204174711, 'weight_cat_class_0': 0.03967163795143591, 'weight_cat_class_1': 0.8945710169653072, 'weight_cat_class_2': 0.9768289033249634}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,433] Trial 20 finished with value: 0.9478444735437085 and parameters: {'weight_lgbm_class_0': 0.02830541585137769, 'weight_lgbm_class_1': 0.33517259656837156, 'weight_lgbm_class_2': 0.07009645776117213, 'weight_xgb_class_0': 0.1254203324087284, 'weight_xgb_class_1': 0.24691383620746213, 'weight_xgb_class_2': 0.08835358776632979, 'weight_cat_class_0': 0.05129886023791902, 'weight_cat_class_1': 0.9356211737160545, 'weight_cat_class_2': 0.9963645024332992}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,467] Trial 22 finished with value: 0.9334268692449937 and parameters: {'weight_lgbm_class_0': 0.2625834567437597, 'weight_lgbm_class_1': 0.44035486305189564, 'weight_lgbm_class_2': 0.009110113066634895, 'weight_xgb_class_0': 0.14529900063174275, 'weight_xgb_class_1': 0.8213895857328712, 'weight_xgb_class_2': 0.046026535949169, 'weight_cat_class_0': 0.01062431759028748, 'weight_cat_class_1': 0.9863765060345764, 'weight_cat_class_2': 0.8039107138230144}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,479] Trial 23 finished with value: 0.9296624136691459 and parameters: {'weight_lgbm_class_0': 0.25133177153638653, 'weight_lgbm_class_1': 0.4250850993193336, 'weight_lgbm_class_2': 0.03892827831898127, 'weight_xgb_class_0': 0.17759781291948923, 'weight_xgb_class_1': 0.834736630381774, 'weight_xgb_class_2': 0.012289469181648915, 'weight_cat_class_0': 0.019980150060230795, 'weight_cat_class_1': 0.9899964096226123, 'weight_cat_class_2': 0.7706845157552377}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,500] Trial 24 finished with value: 0.9365287813275026 and parameters: {'weight_lgbm_class_0': 0.2503069143889502, 'weight_lgbm_class_1': 0.3767848260797316, 'weight_lgbm_class_2': 0.019297106628915983, 'weight_xgb_class_0': 0.2014097383205667, 'weight_xgb_class_1': 0.7889538879645395, 'weight_xgb_class_2': 0.746817873064407, 'weight_cat_class_0': 0.09570859809511274, 'weight_cat_class_1': 0.9819549349067028, 'weight_cat_class_2': 0.7198287198703122}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,526] Trial 25 finished with value: 0.9396403266902243 and parameters: {'weight_lgbm_class_0': 0.2463950786494549, 'weight_lgbm_class_1': 0.47292636344834166, 'weight_lgbm_class_2': 0.0485039995105353, 'weight_xgb_class_0': 0.20125247977477884, 'weight_xgb_class_1': 0.771564980374206, 'weight_xgb_class_2': 0.7296696508461555, 'weight_cat_class_0': 0.0415721988004597, 'weight_cat_class_1': 0.9724351956618542, 'weight_cat_class_2': 0.6971232321648202}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,551] Trial 27 finished with value: 0.9468898394438137 and parameters: {'weight_lgbm_class_0': 0.04755020151895173, 'weight_lgbm_class_1': 0.40675377035572224, 'weight_lgbm_class_2': 0.014685610628562551, 'weight_xgb_class_0': 0.17500260199836454, 'weight_xgb_class_1': 0.3261184846814136, 'weight_xgb_class_2': 0.06657138298158577, 'weight_cat_class_0': 0.004293547604477738, 'weight_cat_class_1': 0.9804890176563171, 'weight_cat_class_2': 0.9533014678949677}. Best is trial 19 with value: 0.9489252170464392.

Best trial: 19. Best value: 0.948925:   2%|██▎                                                                                                                                   | 35/2000 [00:01<00:52, 37.67it/s]

[I 2026-07-03 10:22:36,558] Trial 26 finished with value: 0.9399184846645502 and parameters: {'weight_lgbm_class_0': 0.26215661803177914, 'weight_lgbm_class_1': 0.45187884361510455, 'weight_lgbm_class_2': 0.08850334463874998, 'weight_xgb_class_0': 0.19834013977880885, 'weight_xgb_class_1': 0.7716589982053237, 'weight_xgb_class_2': 0.7819780092887796, 'weight_cat_class_0': 0.03781773252367427, 'weight_cat_class_1': 0.9683043910046809, 'weight_cat_class_2': 0.6886130747677883}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,569] Trial 28 finished with value: 0.9467147565599946 and parameters: {'weight_lgbm_class_0': 0.007978451393623758, 'weight_lgbm_class_1': 0.40965391324497336, 'weight_lgbm_class_2': 0.037045190497267, 'weight_xgb_class_0': 0.20442411851629405, 'weight_xgb_class_1': 0.0035131313110342566, 'weight_xgb_class_2': 0.012486234855346612, 'weight_cat_class_0': 0.008174189934822492, 'weight_cat_class_1': 0.9984885534836241, 'weight_cat_class_2': 0.9985413515958068}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,598] Trial 29 finished with value: 0.9475451198945392 and parameters: {'weight_lgbm_class_0': 0.0006889639962546767, 'weight_lgbm_class_1': 0.4135521627528043, 'weight_lgbm_class_2': 0.0014555442715870268, 'weight_xgb_class_0': 0.21552097220687672, 'weight_xgb_class_1': 0.3623064642169537, 'weight_xgb_class_2': 0.1719912624464609, 'weight_cat_class_0': 0.004561642132831507, 'weight_cat_class_1': 0.8539517199170243, 'weight_cat_class_2': 0.9991357288069069}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,657] Trial 30 finished with value: 0.9421932200975703 and parameters: {'weight_lgbm_class_0': 0.014574714026024976, 'weight_lgbm_class_1': 0.3898198208784486, 'weight_lgbm_class_2': 0.10113957107837471, 'weight_xgb_class_0': 0.19759423876604665, 'weight_xgb_class_1': 0.3622736084873587, 'weight_xgb_class_2': 0.15909177268802016, 'weight_cat_class_0': 0.14961839943719085, 'weight_cat_class_1': 0.8598232059175698, 'weight_cat_class_2': 0.9969893457333296}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,662] Trial 31 finished with value: 0.9417905930063818 and parameters: {'weight_lgbm_class_0': 0.0032376590717596264, 'weight_lgbm_class_1': 0.40888652070829284, 'weight_lgbm_class_2': 0.11296127597306634, 'weight_xgb_class_0': 0.2076973906390486, 'weight_xgb_class_1': 0.33281905711783677, 'weight_xgb_class_2': 0.1614265756051993, 'weight_cat_class_0': 0.15875938786295363, 'weight_cat_class_1': 0.8511773560183484, 'weight_cat_class_2': 0.9982946564964404}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,700] Trial 32 finished with value: 0.9242259731644874 and parameters: {'weight_lgbm_class_0': 0.00699341970054561, 'weight_lgbm_class_1': 0.1561894020603712, 'weight_lgbm_class_2': 0.10473066781788296, 'weight_xgb_class_0': 0.39014241423836443, 'weight_xgb_class_1': 0.3757825144537835, 'weight_xgb_class_2': 0.18907070347370358, 'weight_cat_class_0': 0.2019916445999455, 'weight_cat_class_1': 0.8727203628157871, 'weight_cat_class_2': 0.971679564718803}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,718] Trial 33 finished with value: 0.9140654633699734 and parameters: {'weight_lgbm_class_0': 0.13448783145094995, 'weight_lgbm_class_1': 0.1570994137144491, 'weight_lgbm_class_2': 0.1187758077048084, 'weight_xgb_class_0': 0.40184661672621175, 'weight_xgb_class_1': 0.3826267003727588, 'weight_xgb_class_2': 0.17342082317504756, 'weight_cat_class_0': 0.1830271779274844, 'weight_cat_class_1': 0.8444699364631937, 'weight_cat_class_2': 0.9321028711029476}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,748] Trial 34 finished with value: 0.9180796799547939 and parameters: {'weight_lgbm_class_0': 0.00965349925607584, 'weight_lgbm_class_1': 0.16177183043449217, 'weight_lgbm_class_2': 0.12193763041537897, 'weight_xgb_class_0': 0.38556344027842265, 'weight_xgb_class_1': 0.005596458142657856, 'weight_xgb_class_2': 0.17397389921480605, 'weight_cat_class_0': 0.17535403417455142, 'weight_cat_class_1': 0.8362063898845191, 'weight_cat_class_2': 0.9236144788560486}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,762] Trial 35 finished with value: 0.9200334521790295 and parameters: {'weight_lgbm_class_0': 0.14392025490893945, 'weight_lgbm_class_1': 0.19618155795519487, 'weight_lgbm_class_2': 0.14832333619561644, 'weight_xgb_class_0': 0.366909578101816, 'weight_xgb_class_1': 0.5013980374657825, 'weight_xgb_class_2': 0.24137118291510912, 'weight_cat_class_0': 0.17959191992569765, 'weight_cat_class_1': 0.8504214860337861, 'weight_cat_class_2': 0.9081563207016143}. Best is trial 19 with value: 0.9489252170464392.

[I 2026-07-03 10:22:36,789] Trial 36 finished with value: 0.9210790734622369 and parameters: {'weight_lgbm_class_0': 0.14731876900924995, 'weight_lgbm_class_1': 0.219205725149059, 'weight_lgbm_class_2': 0.17144102479740958, 'weight_xgb_class_0': 0.37497203806437274, 'weight_xgb_class_1': 0.5014588436999411, 'weight_xgb_class_2': 0.27878732483744556, 'weight_cat_class_0': 0.18201503713076309, 'weight_cat_class_1': 0.8321005727422691, 'weight_cat_class_2': 0.9350112471389184}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,827] Trial 37 finished with value: 0.9189488195140965 and parameters: {'weight_lgbm_class_0': 0.1696551801914642, 'weight_lgbm_class_1': 0.2401661832726158, 'weight_lgbm_class_2': 0.1445200293649444, 'weight_xgb_class_0': 0.3824306005270057, 'weight_xgb_class_1': 0.521838521333102, 'weight_xgb_class_2': 0.25932656218234135, 'weight_cat_class_0': 0.17196423557293145, 'weight_cat_class_1': 0.8418964573024426, 'weight_cat_class_2': 0.9100019242605888}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,857] Trial 39 finished with value: 0.941146524883067 and parameters: {'weight_lgbm_class_0': 0.1415861065218621, 'weight_lgbm_class_1': 0.23953570549881517, 'weight_lgbm_class_2': 0.20342975094703214, 'weight_xgb_class_0': 0.0526256217568319, 'weight_xgb_class_1': 0.5151615122604654, 'weight_xgb_class_2': 0.255695802892711, 'weight_cat_class_0': 0.20421756589453766, 'weight_cat_class_1': 0.8379955700010787, 'weight_cat_class_2': 0.9031100246894963}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,860] Trial 38 finished with value: 0.9206204880100893 and parameters: {'weight_lgbm_class_0': 0.13465662488866786, 'weight_lgbm_class_1': 0.21978958241826263, 'weight_lgbm_class_2': 0.2068116801040451, 'weight_xgb_class_0': 0.38310501808780195, 'weight_xgb_class_1': 0.5010588635403663, 'weight_xgb_class_2': 0.26254059697759724, 'weight_cat_class_0': 0.19191201116855724, 'weight_cat_class_1': 0.8400347649727262, 'weight_cat_class_2': 0.9094317885151583}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,925] Trial 40 finished with value: 0.9318593848421521 and parameters: {'weight_lgbm_class_0': 0.14677311996461184, 'weight_lgbm_class_1': 0.26554722379190776, 'weight_lgbm_class_2': 0.2043855214807731, 'weight_xgb_class_0': 0.04876788426837436, 'weight_xgb_class_1': 0.49488009223382534, 'weight_xgb_class_2': 0.26844502120427594, 'weight_cat_class_0': 0.35711458007574237, 'weight_cat_class_1': 0.7960789103912889, 'weight_cat_class_2': 0.8967490484933963}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,930] Trial 41 finished with value: 0.9446360129513156 and parameters: {'weight_lgbm_class_0': 0.14395389500092232, 'weight_lgbm_class_1': 0.2574891120017361, 'weight_lgbm_class_2': 0.19867309937910882, 'weight_xgb_class_0': 0.055552369776048716, 'weight_xgb_class_1': 0.48680322153121414, 'weight_xgb_class_2': 0.24501772804511845, 'weight_cat_class_0': 0.11483106002235506, 'weight_cat_class_1': 0.7911575857447154, 'weight_cat_class_2': 0.8903482469795503}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,947] Trial 42 finished with value: 0.9458535039836967 and parameters: {'weight_lgbm_class_0': 0.14400622800373833, 'weight_lgbm_class_1': 0.255441237124613, 'weight_lgbm_class_2': 0.2274563656520579, 'weight_xgb_class_0': 0.04534596206658381, 'weight_xgb_class_1': 0.5129674741372665, 'weight_xgb_class_2': 0.28491396121764956, 'weight_cat_class_0': 0.10416676207811623, 'weight_cat_class_1': 0.7950357004186257, 'weight_cat_class_2': 0.8861671015039986}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,967] Trial 43 finished with value: 0.945599304029189 and parameters: {'weight_lgbm_class_0': 0.11458498798851477, 'weight_lgbm_class_1': 0.25457625576622944, 'weight_lgbm_class_2': 0.2601682925671612, 'weight_xgb_class_0': 0.049580934070994453, 'weight_xgb_class_1': 0.11451334992523657, 'weight_xgb_class_2': 0.28655976859846277, 'weight_cat_class_0': 0.0995476215788092, 'weight_cat_class_1': 0.7978151799131805, 'weight_cat_class_2': 0.8696980804869994}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:36,990] Trial 44 finished with value: 0.926322082947545 and parameters: {'weight_lgbm_class_0': 0.10038323807974495, 'weight_lgbm_class_1': 0.26515756156651377, 'weight_lgbm_class_2': 0.24912972166955444, 'weight_xgb_class_0': 0.06660867158090532, 'weight_xgb_class_1': 0.10943576783621897, 'weight_xgb_class_2': 0.07967097118093976, 'weight_cat_class_0': 0.3590154335752881, 'weight_cat_class_1': 0.7795008421828282, 'weight_cat_class_2': 0.8743741731633013}. Best is trial 19 with value: 0.9489252170464392.

Best trial: 19. Best value: 0.948925:   3%|███▌                                                                                                                                  | 53/2000 [00:01<00:48, 39.86it/s]

[I 2026-07-03 10:22:37,045] Trial 45 finished with value: 0.9099895276534692 and parameters: {'weight_lgbm_class_0': 0.08739102675388083, 'weight_lgbm_class_1': 0.3109359784444934, 'weight_lgbm_class_2': 0.2835849134957461, 'weight_xgb_class_0': 0.285663450931745, 'weight_xgb_class_1': 0.10275755718871646, 'weight_xgb_class_2': 0.0731215006050985, 'weight_cat_class_0': 0.3403316179108168, 'weight_cat_class_1': 0.7572175467303675, 'weight_cat_class_2': 0.8480850540096682}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,063] Trial 46 finished with value: 0.9289647772879728 and parameters: {'weight_lgbm_class_0': 0.09405063417981568, 'weight_lgbm_class_1': 0.08372616546465622, 'weight_lgbm_class_2': 0.28012703314314635, 'weight_xgb_class_0': 0.3042710560507574, 'weight_xgb_class_1': 0.1318451148202143, 'weight_xgb_class_2': 0.08222989203180073, 'weight_cat_class_0': 0.08737330674208639, 'weight_cat_class_1': 0.9188336433845504, 'weight_cat_class_2': 0.8564261873960854}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,092] Trial 47 finished with value: 0.9100207186986279 and parameters: {'weight_lgbm_class_0': 0.08761085770696572, 'weight_lgbm_class_1': 0.31932951259732734, 'weight_lgbm_class_2': 0.25218951617059576, 'weight_xgb_class_0': 0.27420174099224515, 'weight_xgb_class_1': 0.10595116836994584, 'weight_xgb_class_2': 0.09022823990513147, 'weight_cat_class_0': 0.3521271677213737, 'weight_cat_class_1': 0.7758382290163883, 'weight_cat_class_2': 0.837543543396221}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,107] Trial 49 finished with value: 0.9372975487248443 and parameters: {'weight_lgbm_class_0': 0.08529821015433948, 'weight_lgbm_class_1': 0.3425778148779579, 'weight_lgbm_class_2': 0.2793290971537109, 'weight_xgb_class_0': 0.26638210608989654, 'weight_xgb_class_1': 0.2574342327981585, 'weight_xgb_class_2': 0.09633426172739003, 'weight_cat_class_0': 0.07636652617122713, 'weight_cat_class_1': 0.912739096148786, 'weight_cat_class_2': 0.8350931905582533}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,131] Trial 48 finished with value: 0.9084837797230924 and parameters: {'weight_lgbm_class_0': 0.35447632307124255, 'weight_lgbm_class_1': 0.07135148973483041, 'weight_lgbm_class_2': 0.2689686882419495, 'weight_xgb_class_0': 0.27440366018472895, 'weight_xgb_class_1': 0.10845106546352426, 'weight_xgb_class_2': 0.10498967463056208, 'weight_cat_class_0': 0.09333636303541247, 'weight_cat_class_1': 0.9133505134465095, 'weight_cat_class_2': 0.8731638990404231}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,177] Trial 51 finished with value: 0.9337439277316494 and parameters: {'weight_lgbm_class_0': 0.07267106909423525, 'weight_lgbm_class_1': 0.32629703093406326, 'weight_lgbm_class_2': 0.058086484142062196, 'weight_xgb_class_0': 0.27872223934503687, 'weight_xgb_class_1': 0.23607126834876824, 'weight_xgb_class_2': 0.09159995111886649, 'weight_cat_class_0': 0.05468657371136466, 'weight_cat_class_1': 0.9213948573351449, 'weight_cat_class_2': 0.8029521911667301}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,182] Trial 50 finished with value: 0.9342333167540838 and parameters: {'weight_lgbm_class_0': 0.06502978935323565, 'weight_lgbm_class_1': 0.33457552041114247, 'weight_lgbm_class_2': 0.08152284003175592, 'weight_xgb_class_0': 0.2752544757773012, 'weight_xgb_class_1': 0.2549363224462859, 'weight_xgb_class_2': 0.09767333757567101, 'weight_cat_class_0': 0.0686349718085507, 'weight_cat_class_1': 0.916352320762437, 'weight_cat_class_2': 0.797736532871349}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,208] Trial 52 finished with value: 0.9363558631818125 and parameters: {'weight_lgbm_class_0': 0.07108475057462914, 'weight_lgbm_class_1': 0.33699187619951876, 'weight_lgbm_class_2': 0.07409272049346405, 'weight_xgb_class_0': 0.2617103417306752, 'weight_xgb_class_1': 0.23471453871337997, 'weight_xgb_class_2': 0.08711460777937077, 'weight_cat_class_0': 0.046627715832281584, 'weight_cat_class_1': 0.9218455182821191, 'weight_cat_class_2': 0.8079265214071397}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,241] Trial 53 finished with value: 0.9041953853126511 and parameters: {'weight_lgbm_class_0': 0.38163617554186186, 'weight_lgbm_class_1': 0.06384318277654155, 'weight_lgbm_class_2': 0.07528725205166222, 'weight_xgb_class_0': 0.26505392264066974, 'weight_xgb_class_1': 0.24077102771619469, 'weight_xgb_class_2': 0.11454112043738174, 'weight_cat_class_0': 0.06554276871522108, 'weight_cat_class_1': 0.898610790727754, 'weight_cat_class_2': 0.799269047946987}. Best is trial 19 with value: 0.9489252170464392.

Best trial: 19. Best value: 0.948925:   3%|████▏                                                                                                                                 | 62/2000 [00:01<00:49, 39.39it/s]

[I 2026-07-03 10:22:37,252] Trial 54 finished with value: 0.9262400151572129 and parameters: {'weight_lgbm_class_0': 0.2003365414423857, 'weight_lgbm_class_1': 0.37153584916989485, 'weight_lgbm_class_2': 0.07335175167804864, 'weight_xgb_class_0': 0.25254709979800827, 'weight_xgb_class_1': 0.25436858436853105, 'weight_xgb_class_2': 0.10549658731553085, 'weight_cat_class_0': 0.05718828926988836, 'weight_cat_class_1': 0.9175116427586238, 'weight_cat_class_2': 0.7969990225020428}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,310] Trial 56 finished with value: 0.9370919937497145 and parameters: {'weight_lgbm_class_0': 0.20015292769982743, 'weight_lgbm_class_1': 0.5270309546977486, 'weight_lgbm_class_2': 0.08278794197195524, 'weight_xgb_class_0': 0.13359396741098628, 'weight_xgb_class_1': 0.22163775117917978, 'weight_xgb_class_2': 0.00196654316699698, 'weight_cat_class_0': 0.05654417022489763, 'weight_cat_class_1': 0.6854611019811807, 'weight_cat_class_2': 0.9641462585312592}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,319] Trial 55 finished with value: 0.9373526658952748 and parameters: {'weight_lgbm_class_0': 0.19715558212423076, 'weight_lgbm_class_1': 0.5266252089465375, 'weight_lgbm_class_2': 0.0647566601266086, 'weight_xgb_class_0': 0.1312996626516922, 'weight_xgb_class_1': 0.22613046556120403, 'weight_xgb_class_2': 0.004916424056591304, 'weight_cat_class_0': 0.04805466163440697, 'weight_cat_class_1': 0.6218687965592776, 'weight_cat_class_2': 0.9598074810714098}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,340] Trial 57 finished with value: 0.9395401400887659 and parameters: {'weight_lgbm_class_0': 0.1906020198317534, 'weight_lgbm_class_1': 0.5232510477078489, 'weight_lgbm_class_2': 0.06783199943414317, 'weight_xgb_class_0': 0.10380453124010385, 'weight_xgb_class_1': 0.22435705351026383, 'weight_xgb_class_2': 0.133430680507465, 'weight_cat_class_0': 0.06292496639531264, 'weight_cat_class_1': 0.8956169721316429, 'weight_cat_class_2': 0.7856280112434253}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,390] Trial 58 finished with value: 0.9327884783552166 and parameters: {'weight_lgbm_class_0': 0.19693551206689028, 'weight_lgbm_class_1': 0.5474484228904528, 'weight_lgbm_class_2': 0.06512744141093318, 'weight_xgb_class_0': 0.13725076906473868, 'weight_xgb_class_1': 0.22455933728172217, 'weight_xgb_class_2': 0.03240453059307122, 'weight_cat_class_0': 0.05704032402834773, 'weight_cat_class_1': 0.6594157509148655, 'weight_cat_class_2': 0.7715569914311324}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,409] Trial 59 finished with value: 0.9483393494698847 and parameters: {'weight_lgbm_class_0': 0.04244851662030309, 'weight_lgbm_class_1': 0.5239283909026491, 'weight_lgbm_class_2': 0.005711899291552552, 'weight_xgb_class_0': 0.13185836096657744, 'weight_xgb_class_1': 0.42123034717320473, 'weight_xgb_class_2': 0.045072557060444524, 'weight_cat_class_0': 0.00014749682601308475, 'weight_cat_class_1': 0.688537295233993, 'weight_cat_class_2': 0.961139122426993}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,414] Trial 60 finished with value: 0.9404952294197987 and parameters: {'weight_lgbm_class_0': 0.20237810958228536, 'weight_lgbm_class_1': 0.5101151290501575, 'weight_lgbm_class_2': 0.016474739167809227, 'weight_xgb_class_0': 0.14148620722559377, 'weight_xgb_class_1': 0.19340206482462163, 'weight_xgb_class_2': 0.03276133635372973, 'weight_cat_class_0': 0.00333729399956574, 'weight_cat_class_1': 0.9530597074555763, 'weight_cat_class_2': 0.9531438220414089}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,447] Trial 61 finished with value: 0.9480409418758219 and parameters: {'weight_lgbm_class_0': 0.041656273039128805, 'weight_lgbm_class_1': 0.506352124844843, 'weight_lgbm_class_2': 0.0033329669744773215, 'weight_xgb_class_0': 0.13844317945020163, 'weight_xgb_class_1': 0.42823631354589453, 'weight_xgb_class_2': 0.03659689408024371, 'weight_cat_class_0': 0.0027407717115596614, 'weight_cat_class_1': 0.7008401385720069, 'weight_cat_class_2': 0.9660125973485002}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,471] Trial 62 finished with value: 0.9483659403013647 and parameters: {'weight_lgbm_class_0': 0.03919208349590057, 'weight_lgbm_class_1': 0.5475598276921383, 'weight_lgbm_class_2': 0.0034459453114005015, 'weight_xgb_class_0': 0.1293581317985238, 'weight_xgb_class_1': 0.42793441775057733, 'weight_xgb_class_2': 0.032495507052114146, 'weight_cat_class_0': 0.0029007526654430326, 'weight_cat_class_1': 0.7170872505981077, 'weight_cat_class_2': 0.9585327607971326}. Best is trial 19 with value: 0.9489252170464392.

Best trial: 19. Best value: 0.948925:   4%|████▊                                                                                                                                 | 71/2000 [00:01<00:48, 39.70it/s]

[I 2026-07-03 10:22:37,482] Trial 63 finished with value: 0.9481231390772343 and parameters: {'weight_lgbm_class_0': 0.0370994040079069, 'weight_lgbm_class_1': 0.5275209387744555, 'weight_lgbm_class_2': 0.009271144818340127, 'weight_xgb_class_0': 0.1349744385913205, 'weight_xgb_class_1': 0.42431840486447103, 'weight_xgb_class_2': 0.0005728363219958746, 'weight_cat_class_0': 0.003926536494416658, 'weight_cat_class_1': 0.95803395812979, 'weight_cat_class_2': 0.9502432344173417}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,529] Trial 64 finished with value: 0.9482941673235686 and parameters: {'weight_lgbm_class_0': 0.04239948228969298, 'weight_lgbm_class_1': 0.6281177261820738, 'weight_lgbm_class_2': 0.026918641151482743, 'weight_xgb_class_0': 0.009619639701310856, 'weight_xgb_class_1': 0.42473498000901244, 'weight_xgb_class_2': 0.2023616798523432, 'weight_cat_class_0': 0.0038933351038339717, 'weight_cat_class_1': 0.9585185657249595, 'weight_cat_class_2': 0.9440827078881093}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,549] Trial 65 finished with value: 0.9473163983372924 and parameters: {'weight_lgbm_class_0': 0.04540935892253069, 'weight_lgbm_class_1': 0.4748246143158389, 'weight_lgbm_class_2': 6.427601381158755e-05, 'weight_xgb_class_0': 0.16138495644130485, 'weight_xgb_class_1': 0.4306138935451915, 'weight_xgb_class_2': 0.04736283151553049, 'weight_cat_class_0': 0.006658769230781113, 'weight_cat_class_1': 0.9502097750971512, 'weight_cat_class_2': 0.945179518097264}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,558] Trial 66 finished with value: 0.9476207132942527 and parameters: {'weight_lgbm_class_0': 0.03764046693633776, 'weight_lgbm_class_1': 0.6283111467847864, 'weight_lgbm_class_2': 0.012416865717825817, 'weight_xgb_class_0': 0.1669699962007261, 'weight_xgb_class_1': 0.29260708128653246, 'weight_xgb_class_2': 0.04035164510271457, 'weight_cat_class_0': 0.000859623764012394, 'weight_cat_class_1': 0.9571320224641018, 'weight_cat_class_2': 0.9564680720195317}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,606] Trial 67 finished with value: 0.9159137087171129 and parameters: {'weight_lgbm_class_0': 0.03859376315933854, 'weight_lgbm_class_1': 0.6219162122658719, 'weight_lgbm_class_2': 0.008761811176852602, 'weight_xgb_class_0': 0.16591878185370562, 'weight_xgb_class_1': 0.2983890311994034, 'weight_xgb_class_2': 0.21163686466776288, 'weight_cat_class_0': 0.000269741613567279, 'weight_cat_class_1': 0.9730049195096044, 'weight_cat_class_2': 0.0027019166813350703}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,620] Trial 68 finished with value: 0.948334907402475 and parameters: {'weight_lgbm_class_0': 0.03878558461837794, 'weight_lgbm_class_1': 0.4643133254513803, 'weight_lgbm_class_2': 0.0005502745014129005, 'weight_xgb_class_0': 0.0035963354660395463, 'weight_xgb_class_1': 0.42890015918591184, 'weight_xgb_class_2': 0.05248230473598941, 'weight_cat_class_0': 0.13464551978447656, 'weight_cat_class_1': 0.9502441112138398, 'weight_cat_class_2': 0.9731761985595873}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,651] Trial 69 finished with value: 0.9483070243234316 and parameters: {'weight_lgbm_class_0': 0.04238445725010049, 'weight_lgbm_class_1': 0.6333231550351514, 'weight_lgbm_class_2': 0.0005616757256657853, 'weight_xgb_class_0': 0.009977466234233678, 'weight_xgb_class_1': 0.42677700882927105, 'weight_xgb_class_2': 0.21800132867995345, 'weight_cat_class_0': 0.13066089443956813, 'weight_cat_class_1': 0.32160909069631716, 'weight_cat_class_2': 0.99971313000163}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,677] Trial 70 finished with value: 0.9140327187157613 and parameters: {'weight_lgbm_class_0': 0.038745627792139845, 'weight_lgbm_class_1': 0.6715353671305057, 'weight_lgbm_class_2': 0.007618766418950902, 'weight_xgb_class_0': 0.0872467191459398, 'weight_xgb_class_1': 0.4345413133749811, 'weight_xgb_class_2': 0.20850961629094772, 'weight_cat_class_0': 0.11608497578594293, 'weight_cat_class_1': 0.7057473509869181, 'weight_cat_class_2': 0.03715562410914042}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,698] Trial 72 finished with value: 0.935621577251362 and parameters: {'weight_lgbm_class_0': 0.04197944357028377, 'weight_lgbm_class_1': 0.6525923186346466, 'weight_lgbm_class_2': 0.1576447414064077, 'weight_xgb_class_0': 0.009985171564084072, 'weight_xgb_class_1': 0.4367395080604442, 'weight_xgb_class_2': 0.20692956092544004, 'weight_cat_class_0': 0.12655181735712162, 'weight_cat_class_1': 0.585410038313338, 'weight_cat_class_2': 0.022410711154857765}. Best is trial 19 with value: 0.9489252170464392.

[I 2026-07-03 10:22:37,710] Trial 71 finished with value: 0.9489232938417823 and parameters: {'weight_lgbm_class_0': 0.03831951776245324, 'weight_lgbm_class_1': 0.6410362090091586, 'weight_lgbm_class_2': 0.14914599436083767, 'weight_xgb_class_0': 0.016367778230113747, 'weight_xgb_class_1': 0.4603735267510393, 'weight_xgb_class_2': 0.20772423390202363, 'weight_cat_class_0': 0.12389916920313601, 'weight_cat_class_1': 0.38288790390850785, 'weight_cat_class_2': 0.9558074628846}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,736] Trial 73 finished with value: 0.9486036818448041 and parameters: {'weight_lgbm_class_0': 0.043394347321998185, 'weight_lgbm_class_1': 0.6359184259325771, 'weight_lgbm_class_2': 0.143581007762854, 'weight_xgb_class_0': 0.018490601164048215, 'weight_xgb_class_1': 0.4389384921570212, 'weight_xgb_class_2': 0.20466255428992305, 'weight_cat_class_0': 0.13486754214881463, 'weight_cat_class_1': 0.7045513278370243, 'weight_cat_class_2': 0.9395770462810626}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,781] Trial 74 finished with value: 0.9478579741322095 and parameters: {'weight_lgbm_class_0': 0.054459188661094365, 'weight_lgbm_class_1': 0.6631089761060499, 'weight_lgbm_class_2': 0.1491556872026511, 'weight_xgb_class_0': 0.023503287773339238, 'weight_xgb_class_1': 0.4442250056305908, 'weight_xgb_class_2': 0.2076443418172826, 'weight_cat_class_0': 0.13077628705793187, 'weight_cat_class_1': 0.5939800671426584, 'weight_cat_class_2': 0.7498880397983436}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,809] Trial 75 finished with value: 0.938913716882204 and parameters: {'weight_lgbm_class_0': 0.035290995957522414, 'weight_lgbm_class_1': 0.6603436359473488, 'weight_lgbm_class_2': 0.1551480308528499, 'weight_xgb_class_0': 0.0013974338216835025, 'weight_xgb_class_1': 0.4496605351798017, 'weight_xgb_class_2': 0.2045093345880188, 'weight_cat_class_0': 0.13197940465840097, 'weight_cat_class_1': 0.7093608182013792, 'weight_cat_class_2': 0.056321826326574065}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,829] Trial 76 finished with value: 0.9069570348020367 and parameters: {'weight_lgbm_class_0': 0.04324276942512985, 'weight_lgbm_class_1': 0.7099323896947128, 'weight_lgbm_class_2': 0.15638516586925397, 'weight_xgb_class_0': 0.08700141875948966, 'weight_xgb_class_1': 0.4501537343732114, 'weight_xgb_class_2': 0.34830435953323385, 'weight_cat_class_0': 0.8048490301477658, 'weight_cat_class_1': 0.36995029083898817, 'weight_cat_class_2': 0.936755350159504}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,843] Trial 77 finished with value: 0.9451047044181718 and parameters: {'weight_lgbm_class_0': 0.11164209005654126, 'weight_lgbm_class_1': 0.6992106931557915, 'weight_lgbm_class_2': 0.1616531978000864, 'weight_xgb_class_0': 0.0021522120937790823, 'weight_xgb_class_1': 0.4361687247251167, 'weight_xgb_class_2': 0.1441166239879016, 'weight_cat_class_0': 0.1353598632933284, 'weight_cat_class_1': 0.36419976233038, 'weight_cat_class_2': 0.653152470551261}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,874] Trial 78 finished with value: 0.9476129019482699 and parameters: {'weight_lgbm_class_0': 0.10926286238041664, 'weight_lgbm_class_1': 0.7215108660912709, 'weight_lgbm_class_2': 0.1568065964591412, 'weight_xgb_class_0': 0.006910255741190866, 'weight_xgb_class_1': 0.5555167985849021, 'weight_xgb_class_2': 0.3402823979757067, 'weight_cat_class_0': 0.13360032342851716, 'weight_cat_class_1': 0.3564502884766624, 'weight_cat_class_2': 0.9314911640889365}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,917] Trial 81 finished with value: 0.8940850710400613 and parameters: {'weight_lgbm_class_0': 0.9986095866480418, 'weight_lgbm_class_1': 0.7841135766981925, 'weight_lgbm_class_2': 0.3237039926314469, 'weight_xgb_class_0': 0.08519074113166657, 'weight_xgb_class_1': 0.6378249297510798, 'weight_xgb_class_2': 0.3676995719546896, 'weight_cat_class_0': 0.2553327347084256, 'weight_cat_class_1': 0.3226759914028879, 'weight_cat_class_2': 0.9812403381795576}. Best is trial 19 with value: 0.9489252170464392.

Best trial: 90. Best value: 0.949305:   4%|█████▉                                                                                                                                | 88/2000 [00:02<00:48, 39.43it/s]

[I 2026-07-03 10:22:37,926] Trial 80 finished with value: 0.9448172148787995 and parameters: {'weight_lgbm_class_0': 0.09909902613761817, 'weight_lgbm_class_1': 0.7353501531507682, 'weight_lgbm_class_2': 0.3242543576117555, 'weight_xgb_class_0': 0.008674948183869886, 'weight_xgb_class_1': 0.5913431147560753, 'weight_xgb_class_2': 0.3271359824980103, 'weight_cat_class_0': 0.23538393191101162, 'weight_cat_class_1': 0.2649313353241534, 'weight_cat_class_2': 0.9292938976027847}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,933] Trial 79 finished with value: 0.9444819492176181 and parameters: {'weight_lgbm_class_0': 0.11440447038122764, 'weight_lgbm_class_1': 0.7348921944326192, 'weight_lgbm_class_2': 0.34126765362459044, 'weight_xgb_class_0': 0.012271017501747772, 'weight_xgb_class_1': 0.5717611377803493, 'weight_xgb_class_2': 0.33811951343969837, 'weight_cat_class_0': 0.24435043445324273, 'weight_cat_class_1': 0.34450810091611284, 'weight_cat_class_2': 0.9777352504242097}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,981] Trial 82 finished with value: 0.8999343016612581 and parameters: {'weight_lgbm_class_0': 0.10640629459273926, 'weight_lgbm_class_1': 0.798665076876999, 'weight_lgbm_class_2': 0.12760657592791086, 'weight_xgb_class_0': 0.09374068438572566, 'weight_xgb_class_1': 0.5876790367132523, 'weight_xgb_class_2': 0.13147993998161506, 'weight_cat_class_0': 0.8052827318463864, 'weight_cat_class_1': 0.2964229683371577, 'weight_cat_class_2': 0.9803797367579361}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:37,999] Trial 83 finished with value: 0.9390286153974632 and parameters: {'weight_lgbm_class_0': 0.1093202095442017, 'weight_lgbm_class_1': 0.7953308891061686, 'weight_lgbm_class_2': 0.050220603089984765, 'weight_xgb_class_0': 0.08548730467503049, 'weight_xgb_class_1': 0.557101084597581, 'weight_xgb_class_2': 0.35787987898541834, 'weight_cat_class_0': 0.23882133998303806, 'weight_cat_class_1': 0.3209861952307457, 'weight_cat_class_2': 0.9157838123301992}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:38,036] Trial 84 finished with value: 0.9397334212315451 and parameters: {'weight_lgbm_class_0': 0.11384397488712564, 'weight_lgbm_class_1': 0.7456836365463142, 'weight_lgbm_class_2': 0.04114647436064865, 'weight_xgb_class_0': 0.029393568865514863, 'weight_xgb_class_1': 0.5667907640431042, 'weight_xgb_class_2': 0.1312029905453768, 'weight_cat_class_0': 0.2415137173144002, 'weight_cat_class_1': 0.2929338584244982, 'weight_cat_class_2': 0.9840553441749753}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:38,065] Trial 85 finished with value: 0.9045888294326261 and parameters: {'weight_lgbm_class_0': 0.10744590226851355, 'weight_lgbm_class_1': 0.7917758998347444, 'weight_lgbm_class_2': 0.3317284435820559, 'weight_xgb_class_0': 0.7007901999203159, 'weight_xgb_class_1': 0.5804048844592665, 'weight_xgb_class_2': 0.3530920860529797, 'weight_cat_class_0': 0.25192647830964515, 'weight_cat_class_1': 0.2680447315374547, 'weight_cat_class_2': 0.9176557349072326}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:38,090] Trial 86 finished with value: 0.9438431348968211 and parameters: {'weight_lgbm_class_0': 0.001181762337201478, 'weight_lgbm_class_1': 0.5913895519560266, 'weight_lgbm_class_2': 0.12188992103553702, 'weight_xgb_class_0': 0.08614172460705008, 'weight_xgb_class_1': 0.5509281683538361, 'weight_xgb_class_2': 0.3237599969396505, 'weight_cat_class_0': 0.2331652116242034, 'weight_cat_class_1': 0.2374977027098052, 'weight_cat_class_2': 0.9822696259891647}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:38,093] Trial 87 finished with value: 0.9456516353700758 and parameters: {'weight_lgbm_class_0': 0.006228740684993392, 'weight_lgbm_class_1': 0.8815806613644614, 'weight_lgbm_class_2': 0.3256682275226253, 'weight_xgb_class_0': 0.08171155158623043, 'weight_xgb_class_1': 0.6328218956639549, 'weight_xgb_class_2': 0.14764390272718175, 'weight_cat_class_0': 0.23182685249167248, 'weight_cat_class_1': 0.21718965255895506, 'weight_cat_class_2': 0.9786393416215738}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:38,111] Trial 88 finished with value: 0.9452148398811993 and parameters: {'weight_lgbm_class_0': 0.00040290458145416513, 'weight_lgbm_class_1': 0.5818584635770029, 'weight_lgbm_class_2': 0.04089249441967793, 'weight_xgb_class_0': 0.037287114829067505, 'weight_xgb_class_1': 0.3976130286063878, 'weight_xgb_class_2': 0.3202479378511819, 'weight_cat_class_0': 0.22654003389158217, 'weight_cat_class_1': 0.2099179020115705, 'weight_cat_class_2': 0.9775645187178786}. Best is trial 19 with value: 0.9489252170464392.

Best trial: 92. Best value: 0.949583:   5%|██████▍                                                                                                                               | 97/2000 [00:02<00:48, 39.19it/s]

[I 2026-07-03 10:22:38,157] Trial 89 finished with value: 0.9459573099196789 and parameters: {'weight_lgbm_class_0': 8.25029205140989e-05, 'weight_lgbm_class_1': 0.8128662347370836, 'weight_lgbm_class_2': 0.03788770802601906, 'weight_xgb_class_0': 0.030985432636844043, 'weight_xgb_class_1': 0.3939103240570561, 'weight_xgb_class_2': 0.13995970692628182, 'weight_cat_class_0': 0.21197023770519813, 'weight_cat_class_1': 0.21503985962516184, 'weight_cat_class_2': 0.9077550907993672}. Best is trial 19 with value: 0.9489252170464392.
[I 2026-07-03 10:22:38,186] Trial 90 finished with value: 0.9493046927347009 and parameters: {'weight_lgbm_class_0': 0.002868512948958228, 'weight_lgbm_class_1': 0.5954750319675874, 'weight_lgbm_class_2': 0.04601832531071924, 'weight_xgb_class_0': 0.03097603026402927, 'weight_xgb_class_1': 0.4052931079234885, 'weight_xgb_class_2': 0.14804276320306636, 'weight_cat_class_0': 0.029004311863264493, 'weight_cat_class_1': 0.2361381560815349, 'weight_cat_class_2': 0.9025069977578017}. Best is trial 90 with value: 0.9493046927347009.
[I 2026-07-03 10:22:38,214] Trial 91 finished with value: 0.9495074451340146 and parameters: {'weight_lgbm_class_0': 0.0031711897300714786, 'weight_lgbm_class_1': 0.5966959765693901, 'weight_lgbm_class_2': 0.03955660818995753, 'weight_xgb_class_0': 0.03572471043197746, 'weight_xgb_class_1': 0.3917296228459117, 'weight_xgb_class_2': 0.05807370640131054, 'weight_cat_class_0': 0.034873201021198716, 'weight_cat_class_1': 0.22020226672646293, 'weight_cat_class_2': 0.8939163188667005}. Best is trial 91 with value: 0.9495074451340146.
[I 2026-07-03 10:22:38,236] Trial 92 finished with value: 0.9495827984678685 and parameters: {'weight_lgbm_class_0': 0.01051623955028938, 'weight_lgbm_class_1': 0.5671041092401707, 'weight_lgbm_class_2': 0.034221441948490305, 'weight_xgb_class_0': 0.040248073503691764, 'weight_xgb_class_1': 0.3968228323973164, 'weight_xgb_class_2': 0.14704380892122768, 'weight_cat_class_0': 0.037695042048928165, 'weight_cat_class_1': 0.16545932417640669, 'weight_cat_class_2': 0.8988902779996216}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,266] Trial 93 finished with value: 0.9169464555685667 and parameters: {'weight_lgbm_class_0': 0.004936055862778531, 'weight_lgbm_class_1': 0.594724078038284, 'weight_lgbm_class_2': 0.10108167969575664, 'weight_xgb_class_0': 0.6554372082947979, 'weight_xgb_class_1': 0.4039501463152481, 'weight_xgb_class_2': 0.4874227677852827, 'weight_cat_class_0': 0.030710693965764417, 'weight_cat_class_1': 0.20742502265180118, 'weight_cat_class_2': 0.8916573809397053}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,282] Trial 94 finished with value: 0.9491320358860311 and parameters: {'weight_lgbm_class_0': 0.06892035299703658, 'weight_lgbm_class_1': 0.5801719171486479, 'weight_lgbm_class_2': 0.03695852397163631, 'weight_xgb_class_0': 0.039492644174828416, 'weight_xgb_class_1': 0.39492048154398696, 'weight_xgb_class_2': 0.23254549522689355, 'weight_cat_class_0': 0.027829540916189943, 'weight_cat_class_1': 0.45092120130303914, 'weight_cat_class_2': 0.8806476514035709}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,331] Trial 95 finished with value: 0.9424743977270928 and parameters: {'weight_lgbm_class_0': 0.06696838543634576, 'weight_lgbm_class_1': 0.560986290378596, 'weight_lgbm_class_2': 0.09950479610610709, 'weight_xgb_class_0': 0.22826104399970176, 'weight_xgb_class_1': 0.4042876424396664, 'weight_xgb_class_2': 0.18170069622436538, 'weight_cat_class_0': 0.03192507249317501, 'weight_cat_class_1': 0.5132665259935305, 'weight_cat_class_2': 0.8917898782854162}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,351] Trial 96 finished with value: 0.940538157432699 and parameters: {'weight_lgbm_class_0': 0.0688200308393562, 'weight_lgbm_class_1': 0.6140379835005497, 'weight_lgbm_class_2': 0.10534515405590467, 'weight_xgb_class_0': 0.22438718360018706, 'weight_xgb_class_1': 0.3379672074880051, 'weight_xgb_class_2': 0.056872492329169855, 'weight_cat_class_0': 0.03075005858241094, 'weight_cat_class_1': 0.4836953903203767, 'weight_cat_class_2': 0.828745485278211}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,364] Trial 97 finished with value: 0.9158449458565997 and parameters: {'weight_lgbm_class_0': 0.0727766385103604, 'weight_lgbm_class_1': 0.6151776447648647, 'weight_lgbm_class_2': 0.03075854970792407, 'weight_xgb_class_0': 0.23193407662577026, 'weight_xgb_class_1': 0.3549123413608075, 'weight_xgb_class_2': 0.061981440126408716, 'weight_cat_class_0': 0.2938686486442872, 'weight_cat_class_1': 0.47034526660052467, 'weight_cat_class_2': 0.8279290921711544}. Best is trial 92 with value: 0.9495827984678685.

[I 2026-07-03 10:22:38,368] Trial 98 finished with value: 0.9440971514806615 and parameters: {'weight_lgbm_class_0': 0.16954342581344126, 'weight_lgbm_class_1': 0.4713898204487915, 'weight_lgbm_class_2': 0.5848637542106743, 'weight_xgb_class_0': 0.11109666122447912, 'weight_xgb_class_1': 0.33966675088226667, 'weight_xgb_class_2': 0.05940873046339459, 'weight_cat_class_0': 0.0256699721680934, 'weight_cat_class_1': 0.43568059015824995, 'weight_cat_class_2': 0.8327460854003637}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,444] Trial 99 finished with value: 0.9376232910813599 and parameters: {'weight_lgbm_class_0': 0.0654126014867959, 'weight_lgbm_class_1': 0.47243339399349893, 'weight_lgbm_class_2': 0.10244307893184645, 'weight_xgb_class_0': 0.11157847405356933, 'weight_xgb_class_1': 0.46770868111519076, 'weight_xgb_class_2': 0.06410547866110577, 'weight_cat_class_0': 0.15651007967352334, 'weight_cat_class_1': 0.14866891197354434, 'weight_cat_class_2': 0.8834355627420868}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,451] Trial 100 finished with value: 0.9449144761266551 and parameters: {'weight_lgbm_class_0': 0.06620211861842691, 'weight_lgbm_class_1': 0.5602788294310919, 'weight_lgbm_class_2': 0.11059768042651963, 'weight_xgb_class_0': 0.1132355681321523, 'weight_xgb_class_1': 0.33796231488830475, 'weight_xgb_class_2': 0.05516982297211681, 'weight_cat_class_0': 0.03460753113991183, 'weight_cat_class_1': 0.1275516536273714, 'weight_cat_class_2': 0.8229271879369219}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,477] Trial 101 finished with value: 0.9479985388226829 and parameters: {'weight_lgbm_class_0': 0.06405352236915768, 'weight_lgbm_class_1': 0.554723034561033, 'weight_lgbm_class_2': 0.09945149994272887, 'weight_xgb_class_0': 0.06261815765249953, 'weight_xgb_class_1': 0.33473588906010615, 'weight_xgb_class_2': 0.0599858272916219, 'weight_cat_class_0': 0.0268833268184661, 'weight_cat_class_1': 0.12627376000303683, 'weight_cat_class_2': 0.882059730451722}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,527] Trial 102 finished with value: 0.9460946457494875 and parameters: {'weight_lgbm_class_0': 0.06816606145917047, 'weight_lgbm_class_1': 0.5602347421748772, 'weight_lgbm_class_2': 0.10290201789651657, 'weight_xgb_class_0': 0.11390760291739846, 'weight_xgb_class_1': 0.3443785208149164, 'weight_xgb_class_2': 0.1782698219058302, 'weight_cat_class_0': 0.027381611850348236, 'weight_cat_class_1': 0.16565714477214838, 'weight_cat_class_2': 0.8276082598115331}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,532] Trial 103 finished with value: 0.9450343454743372 and parameters: {'weight_lgbm_class_0': 0.07166703292784969, 'weight_lgbm_class_1': 0.5662067647006273, 'weight_lgbm_class_2': 0.0989136804851661, 'weight_xgb_class_0': 0.11245854898610082, 'weight_xgb_class_1': 0.35092039419499144, 'weight_xgb_class_2': 0.06347645196052042, 'weight_cat_class_0': 0.032383960898489564, 'weight_cat_class_1': 0.1487842253192386, 'weight_cat_class_2': 0.8282206936850042}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,575] Trial 105 finished with value: 0.9386519078170386 and parameters: {'weight_lgbm_class_0': 0.17321631830026346, 'weight_lgbm_class_1': 0.6887673413967346, 'weight_lgbm_class_2': 0.18489593132654542, 'weight_xgb_class_0': 0.10993446486523775, 'weight_xgb_class_1': 0.3244832614512174, 'weight_xgb_class_2': 0.231470835012632, 'weight_cat_class_0': 0.07963616917025576, 'weight_cat_class_1': 0.13534612312260552, 'weight_cat_class_2': 0.8638965545725203}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,606] Trial 104 finished with value: 0.9406726190896549 and parameters: {'weight_lgbm_class_0': 0.1620890342058164, 'weight_lgbm_class_1': 0.5640080301067428, 'weight_lgbm_class_2': 0.18433622210469813, 'weight_xgb_class_0': 0.06644162617975946, 'weight_xgb_class_1': 0.36338719626322064, 'weight_xgb_class_2': 0.16379573818920362, 'weight_cat_class_0': 0.08107543387246666, 'weight_cat_class_1': 0.1335581180459202, 'weight_cat_class_2': 0.8588810689303049}. Best is trial 92 with value: 0.9495827984678685.

[I 2026-07-03 10:22:38,610] Trial 106 finished with value: 0.9482441704758541 and parameters: {'weight_lgbm_class_0': 0.017622948077930585, 'weight_lgbm_class_1': 0.6895471584887627, 'weight_lgbm_class_2': 0.0532673426042256, 'weight_xgb_class_0': 0.06073368243334989, 'weight_xgb_class_1': 0.4655054642262419, 'weight_xgb_class_2': 0.16015271112795468, 'weight_cat_class_0': 0.08692619002951814, 'weight_cat_class_1': 0.1031676108896275, 'weight_cat_class_2': 0.8629179792974142}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,619] Trial 107 finished with value: 0.9481396366002922 and parameters: {'weight_lgbm_class_0': 0.02278243694663411, 'weight_lgbm_class_1': 0.5723145529678149, 'weight_lgbm_class_2': 0.1901530066239055, 'weight_xgb_class_0': 0.06741120763950942, 'weight_xgb_class_1': 0.47605749338615055, 'weight_xgb_class_2': 0.11756191755489664, 'weight_cat_class_0': 0.081657279355276, 'weight_cat_class_1': 0.14409890463950942, 'weight_cat_class_2': 0.8603384028249403}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,650] Trial 108 finished with value: 0.9453255191178892 and parameters: {'weight_lgbm_class_0': 0.020768429971607702, 'weight_lgbm_class_1': 0.29302678567277807, 'weight_lgbm_class_2': 0.18577707153721984, 'weight_xgb_class_0': 0.06303679962404234, 'weight_xgb_class_1': 0.3140722218299796, 'weight_xgb_class_2': 0.1142678808656386, 'weight_cat_class_0': 0.08260048385640734, 'weight_cat_class_1': 0.09628357289599263, 'weight_cat_class_2': 0.8799416083954991}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,684] Trial 109 finished with value: 0.9461873124432642 and parameters: {'weight_lgbm_class_0': 0.023081258381324153, 'weight_lgbm_class_1': 0.28947217192267577, 'weight_lgbm_class_2': 0.1784661108411849, 'weight_xgb_class_0': 0.059963102727245816, 'weight_xgb_class_1': 0.4725690695199187, 'weight_xgb_class_2': 0.1622208468076039, 'weight_cat_class_0': 0.08748939715559761, 'weight_cat_class_1': 0.06166762100558748, 'weight_cat_class_2': 0.8703635818599514}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,696] Trial 110 finished with value: 0.9474507855504157 and parameters: {'weight_lgbm_class_0': 0.022004825494289466, 'weight_lgbm_class_1': 0.4319611730188743, 'weight_lgbm_class_2': 0.18731033585070334, 'weight_xgb_class_0': 0.06470467401297425, 'weight_xgb_class_1': 0.3661261094579383, 'weight_xgb_class_2': 0.11209104147987256, 'weight_cat_class_0': 0.08167983937408235, 'weight_cat_class_1': 0.17625874595098787, 'weight_cat_class_2': 0.8538779743945784}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,725] Trial 111 finished with value: 0.9471789463568284 and parameters: {'weight_lgbm_class_0': 0.022332423483057633, 'weight_lgbm_class_1': 0.4492859750615955, 'weight_lgbm_class_2': 0.18046796214054647, 'weight_xgb_class_0': 0.06367785588539447, 'weight_xgb_class_1': 0.4762502545862114, 'weight_xgb_class_2': 0.11670870893434596, 'weight_cat_class_0': 0.0828249944183654, 'weight_cat_class_1': 0.025051288732380828, 'weight_cat_class_2': 0.8648828977608141}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,741] Trial 112 finished with value: 0.9485543575556239 and parameters: {'weight_lgbm_class_0': 0.017453315304005356, 'weight_lgbm_class_1': 0.6834169671977262, 'weight_lgbm_class_2': 0.1838494493099419, 'weight_xgb_class_0': 0.05812294123682898, 'weight_xgb_class_1': 0.47287250848882706, 'weight_xgb_class_2': 0.11529108825539819, 'weight_cat_class_0': 0.08383523224480575, 'weight_cat_class_1': 0.05011886240583907, 'weight_cat_class_2': 0.8653589685193648}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,782] Trial 113 finished with value: 0.949115553544559 and parameters: {'weight_lgbm_class_0': 0.0236264123553762, 'weight_lgbm_class_1': 0.6862555480242492, 'weight_lgbm_class_2': 0.05492988267003784, 'weight_xgb_class_0': 0.05145098982815201, 'weight_xgb_class_1': 0.48225951658401633, 'weight_xgb_class_2': 0.23806972992913653, 'weight_cat_class_0': 0.08223171909101869, 'weight_cat_class_1': 0.7376380453179385, 'weight_cat_class_2': 0.8593817870127297}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,805] Trial 114 finished with value: 0.9456973702120847 and parameters: {'weight_lgbm_class_0': 0.02399575450930496, 'weight_lgbm_class_1': 0.4450742415750246, 'weight_lgbm_class_2': 0.056403410183903456, 'weight_xgb_class_0': 0.06304315448661005, 'weight_xgb_class_1': 0.37598571426343524, 'weight_xgb_class_2': 0.11885557287344471, 'weight_cat_class_0': 0.09521212696322699, 'weight_cat_class_1': 0.049689810194790796, 'weight_cat_class_2': 0.8632276434623428}. Best is trial 92 with value: 0.9495827984678685.

[I 2026-07-03 10:22:38,849] Trial 115 finished with value: 0.921404814396363 and parameters: {'weight_lgbm_class_0': 0.09339859978608275, 'weight_lgbm_class_1': 0.4947292460093702, 'weight_lgbm_class_2': 0.052394204998331986, 'weight_xgb_class_0': 0.17828545291838918, 'weight_xgb_class_1': 0.27960550278593266, 'weight_xgb_class_2': 0.017688836149666314, 'weight_cat_class_0': 0.15816969006941095, 'weight_cat_class_1': 0.00038182419905929965, 'weight_cat_class_2': 0.930915633792474}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,868] Trial 116 finished with value: 0.9483874003344527 and parameters: {'weight_lgbm_class_0': 0.022280667518442362, 'weight_lgbm_class_1': 0.4910353221167243, 'weight_lgbm_class_2': 0.028994107404180958, 'weight_xgb_class_0': 0.035879429555756646, 'weight_xgb_class_1': 0.27826578161277593, 'weight_xgb_class_2': 0.02389124121778011, 'weight_cat_class_0': 0.10488738433273033, 'weight_cat_class_1': 0.6490467956447752, 'weight_cat_class_2': 0.9209363163054268}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,909] Trial 117 finished with value: 0.9359442463661424 and parameters: {'weight_lgbm_class_0': 0.024738625054790468, 'weight_lgbm_class_1': 0.4420380374963645, 'weight_lgbm_class_2': 0.13576928846346248, 'weight_xgb_class_0': 0.18508001661939627, 'weight_xgb_class_1': 0.3821766795184685, 'weight_xgb_class_2': 0.012961028020405885, 'weight_cat_class_0': 0.11114971116844646, 'weight_cat_class_1': 0.06652952600923599, 'weight_cat_class_2': 0.9209458927008451}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,941] Trial 118 finished with value: 0.9026117825648022 and parameters: {'weight_lgbm_class_0': 0.5219576902847267, 'weight_lgbm_class_1': 0.4907453157872911, 'weight_lgbm_class_2': 0.02704667553775624, 'weight_xgb_class_0': 0.18141481657885233, 'weight_xgb_class_1': 0.3776163354609134, 'weight_xgb_class_2': 0.02384644207039141, 'weight_cat_class_0': 0.10344416658042063, 'weight_cat_class_1': 0.6399774291837887, 'weight_cat_class_2': 0.9315296975114452}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,957] Trial 120 finished with value: 0.8854681361332811 and parameters: {'weight_lgbm_class_0': 0.08846551746081983, 'weight_lgbm_class_1': 0.6357145698589229, 'weight_lgbm_class_2': 0.03169552094413339, 'weight_xgb_class_0': 0.9840620864730214, 'weight_xgb_class_1': 0.3770109094261351, 'weight_xgb_class_2': 0.02154066209591534, 'weight_cat_class_0': 0.11411382365154, 'weight_cat_class_1': 0.7391136933630544, 'weight_cat_class_2': 0.9257334518537276}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:38,977] Trial 119 finished with value: 0.9474829663278692 and parameters: {'weight_lgbm_class_0': 0.08288942599786947, 'weight_lgbm_class_1': 0.6421671064157434, 'weight_lgbm_class_2': 0.03689033837198608, 'weight_xgb_class_0': 0.03346073733797861, 'weight_xgb_class_1': 0.2795089966303023, 'weight_xgb_class_2': 0.2345986768730544, 'weight_cat_class_0': 0.10977065853215281, 'weight_cat_class_1': 0.6417990182345917, 'weight_cat_class_2': 0.9273160009794188}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,001] Trial 121 finished with value: 0.9459412582460791 and parameters: {'weight_lgbm_class_0': 0.08241708910035203, 'weight_lgbm_class_1': 0.6414972527758951, 'weight_lgbm_class_2': 0.22515384901927357, 'weight_xgb_class_0': 0.040062320386463623, 'weight_xgb_class_1': 0.5347758406196793, 'weight_xgb_class_2': 0.03243565131328289, 'weight_cat_class_0': 0.1098613283511028, 'weight_cat_class_1': 0.00572351056179083, 'weight_cat_class_2': 0.9550101439397016}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,011] Trial 123 finished with value: 0.8925863968899425 and parameters: {'weight_lgbm_class_0': 0.5244392512483462, 'weight_lgbm_class_1': 0.6395489623686349, 'weight_lgbm_class_2': 0.1341970219315846, 'weight_xgb_class_0': 0.1855167186320133, 'weight_xgb_class_1': 0.523486999856489, 'weight_xgb_class_2': 0.23788479408160856, 'weight_cat_class_0': 0.10842297369607969, 'weight_cat_class_1': 0.7377540187336686, 'weight_cat_class_2': 0.19795520371164688}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,032] Trial 122 finished with value: 0.9149768418423686 and parameters: {'weight_lgbm_class_0': 0.5620789940933287, 'weight_lgbm_class_1': 0.4930889305385985, 'weight_lgbm_class_2': 0.2227841789082842, 'weight_xgb_class_0': 0.03914879027232869, 'weight_xgb_class_1': 0.27514840793890144, 'weight_xgb_class_2': 0.03203316882490549, 'weight_cat_class_0': 0.10984218895325418, 'weight_cat_class_1': 0.6574452120425301, 'weight_cat_class_2': 0.923281872056474}. Best is trial 92 with value: 0.9495827984678685.

Best trial: 92. Best value: 0.949583:   7%|████████▋                                                                                                                            | 131/2000 [00:03<00:49, 37.72it/s]

[I 2026-07-03 10:22:39,084] Trial 124 finished with value: 0.9081034268427159 and parameters: {'weight_lgbm_class_0': 0.49697304091624994, 'weight_lgbm_class_1': 0.5976373002160297, 'weight_lgbm_class_2': 0.22005425807147777, 'weight_xgb_class_0': 0.038768925804153476, 'weight_xgb_class_1': 0.5410738205451039, 'weight_xgb_class_2': 0.29476558845816325, 'weight_cat_class_0': 0.10663156084072459, 'weight_cat_class_1': 0.7393358721166122, 'weight_cat_class_2': 0.19346763803758887}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,091] Trial 125 finished with value: 0.9486934436165022 and parameters: {'weight_lgbm_class_0': 0.052035866726560506, 'weight_lgbm_class_1': 0.644342723775452, 'weight_lgbm_class_2': 0.2209551390393577, 'weight_xgb_class_0': 0.03698962564353641, 'weight_xgb_class_1': 0.26976067482709937, 'weight_xgb_class_2': 0.29162580555654766, 'weight_cat_class_0': 0.11316755205132206, 'weight_cat_class_1': 0.7477162405644866, 'weight_cat_class_2': 0.91272224912553}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,113] Trial 126 finished with value: 0.9196215137160687 and parameters: {'weight_lgbm_class_0': 0.5083462519154983, 'weight_lgbm_class_1': 0.5947944138209942, 'weight_lgbm_class_2': 0.026395469245014503, 'weight_xgb_class_0': 0.027406232313537518, 'weight_xgb_class_1': 0.16331222351619348, 'weight_xgb_class_2': 0.08273752470773868, 'weight_cat_class_0': 0.05203357610278915, 'weight_cat_class_1': 0.6297975171798685, 'weight_cat_class_2': 0.8987415325481329}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,141] Trial 127 finished with value: 0.9486262133193314 and parameters: {'weight_lgbm_class_0': 0.08448037332055876, 'weight_lgbm_class_1': 0.6404374268684193, 'weight_lgbm_class_2': 0.025574661423605323, 'weight_xgb_class_0': 0.03503383070562767, 'weight_xgb_class_1': 0.15851865945341495, 'weight_xgb_class_2': 0.2268179794228279, 'weight_cat_class_0': 0.054424559319292895, 'weight_cat_class_1': 0.7363848071325823, 'weight_cat_class_2': 0.9011429311835747}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,196] Trial 128 finished with value: 0.9487111042427263 and parameters: {'weight_lgbm_class_0': 0.08777989519769927, 'weight_lgbm_class_1': 0.6009748242293017, 'weight_lgbm_class_2': 0.08037878246328009, 'weight_xgb_class_0': 0.04528391839401852, 'weight_xgb_class_1': 0.5322946894532326, 'weight_xgb_class_2': 0.2382105617476037, 'weight_cat_class_0': 0.052937275401031963, 'weight_cat_class_1': 0.8141404460427886, 'weight_cat_class_2': 0.9028481890863483}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,199] Trial 129 finished with value: 0.9443042019220784 and parameters: {'weight_lgbm_class_0': 0.1292798431775123, 'weight_lgbm_class_1': 0.602070075192949, 'weight_lgbm_class_2': 0.08180323027996603, 'weight_xgb_class_0': 0.14787415959774097, 'weight_xgb_class_1': 0.4931368504915803, 'weight_xgb_class_2': 0.2972283370805646, 'weight_cat_class_0': 0.054523528355945, 'weight_cat_class_1': 0.6778732266131733, 'weight_cat_class_2': 0.9045356021298153}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,243] Trial 130 finished with value: 0.9431917452062963 and parameters: {'weight_lgbm_class_0': 0.1312381544679861, 'weight_lgbm_class_1': 0.674697684248855, 'weight_lgbm_class_2': 0.079148640825697, 'weight_xgb_class_0': 0.15565951524386035, 'weight_xgb_class_1': 0.41182297652962996, 'weight_xgb_class_2': 0.2920523213846659, 'weight_cat_class_0': 0.05517022939762086, 'weight_cat_class_1': 0.5530809681129867, 'weight_cat_class_2': 0.8952500699536852}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,252] Trial 131 finished with value: 0.9493185452678848 and parameters: {'weight_lgbm_class_0': 0.048787715208715846, 'weight_lgbm_class_1': 0.608198284860568, 'weight_lgbm_class_2': 0.08284313013799006, 'weight_xgb_class_0': 0.025271856902841762, 'weight_xgb_class_1': 0.19477641199718154, 'weight_xgb_class_2': 0.290778444244578, 'weight_cat_class_0': 0.055226809748837744, 'weight_cat_class_1': 0.40937499031763824, 'weight_cat_class_2': 0.9033809352847003}. Best is trial 92 with value: 0.9495827984678685.

[I 2026-07-03 10:22:39,297] Trial 132 finished with value: 0.9414017382898275 and parameters: {'weight_lgbm_class_0': 0.12927119949155175, 'weight_lgbm_class_1': 0.535080874367368, 'weight_lgbm_class_2': 0.07610923053546814, 'weight_xgb_class_0': 0.15776093173902195, 'weight_xgb_class_1': 0.4155726370422071, 'weight_xgb_class_2': 0.30102297701238884, 'weight_cat_class_0': 0.05541006960080063, 'weight_cat_class_1': 0.39245159991401485, 'weight_cat_class_2': 0.8959096324150166}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,315] Trial 133 finished with value: 0.9434423842043831 and parameters: {'weight_lgbm_class_0': 0.1306248133127585, 'weight_lgbm_class_1': 0.6775947644397643, 'weight_lgbm_class_2': 0.08313006157371748, 'weight_xgb_class_0': 0.15406434219236398, 'weight_xgb_class_1': 0.17387174711705222, 'weight_xgb_class_2': 0.29496423891407536, 'weight_cat_class_0': 0.055890252161142774, 'weight_cat_class_1': 0.7660787401479118, 'weight_cat_class_2': 0.8949522290691825}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,350] Trial 134 finished with value: 0.9425686388516464 and parameters: {'weight_lgbm_class_0': 0.13045655684638785, 'weight_lgbm_class_1': 0.6758619732743643, 'weight_lgbm_class_2': 0.07820995445845336, 'weight_xgb_class_0': 0.14968314920997056, 'weight_xgb_class_1': 0.20686751085835536, 'weight_xgb_class_2': 0.19170298771600885, 'weight_cat_class_0': 0.06094778473522798, 'weight_cat_class_1': 0.7614046177564041, 'weight_cat_class_2': 0.9043854353702494}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,350] Trial 135 finished with value: 0.9425824566640442 and parameters: {'weight_lgbm_class_0': 0.12896367758726204, 'weight_lgbm_class_1': 0.6760400041317083, 'weight_lgbm_class_2': 0.07866185108729831, 'weight_xgb_class_0': 0.1484938344665652, 'weight_xgb_class_1': 0.3052581025963463, 'weight_xgb_class_2': 0.19101677055630853, 'weight_cat_class_0': 0.05526286033393793, 'weight_cat_class_1': 0.5442455520013036, 'weight_cat_class_2': 0.9036063695183876}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,400] Trial 136 finished with value: 0.948502192062637 and parameters: {'weight_lgbm_class_0': 0.12932274539748134, 'weight_lgbm_class_1': 0.6864073988622612, 'weight_lgbm_class_2': 0.08362975188848881, 'weight_xgb_class_0': 0.023517089178454725, 'weight_xgb_class_1': 0.4911132032919134, 'weight_xgb_class_2': 0.27381666460636545, 'weight_cat_class_0': 0.060318332585184375, 'weight_cat_class_1': 0.8164362895950414, 'weight_cat_class_2': 0.9042309481960457}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,404] Trial 137 finished with value: 0.9367194694756025 and parameters: {'weight_lgbm_class_0': 0.12959574192123507, 'weight_lgbm_class_1': 0.6814944276160966, 'weight_lgbm_class_2': 0.08198094853937303, 'weight_xgb_class_0': 0.09253118735981233, 'weight_xgb_class_1': 0.9809470415802877, 'weight_xgb_class_2': 0.2962955904892617, 'weight_cat_class_0': 0.1472262661042788, 'weight_cat_class_1': 0.7595610592790816, 'weight_cat_class_2': 0.4688135498967556}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,468] Trial 138 finished with value: 0.9490398959917804 and parameters: {'weight_lgbm_class_0': 0.047509579301402136, 'weight_lgbm_class_1': 0.6730868583207028, 'weight_lgbm_class_2': 0.06274240396937558, 'weight_xgb_class_0': 0.045206064920667546, 'weight_xgb_class_1': 0.14190730638246365, 'weight_xgb_class_2': 0.26346931396199036, 'weight_cat_class_0': 0.06851016981348688, 'weight_cat_class_1': 0.7684849588251533, 'weight_cat_class_2': 0.9522608615668561}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,494] Trial 139 finished with value: 0.9487477061149586 and parameters: {'weight_lgbm_class_0': 0.05361295376587431, 'weight_lgbm_class_1': 0.544348991743532, 'weight_lgbm_class_2': 0.842309479850591, 'weight_xgb_class_0': 0.023082023957113396, 'weight_xgb_class_1': 0.19392442291388515, 'weight_xgb_class_2': 0.2592636130450179, 'weight_cat_class_0': 0.14541795811449013, 'weight_cat_class_1': 0.8114939685095012, 'weight_cat_class_2': 0.9427884509823209}. Best is trial 92 with value: 0.9495827984678685.

Best trial: 92. Best value: 0.949583:   7%|█████████▊                                                                                                                           | 147/2000 [00:03<00:50, 36.57it/s]

[I 2026-07-03 10:22:39,504] Trial 140 finished with value: 0.947116283769724 and parameters: {'weight_lgbm_class_0': 0.0510472240300081, 'weight_lgbm_class_1': 0.6856999522026432, 'weight_lgbm_class_2': 0.07685791339179426, 'weight_xgb_class_0': 0.022667586090774093, 'weight_xgb_class_1': 0.20188639490050303, 'weight_xgb_class_2': 0.19206775618757804, 'weight_cat_class_0': 0.16854581259033669, 'weight_cat_class_1': 0.8077111391512102, 'weight_cat_class_2': 0.9034214855274433}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,540] Trial 141 finished with value: 0.9483657485394744 and parameters: {'weight_lgbm_class_0': 0.05663383891992599, 'weight_lgbm_class_1': 0.6777566062469634, 'weight_lgbm_class_2': 0.7863755913279595, 'weight_xgb_class_0': 0.02217734449579524, 'weight_xgb_class_1': 0.15832442862695953, 'weight_xgb_class_2': 0.19209555666119454, 'weight_cat_class_0': 0.17314563110434456, 'weight_cat_class_1': 0.7690732322389273, 'weight_cat_class_2': 0.8463893787479337}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,545] Trial 142 finished with value: 0.9467517003506455 and parameters: {'weight_lgbm_class_0': 0.05513202734646329, 'weight_lgbm_class_1': 0.7091525273804186, 'weight_lgbm_class_2': 0.12767441413147695, 'weight_xgb_class_0': 0.0273612821231861, 'weight_xgb_class_1': 0.20559228632357524, 'weight_xgb_class_2': 0.2673620563712114, 'weight_cat_class_0': 0.14599674955165357, 'weight_cat_class_1': 0.41089626559586345, 'weight_cat_class_2': 0.7650171606384665}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,610] Trial 144 finished with value: 0.9463617918689464 and parameters: {'weight_lgbm_class_0': 0.05407440188769076, 'weight_lgbm_class_1': 0.6145762465199042, 'weight_lgbm_class_2': 0.12571957747339524, 'weight_xgb_class_0': 0.018089116926302655, 'weight_xgb_class_1': 0.07037830692243814, 'weight_xgb_class_2': 0.26178775815689764, 'weight_cat_class_0': 0.1464843446255463, 'weight_cat_class_1': 0.4220987408051526, 'weight_cat_class_2': 0.7719029715079867}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,622] Trial 143 finished with value: 0.9348153540808019 and parameters: {'weight_lgbm_class_0': 0.052994732059331494, 'weight_lgbm_class_1': 0.615770846084611, 'weight_lgbm_class_2': 0.8191753348118616, 'weight_xgb_class_0': 0.02445355021262519, 'weight_xgb_class_1': 0.9427379333516122, 'weight_xgb_class_2': 0.2577212845336044, 'weight_cat_class_0': 0.5180140160955015, 'weight_cat_class_1': 0.8060284477751909, 'weight_cat_class_2': 0.33319907270389215}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,633] Trial 145 finished with value: 0.9466891054565109 and parameters: {'weight_lgbm_class_0': 0.049751616564306336, 'weight_lgbm_class_1': 0.6500997438964405, 'weight_lgbm_class_2': 0.12391509389432426, 'weight_xgb_class_0': 0.021468783159084105, 'weight_xgb_class_1': 0.14984045373653448, 'weight_xgb_class_2': 0.26615246425309724, 'weight_cat_class_0': 0.15109848366775097, 'weight_cat_class_1': 0.4160934066266584, 'weight_cat_class_2': 0.7782704631695168}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,655] Trial 146 finished with value: 0.9298038846707445 and parameters: {'weight_lgbm_class_0': 0.05294379747880922, 'weight_lgbm_class_1': 0.7107980362282843, 'weight_lgbm_class_2': 0.12735550828540304, 'weight_xgb_class_0': 0.023515012494234364, 'weight_xgb_class_1': 0.15682612870840862, 'weight_xgb_class_2': 0.26463388161598944, 'weight_cat_class_0': 0.4695357104795516, 'weight_cat_class_1': 0.812977796295975, 'weight_cat_class_2': 0.7700065571512363}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,697] Trial 147 finished with value: 0.949553846305986 and parameters: {'weight_lgbm_class_0': 0.05820266617210851, 'weight_lgbm_class_1': 0.7036603939541108, 'weight_lgbm_class_2': 0.12491830743614045, 'weight_xgb_class_0': 0.02351218750532684, 'weight_xgb_class_1': 0.15316539799236822, 'weight_xgb_class_2': 0.22073988069698128, 'weight_cat_class_0': 0.01847380002340525, 'weight_cat_class_1': 0.8152185062974774, 'weight_cat_class_2': 0.7757554108299893}. Best is trial 92 with value: 0.9495827984678685.

Best trial: 155. Best value: 0.949717:   8%|██████████▏                                                                                                                         | 155/2000 [00:04<00:49, 37.46it/s]

[I 2026-07-03 10:22:39,707] Trial 148 finished with value: 0.9350462988105438 and parameters: {'weight_lgbm_class_0': 0.056633358594213534, 'weight_lgbm_class_1': 0.7104152342655071, 'weight_lgbm_class_2': 0.825968939092506, 'weight_xgb_class_0': 0.05003579037700523, 'weight_xgb_class_1': 0.16504344425420184, 'weight_xgb_class_2': 0.2510614903152431, 'weight_cat_class_0': 0.5158850865045581, 'weight_cat_class_1': 0.8097646783320789, 'weight_cat_class_2': 0.7564627611426185}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,736] Trial 149 finished with value: 0.9483834654574176 and parameters: {'weight_lgbm_class_0': 0.053240884459385664, 'weight_lgbm_class_1': 0.7652576520266674, 'weight_lgbm_class_2': 0.460771165668351, 'weight_xgb_class_0': 0.0006096837158879112, 'weight_xgb_class_1': 0.06821087773017014, 'weight_xgb_class_2': 0.2548591980133327, 'weight_cat_class_0': 0.1491377683598559, 'weight_cat_class_1': 0.4126527789716644, 'weight_cat_class_2': 0.9487265700696988}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,761] Trial 150 finished with value: 0.9339780107785266 and parameters: {'weight_lgbm_class_0': 0.05480908557156877, 'weight_lgbm_class_1': 0.7622259588227902, 'weight_lgbm_class_2': 0.7473823452049705, 'weight_xgb_class_0': 0.0004865848906654008, 'weight_xgb_class_1': 0.14230749040244148, 'weight_xgb_class_2': 0.2561479284271708, 'weight_cat_class_0': 0.5127547175058285, 'weight_cat_class_1': 0.3890293772035297, 'weight_cat_class_2': 0.9467039615468475}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,806] Trial 151 finished with value: 0.9494726572722398 and parameters: {'weight_lgbm_class_0': 0.08531339597714327, 'weight_lgbm_class_1': 0.6106579416111179, 'weight_lgbm_class_2': 0.6435299089885737, 'weight_xgb_class_0': 0.047075593572315194, 'weight_xgb_class_1': 0.14794606166816995, 'weight_xgb_class_2': 0.25107935752602506, 'weight_cat_class_0': 0.026498757861891493, 'weight_cat_class_1': 0.8709421867528971, 'weight_cat_class_2': 0.9447957841201436}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,811] Trial 152 finished with value: 0.9492340984402162 and parameters: {'weight_lgbm_class_0': 0.05465889507350778, 'weight_lgbm_class_1': 0.6157381183849447, 'weight_lgbm_class_2': 0.4613743543011228, 'weight_xgb_class_0': 0.04860131998979933, 'weight_xgb_class_1': 0.06790867579476777, 'weight_xgb_class_2': 0.38297648628247355, 'weight_cat_class_0': 0.027307098109095547, 'weight_cat_class_1': 0.4406005415942179, 'weight_cat_class_2': 0.9468454716763803}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,825] Trial 153 finished with value: 0.9070248188490591 and parameters: {'weight_lgbm_class_0': 0.8721476810492035, 'weight_lgbm_class_1': 0.7604401169738397, 'weight_lgbm_class_2': 0.05373177085867264, 'weight_xgb_class_0': 0.04546649044996563, 'weight_xgb_class_1': 0.13383181415709028, 'weight_xgb_class_2': 0.38103354160751124, 'weight_cat_class_0': 0.02556107252084007, 'weight_cat_class_1': 0.7240262908121973, 'weight_cat_class_2': 0.951771285541475}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,851] Trial 154 finished with value: 0.9488207167439473 and parameters: {'weight_lgbm_class_0': 0.07942926414615382, 'weight_lgbm_class_1': 0.5885462311612297, 'weight_lgbm_class_2': 0.8979230065500093, 'weight_xgb_class_0': 0.04893037887530418, 'weight_xgb_class_1': 0.07563929385997202, 'weight_xgb_class_2': 0.2377392497292458, 'weight_cat_class_0': 0.020710650585261163, 'weight_cat_class_1': 0.45103610763718277, 'weight_cat_class_2': 0.9612813063999676}. Best is trial 92 with value: 0.9495827984678685.
[I 2026-07-03 10:22:39,896] Trial 155 finished with value: 0.9497166282745368 and parameters: {'weight_lgbm_class_0': 0.09090488619931004, 'weight_lgbm_class_1': 0.7709393736392519, 'weight_lgbm_class_2': 0.5695082413243293, 'weight_xgb_class_0': 0.0013907118066931942, 'weight_xgb_class_1': 0.17728866964326287, 'weight_xgb_class_2': 0.22564051536205826, 'weight_cat_class_0': 0.02521817469383102, 'weight_cat_class_1': 0.7850564993705913, 'weight_cat_class_2': 0.6836562431896785}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:   8%|██████████▊                                                                                                                         | 163/2000 [00:04<00:48, 37.58it/s]

[I 2026-07-03 10:22:39,935] Trial 156 finished with value: 0.9202136051384401 and parameters: {'weight_lgbm_class_0': 0.8630719143290466, 'weight_lgbm_class_1': 0.7709526123091556, 'weight_lgbm_class_2': 0.6776058605705134, 'weight_xgb_class_0': 0.0005196011713658744, 'weight_xgb_class_1': 0.18483400288470114, 'weight_xgb_class_2': 0.21837188303760227, 'weight_cat_class_0': 0.02188442697647533, 'weight_cat_class_1': 0.7266252087859102, 'weight_cat_class_2': 0.9512225692926348}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:39,949] Trial 157 finished with value: 0.946332936020704 and parameters: {'weight_lgbm_class_0': 0.09431484594356497, 'weight_lgbm_class_1': 0.5821560379775418, 'weight_lgbm_class_2': 0.051759607082053544, 'weight_xgb_class_0': 0.07774924596099303, 'weight_xgb_class_1': 0.13797417937887724, 'weight_xgb_class_2': 0.22289266340287694, 'weight_cat_class_0': 0.04157375604970552, 'weight_cat_class_1': 0.8643917848830656, 'weight_cat_class_2': 0.6337554261639313}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,012] Trial 158 finished with value: 0.9489208587933122 and parameters: {'weight_lgbm_class_0': 0.0903862274748132, 'weight_lgbm_class_1': 0.65249424193841, 'weight_lgbm_class_2': 0.9479739130851533, 'weight_xgb_class_0': 0.07877439846432432, 'weight_xgb_class_1': 0.1352129534419111, 'weight_xgb_class_2': 0.22033302785021353, 'weight_cat_class_0': 0.03755545707601542, 'weight_cat_class_1': 0.7248170752582057, 'weight_cat_class_2': 0.6908686881336314}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,022] Trial 159 finished with value: 0.9474926598758353 and parameters: {'weight_lgbm_class_0': 0.08936304612812673, 'weight_lgbm_class_1': 0.5824933015734116, 'weight_lgbm_class_2': 0.9491976844401093, 'weight_xgb_class_0': 0.07901752481320815, 'weight_xgb_class_1': 0.18030686300298904, 'weight_xgb_class_2': 0.21364536598387623, 'weight_cat_class_0': 0.020292151244580156, 'weight_cat_class_1': 0.1871575674565228, 'weight_cat_class_2': 0.809771076699758}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,035] Trial 160 finished with value: 0.9477324451271599 and parameters: {'weight_lgbm_class_0': 0.0939424710916801, 'weight_lgbm_class_1': 0.5764056702837119, 'weight_lgbm_class_2': 0.6904283363204068, 'weight_xgb_class_0': 0.08712050471516875, 'weight_xgb_class_1': 0.013952892335611644, 'weight_xgb_class_2': 0.22777958194446266, 'weight_cat_class_0': 0.022019534246819242, 'weight_cat_class_1': 0.4470578564073087, 'weight_cat_class_2': 0.9998913115419379}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,053] Trial 161 finished with value: 0.9480996054502446 and parameters: {'weight_lgbm_class_0': 0.08971444836719976, 'weight_lgbm_class_1': 0.584508560346072, 'weight_lgbm_class_2': 0.6733245774117862, 'weight_xgb_class_0': 0.09415667705898266, 'weight_xgb_class_1': 0.12426205319730019, 'weight_xgb_class_2': 0.3839958062292079, 'weight_cat_class_0': 0.01804845704278123, 'weight_cat_class_1': 0.44336947815640854, 'weight_cat_class_2': 0.6650481506341395}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,083] Trial 162 finished with value: 0.9492675539153423 and parameters: {'weight_lgbm_class_0': 0.08491856302738059, 'weight_lgbm_class_1': 0.5899812743362775, 'weight_lgbm_class_2': 0.6152608680752841, 'weight_xgb_class_0': 0.08076895003396824, 'weight_xgb_class_1': 0.18132176139579553, 'weight_xgb_class_2': 0.44187897357580014, 'weight_cat_class_0': 0.019961240818972492, 'weight_cat_class_1': 0.83130105301027, 'weight_cat_class_2': 0.9694672284910543}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,120] Trial 163 finished with value: 0.9490140459089634 and parameters: {'weight_lgbm_class_0': 0.09532269124335759, 'weight_lgbm_class_1': 0.5852163162402805, 'weight_lgbm_class_2': 0.6293346406116302, 'weight_xgb_class_0': 0.07883437324107674, 'weight_xgb_class_1': 0.049804829733267546, 'weight_xgb_class_2': 0.22389501172602888, 'weight_cat_class_0': 0.018336086657198974, 'weight_cat_class_1': 0.8637681125719859, 'weight_cat_class_2': 0.7358240550819769}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:   9%|███████████▎                                                                                                                        | 172/2000 [00:04<00:47, 38.13it/s]

[I 2026-07-03 10:22:40,151] Trial 165 finished with value: 0.9489421424552053 and parameters: {'weight_lgbm_class_0': 0.0931233549923164, 'weight_lgbm_class_1': 0.8372701817114051, 'weight_lgbm_class_2': 0.5316992197142263, 'weight_xgb_class_0': 0.08016621377747365, 'weight_xgb_class_1': 0.08835359762564973, 'weight_xgb_class_2': 0.23529684405836568, 'weight_cat_class_0': 0.02252930868840943, 'weight_cat_class_1': 0.86853572083197, 'weight_cat_class_2': 0.6399071993987769}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,160] Trial 164 finished with value: 0.949355637657221 and parameters: {'weight_lgbm_class_0': 0.0942414116438755, 'weight_lgbm_class_1': 0.8252294849748792, 'weight_lgbm_class_2': 0.9263727025925813, 'weight_xgb_class_0': 0.07701192046799257, 'weight_xgb_class_1': 0.09474676276997153, 'weight_xgb_class_2': 0.2258487721511236, 'weight_cat_class_0': 0.02344157733135, 'weight_cat_class_1': 0.8661764334580012, 'weight_cat_class_2': 0.7028019640618147}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,202] Trial 166 finished with value: 0.9172984759373053 and parameters: {'weight_lgbm_class_0': 0.6655210280174133, 'weight_lgbm_class_1': 0.5394088781676727, 'weight_lgbm_class_2': 0.9072164134414503, 'weight_xgb_class_0': 0.08438956282575154, 'weight_xgb_class_1': 0.04038794618383892, 'weight_xgb_class_2': 0.4749476662746333, 'weight_cat_class_0': 0.01609416764547404, 'weight_cat_class_1': 0.46749986609510064, 'weight_cat_class_2': 0.6688700355608357}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,236] Trial 167 finished with value: 0.9144825601086931 and parameters: {'weight_lgbm_class_0': 0.6971845166338081, 'weight_lgbm_class_1': 0.5440801719071795, 'weight_lgbm_class_2': 0.9454461452775569, 'weight_xgb_class_0': 0.08247751075036266, 'weight_xgb_class_1': 0.05050611572327181, 'weight_xgb_class_2': 0.39210920631091906, 'weight_cat_class_0': 0.017380027132437793, 'weight_cat_class_1': 0.4400140059661684, 'weight_cat_class_2': 0.649305108447919}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,278] Trial 169 finished with value: 0.9488504341487395 and parameters: {'weight_lgbm_class_0': 0.00014150410666919494, 'weight_lgbm_class_1': 0.6093773800410237, 'weight_lgbm_class_2': 0.9944392066427463, 'weight_xgb_class_0': 0.052394288023596566, 'weight_xgb_class_1': 0.0869526295614317, 'weight_xgb_class_2': 0.45888171411816114, 'weight_cat_class_0': 0.038617472934568645, 'weight_cat_class_1': 0.8749204983888673, 'weight_cat_class_2': 0.6395304133443889}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,316] Trial 170 finished with value: 0.949400452434442 and parameters: {'weight_lgbm_class_0': 0.03161159902971056, 'weight_lgbm_class_1': 0.6103911313469622, 'weight_lgbm_class_2': 0.9244737533166916, 'weight_xgb_class_0': 0.05011163149241018, 'weight_xgb_class_1': 0.034208170172045874, 'weight_xgb_class_2': 0.2442281532481648, 'weight_cat_class_0': 0.043040708075667525, 'weight_cat_class_1': 0.8715750815204949, 'weight_cat_class_2': 0.7069659945472415}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,325] Trial 168 finished with value: 0.9494528620125285 and parameters: {'weight_lgbm_class_0': 0.006051624614990689, 'weight_lgbm_class_1': 0.8222774971548339, 'weight_lgbm_class_2': 0.9170941671778848, 'weight_xgb_class_0': 0.05307130920968413, 'weight_xgb_class_1': 0.09781094122392275, 'weight_xgb_class_2': 0.17143728725705926, 'weight_cat_class_0': 0.042871879361504314, 'weight_cat_class_1': 0.7852156772629129, 'weight_cat_class_2': 0.6495195697397164}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,336] Trial 171 finished with value: 0.9485924818857709 and parameters: {'weight_lgbm_class_0': 0.0029446531378436377, 'weight_lgbm_class_1': 0.5468167312203962, 'weight_lgbm_class_2': 0.8856287597564332, 'weight_xgb_class_0': 0.050131016061200386, 'weight_xgb_class_1': 0.030476751463551353, 'weight_xgb_class_2': 0.43376814009396353, 'weight_cat_class_0': 0.03433858822279094, 'weight_cat_class_1': 0.4705711515322473, 'weight_cat_class_2': 0.6658618018071965}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,337] Trial 172 finished with value: 0.917799610916048 and parameters: {'weight_lgbm_class_0': 0.7179818178377924, 'weight_lgbm_class_1': 0.8643816407971348, 'weight_lgbm_class_2': 0.6134246224855012, 'weight_xgb_class_0': 0.06782019128847257, 'weight_xgb_class_1': 0.08826287131523691, 'weight_xgb_class_2': 0.4511115760854622, 'weight_cat_class_0': 0.03705036489613018, 'weight_cat_class_1': 0.5140630848576445, 'weight_cat_class_2': 0.6048591953545837}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:   9%|███████████▊                                                                                                                        | 179/2000 [00:04<00:53, 34.28it/s]

[I 2026-07-03 10:22:40,393] Trial 173 finished with value: 0.9482722265695099 and parameters: {'weight_lgbm_class_0': 0.15578534141872363, 'weight_lgbm_class_1': 0.8996101155220584, 'weight_lgbm_class_2': 0.5914652058482763, 'weight_xgb_class_0': 0.07358428956602071, 'weight_xgb_class_1': 0.08611618962405693, 'weight_xgb_class_2': 0.44455090809893977, 'weight_cat_class_0': 0.04085588645862309, 'weight_cat_class_1': 0.8796827650612163, 'weight_cat_class_2': 0.73013126605079}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,433] Trial 174 finished with value: 0.9495408669858056 and parameters: {'weight_lgbm_class_0': 0.00013584867013545499, 'weight_lgbm_class_1': 0.8414018132500335, 'weight_lgbm_class_2': 0.5393532833513244, 'weight_xgb_class_0': 0.10655388433210969, 'weight_xgb_class_1': 0.04513682821103315, 'weight_xgb_class_2': 0.45202646073312347, 'weight_cat_class_0': 0.0003744554733565268, 'weight_cat_class_1': 0.8658036689755269, 'weight_cat_class_2': 0.7325904093584036}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,462] Trial 175 finished with value: 0.9493911758229565 and parameters: {'weight_lgbm_class_0': 0.0032618815784495464, 'weight_lgbm_class_1': 0.8458190000739696, 'weight_lgbm_class_2': 0.5604192094010633, 'weight_xgb_class_0': 0.10345038466703743, 'weight_xgb_class_1': 0.09278364594089344, 'weight_xgb_class_2': 0.5295341513347098, 'weight_cat_class_0': 0.07158712576302712, 'weight_cat_class_1': 0.8752553830259906, 'weight_cat_class_2': 0.7155125341147799}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,476] Trial 176 finished with value: 0.9465316089225122 and parameters: {'weight_lgbm_class_0': 0.1581358824852176, 'weight_lgbm_class_1': 0.8383728059466771, 'weight_lgbm_class_2': 0.6359665916819418, 'weight_xgb_class_0': 0.10466368572692211, 'weight_xgb_class_1': 0.09117774189741994, 'weight_xgb_class_2': 0.3150045313493238, 'weight_cat_class_0': 0.06981039689534788, 'weight_cat_class_1': 0.8727883247554404, 'weight_cat_class_2': 0.7191919495901917}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,539] Trial 177 finished with value: 0.946685173863246 and parameters: {'weight_lgbm_class_0': 0.16007654005603894, 'weight_lgbm_class_1': 0.8349481606039504, 'weight_lgbm_class_2': 0.5836578865891807, 'weight_xgb_class_0': 0.10760131564810486, 'weight_xgb_class_1': 0.0990787110820947, 'weight_xgb_class_2': 0.604676751046529, 'weight_cat_class_0': 0.07018454898969093, 'weight_cat_class_1': 0.881228963143291, 'weight_cat_class_2': 0.618784422800613}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,571] Trial 178 finished with value: 0.9468160470162744 and parameters: {'weight_lgbm_class_0': 0.16060921309657447, 'weight_lgbm_class_1': 0.867111914751832, 'weight_lgbm_class_2': 0.6182400447395168, 'weight_xgb_class_0': 0.10275799168077393, 'weight_xgb_class_1': 0.10215250791310435, 'weight_xgb_class_2': 0.4421418895509317, 'weight_cat_class_0': 0.07472893485680743, 'weight_cat_class_1': 0.8674056813298414, 'weight_cat_class_2': 0.7436743816461602}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,590] Trial 179 finished with value: 0.9491056658558227 and parameters: {'weight_lgbm_class_0': 0.024812230529958207, 'weight_lgbm_class_1': 0.8431055748973821, 'weight_lgbm_class_2': 0.5899341601549855, 'weight_xgb_class_0': 0.10724681455788104, 'weight_xgb_class_1': 0.0957371685488346, 'weight_xgb_class_2': 0.43211167805732725, 'weight_cat_class_0': 0.07251404967151767, 'weight_cat_class_1': 0.8736630837909864, 'weight_cat_class_2': 0.6178617836814884}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:   9%|████████████▎                                                                                                                       | 187/2000 [00:05<00:49, 36.50it/s]

[I 2026-07-03 10:22:40,608] Trial 180 finished with value: 0.9495972558515944 and parameters: {'weight_lgbm_class_0': 0.025553045054873026, 'weight_lgbm_class_1': 0.8374097607697555, 'weight_lgbm_class_2': 0.5520536127773245, 'weight_xgb_class_0': 0.1059792173600646, 'weight_xgb_class_1': 0.10811018149159737, 'weight_xgb_class_2': 0.16739642719199785, 'weight_cat_class_0': 0.002737803603475912, 'weight_cat_class_1': 0.8879680437340444, 'weight_cat_class_2': 0.7160139458338624}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,636] Trial 181 finished with value: 0.9496363652519523 and parameters: {'weight_lgbm_class_0': 0.026620086042828492, 'weight_lgbm_class_1': 0.8371030051837854, 'weight_lgbm_class_2': 0.5368520344952795, 'weight_xgb_class_0': 0.10944403521123225, 'weight_xgb_class_1': 0.11965545686239834, 'weight_xgb_class_2': 0.5235054085951859, 'weight_cat_class_0': 0.00022318097076676376, 'weight_cat_class_1': 0.870528249405614, 'weight_cat_class_2': 0.71529242096617}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,673] Trial 182 finished with value: 0.949640126573268 and parameters: {'weight_lgbm_class_0': 0.026726433868682512, 'weight_lgbm_class_1': 0.8288607779884621, 'weight_lgbm_class_2': 0.5408239383596479, 'weight_xgb_class_0': 0.10394291650744686, 'weight_xgb_class_1': 0.10834084048962132, 'weight_xgb_class_2': 0.5185861433737969, 'weight_cat_class_0': 0.001918422646240668, 'weight_cat_class_1': 0.841522388169808, 'weight_cat_class_2': 0.7124293222877547}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,681] Trial 183 finished with value: 0.948968864579237 and parameters: {'weight_lgbm_class_0': 0.036740613078489394, 'weight_lgbm_class_1': 0.853337148793246, 'weight_lgbm_class_2': 0.5400803683186395, 'weight_xgb_class_0': 0.10936569293480186, 'weight_xgb_class_1': 0.09864266603354521, 'weight_xgb_class_2': 0.42411952539260755, 'weight_cat_class_0': 0.07015507617906461, 'weight_cat_class_1': 0.8448783283881345, 'weight_cat_class_2': 0.7020646299437651}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,726] Trial 184 finished with value: 0.9496129053194234 and parameters: {'weight_lgbm_class_0': 0.03212008954096453, 'weight_lgbm_class_1': 0.8117322481712186, 'weight_lgbm_class_2': 0.6275370020520749, 'weight_xgb_class_0': 0.10195457821252646, 'weight_xgb_class_1': 0.11349205522290794, 'weight_xgb_class_2': 0.4987267146074499, 'weight_cat_class_0': 0.001685701031115143, 'weight_cat_class_1': 0.8356136438348274, 'weight_cat_class_2': 0.7348956057441838}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,736] Trial 185 finished with value: 0.9492193966360669 and parameters: {'weight_lgbm_class_0': 0.023000959639844963, 'weight_lgbm_class_1': 0.8460301012503335, 'weight_lgbm_class_2': 0.5631025866680223, 'weight_xgb_class_0': 0.10658638679318844, 'weight_xgb_class_1': 0.116044639715532, 'weight_xgb_class_2': 0.5051403190594189, 'weight_cat_class_0': 0.06724291812457528, 'weight_cat_class_1': 0.8406030034620187, 'weight_cat_class_2': 0.725544886237831}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,776] Trial 186 finished with value: 0.9087779319103717 and parameters: {'weight_lgbm_class_0': 0.03523245743919911, 'weight_lgbm_class_1': 0.8464552883813632, 'weight_lgbm_class_2': 0.5599694655498197, 'weight_xgb_class_0': 0.1204731968733373, 'weight_xgb_class_1': 0.11348880761625117, 'weight_xgb_class_2': 0.6542203911316364, 'weight_cat_class_0': 0.997576152942248, 'weight_cat_class_1': 0.8462881220903025, 'weight_cat_class_2': 0.7332506911371963}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,803] Trial 187 finished with value: 0.9495926469383028 and parameters: {'weight_lgbm_class_0': 0.02426276417552838, 'weight_lgbm_class_1': 0.8577662248685857, 'weight_lgbm_class_2': 0.5411466319487965, 'weight_xgb_class_0': 0.11951276087572477, 'weight_xgb_class_1': 0.05474928990141477, 'weight_xgb_class_2': 0.5430763438674773, 'weight_cat_class_0': 0.001052564133271986, 'weight_cat_class_1': 0.8312364755493817, 'weight_cat_class_2': 0.7362606305955459}. Best is trial 155 with value: 0.9497166282745368.

[I 2026-07-03 10:22:40,834] Trial 188 finished with value: 0.9488815417583609 and parameters: {'weight_lgbm_class_0': 0.026039009443205897, 'weight_lgbm_class_1': 0.8110912264939577, 'weight_lgbm_class_2': 0.49430462508416073, 'weight_xgb_class_0': 0.12398192839505726, 'weight_xgb_class_1': 0.024256153014342356, 'weight_xgb_class_2': 0.5017631296170059, 'weight_cat_class_0': 8.498060290979687e-05, 'weight_cat_class_1': 0.24949945865921533, 'weight_cat_class_2': 0.7219902390571632}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,864] Trial 189 finished with value: 0.9490461138576961 and parameters: {'weight_lgbm_class_0': 0.027437213523127474, 'weight_lgbm_class_1': 0.8242564999561011, 'weight_lgbm_class_2': 0.551068940204036, 'weight_xgb_class_0': 0.12267287834397872, 'weight_xgb_class_1': 0.11752546088525814, 'weight_xgb_class_2': 0.5426600575538137, 'weight_cat_class_0': 0.07020860319189919, 'weight_cat_class_1': 0.9028855433171228, 'weight_cat_class_2': 0.7159833102280131}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,886] Trial 190 finished with value: 0.9495664822145375 and parameters: {'weight_lgbm_class_0': 0.02419558142581285, 'weight_lgbm_class_1': 0.8236657962771337, 'weight_lgbm_class_2': 0.4949973483588933, 'weight_xgb_class_0': 0.11741236827984515, 'weight_xgb_class_1': 0.01855603543378917, 'weight_xgb_class_2': 0.40118138197660563, 'weight_cat_class_0': 0.0017044724207423284, 'weight_cat_class_1': 0.8431472633570186, 'weight_cat_class_2': 0.7054593111974676}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,932] Trial 191 finished with value: 0.9496013197576635 and parameters: {'weight_lgbm_class_0': 0.023674632506754115, 'weight_lgbm_class_1': 0.8165140302247845, 'weight_lgbm_class_2': 0.5077960298122156, 'weight_xgb_class_0': 0.12057603830301662, 'weight_xgb_class_1': 0.1233585498874355, 'weight_xgb_class_2': 0.5124578522960668, 'weight_cat_class_0': 0.00287361266197075, 'weight_cat_class_1': 0.8380616513243146, 'weight_cat_class_2': 0.7011881288414364}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,958] Trial 193 finished with value: 0.9496963364882408 and parameters: {'weight_lgbm_class_0': 0.0002656768793335984, 'weight_lgbm_class_1': 0.9643849247498142, 'weight_lgbm_class_2': 0.4983583537519351, 'weight_xgb_class_0': 0.13178886305693227, 'weight_xgb_class_1': 0.11881712411621338, 'weight_xgb_class_2': 0.5152040520593165, 'weight_cat_class_0': 0.002382172984922673, 'weight_cat_class_1': 0.9015298727398584, 'weight_cat_class_2': 0.7081643352052429}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:40,962] Trial 192 finished with value: 0.9496738484061188 and parameters: {'weight_lgbm_class_0': 0.020143084177348475, 'weight_lgbm_class_1': 0.8161620359596776, 'weight_lgbm_class_2': 0.49965551269340613, 'weight_xgb_class_0': 0.12010091408707885, 'weight_xgb_class_1': 0.12081832470251318, 'weight_xgb_class_2': 0.5279905393375771, 'weight_cat_class_0': 0.002225557254339536, 'weight_cat_class_1': 0.8327247879226777, 'weight_cat_class_2': 0.7356125276885265}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,003] Trial 194 finished with value: 0.9496180071382144 and parameters: {'weight_lgbm_class_0': 0.016873884383187966, 'weight_lgbm_class_1': 0.8111057576981567, 'weight_lgbm_class_2': 0.5020941968062718, 'weight_xgb_class_0': 0.1252001818969364, 'weight_xgb_class_1': 0.11213610894654566, 'weight_xgb_class_2': 0.5434345280111653, 'weight_cat_class_0': 0.005492594077853748, 'weight_cat_class_1': 0.8982065728874914, 'weight_cat_class_2': 0.7188835314817389}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,022] Trial 195 finished with value: 0.9496895832037122 and parameters: {'weight_lgbm_class_0': 0.0024104068975533965, 'weight_lgbm_class_1': 0.9360624021449284, 'weight_lgbm_class_2': 0.5603634517037765, 'weight_xgb_class_0': 0.12587023385595744, 'weight_xgb_class_1': 0.11847492499266657, 'weight_xgb_class_2': 0.5226040368546754, 'weight_cat_class_0': 0.0031393355972622744, 'weight_cat_class_1': 0.9008123682648478, 'weight_cat_class_2': 0.6981218258332711}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,050] Trial 196 finished with value: 0.9495142624765256 and parameters: {'weight_lgbm_class_0': 0.017586919106499822, 'weight_lgbm_class_1': 0.8082755337842563, 'weight_lgbm_class_2': 0.5131293399013624, 'weight_xgb_class_0': 0.13604198352977215, 'weight_xgb_class_1': 0.03910019327405538, 'weight_xgb_class_2': 0.5233224537409877, 'weight_cat_class_0': 0.003987649667491959, 'weight_cat_class_1': 0.9025418692627558, 'weight_cat_class_2': 0.7081483867577527}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,057] Trial 197 finished with value: 0.9495167703984193 and parameters: {'weight_lgbm_class_0': 0.015019338525880357, 'weight_lgbm_class_1': 0.8150455418260745, 'weight_lgbm_class_2': 0.499579300710683, 'weight_xgb_class_0': 0.13363618139921332, 'weight_xgb_class_1': 0.024559549914106298, 'weight_xgb_class_2': 0.5205018647387281, 'weight_cat_class_0': 0.00614503312836903, 'weight_cat_class_1': 0.9042117448268177, 'weight_cat_class_2': 0.7029860752038702}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:  10%|█████████████▎                                                                                                                      | 202/2000 [00:05<00:52, 34.09it/s]

[I 2026-07-03 10:22:41,085] Trial 198 finished with value: 0.9496736775584154 and parameters: {'weight_lgbm_class_0': 0.006016822811500097, 'weight_lgbm_class_1': 0.918518905795067, 'weight_lgbm_class_2': 0.4964089764407509, 'weight_xgb_class_0': 0.13104587284341102, 'weight_xgb_class_1': 0.06500777610854347, 'weight_xgb_class_2': 0.5451851456641826, 'weight_cat_class_0': 0.006937546138794054, 'weight_cat_class_1': 0.9053803195489911, 'weight_cat_class_2': 0.7035592049600544}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,167] Trial 199 finished with value: 0.9496674066781732 and parameters: {'weight_lgbm_class_0': 0.0007518546606686354, 'weight_lgbm_class_1': 0.9445081799070649, 'weight_lgbm_class_2': 0.5247261153855538, 'weight_xgb_class_0': 0.12586655475126313, 'weight_xgb_class_1': 0.05533386037337257, 'weight_xgb_class_2': 0.5190907235774719, 'weight_cat_class_0': 0.0031220963612235975, 'weight_cat_class_1': 0.8270193220615444, 'weight_cat_class_2': 0.6989525917295182}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,226] Trial 200 finished with value: 0.949653858526025 and parameters: {'weight_lgbm_class_0': 0.005510989330007688, 'weight_lgbm_class_1': 0.8926751298025395, 'weight_lgbm_class_2': 0.5263710517921985, 'weight_xgb_class_0': 0.13685777171085256, 'weight_xgb_class_1': 0.005656828499321254, 'weight_xgb_class_2': 0.5669528765741242, 'weight_cat_class_0': 0.0004300294539068868, 'weight_cat_class_1': 0.8327816897462625, 'weight_cat_class_2': 0.6994328152558732}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,236] Trial 201 finished with value: 0.9393133752357792 and parameters: {'weight_lgbm_class_0': 0.006000940151394169, 'weight_lgbm_class_1': 0.949654780569128, 'weight_lgbm_class_2': 0.5048485707136515, 'weight_xgb_class_0': 0.49898990630386303, 'weight_xgb_class_1': 0.0008294573671504338, 'weight_xgb_class_2': 0.5695204241853952, 'weight_cat_class_0': 0.004373818399214574, 'weight_cat_class_1': 0.8281425470973479, 'weight_cat_class_2': 0.6901332838946235}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,284] Trial 203 finished with value: 0.949591539487994 and parameters: {'weight_lgbm_class_0': 0.011356665355673166, 'weight_lgbm_class_1': 0.943394261369041, 'weight_lgbm_class_2': 0.5125763969174825, 'weight_xgb_class_0': 0.14556977150609035, 'weight_xgb_class_1': 0.05632823995520796, 'weight_xgb_class_2': 0.54270403407714, 'weight_cat_class_0': 0.007224463570346103, 'weight_cat_class_1': 0.9246350554421344, 'weight_cat_class_2': 0.6858275265604866}. Best is trial 155 with value: 0.9497166282745368.

[I 2026-07-03 10:22:41,285] Trial 202 finished with value: 0.9496930851270866 and parameters: {'weight_lgbm_class_0': 0.0019074895305939282, 'weight_lgbm_class_1': 0.9084154227047438, 'weight_lgbm_class_2': 0.49141875430659965, 'weight_xgb_class_0': 0.12300718701361632, 'weight_xgb_class_1': 0.05247350739143633, 'weight_xgb_class_2': 0.525881494081985, 'weight_cat_class_0': 0.0016472545834178703, 'weight_cat_class_1': 0.8949624984121308, 'weight_cat_class_2': 0.6961980158927203}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,328] Trial 206 finished with value: 0.9496424624626378 and parameters: {'weight_lgbm_class_0': 0.0028066521758002387, 'weight_lgbm_class_1': 0.9757966310967291, 'weight_lgbm_class_2': 0.5097697004476103, 'weight_xgb_class_0': 0.1412812551640978, 'weight_xgb_class_1': 0.006282953886468712, 'weight_xgb_class_2': 0.560377268372848, 'weight_cat_class_0': 0.0014466114231832653, 'weight_cat_class_1': 0.9019418334538336, 'weight_cat_class_2': 0.6768375094573549}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,328] Trial 204 finished with value: 0.9496704004429865 and parameters: {'weight_lgbm_class_0': 0.00018433159439241315, 'weight_lgbm_class_1': 0.9516027674151522, 'weight_lgbm_class_2': 0.5051275501672755, 'weight_xgb_class_0': 0.13617104575110622, 'weight_xgb_class_1': 0.05336940062267395, 'weight_xgb_class_2': 0.5717676166314142, 'weight_cat_class_0': 0.008613778933136427, 'weight_cat_class_1': 0.8962996988599334, 'weight_cat_class_2': 0.6938866274435396}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,334] Trial 205 finished with value: 0.9496569948013184 and parameters: {'weight_lgbm_class_0': 0.010919240408293469, 'weight_lgbm_class_1': 0.9081481841455961, 'weight_lgbm_class_2': 0.5111131344660921, 'weight_xgb_class_0': 0.13445843071472643, 'weight_xgb_class_1': 0.0592767182853399, 'weight_xgb_class_2': 0.5315464953746389, 'weight_cat_class_0': 0.007614475708365923, 'weight_cat_class_1': 0.9391911203356956, 'weight_cat_class_2': 0.6889448650646506}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,384] Trial 207 finished with value: 0.949625654249723 and parameters: {'weight_lgbm_class_0': 0.002165128911353925, 'weight_lgbm_class_1': 0.9941879426040737, 'weight_lgbm_class_2': 0.5022660920147234, 'weight_xgb_class_0': 0.14093112155690618, 'weight_xgb_class_1': 0.05127554629483952, 'weight_xgb_class_2': 0.5708336014889561, 'weight_cat_class_0': 0.0014072680725415454, 'weight_cat_class_1': 0.8982141216503667, 'weight_cat_class_2': 0.677906527835965}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,405] Trial 209 finished with value: 0.949693732097844 and parameters: {'weight_lgbm_class_0': 0.0005410024503811977, 'weight_lgbm_class_1': 0.990307209686974, 'weight_lgbm_class_2': 0.5123799852711787, 'weight_xgb_class_0': 0.1327484238394234, 'weight_xgb_class_1': 0.05466108959825283, 'weight_xgb_class_2': 0.5680210020218066, 'weight_cat_class_0': 0.00163655690449989, 'weight_cat_class_1': 0.9260017123664346, 'weight_cat_class_2': 0.6748818411292024}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,422] Trial 208 finished with value: 0.9496316296077918 and parameters: {'weight_lgbm_class_0': 0.0011359744138360536, 'weight_lgbm_class_1': 0.9620918161872627, 'weight_lgbm_class_2': 0.4932661491230519, 'weight_xgb_class_0': 0.13987398090519426, 'weight_xgb_class_1': 0.005048426293599861, 'weight_xgb_class_2': 0.5686795060289461, 'weight_cat_class_0': 0.008357547656039488, 'weight_cat_class_1': 0.9409373621487125, 'weight_cat_class_2': 0.6814073608754149}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,456] Trial 210 finished with value: 0.9496751133603186 and parameters: {'weight_lgbm_class_0': 0.00912647818777033, 'weight_lgbm_class_1': 0.9712711474961916, 'weight_lgbm_class_2': 0.5083618329062509, 'weight_xgb_class_0': 0.13298413818566485, 'weight_xgb_class_1': 0.010154631833409488, 'weight_xgb_class_2': 0.5784353123800434, 'weight_cat_class_0': 0.0027296354975589777, 'weight_cat_class_1': 0.8967392542383893, 'weight_cat_class_2': 0.68477883433204}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,488] Trial 211 finished with value: 0.9496386257418691 and parameters: {'weight_lgbm_class_0': 0.013292634229303612, 'weight_lgbm_class_1': 0.9726258850151958, 'weight_lgbm_class_2': 0.5019398629905342, 'weight_xgb_class_0': 0.13824337045298238, 'weight_xgb_class_1': 0.05066304823422324, 'weight_xgb_class_2': 0.5659336741549621, 'weight_cat_class_0': 0.0017902019855320656, 'weight_cat_class_1': 0.9296529432778259, 'weight_cat_class_2': 0.6908634084745662}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:  11%|██████████████▍                                                                                                                     | 219/2000 [00:05<00:50, 35.15it/s]

[I 2026-07-03 10:22:41,509] Trial 212 finished with value: 0.9496339020844183 and parameters: {'weight_lgbm_class_0': 0.001827705267105375, 'weight_lgbm_class_1': 0.9702039513249833, 'weight_lgbm_class_2': 0.5202205636999923, 'weight_xgb_class_0': 0.14066985925265568, 'weight_xgb_class_1': 0.05571285252211771, 'weight_xgb_class_2': 0.5249600376206357, 'weight_cat_class_0': 0.0002916669425517852, 'weight_cat_class_1': 0.9309485523387583, 'weight_cat_class_2': 0.6797072916911553}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,544] Trial 213 finished with value: 0.9496169886083049 and parameters: {'weight_lgbm_class_0': 0.015889504833520984, 'weight_lgbm_class_1': 0.9714279657660247, 'weight_lgbm_class_2': 0.47437417447992736, 'weight_xgb_class_0': 0.1371165526529532, 'weight_xgb_class_1': 0.04196549030244742, 'weight_xgb_class_2': 0.5251688440943425, 'weight_cat_class_0': 0.0002841118597211472, 'weight_cat_class_1': 0.927179895213955, 'weight_cat_class_2': 0.6796488407241522}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,606] Trial 214 finished with value: 0.9492390796163434 and parameters: {'weight_lgbm_class_0': 0.02895358195984074, 'weight_lgbm_class_1': 0.9749946133090112, 'weight_lgbm_class_2': 0.47362629574029885, 'weight_xgb_class_0': 0.16456655016773447, 'weight_xgb_class_1': 0.0534573684233411, 'weight_xgb_class_2': 0.5654150911775596, 'weight_cat_class_0': 0.004002720181252797, 'weight_cat_class_1': 0.9318445840126889, 'weight_cat_class_2': 0.6765619958661431}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,627] Trial 215 finished with value: 0.9492213017658088 and parameters: {'weight_lgbm_class_0': 0.027096515612039976, 'weight_lgbm_class_1': 0.9896573609662209, 'weight_lgbm_class_2': 0.4694964903254608, 'weight_xgb_class_0': 0.1692463185372554, 'weight_xgb_class_1': 0.06269033492363238, 'weight_xgb_class_2': 0.565633624625342, 'weight_cat_class_0': 0.00024019561616817325, 'weight_cat_class_1': 0.9379650075012546, 'weight_cat_class_2': 0.6782190510044966}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,680] Trial 216 finished with value: 0.9492176852295314 and parameters: {'weight_lgbm_class_0': 0.026410838359845527, 'weight_lgbm_class_1': 0.9940453834234914, 'weight_lgbm_class_2': 0.47237319578131487, 'weight_xgb_class_0': 0.1667883877904915, 'weight_xgb_class_1': 0.0573890423916742, 'weight_xgb_class_2': 0.5618712079989127, 'weight_cat_class_0': 0.0021473320552183295, 'weight_cat_class_1': 0.9340126872058259, 'weight_cat_class_2': 0.6782189448200903}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,691] Trial 218 finished with value: 0.949440604897525 and parameters: {'weight_lgbm_class_0': 0.00013650200856787226, 'weight_lgbm_class_1': 0.9979337068127823, 'weight_lgbm_class_2': 0.4744857883914474, 'weight_xgb_class_0': 0.16883818330003159, 'weight_xgb_class_1': 0.052304996420042715, 'weight_xgb_class_2': 0.5572182744312526, 'weight_cat_class_0': 0.00104057003855456, 'weight_cat_class_1': 0.9345062120409507, 'weight_cat_class_2': 0.6784355327311482}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,696] Trial 217 finished with value: 0.9491818978919895 and parameters: {'weight_lgbm_class_0': 0.028800006557722795, 'weight_lgbm_class_1': 0.9827614982195176, 'weight_lgbm_class_2': 0.46925062224493297, 'weight_xgb_class_0': 0.17164518866437906, 'weight_xgb_class_1': 0.05342172049596113, 'weight_xgb_class_2': 0.5683929345331258, 'weight_cat_class_0': 0.0007780974709044794, 'weight_cat_class_1': 0.9235193067976583, 'weight_cat_class_2': 0.6753593825975923}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:  11%|██████████████▉                                                                                                                     | 226/2000 [00:06<00:53, 33.36it/s]

[I 2026-07-03 10:22:41,772] Trial 219 finished with value: 0.9490575549143482 and parameters: {'weight_lgbm_class_0': 0.03164505166683349, 'weight_lgbm_class_1': 0.9983741538121778, 'weight_lgbm_class_2': 0.4523315198812553, 'weight_xgb_class_0': 0.1769979760387676, 'weight_xgb_class_1': 1.4291652158745886e-05, 'weight_xgb_class_2': 0.5662738924847985, 'weight_cat_class_0': 0.0015014676546489258, 'weight_cat_class_1': 0.937197085249673, 'weight_cat_class_2': 0.677954985846529}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,775] Trial 220 finished with value: 0.9494172139804204 and parameters: {'weight_lgbm_class_0': 0.0016277059161840524, 'weight_lgbm_class_1': 0.9852355160482195, 'weight_lgbm_class_2': 0.45617272898991634, 'weight_xgb_class_0': 0.16592155484555982, 'weight_xgb_class_1': 0.06236534184775555, 'weight_xgb_class_2': 0.569367222624582, 'weight_cat_class_0': 0.0033604985539054987, 'weight_cat_class_1': 0.9336805746461432, 'weight_cat_class_2': 0.6762133573268339}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,802] Trial 221 finished with value: 0.9491980801004002 and parameters: {'weight_lgbm_class_0': 0.030978930647748294, 'weight_lgbm_class_1': 0.9931106915019262, 'weight_lgbm_class_2': 0.47003272737020696, 'weight_xgb_class_0': 0.1680371530210664, 'weight_xgb_class_1': 0.008872007351247121, 'weight_xgb_class_2': 0.5660186854668987, 'weight_cat_class_0': 0.000776864934816341, 'weight_cat_class_1': 0.9347552228608045, 'weight_cat_class_2': 0.6771668508538736}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,842] Trial 222 finished with value: 0.9493653545267134 and parameters: {'weight_lgbm_class_0': 0.006419475047345849, 'weight_lgbm_class_1': 0.9814758297434754, 'weight_lgbm_class_2': 0.4703857232709975, 'weight_xgb_class_0': 0.16844520187902917, 'weight_xgb_class_1': 0.0018301619143328701, 'weight_xgb_class_2': 0.5795547768129046, 'weight_cat_class_0': 0.0008171331037231675, 'weight_cat_class_1': 0.9356848398840292, 'weight_cat_class_2': 0.6777735216775239}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,857] Trial 223 finished with value: 0.9493207863180707 and parameters: {'weight_lgbm_class_0': 0.0014506451135948145, 'weight_lgbm_class_1': 0.9805509413429009, 'weight_lgbm_class_2': 0.46082874552656533, 'weight_xgb_class_0': 0.1714333085013184, 'weight_xgb_class_1': 0.06446394238639881, 'weight_xgb_class_2': 0.573334175767043, 'weight_cat_class_0': 0.0027756371956317995, 'weight_cat_class_1': 0.9301428148288146, 'weight_cat_class_2': 0.6703817227060487}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,873] Trial 224 finished with value: 0.9494004952018881 and parameters: {'weight_lgbm_class_0': 0.0002408953196112243, 'weight_lgbm_class_1': 0.9905644407349968, 'weight_lgbm_class_2': 0.4757562205766234, 'weight_xgb_class_0': 0.17097352767500393, 'weight_xgb_class_1': 0.00652013360428335, 'weight_xgb_class_2': 0.5675450274516008, 'weight_cat_class_0': 0.0020310181660221664, 'weight_cat_class_1': 0.9413662104008599, 'weight_cat_class_2': 0.6754261806777341}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,931] Trial 225 finished with value: 0.9492429765168154 and parameters: {'weight_lgbm_class_0': 0.0010056024795108182, 'weight_lgbm_class_1': 0.9986450324136411, 'weight_lgbm_class_2': 0.42534928244340137, 'weight_xgb_class_0': 0.1759087906015736, 'weight_xgb_class_1': 0.0043566857506797734, 'weight_xgb_class_2': 0.5911030496849962, 'weight_cat_class_0': 0.01685603182821686, 'weight_cat_class_1': 0.9418616598349948, 'weight_cat_class_2': 0.6783975089870026}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,956] Trial 227 finished with value: 0.9490607207116852 and parameters: {'weight_lgbm_class_0': 9.375717212500509e-05, 'weight_lgbm_class_1': 0.9174145756764577, 'weight_lgbm_class_2': 0.44460401699131324, 'weight_xgb_class_0': 0.18565384115382472, 'weight_xgb_class_1': 0.003084436665894993, 'weight_xgb_class_2': 0.5785668122503289, 'weight_cat_class_0': 0.020551182381854768, 'weight_cat_class_1': 0.9398989746319267, 'weight_cat_class_2': 0.6765914327633028}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:  12%|███████████████▍                                                                                                                    | 233/2000 [00:06<00:51, 34.19it/s]

[I 2026-07-03 10:22:41,963] Trial 226 finished with value: 0.9484332253685848 and parameters: {'weight_lgbm_class_0': 0.0009709179949035154, 'weight_lgbm_class_1': 0.919609944422408, 'weight_lgbm_class_2': 0.4294710990749531, 'weight_xgb_class_0': 0.20762134042681346, 'weight_xgb_class_1': 0.002880392863252411, 'weight_xgb_class_2': 0.5938552379916869, 'weight_cat_class_0': 0.039072603920407754, 'weight_cat_class_1': 0.935982949219089, 'weight_cat_class_2': 0.6765843658673772}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,982] Trial 228 finished with value: 0.9484769918342021 and parameters: {'weight_lgbm_class_0': 0.000586198198843142, 'weight_lgbm_class_1': 0.9175244244429079, 'weight_lgbm_class_2': 0.43025456381847754, 'weight_xgb_class_0': 0.19924693341610789, 'weight_xgb_class_1': 0.0008784217838584338, 'weight_xgb_class_2': 0.5985322251730685, 'weight_cat_class_0': 0.03900277585663982, 'weight_cat_class_1': 0.9593885984610175, 'weight_cat_class_2': 0.5836010932560367}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:41,999] Trial 229 finished with value: 0.9485908683579664 and parameters: {'weight_lgbm_class_0': 0.008580104975090569, 'weight_lgbm_class_1': 0.9246300386481834, 'weight_lgbm_class_2': 0.42697051700093075, 'weight_xgb_class_0': 0.18841853858089036, 'weight_xgb_class_1': 0.0026958652031826083, 'weight_xgb_class_2': 0.5996513205376676, 'weight_cat_class_0': 0.03672303401558069, 'weight_cat_class_1': 0.97089827036604, 'weight_cat_class_2': 0.5853633685404528}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,046] Trial 230 finished with value: 0.9485408958152638 and parameters: {'weight_lgbm_class_0': 0.001041096843205001, 'weight_lgbm_class_1': 0.9204606396701457, 'weight_lgbm_class_2': 0.4237145022428101, 'weight_xgb_class_0': 0.2075107415687911, 'weight_xgb_class_1': 0.010787809852939437, 'weight_xgb_class_2': 0.6015818037640699, 'weight_cat_class_0': 0.03391798747106093, 'weight_cat_class_1': 0.9610503133382539, 'weight_cat_class_2': 0.6891053596160489}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,117] Trial 231 finished with value: 0.9493411806895341 and parameters: {'weight_lgbm_class_0': 3.4437174136127185e-05, 'weight_lgbm_class_1': 0.9223335838363871, 'weight_lgbm_class_2': 0.4265156012552498, 'weight_xgb_class_0': 0.14061651072188303, 'weight_xgb_class_1': 0.020509570922871624, 'weight_xgb_class_2': 0.6047927591804023, 'weight_cat_class_0': 0.034923096437416506, 'weight_cat_class_1': 0.976858192610136, 'weight_cat_class_2': 0.6575299019997651}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,130] Trial 232 finished with value: 0.9493386199304478 and parameters: {'weight_lgbm_class_0': 0.004424820448552125, 'weight_lgbm_class_1': 0.9206311359390486, 'weight_lgbm_class_2': 0.43270110330835887, 'weight_xgb_class_0': 0.13887277501554895, 'weight_xgb_class_1': 0.027237632640565772, 'weight_xgb_class_2': 0.6007926785170823, 'weight_cat_class_0': 0.03569127135438349, 'weight_cat_class_1': 0.9713349806042955, 'weight_cat_class_2': 0.6535271518156175}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,132] Trial 233 finished with value: 0.949337828174652 and parameters: {'weight_lgbm_class_0': 0.004525699006011432, 'weight_lgbm_class_1': 0.9118440504770626, 'weight_lgbm_class_2': 0.41130746522044737, 'weight_xgb_class_0': 0.13949948929453926, 'weight_xgb_class_1': 0.027619007635709625, 'weight_xgb_class_2': 0.6077185224627255, 'weight_cat_class_0': 0.032601635983800586, 'weight_cat_class_1': 0.9664616120798997, 'weight_cat_class_2': 0.6572985893534365}. Best is trial 155 with value: 0.9497166282745368.

[I 2026-07-03 10:22:42,203] Trial 234 finished with value: 0.9484680525827791 and parameters: {'weight_lgbm_class_0': 0.016671615750636172, 'weight_lgbm_class_1': 0.9241332690122933, 'weight_lgbm_class_2': 0.5220137776004635, 'weight_xgb_class_0': 0.20211064166095746, 'weight_xgb_class_1': 0.027984746452914863, 'weight_xgb_class_2': 0.49464899471128715, 'weight_cat_class_0': 0.037699084540292555, 'weight_cat_class_1': 0.9687240294223111, 'weight_cat_class_2': 0.7534369833167792}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,208] Trial 235 finished with value: 0.9486973328043028 and parameters: {'weight_lgbm_class_0': 0.00041985931391826103, 'weight_lgbm_class_1': 0.925646434443276, 'weight_lgbm_class_2': 0.42528985917264533, 'weight_xgb_class_0': 0.19982479812882997, 'weight_xgb_class_1': 0.03566813159334027, 'weight_xgb_class_2': 0.6065740138304723, 'weight_cat_class_0': 0.0334544952213942, 'weight_cat_class_1': 0.9672702849985569, 'weight_cat_class_2': 0.6533961187585824}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,209] Trial 236 finished with value: 0.9482080381765537 and parameters: {'weight_lgbm_class_0': 0.03793200426245914, 'weight_lgbm_class_1': 0.922125553369358, 'weight_lgbm_class_2': 0.5230385036226413, 'weight_xgb_class_0': 0.20805297733488148, 'weight_xgb_class_1': 0.0295233113807697, 'weight_xgb_class_2': 0.6222467268014226, 'weight_cat_class_0': 0.0372975892117631, 'weight_cat_class_1': 0.9749414292740539, 'weight_cat_class_2': 0.7551090930745905}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,283] Trial 237 finished with value: 0.9490759030075443 and parameters: {'weight_lgbm_class_0': 0.039326873685393525, 'weight_lgbm_class_1': 0.9554736991698672, 'weight_lgbm_class_2': 0.5216915342240701, 'weight_xgb_class_0': 0.14088530878549876, 'weight_xgb_class_1': 0.03131809844103094, 'weight_xgb_class_2': 0.6099143416549463, 'weight_cat_class_0': 0.03895904241061568, 'weight_cat_class_1': 0.9666505783313947, 'weight_cat_class_2': 0.6506490666050083}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,300] Trial 239 finished with value: 0.9491842332958353 and parameters: {'weight_lgbm_class_0': 0.039357870409699805, 'weight_lgbm_class_1': 0.9538172537616036, 'weight_lgbm_class_2': 0.5223072226694865, 'weight_xgb_class_0': 0.13957932502592768, 'weight_xgb_class_1': 0.02833798651960082, 'weight_xgb_class_2': 0.6258654180804091, 'weight_cat_class_0': 0.02730565804910538, 'weight_cat_class_1': 0.8961731877141047, 'weight_cat_class_2': 0.7531389466860552}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,340] Trial 238 finished with value: 0.9491854035831327 and parameters: {'weight_lgbm_class_0': 0.039114666211661465, 'weight_lgbm_class_1': 0.955406694090418, 'weight_lgbm_class_2': 0.520284136368759, 'weight_xgb_class_0': 0.14190368373764345, 'weight_xgb_class_1': 0.027370434517746074, 'weight_xgb_class_2': 0.6212877163557698, 'weight_cat_class_0': 0.02664756352477413, 'weight_cat_class_1': 0.8994232523311216, 'weight_cat_class_2': 0.7501312558096638}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,346] Trial 240 finished with value: 0.9493316515578393 and parameters: {'weight_lgbm_class_0': 0.03505924612277732, 'weight_lgbm_class_1': 0.959823713592768, 'weight_lgbm_class_2': 0.5263441793004484, 'weight_xgb_class_0': 0.131293086242421, 'weight_xgb_class_1': 0.02593478270250368, 'weight_xgb_class_2': 0.5056552544124892, 'weight_cat_class_0': 0.024558149363434662, 'weight_cat_class_1': 0.8965528784406545, 'weight_cat_class_2': 0.7561577048997701}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,364] Trial 241 finished with value: 0.949208526163778 and parameters: {'weight_lgbm_class_0': 0.037257752356906884, 'weight_lgbm_class_1': 0.9526938001679321, 'weight_lgbm_class_2': 0.5240240218346314, 'weight_xgb_class_0': 0.14285820295352647, 'weight_xgb_class_1': 0.03259679926108899, 'weight_xgb_class_2': 0.6259317687488135, 'weight_cat_class_0': 0.02438771006116589, 'weight_cat_class_1': 0.8922629681556279, 'weight_cat_class_2': 0.7511237393009393}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:  12%|████████████████▎                                                                                                                   | 248/2000 [00:06<00:51, 34.35it/s]

[I 2026-07-03 10:22:42,385] Trial 242 finished with value: 0.9491884046494309 and parameters: {'weight_lgbm_class_0': 0.043383722739946354, 'weight_lgbm_class_1': 0.8892577674059238, 'weight_lgbm_class_2': 0.5223762720646296, 'weight_xgb_class_0': 0.13188346747972665, 'weight_xgb_class_1': 0.02882991277522237, 'weight_xgb_class_2': 0.5030492299526454, 'weight_cat_class_0': 0.022017998594878217, 'weight_cat_class_1': 0.893619739014089, 'weight_cat_class_2': 0.7536852188070806}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,454] Trial 243 finished with value: 0.9493485890276528 and parameters: {'weight_lgbm_class_0': 0.035793384494621744, 'weight_lgbm_class_1': 0.9573414987655074, 'weight_lgbm_class_2': 0.5242230904979408, 'weight_xgb_class_0': 0.1305880605086657, 'weight_xgb_class_1': 0.07679225652414035, 'weight_xgb_class_2': 0.5025468942415191, 'weight_cat_class_0': 0.020536119888782393, 'weight_cat_class_1': 0.8899735580223058, 'weight_cat_class_2': 0.7472534910522121}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,464] Trial 244 finished with value: 0.9493465213101744 and parameters: {'weight_lgbm_class_0': 0.03753932506434323, 'weight_lgbm_class_1': 0.9571208492236916, 'weight_lgbm_class_2': 0.5233778630711343, 'weight_xgb_class_0': 0.1336429445282994, 'weight_xgb_class_1': 0.12399518929550504, 'weight_xgb_class_2': 0.5089962035093545, 'weight_cat_class_0': 0.019592541369678623, 'weight_cat_class_1': 0.8991817734332547, 'weight_cat_class_2': 0.7517795513305966}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,517] Trial 245 finished with value: 0.9493419665342588 and parameters: {'weight_lgbm_class_0': 0.03856581363768094, 'weight_lgbm_class_1': 0.9576566583898156, 'weight_lgbm_class_2': 0.4941930179359194, 'weight_xgb_class_0': 0.13082377341223278, 'weight_xgb_class_1': 0.11808549034078235, 'weight_xgb_class_2': 0.5178862606705512, 'weight_cat_class_0': 0.016332427071494744, 'weight_cat_class_1': 0.8977622939298936, 'weight_cat_class_2': 0.7030625514911785}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,561] Trial 246 finished with value: 0.949350526706885 and parameters: {'weight_lgbm_class_0': 0.03561795744940167, 'weight_lgbm_class_1': 0.945749230394557, 'weight_lgbm_class_2': 0.49561184570994754, 'weight_xgb_class_0': 0.127987658299957, 'weight_xgb_class_1': 0.0776099094688073, 'weight_xgb_class_2': 0.5157206287637798, 'weight_cat_class_0': 0.01751177828303802, 'weight_cat_class_1': 0.8892554292598462, 'weight_cat_class_2': 0.7040148651494125}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,579] Trial 248 finished with value: 0.9493693106894326 and parameters: {'weight_lgbm_class_0': 0.036440898611918245, 'weight_lgbm_class_1': 0.8817821793954629, 'weight_lgbm_class_2': 0.4940790550172644, 'weight_xgb_class_0': 0.12682601757446307, 'weight_xgb_class_1': 0.07615920109444303, 'weight_xgb_class_2': 0.5124777355906678, 'weight_cat_class_0': 0.019285045517902923, 'weight_cat_class_1': 0.8921880157592968, 'weight_cat_class_2': 0.7041894847835646}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,579] Trial 247 finished with value: 0.9492606699265825 and parameters: {'weight_lgbm_class_0': 0.03764783634863593, 'weight_lgbm_class_1': 0.9590557334342127, 'weight_lgbm_class_2': 0.49158533443797664, 'weight_xgb_class_0': 0.13124550530068624, 'weight_xgb_class_1': 0.07679078915702882, 'weight_xgb_class_2': 0.5153993867670377, 'weight_cat_class_0': 0.02233963276725661, 'weight_cat_class_1': 0.8941841950537683, 'weight_cat_class_2': 0.7037807594130538}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:  13%|████████████████▊                                                                                                                   | 255/2000 [00:06<00:52, 33.53it/s]

[I 2026-07-03 10:22:42,603] Trial 249 finished with value: 0.949355883875918 and parameters: {'weight_lgbm_class_0': 0.038275223589604654, 'weight_lgbm_class_1': 0.8927266938716627, 'weight_lgbm_class_2': 0.4951018875989681, 'weight_xgb_class_0': 0.1256807334632158, 'weight_xgb_class_1': 0.07695618284554134, 'weight_xgb_class_2': 0.5147720259185198, 'weight_cat_class_0': 0.021284648304179248, 'weight_cat_class_1': 0.8946335769119885, 'weight_cat_class_2': 0.7008604484533667}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,652] Trial 250 finished with value: 0.9495235655126577 and parameters: {'weight_lgbm_class_0': 0.025184529944562654, 'weight_lgbm_class_1': 0.888383755717165, 'weight_lgbm_class_2': 0.49382137407832893, 'weight_xgb_class_0': 0.12090020660732662, 'weight_xgb_class_1': 0.12341969950936145, 'weight_xgb_class_2': 0.5196330361005, 'weight_cat_class_0': 0.01882237366836863, 'weight_cat_class_1': 0.8948986854823328, 'weight_cat_class_2': 0.7044742662062997}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,672] Trial 251 finished with value: 0.9495748040582722 and parameters: {'weight_lgbm_class_0': 0.024714018726169337, 'weight_lgbm_class_1': 0.8779507532701079, 'weight_lgbm_class_2': 0.49227247413470354, 'weight_xgb_class_0': 0.11985082524181963, 'weight_xgb_class_1': 0.07289266454744564, 'weight_xgb_class_2': 0.5420994688537256, 'weight_cat_class_0': 0.01571566377380204, 'weight_cat_class_1': 0.9128766934088777, 'weight_cat_class_2': 0.7015190768421371}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,745] Trial 252 finished with value: 0.949544680925689 and parameters: {'weight_lgbm_class_0': 0.02289042683637122, 'weight_lgbm_class_1': 0.8770332799095587, 'weight_lgbm_class_2': 0.4889753599862753, 'weight_xgb_class_0': 0.12252962521566392, 'weight_xgb_class_1': 0.07549519944362432, 'weight_xgb_class_2': 0.5363685438376133, 'weight_cat_class_0': 0.016508017897985193, 'weight_cat_class_1': 0.9136188722945707, 'weight_cat_class_2': 0.7288237584939674}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,745] Trial 253 finished with value: 0.9496464787022635 and parameters: {'weight_lgbm_class_0': 0.02215695558614319, 'weight_lgbm_class_1': 0.8731193943988219, 'weight_lgbm_class_2': 0.4999225782314275, 'weight_xgb_class_0': 0.1176572876485511, 'weight_xgb_class_1': 0.12492716816491717, 'weight_xgb_class_2': 0.5390306332167298, 'weight_cat_class_0': 0.016445020552580077, 'weight_cat_class_1': 0.9128467723227502, 'weight_cat_class_2': 0.708905051364542}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,759] Trial 254 finished with value: 0.9495884612206421 and parameters: {'weight_lgbm_class_0': 0.023402657612071987, 'weight_lgbm_class_1': 0.9711698650578023, 'weight_lgbm_class_2': 0.49663845150477703, 'weight_xgb_class_0': 0.12275314657962728, 'weight_xgb_class_1': 0.07609415858703056, 'weight_xgb_class_2': 0.5315992497518108, 'weight_cat_class_0': 0.016879694167721768, 'weight_cat_class_1': 0.915289037165565, 'weight_cat_class_2': 0.7018375453686493}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,818] Trial 256 finished with value: 0.9496998476174974 and parameters: {'weight_lgbm_class_0': 0.020218758492407573, 'weight_lgbm_class_1': 0.969617848900966, 'weight_lgbm_class_2': 0.5690136305476708, 'weight_xgb_class_0': 0.1142059134071376, 'weight_xgb_class_1': 0.07630145924329067, 'weight_xgb_class_2': 0.5380030310408322, 'weight_cat_class_0': 0.0005614782620013184, 'weight_cat_class_1': 0.9153071793664812, 'weight_cat_class_2': 0.7203791843028464}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:  13%|█████████████████▎                                                                                                                  | 262/2000 [00:07<00:53, 32.25it/s]

[I 2026-07-03 10:22:42,830] Trial 257 finished with value: 0.9496713976364815 and parameters: {'weight_lgbm_class_0': 0.022874028311471215, 'weight_lgbm_class_1': 0.8852767395258972, 'weight_lgbm_class_2': 0.5513507013563903, 'weight_xgb_class_0': 0.11901071586560084, 'weight_xgb_class_1': 0.07755523435190523, 'weight_xgb_class_2': 0.5379694300197533, 'weight_cat_class_0': 0.0013261832171649365, 'weight_cat_class_1': 0.8524756431280558, 'weight_cat_class_2': 0.7224154013725149}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,842] Trial 255 finished with value: 0.9495898400348567 and parameters: {'weight_lgbm_class_0': 0.02099790487475022, 'weight_lgbm_class_1': 0.8828813874633118, 'weight_lgbm_class_2': 0.5494958769986192, 'weight_xgb_class_0': 0.11891672976398966, 'weight_xgb_class_1': 0.07171386119223441, 'weight_xgb_class_2': 0.5388370607806325, 'weight_cat_class_0': 0.01622862087725408, 'weight_cat_class_1': 0.9132981833526232, 'weight_cat_class_2': 0.7141413035189118}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,910] Trial 258 finished with value: 0.949640842312831 and parameters: {'weight_lgbm_class_0': 0.01911934107009343, 'weight_lgbm_class_1': 0.8961257389505903, 'weight_lgbm_class_2': 0.5529342124644281, 'weight_xgb_class_0': 0.10091147347017357, 'weight_xgb_class_1': 0.11693455848566497, 'weight_xgb_class_2': 0.5350242053316012, 'weight_cat_class_0': 0.0035982842045347006, 'weight_cat_class_1': 0.8531076231810396, 'weight_cat_class_2': 0.7269468983610803}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,956] Trial 259 finished with value: 0.9496098128115489 and parameters: {'weight_lgbm_class_0': 0.01871946282970609, 'weight_lgbm_class_1': 0.8773251992515391, 'weight_lgbm_class_2': 0.5485626753992544, 'weight_xgb_class_0': 0.10230621294173685, 'weight_xgb_class_1': 0.11456406844760698, 'weight_xgb_class_2': 0.5324132355433804, 'weight_cat_class_0': 6.534441753948406e-06, 'weight_cat_class_1': 0.8268354939712266, 'weight_cat_class_2': 0.7189119747904816}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,973] Trial 260 finished with value: 0.9494434243426899 and parameters: {'weight_lgbm_class_0': 0.022706923503455004, 'weight_lgbm_class_1': 0.8777297087727028, 'weight_lgbm_class_2': 0.5520650827059645, 'weight_xgb_class_0': 0.1536604946235409, 'weight_xgb_class_1': 0.11918728073913697, 'weight_xgb_class_2': 0.5370246594600812, 'weight_cat_class_0': 0.00406092157700395, 'weight_cat_class_1': 0.9149647108437178, 'weight_cat_class_2': 0.725740241997189}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,994] Trial 263 finished with value: 0.9493723402575217 and parameters: {'weight_lgbm_class_0': 0.01803830992260899, 'weight_lgbm_class_1': 0.7887863166153061, 'weight_lgbm_class_2': 0.5487116456178117, 'weight_xgb_class_0': 0.1538546732904516, 'weight_xgb_class_1': 0.05285645469894197, 'weight_xgb_class_2': 0.5448361607126726, 'weight_cat_class_0': 0.00033087184343670497, 'weight_cat_class_1': 0.7886258294723683, 'weight_cat_class_2': 0.726808736165064}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:42,995] Trial 261 finished with value: 0.9493760410289734 and parameters: {'weight_lgbm_class_0': 0.020096450503551466, 'weight_lgbm_class_1': 0.7811510114412267, 'weight_lgbm_class_2': 0.5694218195412308, 'weight_xgb_class_0': 0.1533443801692147, 'weight_xgb_class_1': 0.05463344448300535, 'weight_xgb_class_2': 0.5386900613728572, 'weight_cat_class_0': 0.0013603495420460964, 'weight_cat_class_1': 0.8487626120894903, 'weight_cat_class_2': 0.7275169018735532}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:  14%|█████████████████▊                                                                                                                  | 270/2000 [00:07<00:49, 34.63it/s]

[I 2026-07-03 10:22:43,004] Trial 262 finished with value: 0.9495248430910932 and parameters: {'weight_lgbm_class_0': 0.01862268700290101, 'weight_lgbm_class_1': 0.7807882645753015, 'weight_lgbm_class_2': 0.5492730455729858, 'weight_xgb_class_0': 0.10611572561338921, 'weight_xgb_class_1': 0.04989554293740787, 'weight_xgb_class_2': 0.5359486143154945, 'weight_cat_class_0': 0.000310265323424019, 'weight_cat_class_1': 0.8295615484952477, 'weight_cat_class_2': 0.7283552984233923}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,072] Trial 265 finished with value: 0.94907008103133 and parameters: {'weight_lgbm_class_0': 0.06389761461558713, 'weight_lgbm_class_1': 0.7925410519283209, 'weight_lgbm_class_2': 0.5682379808664046, 'weight_xgb_class_0': 0.09760464733111412, 'weight_xgb_class_1': 0.108151586457767, 'weight_xgb_class_2': 0.47710251001890003, 'weight_cat_class_0': 0.04836149898278943, 'weight_cat_class_1': 0.8478005151530801, 'weight_cat_class_2': 0.7285825823262123}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,079] Trial 264 finished with value: 0.9484065183281946 and parameters: {'weight_lgbm_class_0': 0.06175450080679828, 'weight_lgbm_class_1': 0.9411927457497614, 'weight_lgbm_class_2': 0.5585303851987693, 'weight_xgb_class_0': 0.15395642723909486, 'weight_xgb_class_1': 0.11283666274922981, 'weight_xgb_class_2': 0.4801038244767174, 'weight_cat_class_0': 0.048979448932395975, 'weight_cat_class_1': 0.8506612130810107, 'weight_cat_class_2': 0.7234668390687947}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,122] Trial 266 finished with value: 0.9230431372963581 and parameters: {'weight_lgbm_class_0': 0.0653607009943449, 'weight_lgbm_class_1': 0.796529647035176, 'weight_lgbm_class_2': 0.5680402314109709, 'weight_xgb_class_0': 0.14775257722360421, 'weight_xgb_class_1': 0.11066290519785517, 'weight_xgb_class_2': 0.4730999008614367, 'weight_cat_class_0': 0.6223430910542245, 'weight_cat_class_1': 0.8478259308139494, 'weight_cat_class_2': 0.7270914659213572}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,160] Trial 267 finished with value: 0.9482167957040465 and parameters: {'weight_lgbm_class_0': 0.06590271432033584, 'weight_lgbm_class_1': 0.935070887129902, 'weight_lgbm_class_2': 0.5718314526019043, 'weight_xgb_class_0': 0.15894198126965833, 'weight_xgb_class_1': 0.05394003332498845, 'weight_xgb_class_2': 0.48321821136090676, 'weight_cat_class_0': 0.04669842156270999, 'weight_cat_class_1': 0.8544105529208055, 'weight_cat_class_2': 0.729849288348783}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,162] Trial 268 finished with value: 0.948399638978782 and parameters: {'weight_lgbm_class_0': 0.05994512126521307, 'weight_lgbm_class_1': 0.9384674226909955, 'weight_lgbm_class_2': 0.5848390720120605, 'weight_xgb_class_0': 0.1543481324322657, 'weight_xgb_class_1': 0.0488873996065981, 'weight_xgb_class_2': 0.5465457582171405, 'weight_cat_class_0': 0.04898231955331948, 'weight_cat_class_1': 0.8512025968934531, 'weight_cat_class_2': 0.728918520694553}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,228] Trial 270 finished with value: 0.9482393541586949 and parameters: {'weight_lgbm_class_0': 0.06394536982376868, 'weight_lgbm_class_1': 0.9367989900384527, 'weight_lgbm_class_2': 0.5767129786042522, 'weight_xgb_class_0': 0.1530769804218187, 'weight_xgb_class_1': 0.05055705698728151, 'weight_xgb_class_2': 0.47343495043919936, 'weight_cat_class_0': 0.05270520839983835, 'weight_cat_class_1': 0.8559192934507577, 'weight_cat_class_2': 0.7244193217390944}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,238] Trial 269 finished with value: 0.9211294151249655 and parameters: {'weight_lgbm_class_0': 0.06910165020485311, 'weight_lgbm_class_1': 0.9384410671690804, 'weight_lgbm_class_2': 0.5722341775085161, 'weight_xgb_class_0': 0.15206335284730985, 'weight_xgb_class_1': 0.05090452539058051, 'weight_xgb_class_2': 0.47598123061476977, 'weight_cat_class_0': 0.6419761529662595, 'weight_cat_class_1': 0.8561356853083734, 'weight_cat_class_2': 0.6265399205360541}. Best is trial 155 with value: 0.9497166282745368.

[I 2026-07-03 10:22:43,291] Trial 271 finished with value: 0.9490403981031621 and parameters: {'weight_lgbm_class_0': 0.06915992408228715, 'weight_lgbm_class_1': 0.9385556447277208, 'weight_lgbm_class_2': 0.5703361220260673, 'weight_xgb_class_0': 0.09883303284256313, 'weight_xgb_class_1': 0.04743745461738958, 'weight_xgb_class_2': 0.6631667751184908, 'weight_cat_class_0': 0.051567640559821645, 'weight_cat_class_1': 0.8567598276825207, 'weight_cat_class_2': 0.6302766177609342}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,332] Trial 272 finished with value: 0.9486064660498812 and parameters: {'weight_lgbm_class_0': 0.0706712332263884, 'weight_lgbm_class_1': 0.9414557291052826, 'weight_lgbm_class_2': 0.5744676944872654, 'weight_xgb_class_0': 0.15003825608359078, 'weight_xgb_class_1': 0.10275402041971593, 'weight_xgb_class_2': 0.6575875538552868, 'weight_cat_class_0': 0.04338035415394928, 'weight_cat_class_1': 0.9989038230502975, 'weight_cat_class_2': 0.6353664935022192}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,343] Trial 273 finished with value: 0.9486299845994178 and parameters: {'weight_lgbm_class_0': 0.052942763606713, 'weight_lgbm_class_1': 0.9031089065437375, 'weight_lgbm_class_2': 0.5769262140683769, 'weight_xgb_class_0': 0.15112946208598788, 'weight_xgb_class_1': 0.7229315232539355, 'weight_xgb_class_2': 0.4827789591514031, 'weight_cat_class_0': 0.05561656242473907, 'weight_cat_class_1': 0.8539914547034992, 'weight_cat_class_2': 0.6357194015672187}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,390] Trial 274 finished with value: 0.9161306771716452 and parameters: {'weight_lgbm_class_0': 0.07014094704628533, 'weight_lgbm_class_1': 0.9015856156716957, 'weight_lgbm_class_2': 0.5888022965559165, 'weight_xgb_class_0': 0.8134845462141159, 'weight_xgb_class_1': 0.09793351647696308, 'weight_xgb_class_2': 0.48188513047310366, 'weight_cat_class_0': 0.052871769183858046, 'weight_cat_class_1': 0.8562155433519472, 'weight_cat_class_2': 0.6261545533869245}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,403] Trial 275 finished with value: 0.9484131391227847 and parameters: {'weight_lgbm_class_0': 0.06214009827195853, 'weight_lgbm_class_1': 0.9738652918818751, 'weight_lgbm_class_2': 0.5929278246449484, 'weight_xgb_class_0': 0.15233652744028342, 'weight_xgb_class_1': 0.09722599545474556, 'weight_xgb_class_2': 0.5534672454935435, 'weight_cat_class_0': 0.0527631321015125, 'weight_cat_class_1': 0.8608859275916042, 'weight_cat_class_2': 0.6871626433048587}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,442] Trial 276 finished with value: 0.9491664462394184 and parameters: {'weight_lgbm_class_0': 0.06647652238505153, 'weight_lgbm_class_1': 0.9017810577083945, 'weight_lgbm_class_2': 0.5812795064441602, 'weight_xgb_class_0': 0.09318520561497202, 'weight_xgb_class_1': 0.142137521620557, 'weight_xgb_class_2': 0.6518027536896122, 'weight_cat_class_0': 0.05201480677582395, 'weight_cat_class_1': 0.9167907990737405, 'weight_cat_class_2': 0.6278332924965164}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,456] Trial 277 finished with value: 0.9490712875046307 and parameters: {'weight_lgbm_class_0': 0.06504351098076519, 'weight_lgbm_class_1': 0.9036314499494434, 'weight_lgbm_class_2': 0.5886055239682283, 'weight_xgb_class_0': 0.09532470529933595, 'weight_xgb_class_1': 0.04537660803175142, 'weight_xgb_class_2': 0.6574457648882208, 'weight_cat_class_0': 0.06071275115219239, 'weight_cat_class_1': 0.9161967249340772, 'weight_cat_class_2': 0.6925336420499277}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,479] Trial 278 finished with value: 0.9198990804634065 and parameters: {'weight_lgbm_class_0': 0.06265796173864002, 'weight_lgbm_class_1': 0.9010564019670689, 'weight_lgbm_class_2': 0.5873507149397107, 'weight_xgb_class_0': 0.882795737303063, 'weight_xgb_class_1': 0.04661746812957705, 'weight_xgb_class_2': 0.95589304480445, 'weight_cat_class_0': 0.05141289219612334, 'weight_cat_class_1': 0.9210606447265081, 'weight_cat_class_2': 0.6905832966262208}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:  14%|██████████████████▉                                                                                                                 | 286/2000 [00:07<00:51, 33.17it/s]

[I 2026-07-03 10:22:43,529] Trial 280 finished with value: 0.9496113842746595 and parameters: {'weight_lgbm_class_0': 0.0008707933129842669, 'weight_lgbm_class_1': 0.9652251689674195, 'weight_lgbm_class_2': 0.5086398636007986, 'weight_xgb_class_0': 0.10440802716875172, 'weight_xgb_class_1': 0.14093414086328565, 'weight_xgb_class_2': 0.552822088682273, 'weight_cat_class_0': 0.051624117463062266, 'weight_cat_class_1': 0.923309612259003, 'weight_cat_class_2': 0.626969434624998}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,537] Trial 279 finished with value: 0.9496895169483701 and parameters: {'weight_lgbm_class_0': 0.0005507363491385339, 'weight_lgbm_class_1': 0.9714752949244865, 'weight_lgbm_class_2': 0.5388548745275509, 'weight_xgb_class_0': 0.09173317769150686, 'weight_xgb_class_1': 0.13905728372468001, 'weight_xgb_class_2': 0.5827083666650841, 'weight_cat_class_0': 0.051598234154251424, 'weight_cat_class_1': 0.9165182133364572, 'weight_cat_class_2': 0.6317339682126296}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,595] Trial 281 finished with value: 0.9439174604635626 and parameters: {'weight_lgbm_class_0': 0.29891664965357057, 'weight_lgbm_class_1': 0.9734665256125272, 'weight_lgbm_class_2': 0.5114100709987911, 'weight_xgb_class_0': 0.09362327947050342, 'weight_xgb_class_1': 0.13690363529100902, 'weight_xgb_class_2': 0.5529094453143695, 'weight_cat_class_0': 0.048953313556746536, 'weight_cat_class_1': 0.9133065711134606, 'weight_cat_class_2': 0.6959057857681076}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,601] Trial 282 finished with value: 0.9496099022251858 and parameters: {'weight_lgbm_class_0': 0.013475862778470862, 'weight_lgbm_class_1': 0.9723309977979135, 'weight_lgbm_class_2': 0.5087246292188682, 'weight_xgb_class_0': 0.10432717380204186, 'weight_xgb_class_1': 0.1406834654270976, 'weight_xgb_class_2': 0.6582009077695331, 'weight_cat_class_0': 0.05017923273006342, 'weight_cat_class_1': 0.9180144024434821, 'weight_cat_class_2': 0.6931523082831772}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,653] Trial 284 finished with value: 0.9496764185071956 and parameters: {'weight_lgbm_class_0': 0.014885221188183917, 'weight_lgbm_class_1': 0.9748598107385968, 'weight_lgbm_class_2': 0.5095252514201515, 'weight_xgb_class_0': 0.09367393812129027, 'weight_xgb_class_1': 0.13828796523653625, 'weight_xgb_class_2': 0.5567344602252228, 'weight_cat_class_0': 0.021893059263498216, 'weight_cat_class_1': 0.9126718482787036, 'weight_cat_class_2': 0.6917802430922718}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,677] Trial 283 finished with value: 0.9496650989329994 and parameters: {'weight_lgbm_class_0': 0.0010752534830573827, 'weight_lgbm_class_1': 0.9667652977223695, 'weight_lgbm_class_2': 0.5092289990983468, 'weight_xgb_class_0': 0.0954779477715915, 'weight_xgb_class_1': 0.13727930278807815, 'weight_xgb_class_2': 0.5511216066258097, 'weight_cat_class_0': 0.04594112912189877, 'weight_cat_class_1': 0.9162259743546934, 'weight_cat_class_2': 0.6903483455354151}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,693] Trial 285 finished with value: 0.9266906156077234 and parameters: {'weight_lgbm_class_0': 0.015893229029432743, 'weight_lgbm_class_1': 0.9808016518729782, 'weight_lgbm_class_2': 0.5366314556820527, 'weight_xgb_class_0': 0.09429637779926281, 'weight_xgb_class_1': 0.08320876025664453, 'weight_xgb_class_2': 0.5598871516670647, 'weight_cat_class_0': 0.706043902336618, 'weight_cat_class_1': 0.918183949796547, 'weight_cat_class_2': 0.6915385152325295}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:  15%|███████████████████▍                                                                                                                | 294/2000 [00:08<00:51, 33.29it/s]

[I 2026-07-03 10:22:43,781] Trial 286 finished with value: 0.9497101358193891 and parameters: {'weight_lgbm_class_0': 0.01601607500597617, 'weight_lgbm_class_1': 0.9695842405169752, 'weight_lgbm_class_2': 0.5094903209498747, 'weight_xgb_class_0': 0.09897316197450291, 'weight_xgb_class_1': 0.1401094260178256, 'weight_xgb_class_2': 0.5558690084412111, 'weight_cat_class_0': 0.02238586437354244, 'weight_cat_class_1': 0.9151851164189686, 'weight_cat_class_2': 0.6918911646023109}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,787] Trial 287 finished with value: 0.9496223942507274 and parameters: {'weight_lgbm_class_0': 0.0005175903626607635, 'weight_lgbm_class_1': 0.9712687468168424, 'weight_lgbm_class_2': 0.5358694415686498, 'weight_xgb_class_0': 0.09637065360732461, 'weight_xgb_class_1': 0.13808492749114984, 'weight_xgb_class_2': 0.5838187709738022, 'weight_cat_class_0': 0.02362353828991386, 'weight_cat_class_1': 0.9133385358664382, 'weight_cat_class_2': 0.6914995989163335}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,796] Trial 288 finished with value: 0.9495284586404296 and parameters: {'weight_lgbm_class_0': 0.0005383575962874373, 'weight_lgbm_class_1': 0.976502990064679, 'weight_lgbm_class_2': 0.507887190863784, 'weight_xgb_class_0': 0.11183498276797883, 'weight_xgb_class_1': 0.14119541000632554, 'weight_xgb_class_2': 0.9278796127439146, 'weight_cat_class_0': 0.02282493607240174, 'weight_cat_class_1': 0.952291340338882, 'weight_cat_class_2': 0.6639268910457803}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,854] Trial 289 finished with value: 0.9496607249225323 and parameters: {'weight_lgbm_class_0': 6.88484704425528e-05, 'weight_lgbm_class_1': 0.9709403331500005, 'weight_lgbm_class_2': 0.5367468798577847, 'weight_xgb_class_0': 0.10556336380728587, 'weight_xgb_class_1': 0.08742408088557939, 'weight_xgb_class_2': 0.5804529782280233, 'weight_cat_class_0': 0.023395028841373466, 'weight_cat_class_1': 0.9541335420007527, 'weight_cat_class_2': 0.6514789434841506}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,856] Trial 290 finished with value: 0.9459997263069253 and parameters: {'weight_lgbm_class_0': 0.016722158101531815, 'weight_lgbm_class_1': 0.9734161722336062, 'weight_lgbm_class_2': 0.5373101081736602, 'weight_xgb_class_0': 0.32660971900151803, 'weight_xgb_class_1': 0.08235458732305724, 'weight_xgb_class_2': 0.5823782807820306, 'weight_cat_class_0': 0.020491343658062423, 'weight_cat_class_1': 0.881069280374668, 'weight_cat_class_2': 0.665115005398682}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,874] Trial 291 finished with value: 0.9495496446648922 and parameters: {'weight_lgbm_class_0': 0.015323781908707094, 'weight_lgbm_class_1': 0.9778235105250938, 'weight_lgbm_class_2': 0.5371516883402712, 'weight_xgb_class_0': 0.09175439364200882, 'weight_xgb_class_1': 0.13866505173408994, 'weight_xgb_class_2': 0.8173238242908341, 'weight_cat_class_0': 0.023690845553112072, 'weight_cat_class_1': 0.8834424580376665, 'weight_cat_class_2': 0.662065818821455}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,911] Trial 292 finished with value: 0.926289189420466 and parameters: {'weight_lgbm_class_0': 0.01399225707524476, 'weight_lgbm_class_1': 0.9720118692896016, 'weight_lgbm_class_2': 0.5293411088286806, 'weight_xgb_class_0': 0.091806983449312, 'weight_xgb_class_1': 0.13938851274698102, 'weight_xgb_class_2': 0.5822942949108995, 'weight_cat_class_0': 0.7136236347868159, 'weight_cat_class_1': 0.8799462000157144, 'weight_cat_class_2': 0.6649356401178554}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:43,962] Trial 294 finished with value: 0.9496964711499408 and parameters: {'weight_lgbm_class_0': 0.0019125227583469588, 'weight_lgbm_class_1': 0.9768773708982496, 'weight_lgbm_class_2': 0.5397215150776105, 'weight_xgb_class_0': 0.11476894054998998, 'weight_xgb_class_1': 0.0881262274164423, 'weight_xgb_class_2': 0.5702143265137105, 'weight_cat_class_0': 0.025097895754135423, 'weight_cat_class_1': 0.878604235928678, 'weight_cat_class_2': 0.6562270803015993}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:  15%|███████████████████▊                                                                                                                | 300/2000 [00:08<00:51, 32.70it/s]

[I 2026-07-03 10:22:44,000] Trial 293 finished with value: 0.9496924475060337 and parameters: {'weight_lgbm_class_0': 0.0018054647077629716, 'weight_lgbm_class_1': 0.9708107790290884, 'weight_lgbm_class_2': 0.5370883815955595, 'weight_xgb_class_0': 0.11730729952022692, 'weight_xgb_class_1': 0.08239431020945442, 'weight_xgb_class_2': 0.5818141895774955, 'weight_cat_class_0': 0.023186768669400774, 'weight_cat_class_1': 0.8837311378281533, 'weight_cat_class_2': 0.6549018829205187}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,002] Trial 295 finished with value: 0.949384550451256 and parameters: {'weight_lgbm_class_0': 0.0011407937676753289, 'weight_lgbm_class_1': 0.9668909862313108, 'weight_lgbm_class_2': 0.532998056739405, 'weight_xgb_class_0': 0.07925368927104533, 'weight_xgb_class_1': 0.16817451465009794, 'weight_xgb_class_2': 0.5830094957482048, 'weight_cat_class_0': 0.02323699643096719, 'weight_cat_class_1': 0.9497068337567396, 'weight_cat_class_2': 0.6540779295205341}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,022] Trial 296 finished with value: 0.9495738412004404 and parameters: {'weight_lgbm_class_0': 0.0013168043041387398, 'weight_lgbm_class_1': 0.9711548790702225, 'weight_lgbm_class_2': 0.5367346835359652, 'weight_xgb_class_0': 0.08495864686811871, 'weight_xgb_class_1': 0.16820049357976477, 'weight_xgb_class_2': 0.5828268782557741, 'weight_cat_class_0': 0.027499168528877724, 'weight_cat_class_1': 0.9520810920116826, 'weight_cat_class_2': 0.6578595861088736}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,064] Trial 297 finished with value: 0.9494246455028975 and parameters: {'weight_lgbm_class_0': 0.00014156457506053245, 'weight_lgbm_class_1': 0.9693723282564178, 'weight_lgbm_class_2': 0.5377292011219903, 'weight_xgb_class_0': 0.07867294689634663, 'weight_xgb_class_1': 0.16590395846450962, 'weight_xgb_class_2': 0.5808223630315043, 'weight_cat_class_0': 0.027370250080350465, 'weight_cat_class_1': 0.9497228821955798, 'weight_cat_class_2': 0.6655208129231045}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,089] Trial 298 finished with value: 0.9496778339596256 and parameters: {'weight_lgbm_class_0': 0.04425821091392451, 'weight_lgbm_class_1': 0.8641923434729419, 'weight_lgbm_class_2': 0.5370977791506468, 'weight_xgb_class_0': 0.0762130610429601, 'weight_xgb_class_1': 0.17191888590035753, 'weight_xgb_class_2': 0.5867913198961308, 'weight_cat_class_0': 0.025166730847511736, 'weight_cat_class_1': 0.8751989595129225, 'weight_cat_class_2': 0.660068148069152}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,144] Trial 299 finished with value: 0.9402677419576966 and parameters: {'weight_lgbm_class_0': 0.4258440860454248, 'weight_lgbm_class_1': 0.8630157336041202, 'weight_lgbm_class_2': 0.5360217674676115, 'weight_xgb_class_0': 0.07623745863891127, 'weight_xgb_class_1': 0.1550712948470451, 'weight_xgb_class_2': 0.7646030173222238, 'weight_cat_class_0': 0.03018076294372297, 'weight_cat_class_1': 0.7965996340622395, 'weight_cat_class_2': 0.6563581266275942}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,172] Trial 300 finished with value: 0.9496865324304647 and parameters: {'weight_lgbm_class_0': 0.04340726373587108, 'weight_lgbm_class_1': 0.9429343488099091, 'weight_lgbm_class_2': 0.5358909081833898, 'weight_xgb_class_0': 0.07622021363944205, 'weight_xgb_class_1': 0.1635022166797761, 'weight_xgb_class_2': 0.5814711784553265, 'weight_cat_class_0': 0.026885219118028998, 'weight_cat_class_1': 0.9476530922546761, 'weight_cat_class_2': 0.655816495163337}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:  15%|████████████████████▎                                                                                                               | 308/2000 [00:08<00:48, 34.62it/s]

[I 2026-07-03 10:22:44,220] Trial 301 finished with value: 0.9222673161917913 and parameters: {'weight_lgbm_class_0': 0.04395837449790004, 'weight_lgbm_class_1': 0.858903673863857, 'weight_lgbm_class_2': 0.536687273015414, 'weight_xgb_class_0': 0.7386514110316369, 'weight_xgb_class_1': 0.09588650659154496, 'weight_xgb_class_2': 0.5781225216431907, 'weight_cat_class_0': 0.035581716550647284, 'weight_cat_class_1': 0.7886743491539877, 'weight_cat_class_2': 0.6518865235007798}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,225] Trial 302 finished with value: 0.9496811829741033 and parameters: {'weight_lgbm_class_0': 0.03919233371595275, 'weight_lgbm_class_1': 0.9401762834707131, 'weight_lgbm_class_2': 0.5384110362584326, 'weight_xgb_class_0': 0.07131377159474507, 'weight_xgb_class_1': 0.17667099963553656, 'weight_xgb_class_2': 0.5497351674526199, 'weight_cat_class_0': 0.032348103674046426, 'weight_cat_class_1': 0.9518305649110429, 'weight_cat_class_2': 0.7075338017484948}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,273] Trial 303 finished with value: 0.9496937081451696 and parameters: {'weight_lgbm_class_0': 0.0347298209744463, 'weight_lgbm_class_1': 0.8654252012632957, 'weight_lgbm_class_2': 0.5352708727777044, 'weight_xgb_class_0': 0.07501823915566214, 'weight_xgb_class_1': 0.1703155511744221, 'weight_xgb_class_2': 0.54534982138666, 'weight_cat_class_0': 0.03355677622207535, 'weight_cat_class_1': 0.9488019784810555, 'weight_cat_class_2': 0.6513607606923185}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,297] Trial 305 finished with value: 0.9496948574662137 and parameters: {'weight_lgbm_class_0': 0.04231705779452198, 'weight_lgbm_class_1': 0.9425252601400391, 'weight_lgbm_class_2': 0.5390470658699323, 'weight_xgb_class_0': 0.07003784415161624, 'weight_xgb_class_1': 0.09207857771492636, 'weight_xgb_class_2': 0.5853710209871437, 'weight_cat_class_0': 0.03347428658226054, 'weight_cat_class_1': 0.9477775253526264, 'weight_cat_class_2': 0.6479923758897872}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,308] Trial 304 finished with value: 0.9496738027058435 and parameters: {'weight_lgbm_class_0': 0.04426381626623167, 'weight_lgbm_class_1': 0.9386756481350085, 'weight_lgbm_class_2': 0.543158240522813, 'weight_xgb_class_0': 0.0733084555400747, 'weight_xgb_class_1': 0.1713579125923247, 'weight_xgb_class_2': 0.5525588373629512, 'weight_cat_class_0': 0.030058253383309887, 'weight_cat_class_1': 0.8003209927639263, 'weight_cat_class_2': 0.6518944052620801}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,331] Trial 306 finished with value: 0.9493203799917885 and parameters: {'weight_lgbm_class_0': 0.041161668648429295, 'weight_lgbm_class_1': 0.9349061860288753, 'weight_lgbm_class_2': 0.6064500963357317, 'weight_xgb_class_0': 0.11357532073130844, 'weight_xgb_class_1': 0.15995802992129884, 'weight_xgb_class_2': 0.5528147428268275, 'weight_cat_class_0': 0.03612858005036729, 'weight_cat_class_1': 0.7953511962032928, 'weight_cat_class_2': 0.6637218377434511}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,388] Trial 307 finished with value: 0.9496507825047721 and parameters: {'weight_lgbm_class_0': 0.043590507714054594, 'weight_lgbm_class_1': 0.9386022099683292, 'weight_lgbm_class_2': 0.5578053161709439, 'weight_xgb_class_0': 0.0700759310382974, 'weight_xgb_class_1': 0.1753983272213918, 'weight_xgb_class_2': 0.5465857838011839, 'weight_cat_class_0': 0.036156779483064116, 'weight_cat_class_1': 0.8762070108212177, 'weight_cat_class_2': 0.6454717768890587}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,395] Trial 308 finished with value: 0.9491823491038874 and parameters: {'weight_lgbm_class_0': 0.04271385824949251, 'weight_lgbm_class_1': 0.9396029030400779, 'weight_lgbm_class_2': 0.4815305259705921, 'weight_xgb_class_0': 0.113661298000263, 'weight_xgb_class_1': 0.09355652127420236, 'weight_xgb_class_2': 0.548185052866703, 'weight_cat_class_0': 0.037368038141143936, 'weight_cat_class_1': 0.8016165543277857, 'weight_cat_class_2': 0.6500767132427239}. Best is trial 155 with value: 0.9497166282745368.

[I 2026-07-03 10:22:44,435] Trial 309 finished with value: 0.9486038351238619 and parameters: {'weight_lgbm_class_0': 0.04919277591601005, 'weight_lgbm_class_1': 0.935438531292597, 'weight_lgbm_class_2': 0.48354915112889485, 'weight_xgb_class_0': 0.1169872386200567, 'weight_xgb_class_1': 0.15926374290719292, 'weight_xgb_class_2': 0.5466681082780119, 'weight_cat_class_0': 0.0714393447700061, 'weight_cat_class_1': 0.8814773546862344, 'weight_cat_class_2': 0.6055396208691997}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,474] Trial 310 finished with value: 0.9135089747720175 and parameters: {'weight_lgbm_class_0': 0.04426514331605789, 'weight_lgbm_class_1': 0.9353245489917005, 'weight_lgbm_class_2': 0.4802822865029214, 'weight_xgb_class_0': 0.11437443540196106, 'weight_xgb_class_1': 0.18608291694879295, 'weight_xgb_class_2': 0.5562996428596549, 'weight_cat_class_0': 0.8729939809472334, 'weight_cat_class_1': 0.878419020747641, 'weight_cat_class_2': 0.6466780119667427}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,483] Trial 311 finished with value: 0.9486439917456204 and parameters: {'weight_lgbm_class_0': 0.0452582375242806, 'weight_lgbm_class_1': 0.9314393411527272, 'weight_lgbm_class_2': 0.47852083631506936, 'weight_xgb_class_0': 0.11692570492169746, 'weight_xgb_class_1': 0.1701959893933789, 'weight_xgb_class_2': 0.5494021064559017, 'weight_cat_class_0': 0.07300311527045415, 'weight_cat_class_1': 0.8791556774690754, 'weight_cat_class_2': 0.6017760885290159}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,528] Trial 312 finished with value: 0.9492740751980895 and parameters: {'weight_lgbm_class_0': 0.04674211817266131, 'weight_lgbm_class_1': 0.9402287814792093, 'weight_lgbm_class_2': 0.5117848093463667, 'weight_xgb_class_0': 0.07119579642785431, 'weight_xgb_class_1': 0.1683737935674359, 'weight_xgb_class_2': 0.5512040074514711, 'weight_cat_class_0': 0.06771647505792985, 'weight_cat_class_1': 0.8771474904739925, 'weight_cat_class_2': 0.5971441352686451}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,611] Trial 314 finished with value: 0.9492914657841981 and parameters: {'weight_lgbm_class_0': 0.045857664177872, 'weight_lgbm_class_1': 0.9403833917156764, 'weight_lgbm_class_2': 0.6073645609801009, 'weight_xgb_class_0': 0.0746329828429307, 'weight_xgb_class_1': 0.1848734573669416, 'weight_xgb_class_2': 0.591049717546687, 'weight_cat_class_0': 0.07876641055136413, 'weight_cat_class_1': 0.8805120780119415, 'weight_cat_class_2': 0.5940894302848077}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:  16%|█████████████████████▏                                                                                                              | 321/2000 [00:08<00:50, 33.07it/s]

[I 2026-07-03 10:22:44,616] Trial 313 finished with value: 0.9492582940834406 and parameters: {'weight_lgbm_class_0': 0.04396817168864488, 'weight_lgbm_class_1': 0.9301317110825165, 'weight_lgbm_class_2': 0.47780988219477427, 'weight_xgb_class_0': 0.0667250960079708, 'weight_xgb_class_1': 0.19239775122013852, 'weight_xgb_class_2': 0.5525568739408098, 'weight_cat_class_0': 0.07500382042690464, 'weight_cat_class_1': 0.8802184598582121, 'weight_cat_class_2': 0.6084113020643124}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,656] Trial 315 finished with value: 0.9490956965530243 and parameters: {'weight_lgbm_class_0': 0.04686823023496238, 'weight_lgbm_class_1': 0.9396695634884522, 'weight_lgbm_class_2': 0.555078431346886, 'weight_xgb_class_0': 0.0866829125649117, 'weight_xgb_class_1': 0.2084355517138865, 'weight_xgb_class_2': 0.6307703054773431, 'weight_cat_class_0': 0.08441810923976974, 'weight_cat_class_1': 0.9826887524503676, 'weight_cat_class_2': 0.6013919273296386}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,678] Trial 317 finished with value: 0.9492784730584344 and parameters: {'weight_lgbm_class_0': 0.05002571199337055, 'weight_lgbm_class_1': 0.9443140150032101, 'weight_lgbm_class_2': 0.555462662324689, 'weight_xgb_class_0': 0.06462960748468569, 'weight_xgb_class_1': 0.19397463943459214, 'weight_xgb_class_2': 0.5916656967517537, 'weight_cat_class_0': 0.08169890463733888, 'weight_cat_class_1': 0.8818696097064549, 'weight_cat_class_2': 0.58823915903008}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,682] Trial 316 finished with value: 0.9493527629975085 and parameters: {'weight_lgbm_class_0': 0.04652529637658126, 'weight_lgbm_class_1': 0.9464218216452234, 'weight_lgbm_class_2': 0.6050834798022726, 'weight_xgb_class_0': 0.06955902403772331, 'weight_xgb_class_1': 0.1985821478827069, 'weight_xgb_class_2': 0.6353915683487591, 'weight_cat_class_0': 0.07856365498004109, 'weight_cat_class_1': 0.997321430702953, 'weight_cat_class_2': 0.5936204795787835}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,728] Trial 318 finished with value: 0.9493570159700182 and parameters: {'weight_lgbm_class_0': 0.04609035325778505, 'weight_lgbm_class_1': 0.9423123820199412, 'weight_lgbm_class_2': 0.5606928450722802, 'weight_xgb_class_0': 0.06527247261215985, 'weight_xgb_class_1': 0.18480827563831295, 'weight_xgb_class_2': 0.5927536204688262, 'weight_cat_class_0': 0.08156109219516806, 'weight_cat_class_1': 0.9539155837201071, 'weight_cat_class_2': 0.6209197386769676}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,751] Trial 319 finished with value: 0.949501129930879 and parameters: {'weight_lgbm_class_0': 0.03972604168957513, 'weight_lgbm_class_1': 0.9981930337144843, 'weight_lgbm_class_2': 0.5557761813680705, 'weight_xgb_class_0': 0.06524152860895868, 'weight_xgb_class_1': 0.20163373244372726, 'weight_xgb_class_2': 0.5949524444941939, 'weight_cat_class_0': 0.07337113426413056, 'weight_cat_class_1': 0.9779989697016196, 'weight_cat_class_2': 0.6116408906787688}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,784] Trial 320 finished with value: 0.9490951218925021 and parameters: {'weight_lgbm_class_0': 0.04825126710065546, 'weight_lgbm_class_1': 0.9513789333497156, 'weight_lgbm_class_2': 0.5533220563241021, 'weight_xgb_class_0': 0.08021325125883791, 'weight_xgb_class_1': 0.21002916295323804, 'weight_xgb_class_2': 0.6372393413487917, 'weight_cat_class_0': 0.09107905873706437, 'weight_cat_class_1': 0.9910645723139841, 'weight_cat_class_2': 0.6055916117417937}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,790] Trial 321 finished with value: 0.9492687817091641 and parameters: {'weight_lgbm_class_0': 0.04865920253004024, 'weight_lgbm_class_1': 0.9501446825761807, 'weight_lgbm_class_2': 0.5553117907277396, 'weight_xgb_class_0': 0.06291624308140238, 'weight_xgb_class_1': 0.21013692687776825, 'weight_xgb_class_2': 0.589686927919722, 'weight_cat_class_0': 0.08934474364111486, 'weight_cat_class_1': 0.9571442713540557, 'weight_cat_class_2': 0.59586978283288}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:  16%|█████████████████████▋                                                                                                              | 328/2000 [00:09<00:53, 31.24it/s]

[I 2026-07-03 10:22:44,855] Trial 322 finished with value: 0.949261397837703 and parameters: {'weight_lgbm_class_0': 0.049700608061279815, 'weight_lgbm_class_1': 0.9564851377563236, 'weight_lgbm_class_2': 0.5553607380400897, 'weight_xgb_class_0': 0.06251623913572693, 'weight_xgb_class_1': 0.21530769898084579, 'weight_xgb_class_2': 0.5918718616004377, 'weight_cat_class_0': 0.09284981394169481, 'weight_cat_class_1': 0.9903339738261236, 'weight_cat_class_2': 0.5811894990764714}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,885] Trial 323 finished with value: 0.9493522456948362 and parameters: {'weight_lgbm_class_0': 0.031010470908371973, 'weight_lgbm_class_1': 0.9530993585189016, 'weight_lgbm_class_2': 0.5518720889971233, 'weight_xgb_class_0': 0.07646455106234883, 'weight_xgb_class_1': 0.17960973741577296, 'weight_xgb_class_2': 0.5939983696330093, 'weight_cat_class_0': 0.0818589806654132, 'weight_cat_class_1': 0.9509109013586265, 'weight_cat_class_2': 0.6144195134239537}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,908] Trial 324 finished with value: 0.9494982693345553 and parameters: {'weight_lgbm_class_0': 0.03549166192437316, 'weight_lgbm_class_1': 0.9557680466711382, 'weight_lgbm_class_2': 0.5548714493127702, 'weight_xgb_class_0': 0.06677223685872719, 'weight_xgb_class_1': 0.20812967281686068, 'weight_xgb_class_2': 0.6295251230969, 'weight_cat_class_0': 0.07687608656723877, 'weight_cat_class_1': 0.9783707285332502, 'weight_cat_class_2': 0.6266396996439345}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:44,958] Trial 325 finished with value: 0.9496222560345654 and parameters: {'weight_lgbm_class_0': 0.02797731551629498, 'weight_lgbm_class_1': 0.9992381690796625, 'weight_lgbm_class_2': 0.5609866986436961, 'weight_xgb_class_0': 0.06354604960353234, 'weight_xgb_class_1': 0.20668551449114686, 'weight_xgb_class_2': 0.6245031098465171, 'weight_cat_class_0': 0.06185081861901574, 'weight_cat_class_1': 0.9557795880639252, 'weight_cat_class_2': 0.5645013016747493}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,006] Trial 327 finished with value: 0.9496743495021001 and parameters: {'weight_lgbm_class_0': 0.02742782536216133, 'weight_lgbm_class_1': 0.9936708220823316, 'weight_lgbm_class_2': 0.5178625826181669, 'weight_xgb_class_0': 0.05804405397454754, 'weight_xgb_class_1': 0.14990477628376891, 'weight_xgb_class_2': 0.6052494053655049, 'weight_cat_class_0': 0.05825529826032568, 'weight_cat_class_1': 0.9481289601640135, 'weight_cat_class_2': 0.631822299981306}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,018] Trial 326 finished with value: 0.9495926740955577 and parameters: {'weight_lgbm_class_0': 0.028416017202195203, 'weight_lgbm_class_1': 0.9978002707839501, 'weight_lgbm_class_2': 0.5177091061211259, 'weight_xgb_class_0': 0.06496602618656674, 'weight_xgb_class_1': 0.21503111573298822, 'weight_xgb_class_2': 0.6113851980069389, 'weight_cat_class_0': 0.06108056740766745, 'weight_cat_class_1': 0.9410998859885421, 'weight_cat_class_2': 0.5436801766761263}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,045] Trial 329 finished with value: 0.9496345744392897 and parameters: {'weight_lgbm_class_0': 0.02527243801987438, 'weight_lgbm_class_1': 0.9909888237163891, 'weight_lgbm_class_2': 0.5190619002838296, 'weight_xgb_class_0': 0.08610755841329887, 'weight_xgb_class_1': 0.21507545267402256, 'weight_xgb_class_2': 0.6150165832156415, 'weight_cat_class_0': 0.04519805338273782, 'weight_cat_class_1': 0.953226890617985, 'weight_cat_class_2': 0.636923282174335}. Best is trial 155 with value: 0.9497166282745368.

[I 2026-07-03 10:22:45,067] Trial 328 finished with value: 0.9495822721697597 and parameters: {'weight_lgbm_class_0': 0.02203727573249986, 'weight_lgbm_class_1': 0.995660064197966, 'weight_lgbm_class_2': 0.5536501669096938, 'weight_xgb_class_0': 0.058161816300049754, 'weight_xgb_class_1': 0.23633720641948275, 'weight_xgb_class_2': 0.6145044293803543, 'weight_cat_class_0': 0.041658434943400297, 'weight_cat_class_1': 0.9490312500059835, 'weight_cat_class_2': 0.11173186044503441}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,110] Trial 330 finished with value: 0.9496238245937715 and parameters: {'weight_lgbm_class_0': 0.02545547181140124, 'weight_lgbm_class_1': 0.912173829474207, 'weight_lgbm_class_2': 0.5183372235018832, 'weight_xgb_class_0': 0.08786215495765395, 'weight_xgb_class_1': 0.22926878082716157, 'weight_xgb_class_2': 0.6199579559737372, 'weight_cat_class_0': 0.03980891697684903, 'weight_cat_class_1': 0.9580120091675014, 'weight_cat_class_2': 0.637603949867561}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,128] Trial 332 finished with value: 0.9495975909573788 and parameters: {'weight_lgbm_class_0': 0.024509507105065224, 'weight_lgbm_class_1': 0.9943673848269894, 'weight_lgbm_class_2': 0.5207327731441469, 'weight_xgb_class_0': 0.09446444346591326, 'weight_xgb_class_1': 0.1293094345598708, 'weight_xgb_class_2': 0.5726929595013784, 'weight_cat_class_0': 0.04035594038554163, 'weight_cat_class_1': 0.949378749287642, 'weight_cat_class_2': 0.6368753110754716}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,143] Trial 331 finished with value: 0.9496115004835697 and parameters: {'weight_lgbm_class_0': 0.024417457388087902, 'weight_lgbm_class_1': 0.9075402786958296, 'weight_lgbm_class_2': 0.5188644932381558, 'weight_xgb_class_0': 0.09518788714024659, 'weight_xgb_class_1': 0.22700667423222487, 'weight_xgb_class_2': 0.6165688392568123, 'weight_cat_class_0': 0.04293171792451758, 'weight_cat_class_1': 0.9499071245398178, 'weight_cat_class_2': 0.6470189816817224}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,175] Trial 333 finished with value: 0.9335399402065784 and parameters: {'weight_lgbm_class_0': 0.02481815920156208, 'weight_lgbm_class_1': 0.9948575349410544, 'weight_lgbm_class_2': 0.5132223412597877, 'weight_xgb_class_0': 0.596334992859384, 'weight_xgb_class_1': 0.15067907229119237, 'weight_xgb_class_2': 0.6143233385813694, 'weight_cat_class_0': 0.047990593232105805, 'weight_cat_class_1': 0.9500367619997119, 'weight_cat_class_2': 0.6431967540009526}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,242] Trial 336 finished with value: 0.9496284276244514 and parameters: {'weight_lgbm_class_0': 0.022101534129000303, 'weight_lgbm_class_1': 0.9998612077392325, 'weight_lgbm_class_2': 0.5126969329854303, 'weight_xgb_class_0': 0.09351025172908177, 'weight_xgb_class_1': 0.1602786254720539, 'weight_xgb_class_2': 0.6143345481879852, 'weight_cat_class_0': 0.04619272365100525, 'weight_cat_class_1': 0.9104028316515587, 'weight_cat_class_2': 0.6389124371355193}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,260] Trial 334 finished with value: 0.9496460865470192 and parameters: {'weight_lgbm_class_0': 0.020909940596707345, 'weight_lgbm_class_1': 0.9115999089340181, 'weight_lgbm_class_2': 0.5120510794568416, 'weight_xgb_class_0': 0.09821799524489766, 'weight_xgb_class_1': 0.13183625258982923, 'weight_xgb_class_2': 0.6171828116207028, 'weight_cat_class_0': 0.044568542365286484, 'weight_cat_class_1': 0.9469216037496778, 'weight_cat_class_2': 0.6417376460067356}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:  17%|██████████████████████▋                                                                                                             | 343/2000 [00:09<00:50, 32.98it/s]

[I 2026-07-03 10:22:45,275] Trial 335 finished with value: 0.949512544685961 and parameters: {'weight_lgbm_class_0': 0.025702270050853626, 'weight_lgbm_class_1': 0.9952463497987006, 'weight_lgbm_class_2': 0.5211319918665549, 'weight_xgb_class_0': 0.09552646270321674, 'weight_xgb_class_1': 0.15926567664962535, 'weight_xgb_class_2': 0.5633913836852033, 'weight_cat_class_0': 0.04406838899341267, 'weight_cat_class_1': 0.9076585768548507, 'weight_cat_class_2': 0.5463997407695415}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,285] Trial 337 finished with value: 0.9496282260573174 and parameters: {'weight_lgbm_class_0': 0.021682417631950064, 'weight_lgbm_class_1': 0.9119714450887215, 'weight_lgbm_class_2': 0.5164338232077742, 'weight_xgb_class_0': 0.09167458750134558, 'weight_xgb_class_1': 0.14397651371861597, 'weight_xgb_class_2': 0.5698369666729798, 'weight_cat_class_0': 0.042746371529846436, 'weight_cat_class_1': 0.8193608410835986, 'weight_cat_class_2': 0.6367485826559984}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,346] Trial 338 finished with value: 0.9213909685732057 and parameters: {'weight_lgbm_class_0': 0.7796879417453584, 'weight_lgbm_class_1': 0.9118496848340785, 'weight_lgbm_class_2': 0.509354374398598, 'weight_xgb_class_0': 0.08646351102300814, 'weight_xgb_class_1': 0.23870319155620526, 'weight_xgb_class_2': 0.5685875607209312, 'weight_cat_class_0': 0.041994618849177046, 'weight_cat_class_1': 0.9079377004860816, 'weight_cat_class_2': 0.6400774986345606}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,381] Trial 340 finished with value: 0.9491174606356169 and parameters: {'weight_lgbm_class_0': 0.07641765048989853, 'weight_lgbm_class_1': 0.9124547019719137, 'weight_lgbm_class_2': 0.5164979883411688, 'weight_xgb_class_0': 0.09234010723907363, 'weight_xgb_class_1': 0.13601975198677474, 'weight_xgb_class_2': 0.5666259783847225, 'weight_cat_class_0': 0.04172062245080198, 'weight_cat_class_1': 0.9083401934391782, 'weight_cat_class_2': 0.6459582066645574}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,396] Trial 339 finished with value: 0.9491523241386112 and parameters: {'weight_lgbm_class_0': 0.08037951523142266, 'weight_lgbm_class_1': 0.9131107600492785, 'weight_lgbm_class_2': 0.5101302387371897, 'weight_xgb_class_0': 0.09112849791287342, 'weight_xgb_class_1': 0.15575355116996023, 'weight_xgb_class_2': 0.7015692681468516, 'weight_cat_class_0': 0.04316355860257744, 'weight_cat_class_1': 0.9088297606794957, 'weight_cat_class_2': 0.6380527826608094}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,442] Trial 341 finished with value: 0.9490509523669547 and parameters: {'weight_lgbm_class_0': 0.08380435435709602, 'weight_lgbm_class_1': 0.923232355725237, 'weight_lgbm_class_2': 0.5141450872844292, 'weight_xgb_class_0': 0.0944852169467188, 'weight_xgb_class_1': 0.15919973988186398, 'weight_xgb_class_2': 0.5685209703929244, 'weight_cat_class_0': 0.043578737396749063, 'weight_cat_class_1': 0.9113171599513339, 'weight_cat_class_2': 0.6395823659920453}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,468] Trial 345 finished with value: 0.9486938639777137 and parameters: {'weight_lgbm_class_0': 0.1116951216383608, 'weight_lgbm_class_1': 0.9141682355503341, 'weight_lgbm_class_2': 0.45219379715799835, 'weight_xgb_class_0': 0.09381432527836646, 'weight_xgb_class_1': 0.1320970738303369, 'weight_xgb_class_2': 0.5279427130062163, 'weight_cat_class_0': 0.028161235132967644, 'weight_cat_class_1': 0.9080673656920056, 'weight_cat_class_2': 0.667507994651295}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,484] Trial 342 finished with value: 0.9268332442986367 and parameters: {'weight_lgbm_class_0': 0.08300456178392257, 'weight_lgbm_class_1': 0.9077198973588323, 'weight_lgbm_class_2': 0.5015089981172058, 'weight_xgb_class_0': 0.6277375778914513, 'weight_xgb_class_1': 0.15331535139441632, 'weight_xgb_class_2': 0.5648687863093212, 'weight_cat_class_0': 0.0589298780036073, 'weight_cat_class_1': 0.9063743805803267, 'weight_cat_class_2': 0.6640234547487927}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:  17%|███████████████████████                                                                                                             | 349/2000 [00:09<00:54, 30.50it/s]

[I 2026-07-03 10:22:45,515] Trial 343 finished with value: 0.9496333813841384 and parameters: {'weight_lgbm_class_0': 0.0637720571393769, 'weight_lgbm_class_1': 0.9202358988678627, 'weight_lgbm_class_2': 0.44989963314639103, 'weight_xgb_class_0': 0.04684725077299569, 'weight_xgb_class_1': 0.16569566400362926, 'weight_xgb_class_2': 0.5245570289133136, 'weight_cat_class_0': 0.028725359890439933, 'weight_cat_class_1': 0.9147772659245454, 'weight_cat_class_2': 0.667893878965803}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,525] Trial 344 finished with value: 0.9490416860925802 and parameters: {'weight_lgbm_class_0': 0.08922705987785348, 'weight_lgbm_class_1': 0.7384104216419406, 'weight_lgbm_class_2': 0.5010096223541994, 'weight_xgb_class_0': 0.09614511695466965, 'weight_xgb_class_1': 0.15335910041046538, 'weight_xgb_class_2': 0.7033107796337349, 'weight_cat_class_0': 0.026398712639019713, 'weight_cat_class_1': 0.9053396752370483, 'weight_cat_class_2': 0.6719320309879367}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,625] Trial 346 finished with value: 0.9489203399405106 and parameters: {'weight_lgbm_class_0': 0.07979060795049714, 'weight_lgbm_class_1': 0.9189777865927042, 'weight_lgbm_class_2': 0.4576002807810734, 'weight_xgb_class_0': 0.12073441580031269, 'weight_xgb_class_1': 0.15429412299608097, 'weight_xgb_class_2': 0.5254875475094208, 'weight_cat_class_0': 0.02494630130265526, 'weight_cat_class_1': 0.9058527642391345, 'weight_cat_class_2': 0.6880618293579732}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,638] Trial 347 finished with value: 0.936009605083224 and parameters: {'weight_lgbm_class_0': 0.08001230461522099, 'weight_lgbm_class_1': 0.9598684107169281, 'weight_lgbm_class_2': 0.45261886643329813, 'weight_xgb_class_0': 0.11911039174872763, 'weight_xgb_class_1': 0.12995483903533292, 'weight_xgb_class_2': 0.5245199230873695, 'weight_cat_class_0': 0.4067268942768124, 'weight_cat_class_1': 0.9244580031718025, 'weight_cat_class_2': 0.6713660570880193}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,677] Trial 349 finished with value: 0.9496924188271088 and parameters: {'weight_lgbm_class_0': 0.07795559376207806, 'weight_lgbm_class_1': 0.9612675519478953, 'weight_lgbm_class_2': 0.45585245081460546, 'weight_xgb_class_0': 0.044368357225998085, 'weight_xgb_class_1': 0.12884567944811756, 'weight_xgb_class_2': 0.7066656581190369, 'weight_cat_class_0': 0.023381378788399833, 'weight_cat_class_1': 0.9216928628556342, 'weight_cat_class_2': 0.6673975087994906}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,683] Trial 348 finished with value: 0.9496946682685171 and parameters: {'weight_lgbm_class_0': 0.0695116256287848, 'weight_lgbm_class_1': 0.9614280976210209, 'weight_lgbm_class_2': 0.4534875982572169, 'weight_xgb_class_0': 0.042047824640063916, 'weight_xgb_class_1': 0.12770808336553144, 'weight_xgb_class_2': 0.5242788924171629, 'weight_cat_class_0': 0.02334515990554693, 'weight_cat_class_1': 0.9251174880252158, 'weight_cat_class_2': 0.6672396665027418}. Best is trial 155 with value: 0.9497166282745368.

[I 2026-07-03 10:22:45,726] Trial 350 finished with value: 0.9488801267171176 and parameters: {'weight_lgbm_class_0': 0.07867898722868966, 'weight_lgbm_class_1': 0.028011424306335242, 'weight_lgbm_class_2': 0.4501894578414324, 'weight_xgb_class_0': 0.04044289180559287, 'weight_xgb_class_1': 0.15121534824903105, 'weight_xgb_class_2': 0.5237718115617553, 'weight_cat_class_0': 0.023732386241663538, 'weight_cat_class_1': 0.9258252965764503, 'weight_cat_class_2': 0.6687984243470743}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,780] Trial 351 finished with value: 0.9483341828841098 and parameters: {'weight_lgbm_class_0': 0.10426431802782869, 'weight_lgbm_class_1': 0.7403974870331351, 'weight_lgbm_class_2': 0.4514422483634175, 'weight_xgb_class_0': 0.11921219998031277, 'weight_xgb_class_1': 0.09998679444329275, 'weight_xgb_class_2': 0.5250168163023253, 'weight_cat_class_0': 0.022292262968170502, 'weight_cat_class_1': 0.9243053010227231, 'weight_cat_class_2': 0.669478360744243}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,782] Trial 353 finished with value: 0.9496472385460945 and parameters: {'weight_lgbm_class_0': 0.0004536228764279084, 'weight_lgbm_class_1': 0.9602704126362717, 'weight_lgbm_class_2': 0.48457481870928587, 'weight_xgb_class_0': 0.1205528524631774, 'weight_xgb_class_1': 0.09385467362310108, 'weight_xgb_class_2': 0.5257080936729744, 'weight_cat_class_0': 0.02452594041973478, 'weight_cat_class_1': 0.9250147940686514, 'weight_cat_class_2': 0.785073596536548}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,785] Trial 352 finished with value: 0.9496184014367611 and parameters: {'weight_lgbm_class_0': 0.08027634811046439, 'weight_lgbm_class_1': 0.9633477236188768, 'weight_lgbm_class_2': 0.49101821564312337, 'weight_xgb_class_0': 0.04046370274310742, 'weight_xgb_class_1': 0.10292617949979767, 'weight_xgb_class_2': 0.5231847525308077, 'weight_cat_class_0': 0.023136278264489905, 'weight_cat_class_1': 0.929158878056587, 'weight_cat_class_2': 0.6721671160628606}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,858] Trial 354 finished with value: 0.9483591838590648 and parameters: {'weight_lgbm_class_0': 0.0010178405773404045, 'weight_lgbm_class_1': 0.7461138026183651, 'weight_lgbm_class_2': 0.48678872133766177, 'weight_xgb_class_0': 0.04181363041167751, 'weight_xgb_class_1': 0.10039542516153799, 'weight_xgb_class_2': 0.5017964064672625, 'weight_cat_class_0': 0.021617344294643223, 'weight_cat_class_1': 0.7735782992063512, 'weight_cat_class_2': 0.7877591474309539}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,861] Trial 356 finished with value: 0.9496322960105662 and parameters: {'weight_lgbm_class_0': 0.0013179485062225615, 'weight_lgbm_class_1': 0.9679348843427925, 'weight_lgbm_class_2': 0.4840589795940201, 'weight_xgb_class_0': 0.12461444815321099, 'weight_xgb_class_1': 0.09792328652086954, 'weight_xgb_class_2': 0.5077609125902923, 'weight_cat_class_0': 0.02033362281590969, 'weight_cat_class_1': 0.9315587549259551, 'weight_cat_class_2': 0.7876671377966719}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,882] Trial 355 finished with value: 0.9486075133103773 and parameters: {'weight_lgbm_class_0': 0.00011575187336062545, 'weight_lgbm_class_1': 0.9620110374719757, 'weight_lgbm_class_2': 0.4852412571722527, 'weight_xgb_class_0': 0.048105854111912316, 'weight_xgb_class_1': 0.09762066586655427, 'weight_xgb_class_2': 0.5143775087987941, 'weight_cat_class_0': 0.02050008365392854, 'weight_cat_class_1': 0.8189985899648653, 'weight_cat_class_2': 0.6987938416777788}. Best is trial 155 with value: 0.9497166282745368.

[I 2026-07-03 10:22:45,938] Trial 357 finished with value: 0.9496677071939615 and parameters: {'weight_lgbm_class_0': 0.0010799376504649835, 'weight_lgbm_class_1': 0.9627503789677164, 'weight_lgbm_class_2': 0.5366200013681919, 'weight_xgb_class_0': 0.11914062211803549, 'weight_xgb_class_1': 0.09029130813077417, 'weight_xgb_class_2': 0.49766676983008784, 'weight_cat_class_0': 0.020445031007064244, 'weight_cat_class_1': 0.7758447971728593, 'weight_cat_class_2': 0.7832957416698832}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:45,987] Trial 358 finished with value: 0.9425371663192434 and parameters: {'weight_lgbm_class_0': 0.015804812954566382, 'weight_lgbm_class_1': 0.9600184194663122, 'weight_lgbm_class_2': 0.5363995534956165, 'weight_xgb_class_0': 0.4186117130260813, 'weight_xgb_class_1': 0.09956693506614805, 'weight_xgb_class_2': 0.5048369789718727, 'weight_cat_class_0': 0.02336686024566174, 'weight_cat_class_1': 0.9323852158170047, 'weight_cat_class_2': 0.69180364516731}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:46,042] Trial 360 finished with value: 0.9486912028959177 and parameters: {'weight_lgbm_class_0': 0.06442327578527388, 'weight_lgbm_class_1': 0.0022010140870772354, 'weight_lgbm_class_2': 0.40665277485937745, 'weight_xgb_class_0': 0.008953003328807739, 'weight_xgb_class_1': 0.09775414129468346, 'weight_xgb_class_2': 0.7126782534580636, 'weight_cat_class_0': 0.022429809863701744, 'weight_cat_class_1': 0.934160704224593, 'weight_cat_class_2': 0.7122219880571031}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:46,043] Trial 359 finished with value: 0.9495147101880191 and parameters: {'weight_lgbm_class_0': 0.10445475554277758, 'weight_lgbm_class_1': 0.959686511165067, 'weight_lgbm_class_2': 0.4812833855819443, 'weight_xgb_class_0': 0.043307094246706646, 'weight_xgb_class_1': 0.10390409754650926, 'weight_xgb_class_2': 0.8045723925047354, 'weight_cat_class_0': 0.02375897231347207, 'weight_cat_class_1': 0.9312898815921495, 'weight_cat_class_2': 0.7078608315692534}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:46,086] Trial 361 finished with value: 0.9494894311881211 and parameters: {'weight_lgbm_class_0': 0.0630469791141682, 'weight_lgbm_class_1': 0.9596924909679068, 'weight_lgbm_class_2': 0.4843890892368239, 'weight_xgb_class_0': 0.03971453356092586, 'weight_xgb_class_1': 0.10416597342837171, 'weight_xgb_class_2': 0.7943404873615583, 'weight_cat_class_0': 0.02097677184064029, 'weight_cat_class_1': 0.9301724905647532, 'weight_cat_class_2': 0.7076571585901529}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:46,127] Trial 364 finished with value: 0.9494978784953876 and parameters: {'weight_lgbm_class_0': 0.06047728688984436, 'weight_lgbm_class_1': 0.9779082525377601, 'weight_lgbm_class_2': 0.5389286806372015, 'weight_xgb_class_0': 0.04772605399957164, 'weight_xgb_class_1': 0.1232245393148675, 'weight_xgb_class_2': 0.7336752418388275, 'weight_cat_class_0': 0.062257337351820645, 'weight_cat_class_1': 0.7689709545193365, 'weight_cat_class_2': 0.70443992470573}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 155. Best value: 0.949717:  18%|████████████████████████▎                                                                                                           | 369/2000 [00:10<00:50, 32.03it/s]

[I 2026-07-03 10:22:46,127] Trial 362 finished with value: 0.9496783054182002 and parameters: {'weight_lgbm_class_0': 0.06270059540731368, 'weight_lgbm_class_1': 0.9758992118998095, 'weight_lgbm_class_2': 0.4799868182685464, 'weight_xgb_class_0': 0.04884443841739461, 'weight_xgb_class_1': 0.10276475018461835, 'weight_xgb_class_2': 0.6883044941487662, 'weight_cat_class_0': 0.020233662738646782, 'weight_cat_class_1': 0.9325308954530328, 'weight_cat_class_2': 0.7108265269485912}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:46,134] Trial 365 finished with value: 0.9492946123140859 and parameters: {'weight_lgbm_class_0': 0.10716776195893159, 'weight_lgbm_class_1': 0.9813313219880716, 'weight_lgbm_class_2': 0.5387091307719776, 'weight_xgb_class_0': 0.041552648627594384, 'weight_xgb_class_1': 0.17919681047168468, 'weight_xgb_class_2': 0.7250910348648575, 'weight_cat_class_0': 0.06226107060874166, 'weight_cat_class_1': 0.8889317592055219, 'weight_cat_class_2': 0.7032314379428088}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:46,163] Trial 363 finished with value: 0.9496353422013856 and parameters: {'weight_lgbm_class_0': 0.06361680262948546, 'weight_lgbm_class_1': 0.9781290304623464, 'weight_lgbm_class_2': 0.3943646996976653, 'weight_xgb_class_0': 0.018780804907594574, 'weight_xgb_class_1': 0.181540331869709, 'weight_xgb_class_2': 0.6833285499156877, 'weight_cat_class_0': 0.0633800757975224, 'weight_cat_class_1': 0.8934059884916339, 'weight_cat_class_2': 0.7070214730811525}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:46,206] Trial 366 finished with value: 0.9495273577874568 and parameters: {'weight_lgbm_class_0': 0.10798638623122428, 'weight_lgbm_class_1': 0.9830873806210744, 'weight_lgbm_class_2': 0.5813349115703769, 'weight_xgb_class_0': 0.013220205127714007, 'weight_xgb_class_1': 0.07598322700756864, 'weight_xgb_class_2': 0.7542199035241216, 'weight_cat_class_0': 0.06394559464765112, 'weight_cat_class_1': 0.8928185308645608, 'weight_cat_class_2': 0.7061196757488032}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:46,239] Trial 367 finished with value: 0.9494510236106208 and parameters: {'weight_lgbm_class_0': 0.10328251156732021, 'weight_lgbm_class_1': 0.9788961881487255, 'weight_lgbm_class_2': 0.3745805295976378, 'weight_xgb_class_0': 0.012057982817758592, 'weight_xgb_class_1': 0.12121843234917895, 'weight_xgb_class_2': 0.7929752162415753, 'weight_cat_class_0': 0.06699890930588767, 'weight_cat_class_1': 0.8913578511834074, 'weight_cat_class_2': 0.7071985000091627}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:46,303] Trial 369 finished with value: 0.9493949774807716 and parameters: {'weight_lgbm_class_0': 0.11341894473822185, 'weight_lgbm_class_1': 0.9804495434882765, 'weight_lgbm_class_2': 0.40793269313678004, 'weight_xgb_class_0': 0.018275731851548842, 'weight_xgb_class_1': 0.18041671522565583, 'weight_xgb_class_2': 0.8402923044165778, 'weight_cat_class_0': 0.06475131669420962, 'weight_cat_class_1': 0.885670171948561, 'weight_cat_class_2': 0.7071772894080213}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:46,305] Trial 368 finished with value: 0.9345110685521384 and parameters: {'weight_lgbm_class_0': 0.10527263980132642, 'weight_lgbm_class_1': 0.9845534023125095, 'weight_lgbm_class_2': 0.5782326289568663, 'weight_xgb_class_0': 0.013977944803615985, 'weight_xgb_class_1': 0.17771000341551738, 'weight_xgb_class_2': 0.584246678937284, 'weight_cat_class_0': 0.5724545877152891, 'weight_cat_class_1': 0.892471371528406, 'weight_cat_class_2': 0.7050101483835741}. Best is trial 155 with value: 0.9497166282745368.

Best trial: 373. Best value: 0.949719:  19%|████████████████████████▉                                                                                                           | 378/2000 [00:10<00:50, 32.28it/s]

[I 2026-07-03 10:22:46,397] Trial 371 finished with value: 0.9495810836844708 and parameters: {'weight_lgbm_class_0': 0.056901810857236175, 'weight_lgbm_class_1': 0.9823721788927473, 'weight_lgbm_class_2': 0.3726882477346173, 'weight_xgb_class_0': 0.00023292970796164048, 'weight_xgb_class_1': 0.17636640232639827, 'weight_xgb_class_2': 0.7593747674230735, 'weight_cat_class_0': 0.06128726720295153, 'weight_cat_class_1': 0.8760422119664603, 'weight_cat_class_2': 0.7457030518280611}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:46,397] Trial 370 finished with value: 0.9496244796063361 and parameters: {'weight_lgbm_class_0': 0.061201642991531455, 'weight_lgbm_class_1': 0.9819304934928043, 'weight_lgbm_class_2': 0.5939541503334692, 'weight_xgb_class_0': 0.02015161907095553, 'weight_xgb_class_1': 0.18390467938009275, 'weight_xgb_class_2': 0.7544961567870062, 'weight_cat_class_0': 0.06309546258871374, 'weight_cat_class_1': 0.8915243244375014, 'weight_cat_class_2': 0.709376416123327}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:46,438] Trial 372 finished with value: 0.9495841777883526 and parameters: {'weight_lgbm_class_0': 0.05838422310552386, 'weight_lgbm_class_1': 0.9796910291381572, 'weight_lgbm_class_2': 0.5819992445403137, 'weight_xgb_class_0': 0.01794546287627298, 'weight_xgb_class_1': 0.17315146620963223, 'weight_xgb_class_2': 0.8919242849150495, 'weight_cat_class_0': 0.061568297098640076, 'weight_cat_class_1': 0.8916044644662635, 'weight_cat_class_2': 0.6170509993337966}. Best is trial 155 with value: 0.9497166282745368.
[I 2026-07-03 10:22:46,452] Trial 373 finished with value: 0.9497190067339387 and parameters: {'weight_lgbm_class_0': 0.05424061615838488, 'weight_lgbm_class_1': 0.9822244171656327, 'weight_lgbm_class_2': 0.5999857911658261, 'weight_xgb_class_0': 0.02132321585935857, 'weight_xgb_class_1': 0.1224852094245537, 'weight_xgb_class_2': 0.5830874068882603, 'weight_cat_class_0': 0.061092842035689675, 'weight_cat_class_1': 0.8847398858949169, 'weight_cat_class_2': 0.6201541183113449}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:46,493] Trial 375 finished with value: 0.949659606657768 and parameters: {'weight_lgbm_class_0': 0.055138452396168734, 'weight_lgbm_class_1': 0.8866616138909087, 'weight_lgbm_class_2': 0.5979726310487783, 'weight_xgb_class_0': 0.017967527077562648, 'weight_xgb_class_1': 0.12015326185518824, 'weight_xgb_class_2': 0.5464116240190617, 'weight_cat_class_0': 0.06610435321083338, 'weight_cat_class_1': 0.9694773777149526, 'weight_cat_class_2': 0.7450817928877664}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:46,523] Trial 374 finished with value: 0.9492483705837146 and parameters: {'weight_lgbm_class_0': 0.05674083185252402, 'weight_lgbm_class_1': 0.9807803424227419, 'weight_lgbm_class_2': 0.38750316471621643, 'weight_xgb_class_0': 0.06320740708546972, 'weight_xgb_class_1': 0.12335394827867514, 'weight_xgb_class_2': 0.545667233839633, 'weight_cat_class_0': 0.06472060846414157, 'weight_cat_class_1': 0.9700664765516321, 'weight_cat_class_2': 0.7471902294635216}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:46,539] Trial 376 finished with value: 0.9429114118280605 and parameters: {'weight_lgbm_class_0': 0.057779482026144066, 'weight_lgbm_class_1': 0.8646356311890433, 'weight_lgbm_class_2': 0.46717374430761904, 'weight_xgb_class_0': 0.0597439521423983, 'weight_xgb_class_1': 0.12290052712390728, 'weight_xgb_class_2': 0.5467252852680962, 'weight_cat_class_0': 0.3234427925758373, 'weight_cat_class_1': 0.9742516836448426, 'weight_cat_class_2': 0.618420051301113}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:46,552] Trial 377 finished with value: 0.9172637334479802 and parameters: {'weight_lgbm_class_0': 0.933236507126505, 'weight_lgbm_class_1': 0.861797708207555, 'weight_lgbm_class_2': 0.5980306905823652, 'weight_xgb_class_0': 0.06149058104621843, 'weight_xgb_class_1': 0.12405675373606781, 'weight_xgb_class_2': 0.6849561238309505, 'weight_cat_class_0': 0.06109770576727785, 'weight_cat_class_1': 0.9786189822696635, 'weight_cat_class_2': 0.7393433936362964}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:46,585] Trial 379 finished with value: 0.8957845952328398 and parameters: {'weight_lgbm_class_0': 0.9373893636514484, 'weight_lgbm_class_1': 0.11582327744599574, 'weight_lgbm_class_2': 0.5798783043919549, 'weight_xgb_class_0': 0.060130200049139146, 'weight_xgb_class_1': 0.12255215697318532, 'weight_xgb_class_2': 0.5519793386415873, 'weight_cat_class_0': 0.0022739892224723952, 'weight_cat_class_1': 0.9724522059494195, 'weight_cat_class_2': 0.29316705796262993}. Best is trial 373 with value: 0.9497190067339387.

Best trial: 373. Best value: 0.949719:  19%|█████████████████████████▎                                                                                                          | 384/2000 [00:10<00:52, 30.91it/s]

[I 2026-07-03 10:22:46,605] Trial 378 finished with value: 0.9487557504805798 and parameters: {'weight_lgbm_class_0': 0.054342053946301816, 'weight_lgbm_class_1': 0.8904809337164233, 'weight_lgbm_class_2': 0.46279968354930595, 'weight_xgb_class_0': 0.0255864790292483, 'weight_xgb_class_1': 0.128104101850024, 'weight_xgb_class_2': 0.6981738732359904, 'weight_cat_class_0': 0.0022041255045375753, 'weight_cat_class_1': 0.9720094850953542, 'weight_cat_class_2': 0.7391148069593761}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:46,694] Trial 380 finished with value: 0.944499807095912 and parameters: {'weight_lgbm_class_0': 0.05622458041986122, 'weight_lgbm_class_1': 0.8858352447217631, 'weight_lgbm_class_2': 0.5918904973507304, 'weight_xgb_class_0': 0.06023924201003715, 'weight_xgb_class_1': 0.12459400934582109, 'weight_xgb_class_2': 0.5506474068159729, 'weight_cat_class_0': 0.3103410088664062, 'weight_cat_class_1': 0.9743487483851853, 'weight_cat_class_2': 0.683701042476426}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:46,704] Trial 381 finished with value: 0.9494074569235688 and parameters: {'weight_lgbm_class_0': 0.05834700445966337, 'weight_lgbm_class_1': 0.8923687204147633, 'weight_lgbm_class_2': 0.6001261146190071, 'weight_xgb_class_0': 0.05773407328343818, 'weight_xgb_class_1': 0.1297837447683727, 'weight_xgb_class_2': 0.6971649568509793, 'weight_cat_class_0': 0.0015112115008554107, 'weight_cat_class_1': 0.9738555389357595, 'weight_cat_class_2': 0.7366388609172432}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:46,750] Trial 382 finished with value: 0.9326584291796749 and parameters: {'weight_lgbm_class_0': 0.6172350929180678, 'weight_lgbm_class_1': 0.8664129940663043, 'weight_lgbm_class_2': 0.5685357181116912, 'weight_xgb_class_0': 0.06433812149290477, 'weight_xgb_class_1': 0.12374026325308327, 'weight_xgb_class_2': 0.5474966874561545, 'weight_cat_class_0': 0.0029832936366159003, 'weight_cat_class_1': 0.9684298998194237, 'weight_cat_class_2': 0.6175684151213525}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:46,777] Trial 383 finished with value: 0.9495228895058462 and parameters: {'weight_lgbm_class_0': 0.040561459232815324, 'weight_lgbm_class_1': 0.887038680381594, 'weight_lgbm_class_2': 0.4638055950056442, 'weight_xgb_class_0': 0.055596907167927714, 'weight_xgb_class_1': 0.12233121641180662, 'weight_xgb_class_2': 0.6755914408505046, 'weight_cat_class_0': 0.01344238579223083, 'weight_cat_class_1': 0.9728133849060092, 'weight_cat_class_2': 0.6593441083317666}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:46,788] Trial 385 finished with value: 0.9494545526169129 and parameters: {'weight_lgbm_class_0': 0.04342896925396161, 'weight_lgbm_class_1': 0.936824977486713, 'weight_lgbm_class_2': 0.6097099645191921, 'weight_xgb_class_0': 0.054355059328034146, 'weight_xgb_class_1': 0.12200138158761219, 'weight_xgb_class_2': 0.6731173253703386, 'weight_cat_class_0': 0.09251874183338309, 'weight_cat_class_1': 0.9706353876022219, 'weight_cat_class_2': 0.6215106387203868}. Best is trial 373 with value: 0.9497190067339387.

Best trial: 373. Best value: 0.949719:  20%|█████████████████████████▊                                                                                                          | 391/2000 [00:11<00:54, 29.51it/s]

[I 2026-07-03 10:22:46,812] Trial 384 finished with value: 0.9228597099218204 and parameters: {'weight_lgbm_class_0': 0.5926836137294278, 'weight_lgbm_class_1': 0.9362286466577023, 'weight_lgbm_class_2': 0.46829970899213713, 'weight_xgb_class_0': 0.05852198482099004, 'weight_xgb_class_1': 0.11974692415281646, 'weight_xgb_class_2': 0.5962898871104152, 'weight_cat_class_0': 0.09499421692882148, 'weight_cat_class_1': 0.9699783214905178, 'weight_cat_class_2': 0.2777198190966672}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:46,868] Trial 386 finished with value: 0.9496283270797896 and parameters: {'weight_lgbm_class_0': 0.04206528782576867, 'weight_lgbm_class_1': 0.936076236044224, 'weight_lgbm_class_2': 0.4672080807760058, 'weight_xgb_class_0': 0.05438360385182387, 'weight_xgb_class_1': 0.1236338884980702, 'weight_xgb_class_2': 0.594791800641859, 'weight_cat_class_0': 0.04136860611192519, 'weight_cat_class_1': 0.9823281316883309, 'weight_cat_class_2': 0.4351363225097885}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:46,886] Trial 387 finished with value: 0.9492350604930934 and parameters: {'weight_lgbm_class_0': 0.039069321062807534, 'weight_lgbm_class_1': 0.9359186620213031, 'weight_lgbm_class_2': 0.4405432243355067, 'weight_xgb_class_0': 0.059165805662781096, 'weight_xgb_class_1': 0.13398899768963266, 'weight_xgb_class_2': 0.5900266911169152, 'weight_cat_class_0': 0.09807406810801209, 'weight_cat_class_1': 0.8666741432455292, 'weight_cat_class_2': 0.6188009824975239}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:46,954] Trial 389 finished with value: 0.9494776959712502 and parameters: {'weight_lgbm_class_0': 0.03749783414848367, 'weight_lgbm_class_1': 0.9378225207270374, 'weight_lgbm_class_2': 0.641509974505675, 'weight_xgb_class_0': 0.03774962257903591, 'weight_xgb_class_1': 0.14638377339526165, 'weight_xgb_class_2': 0.6725671791725668, 'weight_cat_class_0': 0.04140122946460257, 'weight_cat_class_1': 0.9390076123766499, 'weight_cat_class_2': 0.6566321814351277}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:46,962] Trial 388 finished with value: 0.9496848213607784 and parameters: {'weight_lgbm_class_0': 0.03507642607229246, 'weight_lgbm_class_1': 0.9508755985922299, 'weight_lgbm_class_2': 0.6195694472208684, 'weight_xgb_class_0': 0.03320357670408483, 'weight_xgb_class_1': 0.14300383242442644, 'weight_xgb_class_2': 0.6839637456696025, 'weight_cat_class_0': 0.0940482559437314, 'weight_cat_class_1': 0.9393715491775518, 'weight_cat_class_2': 0.6547996985838016}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:46,983] Trial 390 finished with value: 0.9495030340688273 and parameters: {'weight_lgbm_class_0': 0.03754284075880768, 'weight_lgbm_class_1': 0.9358298009670917, 'weight_lgbm_class_2': 0.5374742723969779, 'weight_xgb_class_0': 0.03917449334190706, 'weight_xgb_class_1': 0.1412227496441195, 'weight_xgb_class_2': 0.6767259122335393, 'weight_cat_class_0': 0.09484706881479196, 'weight_cat_class_1': 0.8665542240601775, 'weight_cat_class_2': 0.5724148425639749}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:46,987] Trial 391 finished with value: 0.9495639212011185 and parameters: {'weight_lgbm_class_0': 0.03741949206550407, 'weight_lgbm_class_1': 0.9367905383412167, 'weight_lgbm_class_2': 0.5692115925870929, 'weight_xgb_class_0': 0.03632186408859929, 'weight_xgb_class_1': 0.14870920348480324, 'weight_xgb_class_2': 0.5912506642056407, 'weight_cat_class_0': 0.03843930561927199, 'weight_cat_class_1': 0.8667466690828103, 'weight_cat_class_2': 0.6553042066477842}. Best is trial 373 with value: 0.9497190067339387.

[I 2026-07-03 10:22:47,075] Trial 393 finished with value: 0.9495080847212359 and parameters: {'weight_lgbm_class_0': 0.03849461385005417, 'weight_lgbm_class_1': 0.9333321001721272, 'weight_lgbm_class_2': 0.6533331110669246, 'weight_xgb_class_0': 0.03526555852939607, 'weight_xgb_class_1': 0.07740343090582094, 'weight_xgb_class_2': 0.5955005079986047, 'weight_cat_class_0': 0.03995080366333968, 'weight_cat_class_1': 0.9293153125815269, 'weight_cat_class_2': 0.6556281408881492}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,079] Trial 392 finished with value: 0.949583531680994 and parameters: {'weight_lgbm_class_0': 0.03627182420865149, 'weight_lgbm_class_1': 0.9364219602707209, 'weight_lgbm_class_2': 0.6246670415703405, 'weight_xgb_class_0': 0.03865512860321575, 'weight_xgb_class_1': 0.14361330168367467, 'weight_xgb_class_2': 0.6761099778480866, 'weight_cat_class_0': 0.09909504507500158, 'weight_cat_class_1': 0.9372721706639147, 'weight_cat_class_2': 0.6591953021375015}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,128] Trial 394 finished with value: 0.9496594382284451 and parameters: {'weight_lgbm_class_0': 0.0795860789455532, 'weight_lgbm_class_1': 0.9359546067540839, 'weight_lgbm_class_2': 0.6437155681448778, 'weight_xgb_class_0': 0.04137042062010183, 'weight_xgb_class_1': 0.15042024173354338, 'weight_xgb_class_2': 0.586536061923335, 'weight_cat_class_0': 0.040077169581872144, 'weight_cat_class_1': 0.8641905599182776, 'weight_cat_class_2': 0.657976728210544}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,148] Trial 395 finished with value: 0.9491705002610544 and parameters: {'weight_lgbm_class_0': 0.08698886192005288, 'weight_lgbm_class_1': 0.9473376344089416, 'weight_lgbm_class_2': 0.6260765193695673, 'weight_xgb_class_0': 0.0340222322590719, 'weight_xgb_class_1': 0.1473902456370573, 'weight_xgb_class_2': 0.6422023937104606, 'weight_cat_class_0': 0.09908925188338083, 'weight_cat_class_1': 0.8660002151346129, 'weight_cat_class_2': 0.6548892785360346}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,221] Trial 396 finished with value: 0.949511552396316 and parameters: {'weight_lgbm_class_0': 0.033147588528568764, 'weight_lgbm_class_1': 0.9507026460475426, 'weight_lgbm_class_2': 0.4383188073368745, 'weight_xgb_class_0': 0.034445318072831875, 'weight_xgb_class_1': 0.14489910054035743, 'weight_xgb_class_2': 0.5840145192217402, 'weight_cat_class_0': 0.035543627756307344, 'weight_cat_class_1': 0.9403539751408043, 'weight_cat_class_2': 0.5719264181092966}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,228] Trial 398 finished with value: 0.9492916497826864 and parameters: {'weight_lgbm_class_0': 0.0825644705172108, 'weight_lgbm_class_1': 0.9575960249905213, 'weight_lgbm_class_2': 0.5334653557530115, 'weight_xgb_class_0': 0.07772970053623711, 'weight_xgb_class_1': 0.0685569439528295, 'weight_xgb_class_2': 0.5771465999442086, 'weight_cat_class_0': 0.03540918693852075, 'weight_cat_class_1': 0.938420706726439, 'weight_cat_class_2': 0.6565959309782666}. Best is trial 373 with value: 0.9497190067339387.

[I 2026-07-03 10:22:47,230] Trial 397 finished with value: 0.9495296430162479 and parameters: {'weight_lgbm_class_0': 0.08172747558516885, 'weight_lgbm_class_1': 0.9509884984116949, 'weight_lgbm_class_2': 0.651731859817727, 'weight_xgb_class_0': 0.07696984125644796, 'weight_xgb_class_1': 0.9018573946399295, 'weight_xgb_class_2': 0.5863961439116081, 'weight_cat_class_0': 0.039155779691432135, 'weight_cat_class_1': 0.9366694161760534, 'weight_cat_class_2': 0.6576799083667006}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,250] Trial 399 finished with value: 0.9494136991118545 and parameters: {'weight_lgbm_class_0': 0.08792046880799476, 'weight_lgbm_class_1': 0.9990332294782928, 'weight_lgbm_class_2': 0.6334837595158012, 'weight_xgb_class_0': 0.07477760710124282, 'weight_xgb_class_1': 0.1490602770759255, 'weight_xgb_class_2': 0.6465774414382293, 'weight_cat_class_0': 0.03686988095032367, 'weight_cat_class_1': 0.9372265074191892, 'weight_cat_class_2': 0.6584333492951904}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,335] Trial 401 finished with value: 0.9496223323722203 and parameters: {'weight_lgbm_class_0': 0.07850428128201911, 'weight_lgbm_class_1': 0.9567949872172238, 'weight_lgbm_class_2': 0.5354816731376184, 'weight_xgb_class_0': 0.00013380644295440253, 'weight_xgb_class_1': 0.15599084558765702, 'weight_xgb_class_2': 0.7114650636107258, 'weight_cat_class_0': 0.04164638026926683, 'weight_cat_class_1': 0.9319379199522907, 'weight_cat_class_2': 0.6554529967223083}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,357] Trial 400 finished with value: 0.9492036801189818 and parameters: {'weight_lgbm_class_0': 0.08480957519975363, 'weight_lgbm_class_1': 0.9983913130479014, 'weight_lgbm_class_2': 0.6242508494918093, 'weight_xgb_class_0': 0.028576128449854767, 'weight_xgb_class_1': 0.16002316222783855, 'weight_xgb_class_2': 0.6477658696038306, 'weight_cat_class_0': 0.11162214987787619, 'weight_cat_class_1': 0.9257189952354069, 'weight_cat_class_2': 0.6572237812478965}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,401] Trial 402 finished with value: 0.9490417905536855 and parameters: {'weight_lgbm_class_0': 0.08166938185855549, 'weight_lgbm_class_1': 0.9585163206535181, 'weight_lgbm_class_2': 0.5366131182195732, 'weight_xgb_class_0': 0.028355017648179527, 'weight_xgb_class_1': 0.1602038463330781, 'weight_xgb_class_2': 0.5669848018066702, 'weight_cat_class_0': 0.12246951805954387, 'weight_cat_class_1': 0.9381430091211449, 'weight_cat_class_2': 0.6551993333187262}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,442] Trial 403 finished with value: 0.9496636678573468 and parameters: {'weight_lgbm_class_0': 0.08189116431599641, 'weight_lgbm_class_1': 0.9552029076216267, 'weight_lgbm_class_2': 0.5358511279592556, 'weight_xgb_class_0': 0.03504366528309086, 'weight_xgb_class_1': 0.16315246375730744, 'weight_xgb_class_2': 0.5770256114292075, 'weight_cat_class_0': 0.038591600204975034, 'weight_cat_class_1': 0.9396988479120133, 'weight_cat_class_2': 0.6597335885715967}. Best is trial 373 with value: 0.9497190067339387.

Best trial: 373. Best value: 0.949719:  21%|███████████████████████████▏                                                                                                        | 411/2000 [00:11<00:51, 30.93it/s]

[I 2026-07-03 10:22:47,487] Trial 406 finished with value: 0.9483573319719185 and parameters: {'weight_lgbm_class_0': 0.07510871843692676, 'weight_lgbm_class_1': 0.958159872886188, 'weight_lgbm_class_2': 0.5470330500087468, 'weight_xgb_class_0': 0.0803999006552231, 'weight_xgb_class_1': 0.16073046090549395, 'weight_xgb_class_2': 0.5692950358493252, 'weight_cat_class_0': 0.12137558655052087, 'weight_cat_class_1': 0.9435188955684705, 'weight_cat_class_2': 0.678807613712831}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,500] Trial 405 finished with value: 0.9486565162665951 and parameters: {'weight_lgbm_class_0': 0.0786484465424508, 'weight_lgbm_class_1': 0.9575058211390612, 'weight_lgbm_class_2': 0.6686736242670296, 'weight_xgb_class_0': 0.07718008967117516, 'weight_xgb_class_1': 0.16677713764684618, 'weight_xgb_class_2': 0.5710347380043174, 'weight_cat_class_0': 0.11407562964971824, 'weight_cat_class_1': 0.945738148811733, 'weight_cat_class_2': 0.6830212168695562}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,511] Trial 404 finished with value: 0.9495567437876097 and parameters: {'weight_lgbm_class_0': 0.07953104376969565, 'weight_lgbm_class_1': 0.9981356644076512, 'weight_lgbm_class_2': 0.5361644034154759, 'weight_xgb_class_0': 0.0013454325197053182, 'weight_xgb_class_1': 0.1649681953999051, 'weight_xgb_class_2': 0.6384295788210296, 'weight_cat_class_0': 0.03491744238797711, 'weight_cat_class_1': 0.9414777858623182, 'weight_cat_class_2': 0.6771792835341238}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,565] Trial 407 finished with value: 0.9496103334626239 and parameters: {'weight_lgbm_class_0': 0.07772905352649062, 'weight_lgbm_class_1': 0.9984174974004403, 'weight_lgbm_class_2': 0.5342960834109695, 'weight_xgb_class_0': 0.07660852439456879, 'weight_xgb_class_1': 0.8926457996584145, 'weight_xgb_class_2': 0.7227025199062429, 'weight_cat_class_0': 0.03350274244132197, 'weight_cat_class_1': 0.9470532456597706, 'weight_cat_class_2': 0.6748883476770807}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,605] Trial 409 finished with value: 0.9460556525634187 and parameters: {'weight_lgbm_class_0': 0.021384013821361972, 'weight_lgbm_class_1': 0.9640409701060116, 'weight_lgbm_class_2': 0.5408498680991538, 'weight_xgb_class_0': 0.0001920248368027927, 'weight_xgb_class_1': 0.16923137526026086, 'weight_xgb_class_2': 0.7192547322081725, 'weight_cat_class_0': 0.01986739189141153, 'weight_cat_class_1': 0.91771283341247, 'weight_cat_class_2': 0.6318901652045984}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,635] Trial 408 finished with value: 0.9459658092012658 and parameters: {'weight_lgbm_class_0': 0.018952753588607443, 'weight_lgbm_class_1': 0.9999276080047366, 'weight_lgbm_class_2': 0.5694684542964443, 'weight_xgb_class_0': 0.004177924177662044, 'weight_xgb_class_1': 0.16977719171668754, 'weight_xgb_class_2': 0.7226543873949389, 'weight_cat_class_0': 0.018924296251283296, 'weight_cat_class_1': 0.9175532541718047, 'weight_cat_class_2': 0.6824502030993276}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,646] Trial 410 finished with value: 0.9376693436980768 and parameters: {'weight_lgbm_class_0': 0.024350927158740963, 'weight_lgbm_class_1': 0.9998312419975697, 'weight_lgbm_class_2': 0.5655418630515422, 'weight_xgb_class_0': 0.511115997038594, 'weight_xgb_class_1': 0.16621831967093248, 'weight_xgb_class_2': 0.5664037711401444, 'weight_cat_class_0': 0.054836549334712346, 'weight_cat_class_1': 0.9155619255316003, 'weight_cat_class_2': 0.6786984867538738}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,695] Trial 411 finished with value: 0.949530641579877 and parameters: {'weight_lgbm_class_0': 0.02169610582545702, 'weight_lgbm_class_1': 0.9653818747629407, 'weight_lgbm_class_2': 0.5646781299875643, 'weight_xgb_class_0': 0.07828087659533976, 'weight_xgb_class_1': 0.16869966038884732, 'weight_xgb_class_2': 0.7359996070998913, 'weight_cat_class_0': 0.018628377871903933, 'weight_cat_class_1': 0.9151635287181694, 'weight_cat_class_2': 0.6797401689182833}. Best is trial 373 with value: 0.9497190067339387.

Best trial: 373. Best value: 0.949719:  21%|███████████████████████████▌                                                                                                        | 418/2000 [00:12<00:53, 29.40it/s]

[I 2026-07-03 10:22:47,704] Trial 412 finished with value: 0.9469788262581157 and parameters: {'weight_lgbm_class_0': 0.02462257512498192, 'weight_lgbm_class_1': 0.966679810252323, 'weight_lgbm_class_2': 0.5585863372237629, 'weight_xgb_class_0': 0.00032701792585292794, 'weight_xgb_class_1': 0.18560973392754987, 'weight_xgb_class_2': 0.4961277090892927, 'weight_cat_class_0': 0.022218799012464104, 'weight_cat_class_1': 0.9094872615839579, 'weight_cat_class_2': 0.6291527235568545}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,748] Trial 413 finished with value: 0.9496037533544143 and parameters: {'weight_lgbm_class_0': 0.021600213240911405, 'weight_lgbm_class_1': 0.999972986962519, 'weight_lgbm_class_2': 0.5616213345431367, 'weight_xgb_class_0': 0.07340918223525392, 'weight_xgb_class_1': 0.19164826918255856, 'weight_xgb_class_2': 0.5624548224312615, 'weight_cat_class_0': 0.020570914150835385, 'weight_cat_class_1': 0.9165258841495476, 'weight_cat_class_2': 0.6785734897112735}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,778] Trial 414 finished with value: 0.9207680391037337 and parameters: {'weight_lgbm_class_0': 0.8496124242591535, 'weight_lgbm_class_1': 0.9704427184379082, 'weight_lgbm_class_2': 0.5634427038509164, 'weight_xgb_class_0': 0.07939569583424594, 'weight_xgb_class_1': 0.19262288081105527, 'weight_xgb_class_2': 0.5660219000382966, 'weight_cat_class_0': 0.01847132657712622, 'weight_cat_class_1': 0.9070627242815793, 'weight_cat_class_2': 0.6829701701163999}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,805] Trial 415 finished with value: 0.9495337407106855 and parameters: {'weight_lgbm_class_0': 0.019509197825441957, 'weight_lgbm_class_1': 0.9735250662526846, 'weight_lgbm_class_2': 0.5657935921755569, 'weight_xgb_class_0': 0.07720051448134452, 'weight_xgb_class_1': 0.18992736024884913, 'weight_xgb_class_2': 0.7308425731830858, 'weight_cat_class_0': 0.022189883275295943, 'weight_cat_class_1': 0.9103170167801167, 'weight_cat_class_2': 0.6825326926450688}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,886] Trial 416 finished with value: 0.9496353532011544 and parameters: {'weight_lgbm_class_0': 0.022951943677476227, 'weight_lgbm_class_1': 0.9791023386319199, 'weight_lgbm_class_2': 0.5690870988180902, 'weight_xgb_class_0': 0.07835753142244695, 'weight_xgb_class_1': 0.18809323015673945, 'weight_xgb_class_2': 0.6078300329750695, 'weight_cat_class_0': 0.016155454640726985, 'weight_cat_class_1': 0.9080060080211584, 'weight_cat_class_2': 0.630649377701227}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,889] Trial 417 finished with value: 0.9495694709987675 and parameters: {'weight_lgbm_class_0': 0.021493409111871375, 'weight_lgbm_class_1': 0.9832030309231169, 'weight_lgbm_class_2': 0.5691646016809081, 'weight_xgb_class_0': 0.07797361658862834, 'weight_xgb_class_1': 0.1881540753596811, 'weight_xgb_class_2': 0.7313548128838099, 'weight_cat_class_0': 0.018452616223933054, 'weight_cat_class_1': 0.9127320174135533, 'weight_cat_class_2': 0.6274100824922371}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,934] Trial 418 finished with value: 0.9492687347830425 and parameters: {'weight_lgbm_class_0': 0.02132819124152592, 'weight_lgbm_class_1': 0.9765475832192599, 'weight_lgbm_class_2': 0.564091205192315, 'weight_xgb_class_0': 0.11185017626282052, 'weight_xgb_class_1': 0.19945957476129095, 'weight_xgb_class_2': 0.4943064782890256, 'weight_cat_class_0': 0.059102518971155926, 'weight_cat_class_1': 0.9092325455278789, 'weight_cat_class_2': 0.6237672598737265}. Best is trial 373 with value: 0.9497190067339387.

Best trial: 373. Best value: 0.949719:  21%|████████████████████████████                                                                                                        | 425/2000 [00:12<00:48, 32.28it/s]

[I 2026-07-03 10:22:47,950] Trial 419 finished with value: 0.9493359399350046 and parameters: {'weight_lgbm_class_0': 0.024265818925967658, 'weight_lgbm_class_1': 0.9766140894417716, 'weight_lgbm_class_2': 0.5619255412588912, 'weight_xgb_class_0': 0.10679795034856776, 'weight_xgb_class_1': 0.19112352419992262, 'weight_xgb_class_2': 0.6064684986769054, 'weight_cat_class_0': 0.05591545426114816, 'weight_cat_class_1': 0.9048682069803649, 'weight_cat_class_2': 0.6283108485904177}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:47,961] Trial 420 finished with value: 0.9494329882255164 and parameters: {'weight_lgbm_class_0': 0.020442159493154637, 'weight_lgbm_class_1': 0.9765108022422704, 'weight_lgbm_class_2': 0.4926148418890158, 'weight_xgb_class_0': 0.10241424399822323, 'weight_xgb_class_1': 0.20002814137784278, 'weight_xgb_class_2': 0.9895234366941666, 'weight_cat_class_0': 0.06265227019263202, 'weight_cat_class_1': 0.9038370716778504, 'weight_cat_class_2': 0.6261128902905395}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,000] Trial 422 finished with value: 0.949251217659092 and parameters: {'weight_lgbm_class_0': 0.023722037787490748, 'weight_lgbm_class_1': 0.9679676477297013, 'weight_lgbm_class_2': 0.49803118262012275, 'weight_xgb_class_0': 0.10978243186617367, 'weight_xgb_class_1': 0.19508464820314098, 'weight_xgb_class_2': 0.4927700629121703, 'weight_cat_class_0': 0.059478428414244354, 'weight_cat_class_1': 0.9991516295875682, 'weight_cat_class_2': 0.6277472164234712}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,018] Trial 421 finished with value: 0.9490534358221908 and parameters: {'weight_lgbm_class_0': 0.019398785719432213, 'weight_lgbm_class_1': 0.9745926583630308, 'weight_lgbm_class_2': 0.49553507962596904, 'weight_xgb_class_0': 0.10949211775007175, 'weight_xgb_class_1': 0.08358430165745237, 'weight_xgb_class_2': 0.4917416990839872, 'weight_cat_class_0': 0.07147639088283078, 'weight_cat_class_1': 0.8958793404331268, 'weight_cat_class_2': 0.6147451535863808}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,102] Trial 423 finished with value: 0.9474003044553839 and parameters: {'weight_lgbm_class_0': 0.129001851667983, 'weight_lgbm_class_1': 0.9791615297023526, 'weight_lgbm_class_2': 0.5030409785437169, 'weight_xgb_class_0': 0.10553702270913366, 'weight_xgb_class_1': 0.08812563111014118, 'weight_xgb_class_2': 0.6083138958339795, 'weight_cat_class_0': 0.07496263671235913, 'weight_cat_class_1': 0.8963162708160726, 'weight_cat_class_2': 0.6145934852405831}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,121] Trial 424 finished with value: 0.948900626685302 and parameters: {'weight_lgbm_class_0': 0.05310125557792546, 'weight_lgbm_class_1': 0.9222477799131421, 'weight_lgbm_class_2': 0.4995027624598685, 'weight_xgb_class_0': 0.10855699619384235, 'weight_xgb_class_1': 0.0830751648659388, 'weight_xgb_class_2': 0.6085221148194099, 'weight_cat_class_0': 0.06196330729147255, 'weight_cat_class_1': 0.8300808743754834, 'weight_cat_class_2': 0.6141398017415746}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,126] Trial 426 finished with value: 0.9470514814979434 and parameters: {'weight_lgbm_class_0': 0.1262274675575256, 'weight_lgbm_class_1': 0.9216630436469466, 'weight_lgbm_class_2': 0.49733757576747883, 'weight_xgb_class_0': 0.10527124099949844, 'weight_xgb_class_1': 0.08263417031506079, 'weight_xgb_class_2': 0.5420214823847704, 'weight_cat_class_0': 0.07892540582169293, 'weight_cat_class_1': 0.8299164635204543, 'weight_cat_class_2': 0.6316901298698985}. Best is trial 373 with value: 0.9497190067339387.

Best trial: 373. Best value: 0.949719:  22%|████████████████████████████▍                                                                                                       | 430/2000 [00:12<00:54, 28.71it/s]

[I 2026-07-03 10:22:48,142] Trial 425 finished with value: 0.9488318934752008 and parameters: {'weight_lgbm_class_0': 0.05523886812881643, 'weight_lgbm_class_1': 0.9773190749477689, 'weight_lgbm_class_2': 0.49245941131304855, 'weight_xgb_class_0': 0.10733590478132701, 'weight_xgb_class_1': 0.08113469070886577, 'weight_xgb_class_2': 0.604932098852924, 'weight_cat_class_0': 0.0693247654047984, 'weight_cat_class_1': 0.8875783086639102, 'weight_cat_class_2': 0.61241774534739}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,236] Trial 427 finished with value: 0.9485224487401013 and parameters: {'weight_lgbm_class_0': 0.052632855621211325, 'weight_lgbm_class_1': 0.9229293894112993, 'weight_lgbm_class_2': 0.4948393580430153, 'weight_xgb_class_0': 0.10871350147089369, 'weight_xgb_class_1': 0.07719495983495155, 'weight_xgb_class_2': 0.5362126498120174, 'weight_cat_class_0': 0.07816405183378691, 'weight_cat_class_1': 0.8132943145489586, 'weight_cat_class_2': 0.6187788942369159}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,293] Trial 428 finished with value: 0.9486128217743639 and parameters: {'weight_lgbm_class_0': 0.055285110255396216, 'weight_lgbm_class_1': 0.92400767305867, 'weight_lgbm_class_2': 0.49843432078455635, 'weight_xgb_class_0': 0.10726930823707125, 'weight_xgb_class_1': 0.10250331025471125, 'weight_xgb_class_2': 0.5347736377794313, 'weight_cat_class_0': 0.07595570127562304, 'weight_cat_class_1': 0.9995764468833632, 'weight_cat_class_2': 0.6005323136678986}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,321] Trial 431 finished with value: 0.948541282162234 and parameters: {'weight_lgbm_class_0': 0.05341665446108353, 'weight_lgbm_class_1': 0.918500893866284, 'weight_lgbm_class_2': 0.4986960934593921, 'weight_xgb_class_0': 0.10931627492717932, 'weight_xgb_class_1': 0.08211786552774886, 'weight_xgb_class_2': 0.5336615254541033, 'weight_cat_class_0': 0.07894477838248629, 'weight_cat_class_1': 0.8370886567401015, 'weight_cat_class_2': 0.6391103431757282}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,323] Trial 429 finished with value: 0.9486937560572296 and parameters: {'weight_lgbm_class_0': 0.051448615069892546, 'weight_lgbm_class_1': 0.9224866327538945, 'weight_lgbm_class_2': 0.49654031061420717, 'weight_xgb_class_0': 0.10803486504635733, 'weight_xgb_class_1': 0.08163357841990532, 'weight_xgb_class_2': 0.5426069703280465, 'weight_cat_class_0': 0.06892705977183355, 'weight_cat_class_1': 0.7981371697863062, 'weight_cat_class_2': 0.6114641631365422}. Best is trial 373 with value: 0.9497190067339387.

Best trial: 373. Best value: 0.949719:  22%|████████████████████████████▉                                                                                                       | 438/2000 [00:12<00:48, 32.48it/s]

[I 2026-07-03 10:22:48,324] Trial 430 finished with value: 0.948830513908098 and parameters: {'weight_lgbm_class_0': 0.052941127944728154, 'weight_lgbm_class_1': 0.9501110402431743, 'weight_lgbm_class_2': 0.5003633943714159, 'weight_xgb_class_0': 0.09652410823709409, 'weight_xgb_class_1': 0.10853939550591452, 'weight_xgb_class_2': 0.6058597405547858, 'weight_cat_class_0': 0.07942732189604126, 'weight_cat_class_1': 0.8104129988785752, 'weight_cat_class_2': 0.5995023652048036}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,349] Trial 432 finished with value: 0.949183087919694 and parameters: {'weight_lgbm_class_0': 0.05192511170004864, 'weight_lgbm_class_1': 0.9284704429211087, 'weight_lgbm_class_2': 0.49899770850205444, 'weight_xgb_class_0': 0.05493852881554427, 'weight_xgb_class_1': 0.08949303379476008, 'weight_xgb_class_2': 0.5320122136969105, 'weight_cat_class_0': 0.08266934934171381, 'weight_cat_class_1': 0.7997699466034391, 'weight_cat_class_2': 0.5967978453840829}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,428] Trial 433 finished with value: 0.9492537592819851 and parameters: {'weight_lgbm_class_0': 0.05131549224080222, 'weight_lgbm_class_1': 0.759538941583326, 'weight_lgbm_class_2': 0.6131200158071822, 'weight_xgb_class_0': 0.04965220871632474, 'weight_xgb_class_1': 0.10280574651156744, 'weight_xgb_class_2': 0.5350214232321572, 'weight_cat_class_0': 0.08368624121717706, 'weight_cat_class_1': 0.8286792239347603, 'weight_cat_class_2': 0.5963869307172666}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,431] Trial 434 finished with value: 0.9495279087472414 and parameters: {'weight_lgbm_class_0': 0.05111245296472955, 'weight_lgbm_class_1': 0.9225830112903645, 'weight_lgbm_class_2': 0.6083994833543322, 'weight_xgb_class_0': 0.05166233013907867, 'weight_xgb_class_1': 0.10757921117546425, 'weight_xgb_class_2': 0.5354174403856344, 'weight_cat_class_0': 0.0018158518814613278, 'weight_cat_class_1': 0.8078459991454721, 'weight_cat_class_2': 0.5978419077503496}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,492] Trial 435 finished with value: 0.9495601302293645 and parameters: {'weight_lgbm_class_0': 0.05218607411110353, 'weight_lgbm_class_1': 0.9223990627469384, 'weight_lgbm_class_2': 0.5153231821703997, 'weight_xgb_class_0': 0.05501896638379333, 'weight_xgb_class_1': 0.1047965349148269, 'weight_xgb_class_2': 0.5457606177309576, 'weight_cat_class_0': 0.047626405693709795, 'weight_cat_class_1': 0.7512899062074909, 'weight_cat_class_2': 0.6883771258101192}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,512] Trial 436 finished with value: 0.9496293258900375 and parameters: {'weight_lgbm_class_0': 0.047406705466256256, 'weight_lgbm_class_1': 0.9494110237080219, 'weight_lgbm_class_2': 0.523404729709526, 'weight_xgb_class_0': 0.05304287291594942, 'weight_xgb_class_1': 0.10580901047949155, 'weight_xgb_class_2': 0.5309834950939699, 'weight_cat_class_0': 0.013786187947057486, 'weight_cat_class_1': 0.7886545848713253, 'weight_cat_class_2': 0.6919601363852708}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,524] Trial 437 finished with value: 0.9493416120302346 and parameters: {'weight_lgbm_class_0': 0.04987343827714346, 'weight_lgbm_class_1': 0.9493528099294762, 'weight_lgbm_class_2': 0.6128128647919769, 'weight_xgb_class_0': 0.053870479981534256, 'weight_xgb_class_1': 0.11397382657853061, 'weight_xgb_class_2': 0.530463251067292, 'weight_cat_class_0': 0.00020190689896328008, 'weight_cat_class_1': 0.8042471013081108, 'weight_cat_class_2': 0.7631867098082931}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,542] Trial 438 finished with value: 0.9493206873081105 and parameters: {'weight_lgbm_class_0': 0.05163198903702352, 'weight_lgbm_class_1': 0.7750888194611096, 'weight_lgbm_class_2': 0.6070545706624817, 'weight_xgb_class_0': 0.0507553872157816, 'weight_xgb_class_1': 0.10695111553282778, 'weight_xgb_class_2': 0.5325544766546606, 'weight_cat_class_0': 0.0024655585393507755, 'weight_cat_class_1': 0.8828815570449252, 'weight_cat_class_2': 0.7651587304166118}. Best is trial 373 with value: 0.9497190067339387.

Best trial: 373. Best value: 0.949719:  22%|█████████████████████████████▎                                                                                                      | 444/2000 [00:12<00:53, 29.13it/s]

[I 2026-07-03 10:22:48,590] Trial 439 finished with value: 0.9493784630632325 and parameters: {'weight_lgbm_class_0': 0.046406913469668, 'weight_lgbm_class_1': 0.9498725160080587, 'weight_lgbm_class_2': 0.6153290596670405, 'weight_xgb_class_0': 0.05198036808545318, 'weight_xgb_class_1': 0.1065789539949114, 'weight_xgb_class_2': 0.5317143762627762, 'weight_cat_class_0': 0.004481824518254549, 'weight_cat_class_1': 0.7520875297344762, 'weight_cat_class_2': 0.6931304586549785}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,653] Trial 440 finished with value: 0.9497042612859127 and parameters: {'weight_lgbm_class_0': 0.10094345131397135, 'weight_lgbm_class_1': 0.7580626907643083, 'weight_lgbm_class_2': 0.5214636198505174, 'weight_xgb_class_0': 0.052830414563749414, 'weight_xgb_class_1': 0.6815496559394245, 'weight_xgb_class_2': 0.4630246683126489, 'weight_cat_class_0': 0.002736549446898922, 'weight_cat_class_1': 0.8692197886832237, 'weight_cat_class_2': 0.7680914885443952}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,700] Trial 441 finished with value: 0.9494822920165488 and parameters: {'weight_lgbm_class_0': 0.03796950059200718, 'weight_lgbm_class_1': 0.9503629940871037, 'weight_lgbm_class_2': 0.6142113747830729, 'weight_xgb_class_0': 0.13856293820598534, 'weight_xgb_class_1': 0.11389946265489947, 'weight_xgb_class_2': 0.6920263777563779, 'weight_cat_class_0': 0.0027724957006492754, 'weight_cat_class_1': 0.8726902477757237, 'weight_cat_class_2': 0.694191781669659}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,730] Trial 442 finished with value: 0.9489747379872681 and parameters: {'weight_lgbm_class_0': 0.0388180242753052, 'weight_lgbm_class_1': 0.9506938949080865, 'weight_lgbm_class_2': 0.6023248856928751, 'weight_xgb_class_0': 0.04909176553421458, 'weight_xgb_class_1': 0.14050693641307752, 'weight_xgb_class_2': 0.5610793571815804, 'weight_cat_class_0': 0.0031463978501682435, 'weight_cat_class_1': 0.8671559620921141, 'weight_cat_class_2': 0.7671069777832966}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,758] Trial 444 finished with value: 0.9182264824134858 and parameters: {'weight_lgbm_class_0': 0.0010342537831761144, 'weight_lgbm_class_1': 0.9490895817807289, 'weight_lgbm_class_2': 0.5225002733272238, 'weight_xgb_class_0': 0.14196436341162227, 'weight_xgb_class_1': 0.10897838900774452, 'weight_xgb_class_2': 0.5565643905039391, 'weight_cat_class_0': 0.8148285962440149, 'weight_cat_class_1': 0.8732704725163117, 'weight_cat_class_2': 0.6894821448500711}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,760] Trial 443 finished with value: 0.917420021365376 and parameters: {'weight_lgbm_class_0': 0.0394800778645488, 'weight_lgbm_class_1': 0.9469820760623789, 'weight_lgbm_class_2': 0.6126495521971603, 'weight_xgb_class_0': 0.9758480354503403, 'weight_xgb_class_1': 0.1117431701123572, 'weight_xgb_class_2': 0.6914459865978948, 'weight_cat_class_0': 0.001985102749285461, 'weight_cat_class_1': 0.8691183169044975, 'weight_cat_class_2': 0.7203656447457659}. Best is trial 373 with value: 0.9497190067339387.

Best trial: 373. Best value: 0.949719:  23%|█████████████████████████████▊                                                                                                      | 451/2000 [00:13<00:50, 30.40it/s]

[I 2026-07-03 10:22:48,820] Trial 445 finished with value: 0.9211406369430414 and parameters: {'weight_lgbm_class_0': 0.10899023258295953, 'weight_lgbm_class_1': 0.9485429742574558, 'weight_lgbm_class_2': 0.5225335113478574, 'weight_xgb_class_0': 0.7744795969911747, 'weight_xgb_class_1': 0.13524693089411274, 'weight_xgb_class_2': 0.4655038686432784, 'weight_cat_class_0': 0.00034730245078672464, 'weight_cat_class_1': 0.8731153184799073, 'weight_cat_class_2': 0.7706038730731063}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,837] Trial 446 finished with value: 0.9483635366282006 and parameters: {'weight_lgbm_class_0': 0.0001600118435230377, 'weight_lgbm_class_1': 0.9485459738594821, 'weight_lgbm_class_2': 0.5254559718432109, 'weight_xgb_class_0': 0.024442832321456835, 'weight_xgb_class_1': 0.1354646392437035, 'weight_xgb_class_2': 0.5546953532270409, 'weight_cat_class_0': 0.043441192592674024, 'weight_cat_class_1': 0.8728746539656846, 'weight_cat_class_2': 0.7646865992472124}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,878] Trial 447 finished with value: 0.9194822357571918 and parameters: {'weight_lgbm_class_0': 0.10235765653054557, 'weight_lgbm_class_1': 0.9497898822437288, 'weight_lgbm_class_2': 0.47060314119624347, 'weight_xgb_class_0': 0.7474900462207931, 'weight_xgb_class_1': 0.13695656123226665, 'weight_xgb_class_2': 0.5077345019292204, 'weight_cat_class_0': 0.046059163400057675, 'weight_cat_class_1': 0.8741117888108125, 'weight_cat_class_2': 0.714558500126741}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,908] Trial 448 finished with value: 0.9486702879390713 and parameters: {'weight_lgbm_class_0': 0.10489457405313328, 'weight_lgbm_class_1': 0.9513364692385454, 'weight_lgbm_class_2': 0.4723866324321674, 'weight_xgb_class_0': 0.13853481377879864, 'weight_xgb_class_1': 0.14017039512244073, 'weight_xgb_class_2': 0.5634652341282655, 'weight_cat_class_0': 0.0009726492394551509, 'weight_cat_class_1': 0.8723620400241064, 'weight_cat_class_2': 0.7131243772035535}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,952] Trial 449 finished with value: 0.9493246198468251 and parameters: {'weight_lgbm_class_0': 0.0009692756275102368, 'weight_lgbm_class_1': 0.9513907864159605, 'weight_lgbm_class_2': 0.4680972688813516, 'weight_xgb_class_0': 0.13381560170087983, 'weight_xgb_class_1': 0.14305644547721288, 'weight_xgb_class_2': 0.5587861860964115, 'weight_cat_class_0': 0.045236064857642595, 'weight_cat_class_1': 0.9540782608555065, 'weight_cat_class_2': 0.7177709936541368}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:48,983] Trial 450 finished with value: 0.9492210889855989 and parameters: {'weight_lgbm_class_0': 0.011592662655560141, 'weight_lgbm_class_1': 0.9531854837095474, 'weight_lgbm_class_2': 0.46833469080322243, 'weight_xgb_class_0': 0.13854496549806103, 'weight_xgb_class_1': 0.1347894747218026, 'weight_xgb_class_2': 0.4599400169040171, 'weight_cat_class_0': 0.037545711363171363, 'weight_cat_class_1': 0.8669701690347912, 'weight_cat_class_2': 0.7230902519492137}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,006] Trial 451 finished with value: 0.9493073260660688 and parameters: {'weight_lgbm_class_0': 0.013413737525504878, 'weight_lgbm_class_1': 0.9016708648917151, 'weight_lgbm_class_2': 0.7128490883996914, 'weight_xgb_class_0': 0.14325696404340033, 'weight_xgb_class_1': 0.1389174619964444, 'weight_xgb_class_2': 0.5787370575889369, 'weight_cat_class_0': 0.047076989884880516, 'weight_cat_class_1': 0.9580877805499027, 'weight_cat_class_2': 0.7228931085743205}. Best is trial 373 with value: 0.9497190067339387.

Best trial: 373. Best value: 0.949719:  23%|██████████████████████████████▏                                                                                                     | 457/2000 [00:13<00:48, 31.71it/s]

[I 2026-07-03 10:22:49,044] Trial 452 finished with value: 0.9496774679003579 and parameters: {'weight_lgbm_class_0': 0.13147573804069182, 'weight_lgbm_class_1': 0.8033355411285334, 'weight_lgbm_class_2': 0.46742391463553734, 'weight_xgb_class_0': 0.02489953062485309, 'weight_xgb_class_1': 0.7600811018530778, 'weight_xgb_class_2': 0.6929665168285407, 'weight_cat_class_0': 0.0010461235780908915, 'weight_cat_class_1': 0.8742339603871165, 'weight_cat_class_2': 0.7232119303363196}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,077] Trial 453 finished with value: 0.9193413511903886 and parameters: {'weight_lgbm_class_0': 0.09871770771556318, 'weight_lgbm_class_1': 0.7678997644560465, 'weight_lgbm_class_2': 0.47637758678419534, 'weight_xgb_class_0': 0.01985004352080255, 'weight_xgb_class_1': 0.6508842999736826, 'weight_xgb_class_2': 0.466152297283122, 'weight_cat_class_0': 0.8597269778756642, 'weight_cat_class_1': 0.9588237548288113, 'weight_cat_class_2': 0.7187334091076579}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,119] Trial 455 finished with value: 0.9490979660716893 and parameters: {'weight_lgbm_class_0': 0.14068111025778143, 'weight_lgbm_class_1': 0.7540595078513138, 'weight_lgbm_class_2': 0.4640426736498542, 'weight_xgb_class_0': 0.03049751103033653, 'weight_xgb_class_1': 0.13401715926446384, 'weight_xgb_class_2': 0.5043545763942952, 'weight_cat_class_0': 0.036309102237075196, 'weight_cat_class_1': 0.8922252628588406, 'weight_cat_class_2': 0.8085608433999504}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,145] Trial 454 finished with value: 0.9467026321125293 and parameters: {'weight_lgbm_class_0': 0.115170928364531, 'weight_lgbm_class_1': 0.7567996899250206, 'weight_lgbm_class_2': 0.46472868988611743, 'weight_xgb_class_0': 0.18268190854265529, 'weight_xgb_class_1': 0.6636094395460634, 'weight_xgb_class_2': 0.4129406556156322, 'weight_cat_class_0': 0.03939001161010419, 'weight_cat_class_1': 0.8745982797815556, 'weight_cat_class_2': 0.7223371959359941}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,165] Trial 456 finished with value: 0.949302213178024 and parameters: {'weight_lgbm_class_0': 0.1110867664648493, 'weight_lgbm_class_1': 0.7280400330123684, 'weight_lgbm_class_2': 0.4417289056146771, 'weight_xgb_class_0': 0.03150019191010968, 'weight_xgb_class_1': 0.06416302569307056, 'weight_xgb_class_2': 0.5081788661655692, 'weight_cat_class_0': 0.03373568147106787, 'weight_cat_class_1': 0.959225303672225, 'weight_cat_class_2': 0.7322063280667198}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,245] Trial 458 finished with value: 0.9495324963728579 and parameters: {'weight_lgbm_class_0': 0.12026527568438804, 'weight_lgbm_class_1': 0.7581532017533353, 'weight_lgbm_class_2': 0.4394747734343708, 'weight_xgb_class_0': 0.023070055024325145, 'weight_xgb_class_1': 0.6848022649027943, 'weight_xgb_class_2': 0.4626206766487823, 'weight_cat_class_0': 0.026923452850139466, 'weight_cat_class_1': 0.962541054546443, 'weight_cat_class_2': 0.7339046520478595}. Best is trial 373 with value: 0.9497190067339387.

Best trial: 373. Best value: 0.949719:  23%|██████████████████████████████▌                                                                                                     | 464/2000 [00:13<00:52, 29.46it/s]

[I 2026-07-03 10:22:49,269] Trial 457 finished with value: 0.9481949289774377 and parameters: {'weight_lgbm_class_0': 0.016262643593238504, 'weight_lgbm_class_1': 0.8524463602912161, 'weight_lgbm_class_2': 0.4697744542614932, 'weight_xgb_class_0': 0.026406873669445368, 'weight_xgb_class_1': 0.7782071805847082, 'weight_xgb_class_2': 0.6335085043233784, 'weight_cat_class_0': 0.032348964674389316, 'weight_cat_class_1': 0.9574420918688309, 'weight_cat_class_2': 0.7375774878317626}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,311] Trial 459 finished with value: 0.9489095244487166 and parameters: {'weight_lgbm_class_0': 0.13756157198769442, 'weight_lgbm_class_1': 0.7268304336657264, 'weight_lgbm_class_2': 0.4509214379493635, 'weight_xgb_class_0': 0.08113211060684433, 'weight_xgb_class_1': 0.7516368843356097, 'weight_xgb_class_2': 0.6339738736744316, 'weight_cat_class_0': 0.02991878050204852, 'weight_cat_class_1': 0.9522363781579078, 'weight_cat_class_2': 0.735379262226484}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,314] Trial 460 finished with value: 0.9496564875114742 and parameters: {'weight_lgbm_class_0': 0.07069913814079232, 'weight_lgbm_class_1': 0.7569764549173613, 'weight_lgbm_class_2': 0.4412544870901241, 'weight_xgb_class_0': 0.028136186430243147, 'weight_xgb_class_1': 0.8392410686909932, 'weight_xgb_class_2': 0.582097214462725, 'weight_cat_class_0': 0.030186260393021656, 'weight_cat_class_1': 0.8925259387235646, 'weight_cat_class_2': 0.8025002153702727}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,380] Trial 461 finished with value: 0.9494181963986641 and parameters: {'weight_lgbm_class_0': 0.14620620656822245, 'weight_lgbm_class_1': 0.7768143953293538, 'weight_lgbm_class_2': 0.5470810725525658, 'weight_xgb_class_0': 0.023092348672938995, 'weight_xgb_class_1': 0.7429599936316229, 'weight_xgb_class_2': 0.42024719624967416, 'weight_cat_class_0': 0.026623373367043294, 'weight_cat_class_1': 0.9586173425459896, 'weight_cat_class_2': 0.8104343257587596}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,387] Trial 462 finished with value: 0.9496284844606041 and parameters: {'weight_lgbm_class_0': 0.06873023001361542, 'weight_lgbm_class_1': 0.7601005416850609, 'weight_lgbm_class_2': 0.583303851452849, 'weight_xgb_class_0': 0.030770504582806214, 'weight_xgb_class_1': 0.747305628885348, 'weight_xgb_class_2': 0.4163720214443709, 'weight_cat_class_0': 0.027029005065090986, 'weight_cat_class_1': 0.953867349603129, 'weight_cat_class_2': 0.7348316288710508}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,401] Trial 463 finished with value: 0.9494406093153857 and parameters: {'weight_lgbm_class_0': 0.14448561200007076, 'weight_lgbm_class_1': 0.7597504592767671, 'weight_lgbm_class_2': 0.5870309092866262, 'weight_xgb_class_0': 0.028639799199254752, 'weight_xgb_class_1': 0.6397173945644299, 'weight_xgb_class_2': 0.6278171659618118, 'weight_cat_class_0': 0.02410468647495943, 'weight_cat_class_1': 0.956359004779137, 'weight_cat_class_2': 0.7341381986044924}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,450] Trial 464 finished with value: 0.9495285663756002 and parameters: {'weight_lgbm_class_0': 0.13835873151778377, 'weight_lgbm_class_1': 0.7568292975374246, 'weight_lgbm_class_2': 0.43417355003006886, 'weight_xgb_class_0': 0.025544281640638114, 'weight_xgb_class_1': 0.9495189880401984, 'weight_xgb_class_2': 0.6377918577318547, 'weight_cat_class_0': 0.02686453530518978, 'weight_cat_class_1': 0.958650939198614, 'weight_cat_class_2': 0.8022845326505273}. Best is trial 373 with value: 0.9497190067339387.

Best trial: 373. Best value: 0.949719:  24%|███████████████████████████████                                                                                                     | 470/2000 [00:13<00:52, 29.28it/s]

[I 2026-07-03 10:22:49,459] Trial 465 finished with value: 0.9494734388477785 and parameters: {'weight_lgbm_class_0': 0.14119296514592924, 'weight_lgbm_class_1': 0.7831180203769624, 'weight_lgbm_class_2': 0.438928492337647, 'weight_xgb_class_0': 0.02406225879791809, 'weight_xgb_class_1': 0.7649063657454053, 'weight_xgb_class_2': 0.6637666327701943, 'weight_cat_class_0': 0.025472891889733625, 'weight_cat_class_1': 0.896201894464673, 'weight_cat_class_2': 0.6689046968873306}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,526] Trial 466 finished with value: 0.9495002562888045 and parameters: {'weight_lgbm_class_0': 0.14525373830667068, 'weight_lgbm_class_1': 0.982144689321143, 'weight_lgbm_class_2': 0.4450805006287894, 'weight_xgb_class_0': 0.022899391908747777, 'weight_xgb_class_1': 0.7613671003632672, 'weight_xgb_class_2': 0.6732713359263313, 'weight_cat_class_0': 0.022766727108385534, 'weight_cat_class_1': 0.6845996714894433, 'weight_cat_class_2': 0.6443879823722168}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,556] Trial 467 finished with value: 0.949669685859785 and parameters: {'weight_lgbm_class_0': 0.1196536841396349, 'weight_lgbm_class_1': 0.7784789899196262, 'weight_lgbm_class_2': 0.4416740212133352, 'weight_xgb_class_0': 0.019640893572618803, 'weight_xgb_class_1': 0.7390699663854455, 'weight_xgb_class_2': 0.6447589433756507, 'weight_cat_class_0': 0.01989433617258359, 'weight_cat_class_1': 0.9284048166570918, 'weight_cat_class_2': 0.6698227220538795}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,564] Trial 468 finished with value: 0.9072702129275632 and parameters: {'weight_lgbm_class_0': 0.1430011298385565, 'weight_lgbm_class_1': 0.7962260374996256, 'weight_lgbm_class_2': 0.43949589427775876, 'weight_xgb_class_0': 0.012360189274180616, 'weight_xgb_class_1': 0.06951170159514986, 'weight_xgb_class_2': 0.6328289981893632, 'weight_cat_class_0': 0.9518497397294778, 'weight_cat_class_1': 0.9282762260634962, 'weight_cat_class_2': 0.6702635835036936}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,648] Trial 470 finished with value: 0.9494852534707766 and parameters: {'weight_lgbm_class_0': 0.15553120310669452, 'weight_lgbm_class_1': 0.7878336892184726, 'weight_lgbm_class_2': 0.5448766676783815, 'weight_xgb_class_0': 0.017097195094393374, 'weight_xgb_class_1': 0.8418543944168159, 'weight_xgb_class_2': 0.6514148058424589, 'weight_cat_class_0': 0.022031385506686534, 'weight_cat_class_1': 0.9275197255875505, 'weight_cat_class_2': 0.66848260881397}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,663] Trial 469 finished with value: 0.9491267839855149 and parameters: {'weight_lgbm_class_0': 0.07207767476349086, 'weight_lgbm_class_1': 0.9989125112214409, 'weight_lgbm_class_2': 0.5457077932424688, 'weight_xgb_class_0': 0.013910616009484844, 'weight_xgb_class_1': 0.7958970175431251, 'weight_xgb_class_2': 0.7020114398847814, 'weight_cat_class_0': 0.019046738583586156, 'weight_cat_class_1': 0.9190928622313206, 'weight_cat_class_2': 0.6697870073326968}. Best is trial 373 with value: 0.9497190067339387.

Best trial: 373. Best value: 0.949719:  24%|███████████████████████████████▌                                                                                                    | 478/2000 [00:14<00:48, 31.16it/s]

[I 2026-07-03 10:22:49,708] Trial 472 finished with value: 0.9496629053485165 and parameters: {'weight_lgbm_class_0': 0.0988488195122938, 'weight_lgbm_class_1': 0.777744202385518, 'weight_lgbm_class_2': 0.5402845648281985, 'weight_xgb_class_0': 0.012258082233328155, 'weight_xgb_class_1': 0.7248449710104591, 'weight_xgb_class_2': 0.6553299735696131, 'weight_cat_class_0': 0.018933957747643736, 'weight_cat_class_1': 0.6944013959922393, 'weight_cat_class_2': 0.6686419426193623}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,743] Trial 471 finished with value: 0.9493241314571303 and parameters: {'weight_lgbm_class_0': 0.15056907938569475, 'weight_lgbm_class_1': 0.777728674553202, 'weight_lgbm_class_2': 0.5873445667478654, 'weight_xgb_class_0': 0.015549954392958885, 'weight_xgb_class_1': 0.0631231007817254, 'weight_xgb_class_2': 0.654231376315288, 'weight_cat_class_0': 0.024230850486235467, 'weight_cat_class_1': 0.9301117867550491, 'weight_cat_class_2': 0.673219478695064}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,785] Trial 474 finished with value: 0.9166811413504771 and parameters: {'weight_lgbm_class_0': 0.9934929521103409, 'weight_lgbm_class_1': 0.8007664215357544, 'weight_lgbm_class_2': 0.5232926585723562, 'weight_xgb_class_0': 0.07111947344169185, 'weight_xgb_class_1': 0.8283844188328212, 'weight_xgb_class_2': 0.6642553995346915, 'weight_cat_class_0': 0.056482748107879184, 'weight_cat_class_1': 0.9213916696407664, 'weight_cat_class_2': 0.6457342098299066}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,801] Trial 473 finished with value: 0.9433772754821361 and parameters: {'weight_lgbm_class_0': 0.38059918665153153, 'weight_lgbm_class_1': 0.7945553646148593, 'weight_lgbm_class_2': 0.528333305484559, 'weight_xgb_class_0': 0.07164656112039196, 'weight_xgb_class_1': 0.8672927053385201, 'weight_xgb_class_2': 0.7029688702249779, 'weight_cat_class_0': 0.054456525509307276, 'weight_cat_class_1': 0.9244304916284198, 'weight_cat_class_2': 0.6428499700029955}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,825] Trial 475 finished with value: 0.9478319790287761 and parameters: {'weight_lgbm_class_0': 0.07203479103162098, 'weight_lgbm_class_1': 0.19433725291324688, 'weight_lgbm_class_2': 0.523765321738828, 'weight_xgb_class_0': 0.07765170051418484, 'weight_xgb_class_1': 0.06343399641095952, 'weight_xgb_class_2': 0.6974673618529701, 'weight_cat_class_0': 0.05823560991993433, 'weight_cat_class_1': 0.9263064293413545, 'weight_cat_class_2': 0.6510419673789406}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,869] Trial 476 finished with value: 0.9477810620284998 and parameters: {'weight_lgbm_class_0': 0.21493682910780876, 'weight_lgbm_class_1': 0.9819366186084428, 'weight_lgbm_class_2': 0.5389177468135017, 'weight_xgb_class_0': 0.07029116383203504, 'weight_xgb_class_1': 0.7020617857890504, 'weight_xgb_class_2': 0.6613898618456796, 'weight_cat_class_0': 0.05394827130299949, 'weight_cat_class_1': 0.9200976021855368, 'weight_cat_class_2': 0.6480173311911518}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,878] Trial 477 finished with value: 0.9490447594691137 and parameters: {'weight_lgbm_class_0': 0.09800501629010959, 'weight_lgbm_class_1': 0.363792539816566, 'weight_lgbm_class_2': 0.5267050546311772, 'weight_xgb_class_0': 0.07241360659021046, 'weight_xgb_class_1': 0.672260786478673, 'weight_xgb_class_2': 0.7056578487751649, 'weight_cat_class_0': 0.05182189277549505, 'weight_cat_class_1': 0.9244255157250936, 'weight_cat_class_2': 0.6496063883668268}. Best is trial 373 with value: 0.9497190067339387.

[I 2026-07-03 10:22:49,918] Trial 478 finished with value: 0.9477146193317765 and parameters: {'weight_lgbm_class_0': 0.17020147583754258, 'weight_lgbm_class_1': 0.9848151838306628, 'weight_lgbm_class_2': 0.5274757688796545, 'weight_xgb_class_0': 0.07379622276710104, 'weight_xgb_class_1': 0.03402198474140696, 'weight_xgb_class_2': 0.7109246241948357, 'weight_cat_class_0': 0.05182750066721097, 'weight_cat_class_1': 0.9180712576872494, 'weight_cat_class_2': 0.49096452043125194}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,952] Trial 479 finished with value: 0.9472235758397646 and parameters: {'weight_lgbm_class_0': 0.1814099954476399, 'weight_lgbm_class_1': 0.9869823374181845, 'weight_lgbm_class_2': 0.5268146697294377, 'weight_xgb_class_0': 0.07048949739832973, 'weight_xgb_class_1': 0.06536586666169608, 'weight_xgb_class_2': 0.7051510853853258, 'weight_cat_class_0': 0.051835979511615136, 'weight_cat_class_1': 0.5972159856695723, 'weight_cat_class_2': 0.6428655509064435}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:49,972] Trial 480 finished with value: 0.9485403586409286 and parameters: {'weight_lgbm_class_0': 0.17372493338332276, 'weight_lgbm_class_1': 0.9847672801362595, 'weight_lgbm_class_2': 0.522520928163596, 'weight_xgb_class_0': 0.07065496121480035, 'weight_xgb_class_1': 0.8047303137201587, 'weight_xgb_class_2': 0.7039918153015067, 'weight_cat_class_0': 0.05426873738793073, 'weight_cat_class_1': 0.9236784888656466, 'weight_cat_class_2': 0.643417389798405}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,071] Trial 482 finished with value: 0.9486458217132889 and parameters: {'weight_lgbm_class_0': 0.0966492604934169, 'weight_lgbm_class_1': 0.2057447912652437, 'weight_lgbm_class_2': 0.523093103308007, 'weight_xgb_class_0': 0.07111035930274068, 'weight_xgb_class_1': 0.03509424294442152, 'weight_xgb_class_2': 0.7084061659261143, 'weight_cat_class_0': 0.00030617476971944426, 'weight_cat_class_1': 0.8967468774116534, 'weight_cat_class_2': 0.7009575602876337}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,089] Trial 483 finished with value: 0.9480440086911927 and parameters: {'weight_lgbm_class_0': 0.18460871697283684, 'weight_lgbm_class_1': 0.9812728846877059, 'weight_lgbm_class_2': 0.5270590244333588, 'weight_xgb_class_0': 0.07384286933118835, 'weight_xgb_class_1': 0.7169521739101815, 'weight_xgb_class_2': 0.5992911475018918, 'weight_cat_class_0': 0.053222561773851804, 'weight_cat_class_1': 0.894723065421853, 'weight_cat_class_2': 0.6432738771540475}. Best is trial 373 with value: 0.9497190067339387.

Best trial: 373. Best value: 0.949719:  24%|████████████████████████████████▎                                                                                                   | 490/2000 [00:14<00:53, 28.14it/s]

[I 2026-07-03 10:22:50,096] Trial 481 finished with value: 0.9037402604042001 and parameters: {'weight_lgbm_class_0': 0.09666529902220602, 'weight_lgbm_class_1': 0.38025220057277637, 'weight_lgbm_class_2': 0.5235935457660783, 'weight_xgb_class_0': 0.8735569942075918, 'weight_xgb_class_1': 0.07143794976286044, 'weight_xgb_class_2': 0.5802972365879365, 'weight_cat_class_0': 0.051755825776008055, 'weight_cat_class_1': 0.8964531396797459, 'weight_cat_class_2': 0.6430518730158741}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,129] Trial 484 finished with value: 0.9392995636428427 and parameters: {'weight_lgbm_class_0': 0.4057737067973529, 'weight_lgbm_class_1': 0.9777323710580395, 'weight_lgbm_class_2': 0.5251129997438871, 'weight_xgb_class_0': 0.07824013003494779, 'weight_xgb_class_1': 0.03481310719730665, 'weight_xgb_class_2': 0.5927984137374228, 'weight_cat_class_0': 0.05499106659610428, 'weight_cat_class_1': 0.8951170040346217, 'weight_cat_class_2': 0.6420556109710406}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,194] Trial 485 finished with value: 0.9496635703401314 and parameters: {'weight_lgbm_class_0': 0.0312183495781881, 'weight_lgbm_class_1': 0.9827052346578589, 'weight_lgbm_class_2': 0.516041332032328, 'weight_xgb_class_0': 0.0885866490932099, 'weight_xgb_class_1': 0.6850062093874079, 'weight_xgb_class_2': 0.5929158449530998, 'weight_cat_class_0': 0.0489871333673824, 'weight_cat_class_1': 0.8519785146672244, 'weight_cat_class_2': 0.6943877413160394}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,242] Trial 486 finished with value: 0.9463075774070949 and parameters: {'weight_lgbm_class_0': 0.09832095581164213, 'weight_lgbm_class_1': 0.9782909115039599, 'weight_lgbm_class_2': 0.5166641991498094, 'weight_xgb_class_0': 0.15983013972734528, 'weight_xgb_class_1': 0.06827713448274056, 'weight_xgb_class_2': 0.5900218086488109, 'weight_cat_class_0': 0.10388967544268315, 'weight_cat_class_1': 0.887570745185389, 'weight_cat_class_2': 0.6954094675615997}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,258] Trial 488 finished with value: 0.9494489422129466 and parameters: {'weight_lgbm_class_0': 0.02859878912941966, 'weight_lgbm_class_1': 0.9734023184297951, 'weight_lgbm_class_2': 0.4815461980935344, 'weight_xgb_class_0': 0.09204920194632206, 'weight_xgb_class_1': 0.7910700685144076, 'weight_xgb_class_2': 0.7715864344107817, 'weight_cat_class_0': 0.0007266310664800421, 'weight_cat_class_1': 0.8934505799035015, 'weight_cat_class_2': 0.6960310976143581}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,273] Trial 487 finished with value: 0.947218555891359 and parameters: {'weight_lgbm_class_0': 0.09582543372010219, 'weight_lgbm_class_1': 0.9791026768279398, 'weight_lgbm_class_2': 0.4798911800174994, 'weight_xgb_class_0': 0.1622109153890026, 'weight_xgb_class_1': 0.03533218154196748, 'weight_xgb_class_2': 0.5930392423905233, 'weight_cat_class_0': 0.054080621187187004, 'weight_cat_class_1': 0.8527311366918289, 'weight_cat_class_2': 0.6861184131836879}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,288] Trial 489 finished with value: 0.9493567022749856 and parameters: {'weight_lgbm_class_0': 0.030414822901733668, 'weight_lgbm_class_1': 0.9705719940122851, 'weight_lgbm_class_2': 0.48406198284828333, 'weight_xgb_class_0': 0.16874372746709862, 'weight_xgb_class_1': 0.8012060332236545, 'weight_xgb_class_2': 0.5928114984389985, 'weight_cat_class_0': 0.0015427634239160953, 'weight_cat_class_1': 0.8515806172789807, 'weight_cat_class_2': 0.6904832031473132}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,320] Trial 491 finished with value: 0.9491583867182752 and parameters: {'weight_lgbm_class_0': 0.030878527867975465, 'weight_lgbm_class_1': 0.9696837921925048, 'weight_lgbm_class_2': 0.48378443497463647, 'weight_xgb_class_0': 0.16708607465851946, 'weight_xgb_class_1': 0.03782881368581077, 'weight_xgb_class_2': 0.5915262782299247, 'weight_cat_class_0': 0.0009223960574661835, 'weight_cat_class_1': 0.8471125495465642, 'weight_cat_class_2': 0.7076295155474611}. Best is trial 373 with value: 0.9497190067339387.

[I 2026-07-03 10:22:50,340] Trial 490 finished with value: 0.9488773638586251 and parameters: {'weight_lgbm_class_0': 0.03285411120722273, 'weight_lgbm_class_1': 0.966964641921048, 'weight_lgbm_class_2': 0.48595086078984384, 'weight_xgb_class_0': 0.047431937813603886, 'weight_xgb_class_1': 0.09271377718780702, 'weight_xgb_class_2': 0.5918495626293035, 'weight_cat_class_0': 0.0005506722103987703, 'weight_cat_class_1': 0.8922410889843474, 'weight_cat_class_2': 0.6935609285141159}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,379] Trial 492 finished with value: 0.9496296623577766 and parameters: {'weight_lgbm_class_0': 0.03321039607552559, 'weight_lgbm_class_1': 0.9027875802017954, 'weight_lgbm_class_2': 0.4836940394378804, 'weight_xgb_class_0': 0.0909126370370294, 'weight_xgb_class_1': 0.7056626529094615, 'weight_xgb_class_2': 0.5989068356489806, 'weight_cat_class_0': 0.0004268727988713285, 'weight_cat_class_1': 0.8534843617149319, 'weight_cat_class_2': 0.6931203540231946}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,466] Trial 493 finished with value: 0.9487528154022592 and parameters: {'weight_lgbm_class_0': 0.02853878591631516, 'weight_lgbm_class_1': 0.9676837431991617, 'weight_lgbm_class_2': 0.4821644442567042, 'weight_xgb_class_0': 0.04655992503416294, 'weight_xgb_class_1': 0.0907061776095229, 'weight_xgb_class_2': 0.5924294274116559, 'weight_cat_class_0': 0.0003803658487523268, 'weight_cat_class_1': 0.845950362210375, 'weight_cat_class_2': 0.6887386639333282}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,502] Trial 495 finished with value: 0.9494964335903989 and parameters: {'weight_lgbm_class_0': 0.033527315509532994, 'weight_lgbm_class_1': 0.9644587899309907, 'weight_lgbm_class_2': 0.4835438286184777, 'weight_xgb_class_0': 0.04454610188747711, 'weight_xgb_class_1': 0.08879258131665561, 'weight_xgb_class_2': 0.742933544791104, 'weight_cat_class_0': 0.09932694025043817, 'weight_cat_class_1': 0.8509564044957385, 'weight_cat_class_2': 0.6886523715308788}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,511] Trial 494 finished with value: 0.949269943086403 and parameters: {'weight_lgbm_class_0': 0.032145972700559064, 'weight_lgbm_class_1': 0.8975699952578395, 'weight_lgbm_class_2': 0.48581216431054325, 'weight_xgb_class_0': 0.1648176694236777, 'weight_xgb_class_1': 0.09421204068671372, 'weight_xgb_class_2': 0.7736868208104288, 'weight_cat_class_0': 0.00034977905046408, 'weight_cat_class_1': 0.8541688356227342, 'weight_cat_class_2': 0.6902601025657564}. Best is trial 373 with value: 0.9497190067339387.

Best trial: 503. Best value: 0.949768:  25%|█████████████████████████████████▏                                                                                                  | 502/2000 [00:14<00:50, 29.71it/s]

[I 2026-07-03 10:22:50,563] Trial 496 finished with value: 0.9489781674146283 and parameters: {'weight_lgbm_class_0': 0.032218259612234464, 'weight_lgbm_class_1': 0.9996815053348492, 'weight_lgbm_class_2': 0.48491051763386817, 'weight_xgb_class_0': 0.16200728317869617, 'weight_xgb_class_1': 0.5975171111474838, 'weight_xgb_class_2': 0.6065713552973868, 'weight_cat_class_0': 0.002735340262808575, 'weight_cat_class_1': 0.8922593740742883, 'weight_cat_class_2': 0.3438562854498072}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,604] Trial 497 finished with value: 0.9483204904247334 and parameters: {'weight_lgbm_class_0': 0.03203013801094463, 'weight_lgbm_class_1': 0.8957807873539743, 'weight_lgbm_class_2': 0.48146188318881145, 'weight_xgb_class_0': 0.1626695771797576, 'weight_xgb_class_1': 0.6140862054812906, 'weight_xgb_class_2': 0.6142025162117917, 'weight_cat_class_0': 0.09660447683685326, 'weight_cat_class_1': 0.8532814530547467, 'weight_cat_class_2': 0.6877347983562941}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,620] Trial 498 finished with value: 0.9492436561041524 and parameters: {'weight_lgbm_class_0': 0.03235862242877813, 'weight_lgbm_class_1': 0.9028480766595306, 'weight_lgbm_class_2': 0.5803519061540543, 'weight_xgb_class_0': 0.04512038318340578, 'weight_xgb_class_1': 0.08773684051470074, 'weight_xgb_class_2': 0.5773447706810626, 'weight_cat_class_0': 0.016744176053773728, 'weight_cat_class_1': 0.8508365846328433, 'weight_cat_class_2': 0.6918919827160748}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,667] Trial 500 finished with value: 0.949153789508436 and parameters: {'weight_lgbm_class_0': 0.06942334278961027, 'weight_lgbm_class_1': 0.8961221991783008, 'weight_lgbm_class_2': 0.40957851531709777, 'weight_xgb_class_0': 0.045541661811056115, 'weight_xgb_class_1': 0.5829581986246932, 'weight_xgb_class_2': 0.5738878059093223, 'weight_cat_class_0': 0.0999201411135431, 'weight_cat_class_1': 0.9836599643490933, 'weight_cat_class_2': 0.6858014819496722}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,670] Trial 499 finished with value: 0.9487576358983739 and parameters: {'weight_lgbm_class_0': 0.015321850795811514, 'weight_lgbm_class_1': 0.9012956267890482, 'weight_lgbm_class_2': 0.5813279624140272, 'weight_xgb_class_0': 0.04790099186232181, 'weight_xgb_class_1': 0.08871372298189392, 'weight_xgb_class_2': 0.5731316718753517, 'weight_cat_class_0': 0.015267304052178673, 'weight_cat_class_1': 0.8564086264255653, 'weight_cat_class_2': 0.6935385722719055}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,712] Trial 501 finished with value: 0.9496568005405219 and parameters: {'weight_lgbm_class_0': 0.07093520684918048, 'weight_lgbm_class_1': 0.9058035871814348, 'weight_lgbm_class_2': 0.554685184103158, 'weight_xgb_class_0': 0.044507762927463085, 'weight_xgb_class_1': 0.6163116307053419, 'weight_xgb_class_2': 0.5627265769800072, 'weight_cat_class_0': 0.015494019022759487, 'weight_cat_class_1': 0.9912757096974842, 'weight_cat_class_2': 0.38216105018401003}. Best is trial 373 with value: 0.9497190067339387.
[I 2026-07-03 10:22:50,746] Trial 503 finished with value: 0.9497676925748403 and parameters: {'weight_lgbm_class_0': 0.06686152313056612, 'weight_lgbm_class_1': 0.9289037937237417, 'weight_lgbm_class_2': 0.5844589056753553, 'weight_xgb_class_0': 0.045980837963136664, 'weight_xgb_class_1': 0.2608328763284878, 'weight_xgb_class_2': 0.5686291336048178, 'weight_cat_class_0': 0.01845416348598921, 'weight_cat_class_1': 0.9833796567922864, 'weight_cat_class_2': 0.5757040387034328}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  25%|█████████████████████████████████▌                                                                                                  | 509/2000 [00:15<00:52, 28.46it/s]

[I 2026-07-03 10:22:50,795] Trial 502 finished with value: 0.9493497585336025 and parameters: {'weight_lgbm_class_0': 0.06575279211115308, 'weight_lgbm_class_1': 0.8350563014979597, 'weight_lgbm_class_2': 0.5491206831597557, 'weight_xgb_class_0': 0.04719652679936104, 'weight_xgb_class_1': 0.5856761780427441, 'weight_xgb_class_2': 0.7497687477064799, 'weight_cat_class_0': 0.09553266214897724, 'weight_cat_class_1': 0.9851696182485267, 'weight_cat_class_2': 0.6715122347461254}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:50,816] Trial 504 finished with value: 0.9496717661112685 and parameters: {'weight_lgbm_class_0': 0.0011351350903951035, 'weight_lgbm_class_1': 0.9995310187463476, 'weight_lgbm_class_2': 0.5529178452721001, 'weight_xgb_class_0': 0.04437645059565481, 'weight_xgb_class_1': 0.6003056684238242, 'weight_xgb_class_2': 0.5645734081251778, 'weight_cat_class_0': 0.09268330265687146, 'weight_cat_class_1': 0.9428421845166486, 'weight_cat_class_2': 0.5732864058982582}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:50,881] Trial 505 finished with value: 0.948605385407412 and parameters: {'weight_lgbm_class_0': 0.07026231237952674, 'weight_lgbm_class_1': 0.8253056437855316, 'weight_lgbm_class_2': 0.5769663209572302, 'weight_xgb_class_0': 0.12442831846710074, 'weight_xgb_class_1': 0.9911767819524024, 'weight_xgb_class_2': 0.5608725636413978, 'weight_cat_class_0': 0.08864018755018928, 'weight_cat_class_1': 0.9430859544099579, 'weight_cat_class_2': 0.6727444651345147}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:50,914] Trial 506 finished with value: 0.9496523230969162 and parameters: {'weight_lgbm_class_0': 0.0671086887221066, 'weight_lgbm_class_1': 0.9259885120723873, 'weight_lgbm_class_2': 0.41067471911270903, 'weight_xgb_class_0': 0.04766681813094298, 'weight_xgb_class_1': 0.1498420562699591, 'weight_xgb_class_2': 0.5565019972118223, 'weight_cat_class_0': 0.016893246239780384, 'weight_cat_class_1': 0.9431324967944821, 'weight_cat_class_2': 0.6670830970469952}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:50,922] Trial 507 finished with value: 0.9490463661930576 and parameters: {'weight_lgbm_class_0': 0.06745950450223409, 'weight_lgbm_class_1': 0.9299292699767772, 'weight_lgbm_class_2': 0.5793185051929, 'weight_xgb_class_0': 0.12713678129929554, 'weight_xgb_class_1': 0.15466489951105925, 'weight_xgb_class_2': 0.5706789627696258, 'weight_cat_class_0': 0.027429145677152905, 'weight_cat_class_1': 0.9016946639795729, 'weight_cat_class_2': 0.5777484357514424}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:50,971] Trial 508 finished with value: 0.9492359415447676 and parameters: {'weight_lgbm_class_0': 0.0701920791801162, 'weight_lgbm_class_1': 0.9255799580172346, 'weight_lgbm_class_2': 0.5530523330381629, 'weight_xgb_class_0': 1.0474997468819247e-05, 'weight_xgb_class_1': 0.15634350606818212, 'weight_xgb_class_2': 0.5618158701953306, 'weight_cat_class_0': 0.02675218018509984, 'weight_cat_class_1': 0.9447067223065656, 'weight_cat_class_2': 0.6686230526581428}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,011] Trial 510 finished with value: 0.949018555429102 and parameters: {'weight_lgbm_class_0': 0.06653799216647202, 'weight_lgbm_class_1': 0.8236545312934194, 'weight_lgbm_class_2': 0.5731900765520559, 'weight_xgb_class_0': 0.12276166347012762, 'weight_xgb_class_1': 0.1542532358450043, 'weight_xgb_class_2': 0.5606107454024892, 'weight_cat_class_0': 0.03614253806579432, 'weight_cat_class_1': 0.9885129342104929, 'weight_cat_class_2': 0.661313788054322}. Best is trial 503 with value: 0.9497676925748403.

[I 2026-07-03 10:22:51,026] Trial 509 finished with value: 0.9495273256824647 and parameters: {'weight_lgbm_class_0': 0.0008412517108625384, 'weight_lgbm_class_1': 0.9194966814283049, 'weight_lgbm_class_2': 0.5524388228956097, 'weight_xgb_class_0': 0.12573581238150977, 'weight_xgb_class_1': 0.1529707862348628, 'weight_xgb_class_2': 0.3694895986430725, 'weight_cat_class_0': 0.03279050260375859, 'weight_cat_class_1': 0.9953242984499793, 'weight_cat_class_2': 0.6629319846297207}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,057] Trial 511 finished with value: 0.9496150883409221 and parameters: {'weight_lgbm_class_0': 0.0023199489398356343, 'weight_lgbm_class_1': 0.9276866416715515, 'weight_lgbm_class_2': 0.5525249423776826, 'weight_xgb_class_0': 0.12147390075341624, 'weight_xgb_class_1': 0.15154025726828285, 'weight_xgb_class_2': 0.5115439840584237, 'weight_cat_class_0': 0.034500907627914815, 'weight_cat_class_1': 0.938761970559768, 'weight_cat_class_2': 0.6661137858797304}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,111] Trial 512 finished with value: 0.949335889343911 and parameters: {'weight_lgbm_class_0': 0.003944565425581276, 'weight_lgbm_class_1': 0.929705885845878, 'weight_lgbm_class_2': 0.550345425724898, 'weight_xgb_class_0': 0.1293425454736414, 'weight_xgb_class_1': 0.15210873124968166, 'weight_xgb_class_2': 0.3657797283133388, 'weight_cat_class_0': 0.034573980876248474, 'weight_cat_class_1': 0.9075334346782625, 'weight_cat_class_2': 0.5692421398036148}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,133] Trial 513 finished with value: 0.9489551725928184 and parameters: {'weight_lgbm_class_0': 0.07025392571920126, 'weight_lgbm_class_1': 0.9304525901423621, 'weight_lgbm_class_2': 0.5932173039983987, 'weight_xgb_class_0': 0.12924153319236004, 'weight_xgb_class_1': 0.23664675535556154, 'weight_xgb_class_2': 0.5151333144644447, 'weight_cat_class_0': 0.030845434201210796, 'weight_cat_class_1': 0.99246252753806, 'weight_cat_class_2': 0.5839275100557124}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,172] Trial 514 finished with value: 0.941498673449606 and parameters: {'weight_lgbm_class_0': 0.4658595887412757, 'weight_lgbm_class_1': 0.930911366923526, 'weight_lgbm_class_2': 0.5802316072587503, 'weight_xgb_class_0': 0.00043995710353814804, 'weight_xgb_class_1': 0.22334305146790842, 'weight_xgb_class_2': 0.354525517306095, 'weight_cat_class_0': 0.035100623111325426, 'weight_cat_class_1': 0.9385448570322239, 'weight_cat_class_2': 0.7543384573210514}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,221] Trial 515 finished with value: 0.948685328567569 and parameters: {'weight_lgbm_class_0': 0.12206341774901594, 'weight_lgbm_class_1': 0.9282535113478677, 'weight_lgbm_class_2': 0.5886625970025474, 'weight_xgb_class_0': 0.12407530647833441, 'weight_xgb_class_1': 0.12095442137206441, 'weight_xgb_class_2': 0.871738845479973, 'weight_cat_class_0': 0.03288196840091575, 'weight_cat_class_1': 0.9965287548748113, 'weight_cat_class_2': 0.7467264287267679}. Best is trial 503 with value: 0.9497676925748403.

[I 2026-07-03 10:22:51,225] Trial 516 finished with value: 0.9489259314650728 and parameters: {'weight_lgbm_class_0': 0.06601185092831859, 'weight_lgbm_class_1': 0.9300847760768925, 'weight_lgbm_class_2': 0.5943507504089567, 'weight_xgb_class_0': 0.12519598529183035, 'weight_xgb_class_1': 0.2300449116987826, 'weight_xgb_class_2': 0.5167794867461332, 'weight_cat_class_0': 0.03282293407642066, 'weight_cat_class_1': 0.9970476374244889, 'weight_cat_class_2': 0.5407284861754018}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,264] Trial 517 finished with value: 0.9487615113412851 and parameters: {'weight_lgbm_class_0': 0.11853675098063116, 'weight_lgbm_class_1': 0.8718015583947141, 'weight_lgbm_class_2': 0.573524562232852, 'weight_xgb_class_0': 0.09729524904569306, 'weight_xgb_class_1': 0.23900295693026885, 'weight_xgb_class_2': 0.5064624957351695, 'weight_cat_class_0': 0.03399575459026893, 'weight_cat_class_1': 0.9076629862119997, 'weight_cat_class_2': 0.7149348551705658}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,303] Trial 518 finished with value: 0.949569057658645 and parameters: {'weight_lgbm_class_0': 7.478209530708212e-05, 'weight_lgbm_class_1': 0.8713138605355506, 'weight_lgbm_class_2': 0.5974762259968387, 'weight_xgb_class_0': 0.12478032617833017, 'weight_xgb_class_1': 0.12442039898406004, 'weight_xgb_class_2': 0.5127007179083607, 'weight_cat_class_0': 0.0344201297875521, 'weight_cat_class_1': 0.9042961905740994, 'weight_cat_class_2': 0.5275709611856858}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,364] Trial 520 finished with value: 0.9484120387683678 and parameters: {'weight_lgbm_class_0': 0.12306332621941546, 'weight_lgbm_class_1': 0.9346483500358584, 'weight_lgbm_class_2': 0.5959003304552446, 'weight_xgb_class_0': 0.12376046425430581, 'weight_xgb_class_1': 0.24816082897676445, 'weight_xgb_class_2': 0.5131354748173141, 'weight_cat_class_0': 0.035499485789976734, 'weight_cat_class_1': 0.9945463072711624, 'weight_cat_class_2': 0.7545040322338255}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,371] Trial 519 finished with value: 0.94931116690934 and parameters: {'weight_lgbm_class_0': 0.000590323272008768, 'weight_lgbm_class_1': 0.9336211397898239, 'weight_lgbm_class_2': 0.6624945275527482, 'weight_xgb_class_0': 0.09330570352651474, 'weight_xgb_class_1': 0.11709582616215944, 'weight_xgb_class_2': 0.8777323478296667, 'weight_cat_class_0': 0.03333004765083752, 'weight_cat_class_1': 0.9989699511791509, 'weight_cat_class_2': 0.756990227072387}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,439] Trial 523 finished with value: 0.9494371401470949 and parameters: {'weight_lgbm_class_0': 0.08347464021449752, 'weight_lgbm_class_1': 0.9411857119882068, 'weight_lgbm_class_2': 0.6307368538172398, 'weight_xgb_class_0': 0.10029334101209118, 'weight_xgb_class_1': 0.27333315272979014, 'weight_xgb_class_2': 0.865196346090849, 'weight_cat_class_0': 0.01733718112019926, 'weight_cat_class_1': 0.9052748130821626, 'weight_cat_class_2': 0.554721155833411}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  26%|██████████████████████████████████▊                                                                                                 | 528/2000 [00:15<00:47, 31.14it/s]

[I 2026-07-03 10:22:51,445] Trial 521 finished with value: 0.9486617668770986 and parameters: {'weight_lgbm_class_0': 0.11995084062455617, 'weight_lgbm_class_1': 0.8660851949160137, 'weight_lgbm_class_2': 0.5870307049695064, 'weight_xgb_class_0': 0.09629198214658746, 'weight_xgb_class_1': 0.1199665813114156, 'weight_xgb_class_2': 0.4954508526553295, 'weight_cat_class_0': 0.019804501434453406, 'weight_cat_class_1': 0.9102824193271275, 'weight_cat_class_2': 0.5523661715213941}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,452] Trial 522 finished with value: 0.949609505500545 and parameters: {'weight_lgbm_class_0': 0.0008920183880488385, 'weight_lgbm_class_1': 0.8602288955273659, 'weight_lgbm_class_2': 0.6562792781390117, 'weight_xgb_class_0': 0.09340102122941676, 'weight_xgb_class_1': 0.24015442467675718, 'weight_xgb_class_2': 0.5169216204147993, 'weight_cat_class_0': 0.01928352865534702, 'weight_cat_class_1': 0.9082946327113411, 'weight_cat_class_2': 0.5642911356672783}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,529] Trial 524 finished with value: 0.9491903666925241 and parameters: {'weight_lgbm_class_0': 0.09617600087381827, 'weight_lgbm_class_1': 0.8716364509045332, 'weight_lgbm_class_2': 0.5830837684786776, 'weight_xgb_class_0': 0.09278008656403489, 'weight_xgb_class_1': 0.11680608078125516, 'weight_xgb_class_2': 0.5188271188167094, 'weight_cat_class_0': 0.01716296305862703, 'weight_cat_class_1': 0.8804027090132766, 'weight_cat_class_2': 0.7145159754838792}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,546] Trial 525 finished with value: 0.9488612178178677 and parameters: {'weight_lgbm_class_0': 0.12259502061315869, 'weight_lgbm_class_1': 0.8714146174112367, 'weight_lgbm_class_2': 0.5068555195743932, 'weight_xgb_class_0': 0.09131196476677461, 'weight_xgb_class_1': 0.11892226747021413, 'weight_xgb_class_2': 0.4819381771101344, 'weight_cat_class_0': 0.018278385107692086, 'weight_cat_class_1': 0.8836881562438831, 'weight_cat_class_2': 0.7146727307458}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,549] Trial 526 finished with value: 0.9478715834843138 and parameters: {'weight_lgbm_class_0': 0.09572576227337505, 'weight_lgbm_class_1': 0.85564366560046, 'weight_lgbm_class_2': 0.5043657724313643, 'weight_xgb_class_0': 0.09835967853355745, 'weight_xgb_class_1': 0.27425271340598145, 'weight_xgb_class_2': 0.5126771561141725, 'weight_cat_class_0': 0.01695516149132702, 'weight_cat_class_1': 0.8786215238785183, 'weight_cat_class_2': 0.16607653988025678}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,595] Trial 527 finished with value: 0.9495023205473698 and parameters: {'weight_lgbm_class_0': 2.1100171032413517e-05, 'weight_lgbm_class_1': 0.9569922670587707, 'weight_lgbm_class_2': 0.6586280408732773, 'weight_xgb_class_0': 0.09655355120664075, 'weight_xgb_class_1': 0.11907311314964376, 'weight_xgb_class_2': 0.5026398709682333, 'weight_cat_class_0': 0.01576084016303871, 'weight_cat_class_1': 0.8812358292399205, 'weight_cat_class_2': 0.7157389382189563}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,666] Trial 528 finished with value: 0.9493143157133206 and parameters: {'weight_lgbm_class_0': 0.09510129490783908, 'weight_lgbm_class_1': 0.9587034823677583, 'weight_lgbm_class_2': 0.6484296025537152, 'weight_xgb_class_0': 0.09047856009595341, 'weight_xgb_class_1': 0.12045686590032523, 'weight_xgb_class_2': 0.48218035857795627, 'weight_cat_class_0': 0.015300791078096145, 'weight_cat_class_1': 0.8853628561949846, 'weight_cat_class_2': 0.7100891127780801}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  27%|███████████████████████████████████▎                                                                                                | 535/2000 [00:16<00:47, 31.07it/s]

[I 2026-07-03 10:22:51,667] Trial 529 finished with value: 0.9490140754768852 and parameters: {'weight_lgbm_class_0': 0.09454075424135111, 'weight_lgbm_class_1': 0.9528298234776962, 'weight_lgbm_class_2': 0.5082113559316385, 'weight_xgb_class_0': 0.09691312729453469, 'weight_xgb_class_1': 0.11700088271070791, 'weight_xgb_class_2': 0.5463126368944439, 'weight_cat_class_0': 0.016516450152579305, 'weight_cat_class_1': 0.8778308283592652, 'weight_cat_class_2': 0.5588166677673321}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,730] Trial 531 finished with value: 0.9493325444389038 and parameters: {'weight_lgbm_class_0': 0.0893402570248695, 'weight_lgbm_class_1': 0.9586736121800297, 'weight_lgbm_class_2': 0.5096685542018313, 'weight_xgb_class_0': 0.08892654833543566, 'weight_xgb_class_1': 0.513547427902989, 'weight_xgb_class_2': 0.545433019560713, 'weight_cat_class_0': 0.01817416995648312, 'weight_cat_class_1': 0.8792228739547145, 'weight_cat_class_2': 0.7138505146990288}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,746] Trial 530 finished with value: 0.9496286920700651 and parameters: {'weight_lgbm_class_0': 0.01591800451230626, 'weight_lgbm_class_1': 0.958406433576368, 'weight_lgbm_class_2': 0.6526828465308486, 'weight_xgb_class_0': 0.08891581052784804, 'weight_xgb_class_1': 0.2595435184545964, 'weight_xgb_class_2': 0.5485766330264594, 'weight_cat_class_0': 0.016615517418345285, 'weight_cat_class_1': 0.8805403042687716, 'weight_cat_class_2': 0.714557980357506}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,781] Trial 532 finished with value: 0.949183004733232 and parameters: {'weight_lgbm_class_0': 0.08803004004717627, 'weight_lgbm_class_1': 0.711108426964701, 'weight_lgbm_class_2': 0.627830505252864, 'weight_xgb_class_0': 0.092150070463031, 'weight_xgb_class_1': 0.11582220681401349, 'weight_xgb_class_2': 0.47966612109896206, 'weight_cat_class_0': 0.01641411114641112, 'weight_cat_class_1': 0.8735879363836281, 'weight_cat_class_2': 0.7162181635652136}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,813] Trial 533 finished with value: 0.9489773564893272 and parameters: {'weight_lgbm_class_0': 0.09177021362337875, 'weight_lgbm_class_1': 0.9598992052724495, 'weight_lgbm_class_2': 0.5070622907725029, 'weight_xgb_class_0': 0.06610858200428188, 'weight_xgb_class_1': 0.06800181073221723, 'weight_xgb_class_2': 0.48067486737889664, 'weight_cat_class_0': 0.06565199037517534, 'weight_cat_class_1': 0.8746151583859245, 'weight_cat_class_2': 0.7138144403935639}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,848] Trial 534 finished with value: 0.949639630483468 and parameters: {'weight_lgbm_class_0': 0.09418829831117047, 'weight_lgbm_class_1': 0.9558480133478842, 'weight_lgbm_class_2': 0.5119939163098997, 'weight_xgb_class_0': 0.06726254945547368, 'weight_xgb_class_1': 0.061769811166439426, 'weight_xgb_class_2': 0.48968834432876385, 'weight_cat_class_0': 0.00037247616722130533, 'weight_cat_class_1': 0.8787147673598226, 'weight_cat_class_2': 0.7166780756230267}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:51,875] Trial 535 finished with value: 0.9390025413769432 and parameters: {'weight_lgbm_class_0': 0.08883447864300581, 'weight_lgbm_class_1': 0.9658298376322892, 'weight_lgbm_class_2': 0.5067938215207212, 'weight_xgb_class_0': 0.06144897439595498, 'weight_xgb_class_1': 0.8750582760030345, 'weight_xgb_class_2': 0.48492722063745436, 'weight_cat_class_0': 0.46763088154319854, 'weight_cat_class_1': 0.8824386501397055, 'weight_cat_class_2': 0.7197695800849953}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  27%|███████████████████████████████████▊                                                                                                | 543/2000 [00:16<00:50, 28.86it/s]

[I 2026-07-03 10:22:51,994] Trial 537 finished with value: 0.9496450363725092 and parameters: {'weight_lgbm_class_0': 0.0175493432309531, 'weight_lgbm_class_1': 0.9601992640272866, 'weight_lgbm_class_2': 0.5080102553777185, 'weight_xgb_class_0': 0.06236797654657114, 'weight_xgb_class_1': 0.17618813240909756, 'weight_xgb_class_2': 0.5461988497548458, 'weight_cat_class_0': 0.06801180190628858, 'weight_cat_class_1': 0.9595312641152854, 'weight_cat_class_2': 0.7151949882923261}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,011] Trial 536 finished with value: 0.9394432528989687 and parameters: {'weight_lgbm_class_0': 0.01703317474228135, 'weight_lgbm_class_1': 0.9590815902535574, 'weight_lgbm_class_2': 0.45522149644671434, 'weight_xgb_class_0': 0.4744292799681038, 'weight_xgb_class_1': 0.1770659920792325, 'weight_xgb_class_2': 0.6855654454713672, 'weight_cat_class_0': 0.06590648484917322, 'weight_cat_class_1': 0.9731085758195641, 'weight_cat_class_2': 0.7211956662378356}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,037] Trial 538 finished with value: 0.949521312097887 and parameters: {'weight_lgbm_class_0': 0.04365370868655663, 'weight_lgbm_class_1': 0.9523411034085058, 'weight_lgbm_class_2': 0.5443046656849647, 'weight_xgb_class_0': 0.06190907510655903, 'weight_xgb_class_1': 0.06251287458883918, 'weight_xgb_class_2': 0.5508156256231324, 'weight_cat_class_0': 0.06328778050351203, 'weight_cat_class_1': 0.9617891005085609, 'weight_cat_class_2': 0.6289075162775579}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,075] Trial 539 finished with value: 0.9414372247129604 and parameters: {'weight_lgbm_class_0': 0.3200973017649803, 'weight_lgbm_class_1': 0.7346813410126789, 'weight_lgbm_class_2': 0.46040382835621896, 'weight_xgb_class_0': 0.06362029969115941, 'weight_xgb_class_1': 0.062037008075154526, 'weight_xgb_class_2': 0.54452419645405, 'weight_cat_class_0': 0.06989739493688374, 'weight_cat_class_1': 0.9646279294658308, 'weight_cat_class_2': 0.6256452421577587}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,090] Trial 540 finished with value: 0.9493843129934773 and parameters: {'weight_lgbm_class_0': 0.046124280271275644, 'weight_lgbm_class_1': 0.9602080946075736, 'weight_lgbm_class_2': 0.45647259667889006, 'weight_xgb_class_0': 0.060290327904852996, 'weight_xgb_class_1': 0.06840006014415063, 'weight_xgb_class_2': 0.6819528989835877, 'weight_cat_class_0': 0.073120286554656, 'weight_cat_class_1': 0.9582566073208908, 'weight_cat_class_2': 0.6290557856230894}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,106] Trial 541 finished with value: 0.9493341532318126 and parameters: {'weight_lgbm_class_0': 0.0462572455477772, 'weight_lgbm_class_1': 0.9633380524782573, 'weight_lgbm_class_2': 0.45447283121762233, 'weight_xgb_class_0': 0.06685447140473755, 'weight_xgb_class_1': 0.2987445303879956, 'weight_xgb_class_2': 0.5361043970512828, 'weight_cat_class_0': 0.06988635320472941, 'weight_cat_class_1': 0.9607731660212258, 'weight_cat_class_2': 0.6235942417322154}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,121] Trial 542 finished with value: 0.9493912280843947 and parameters: {'weight_lgbm_class_0': 0.04749898815039879, 'weight_lgbm_class_1': 0.7100491118810774, 'weight_lgbm_class_2': 0.4611085360148508, 'weight_xgb_class_0': 0.06260361611619276, 'weight_xgb_class_1': 0.17783853676338712, 'weight_xgb_class_2': 0.6206462779522713, 'weight_cat_class_0': 0.06045558547291481, 'weight_cat_class_1': 0.9699222777377592, 'weight_cat_class_2': 0.6255602514935111}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,183] Trial 543 finished with value: 0.9493450946398161 and parameters: {'weight_lgbm_class_0': 0.04792665564954869, 'weight_lgbm_class_1': 0.7285634110514618, 'weight_lgbm_class_2': 0.7869030595479274, 'weight_xgb_class_0': 0.06291866040372704, 'weight_xgb_class_1': 0.06840546248072821, 'weight_xgb_class_2': 0.6212171248278228, 'weight_cat_class_0': 0.07550107948846095, 'weight_cat_class_1': 0.9705030122118636, 'weight_cat_class_2': 0.627926506034652}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  27%|████████████████████████████████████▏                                                                                               | 548/2000 [00:16<00:46, 31.30it/s]

[I 2026-07-03 10:22:52,206] Trial 544 finished with value: 0.9494462941448959 and parameters: {'weight_lgbm_class_0': 0.04483991012317896, 'weight_lgbm_class_1': 0.725722394703855, 'weight_lgbm_class_2': 0.5446627324080082, 'weight_xgb_class_0': 0.06445158625250083, 'weight_xgb_class_1': 0.30757641944362574, 'weight_xgb_class_2': 0.6787309082086889, 'weight_cat_class_0': 0.0697289201452096, 'weight_cat_class_1': 0.966479069086207, 'weight_cat_class_2': 0.6245176024935072}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,226] Trial 545 finished with value: 0.949390896923513 and parameters: {'weight_lgbm_class_0': 0.04866231633548277, 'weight_lgbm_class_1': 0.969178812603117, 'weight_lgbm_class_2': 0.5453703516445297, 'weight_xgb_class_0': 0.06257216987650858, 'weight_xgb_class_1': 0.17695058576794082, 'weight_xgb_class_2': 0.5453490007032304, 'weight_cat_class_0': 0.06906429908790737, 'weight_cat_class_1': 0.9672666256533786, 'weight_cat_class_2': 0.6190332187398605}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,251] Trial 546 finished with value: 0.9494498610075356 and parameters: {'weight_lgbm_class_0': 0.048312285805044534, 'weight_lgbm_class_1': 0.9686189263074595, 'weight_lgbm_class_2': 0.4577541471623313, 'weight_xgb_class_0': 0.06138516970552039, 'weight_xgb_class_1': 0.32013547614933796, 'weight_xgb_class_2': 0.6202036610829478, 'weight_cat_class_0': 0.0687681527448189, 'weight_cat_class_1': 0.9601487837869571, 'weight_cat_class_2': 0.6304329701814197}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,294] Trial 547 finished with value: 0.949593390719265 and parameters: {'weight_lgbm_class_0': 0.04673795311137504, 'weight_lgbm_class_1': 0.9094173644295327, 'weight_lgbm_class_2': 0.4552427335600894, 'weight_xgb_class_0': 0.028277558679706574, 'weight_xgb_class_1': 0.1772639403680186, 'weight_xgb_class_2': 0.6163436812016068, 'weight_cat_class_0': 0.07330059293897222, 'weight_cat_class_1': 0.9614157955909678, 'weight_cat_class_2': 0.6321937396927819}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,400] Trial 548 finished with value: 0.9497228261249672 and parameters: {'weight_lgbm_class_0': 0.04449436591397528, 'weight_lgbm_class_1': 0.916305777596202, 'weight_lgbm_class_2': 0.4587609061035998, 'weight_xgb_class_0': 0.03393252992003082, 'weight_xgb_class_1': 0.17498672450542152, 'weight_xgb_class_2': 0.6826455682023107, 'weight_cat_class_0': 0.0472294689436962, 'weight_cat_class_1': 0.9660438786302596, 'weight_cat_class_2': 0.6275508479483678}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  28%|████████████████████████████████████▊                                                                                               | 557/2000 [00:16<00:51, 28.02it/s]

[I 2026-07-03 10:22:52,443] Trial 549 finished with value: 0.9493359565910464 and parameters: {'weight_lgbm_class_0': 0.04827225435426087, 'weight_lgbm_class_1': 0.9096270187579032, 'weight_lgbm_class_2': 0.549559385978316, 'weight_xgb_class_0': 0.03316910831400056, 'weight_xgb_class_1': 0.3136879280696737, 'weight_xgb_class_2': 0.574468660943629, 'weight_cat_class_0': 0.05096450026052137, 'weight_cat_class_1': 0.9308853270397774, 'weight_cat_class_2': 0.04890318239386032}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,456] Trial 550 finished with value: 0.9496330512309434 and parameters: {'weight_lgbm_class_0': 0.04315987609667339, 'weight_lgbm_class_1': 0.9069914896834348, 'weight_lgbm_class_2': 0.5481881299606113, 'weight_xgb_class_0': 0.03790459600661934, 'weight_xgb_class_1': 0.09684870368232872, 'weight_xgb_class_2': 0.625386734437829, 'weight_cat_class_0': 0.04594101414588978, 'weight_cat_class_1': 0.927996167093803, 'weight_cat_class_2': 0.6548359361655456}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,466] Trial 551 finished with value: 0.9496036300211531 and parameters: {'weight_lgbm_class_0': 0.052366675225517224, 'weight_lgbm_class_1': 0.9035556033411285, 'weight_lgbm_class_2': 0.539605981561159, 'weight_xgb_class_0': 0.04055898427961478, 'weight_xgb_class_1': 0.956822820072349, 'weight_xgb_class_2': 0.5779029132484458, 'weight_cat_class_0': 0.04563729083778707, 'weight_cat_class_1': 0.9283843105914447, 'weight_cat_class_2': 0.515359687631228}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,500] Trial 552 finished with value: 0.9496444882398961 and parameters: {'weight_lgbm_class_0': 0.03942066019003681, 'weight_lgbm_class_1': 0.900437082526955, 'weight_lgbm_class_2': 0.543733626523246, 'weight_xgb_class_0': 0.03189258920697244, 'weight_xgb_class_1': 0.13649229364669713, 'weight_xgb_class_2': 0.5779057118377973, 'weight_cat_class_0': 0.04604932694966604, 'weight_cat_class_1': 0.9291444514355117, 'weight_cat_class_2': 0.6512981638910801}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,561] Trial 553 finished with value: 0.9493043757733162 and parameters: {'weight_lgbm_class_0': 0.018619663282232406, 'weight_lgbm_class_1': 0.9985462472670755, 'weight_lgbm_class_2': 0.543872910532763, 'weight_xgb_class_0': 0.0320283838012836, 'weight_xgb_class_1': 0.020417302832446235, 'weight_xgb_class_2': 0.5779735827718295, 'weight_cat_class_0': 0.046805202488882085, 'weight_cat_class_1': 0.9243343109542066, 'weight_cat_class_2': 0.6567809809444335}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,590] Trial 554 finished with value: 0.949352342950005 and parameters: {'weight_lgbm_class_0': 0.02029576094635962, 'weight_lgbm_class_1': 0.9853816582094617, 'weight_lgbm_class_2': 0.5437302650188005, 'weight_xgb_class_0': 0.03518720902573999, 'weight_xgb_class_1': 0.13429878339919346, 'weight_xgb_class_2': 0.5720726127514192, 'weight_cat_class_0': 0.04645091236173859, 'weight_cat_class_1': 0.927080998543828, 'weight_cat_class_2': 0.6527165405280739}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,596] Trial 555 finished with value: 0.9483866192444378 and parameters: {'weight_lgbm_class_0': 0.018266063493263814, 'weight_lgbm_class_1': 0.9024443409793167, 'weight_lgbm_class_2': 0.5436752941158713, 'weight_xgb_class_0': 0.18591711599351252, 'weight_xgb_class_1': 0.09965394139670436, 'weight_xgb_class_2': 0.5750371899033184, 'weight_cat_class_0': 0.04643593775639395, 'weight_cat_class_1': 0.9261167066926247, 'weight_cat_class_2': 0.5088823979295519}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,601] Trial 556 finished with value: 0.9491157456186321 and parameters: {'weight_lgbm_class_0': 0.020279094796978828, 'weight_lgbm_class_1': 0.996995250184642, 'weight_lgbm_class_2': 0.5671772200461981, 'weight_xgb_class_0': 0.02437345616301255, 'weight_xgb_class_1': 0.022596771466186563, 'weight_xgb_class_2': 0.5667387768639568, 'weight_cat_class_0': 0.04520309648400691, 'weight_cat_class_1': 0.933921752750086, 'weight_cat_class_2': 0.6710830421919649}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,617] Trial 557 finished with value: 0.9485608014601835 and parameters: {'weight_lgbm_class_0': 0.019652738073138696, 'weight_lgbm_class_1': 0.9088326756036456, 'weight_lgbm_class_2': 0.5639427746762681, 'weight_xgb_class_0': 0.19369057133845127, 'weight_xgb_class_1': 0.2054821145673681, 'weight_xgb_class_2': 0.5766992868900845, 'weight_cat_class_0': 0.04520966678821806, 'weight_cat_class_1': 0.926726313416026, 'weight_cat_class_2': 0.6594225118355506}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  28%|█████████████████████████████████████                                                                                               | 561/2000 [00:17<00:44, 32.70it/s]

[I 2026-07-03 10:22:52,670] Trial 558 finished with value: 0.9492709407297147 and parameters: {'weight_lgbm_class_0': 0.01886832166240788, 'weight_lgbm_class_1': 0.9103883608821156, 'weight_lgbm_class_2': 0.5535435098837209, 'weight_xgb_class_0': 0.029639018279112382, 'weight_xgb_class_1': 0.09358560490766396, 'weight_xgb_class_2': 0.5789034845500923, 'weight_cat_class_0': 0.04728809771441942, 'weight_cat_class_1': 0.9254281852130433, 'weight_cat_class_2': 0.6551764211934589}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,672] Trial 559 finished with value: 0.9492009004273138 and parameters: {'weight_lgbm_class_0': 0.017989095836232063, 'weight_lgbm_class_1': 0.9999483062940208, 'weight_lgbm_class_2': 0.5593518960763499, 'weight_xgb_class_0': 0.03275393438545681, 'weight_xgb_class_1': 0.0166482962906548, 'weight_xgb_class_2': 0.577984560850398, 'weight_cat_class_0': 0.04196438078883223, 'weight_cat_class_1': 0.9256490450664123, 'weight_cat_class_2': 0.6545519703528552}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,788] Trial 560 finished with value: 0.9256058042796186 and parameters: {'weight_lgbm_class_0': 0.017794800717135625, 'weight_lgbm_class_1': 0.9134108053392275, 'weight_lgbm_class_2': 0.41591284424005553, 'weight_xgb_class_0': 0.03244411870929873, 'weight_xgb_class_1': 0.13702029563685328, 'weight_xgb_class_2': 0.7367933521828557, 'weight_cat_class_0': 0.7706784713039889, 'weight_cat_class_1': 0.9301113423147764, 'weight_cat_class_2': 0.5941611742705132}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,848] Trial 561 finished with value: 0.9355174482172662 and parameters: {'weight_lgbm_class_0': 0.018623703523183658, 'weight_lgbm_class_1': 0.813362069763491, 'weight_lgbm_class_2': 0.573818276589093, 'weight_xgb_class_0': 0.5604973006622591, 'weight_xgb_class_1': 0.21227292242193427, 'weight_xgb_class_2': 0.6822073970059348, 'weight_cat_class_0': 0.04349127877491138, 'weight_cat_class_1': 0.9239431522869848, 'weight_cat_class_2': 0.5941127822608188}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  28%|█████████████████████████████████████▌                                                                                              | 569/2000 [00:17<00:50, 28.29it/s]

[I 2026-07-03 10:22:52,882] Trial 562 finished with value: 0.948441207596514 and parameters: {'weight_lgbm_class_0': 0.019373153466305842, 'weight_lgbm_class_1': 0.9369361575303008, 'weight_lgbm_class_2': 0.4131299501790798, 'weight_xgb_class_0': 0.005342686037424996, 'weight_xgb_class_1': 0.19807311488933482, 'weight_xgb_class_2': 0.7362778470123009, 'weight_cat_class_0': 0.044221455169737495, 'weight_cat_class_1': 0.9418096672632624, 'weight_cat_class_2': 0.5891883048375878}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,905] Trial 563 finished with value: 0.9493870789228983 and parameters: {'weight_lgbm_class_0': 0.07163271876235354, 'weight_lgbm_class_1': 0.9362030776486626, 'weight_lgbm_class_2': 0.5675167101595354, 'weight_xgb_class_0': 0.0022343658968836805, 'weight_xgb_class_1': 0.21892100406835557, 'weight_xgb_class_2': 0.6845254101568736, 'weight_cat_class_0': 0.11960284901868498, 'weight_cat_class_1': 0.9428385683366555, 'weight_cat_class_2': 0.5923826448579836}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,933] Trial 564 finished with value: 0.9495484299649366 and parameters: {'weight_lgbm_class_0': 0.07304598902672671, 'weight_lgbm_class_1': 0.9375155462120977, 'weight_lgbm_class_2': 0.4135768338767988, 'weight_xgb_class_0': 0.001510730788269507, 'weight_xgb_class_1': 0.13567303286527677, 'weight_xgb_class_2': 0.7241595594205356, 'weight_cat_class_0': 0.04479236703220274, 'weight_cat_class_1': 0.9434561829008778, 'weight_cat_class_2': 0.7778311604727675}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:52,949] Trial 565 finished with value: 0.9496360442761801 and parameters: {'weight_lgbm_class_0': 0.06668244949316665, 'weight_lgbm_class_1': 0.9362053148532136, 'weight_lgbm_class_2': 0.5643512335747999, 'weight_xgb_class_0': 0.01621043376916, 'weight_xgb_class_1': 0.20670014728149538, 'weight_xgb_class_2': 0.7295302911463344, 'weight_cat_class_0': 0.041702092832656475, 'weight_cat_class_1': 0.9352760898441524, 'weight_cat_class_2': 0.590923159640494}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,020] Trial 566 finished with value: 0.9490298354172916 and parameters: {'weight_lgbm_class_0': 0.065218387689265, 'weight_lgbm_class_1': 0.9363857833529217, 'weight_lgbm_class_2': 0.4231199457552874, 'weight_xgb_class_0': 0.010447638286566502, 'weight_xgb_class_1': 0.20700187571879217, 'weight_xgb_class_2': 0.7298908141855572, 'weight_cat_class_0': 0.0007623995188792629, 'weight_cat_class_1': 0.952206396001221, 'weight_cat_class_2': 0.2481431565726871}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,030] Trial 568 finished with value: 0.9485012115878861 and parameters: {'weight_lgbm_class_0': 0.06496539844012796, 'weight_lgbm_class_1': 0.9369996730584549, 'weight_lgbm_class_2': 0.42250985259568397, 'weight_xgb_class_0': 0.006216417136009719, 'weight_xgb_class_1': 0.16362836970944034, 'weight_xgb_class_2': 0.7358857553244362, 'weight_cat_class_0': 0.00035246567776064247, 'weight_cat_class_1': 0.9441512210729569, 'weight_cat_class_2': 0.6770206405292609}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,040] Trial 567 finished with value: 0.9491532255136949 and parameters: {'weight_lgbm_class_0': 0.07075261046084702, 'weight_lgbm_class_1': 0.810133641200907, 'weight_lgbm_class_2': 0.42938827155755777, 'weight_xgb_class_0': 0.015800915600416028, 'weight_xgb_class_1': 0.21124277001100794, 'weight_xgb_class_2': 0.660629301735613, 'weight_cat_class_0': 0.11652448696335804, 'weight_cat_class_1': 0.9449987995033431, 'weight_cat_class_2': 0.5911389645496999}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,052] Trial 569 finished with value: 0.9492619150375786 and parameters: {'weight_lgbm_class_0': 0.06740415085615464, 'weight_lgbm_class_1': 0.9350241530371941, 'weight_lgbm_class_2': 0.42589032929293863, 'weight_xgb_class_0': 0.006496824280905748, 'weight_xgb_class_1': 0.21075058096686683, 'weight_xgb_class_2': 0.6782472591663231, 'weight_cat_class_0': 0.121013714043959, 'weight_cat_class_1': 0.9458836847629656, 'weight_cat_class_2': 0.5966632566640103}. Best is trial 503 with value: 0.9497676925748403.

[I 2026-07-03 10:22:53,114] Trial 570 finished with value: 0.9495669899541982 and parameters: {'weight_lgbm_class_0': 0.06969385919261023, 'weight_lgbm_class_1': 0.9378382767015647, 'weight_lgbm_class_2': 0.6076053795519911, 'weight_xgb_class_0': 0.04438994295592906, 'weight_xgb_class_1': 0.20603468347564027, 'weight_xgb_class_2': 0.6821319954613293, 'weight_cat_class_0': 0.0011938273037049967, 'weight_cat_class_1': 0.9502358326726364, 'weight_cat_class_2': 0.5922106489034977}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,119] Trial 571 finished with value: 0.9383040706851541 and parameters: {'weight_lgbm_class_0': 0.06232036522152487, 'weight_lgbm_class_1': 0.8840280758833462, 'weight_lgbm_class_2': 0.6033721913400613, 'weight_xgb_class_0': 0.018290776139875113, 'weight_xgb_class_1': 0.21044585273721278, 'weight_xgb_class_2': 0.7317718784101436, 'weight_cat_class_0': 0.5486011103628268, 'weight_cat_class_1': 0.944081483397782, 'weight_cat_class_2': 0.6824687593949408}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,201] Trial 572 finished with value: 0.9493450798645645 and parameters: {'weight_lgbm_class_0': 0.07039946173231015, 'weight_lgbm_class_1': 0.883514316699118, 'weight_lgbm_class_2': 0.41398041802322266, 'weight_xgb_class_0': 0.0025860921867199363, 'weight_xgb_class_1': 0.2117632026287432, 'weight_xgb_class_2': 0.7320504085679663, 'weight_cat_class_0': 0.12163252533118282, 'weight_cat_class_1': 0.906940691510434, 'weight_cat_class_2': 0.7786490525933358}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,299] Trial 573 finished with value: 0.9488519929929325 and parameters: {'weight_lgbm_class_0': 0.06967138838583398, 'weight_lgbm_class_1': 0.9399546102043052, 'weight_lgbm_class_2': 0.4286328645257472, 'weight_xgb_class_0': 0.001778978637928072, 'weight_xgb_class_1': 0.17207308280738656, 'weight_xgb_class_2': 0.44288887995109144, 'weight_cat_class_0': 0.001172819688896151, 'weight_cat_class_1': 0.949449875196187, 'weight_cat_class_2': 0.6049765107177303}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  29%|██████████████████████████████████████▎                                                                                             | 580/2000 [00:17<00:56, 25.32it/s]

[I 2026-07-03 10:22:53,300] Trial 574 finished with value: 0.9353573295137796 and parameters: {'weight_lgbm_class_0': 0.06924639129879391, 'weight_lgbm_class_1': 0.8869271553688112, 'weight_lgbm_class_2': 0.6082629497181818, 'weight_xgb_class_0': 0.003499844091993557, 'weight_xgb_class_1': 0.15951104234755512, 'weight_xgb_class_2': 0.6577417272970906, 'weight_cat_class_0': 0.6008017098278999, 'weight_cat_class_1': 0.9104956739559237, 'weight_cat_class_2': 0.6756031964354298}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,375] Trial 576 finished with value: 0.9491032967050995 and parameters: {'weight_lgbm_class_0': 0.07326769836651027, 'weight_lgbm_class_1': 0.8897851960215374, 'weight_lgbm_class_2': 0.48023053935320525, 'weight_xgb_class_0': 0.14713480153698383, 'weight_xgb_class_1': 0.16798209192465788, 'weight_xgb_class_2': 0.6629171680871866, 'weight_cat_class_0': 0.0009133617558509943, 'weight_cat_class_1': 0.8968602232553053, 'weight_cat_class_2': 0.6795924500095507}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,375] Trial 575 finished with value: 0.9492636084073633 and parameters: {'weight_lgbm_class_0': 0.06672192702421803, 'weight_lgbm_class_1': 0.8907645408178851, 'weight_lgbm_class_2': 0.4305233790229939, 'weight_xgb_class_0': 0.07824780496027581, 'weight_xgb_class_1': 0.17145181269638562, 'weight_xgb_class_2': 0.5405847160798557, 'weight_cat_class_0': 0.00042284516871802375, 'weight_cat_class_1': 0.9022764105657058, 'weight_cat_class_2': 0.2519888246930739}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,396] Trial 577 finished with value: 0.9496081545095704 and parameters: {'weight_lgbm_class_0': 0.06703824211251712, 'weight_lgbm_class_1': 0.8880898241743652, 'weight_lgbm_class_2': 0.5991906351572668, 'weight_xgb_class_0': 0.04434062858269974, 'weight_xgb_class_1': 0.16332769941629147, 'weight_xgb_class_2': 0.5288325900940469, 'weight_cat_class_0': 0.003046158085606543, 'weight_cat_class_1': 0.9030088433452931, 'weight_cat_class_2': 0.6803744459466711}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,435] Trial 578 finished with value: 0.9462859399415339 and parameters: {'weight_lgbm_class_0': 0.07706891346926988, 'weight_lgbm_class_1': 0.8444509047790582, 'weight_lgbm_class_2': 0.6092924208570195, 'weight_xgb_class_0': 0.08000451861241648, 'weight_xgb_class_1': 0.17667599536675663, 'weight_xgb_class_2': 0.6620917745886413, 'weight_cat_class_0': 0.13262109961226787, 'weight_cat_class_1': 0.9066521066289814, 'weight_cat_class_2': 0.07778065647085891}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,446] Trial 580 finished with value: 0.9494683423309925 and parameters: {'weight_lgbm_class_0': 1.954981733620848e-05, 'weight_lgbm_class_1': 0.8929405722226252, 'weight_lgbm_class_2': 0.4950878861113386, 'weight_xgb_class_0': 0.14703012178962094, 'weight_xgb_class_1': 0.16566239518775583, 'weight_xgb_class_2': 0.4467078785822298, 'weight_cat_class_0': 0.01884641745386101, 'weight_cat_class_1': 0.9033460886762454, 'weight_cat_class_2': 0.7400455335073837}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,492] Trial 579 finished with value: 0.9493674486205649 and parameters: {'weight_lgbm_class_0': 0.0327455951123853, 'weight_lgbm_class_1': 0.8769126524865554, 'weight_lgbm_class_2': 0.6022684975709021, 'weight_xgb_class_0': 0.052433098186853794, 'weight_xgb_class_1': 0.16645994158964367, 'weight_xgb_class_2': 0.5304775057944295, 'weight_cat_class_0': 0.016284809029106104, 'weight_cat_class_1': 0.901597878570496, 'weight_cat_class_2': 0.6815728624551519}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  29%|██████████████████████████████████████▋                                                                                             | 586/2000 [00:17<00:50, 27.92it/s]

[I 2026-07-03 10:22:53,510] Trial 581 finished with value: 0.949693224001054 and parameters: {'weight_lgbm_class_0': 0.035409223361300854, 'weight_lgbm_class_1': 0.8786132363396055, 'weight_lgbm_class_2': 0.6013450866821207, 'weight_xgb_class_0': 0.08074094088475553, 'weight_xgb_class_1': 0.16975891261080417, 'weight_xgb_class_2': 0.521934994962729, 'weight_cat_class_0': 0.01818833171892825, 'weight_cat_class_1': 0.9034081268660463, 'weight_cat_class_2': 0.6827789114827879}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,512] Trial 582 finished with value: 0.9492191400242714 and parameters: {'weight_lgbm_class_0': 0.00020262310822810256, 'weight_lgbm_class_1': 0.839956752556471, 'weight_lgbm_class_2': 0.6268219865898242, 'weight_xgb_class_0': 0.08124111883850067, 'weight_xgb_class_1': 0.16541632980398716, 'weight_xgb_class_2': 0.5303973298549578, 'weight_cat_class_0': 0.015108405530145374, 'weight_cat_class_1': 0.9050412861130775, 'weight_cat_class_2': 0.7426543748254997}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,580] Trial 583 finished with value: 0.9495880458863574 and parameters: {'weight_lgbm_class_0': 0.03892672514796972, 'weight_lgbm_class_1': 0.8860032054276409, 'weight_lgbm_class_2': 0.475218523367778, 'weight_xgb_class_0': 0.08497912569653755, 'weight_xgb_class_1': 0.16853635315953433, 'weight_xgb_class_2': 0.44696933821381735, 'weight_cat_class_0': 0.01776805689483229, 'weight_cat_class_1': 0.9005156187593701, 'weight_cat_class_2': 0.6808966682284358}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,622] Trial 584 finished with value: 0.9220768795226869 and parameters: {'weight_lgbm_class_0': 0.6694863431152159, 'weight_lgbm_class_1': 0.9802053933229584, 'weight_lgbm_class_2': 0.4736098966387031, 'weight_xgb_class_0': 0.14746639523709834, 'weight_xgb_class_1': 0.1661094209443301, 'weight_xgb_class_2': 0.316272539089005, 'weight_cat_class_0': 0.019520923024560363, 'weight_cat_class_1': 0.9035406587165888, 'weight_cat_class_2': 0.7427957967755288}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,699] Trial 585 finished with value: 0.9492158197577378 and parameters: {'weight_lgbm_class_0': 0.035527405773011965, 'weight_lgbm_class_1': 0.9814352756381618, 'weight_lgbm_class_2': 0.4709638562767966, 'weight_xgb_class_0': 0.14737544555265958, 'weight_xgb_class_1': 0.10483947978342192, 'weight_xgb_class_2': 0.5371865420248289, 'weight_cat_class_0': 0.02072281232480615, 'weight_cat_class_1': 0.9817650935672875, 'weight_cat_class_2': 0.7429359278790787}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  30%|███████████████████████████████████████▏                                                                                            | 593/2000 [00:18<00:56, 24.74it/s]

[I 2026-07-03 10:22:53,761] Trial 586 finished with value: 0.9450152780432295 and parameters: {'weight_lgbm_class_0': 0.03495919005845247, 'weight_lgbm_class_1': 0.84831295959339, 'weight_lgbm_class_2': 0.474275534054661, 'weight_xgb_class_0': 0.3016704995614834, 'weight_xgb_class_1': 0.10362435506932403, 'weight_xgb_class_2': 0.3312610817169313, 'weight_cat_class_0': 0.020812679920063717, 'weight_cat_class_1': 0.9008869845479051, 'weight_cat_class_2': 0.7467290408366349}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,806] Trial 587 finished with value: 0.9496118130270936 and parameters: {'weight_lgbm_class_0': 0.03576851203305957, 'weight_lgbm_class_1': 0.9828321687524519, 'weight_lgbm_class_2': 0.521440255504954, 'weight_xgb_class_0': 0.10722981826638028, 'weight_xgb_class_1': 0.10211230642318316, 'weight_xgb_class_2': 0.5267460939992042, 'weight_cat_class_0': 0.022967566754682978, 'weight_cat_class_1': 0.9088322264463735, 'weight_cat_class_2': 0.7400468866232542}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,853] Trial 588 finished with value: 0.9496063125662327 and parameters: {'weight_lgbm_class_0': 0.035291235025857716, 'weight_lgbm_class_1': 0.9764199663716769, 'weight_lgbm_class_2': 0.528231634035561, 'weight_xgb_class_0': 0.10804167444863605, 'weight_xgb_class_1': 0.1405973265985497, 'weight_xgb_class_2': 0.5346174008002795, 'weight_cat_class_0': 0.018722922161508882, 'weight_cat_class_1': 0.9868940084085347, 'weight_cat_class_2': 0.7425958195313466}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,868] Trial 589 finished with value: 0.9158920673269554 and parameters: {'weight_lgbm_class_0': 0.6740760878893403, 'weight_lgbm_class_1': 0.9845344596478033, 'weight_lgbm_class_2': 0.6905535615990481, 'weight_xgb_class_0': 0.11356293878461636, 'weight_xgb_class_1': 0.10667938560503815, 'weight_xgb_class_2': 0.5295109285747185, 'weight_cat_class_0': 0.02581606292837528, 'weight_cat_class_1': 0.9742462172857004, 'weight_cat_class_2': 0.008252249448633064}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,874] Trial 590 finished with value: 0.9494011520006255 and parameters: {'weight_lgbm_class_0': 0.037466157173871986, 'weight_lgbm_class_1': 0.980457308113991, 'weight_lgbm_class_2': 0.5258134222848572, 'weight_xgb_class_0': 0.04788808612722501, 'weight_xgb_class_1': 0.09306363912641742, 'weight_xgb_class_2': 0.5286519898979133, 'weight_cat_class_0': 0.02051774240911593, 'weight_cat_class_1': 0.9865679299614307, 'weight_cat_class_2': 0.7412813895848777}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,892] Trial 591 finished with value: 0.9485712598596869 and parameters: {'weight_lgbm_class_0': 0.11737070191733659, 'weight_lgbm_class_1': 0.9812062358502815, 'weight_lgbm_class_2': 0.5242646031910371, 'weight_xgb_class_0': 0.10809105298799729, 'weight_xgb_class_1': 0.13722961455227756, 'weight_xgb_class_2': 0.5521064835664442, 'weight_cat_class_0': 0.025820756573043616, 'weight_cat_class_1': 0.713242557962034, 'weight_cat_class_2': 0.7385621785652715}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,945] Trial 592 finished with value: 0.9467977753143247 and parameters: {'weight_lgbm_class_0': 0.11642461115654577, 'weight_lgbm_class_1': 0.9198687460482478, 'weight_lgbm_class_2': 0.5877745038171381, 'weight_xgb_class_0': 0.1085702772710113, 'weight_xgb_class_1': 0.10263510825268876, 'weight_xgb_class_2': 0.3126672313528619, 'weight_cat_class_0': 0.0865633990167054, 'weight_cat_class_1': 0.8672282761432858, 'weight_cat_class_2': 0.6373088448139791}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:53,967] Trial 593 finished with value: 0.9489337388564482 and parameters: {'weight_lgbm_class_0': 0.11095430598230813, 'weight_lgbm_class_1': 0.853973201083719, 'weight_lgbm_class_2': 0.6272647027722584, 'weight_xgb_class_0': 0.046035385921150584, 'weight_xgb_class_1': 0.13986278401442762, 'weight_xgb_class_2': 0.519847881934731, 'weight_cat_class_0': 0.08308566154346153, 'weight_cat_class_1': 0.9758043966394018, 'weight_cat_class_2': 0.6434084500548507}. Best is trial 503 with value: 0.9497676925748403.

[I 2026-07-03 10:22:53,999] Trial 594 finished with value: 0.9486335490055131 and parameters: {'weight_lgbm_class_0': 0.11661965796763443, 'weight_lgbm_class_1': 0.8536666194791842, 'weight_lgbm_class_2': 0.6367933528602264, 'weight_xgb_class_0': 0.10962365302513342, 'weight_xgb_class_1': 0.1398045247590698, 'weight_xgb_class_2': 0.5229055859712436, 'weight_cat_class_0': 0.029036362866366718, 'weight_cat_class_1': 0.9772840960444942, 'weight_cat_class_2': 0.64100561140606}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,028] Trial 595 finished with value: 0.9183619289500825 and parameters: {'weight_lgbm_class_0': 0.7423843591843396, 'weight_lgbm_class_1': 0.8535017665702769, 'weight_lgbm_class_2': 0.6261972647764068, 'weight_xgb_class_0': 0.1142075156233024, 'weight_xgb_class_1': 0.10639150686373548, 'weight_xgb_class_2': 0.5248399327069595, 'weight_cat_class_0': 0.08785894082584621, 'weight_cat_class_1': 0.8376912669813734, 'weight_cat_class_2': 0.6984454083621882}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,041] Trial 596 finished with value: 0.9432303772654679 and parameters: {'weight_lgbm_class_0': 0.03663562105154701, 'weight_lgbm_class_1': 0.8534306498961837, 'weight_lgbm_class_2': 0.5276887274560532, 'weight_xgb_class_0': 0.11228185389480341, 'weight_xgb_class_1': 0.1392797332184051, 'weight_xgb_class_2': 0.512916644488941, 'weight_cat_class_0': 0.2809649811038726, 'weight_cat_class_1': 0.8374503692107064, 'weight_cat_class_2': 0.6399521236884675}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,078] Trial 597 finished with value: 0.9470228278398033 and parameters: {'weight_lgbm_class_0': 0.11969821825105252, 'weight_lgbm_class_1': 0.8385991431487132, 'weight_lgbm_class_2': 0.5774331648101559, 'weight_xgb_class_0': 0.10570700818054421, 'weight_xgb_class_1': 0.13351268368405425, 'weight_xgb_class_2': 0.5109173880322097, 'weight_cat_class_0': 0.09274313016161621, 'weight_cat_class_1': 0.8612144528230772, 'weight_cat_class_2': 0.644297721141973}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  30%|███████████████████████████████████████▊                                                                                            | 603/2000 [00:18<00:56, 24.54it/s]

[I 2026-07-03 10:22:54,197] Trial 598 finished with value: 0.9494916282522631 and parameters: {'weight_lgbm_class_0': 0.041147297528109486, 'weight_lgbm_class_1': 0.9194133452215183, 'weight_lgbm_class_2': 0.6308760363479186, 'weight_xgb_class_0': 0.04427075634519688, 'weight_xgb_class_1': 0.14023131419591237, 'weight_xgb_class_2': 0.5061446461806177, 'weight_cat_class_0': 0.09235752681852895, 'weight_cat_class_1': 0.8639391418517629, 'weight_cat_class_2': 0.6464673426479909}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,216] Trial 599 finished with value: 0.9488554476301339 and parameters: {'weight_lgbm_class_0': 0.11394316967153974, 'weight_lgbm_class_1': 0.8543630607107872, 'weight_lgbm_class_2': 0.6335536204954646, 'weight_xgb_class_0': 0.047077085366014224, 'weight_xgb_class_1': 0.14100069455730557, 'weight_xgb_class_2': 0.49636271188093034, 'weight_cat_class_0': 0.08237728267464194, 'weight_cat_class_1': 0.9792055208764874, 'weight_cat_class_2': 0.6372508801107255}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,293] Trial 600 finished with value: 0.9486812046873899 and parameters: {'weight_lgbm_class_0': 0.10686438889593367, 'weight_lgbm_class_1': 0.9235999604331339, 'weight_lgbm_class_2': 0.6377328991270953, 'weight_xgb_class_0': 0.04560729873446466, 'weight_xgb_class_1': 0.07999151916963718, 'weight_xgb_class_2': 0.5007262680297809, 'weight_cat_class_0': 0.08952592591152486, 'weight_cat_class_1': 0.8369389663360464, 'weight_cat_class_2': 0.6457329202274293}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,313] Trial 602 finished with value: 0.9482687185010117 and parameters: {'weight_lgbm_class_0': 0.11157855544821749, 'weight_lgbm_class_1': 0.858567254711368, 'weight_lgbm_class_2': 0.38392763555567205, 'weight_xgb_class_0': 0.051394647058303, 'weight_xgb_class_1': 0.1911660465184893, 'weight_xgb_class_2': 0.48913007387693846, 'weight_cat_class_0': 0.08736422509341432, 'weight_cat_class_1': 0.867961733766793, 'weight_cat_class_2': 0.6484697550485152}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,367] Trial 601 finished with value: 0.9215135977572516 and parameters: {'weight_lgbm_class_0': 0.7543206465135075, 'weight_lgbm_class_1': 0.9114436757163032, 'weight_lgbm_class_2': 0.5804276713966311, 'weight_xgb_class_0': 0.04330007472696994, 'weight_xgb_class_1': 0.191010059799605, 'weight_xgb_class_2': 0.5040930547060049, 'weight_cat_class_0': 0.08804482154348899, 'weight_cat_class_1': 0.8342276441849572, 'weight_cat_class_2': 0.64350195462867}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,392] Trial 603 finished with value: 0.9410115014267385 and parameters: {'weight_lgbm_class_0': 0.09815353987963085, 'weight_lgbm_class_1': 0.9224149024062765, 'weight_lgbm_class_2': 0.5707616872986633, 'weight_xgb_class_0': 0.3562696437197902, 'weight_xgb_class_1': 0.9279009907728724, 'weight_xgb_class_2': 0.5047943803938777, 'weight_cat_class_0': 0.09046225941605357, 'weight_cat_class_1': 0.8337759212916488, 'weight_cat_class_2': 0.6442935359574192}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  30%|████████████████████████████████████████▎                                                                                           | 610/2000 [00:18<00:47, 29.52it/s]

[I 2026-07-03 10:22:54,405] Trial 604 finished with value: 0.9450585332436492 and parameters: {'weight_lgbm_class_0': 0.051908905258042815, 'weight_lgbm_class_1': 0.9193166681652576, 'weight_lgbm_class_2': 0.5725517042355363, 'weight_xgb_class_0': 0.08094404282605798, 'weight_xgb_class_1': 0.08035636438186, 'weight_xgb_class_2': 0.6406021928974939, 'weight_cat_class_0': 0.2728885811043136, 'weight_cat_class_1': 0.8390290816946808, 'weight_cat_class_2': 0.6998132792139915}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,423] Trial 605 finished with value: 0.9492872971496592 and parameters: {'weight_lgbm_class_0': 0.05257756672566838, 'weight_lgbm_class_1': 0.9196010443714034, 'weight_lgbm_class_2': 0.5699489813063389, 'weight_xgb_class_0': 0.07856061159644853, 'weight_xgb_class_1': 0.1927706415470079, 'weight_xgb_class_2': 0.493189160847994, 'weight_cat_class_0': 0.05872501346254033, 'weight_cat_class_1': 0.8597947787608718, 'weight_cat_class_2': 0.6453187212955244}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,451] Trial 606 finished with value: 0.9310650969081135 and parameters: {'weight_lgbm_class_0': 0.05045008884231551, 'weight_lgbm_class_1': 0.9185541717837545, 'weight_lgbm_class_2': 0.5772346744455208, 'weight_xgb_class_0': 0.6602348677708464, 'weight_xgb_class_1': 0.8149947374770294, 'weight_xgb_class_2': 0.4980828812427724, 'weight_cat_class_0': 0.055650304976029824, 'weight_cat_class_1': 0.8373186189744665, 'weight_cat_class_2': 0.7004942537652071}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,465] Trial 607 finished with value: 0.9207506927295422 and parameters: {'weight_lgbm_class_0': 0.05368822665601145, 'weight_lgbm_class_1': 0.9148533243744437, 'weight_lgbm_class_2': 0.3836427698731414, 'weight_xgb_class_0': 0.7005492422475944, 'weight_xgb_class_1': 0.08342736407981145, 'weight_xgb_class_2': 0.49593814481301646, 'weight_cat_class_0': 0.05731138553634914, 'weight_cat_class_1': 0.8625169416089176, 'weight_cat_class_2': 0.6677594384796528}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,496] Trial 608 finished with value: 0.9490721955436738 and parameters: {'weight_lgbm_class_0': 0.08986283731394644, 'weight_lgbm_class_1': 0.9109682883104414, 'weight_lgbm_class_2': 0.38444011360105135, 'weight_xgb_class_0': 0.05230370835179333, 'weight_xgb_class_1': 0.08186785973545921, 'weight_xgb_class_2': 0.49728136437658216, 'weight_cat_class_0': 0.05475049635304699, 'weight_cat_class_1': 0.8635750423180653, 'weight_cat_class_2': 0.6681241363990505}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,536] Trial 609 finished with value: 0.9495712957639006 and parameters: {'weight_lgbm_class_0': 0.0007196392663688343, 'weight_lgbm_class_1': 0.9109890038937324, 'weight_lgbm_class_2': 0.5753386145852506, 'weight_xgb_class_0': 0.0525696463531735, 'weight_xgb_class_1': 0.18959074441232224, 'weight_xgb_class_2': 0.4951332721937635, 'weight_cat_class_0': 0.057590852950400936, 'weight_cat_class_1': 0.8660511299994145, 'weight_cat_class_2': 0.6981489205118699}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  31%|████████████████████████████████████████▌                                                                                           | 615/2000 [00:19<00:57, 24.27it/s]

[I 2026-07-03 10:22:54,662] Trial 610 finished with value: 0.9163932926033161 and parameters: {'weight_lgbm_class_0': 0.833277204894138, 'weight_lgbm_class_1': 0.9138631116039249, 'weight_lgbm_class_2': 0.5723358513247835, 'weight_xgb_class_0': 0.07450637473955335, 'weight_xgb_class_1': 0.1846863802172656, 'weight_xgb_class_2': 0.6962661616517231, 'weight_cat_class_0': 0.051612396289797545, 'weight_cat_class_1': 0.5111557707208384, 'weight_cat_class_2': 0.700330464758402}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,682] Trial 611 finished with value: 0.9495937830801026 and parameters: {'weight_lgbm_class_0': 0.017057754209300106, 'weight_lgbm_class_1': 0.9526233775024224, 'weight_lgbm_class_2': 0.3804377002316188, 'weight_xgb_class_0': 0.07887986431978125, 'weight_xgb_class_1': 0.18937559760088724, 'weight_xgb_class_2': 0.6942782087829336, 'weight_cat_class_0': 0.056835369202917374, 'weight_cat_class_1': 0.865544296301564, 'weight_cat_class_2': 0.7015702400679751}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,728] Trial 612 finished with value: 0.9496930447288162 and parameters: {'weight_lgbm_class_0': 0.01727882559057869, 'weight_lgbm_class_1': 0.9122009112849164, 'weight_lgbm_class_2': 0.5765898657233038, 'weight_xgb_class_0': 0.07080819469121585, 'weight_xgb_class_1': 0.18867349674318887, 'weight_xgb_class_2': 0.6389914431722227, 'weight_cat_class_0': 0.05756874800995905, 'weight_cat_class_1': 0.8817681580632446, 'weight_cat_class_2': 0.608697148438533}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,769] Trial 613 finished with value: 0.9427077661108977 and parameters: {'weight_lgbm_class_0': 0.05330425154974135, 'weight_lgbm_class_1': 0.9475505200026901, 'weight_lgbm_class_2': 0.5740954585811754, 'weight_xgb_class_0': 0.3557694662015746, 'weight_xgb_class_1': 0.05420437450639822, 'weight_xgb_class_2': 0.6978332334835444, 'weight_cat_class_0': 0.05202801339672465, 'weight_cat_class_1': 0.8905636937493361, 'weight_cat_class_2': 0.6099654531293673}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,809] Trial 614 finished with value: 0.9495628674388351 and parameters: {'weight_lgbm_class_0': 0.0008879517619911669, 'weight_lgbm_class_1': 0.8021904629668021, 'weight_lgbm_class_2': 0.5020762783515625, 'weight_xgb_class_0': 0.08187473273123914, 'weight_xgb_class_1': 0.07594261526723464, 'weight_xgb_class_2': 0.6440062539691151, 'weight_cat_class_0': 0.05895468243861734, 'weight_cat_class_1': 0.8862984634126876, 'weight_cat_class_2': 0.6985578907092355}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,834] Trial 615 finished with value: 0.949611494839863 and parameters: {'weight_lgbm_class_0': 0.018192624841329438, 'weight_lgbm_class_1': 0.9556570500771288, 'weight_lgbm_class_2': 0.5005542854743295, 'weight_xgb_class_0': 0.07793349707983893, 'weight_xgb_class_1': 0.055246024303513004, 'weight_xgb_class_2': 0.7119245893319682, 'weight_cat_class_0': 0.05924955662070804, 'weight_cat_class_1': 0.9164402471083879, 'weight_cat_class_2': 0.6146108153188992}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  31%|█████████████████████████████████████████                                                                                           | 622/2000 [00:19<00:44, 30.75it/s]

[I 2026-07-03 10:22:54,876] Trial 617 finished with value: 0.9496059773576516 and parameters: {'weight_lgbm_class_0': 0.017826416321077083, 'weight_lgbm_class_1': 0.9506189336176911, 'weight_lgbm_class_2': 0.5097390080413713, 'weight_xgb_class_0': 0.0775466489054107, 'weight_xgb_class_1': 0.11742603332535459, 'weight_xgb_class_2': 0.6966342736226212, 'weight_cat_class_0': 0.043665165295213464, 'weight_cat_class_1': 0.8912209414464104, 'weight_cat_class_2': 0.4195122927049705}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,886] Trial 616 finished with value: 0.9273034078749505 and parameters: {'weight_lgbm_class_0': 0.0010527736278203997, 'weight_lgbm_class_1': 0.9495089787751065, 'weight_lgbm_class_2': 0.4990685882608123, 'weight_xgb_class_0': 0.08040996599257294, 'weight_xgb_class_1': 0.04652538863504363, 'weight_xgb_class_2': 0.5553814547625446, 'weight_cat_class_0': 0.6887258559314412, 'weight_cat_class_1': 0.88861124279973, 'weight_cat_class_2': 0.668575929367864}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,906] Trial 618 finished with value: 0.9494250916878689 and parameters: {'weight_lgbm_class_0': 0.001232816238901438, 'weight_lgbm_class_1': 0.8007596347769141, 'weight_lgbm_class_2': 0.5015818981006049, 'weight_xgb_class_0': 0.07527129420567658, 'weight_xgb_class_1': 0.12090423182026719, 'weight_xgb_class_2': 0.7033710341591797, 'weight_cat_class_0': 0.03600618852270387, 'weight_cat_class_1': 0.9186225038269183, 'weight_cat_class_2': 0.6683596575787697}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,928] Trial 619 finished with value: 0.9409784890612682 and parameters: {'weight_lgbm_class_0': 0.01682753041140113, 'weight_lgbm_class_1': 0.9462927080644785, 'weight_lgbm_class_2': 0.5008190048912713, 'weight_xgb_class_0': 0.07828147766027899, 'weight_xgb_class_1': 0.04867235291466611, 'weight_xgb_class_2': 0.6995283830102219, 'weight_cat_class_0': 0.38250645243413367, 'weight_cat_class_1': 0.6692219884433724, 'weight_cat_class_2': 0.609271461475895}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,931] Trial 620 finished with value: 0.9496591084169518 and parameters: {'weight_lgbm_class_0': 0.014960093830392074, 'weight_lgbm_class_1': 0.8037294809346429, 'weight_lgbm_class_2': 0.5047805875059358, 'weight_xgb_class_0': 0.07798106893563497, 'weight_xgb_class_1': 0.5546469094167336, 'weight_xgb_class_2': 0.7082605425672942, 'weight_cat_class_0': 0.03698413077161987, 'weight_cat_class_1': 0.668520579418494, 'weight_cat_class_2': 0.6084712736583625}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:54,990] Trial 621 finished with value: 0.949661493301408 and parameters: {'weight_lgbm_class_0': 0.017029433353003963, 'weight_lgbm_class_1': 0.9467091512636266, 'weight_lgbm_class_2': 0.5036583230109868, 'weight_xgb_class_0': 0.0817311864362732, 'weight_xgb_class_1': 0.04448520541331091, 'weight_xgb_class_2': 0.6947334188005536, 'weight_cat_class_0': 0.03738946626712602, 'weight_cat_class_1': 0.9195336470128205, 'weight_cat_class_2': 0.6107394458144176}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,064] Trial 622 finished with value: 0.9489579506378099 and parameters: {'weight_lgbm_class_0': 0.017741849288394736, 'weight_lgbm_class_1': 0.80192745217635, 'weight_lgbm_class_2': 0.9776550163533683, 'weight_xgb_class_0': 0.08115615421184313, 'weight_xgb_class_1': 0.5620287867192926, 'weight_xgb_class_2': 0.555392671756613, 'weight_cat_class_0': 0.000497285979754309, 'weight_cat_class_1': 0.8881914420606365, 'weight_cat_class_2': 0.606481763323451}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  31%|█████████████████████████████████████████▍                                                                                          | 628/2000 [00:19<00:54, 25.01it/s]

[I 2026-07-03 10:22:55,123] Trial 623 finished with value: 0.9490724055280942 and parameters: {'weight_lgbm_class_0': 0.015587708113945952, 'weight_lgbm_class_1': 0.7434930136559194, 'weight_lgbm_class_2': 0.5011814139115536, 'weight_xgb_class_0': 0.028669488757916965, 'weight_xgb_class_1': 0.0502240800271769, 'weight_xgb_class_2': 0.559158897421491, 'weight_cat_class_0': 0.03596490587947313, 'weight_cat_class_1': 0.8885329939181876, 'weight_cat_class_2': 0.6052569498329209}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,189] Trial 624 finished with value: 0.9497580508707482 and parameters: {'weight_lgbm_class_0': 0.020334558538053975, 'weight_lgbm_class_1': 0.9537574588861368, 'weight_lgbm_class_2': 0.5974849219007949, 'weight_xgb_class_0': 0.08334845848949529, 'weight_xgb_class_1': 0.5500864634952953, 'weight_xgb_class_2': 0.6421879432455493, 'weight_cat_class_0': 0.03906666851521406, 'weight_cat_class_1': 0.9172931677727764, 'weight_cat_class_2': 0.5707779237229418}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,208] Trial 625 finished with value: 0.9496339004806975 and parameters: {'weight_lgbm_class_0': 0.018617611832509613, 'weight_lgbm_class_1': 0.9505246255284477, 'weight_lgbm_class_2': 0.6140359509882258, 'weight_xgb_class_0': 0.07945805719833882, 'weight_xgb_class_1': 0.561356922897993, 'weight_xgb_class_2': 0.6254281657249774, 'weight_cat_class_0': 0.03239117488160749, 'weight_cat_class_1': 0.9228246196427704, 'weight_cat_class_2': 0.6040265660847415}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,265] Trial 627 finished with value: 0.9496720176194042 and parameters: {'weight_lgbm_class_0': 0.01775583169159603, 'weight_lgbm_class_1': 0.9446203451090346, 'weight_lgbm_class_2': 0.6090332627693935, 'weight_xgb_class_0': 0.06529667742600664, 'weight_xgb_class_1': 0.15864785143051988, 'weight_xgb_class_2': 0.6068800529014566, 'weight_cat_class_0': 0.04102125791783304, 'weight_cat_class_1': 0.9190562482059121, 'weight_cat_class_2': 0.6137738069730256}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,266] Trial 626 finished with value: 0.9492602849367149 and parameters: {'weight_lgbm_class_0': 0.02127545128143215, 'weight_lgbm_class_1': 0.9475180850835592, 'weight_lgbm_class_2': 0.598747965349584, 'weight_xgb_class_0': 0.135523172726185, 'weight_xgb_class_1': 0.15046815273748584, 'weight_xgb_class_2': 0.6034013136138138, 'weight_cat_class_0': 0.03668889934423662, 'weight_cat_class_1': 0.6639636010372807, 'weight_cat_class_2': 0.6091269255455674}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,304] Trial 628 finished with value: 0.9493180152304665 and parameters: {'weight_lgbm_class_0': 0.03276983880388973, 'weight_lgbm_class_1': 0.9430496200851132, 'weight_lgbm_class_2': 0.6024438472476372, 'weight_xgb_class_0': 0.13740358123913565, 'weight_xgb_class_1': 0.5442380893542104, 'weight_xgb_class_2': 0.6159067743323798, 'weight_cat_class_0': 0.03363634436357081, 'weight_cat_class_1': 0.9199203251958267, 'weight_cat_class_2': 0.5702759601377766}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  32%|█████████████████████████████████████████▊                                                                                          | 634/2000 [00:19<00:46, 29.16it/s]

[I 2026-07-03 10:22:55,316] Trial 629 finished with value: 0.949290431076057 and parameters: {'weight_lgbm_class_0': 0.029806333441013452, 'weight_lgbm_class_1': 0.9673991681265338, 'weight_lgbm_class_2': 0.5943823827420583, 'weight_xgb_class_0': 0.13790602216891526, 'weight_xgb_class_1': 0.15412614673613842, 'weight_xgb_class_2': 0.6121281858238374, 'weight_cat_class_0': 0.03523808095371053, 'weight_cat_class_1': 0.9508534719652734, 'weight_cat_class_2': 0.6121401275874073}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,358] Trial 630 finished with value: 0.9492633300788219 and parameters: {'weight_lgbm_class_0': 0.03285464269576303, 'weight_lgbm_class_1': 0.9651704321065779, 'weight_lgbm_class_2': 0.5922317370940504, 'weight_xgb_class_0': 0.13885892923709517, 'weight_xgb_class_1': 0.15160473657845425, 'weight_xgb_class_2': 0.6040061000003158, 'weight_cat_class_0': 0.031826160911476234, 'weight_cat_class_1': 0.9529078143618359, 'weight_cat_class_2': 0.5627170538236693}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,374] Trial 631 finished with value: 0.9492918112189143 and parameters: {'weight_lgbm_class_0': 0.026904089517911775, 'weight_lgbm_class_1': 0.8810124251132073, 'weight_lgbm_class_2': 0.6025075434544299, 'weight_xgb_class_0': 0.1369599014086509, 'weight_xgb_class_1': 0.14909376529480314, 'weight_xgb_class_2': 0.6026465925040613, 'weight_cat_class_0': 0.03193246355921203, 'weight_cat_class_1': 0.9563426905463733, 'weight_cat_class_2': 0.5763466485499283}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,431] Trial 632 finished with value: 0.9491752082875684 and parameters: {'weight_lgbm_class_0': 0.03517884000652262, 'weight_lgbm_class_1': 0.8759259090928245, 'weight_lgbm_class_2': 0.5950021136964747, 'weight_xgb_class_0': 0.14451470950745587, 'weight_xgb_class_1': 0.1531707582002914, 'weight_xgb_class_2': 0.6063230639477072, 'weight_cat_class_0': 0.03498085786825734, 'weight_cat_class_1': 0.9541932558218476, 'weight_cat_class_2': 0.6112442594461084}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,454] Trial 633 finished with value: 0.9325181146638423 and parameters: {'weight_lgbm_class_0': 0.5442708854173206, 'weight_lgbm_class_1': 0.9608851589133741, 'weight_lgbm_class_2': 0.5899879342943419, 'weight_xgb_class_0': 0.14017711369351787, 'weight_xgb_class_1': 0.15143550045813833, 'weight_xgb_class_2': 0.6186307013415344, 'weight_cat_class_0': 0.03412805217707275, 'weight_cat_class_1': 0.9566845604724838, 'weight_cat_class_2': 0.6143927849402838}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,504] Trial 634 finished with value: 0.9491720214211812 and parameters: {'weight_lgbm_class_0': 0.034364162681546066, 'weight_lgbm_class_1': 0.8844275373811279, 'weight_lgbm_class_2': 0.6073384188495864, 'weight_xgb_class_0': 0.1422943795741916, 'weight_xgb_class_1': 0.15621745011621183, 'weight_xgb_class_2': 0.6085389343346782, 'weight_cat_class_0': 0.03153808817453074, 'weight_cat_class_1': 0.9464242841125058, 'weight_cat_class_2': 0.5700968440320071}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  32%|██████████████████████████████████████████▏                                                                                         | 640/2000 [00:19<00:56, 24.05it/s]

[I 2026-07-03 10:22:55,579] Trial 635 finished with value: 0.9492017764539913 and parameters: {'weight_lgbm_class_0': 0.034726861592565376, 'weight_lgbm_class_1': 0.9685214858892642, 'weight_lgbm_class_2': 0.5567497728637437, 'weight_xgb_class_0': 0.14640607933183897, 'weight_xgb_class_1': 0.1523062451606068, 'weight_xgb_class_2': 0.5992134006375166, 'weight_cat_class_0': 0.030848615914808208, 'weight_cat_class_1': 0.9597002824889219, 'weight_cat_class_2': 0.6658889003836321}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,629] Trial 636 finished with value: 0.94872982838242 and parameters: {'weight_lgbm_class_0': 0.03424044992600801, 'weight_lgbm_class_1': 0.9659425733166765, 'weight_lgbm_class_2': 0.5988427212116187, 'weight_xgb_class_0': 0.143388229107563, 'weight_xgb_class_1': 0.15590124925569504, 'weight_xgb_class_2': 0.6367781745764874, 'weight_cat_class_0': 0.07340603261026206, 'weight_cat_class_1': 0.9526766663101195, 'weight_cat_class_2': 0.57252995066885}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,686] Trial 637 finished with value: 0.9488472826735105 and parameters: {'weight_lgbm_class_0': 0.03679882064813696, 'weight_lgbm_class_1': 0.9698111017518698, 'weight_lgbm_class_2': 0.60061127980538, 'weight_xgb_class_0': 0.14251313384536113, 'weight_xgb_class_1': 0.5055519088974997, 'weight_xgb_class_2': 0.6363793171780034, 'weight_cat_class_0': 0.0723872578555328, 'weight_cat_class_1': 0.948808410034725, 'weight_cat_class_2': 0.5630188235148238}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,693] Trial 639 finished with value: 0.9489883572387674 and parameters: {'weight_lgbm_class_0': 0.03540295643339057, 'weight_lgbm_class_1': 0.9688670188790385, 'weight_lgbm_class_2': 0.5935650829415701, 'weight_xgb_class_0': 0.12400163110548001, 'weight_xgb_class_1': 0.34934402076358, 'weight_xgb_class_2': 0.5974821741426302, 'weight_cat_class_0': 0.07328399552132184, 'weight_cat_class_1': 0.9536337199896053, 'weight_cat_class_2': 0.584854744168893}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,730] Trial 638 finished with value: 0.9489046439784922 and parameters: {'weight_lgbm_class_0': 0.03614405497632777, 'weight_lgbm_class_1': 0.9667126227169953, 'weight_lgbm_class_2': 0.5905417152862357, 'weight_xgb_class_0': 0.1306157276703807, 'weight_xgb_class_1': 0.4922509667495788, 'weight_xgb_class_2': 0.6418972759526025, 'weight_cat_class_0': 0.07340961127023835, 'weight_cat_class_1': 0.953269086944151, 'weight_cat_class_2': 0.5423723586129972}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,774] Trial 640 finished with value: 0.9492005413017658 and parameters: {'weight_lgbm_class_0': 0.034967476477665696, 'weight_lgbm_class_1': 0.9667684634467452, 'weight_lgbm_class_2': 0.5932171278862816, 'weight_xgb_class_0': 0.10543581905527476, 'weight_xgb_class_1': 0.12009331288187614, 'weight_xgb_class_2': 0.6472087333494483, 'weight_cat_class_0': 0.07167621210217973, 'weight_cat_class_1': 0.9565442505969113, 'weight_cat_class_2': 0.5424443893837182}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  32%|██████████████████████████████████████████▋                                                                                         | 647/2000 [00:20<00:48, 27.77it/s]

[I 2026-07-03 10:22:55,796] Trial 641 finished with value: 0.9476967421624259 and parameters: {'weight_lgbm_class_0': 0.0005303426759830638, 'weight_lgbm_class_1': 0.9800802160411665, 'weight_lgbm_class_2': 0.5545087708499831, 'weight_xgb_class_0': 0.2434776143359676, 'weight_xgb_class_1': 0.3596378734614899, 'weight_xgb_class_2': 0.6347785470947307, 'weight_cat_class_0': 0.06783985085998827, 'weight_cat_class_1': 0.9355801174732714, 'weight_cat_class_2': 0.5740706982611258}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,828] Trial 642 finished with value: 0.9486534320930243 and parameters: {'weight_lgbm_class_0': 0.05132055166770329, 'weight_lgbm_class_1': 0.9704547550013406, 'weight_lgbm_class_2': 0.2911422289549847, 'weight_xgb_class_0': 0.10379043705414279, 'weight_xgb_class_1': 0.46437658910607293, 'weight_xgb_class_2': 0.6478485652291887, 'weight_cat_class_0': 0.07135297578355772, 'weight_cat_class_1': 0.9365833120095064, 'weight_cat_class_2': 0.5587850852213614}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,832] Trial 643 finished with value: 0.9492014602739545 and parameters: {'weight_lgbm_class_0': 0.04208152030857502, 'weight_lgbm_class_1': 0.9648602985246786, 'weight_lgbm_class_2': 0.6903008848824899, 'weight_xgb_class_0': 0.10292711543575332, 'weight_xgb_class_1': 0.11739375269871385, 'weight_xgb_class_2': 0.6496762284849732, 'weight_cat_class_0': 0.07295322578472974, 'weight_cat_class_1': 0.9438190651926089, 'weight_cat_class_2': 0.5630511945161027}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,847] Trial 644 finished with value: 0.949471654373267 and parameters: {'weight_lgbm_class_0': 0.0008686624098039495, 'weight_lgbm_class_1': 0.9707743906801739, 'weight_lgbm_class_2': 0.6751948429418653, 'weight_xgb_class_0': 0.10333135105093066, 'weight_xgb_class_1': 0.12250015646108729, 'weight_xgb_class_2': 0.6684117580510087, 'weight_cat_class_0': 0.07046330978334558, 'weight_cat_class_1': 0.6172058047217099, 'weight_cat_class_2': 0.5567699553185411}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,895] Trial 645 finished with value: 0.9489756864680032 and parameters: {'weight_lgbm_class_0': 0.05045118397473822, 'weight_lgbm_class_1': 0.9776176243287314, 'weight_lgbm_class_2': 0.557778894481066, 'weight_xgb_class_0': 0.10363633845598116, 'weight_xgb_class_1': 0.12342964484395703, 'weight_xgb_class_2': 0.6394569443744254, 'weight_cat_class_0': 0.07632230353974287, 'weight_cat_class_1': 0.9392393770172185, 'weight_cat_class_2': 0.5525044414750697}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:55,970] Trial 646 finished with value: 0.9489847632647505 and parameters: {'weight_lgbm_class_0': 0.05538218518662941, 'weight_lgbm_class_1': 0.9987743499233165, 'weight_lgbm_class_2': 0.5627419946889111, 'weight_xgb_class_0': 0.10695266893646195, 'weight_xgb_class_1': 0.3522117792158831, 'weight_xgb_class_2': 0.6387279569085749, 'weight_cat_class_0': 0.0687623136785438, 'weight_cat_class_1': 0.9342622873851967, 'weight_cat_class_2': 0.5771647432895519}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  33%|███████████████████████████████████████████                                                                                         | 652/2000 [00:20<00:54, 24.64it/s]

[I 2026-07-03 10:22:56,036] Trial 647 finished with value: 0.9493562275090336 and parameters: {'weight_lgbm_class_0': 0.0005580238102064622, 'weight_lgbm_class_1': 0.9693284500805935, 'weight_lgbm_class_2': 0.5608776046867814, 'weight_xgb_class_0': 0.10116037299754344, 'weight_xgb_class_1': 0.3577586688028953, 'weight_xgb_class_2': 0.6456620805771945, 'weight_cat_class_0': 0.0812226677630771, 'weight_cat_class_1': 0.6094755164908382, 'weight_cat_class_2': 0.5367270480857497}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,056] Trial 648 finished with value: 0.9493756382079481 and parameters: {'weight_lgbm_class_0': 0.001261950998732747, 'weight_lgbm_class_1': 0.9934632359973026, 'weight_lgbm_class_2': 0.5551554778949663, 'weight_xgb_class_0': 0.11356978782500467, 'weight_xgb_class_1': 0.1258321243161323, 'weight_xgb_class_2': 0.6710322142740359, 'weight_cat_class_0': 0.07171231115069217, 'weight_cat_class_1': 0.9370521721698777, 'weight_cat_class_2': 0.5780615127842637}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,130] Trial 649 finished with value: 0.9496274052524357 and parameters: {'weight_lgbm_class_0': 0.05433001147559775, 'weight_lgbm_class_1': 0.9999079831539822, 'weight_lgbm_class_2': 0.5516868021038731, 'weight_xgb_class_0': 0.10193650433555605, 'weight_xgb_class_1': 0.11960286025715341, 'weight_xgb_class_2': 0.6723228355009617, 'weight_cat_class_0': 0.012830890146346072, 'weight_cat_class_1': 0.934606625466319, 'weight_cat_class_2': 0.5550473712819495}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,164] Trial 650 finished with value: 0.9496373408416686 and parameters: {'weight_lgbm_class_0': 0.05821276193923003, 'weight_lgbm_class_1': 0.997771663616236, 'weight_lgbm_class_2': 0.5589175947032757, 'weight_xgb_class_0': 0.1028596957805843, 'weight_xgb_class_1': 0.12306791465010564, 'weight_xgb_class_2': 0.6671551338534032, 'weight_cat_class_0': 0.0008264335481878002, 'weight_cat_class_1': 0.9299099873201223, 'weight_cat_class_2': 0.6709529682510439}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,180] Trial 651 finished with value: 0.949635723287376 and parameters: {'weight_lgbm_class_0': 0.0003258865284152812, 'weight_lgbm_class_1': 0.9314481530063363, 'weight_lgbm_class_2': 0.5603851617301802, 'weight_xgb_class_0': 0.057058781870058736, 'weight_xgb_class_1': 0.4451378362503144, 'weight_xgb_class_2': 0.6713473670435137, 'weight_cat_class_0': 0.10625637258111582, 'weight_cat_class_1': 0.9298299792192316, 'weight_cat_class_2': 0.5320720591618515}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,229] Trial 652 finished with value: 0.9477983247384801 and parameters: {'weight_lgbm_class_0': 0.0001971243145607695, 'weight_lgbm_class_1': 0.9973126040376217, 'weight_lgbm_class_2': 0.5583486606214809, 'weight_xgb_class_0': 0.05736700536572601, 'weight_xgb_class_1': 0.08968254796499416, 'weight_xgb_class_2': 0.66847398164637, 'weight_cat_class_0': 0.00024165089045077187, 'weight_cat_class_1': 0.9167981935778121, 'weight_cat_class_2': 0.6775391491045792}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  33%|███████████████████████████████████████████▍                                                                                        | 659/2000 [00:20<00:48, 27.81it/s]

[I 2026-07-03 10:22:56,256] Trial 653 finished with value: 0.9485494539473844 and parameters: {'weight_lgbm_class_0': 0.059097675210004016, 'weight_lgbm_class_1': 0.9263322539192096, 'weight_lgbm_class_2': 0.30747601648874334, 'weight_xgb_class_0': 0.060448122933579096, 'weight_xgb_class_1': 0.12368931098903455, 'weight_xgb_class_2': 0.662202436061694, 'weight_cat_class_0': 0.1060390775160136, 'weight_cat_class_1': 0.6205470930117917, 'weight_cat_class_2': 0.681898785332595}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,286] Trial 654 finished with value: 0.9495635983286629 and parameters: {'weight_lgbm_class_0': 0.08552935617586911, 'weight_lgbm_class_1': 0.9958589023427731, 'weight_lgbm_class_2': 0.5620821044592664, 'weight_xgb_class_0': 0.026973741347776324, 'weight_xgb_class_1': 0.09440915283111147, 'weight_xgb_class_2': 0.5519343779165997, 'weight_cat_class_0': 5.322882763678831e-05, 'weight_cat_class_1': 0.9188615834952405, 'weight_cat_class_2': 0.6753796694236927}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,301] Trial 655 finished with value: 0.9496973076190711 and parameters: {'weight_lgbm_class_0': 0.06016827649728841, 'weight_lgbm_class_1': 0.9976554775969477, 'weight_lgbm_class_2': 0.5550681602517451, 'weight_xgb_class_0': 0.05796330764394586, 'weight_xgb_class_1': 0.09139407434334848, 'weight_xgb_class_2': 0.556880315623052, 'weight_cat_class_0': 0.01523025809956118, 'weight_cat_class_1': 0.9198417855447933, 'weight_cat_class_2': 0.6800611124332282}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,334] Trial 657 finished with value: 0.9496508339515507 and parameters: {'weight_lgbm_class_0': 0.08517919075056028, 'weight_lgbm_class_1': 0.9988944808135498, 'weight_lgbm_class_2': 0.5329209839357846, 'weight_xgb_class_0': 0.05785338162842837, 'weight_xgb_class_1': 0.0958341245789792, 'weight_xgb_class_2': 0.5600411261879206, 'weight_cat_class_0': 0.014932433967637215, 'weight_cat_class_1': 0.915517332972664, 'weight_cat_class_2': 0.6737401021052024}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,342] Trial 656 finished with value: 0.9497076944612274 and parameters: {'weight_lgbm_class_0': 0.08069497973125615, 'weight_lgbm_class_1': 0.932204291307913, 'weight_lgbm_class_2': 0.5614128475609312, 'weight_xgb_class_0': 0.05434160159800189, 'weight_xgb_class_1': 0.0902844087919875, 'weight_xgb_class_2': 0.5549018517926376, 'weight_cat_class_0': 0.000532542025829686, 'weight_cat_class_1': 0.9153220275148839, 'weight_cat_class_2': 0.6824259843438393}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,416] Trial 658 finished with value: 0.9487394718881127 and parameters: {'weight_lgbm_class_0': 0.0828571798676812, 'weight_lgbm_class_1': 0.9309953539160721, 'weight_lgbm_class_2': 0.5444917689807124, 'weight_xgb_class_0': 0.05572062342335742, 'weight_xgb_class_1': 0.09387582348712786, 'weight_xgb_class_2': 0.5528423764003181, 'weight_cat_class_0': 0.10647883972220284, 'weight_cat_class_1': 0.9153588832691169, 'weight_cat_class_2': 0.677320378810173}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  33%|███████████████████████████████████████████▉                                                                                        | 665/2000 [00:20<00:53, 24.96it/s]

[I 2026-07-03 10:22:56,503] Trial 660 finished with value: 0.949717626084812 and parameters: {'weight_lgbm_class_0': 0.0854949795846922, 'weight_lgbm_class_1': 0.9292211201851761, 'weight_lgbm_class_2': 0.6194565476245324, 'weight_xgb_class_0': 0.05710976775411, 'weight_xgb_class_1': 0.08992582088462675, 'weight_xgb_class_2': 0.5527539444270332, 'weight_cat_class_0': 0.013373401665477437, 'weight_cat_class_1': 0.9138902032421865, 'weight_cat_class_2': 0.6786410372965971}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,505] Trial 659 finished with value: 0.9172201059403724 and parameters: {'weight_lgbm_class_0': 0.9073807690139026, 'weight_lgbm_class_1': 0.9377901499561596, 'weight_lgbm_class_2': 0.5360798413442022, 'weight_xgb_class_0': 0.05969649295665446, 'weight_xgb_class_1': 0.09259680423195057, 'weight_xgb_class_2': 0.555119632352057, 'weight_cat_class_0': 0.012153454036061655, 'weight_cat_class_1': 0.9105171893734614, 'weight_cat_class_2': 0.6804465600685692}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,575] Trial 661 finished with value: 0.9487878977553184 and parameters: {'weight_lgbm_class_0': 0.08345348699056764, 'weight_lgbm_class_1': 0.9249168680824372, 'weight_lgbm_class_2': 0.5349095741349335, 'weight_xgb_class_0': 0.06272106545954022, 'weight_xgb_class_1': 0.4470099715044165, 'weight_xgb_class_2': 0.5571026936767005, 'weight_cat_class_0': 0.10863664000745721, 'weight_cat_class_1': 0.9093979780535709, 'weight_cat_class_2': 0.6726255052819009}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,612] Trial 663 finished with value: 0.9497178437891519 and parameters: {'weight_lgbm_class_0': 0.08405819644293094, 'weight_lgbm_class_1': 0.931624953740689, 'weight_lgbm_class_2': 0.62320632171175, 'weight_xgb_class_0': 0.042629265373142565, 'weight_xgb_class_1': 0.2563111514178144, 'weight_xgb_class_2': 0.5531151864891919, 'weight_cat_class_0': 0.017293563328783828, 'weight_cat_class_1': 0.9103114400408008, 'weight_cat_class_2': 0.629584637663141}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,621] Trial 662 finished with value: 0.9497216192481938 and parameters: {'weight_lgbm_class_0': 0.08473531887930232, 'weight_lgbm_class_1': 0.929426911285701, 'weight_lgbm_class_2': 0.5409416729262468, 'weight_xgb_class_0': 0.06129584048309914, 'weight_xgb_class_1': 0.08941370604129031, 'weight_xgb_class_2': 0.5569276265028602, 'weight_cat_class_0': 0.0002960231652503406, 'weight_cat_class_1': 0.9129678754024083, 'weight_cat_class_2': 0.6813007620291924}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,668] Trial 664 finished with value: 0.9496094591989171 and parameters: {'weight_lgbm_class_0': 0.08789118036733683, 'weight_lgbm_class_1': 0.9349552431888326, 'weight_lgbm_class_2': 0.34659444696082975, 'weight_xgb_class_0': 0.029781442308668776, 'weight_xgb_class_1': 0.09079404594355198, 'weight_xgb_class_2': 0.5544023028534617, 'weight_cat_class_0': 0.016256139795759666, 'weight_cat_class_1': 0.5632737057085557, 'weight_cat_class_2': 0.6301677482247675}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,698] Trial 665 finished with value: 0.9496959675738079 and parameters: {'weight_lgbm_class_0': 0.08363518510798733, 'weight_lgbm_class_1': 0.9292650370843321, 'weight_lgbm_class_2': 0.6218653781415954, 'weight_xgb_class_0': 0.041425089986950464, 'weight_xgb_class_1': 0.09350231416102092, 'weight_xgb_class_2': 0.5563066846476202, 'weight_cat_class_0': 0.019637592378921806, 'weight_cat_class_1': 0.9138576143800323, 'weight_cat_class_2': 0.630951431605122}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  34%|████████████████████████████████████████████▏                                                                                       | 670/2000 [00:21<00:48, 27.55it/s]

[I 2026-07-03 10:22:56,743] Trial 666 finished with value: 0.910307427939038 and parameters: {'weight_lgbm_class_0': 0.9080043454621165, 'weight_lgbm_class_1': 0.9004362547657977, 'weight_lgbm_class_2': 0.5320371430938085, 'weight_xgb_class_0': 0.1816095631181685, 'weight_xgb_class_1': 0.25393713127320844, 'weight_xgb_class_2': 0.5578339045658406, 'weight_cat_class_0': 0.02081135804028844, 'weight_cat_class_1': 0.8993865544221252, 'weight_cat_class_2': 0.6325783820944193}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,751] Trial 667 finished with value: 0.9386150354052646 and parameters: {'weight_lgbm_class_0': 0.07923544410643926, 'weight_lgbm_class_1': 0.9360487251097265, 'weight_lgbm_class_2': 0.5350141260924501, 'weight_xgb_class_0': 0.42847916768548994, 'weight_xgb_class_1': 0.25156734598686764, 'weight_xgb_class_2': 0.5549373276317459, 'weight_cat_class_0': 0.05021062362367146, 'weight_cat_class_1': 0.9773834161406356, 'weight_cat_class_2': 0.6258453519983953}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,789] Trial 668 finished with value: 0.9497160869781647 and parameters: {'weight_lgbm_class_0': 0.08146629079724506, 'weight_lgbm_class_1': 0.9382869607831139, 'weight_lgbm_class_2': 0.619103476779442, 'weight_xgb_class_0': 0.03137794845118362, 'weight_xgb_class_1': 0.07040455010418492, 'weight_xgb_class_2': 0.5612767143884471, 'weight_cat_class_0': 0.016263804457845414, 'weight_cat_class_1': 0.9040936468884527, 'weight_cat_class_2': 0.6285996754839563}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,837] Trial 669 finished with value: 0.949671318058073 and parameters: {'weight_lgbm_class_0': 0.09126127723346497, 'weight_lgbm_class_1': 0.8963002472497477, 'weight_lgbm_class_2': 0.351191405469867, 'weight_xgb_class_0': 0.03342092419289188, 'weight_xgb_class_1': 0.07300407328663154, 'weight_xgb_class_2': 0.5594639621170833, 'weight_cat_class_0': 0.0007187630881363982, 'weight_cat_class_1': 0.8997314810527007, 'weight_cat_class_2': 0.6302248980550738}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,866] Trial 670 finished with value: 0.9496139675139551 and parameters: {'weight_lgbm_class_0': 0.08580016067462908, 'weight_lgbm_class_1': 0.8954503265972606, 'weight_lgbm_class_2': 0.6125814744591087, 'weight_xgb_class_0': 0.03513625625188265, 'weight_xgb_class_1': 0.0675728854538378, 'weight_xgb_class_2': 0.5850047236323029, 'weight_cat_class_0': 0.000505484128182427, 'weight_cat_class_1': 0.898407989701876, 'weight_cat_class_2': 0.6276635063393124}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  34%|████████████████████████████████████████████▋                                                                                       | 677/2000 [00:21<00:52, 25.41it/s]

[I 2026-07-03 10:22:56,959] Trial 672 finished with value: 0.9483619297290528 and parameters: {'weight_lgbm_class_0': 0.07761486993798558, 'weight_lgbm_class_1': 0.910299889054126, 'weight_lgbm_class_2': 0.624635331691016, 'weight_xgb_class_0': 0.17370756462328055, 'weight_xgb_class_1': 0.06505328240657549, 'weight_xgb_class_2': 0.5816966665029729, 'weight_cat_class_0': 0.013751009018765496, 'weight_cat_class_1': 0.881970786453976, 'weight_cat_class_2': 0.6281349181144016}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:56,981] Trial 671 finished with value: 0.9483438967956407 and parameters: {'weight_lgbm_class_0': 0.08785712173874784, 'weight_lgbm_class_1': 0.9023816846408661, 'weight_lgbm_class_2': 0.5791686839470579, 'weight_xgb_class_0': 0.17282809877135086, 'weight_xgb_class_1': 0.07056600337338031, 'weight_xgb_class_2': 0.583824536387841, 'weight_cat_class_0': 0.0006133278595122221, 'weight_cat_class_1': 0.888018012716722, 'weight_cat_class_2': 0.631582328333617}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,037] Trial 674 finished with value: 0.9495956860872875 and parameters: {'weight_lgbm_class_0': 0.09568090706951696, 'weight_lgbm_class_1': 0.9004297559641108, 'weight_lgbm_class_2': 0.6422520861377154, 'weight_xgb_class_0': 0.025015253668609128, 'weight_xgb_class_1': 0.07518178739285565, 'weight_xgb_class_2': 0.5418236274649563, 'weight_cat_class_0': 0.0005812120434368351, 'weight_cat_class_1': 0.8876968997333046, 'weight_cat_class_2': 0.6550422291567185}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,079] Trial 673 finished with value: 0.949581262758829 and parameters: {'weight_lgbm_class_0': 0.09178526533024674, 'weight_lgbm_class_1': 0.8995188831031141, 'weight_lgbm_class_2': 0.645885915524573, 'weight_xgb_class_0': 0.03441120207288692, 'weight_xgb_class_1': 0.06093495752783755, 'weight_xgb_class_2': 0.5784098359155643, 'weight_cat_class_0': 0.0006391269610530777, 'weight_cat_class_1': 0.8850200900321834, 'weight_cat_class_2': 0.6296579356558644}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,091] Trial 675 finished with value: 0.9497027283654149 and parameters: {'weight_lgbm_class_0': 0.10675153904201702, 'weight_lgbm_class_1': 0.8898866213574621, 'weight_lgbm_class_2': 0.6351172163791096, 'weight_xgb_class_0': 0.02890751900581823, 'weight_xgb_class_1': 0.2626309063033959, 'weight_xgb_class_2': 0.5300619011279943, 'weight_cat_class_0': 0.013514370467877632, 'weight_cat_class_1': 0.8877864076214668, 'weight_cat_class_2': 0.6890096406422014}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,107] Trial 676 finished with value: 0.9496465046211062 and parameters: {'weight_lgbm_class_0': 0.10167733343206134, 'weight_lgbm_class_1': 0.9079012845666361, 'weight_lgbm_class_2': 0.6456424238249574, 'weight_xgb_class_0': 0.028312253152054507, 'weight_xgb_class_1': 0.06231994290375927, 'weight_xgb_class_2': 0.5402431227205768, 'weight_cat_class_0': 0.014683154309033462, 'weight_cat_class_1': 0.8897759178263245, 'weight_cat_class_2': 0.6951130790571639}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,155] Trial 677 finished with value: 0.9496842887973306 and parameters: {'weight_lgbm_class_0': 0.10248491128811427, 'weight_lgbm_class_1': 0.8959510241908278, 'weight_lgbm_class_2': 0.6165329054621529, 'weight_xgb_class_0': 0.03484947505613832, 'weight_xgb_class_1': 0.06822048232453576, 'weight_xgb_class_2': 0.5368681360382296, 'weight_cat_class_0': 3.82714963078918e-05, 'weight_cat_class_1': 0.8783243881447036, 'weight_cat_class_2': 0.6293222641056808}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  34%|█████████████████████████████████████████████                                                                                       | 682/2000 [00:21<00:46, 28.13it/s]

[I 2026-07-03 10:22:57,191] Trial 678 finished with value: 0.9496237453111869 and parameters: {'weight_lgbm_class_0': 0.08864778681862995, 'weight_lgbm_class_1': 0.8985439489816563, 'weight_lgbm_class_2': 0.6443815595934641, 'weight_xgb_class_0': 0.0323047705830794, 'weight_xgb_class_1': 0.0662528059578998, 'weight_xgb_class_2': 0.5426126308120433, 'weight_cat_class_0': 0.012912382886521264, 'weight_cat_class_1': 0.8875417489338628, 'weight_cat_class_2': 0.6536034408749135}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,219] Trial 679 finished with value: 0.9497114079799912 and parameters: {'weight_lgbm_class_0': 0.10848258625188088, 'weight_lgbm_class_1': 0.8972547984297032, 'weight_lgbm_class_2': 0.6489235815273019, 'weight_xgb_class_0': 0.026814858787721385, 'weight_xgb_class_1': 0.0662421442900088, 'weight_xgb_class_2': 0.532136595591617, 'weight_cat_class_0': 0.015654496113871395, 'weight_cat_class_1': 0.8867932460603974, 'weight_cat_class_2': 0.5923798212859303}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,258] Trial 680 finished with value: 0.9496766318631599 and parameters: {'weight_lgbm_class_0': 0.10336601878908587, 'weight_lgbm_class_1': 0.8982420448445333, 'weight_lgbm_class_2': 0.6206817990870251, 'weight_xgb_class_0': 0.02673527103034698, 'weight_xgb_class_1': 0.06842464422236233, 'weight_xgb_class_2': 0.537773062653517, 'weight_cat_class_0': 0.000728832067133519, 'weight_cat_class_1': 0.8878016757936023, 'weight_cat_class_2': 0.6286991512998211}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,275] Trial 681 finished with value: 0.9497082585872246 and parameters: {'weight_lgbm_class_0': 0.10523774140406167, 'weight_lgbm_class_1': 0.8919594056371435, 'weight_lgbm_class_2': 0.6170997798523563, 'weight_xgb_class_0': 0.021490850733793827, 'weight_xgb_class_1': 0.06278678767924067, 'weight_xgb_class_2': 0.5344081371681066, 'weight_cat_class_0': 0.0021492352129134705, 'weight_cat_class_1': 0.8864415316340253, 'weight_cat_class_2': 0.5943352396101624}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,301] Trial 682 finished with value: 0.9496659078129422 and parameters: {'weight_lgbm_class_0': 0.10553575281031059, 'weight_lgbm_class_1': 0.9024608369880807, 'weight_lgbm_class_2': 0.6296919000646786, 'weight_xgb_class_0': 0.02076167888876953, 'weight_xgb_class_1': 0.0656152375122911, 'weight_xgb_class_2': 0.533543830141133, 'weight_cat_class_0': 0.014032336336083653, 'weight_cat_class_1': 0.8727266192072212, 'weight_cat_class_2': 0.5919632652660192}. Best is trial 503 with value: 0.9497676925748403.

[I 2026-07-03 10:22:57,428] Trial 683 finished with value: 0.9496563569336466 and parameters: {'weight_lgbm_class_0': 0.10265980020330027, 'weight_lgbm_class_1': 0.9006800406640291, 'weight_lgbm_class_2': 0.655609851012507, 'weight_xgb_class_0': 0.024776987721546413, 'weight_xgb_class_1': 0.044398526820429704, 'weight_xgb_class_2': 0.5301781513412706, 'weight_cat_class_0': 0.013534298037797172, 'weight_cat_class_1': 0.8875387532925209, 'weight_cat_class_2': 0.5894197314104734}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,467] Trial 685 finished with value: 0.9496137861804662 and parameters: {'weight_lgbm_class_0': 0.13258528065983188, 'weight_lgbm_class_1': 0.9175560996256866, 'weight_lgbm_class_2': 0.6493853442860085, 'weight_xgb_class_0': 0.016754982763989172, 'weight_xgb_class_1': 0.05607252232275045, 'weight_xgb_class_2': 0.5369612588983462, 'weight_cat_class_0': 0.01802846443173744, 'weight_cat_class_1': 0.8829899097664506, 'weight_cat_class_2': 0.5999089639223252}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,480] Trial 684 finished with value: 0.9496436678128891 and parameters: {'weight_lgbm_class_0': 0.1051350577436827, 'weight_lgbm_class_1': 0.9167156266558725, 'weight_lgbm_class_2': 0.643663406659392, 'weight_xgb_class_0': 0.021808913930575612, 'weight_xgb_class_1': 0.051184665935484416, 'weight_xgb_class_2': 0.5362520251120475, 'weight_cat_class_0': 0.018038215223877937, 'weight_cat_class_1': 0.8879826517213053, 'weight_cat_class_2': 0.6560706688484691}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,524] Trial 686 finished with value: 0.9496425124779773 and parameters: {'weight_lgbm_class_0': 0.12722769615123838, 'weight_lgbm_class_1': 0.8766452056613036, 'weight_lgbm_class_2': 0.656460426620128, 'weight_xgb_class_0': 0.01540650485315126, 'weight_xgb_class_1': 0.29982161567810844, 'weight_xgb_class_2': 0.5262300890309168, 'weight_cat_class_0': 0.019242311431983693, 'weight_cat_class_1': 0.8973528447205572, 'weight_cat_class_2': 0.8306933507865798}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,568] Trial 687 finished with value: 0.9496223021460275 and parameters: {'weight_lgbm_class_0': 0.1227451310199214, 'weight_lgbm_class_1': 0.8782925990079927, 'weight_lgbm_class_2': 0.6484089507189573, 'weight_xgb_class_0': 0.01521980752304394, 'weight_xgb_class_1': 0.04222225919208097, 'weight_xgb_class_2': 0.5333353179011082, 'weight_cat_class_0': 0.01641286840139046, 'weight_cat_class_1': 0.9037766386693531, 'weight_cat_class_2': 0.5142788640246654}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,574] Trial 688 finished with value: 0.9496647811979809 and parameters: {'weight_lgbm_class_0': 0.1334877419892607, 'weight_lgbm_class_1': 0.8859646217207545, 'weight_lgbm_class_2': 0.6750473700583015, 'weight_xgb_class_0': 0.017818782879037175, 'weight_xgb_class_1': 0.27748157857482814, 'weight_xgb_class_2': 0.5254158550519074, 'weight_cat_class_0': 0.019272767302319103, 'weight_cat_class_1': 0.9082327805094609, 'weight_cat_class_2': 0.5992097941662945}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  35%|█████████████████████████████████████████████▊                                                                                      | 695/2000 [00:21<00:41, 31.40it/s]

[I 2026-07-03 10:22:57,623] Trial 689 finished with value: 0.9497143591337469 and parameters: {'weight_lgbm_class_0': 0.13226490042811462, 'weight_lgbm_class_1': 0.8738976116134063, 'weight_lgbm_class_2': 0.66769394274602, 'weight_xgb_class_0': 0.01305232889561151, 'weight_xgb_class_1': 0.2438621459751704, 'weight_xgb_class_2': 0.5269414077842278, 'weight_cat_class_0': 0.019343303884227402, 'weight_cat_class_1': 0.9069656698624259, 'weight_cat_class_2': 0.5981092876365389}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,652] Trial 691 finished with value: 0.9495543934468058 and parameters: {'weight_lgbm_class_0': 0.12938366328408887, 'weight_lgbm_class_1': 0.8746268104733466, 'weight_lgbm_class_2': 0.6397543544900802, 'weight_xgb_class_0': 0.019645394782405512, 'weight_xgb_class_1': 0.038178418022678545, 'weight_xgb_class_2': 0.5206196977434019, 'weight_cat_class_0': 0.02000161375153623, 'weight_cat_class_1': 0.908863856700464, 'weight_cat_class_2': 0.5976667403648984}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,663] Trial 690 finished with value: 0.9496654641491481 and parameters: {'weight_lgbm_class_0': 0.11926019194893267, 'weight_lgbm_class_1': 0.8831192160149222, 'weight_lgbm_class_2': 0.6835115164083815, 'weight_xgb_class_0': 0.016081401215874657, 'weight_xgb_class_1': 0.3036433335532211, 'weight_xgb_class_2': 0.5214512305035169, 'weight_cat_class_0': 0.027655047954082038, 'weight_cat_class_1': 0.9074935449687189, 'weight_cat_class_2': 0.5891163267944175}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,690] Trial 692 finished with value: 0.9497372277135386 and parameters: {'weight_lgbm_class_0': 0.12184897199286071, 'weight_lgbm_class_1': 0.874609387263185, 'weight_lgbm_class_2': 0.6487992952852857, 'weight_xgb_class_0': 0.0011840092744291007, 'weight_xgb_class_1': 0.292388527383219, 'weight_xgb_class_2': 0.5209564386946487, 'weight_cat_class_0': 0.020576063709756967, 'weight_cat_class_1': 0.90983173632004, 'weight_cat_class_2': 0.5953164451155559}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,731] Trial 694 finished with value: 0.9496762868396305 and parameters: {'weight_lgbm_class_0': 0.10998207826106948, 'weight_lgbm_class_1': 0.8795226423399098, 'weight_lgbm_class_2': 0.6665198316283327, 'weight_xgb_class_0': 0.009960785880641247, 'weight_xgb_class_1': 0.04120694896762436, 'weight_xgb_class_2': 0.5206256112230835, 'weight_cat_class_0': 0.022743790783981498, 'weight_cat_class_1': 0.9115189763178388, 'weight_cat_class_2': 0.5876394681484761}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,744] Trial 693 finished with value: 0.9496238618695125 and parameters: {'weight_lgbm_class_0': 0.134435789380427, 'weight_lgbm_class_1': 0.880710925272908, 'weight_lgbm_class_2': 0.6772676707710094, 'weight_xgb_class_0': 0.0028575994843592183, 'weight_xgb_class_1': 0.03185842342615884, 'weight_xgb_class_2': 0.5230027952704493, 'weight_cat_class_0': 0.021136068185859825, 'weight_cat_class_1': 0.9108879816825113, 'weight_cat_class_2': 0.5894364749253623}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  35%|██████████████████████████████████████████████▎                                                                                     | 701/2000 [00:22<00:54, 24.03it/s]

[I 2026-07-03 10:22:57,907] Trial 695 finished with value: 0.9495651310589951 and parameters: {'weight_lgbm_class_0': 0.1328793780411609, 'weight_lgbm_class_1': 0.9255298845198118, 'weight_lgbm_class_2': 0.6611232266030007, 'weight_xgb_class_0': 0.012586799929348066, 'weight_xgb_class_1': 0.0386009492936771, 'weight_xgb_class_2': 0.5187592239021104, 'weight_cat_class_0': 0.025033032450637066, 'weight_cat_class_1': 0.9084921860293332, 'weight_cat_class_2': 0.583025289686695}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,914] Trial 696 finished with value: 0.9494957050417527 and parameters: {'weight_lgbm_class_0': 0.13937689928888927, 'weight_lgbm_class_1': 0.8692849423782151, 'weight_lgbm_class_2': 0.6609943589150301, 'weight_xgb_class_0': 0.006953708104488247, 'weight_xgb_class_1': 0.04071178914473883, 'weight_xgb_class_2': 0.4683594095595483, 'weight_cat_class_0': 0.03286343814927148, 'weight_cat_class_1': 0.9107620058229599, 'weight_cat_class_2': 0.6023684625562763}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,916] Trial 697 finished with value: 0.9494158050225298 and parameters: {'weight_lgbm_class_0': 0.1443118226020646, 'weight_lgbm_class_1': 0.8804821704850535, 'weight_lgbm_class_2': 0.6823838026619443, 'weight_xgb_class_0': 0.008146285404887318, 'weight_xgb_class_1': 0.03584771982270723, 'weight_xgb_class_2': 0.5232625083706071, 'weight_cat_class_0': 0.03416648384446701, 'weight_cat_class_1': 0.9115395321519175, 'weight_cat_class_2': 0.5878652572681868}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:57,977] Trial 698 finished with value: 0.949335385528873 and parameters: {'weight_lgbm_class_0': 0.14865247469562967, 'weight_lgbm_class_1': 0.873606279745983, 'weight_lgbm_class_2': 0.6797580203974446, 'weight_xgb_class_0': 0.0013276322527393108, 'weight_xgb_class_1': 0.04472828582831321, 'weight_xgb_class_2': 0.4709198189071497, 'weight_cat_class_0': 0.036360053640927245, 'weight_cat_class_1': 0.912151440427935, 'weight_cat_class_2': 0.5178861844887177}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,012] Trial 700 finished with value: 0.9494512254861446 and parameters: {'weight_lgbm_class_0': 0.1383378112358037, 'weight_lgbm_class_1': 0.8734762493955275, 'weight_lgbm_class_2': 0.7145125169159123, 'weight_xgb_class_0': 0.008691007981221808, 'weight_xgb_class_1': 0.29955822589545755, 'weight_xgb_class_2': 0.46379769701100687, 'weight_cat_class_0': 0.039557365065927774, 'weight_cat_class_1': 0.8569525791350281, 'weight_cat_class_2': 0.5838220933083188}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,026] Trial 699 finished with value: 0.9487177629916084 and parameters: {'weight_lgbm_class_0': 0.156931079380217, 'weight_lgbm_class_1': 0.8808525311972977, 'weight_lgbm_class_2': 0.6269596956069369, 'weight_xgb_class_0': 0.0417116284455921, 'weight_xgb_class_1': 0.25637225825756393, 'weight_xgb_class_2': 0.5159802606849873, 'weight_cat_class_0': 0.038757326454368704, 'weight_cat_class_1': 0.8611078901899661, 'weight_cat_class_2': 0.48805740926654007}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,093] Trial 702 finished with value: 0.9496896032935349 and parameters: {'weight_lgbm_class_0': 0.11644913443476897, 'weight_lgbm_class_1': 0.8705273826016688, 'weight_lgbm_class_2': 0.6686665366476708, 'weight_xgb_class_0': 0.006740287669466834, 'weight_xgb_class_1': 0.23690289045459612, 'weight_xgb_class_2': 0.5665547794349038, 'weight_cat_class_0': 0.03798262006296173, 'weight_cat_class_1': 0.9141943909935396, 'weight_cat_class_2': 0.5822324544926303}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  35%|██████████████████████████████████████████████▌                                                                                     | 706/2000 [00:22<00:48, 26.51it/s]

[I 2026-07-03 10:22:58,112] Trial 701 finished with value: 0.9482238484589786 and parameters: {'weight_lgbm_class_0': 0.1501150681957411, 'weight_lgbm_class_1': 0.0341632833166467, 'weight_lgbm_class_2': 0.7059843836158287, 'weight_xgb_class_0': 0.00030395968885984495, 'weight_xgb_class_1': 0.2842126535582975, 'weight_xgb_class_2': 0.46599826776968667, 'weight_cat_class_0': 0.0398419008986725, 'weight_cat_class_1': 0.8628463875897289, 'weight_cat_class_2': 0.5823459938269768}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,115] Trial 703 finished with value: 0.9496653071307809 and parameters: {'weight_lgbm_class_0': 0.15397096872324556, 'weight_lgbm_class_1': 0.9245854145731006, 'weight_lgbm_class_2': 0.6564868114859869, 'weight_xgb_class_0': 0.0036438508137038653, 'weight_xgb_class_1': 0.2635924003118563, 'weight_xgb_class_2': 0.47523383281947573, 'weight_cat_class_0': 0.00039550884966967764, 'weight_cat_class_1': 0.8660451616777892, 'weight_cat_class_2': 0.5809271751413356}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,165] Trial 704 finished with value: 0.9493585755289354 and parameters: {'weight_lgbm_class_0': 0.15784891828745568, 'weight_lgbm_class_1': 0.921319257074294, 'weight_lgbm_class_2': 0.6683503585266302, 'weight_xgb_class_0': 0.006121796071665946, 'weight_xgb_class_1': 0.2561447160321761, 'weight_xgb_class_2': 0.4699638660234985, 'weight_cat_class_0': 0.03831894934737179, 'weight_cat_class_1': 0.8647317412202051, 'weight_cat_class_2': 0.5778265890235841}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,179] Trial 705 finished with value: 0.9486672709285942 and parameters: {'weight_lgbm_class_0': 0.16720601568859314, 'weight_lgbm_class_1': 0.4205426215823539, 'weight_lgbm_class_2': 0.6711154195125676, 'weight_xgb_class_0': 0.010292865651038097, 'weight_xgb_class_1': 0.26877002059404387, 'weight_xgb_class_2': 0.4791612785610635, 'weight_cat_class_0': 0.040913726646160706, 'weight_cat_class_1': 0.8530169625576378, 'weight_cat_class_2': 0.5785347178469389}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,201] Trial 706 finished with value: 0.9491731234459428 and parameters: {'weight_lgbm_class_0': 0.16549742891773195, 'weight_lgbm_class_1': 0.9280321819166243, 'weight_lgbm_class_2': 0.6642625348244445, 'weight_xgb_class_0': 0.003515596549731055, 'weight_xgb_class_1': 0.2822807435735644, 'weight_xgb_class_2': 0.4712624326932049, 'weight_cat_class_0': 0.04475755354652143, 'weight_cat_class_1': 0.8575849562533332, 'weight_cat_class_2': 0.579770641693663}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  36%|███████████████████████████████████████████████                                                                                     | 713/2000 [00:22<00:52, 24.53it/s]

[I 2026-07-03 10:22:58,345] Trial 707 finished with value: 0.9494348714097777 and parameters: {'weight_lgbm_class_0': 0.15386325533021072, 'weight_lgbm_class_1': 0.9256958287732435, 'weight_lgbm_class_2': 0.6666561029698781, 'weight_xgb_class_0': 0.03661837255568263, 'weight_xgb_class_1': 0.28118684700164853, 'weight_xgb_class_2': 0.558343972383773, 'weight_cat_class_0': 6.0106219058778804e-05, 'weight_cat_class_1': 0.8607436325801993, 'weight_cat_class_2': 0.5661803445249833}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,365] Trial 708 finished with value: 0.9497153921430841 and parameters: {'weight_lgbm_class_0': 0.11603848092568254, 'weight_lgbm_class_1': 0.9183060880828552, 'weight_lgbm_class_2': 0.667348058727324, 'weight_xgb_class_0': 0.005095844011431053, 'weight_xgb_class_1': 0.26740980251444746, 'weight_xgb_class_2': 0.5623869418872531, 'weight_cat_class_0': 0.043389948127124406, 'weight_cat_class_1': 0.8608318422575827, 'weight_cat_class_2': 0.5753212821410997}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,394] Trial 709 finished with value: 0.9493681477446456 and parameters: {'weight_lgbm_class_0': 0.16253436584988934, 'weight_lgbm_class_1': 0.922593279944987, 'weight_lgbm_class_2': 0.6866085211261653, 'weight_xgb_class_0': 0.00016925122764135914, 'weight_xgb_class_1': 0.2665817696980626, 'weight_xgb_class_2': 0.5620372245330689, 'weight_cat_class_0': 0.04173020688560626, 'weight_cat_class_1': 0.8745772394924033, 'weight_cat_class_2': 0.5772197543437277}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,455] Trial 711 finished with value: 0.9492309145236115 and parameters: {'weight_lgbm_class_0': 0.16712898394587367, 'weight_lgbm_class_1': 0.9203239581083443, 'weight_lgbm_class_2': 0.6242947174767116, 'weight_xgb_class_0': 0.03976588798564498, 'weight_xgb_class_1': 0.29148089935633315, 'weight_xgb_class_2': 0.5646631917415675, 'weight_cat_class_0': 0.001844459918935986, 'weight_cat_class_1': 0.853650281680955, 'weight_cat_class_2': 0.5441993575764962}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,473] Trial 710 finished with value: 0.9487978894432433 and parameters: {'weight_lgbm_class_0': 0.15154015740424664, 'weight_lgbm_class_1': 0.6972677055360323, 'weight_lgbm_class_2': 0.6968838341817902, 'weight_xgb_class_0': 0.04030990394545492, 'weight_xgb_class_1': 0.2859251594325309, 'weight_xgb_class_2': 0.5647118576087408, 'weight_cat_class_0': 0.04545629464515597, 'weight_cat_class_1': 0.8587173073283096, 'weight_cat_class_2': 0.5540529239867221}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,497] Trial 712 finished with value: 0.9496671924457782 and parameters: {'weight_lgbm_class_0': 0.11529543157613183, 'weight_lgbm_class_1': 0.9241664986491116, 'weight_lgbm_class_2': 0.6555803498744344, 'weight_xgb_class_0': 0.04191563499493989, 'weight_xgb_class_1': 0.26945535700439793, 'weight_xgb_class_2': 0.5675783599559642, 'weight_cat_class_0': 0.0011114292398147485, 'weight_cat_class_1': 0.8668216498506475, 'weight_cat_class_2': 0.5541554754444885}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,544] Trial 713 finished with value: 0.949293011308186 and parameters: {'weight_lgbm_class_0': 0.11414940459033468, 'weight_lgbm_class_1': 0.9202734643454539, 'weight_lgbm_class_2': 0.6332883551061601, 'weight_xgb_class_0': 0.043293791368769145, 'weight_xgb_class_1': 0.2794055149046826, 'weight_xgb_class_2': 0.5671054571564954, 'weight_cat_class_0': 0.04493341314843596, 'weight_cat_class_1': 0.8721590160122928, 'weight_cat_class_2': 0.5420421080903297}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  36%|███████████████████████████████████████████████▍                                                                                    | 718/2000 [00:22<00:46, 27.65it/s]

[I 2026-07-03 10:22:58,581] Trial 716 finished with value: 0.9485890375789655 and parameters: {'weight_lgbm_class_0': 0.1803102732190462, 'weight_lgbm_class_1': 0.9354353177626635, 'weight_lgbm_class_2': 0.6295915988482605, 'weight_xgb_class_0': 0.03874404655562239, 'weight_xgb_class_1': 0.28152936167312376, 'weight_xgb_class_2': 0.5692609584252816, 'weight_cat_class_0': 0.05028596548244613, 'weight_cat_class_1': 0.9317841581866796, 'weight_cat_class_2': 0.6134946495838235}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,582] Trial 714 finished with value: 0.9492477848823979 and parameters: {'weight_lgbm_class_0': 0.17629394225057243, 'weight_lgbm_class_1': 0.9251640765536742, 'weight_lgbm_class_2': 0.7025689990406815, 'weight_xgb_class_0': 0.036593849194906755, 'weight_xgb_class_1': 0.26967265146152314, 'weight_xgb_class_2': 0.5688660394685229, 'weight_cat_class_0': 7.341458471149341e-05, 'weight_cat_class_1': 0.8699046102304723, 'weight_cat_class_2': 0.550630237859543}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,591] Trial 715 finished with value: 0.9493018190566115 and parameters: {'weight_lgbm_class_0': 0.17186743698249884, 'weight_lgbm_class_1': 0.9263483321718804, 'weight_lgbm_class_2': 0.6978927150175419, 'weight_xgb_class_0': 0.03865413582366058, 'weight_xgb_class_1': 0.24630998849010147, 'weight_xgb_class_2': 0.5584475210538296, 'weight_cat_class_0': 0.0017310855568915648, 'weight_cat_class_1': 0.9247523443764412, 'weight_cat_class_2': 0.5522569291075919}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,640] Trial 717 finished with value: 0.9153709961040776 and parameters: {'weight_lgbm_class_0': 0.11608371336714085, 'weight_lgbm_class_1': 0.6967471660523297, 'weight_lgbm_class_2': 0.6275316777062938, 'weight_xgb_class_0': 0.8394406568380917, 'weight_xgb_class_1': 0.2345298263303517, 'weight_xgb_class_2': 0.5680184451222511, 'weight_cat_class_0': 0.00011750011197352722, 'weight_cat_class_1': 0.9218162715079489, 'weight_cat_class_2': 0.5431191276315339}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,671] Trial 718 finished with value: 0.9496670400508648 and parameters: {'weight_lgbm_class_0': 0.11435843456699382, 'weight_lgbm_class_1': 0.9427259370562888, 'weight_lgbm_class_2': 0.7139181783876675, 'weight_xgb_class_0': 0.04181183703353072, 'weight_xgb_class_1': 0.2851320492109059, 'weight_xgb_class_2': 0.5649409151141044, 'weight_cat_class_0': 0.015316948099615141, 'weight_cat_class_1': 0.9248334918958782, 'weight_cat_class_2': 0.539130057640245}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  36%|███████████████████████████████████████████████▊                                                                                    | 724/2000 [00:23<00:50, 25.43it/s]

[I 2026-07-03 10:22:58,816] Trial 720 finished with value: 0.9492263636182615 and parameters: {'weight_lgbm_class_0': 0.12377366798130582, 'weight_lgbm_class_1': 0.9079834200611804, 'weight_lgbm_class_2': 0.6910866802576161, 'weight_xgb_class_0': 0.03838879687522871, 'weight_xgb_class_1': 0.28622604668401963, 'weight_xgb_class_2': 0.5707263684179449, 'weight_cat_class_0': 0.05108277755530199, 'weight_cat_class_1': 0.8361674313124189, 'weight_cat_class_2': 0.5609752476501308}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,854] Trial 721 finished with value: 0.9481214590005314 and parameters: {'weight_lgbm_class_0': 0.11535872250867737, 'weight_lgbm_class_1': 0.17182715149623284, 'weight_lgbm_class_2': 0.6993746867197589, 'weight_xgb_class_0': 0.037866595770470586, 'weight_xgb_class_1': 0.27027916585286765, 'weight_xgb_class_2': 0.5674387231694665, 'weight_cat_class_0': 0.05495564585663682, 'weight_cat_class_1': 0.8227289150979641, 'weight_cat_class_2': 0.5408930747768681}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,863] Trial 719 finished with value: 0.9492030326752667 and parameters: {'weight_lgbm_class_0': 0.11738953342068367, 'weight_lgbm_class_1': 0.9135639724516669, 'weight_lgbm_class_2': 0.6401259973211053, 'weight_xgb_class_0': 0.03921657180553658, 'weight_xgb_class_1': 0.27131886463175975, 'weight_xgb_class_2': 0.5643080166559906, 'weight_cat_class_0': 0.050710789186035374, 'weight_cat_class_1': 0.8395031868345223, 'weight_cat_class_2': 0.5424615474099191}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,931] Trial 723 finished with value: 0.9484192030310915 and parameters: {'weight_lgbm_class_0': 0.1854397198712202, 'weight_lgbm_class_1': 0.9035737409800202, 'weight_lgbm_class_2': 0.7015872485461088, 'weight_xgb_class_0': 0.031399598288288394, 'weight_xgb_class_1': 0.330316840980918, 'weight_xgb_class_2': 0.5455936053080926, 'weight_cat_class_0': 0.050956773808145825, 'weight_cat_class_1': 0.7365515089830457, 'weight_cat_class_2': 0.5324184769265377}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,966] Trial 722 finished with value: 0.9150223151938642 and parameters: {'weight_lgbm_class_0': 0.11902326609618971, 'weight_lgbm_class_1': 0.8996764784540227, 'weight_lgbm_class_2': 0.6267480230838761, 'weight_xgb_class_0': 0.83890346149292, 'weight_xgb_class_1': 0.32896227049831467, 'weight_xgb_class_2': 0.5052010228340716, 'weight_cat_class_0': 0.051724449886373126, 'weight_cat_class_1': 0.8406003917358744, 'weight_cat_class_2': 0.5986199059918386}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:58,991] Trial 725 finished with value: 0.9492309889028118 and parameters: {'weight_lgbm_class_0': 0.12955625018182476, 'weight_lgbm_class_1': 0.8947523367714383, 'weight_lgbm_class_2': 0.6377070870171577, 'weight_xgb_class_0': 0.02806061486590573, 'weight_xgb_class_1': 0.33989557557321903, 'weight_xgb_class_2': 0.5479771548404258, 'weight_cat_class_0': 0.053680364468809486, 'weight_cat_class_1': 0.821219900944788, 'weight_cat_class_2': 0.6084102503457631}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  36%|████████████████████████████████████████████████▏                                                                                   | 730/2000 [00:23<00:46, 27.38it/s]

[I 2026-07-03 10:22:59,019] Trial 726 finished with value: 0.9495956568813476 and parameters: {'weight_lgbm_class_0': 0.11721285218993437, 'weight_lgbm_class_1': 0.8988801124186819, 'weight_lgbm_class_2': 0.6376401232583258, 'weight_xgb_class_0': 0.023376729614013544, 'weight_xgb_class_1': 0.08291286227432092, 'weight_xgb_class_2': 0.5457119510036399, 'weight_cat_class_0': 0.02126852554116711, 'weight_cat_class_1': 0.8374201313305609, 'weight_cat_class_2': 0.5223712831847381}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,020] Trial 724 finished with value: 0.949260362582267 and parameters: {'weight_lgbm_class_0': 0.12090188026671815, 'weight_lgbm_class_1': 0.900988242459737, 'weight_lgbm_class_2': 0.7243453669317168, 'weight_xgb_class_0': 0.03543596828690077, 'weight_xgb_class_1': 0.24264087333929674, 'weight_xgb_class_2': 0.5452498885205274, 'weight_cat_class_0': 0.050447319077887076, 'weight_cat_class_1': 0.8900193083593845, 'weight_cat_class_2': 0.556947780977537}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,044] Trial 727 finished with value: 0.9370233694259144 and parameters: {'weight_lgbm_class_0': 0.1235699465394586, 'weight_lgbm_class_1': 0.13569059558593255, 'weight_lgbm_class_2': 0.7197660337961511, 'weight_xgb_class_0': 0.029478475840768584, 'weight_xgb_class_1': 0.23956375846163505, 'weight_xgb_class_2': 0.5451804494203141, 'weight_cat_class_0': 0.05402405910110589, 'weight_cat_class_1': 0.08483477790006294, 'weight_cat_class_2': 0.522731286002503}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,072] Trial 729 finished with value: 0.9492879683814809 and parameters: {'weight_lgbm_class_0': 0.128964039977108, 'weight_lgbm_class_1': 0.8999483378400738, 'weight_lgbm_class_2': 0.6441671531625892, 'weight_xgb_class_0': 0.023070022623387816, 'weight_xgb_class_1': 0.30786857698076175, 'weight_xgb_class_2': 0.5497844509204488, 'weight_cat_class_0': 0.055123832109643875, 'weight_cat_class_1': 0.8827659482401923, 'weight_cat_class_2': 0.6071363659099387}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,091] Trial 728 finished with value: 0.9487547705115719 and parameters: {'weight_lgbm_class_0': 0.1282145482557387, 'weight_lgbm_class_1': 0.945744095322603, 'weight_lgbm_class_2': 0.6313681687667656, 'weight_xgb_class_0': 0.00017143816065074563, 'weight_xgb_class_1': 0.24206033014106265, 'weight_xgb_class_2': 0.5395686326839669, 'weight_cat_class_0': 0.054170856612322446, 'weight_cat_class_1': 0.07879503163751578, 'weight_cat_class_2': 0.600301069052553}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,113] Trial 730 finished with value: 0.9140212033946429 and parameters: {'weight_lgbm_class_0': 0.12621056049880028, 'weight_lgbm_class_1': 0.8944508484286441, 'weight_lgbm_class_2': 0.6358662967578316, 'weight_xgb_class_0': 0.0232212133685847, 'weight_xgb_class_1': 0.29322909870209535, 'weight_xgb_class_2': 0.545376493679306, 'weight_cat_class_0': 0.9286215853504811, 'weight_cat_class_1': 0.8948871652293356, 'weight_cat_class_2': 0.6087823307597249}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  37%|████████████████████████████████████████████████▌                                                                                   | 735/2000 [00:23<00:50, 25.15it/s]

[I 2026-07-03 10:22:59,236] Trial 731 finished with value: 0.9496795652837023 and parameters: {'weight_lgbm_class_0': 0.10380548161814858, 'weight_lgbm_class_1': 0.8278498952746316, 'weight_lgbm_class_2': 0.6210427683185256, 'weight_xgb_class_0': 0.02576358350724684, 'weight_xgb_class_1': 0.2524523767915385, 'weight_xgb_class_2': 0.5451667351200592, 'weight_cat_class_0': 0.024176773253810634, 'weight_cat_class_1': 0.8897935484625992, 'weight_cat_class_2': 0.6071135143991121}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,323] Trial 732 finished with value: 0.9493056610257935 and parameters: {'weight_lgbm_class_0': 0.10099756628224504, 'weight_lgbm_class_1': 0.2676376756388994, 'weight_lgbm_class_2': 0.7486956745662233, 'weight_xgb_class_0': 0.02393354785802282, 'weight_xgb_class_1': 0.25741628359163343, 'weight_xgb_class_2': 0.5088529228414522, 'weight_cat_class_0': 0.024620852153642216, 'weight_cat_class_1': 0.8952865517684833, 'weight_cat_class_2': 0.6120773582170489}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,352] Trial 733 finished with value: 0.9496724055416358 and parameters: {'weight_lgbm_class_0': 0.1003698715369361, 'weight_lgbm_class_1': 0.8940457773368652, 'weight_lgbm_class_2': 0.619936406888638, 'weight_xgb_class_0': 0.02261239803650663, 'weight_xgb_class_1': 0.31252731945600815, 'weight_xgb_class_2': 0.3932975335858352, 'weight_cat_class_0': 0.025596889529882066, 'weight_cat_class_1': 0.8938784101084675, 'weight_cat_class_2': 0.6017870418396137}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,376] Trial 735 finished with value: 0.9037187348130497 and parameters: {'weight_lgbm_class_0': 0.09706934056264664, 'weight_lgbm_class_1': 0.9447155404301535, 'weight_lgbm_class_2': 0.6200709398586395, 'weight_xgb_class_0': 0.9440774757231645, 'weight_xgb_class_1': 0.2505558233880679, 'weight_xgb_class_2': 0.08305749015444891, 'weight_cat_class_0': 0.02348784468995873, 'weight_cat_class_1': 0.8928713469325503, 'weight_cat_class_2': 0.6091878075666002}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,388] Trial 734 finished with value: 0.9497425223872846 and parameters: {'weight_lgbm_class_0': 0.09998633876381549, 'weight_lgbm_class_1': 0.8393937263931763, 'weight_lgbm_class_2': 0.6241018110174852, 'weight_xgb_class_0': 0.00043986277241588045, 'weight_xgb_class_1': 0.2505501437005388, 'weight_xgb_class_2': 0.5099006553511489, 'weight_cat_class_0': 0.023847372099653402, 'weight_cat_class_1': 0.8941958833213696, 'weight_cat_class_2': 0.6079069946948255}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  37%|█████████████████████████████████████████████████                                                                                   | 743/2000 [00:23<00:42, 29.31it/s]

[I 2026-07-03 10:22:59,468] Trial 736 finished with value: 0.949718442813535 and parameters: {'weight_lgbm_class_0': 0.097238346954241, 'weight_lgbm_class_1': 0.8404702412293803, 'weight_lgbm_class_2': 0.6188484614398079, 'weight_xgb_class_0': 0.01927929997395131, 'weight_xgb_class_1': 0.24565526317945147, 'weight_xgb_class_2': 0.5072710437606037, 'weight_cat_class_0': 0.023721937411409752, 'weight_cat_class_1': 0.8919091690312968, 'weight_cat_class_2': 0.5995951379586649}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,491] Trial 737 finished with value: 0.9497261523793049 and parameters: {'weight_lgbm_class_0': 0.09867632618541751, 'weight_lgbm_class_1': 0.8343123620399506, 'weight_lgbm_class_2': 0.6198776052053114, 'weight_xgb_class_0': 0.01885933881806997, 'weight_xgb_class_1': 0.24446582302397185, 'weight_xgb_class_2': 0.5060062978542259, 'weight_cat_class_0': 0.022924365046775037, 'weight_cat_class_1': 0.8899686196395139, 'weight_cat_class_2': 0.6117490195490779}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,530] Trial 738 finished with value: 0.9049919490320297 and parameters: {'weight_lgbm_class_0': 0.09590110129262855, 'weight_lgbm_class_1': 0.9468051163357715, 'weight_lgbm_class_2': 0.6217975035933128, 'weight_xgb_class_0': 0.9325958636152428, 'weight_xgb_class_1': 0.24058900616198298, 'weight_xgb_class_2': 0.5064640755436448, 'weight_cat_class_0': 0.021151582885374578, 'weight_cat_class_1': 0.2964592407515248, 'weight_cat_class_2': 0.6141620411911716}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,549] Trial 740 finished with value: 0.949579972235202 and parameters: {'weight_lgbm_class_0': 0.09294296522373137, 'weight_lgbm_class_1': 0.8303998639062907, 'weight_lgbm_class_2': 0.6175411884884964, 'weight_xgb_class_0': 0.0542713728764746, 'weight_xgb_class_1': 0.23842737683786142, 'weight_xgb_class_2': 0.5073940449348651, 'weight_cat_class_0': 0.02357524055717593, 'weight_cat_class_1': 0.8948581578807346, 'weight_cat_class_2': 0.6132621407797114}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,550] Trial 739 finished with value: 0.9497195854011347 and parameters: {'weight_lgbm_class_0': 0.09892312294594463, 'weight_lgbm_class_1': 0.8378563216175682, 'weight_lgbm_class_2': 0.6218219204291308, 'weight_xgb_class_0': 0.0019514816690946255, 'weight_xgb_class_1': 0.24166087185475293, 'weight_xgb_class_2': 0.5068010734222872, 'weight_cat_class_0': 0.023081772652465582, 'weight_cat_class_1': 0.8941389190169908, 'weight_cat_class_2': 0.6135227336411679}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,556] Trial 741 finished with value: 0.9496481620312266 and parameters: {'weight_lgbm_class_0': 0.09494563356742598, 'weight_lgbm_class_1': 0.8531951188136887, 'weight_lgbm_class_2': 0.6176068990004038, 'weight_xgb_class_0': 0.0005303003309615265, 'weight_xgb_class_1': 0.25539771984576615, 'weight_xgb_class_2': 0.5829229566483906, 'weight_cat_class_0': 0.02411527203675529, 'weight_cat_class_1': 0.8942982053941327, 'weight_cat_class_2': 0.6106318738060917}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,595] Trial 742 finished with value: 0.9496213623311277 and parameters: {'weight_lgbm_class_0': 0.09920417686748048, 'weight_lgbm_class_1': 0.2773228673504321, 'weight_lgbm_class_2': 0.6152306251774522, 'weight_xgb_class_0': 0.0009035990280616482, 'weight_xgb_class_1': 0.6242774091572812, 'weight_xgb_class_2': 0.5106593950732777, 'weight_cat_class_0': 0.02584796242682109, 'weight_cat_class_1': 0.8976177572741583, 'weight_cat_class_2': 0.6195632537679194}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  37%|█████████████████████████████████████████████████▎                                                                                  | 748/2000 [00:24<00:55, 22.57it/s]

[I 2026-07-03 10:22:59,730] Trial 743 finished with value: 0.9495045564548003 and parameters: {'weight_lgbm_class_0': 0.0981481544431043, 'weight_lgbm_class_1': 0.9445886516793564, 'weight_lgbm_class_2': 0.6187406940046047, 'weight_xgb_class_0': 0.0548833427310026, 'weight_xgb_class_1': 0.2553961611806363, 'weight_xgb_class_2': 0.5054554322664958, 'weight_cat_class_0': 0.022057363562364558, 'weight_cat_class_1': 0.8990044126082793, 'weight_cat_class_2': 0.5642988614580472}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,840] Trial 744 finished with value: 0.9495695369737134 and parameters: {'weight_lgbm_class_0': 0.09283060770123848, 'weight_lgbm_class_1': 0.9445022803332505, 'weight_lgbm_class_2': 0.6084005897780058, 'weight_xgb_class_0': 0.05470767749044318, 'weight_xgb_class_1': 0.2293612651321411, 'weight_xgb_class_2': 0.503754836896001, 'weight_cat_class_0': 0.024334545421987902, 'weight_cat_class_1': 0.9188374774733806, 'weight_cat_class_2': 0.6198202273768956}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,843] Trial 745 finished with value: 0.94967029178218 and parameters: {'weight_lgbm_class_0': 0.08468123756977725, 'weight_lgbm_class_1': 0.8456704240945276, 'weight_lgbm_class_2': 0.6619219546108726, 'weight_xgb_class_0': 0.0559711189510737, 'weight_xgb_class_1': 0.22533194456202602, 'weight_xgb_class_2': 0.5104197236594828, 'weight_cat_class_0': 0.020315644455388367, 'weight_cat_class_1': 0.9208040829392031, 'weight_cat_class_2': 0.5696352004971585}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,846] Trial 746 finished with value: 0.9496062068175103 and parameters: {'weight_lgbm_class_0': 0.09118361728380597, 'weight_lgbm_class_1': 0.8241859656876626, 'weight_lgbm_class_2': 0.6597300876136881, 'weight_xgb_class_0': 0.05549789223458319, 'weight_xgb_class_1': 0.08283510762085239, 'weight_xgb_class_2': 0.49212146568157605, 'weight_cat_class_0': 0.00011357754138691112, 'weight_cat_class_1': 0.7691808004090335, 'weight_cat_class_2': 0.6132706174380017}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,882] Trial 747 finished with value: 0.9496734577363712 and parameters: {'weight_lgbm_class_0': 0.08996974334046798, 'weight_lgbm_class_1': 0.8220738706275593, 'weight_lgbm_class_2': 0.6638810862457134, 'weight_xgb_class_0': 0.003638684747542774, 'weight_xgb_class_1': 0.2589407875143952, 'weight_xgb_class_2': 0.4954319840368993, 'weight_cat_class_0': 0.0234655588922024, 'weight_cat_class_1': 0.8786421228208613, 'weight_cat_class_2': 0.5699956950947952}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,939] Trial 748 finished with value: 0.9496917721029702 and parameters: {'weight_lgbm_class_0': 0.1414148130170403, 'weight_lgbm_class_1': 0.8268435106478907, 'weight_lgbm_class_2': 0.6518495783745523, 'weight_xgb_class_0': 0.002000512647814562, 'weight_xgb_class_1': 0.25720982906617623, 'weight_xgb_class_2': 0.492803158619701, 'weight_cat_class_0': 0.017581764842870495, 'weight_cat_class_1': 0.8686865033260646, 'weight_cat_class_2': 0.5719359039474142}. Best is trial 503 with value: 0.9497676925748403.

[I 2026-07-03 10:22:59,964] Trial 749 finished with value: 0.9497443132819984 and parameters: {'weight_lgbm_class_0': 0.1425151619685351, 'weight_lgbm_class_1': 0.8363690900410975, 'weight_lgbm_class_2': 0.6628806061994021, 'weight_xgb_class_0': 0.002691083889408575, 'weight_xgb_class_1': 0.25347606608662776, 'weight_xgb_class_2': 0.49057849106168216, 'weight_cat_class_0': 0.0005972528811038352, 'weight_cat_class_1': 0.8703444867556313, 'weight_cat_class_2': 0.5760498210354476}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:22:59,992] Trial 750 finished with value: 0.9497083115682393 and parameters: {'weight_lgbm_class_0': 0.14448835179681555, 'weight_lgbm_class_1': 0.8221015363436645, 'weight_lgbm_class_2': 0.6526638571966591, 'weight_xgb_class_0': 0.0029479348834014485, 'weight_xgb_class_1': 0.2565749207597165, 'weight_xgb_class_2': 0.4878030781687751, 'weight_cat_class_0': 0.0007265219184748684, 'weight_cat_class_1': 0.8175224081187459, 'weight_cat_class_2': 0.5672470591035135}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,024] Trial 752 finished with value: 0.9368590474731389 and parameters: {'weight_lgbm_class_0': 0.1439771121487416, 'weight_lgbm_class_1': 0.8463395604995863, 'weight_lgbm_class_2': 0.6519945210521554, 'weight_xgb_class_0': 0.002472458551431707, 'weight_xgb_class_1': 0.22871236378434112, 'weight_xgb_class_2': 0.4846285166097453, 'weight_cat_class_0': 0.446978444265023, 'weight_cat_class_1': 0.8168792782534261, 'weight_cat_class_2': 0.5719593769856212}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,024] Trial 751 finished with value: 0.9494993362220256 and parameters: {'weight_lgbm_class_0': 0.14226655203904331, 'weight_lgbm_class_1': 0.8409567496247772, 'weight_lgbm_class_2': 0.6745250736548967, 'weight_xgb_class_0': 0.001052128379867713, 'weight_xgb_class_1': 0.23433243517912997, 'weight_xgb_class_2': 0.49248448616335855, 'weight_cat_class_0': 0.032984035347571154, 'weight_cat_class_1': 0.8500747545696931, 'weight_cat_class_2': 0.5699177478095654}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,076] Trial 753 finished with value: 0.937350503534501 and parameters: {'weight_lgbm_class_0': 0.138938800389315, 'weight_lgbm_class_1': 0.8228899315381095, 'weight_lgbm_class_2': 0.6591909990381484, 'weight_xgb_class_0': 0.0013381521268807342, 'weight_xgb_class_1': 0.25530990052513175, 'weight_xgb_class_2': 0.4912644967084227, 'weight_cat_class_0': 0.44145216872952237, 'weight_cat_class_1': 0.8173481300395384, 'weight_cat_class_2': 0.571470540115446}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,089] Trial 754 finished with value: 0.949474803593752 and parameters: {'weight_lgbm_class_0': 0.13808451207228833, 'weight_lgbm_class_1': 0.8459006558330313, 'weight_lgbm_class_2': 0.6569007206803907, 'weight_xgb_class_0': 0.00021777693305694706, 'weight_xgb_class_1': 0.22883351960721793, 'weight_xgb_class_2': 0.4948135539815557, 'weight_cat_class_0': 0.0369284026427953, 'weight_cat_class_1': 0.851018012341517, 'weight_cat_class_2': 0.5973351443345344}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  38%|██████████████████████████████████████████████████                                                                                  | 759/2000 [00:24<00:54, 22.82it/s]

[I 2026-07-03 10:23:00,180] Trial 755 finished with value: 0.9497139203197454 and parameters: {'weight_lgbm_class_0': 0.14310964280514232, 'weight_lgbm_class_1': 0.8138589955035691, 'weight_lgbm_class_2': 0.6589466471651421, 'weight_xgb_class_0': 0.004574600768766254, 'weight_xgb_class_1': 0.2280507041179035, 'weight_xgb_class_2': 0.4884169001792062, 'weight_cat_class_0': 0.00030253820141366806, 'weight_cat_class_1': 0.8482361458845322, 'weight_cat_class_2': 0.5710757178638016}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,289] Trial 756 finished with value: 0.9494661411443485 and parameters: {'weight_lgbm_class_0': 0.14354780630194275, 'weight_lgbm_class_1': 0.8167054680211966, 'weight_lgbm_class_2': 0.6739564934993795, 'weight_xgb_class_0': 0.0022254241503507043, 'weight_xgb_class_1': 0.2288283441492197, 'weight_xgb_class_2': 0.48843564034330406, 'weight_cat_class_0': 0.03741396465588008, 'weight_cat_class_1': 0.8507535740278773, 'weight_cat_class_2': 0.5765244550236538}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,337] Trial 757 finished with value: 0.9494012073459634 and parameters: {'weight_lgbm_class_0': 0.14273137809217218, 'weight_lgbm_class_1': 0.83939117408903, 'weight_lgbm_class_2': 0.6459665876197831, 'weight_xgb_class_0': 0.0012050916444745863, 'weight_xgb_class_1': 0.2319344109996665, 'weight_xgb_class_2': 0.48802000697522047, 'weight_cat_class_0': 0.04066844332878628, 'weight_cat_class_1': 0.8212030173534182, 'weight_cat_class_2': 0.5812322993321211}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,351] Trial 758 finished with value: 0.9497299501332428 and parameters: {'weight_lgbm_class_0': 0.11402243154116486, 'weight_lgbm_class_1': 0.8375875334549462, 'weight_lgbm_class_2': 0.6485595033838604, 'weight_xgb_class_0': 0.0010835875586645625, 'weight_xgb_class_1': 0.23330128687010535, 'weight_xgb_class_2': 0.4816820995889674, 'weight_cat_class_0': 0.04041119578372796, 'weight_cat_class_1': 0.8466977638344493, 'weight_cat_class_2': 0.5821891236768213}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,362] Trial 759 finished with value: 0.9492781917767835 and parameters: {'weight_lgbm_class_0': 0.13882794149244188, 'weight_lgbm_class_1': 0.8148867389742067, 'weight_lgbm_class_2': 0.6480550465202316, 'weight_xgb_class_0': 0.018712099775087247, 'weight_xgb_class_1': 0.22268479902503963, 'weight_xgb_class_2': 0.44960704600503654, 'weight_cat_class_0': 0.03818797485156887, 'weight_cat_class_1': 0.8228529711809613, 'weight_cat_class_2': 0.5858775555906125}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  38%|██████████████████████████████████████████████████▌                                                                                 | 766/2000 [00:24<00:49, 24.93it/s]

[I 2026-07-03 10:23:00,385] Trial 760 finished with value: 0.9493212649212762 and parameters: {'weight_lgbm_class_0': 0.13825935893286595, 'weight_lgbm_class_1': 0.8380144219766839, 'weight_lgbm_class_2': 0.6458412116830572, 'weight_xgb_class_0': 0.014726707636532868, 'weight_xgb_class_1': 0.23455523051725452, 'weight_xgb_class_2': 0.4908556513137823, 'weight_cat_class_0': 0.03617365526276807, 'weight_cat_class_1': 0.8143274854656504, 'weight_cat_class_2': 0.5874781246626315}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,451] Trial 761 finished with value: 0.9497324792887542 and parameters: {'weight_lgbm_class_0': 0.14418938569995074, 'weight_lgbm_class_1': 0.8078562830512004, 'weight_lgbm_class_2': 0.681156140085682, 'weight_xgb_class_0': 0.0003471219454478009, 'weight_xgb_class_1': 0.23663662001009853, 'weight_xgb_class_2': 0.4717694979871169, 'weight_cat_class_0': 0.0011316053539948759, 'weight_cat_class_1': 0.8330943790577394, 'weight_cat_class_2': 0.5821129115592121}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,491] Trial 762 finished with value: 0.9487392019556463 and parameters: {'weight_lgbm_class_0': 0.19626481454409028, 'weight_lgbm_class_1': 0.8388334415000035, 'weight_lgbm_class_2': 0.6526561493523816, 'weight_xgb_class_0': 0.0012218187459707383, 'weight_xgb_class_1': 0.23334325630521813, 'weight_xgb_class_2': 0.46320717981622156, 'weight_cat_class_0': 0.03957735140385719, 'weight_cat_class_1': 0.7726360107352065, 'weight_cat_class_2': 0.5849112660431638}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,493] Trial 763 finished with value: 0.9457092094552673 and parameters: {'weight_lgbm_class_0': 0.15066714300362297, 'weight_lgbm_class_1': 0.8175768460896167, 'weight_lgbm_class_2': 0.6465034984539076, 'weight_xgb_class_0': 0.0005933887000523427, 'weight_xgb_class_1': 0.22684780426216739, 'weight_xgb_class_2': 0.4431080505326272, 'weight_cat_class_0': 0.20636205261243723, 'weight_cat_class_1': 0.7965035486647755, 'weight_cat_class_2': 0.5885612449825848}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,501] Trial 764 finished with value: 0.9491487834129734 and parameters: {'weight_lgbm_class_0': 0.19798900233943756, 'weight_lgbm_class_1': 0.8201207912077282, 'weight_lgbm_class_2': 0.6871784260433583, 'weight_xgb_class_0': 0.01354318780941623, 'weight_xgb_class_1': 0.22420470823861072, 'weight_xgb_class_2': 0.44814374597949197, 'weight_cat_class_0': 0.0007032207416573875, 'weight_cat_class_1': 0.7803451202629379, 'weight_cat_class_2': 0.5806372606485992}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,540] Trial 765 finished with value: 0.9493501042767086 and parameters: {'weight_lgbm_class_0': 0.15844609509003307, 'weight_lgbm_class_1': 0.8130390764156435, 'weight_lgbm_class_2': 0.6818905450645694, 'weight_xgb_class_0': 0.020907251527496343, 'weight_xgb_class_1': 0.2870758170613381, 'weight_xgb_class_2': 0.44110597809596114, 'weight_cat_class_0': 0.000682581315764888, 'weight_cat_class_1': 0.8042558578376908, 'weight_cat_class_2': 0.48603599940796804}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,563] Trial 766 finished with value: 0.9490624442202936 and parameters: {'weight_lgbm_class_0': 0.19409926987020998, 'weight_lgbm_class_1': 0.8259550608452505, 'weight_lgbm_class_2': 0.6786745976699475, 'weight_xgb_class_0': 0.019066227091610297, 'weight_xgb_class_1': 0.2697246117473891, 'weight_xgb_class_2': 0.498230336711354, 'weight_cat_class_0': 0.0009885781091079349, 'weight_cat_class_1': 0.8403852261680347, 'weight_cat_class_2': 0.4915023317130872}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  38%|██████████████████████████████████████████████████▊                                                                                 | 770/2000 [00:25<00:47, 26.00it/s]

[I 2026-07-03 10:23:00,672] Trial 767 finished with value: 0.9490981882349153 and parameters: {'weight_lgbm_class_0': 0.18846677189509853, 'weight_lgbm_class_1': 0.8261318588328217, 'weight_lgbm_class_2': 0.6845922558991742, 'weight_xgb_class_0': 0.017517312744313063, 'weight_xgb_class_1': 0.2615982605511169, 'weight_xgb_class_2': 0.44056833334779566, 'weight_cat_class_0': 0.0022767955515014147, 'weight_cat_class_1': 0.798404384143219, 'weight_cat_class_2': 0.5015309996890376}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,764] Trial 768 finished with value: 0.9486867088875602 and parameters: {'weight_lgbm_class_0': 0.2114659655548891, 'weight_lgbm_class_1': 0.8128394382876786, 'weight_lgbm_class_2': 0.6902711583449099, 'weight_xgb_class_0': 0.02447086308255482, 'weight_xgb_class_1': 0.22241574461074815, 'weight_xgb_class_2': 0.43006496123609395, 'weight_cat_class_0': 0.003896557448858983, 'weight_cat_class_1': 0.8124957999211558, 'weight_cat_class_2': 0.5578725074048645}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,803] Trial 769 finished with value: 0.9484236955583388 and parameters: {'weight_lgbm_class_0': 0.16607180342139508, 'weight_lgbm_class_1': 0.8120248793692462, 'weight_lgbm_class_2': 0.6825265886070717, 'weight_xgb_class_0': 0.020158981486546303, 'weight_xgb_class_1': 0.21917454555028865, 'weight_xgb_class_2': 0.42634285364305646, 'weight_cat_class_0': 0.06290961754412126, 'weight_cat_class_1': 0.8086823021167489, 'weight_cat_class_2': 0.5183802265352563}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,847] Trial 771 finished with value: 0.9483899047510894 and parameters: {'weight_lgbm_class_0': 0.1813672812519596, 'weight_lgbm_class_1': 0.786030135989555, 'weight_lgbm_class_2': 0.6924441644433005, 'weight_xgb_class_0': 0.014955833215029028, 'weight_xgb_class_1': 0.2608640526584539, 'weight_xgb_class_2': 0.445534212653966, 'weight_cat_class_0': 0.0593269690833534, 'weight_cat_class_1': 0.8049190546125067, 'weight_cat_class_2': 0.5225176053688867}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  39%|███████████████████████████████████████████████████▎                                                                                | 778/2000 [00:25<00:49, 24.88it/s]

[I 2026-07-03 10:23:00,852] Trial 772 finished with value: 0.949720338765854 and parameters: {'weight_lgbm_class_0': 0.1203828745519217, 'weight_lgbm_class_1': 0.7966080796944135, 'weight_lgbm_class_2': 0.6831378595289708, 'weight_xgb_class_0': 0.013780686722256292, 'weight_xgb_class_1': 0.21853592861359789, 'weight_xgb_class_2': 0.43611335056740874, 'weight_cat_class_0': 0.0011495082647271608, 'weight_cat_class_1': 0.7953133588748725, 'weight_cat_class_2': 0.5329101742386002}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,866] Trial 770 finished with value: 0.9484217622969672 and parameters: {'weight_lgbm_class_0': 0.2359047848130344, 'weight_lgbm_class_1': 0.8320242076555543, 'weight_lgbm_class_2': 0.6775719370800525, 'weight_xgb_class_0': 0.015995662409047897, 'weight_xgb_class_1': 0.22161314151710762, 'weight_xgb_class_2': 0.45057147788037044, 'weight_cat_class_0': 2.4397709158942293e-05, 'weight_cat_class_1': 0.7811240412718344, 'weight_cat_class_2': 0.5174580574403637}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,939] Trial 773 finished with value: 0.9494850362393944 and parameters: {'weight_lgbm_class_0': 0.17135892980490341, 'weight_lgbm_class_1': 0.7860221874230712, 'weight_lgbm_class_2': 0.6824087445777722, 'weight_xgb_class_0': 0.0008234903049179693, 'weight_xgb_class_1': 0.24820807279421403, 'weight_xgb_class_2': 0.4431069845184966, 'weight_cat_class_0': 0.0009669924794055498, 'weight_cat_class_1': 0.8020795306684635, 'weight_cat_class_2': 0.5220151456186107}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,984] Trial 774 finished with value: 0.9482528300416332 and parameters: {'weight_lgbm_class_0': 0.18461055964194054, 'weight_lgbm_class_1': 0.7871106723237283, 'weight_lgbm_class_2': 0.6804441047973934, 'weight_xgb_class_0': 0.018856580439056463, 'weight_xgb_class_1': 0.25006744009001775, 'weight_xgb_class_2': 0.4294012232661991, 'weight_cat_class_0': 0.06128729076443991, 'weight_cat_class_1': 0.8506396819815776, 'weight_cat_class_2': 0.5608372407025454}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,993] Trial 775 finished with value: 0.9486152241531284 and parameters: {'weight_lgbm_class_0': 0.16038060218134936, 'weight_lgbm_class_1': 0.7950614045790162, 'weight_lgbm_class_2': 0.735897313947621, 'weight_xgb_class_0': 0.02044009198886015, 'weight_xgb_class_1': 0.2570808817931403, 'weight_xgb_class_2': 0.44903614819916543, 'weight_cat_class_0': 0.062468792298328454, 'weight_cat_class_1': 0.7935349123801293, 'weight_cat_class_2': 0.53115541346015}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:00,994] Trial 776 finished with value: 0.94790639050875 and parameters: {'weight_lgbm_class_0': 0.18910515926282978, 'weight_lgbm_class_1': 0.7936154280706476, 'weight_lgbm_class_2': 0.6931294411801072, 'weight_xgb_class_0': 0.02560082814351939, 'weight_xgb_class_1': 0.2655650132544499, 'weight_xgb_class_2': 0.42524142502736395, 'weight_cat_class_0': 0.061439255065528636, 'weight_cat_class_1': 0.8008328686381508, 'weight_cat_class_2': 0.5058650365314503}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,012] Trial 778 finished with value: 0.9483919090968503 and parameters: {'weight_lgbm_class_0': 0.17075153346827857, 'weight_lgbm_class_1': 0.7873854701551638, 'weight_lgbm_class_2': 0.7024319013778524, 'weight_xgb_class_0': 0.02067408059944354, 'weight_xgb_class_1': 0.2536977879340994, 'weight_xgb_class_2': 0.43556702124141755, 'weight_cat_class_0': 0.06562342583904117, 'weight_cat_class_1': 0.8050524158535913, 'weight_cat_class_2': 0.5551629618890553}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,051] Trial 777 finished with value: 0.94857361086601 and parameters: {'weight_lgbm_class_0': 0.1703192233638573, 'weight_lgbm_class_1': 0.7938530401310387, 'weight_lgbm_class_2': 0.7290241672181916, 'weight_xgb_class_0': 0.02083071458114163, 'weight_xgb_class_1': 0.24903979258586598, 'weight_xgb_class_2': 0.47118198736316963, 'weight_cat_class_0': 0.05892675571718386, 'weight_cat_class_1': 0.797784449550379, 'weight_cat_class_2': 0.5453602134437321}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  39%|███████████████████████████████████████████████████▋                                                                                | 783/2000 [00:25<00:52, 23.30it/s]

[I 2026-07-03 10:23:01,154] Trial 779 finished with value: 0.9486178076800685 and parameters: {'weight_lgbm_class_0': 0.16740833702114574, 'weight_lgbm_class_1': 0.7912616034441651, 'weight_lgbm_class_2': 0.723226123017355, 'weight_xgb_class_0': 0.021010262585057657, 'weight_xgb_class_1': 0.24306613591069914, 'weight_xgb_class_2': 0.4743356076689786, 'weight_cat_class_0': 0.059640971475305796, 'weight_cat_class_1': 0.8240285079284607, 'weight_cat_class_2': 0.5317786458143587}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,251] Trial 780 finished with value: 0.9484738681006274 and parameters: {'weight_lgbm_class_0': 0.17138791518425406, 'weight_lgbm_class_1': 0.7927152313509862, 'weight_lgbm_class_2': 0.7134198711404511, 'weight_xgb_class_0': 0.017635132112046592, 'weight_xgb_class_1': 0.24885231615815626, 'weight_xgb_class_2': 0.46458649051190054, 'weight_cat_class_0': 0.06465439823750829, 'weight_cat_class_1': 0.7964735187218491, 'weight_cat_class_2': 0.5246203982427139}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,278] Trial 781 finished with value: 0.9490619517544404 and parameters: {'weight_lgbm_class_0': 0.16370284431188475, 'weight_lgbm_class_1': 0.7762193086249057, 'weight_lgbm_class_2': 0.7126723787485211, 'weight_xgb_class_0': 0.001491036791225614, 'weight_xgb_class_1': 0.25105502891645054, 'weight_xgb_class_2': 0.46086794472669984, 'weight_cat_class_0': 0.05306007558209508, 'weight_cat_class_1': 0.8291661424298461, 'weight_cat_class_2': 0.5531293023639849}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,329] Trial 783 finished with value: 0.9486738824888427 and parameters: {'weight_lgbm_class_0': 0.1789385537285308, 'weight_lgbm_class_1': 0.7867833869924029, 'weight_lgbm_class_2': 0.7021955970383746, 'weight_xgb_class_0': 0.0009143552230488979, 'weight_xgb_class_1': 0.25601049200141396, 'weight_xgb_class_2': 0.465657017375996, 'weight_cat_class_0': 0.05866660457461072, 'weight_cat_class_1': 0.7839647267055228, 'weight_cat_class_2': 0.5450913369080163}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,332] Trial 782 finished with value: 0.9489612018367919 and parameters: {'weight_lgbm_class_0': 0.16226716168095745, 'weight_lgbm_class_1': 0.8513670704992264, 'weight_lgbm_class_2': 0.7210320201242526, 'weight_xgb_class_0': 0.0015651308864979147, 'weight_xgb_class_1': 0.2501158624655008, 'weight_xgb_class_2': 0.46683917835566285, 'weight_cat_class_0': 0.06052737186356755, 'weight_cat_class_1': 0.7551497066200795, 'weight_cat_class_2': 0.5381696144547712}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  40%|████████████████████████████████████████████████████▏                                                                               | 791/2000 [00:25<00:42, 28.65it/s]

[I 2026-07-03 10:23:01,375] Trial 784 finished with value: 0.9485732973022332 and parameters: {'weight_lgbm_class_0': 0.17004144779768246, 'weight_lgbm_class_1': 0.7873629638765967, 'weight_lgbm_class_2': 0.7583699310762727, 'weight_xgb_class_0': 0.019991454713797072, 'weight_xgb_class_1': 0.2473729490003044, 'weight_xgb_class_2': 0.4762526530234463, 'weight_cat_class_0': 0.058254400684604184, 'weight_cat_class_1': 0.7769232353674511, 'weight_cat_class_2': 0.5439245058773473}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,418] Trial 785 finished with value: 0.9486932090553797 and parameters: {'weight_lgbm_class_0': 0.16037349602821704, 'weight_lgbm_class_1': 0.8041394179246181, 'weight_lgbm_class_2': 0.7117488744499472, 'weight_xgb_class_0': 0.018785191827486128, 'weight_xgb_class_1': 0.24822551276077293, 'weight_xgb_class_2': 0.4623503887853409, 'weight_cat_class_0': 0.06089889745537723, 'weight_cat_class_1': 0.7856330741992545, 'weight_cat_class_2': 0.543685423892442}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,457] Trial 787 finished with value: 0.9495413781587816 and parameters: {'weight_lgbm_class_0': 0.13025203836788246, 'weight_lgbm_class_1': 0.8514501033477926, 'weight_lgbm_class_2': 0.7237843783887378, 'weight_xgb_class_0': 0.003448927707492919, 'weight_xgb_class_1': 0.21273712446460613, 'weight_xgb_class_2': 0.47092949325816913, 'weight_cat_class_0': 0.03724128651122986, 'weight_cat_class_1': 0.8252341363591901, 'weight_cat_class_2': 0.5417049521970765}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,479] Trial 786 finished with value: 0.9495700880517223 and parameters: {'weight_lgbm_class_0': 0.13240668028232358, 'weight_lgbm_class_1': 0.8531317355557367, 'weight_lgbm_class_2': 0.7334572259029221, 'weight_xgb_class_0': 0.0023048998981676384, 'weight_xgb_class_1': 0.2868549808840131, 'weight_xgb_class_2': 0.4644826882730449, 'weight_cat_class_0': 0.037108327852605316, 'weight_cat_class_1': 0.8243912653463886, 'weight_cat_class_2': 0.5400546190103901}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,494] Trial 788 finished with value: 0.9491404435276355 and parameters: {'weight_lgbm_class_0': 0.15704869562754897, 'weight_lgbm_class_1': 0.8554866000077445, 'weight_lgbm_class_2': 0.712442772481043, 'weight_xgb_class_0': 0.018719658937076094, 'weight_xgb_class_1': 0.21617489557777683, 'weight_xgb_class_2': 0.4867915478351909, 'weight_cat_class_0': 0.03778974827361187, 'weight_cat_class_1': 0.7609595578273001, 'weight_cat_class_2': 0.5431622811989542}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,526] Trial 789 finished with value: 0.9495478690179221 and parameters: {'weight_lgbm_class_0': 0.13185329412882074, 'weight_lgbm_class_1': 0.8547916028421625, 'weight_lgbm_class_2': 0.711661467891352, 'weight_xgb_class_0': 0.0011389166084426541, 'weight_xgb_class_1': 0.30289679884455584, 'weight_xgb_class_2': 0.47354115899070215, 'weight_cat_class_0': 0.0382735983840357, 'weight_cat_class_1': 0.7549999229631372, 'weight_cat_class_2': 0.540000368405288}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,536] Trial 790 finished with value: 0.9495150401356209 and parameters: {'weight_lgbm_class_0': 0.12554449044980512, 'weight_lgbm_class_1': 0.8566016595425074, 'weight_lgbm_class_2': 0.6675835728689048, 'weight_xgb_class_0': 0.0008541630853967173, 'weight_xgb_class_1': 0.21516847837369338, 'weight_xgb_class_2': 0.4704901103224259, 'weight_cat_class_0': 0.043318416216993505, 'weight_cat_class_1': 0.8252610376188804, 'weight_cat_class_2': 0.5489128432817787}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  40%|████████████████████████████████████████████████████▌                                                                               | 796/2000 [00:26<00:52, 22.75it/s]

[I 2026-07-03 10:23:01,664] Trial 791 finished with value: 0.9484057265723987 and parameters: {'weight_lgbm_class_0': 0.2209480630071167, 'weight_lgbm_class_1': 0.8520708312713056, 'weight_lgbm_class_2': 0.6663372035038119, 'weight_xgb_class_0': 0.0030151276605575213, 'weight_xgb_class_1': 0.2168050956879822, 'weight_xgb_class_2': 0.47667337674934857, 'weight_cat_class_0': 0.030631762302428256, 'weight_cat_class_1': 0.7626079060416019, 'weight_cat_class_2': 0.556342281705993}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,727] Trial 792 finished with value: 0.9495652439730943 and parameters: {'weight_lgbm_class_0': 0.13152901596715297, 'weight_lgbm_class_1': 0.8543648832275946, 'weight_lgbm_class_2': 0.6636903536728582, 'weight_xgb_class_0': 0.0006032197206852054, 'weight_xgb_class_1': 0.21304391995470043, 'weight_xgb_class_2': 0.4768057309504075, 'weight_cat_class_0': 0.03409275122342987, 'weight_cat_class_1': 0.829038865547788, 'weight_cat_class_2': 0.5615188241544682}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,735] Trial 793 finished with value: 0.9494993981005327 and parameters: {'weight_lgbm_class_0': 0.14234144913884547, 'weight_lgbm_class_1': 0.8530841697405142, 'weight_lgbm_class_2': 0.6681086202177997, 'weight_xgb_class_0': 0.003333428385313518, 'weight_xgb_class_1': 0.29256048513301686, 'weight_xgb_class_2': 0.4764097711999504, 'weight_cat_class_0': 0.03403288235947804, 'weight_cat_class_1': 0.7637810790602872, 'weight_cat_class_2': 0.5637633126803484}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,810] Trial 795 finished with value: 0.9493465379613637 and parameters: {'weight_lgbm_class_0': 0.1324707632883473, 'weight_lgbm_class_1': 0.8473544722116844, 'weight_lgbm_class_2': 0.6583982227621846, 'weight_xgb_class_0': 0.026161480258679554, 'weight_xgb_class_1': 0.2151743275331546, 'weight_xgb_class_2': 0.4825307081950088, 'weight_cat_class_0': 0.02910314787819889, 'weight_cat_class_1': 0.8294564447264526, 'weight_cat_class_2': 0.5693202411026245}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,810] Trial 794 finished with value: 0.9493290572290097 and parameters: {'weight_lgbm_class_0': 0.12720300858651132, 'weight_lgbm_class_1': 0.8422732366165784, 'weight_lgbm_class_2': 0.6665240132211132, 'weight_xgb_class_0': 0.027019039610975584, 'weight_xgb_class_1': 0.21031965023337487, 'weight_xgb_class_2': 0.40798847482603784, 'weight_cat_class_0': 0.03297326535992255, 'weight_cat_class_1': 0.8304257891386853, 'weight_cat_class_2': 0.5684510557938719}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,866] Trial 796 finished with value: 0.9492547753727685 and parameters: {'weight_lgbm_class_0': 0.12815519574707732, 'weight_lgbm_class_1': 0.8370518801020688, 'weight_lgbm_class_2': 0.666459059691889, 'weight_xgb_class_0': 0.03074116197789676, 'weight_xgb_class_1': 0.21025604856293545, 'weight_xgb_class_2': 0.4856792739886032, 'weight_cat_class_0': 0.03360132836309375, 'weight_cat_class_1': 0.758678041715132, 'weight_cat_class_2': 0.5653325505347371}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  40%|████████████████████████████████████████████████████▉                                                                               | 803/2000 [00:26<00:43, 27.47it/s]

[I 2026-07-03 10:23:01,896] Trial 797 finished with value: 0.949452695405086 and parameters: {'weight_lgbm_class_0': 0.12964663364268944, 'weight_lgbm_class_1': 0.8567187615864577, 'weight_lgbm_class_2': 0.6670471989369628, 'weight_xgb_class_0': 0.0025840942377106223, 'weight_xgb_class_1': 0.21510424009035797, 'weight_xgb_class_2': 0.39984481434428365, 'weight_cat_class_0': 0.03340622555903625, 'weight_cat_class_1': 0.8239946552755791, 'weight_cat_class_2': 0.4584929312052115}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,922] Trial 798 finished with value: 0.9494164285468824 and parameters: {'weight_lgbm_class_0': 0.12506460114388326, 'weight_lgbm_class_1': 0.828638470753295, 'weight_lgbm_class_2': 0.6442776355458534, 'weight_xgb_class_0': 0.02870407592889038, 'weight_xgb_class_1': 0.29941214152510687, 'weight_xgb_class_2': 0.4852579516214382, 'weight_cat_class_0': 0.026534433901730867, 'weight_cat_class_1': 0.8383919004478637, 'weight_cat_class_2': 0.5751444114395783}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,947] Trial 799 finished with value: 0.949748858749235 and parameters: {'weight_lgbm_class_0': 0.12039522628562366, 'weight_lgbm_class_1': 0.8266411952549424, 'weight_lgbm_class_2': 0.6665669078729421, 'weight_xgb_class_0': 0.0013483124962303489, 'weight_xgb_class_1': 0.29951416437526945, 'weight_xgb_class_2': 0.4835384720117867, 'weight_cat_class_0': 0.024885121266199385, 'weight_cat_class_1': 0.8381175963953537, 'weight_cat_class_2': 0.5636121251585783}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:01,986] Trial 800 finished with value: 0.9497140677210439 and parameters: {'weight_lgbm_class_0': 0.12202979485481967, 'weight_lgbm_class_1': 0.8351566367860968, 'weight_lgbm_class_2': 0.6399698676170594, 'weight_xgb_class_0': 5.931967567370791e-05, 'weight_xgb_class_1': 0.2948952894232186, 'weight_xgb_class_2': 0.4818518926532532, 'weight_cat_class_0': 0.018376057438161817, 'weight_cat_class_1': 0.8343965940685294, 'weight_cat_class_2': 0.5657321307847772}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,009] Trial 802 finished with value: 0.9495557999940297 and parameters: {'weight_lgbm_class_0': 0.11553667585341879, 'weight_lgbm_class_1': 0.8224399577054206, 'weight_lgbm_class_2': 0.6404673658329054, 'weight_xgb_class_0': 0.03302759389189763, 'weight_xgb_class_1': 0.27265610779462474, 'weight_xgb_class_2': 0.48841977773211115, 'weight_cat_class_0': 0.018291762502083184, 'weight_cat_class_1': 0.8418418613174866, 'weight_cat_class_2': 0.5641026536180012}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,025] Trial 801 finished with value: 0.9482424554328056 and parameters: {'weight_lgbm_class_0': 0.21226981605690137, 'weight_lgbm_class_1': 0.8339642905513691, 'weight_lgbm_class_2': 0.6384451935940599, 'weight_xgb_class_0': 0.03412877799104612, 'weight_xgb_class_1': 0.27240796291383934, 'weight_xgb_class_2': 0.48534176169756565, 'weight_cat_class_0': 0.021410856731539373, 'weight_cat_class_1': 0.8338569219132863, 'weight_cat_class_2': 0.5660371706887083}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  40%|█████████████████████████████████████████████████████▎                                                                              | 807/2000 [00:26<00:54, 21.77it/s]

[I 2026-07-03 10:23:02,141] Trial 803 finished with value: 0.9495015091409317 and parameters: {'weight_lgbm_class_0': 0.11471743887450545, 'weight_lgbm_class_1': 0.8304191005288089, 'weight_lgbm_class_2': 0.6363403772595573, 'weight_xgb_class_0': 0.03750658688146485, 'weight_xgb_class_1': 0.2849668615955345, 'weight_xgb_class_2': 0.4884082615042925, 'weight_cat_class_0': 0.019590143669668266, 'weight_cat_class_1': 0.8397183174770471, 'weight_cat_class_2': 0.5723107697892416}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,181] Trial 804 finished with value: 0.9495009328844023 and parameters: {'weight_lgbm_class_0': 0.11173987140524308, 'weight_lgbm_class_1': 0.832643637866475, 'weight_lgbm_class_2': 0.6429477278610591, 'weight_xgb_class_0': 0.040752283507356636, 'weight_xgb_class_1': 0.27659739274416106, 'weight_xgb_class_2': 0.4077696754735056, 'weight_cat_class_0': 0.018128306400961, 'weight_cat_class_1': 0.83966936958006, 'weight_cat_class_2': 0.5895178064663209}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,238] Trial 805 finished with value: 0.9496137464940585 and parameters: {'weight_lgbm_class_0': 0.11659547752119506, 'weight_lgbm_class_1': 0.8244662062363468, 'weight_lgbm_class_2': 0.6408011403095805, 'weight_xgb_class_0': 0.03342836579870214, 'weight_xgb_class_1': 0.2839830948308163, 'weight_xgb_class_2': 0.5021810490276625, 'weight_cat_class_0': 0.016738697408183394, 'weight_cat_class_1': 0.8419674728622388, 'weight_cat_class_2': 0.5879458323980743}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,329] Trial 808 finished with value: 0.9495238863161483 and parameters: {'weight_lgbm_class_0': 0.11524282428534245, 'weight_lgbm_class_1': 0.8121400062169037, 'weight_lgbm_class_2': 0.641955392091655, 'weight_xgb_class_0': 0.03252400115812441, 'weight_xgb_class_1': 0.27522045293834185, 'weight_xgb_class_2': 0.5064312586957099, 'weight_cat_class_0': 0.01742883848401844, 'weight_cat_class_1': 0.8442493490906523, 'weight_cat_class_2': 0.4742316663557208}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,334] Trial 806 finished with value: 0.9495912183143423 and parameters: {'weight_lgbm_class_0': 0.10910910719379281, 'weight_lgbm_class_1': 0.8189934421970313, 'weight_lgbm_class_2': 0.6361993338995725, 'weight_xgb_class_0': 0.03619260620389773, 'weight_xgb_class_1': 0.23353110233462473, 'weight_xgb_class_2': 0.5088559813262746, 'weight_cat_class_0': 0.01985677789990847, 'weight_cat_class_1': 0.8623121381488589, 'weight_cat_class_2': 0.5854029017199477}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  41%|█████████████████████████████████████████████████████▋                                                                              | 814/2000 [00:26<00:48, 24.50it/s]

[I 2026-07-03 10:23:02,334] Trial 807 finished with value: 0.9496136318811556 and parameters: {'weight_lgbm_class_0': 0.11314987033490484, 'weight_lgbm_class_1': 0.8250075902878806, 'weight_lgbm_class_2': 0.6359857084966486, 'weight_xgb_class_0': 0.03554524033213026, 'weight_xgb_class_1': 0.2787916620607505, 'weight_xgb_class_2': 0.5107693999893685, 'weight_cat_class_0': 0.017373000734837007, 'weight_cat_class_1': 0.8447829790364308, 'weight_cat_class_2': 0.5841478037412029}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,376] Trial 809 finished with value: 0.9493556441899244 and parameters: {'weight_lgbm_class_0': 0.1092229198208873, 'weight_lgbm_class_1': 0.8151931348540592, 'weight_lgbm_class_2': 0.6376678285379485, 'weight_xgb_class_0': 0.040684972398826125, 'weight_xgb_class_1': 0.2765010845451546, 'weight_xgb_class_2': 0.145262409178529, 'weight_cat_class_0': 0.016545484845007903, 'weight_cat_class_1': 0.8458571807583817, 'weight_cat_class_2': 0.5865852531526183}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,433] Trial 810 finished with value: 0.9496582920376443 and parameters: {'weight_lgbm_class_0': 0.10754625010798989, 'weight_lgbm_class_1': 0.8119252533198661, 'weight_lgbm_class_2': 0.6432623542649467, 'weight_xgb_class_0': 0.038298331225480535, 'weight_xgb_class_1': 0.2719376567888587, 'weight_xgb_class_2': 0.5087171965325561, 'weight_cat_class_0': 0.017980669012908502, 'weight_cat_class_1': 0.8442588345033217, 'weight_cat_class_2': 0.5945274281977172}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,457] Trial 811 finished with value: 0.9342896863175861 and parameters: {'weight_lgbm_class_0': 0.11514073403318245, 'weight_lgbm_class_1': 0.8387631844050586, 'weight_lgbm_class_2': 0.6356224414125523, 'weight_xgb_class_0': 0.04260485074963737, 'weight_xgb_class_1': 0.3198475218391527, 'weight_xgb_class_2': 0.506000370804489, 'weight_cat_class_0': 0.5031399694206184, 'weight_cat_class_1': 0.8469013689916883, 'weight_cat_class_2': 0.5916481065452598}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,479] Trial 812 finished with value: 0.9491105925736175 and parameters: {'weight_lgbm_class_0': 0.11553477564236977, 'weight_lgbm_class_1': 0.8321191561389872, 'weight_lgbm_class_2': 0.6331039437505549, 'weight_xgb_class_0': 0.025059924816790525, 'weight_xgb_class_1': 0.3245667988113154, 'weight_xgb_class_2': 0.5044441808318637, 'weight_cat_class_0': 0.08138591849120512, 'weight_cat_class_1': 0.8427790664197584, 'weight_cat_class_2': 0.5897278340191096}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,481] Trial 813 finished with value: 0.9490543066834373 and parameters: {'weight_lgbm_class_0': 0.10776988724555168, 'weight_lgbm_class_1': 0.8106312911984541, 'weight_lgbm_class_2': 0.6364452133525422, 'weight_xgb_class_0': 0.03929395251519153, 'weight_xgb_class_1': 0.3214113306832579, 'weight_xgb_class_2': 0.509441173810594, 'weight_cat_class_0': 0.07987094917494794, 'weight_cat_class_1': 0.8467610488528914, 'weight_cat_class_2': 0.5983481304421582}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,521] Trial 814 finished with value: 0.9490474539439847 and parameters: {'weight_lgbm_class_0': 0.10604397930818993, 'weight_lgbm_class_1': 0.8109666328064409, 'weight_lgbm_class_2': 0.6344560030828541, 'weight_xgb_class_0': 0.04009469512902632, 'weight_xgb_class_1': 0.30756227218696264, 'weight_xgb_class_2': 0.5116635751344263, 'weight_cat_class_0': 0.08180379303686489, 'weight_cat_class_1': 0.8481945428859892, 'weight_cat_class_2': 0.5859561797343801}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  41%|█████████████████████████████████████████████████████▉                                                                              | 817/2000 [00:26<00:44, 26.75it/s]

[I 2026-07-03 10:23:02,592] Trial 815 finished with value: 0.9489902252935091 and parameters: {'weight_lgbm_class_0': 0.10871450852045222, 'weight_lgbm_class_1': 0.8091670660613279, 'weight_lgbm_class_2': 0.6290868486265949, 'weight_xgb_class_0': 0.03766715891191348, 'weight_xgb_class_1': 0.3105380607724115, 'weight_xgb_class_2': 0.5165625842671919, 'weight_cat_class_0': 0.08391985709057304, 'weight_cat_class_1': 0.8524570581952858, 'weight_cat_class_2': 0.5911652405788065}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,651] Trial 816 finished with value: 0.9493796802018485 and parameters: {'weight_lgbm_class_0': 0.11158955385704807, 'weight_lgbm_class_1': 0.8103453215260292, 'weight_lgbm_class_2': 0.6136132190129608, 'weight_xgb_class_0': 0.0006257216284164813, 'weight_xgb_class_1': 0.3039606916918292, 'weight_xgb_class_2': 0.5093950409658974, 'weight_cat_class_0': 0.0721595306953812, 'weight_cat_class_1': 0.8518967896512812, 'weight_cat_class_2': 0.5914628936866683}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,727] Trial 817 finished with value: 0.9493861318475392 and parameters: {'weight_lgbm_class_0': 0.10486262463133217, 'weight_lgbm_class_1': 0.8063475483323906, 'weight_lgbm_class_2': 0.6158801836613923, 'weight_xgb_class_0': 7.618904734546864e-05, 'weight_xgb_class_1': 0.32451895869842656, 'weight_xgb_class_2': 0.5013121661691092, 'weight_cat_class_0': 0.07676888879227536, 'weight_cat_class_1': 0.8558941678016139, 'weight_cat_class_2': 0.5932394407085748}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  41%|██████████████████████████████████████████████████████▌                                                                             | 826/2000 [00:27<00:46, 25.44it/s]

[I 2026-07-03 10:23:02,827] Trial 819 finished with value: 0.9494396553087024 and parameters: {'weight_lgbm_class_0': 0.10135040563796001, 'weight_lgbm_class_1': 0.7684253460495835, 'weight_lgbm_class_2': 0.6118025324949123, 'weight_xgb_class_0': 0.00022455465475826678, 'weight_xgb_class_1': 0.32021124690625097, 'weight_xgb_class_2': 0.5127253091231777, 'weight_cat_class_0': 0.07818926631220535, 'weight_cat_class_1': 0.8595161815824434, 'weight_cat_class_2': 0.6013161039238074}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,863] Trial 818 finished with value: 0.9485531035519879 and parameters: {'weight_lgbm_class_0': 0.14151375500841828, 'weight_lgbm_class_1': 0.8042306184309989, 'weight_lgbm_class_2': 0.6090584028075706, 'weight_xgb_class_0': 0.01664856079880289, 'weight_xgb_class_1': 0.3034047390278388, 'weight_xgb_class_2': 0.4530108798864312, 'weight_cat_class_0': 0.08057636846761193, 'weight_cat_class_1': 0.7877462639887186, 'weight_cat_class_2': 0.5053361847503995}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,891] Trial 820 finished with value: 0.9483465789343861 and parameters: {'weight_lgbm_class_0': 0.1441910941467358, 'weight_lgbm_class_1': 0.7754837288140759, 'weight_lgbm_class_2': 0.6081756258750745, 'weight_xgb_class_0': 0.02947484269699989, 'weight_xgb_class_1': 0.3211169709304095, 'weight_xgb_class_2': 0.454568235394418, 'weight_cat_class_0': 0.08812227166617281, 'weight_cat_class_1': 0.8604172471876741, 'weight_cat_class_2': 0.598891961485588}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,896] Trial 821 finished with value: 0.9489494890176134 and parameters: {'weight_lgbm_class_0': 0.14497071025288083, 'weight_lgbm_class_1': 0.8013740632411941, 'weight_lgbm_class_2': 0.618943088971486, 'weight_xgb_class_0': 0.0010049349763238888, 'weight_xgb_class_1': 0.3174036808493969, 'weight_xgb_class_2': 0.45358046816938274, 'weight_cat_class_0': 0.08225720102443124, 'weight_cat_class_1': 0.8650055465050045, 'weight_cat_class_2': 0.6017874328220354}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,938] Trial 822 finished with value: 0.9490741577923605 and parameters: {'weight_lgbm_class_0': 0.14448296197029944, 'weight_lgbm_class_1': 0.80582896597795, 'weight_lgbm_class_2': 0.6113501519172149, 'weight_xgb_class_0': 0.0012066303013726232, 'weight_xgb_class_1': 0.3247031345257983, 'weight_xgb_class_2': 0.46155060926331254, 'weight_cat_class_0': 0.07915871769797919, 'weight_cat_class_1': 0.863862339544668, 'weight_cat_class_2': 0.6035756171422925}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,948] Trial 824 finished with value: 0.9464921881634508 and parameters: {'weight_lgbm_class_0': 0.2808766160993501, 'weight_lgbm_class_1': 0.8045775650110469, 'weight_lgbm_class_2': 0.6079549277578791, 'weight_xgb_class_0': 0.015307625960865084, 'weight_xgb_class_1': 0.3164945799988632, 'weight_xgb_class_2': 0.4638712102588237, 'weight_cat_class_0': 0.047627622411052485, 'weight_cat_class_1': 0.8640906349454796, 'weight_cat_class_2': 0.6038968870605719}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,952] Trial 823 finished with value: 0.9485771176517434 and parameters: {'weight_lgbm_class_0': 0.152017222616394, 'weight_lgbm_class_1': 0.764529755000788, 'weight_lgbm_class_2': 0.6065934198248795, 'weight_xgb_class_0': 0.02074631770480429, 'weight_xgb_class_1': 0.32228687066496403, 'weight_xgb_class_2': 0.44452860653816073, 'weight_cat_class_0': 0.07438400803052914, 'weight_cat_class_1': 0.859195708560147, 'weight_cat_class_2': 0.5985052188381922}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,978] Trial 825 finished with value: 0.9493111830127688 and parameters: {'weight_lgbm_class_0': 0.1429115810929135, 'weight_lgbm_class_1': 0.7696313462275783, 'weight_lgbm_class_2': 0.6150000215436848, 'weight_xgb_class_0': 0.0009611578947789172, 'weight_xgb_class_1': 0.2954118992811685, 'weight_xgb_class_2': 0.4617929269225007, 'weight_cat_class_0': 0.047490810802370595, 'weight_cat_class_1': 0.8680182090678215, 'weight_cat_class_2': 0.5997767741983822}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:02,980] Trial 826 finished with value: 0.9490770639861629 and parameters: {'weight_lgbm_class_0': 0.1434185926577778, 'weight_lgbm_class_1': 0.7690776264487266, 'weight_lgbm_class_2': 0.6084351554833797, 'weight_xgb_class_0': 0.017227682292691456, 'weight_xgb_class_1': 0.29732282873218624, 'weight_xgb_class_2': 0.4584273183878026, 'weight_cat_class_0': 0.055998654229849204, 'weight_cat_class_1': 0.8695690239549566, 'weight_cat_class_2': 0.5968556729476868}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  41%|██████████████████████████████████████████████████████▋                                                                             | 829/2000 [00:27<00:43, 27.07it/s]

[I 2026-07-03 10:23:03,053] Trial 827 finished with value: 0.9490242259563185 and parameters: {'weight_lgbm_class_0': 0.14892668379060764, 'weight_lgbm_class_1': 0.7642944044025817, 'weight_lgbm_class_2': 0.6083233335100519, 'weight_xgb_class_0': 0.01748393310455823, 'weight_xgb_class_1': 0.2982056201939039, 'weight_xgb_class_2': 0.4576833644877872, 'weight_cat_class_0': 0.0485017116872959, 'weight_cat_class_1': 0.7856114178845401, 'weight_cat_class_2': 0.6062391450546314}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:03,122] Trial 828 finished with value: 0.9490607600279319 and parameters: {'weight_lgbm_class_0': 0.14714512391633977, 'weight_lgbm_class_1': 0.7757919133626124, 'weight_lgbm_class_2': 0.6897921116464791, 'weight_xgb_class_0': 0.01907372744004604, 'weight_xgb_class_1': 0.22879977903496723, 'weight_xgb_class_2': 0.455256938433235, 'weight_cat_class_0': 0.047894668272486715, 'weight_cat_class_1': 0.8629800221352816, 'weight_cat_class_2': 0.518999767183694}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:03,170] Trial 829 finished with value: 0.9489874208291892 and parameters: {'weight_lgbm_class_0': 0.1509073380028734, 'weight_lgbm_class_1': 0.771367906073944, 'weight_lgbm_class_2': 0.6868698326200661, 'weight_xgb_class_0': 0.018864554822558558, 'weight_xgb_class_1': 0.2354746604775676, 'weight_xgb_class_2': 0.4530841168519302, 'weight_cat_class_0': 0.05134846246963503, 'weight_cat_class_1': 0.8102623603489154, 'weight_cat_class_2': 0.6134647109520953}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  42%|███████████████████████████████████████████████████████▎                                                                            | 838/2000 [00:27<00:44, 26.11it/s]

[I 2026-07-03 10:23:03,351] Trial 830 finished with value: 0.9463613763811347 and parameters: {'weight_lgbm_class_0': 0.15133132412074907, 'weight_lgbm_class_1': 0.76754341449281, 'weight_lgbm_class_2': 0.6864549225919662, 'weight_xgb_class_0': 0.018614566794714526, 'weight_xgb_class_1': 0.23294663499194282, 'weight_xgb_class_2': 0.34038660648171726, 'weight_cat_class_0': 0.05258881891851667, 'weight_cat_class_1': 0.024444887991758812, 'weight_cat_class_2': 0.5642423629252985}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:03,387] Trial 831 finished with value: 0.9496856639875985 and parameters: {'weight_lgbm_class_0': 0.08311975496269741, 'weight_lgbm_class_1': 0.8642601927027622, 'weight_lgbm_class_2': 0.6816824557155895, 'weight_xgb_class_0': 0.017790420405884938, 'weight_xgb_class_1': 0.23115765396460192, 'weight_xgb_class_2': 0.43015580620920635, 'weight_cat_class_0': 0.04858123883799227, 'weight_cat_class_1': 0.808487690055501, 'weight_cat_class_2': 0.526846803703552}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:03,393] Trial 832 finished with value: 0.9497258248833954 and parameters: {'weight_lgbm_class_0': 0.08268571055096652, 'weight_lgbm_class_1': 0.8661325147322629, 'weight_lgbm_class_2': 0.872328880174277, 'weight_xgb_class_0': 0.02008863025548077, 'weight_xgb_class_1': 0.3863712116260997, 'weight_xgb_class_2': 0.4536262825773886, 'weight_cat_class_0': 0.03978498874668154, 'weight_cat_class_1': 0.8211688459172194, 'weight_cat_class_2': 0.5195892623156129}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:03,418] Trial 833 finished with value: 0.949697274871701 and parameters: {'weight_lgbm_class_0': 0.08956945727642174, 'weight_lgbm_class_1': 0.8725264621703287, 'weight_lgbm_class_2': 0.6898099230310027, 'weight_xgb_class_0': 0.017316877983549035, 'weight_xgb_class_1': 0.23673093645762114, 'weight_xgb_class_2': 0.42291368862554246, 'weight_cat_class_0': 0.0423334175847149, 'weight_cat_class_1': 0.8155968568466094, 'weight_cat_class_2': 0.5220093366970018}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:03,449] Trial 834 finished with value: 0.9496902517575028 and parameters: {'weight_lgbm_class_0': 0.08289153317271097, 'weight_lgbm_class_1': 0.8654714518112098, 'weight_lgbm_class_2': 0.6907649483464491, 'weight_xgb_class_0': 0.02055093532752789, 'weight_xgb_class_1': 0.22186271646894565, 'weight_xgb_class_2': 0.4217496970377037, 'weight_cat_class_0': 0.04679600112904829, 'weight_cat_class_1': 0.8145957831322821, 'weight_cat_class_2': 0.5703779192895668}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:03,458] Trial 836 finished with value: 0.9205808371077661 and parameters: {'weight_lgbm_class_0': 0.08520682904236629, 'weight_lgbm_class_1': 0.8550761384318567, 'weight_lgbm_class_2': 0.6789188456847782, 'weight_xgb_class_0': 0.01992574266350734, 'weight_xgb_class_1': 0.23388070003502928, 'weight_xgb_class_2': 0.48481174085523177, 'weight_cat_class_0': 0.7826005211301699, 'weight_cat_class_1': 0.8072196699007734, 'weight_cat_class_2': 0.5256182013855814}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:03,471] Trial 835 finished with value: 0.9496974241773967 and parameters: {'weight_lgbm_class_0': 0.08351162979527676, 'weight_lgbm_class_1': 0.8702943031482199, 'weight_lgbm_class_2': 0.6857991726914556, 'weight_xgb_class_0': 0.021910162287354037, 'weight_xgb_class_1': 0.2360189924170013, 'weight_xgb_class_2': 0.424646534477489, 'weight_cat_class_0': 0.04357105861725397, 'weight_cat_class_1': 0.8147250927252248, 'weight_cat_class_2': 0.525988014881296}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:03,498] Trial 837 finished with value: 0.9495762235381217 and parameters: {'weight_lgbm_class_0': 0.08134020106198667, 'weight_lgbm_class_1': 0.8544128360419512, 'weight_lgbm_class_2': 0.6873292280897285, 'weight_xgb_class_0': 0.022281000004916857, 'weight_xgb_class_1': 0.2288105891918299, 'weight_xgb_class_2': 0.9282530181001124, 'weight_cat_class_0': 0.044672211580617724, 'weight_cat_class_1': 0.7812616725986494, 'weight_cat_class_2': 0.5257577262263424}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:03,514] Trial 838 finished with value: 0.9494185245446651 and parameters: {'weight_lgbm_class_0': 0.08582961693342187, 'weight_lgbm_class_1': 0.8621038974371312, 'weight_lgbm_class_2': 0.6803344690649364, 'weight_xgb_class_0': 0.022727886909917755, 'weight_xgb_class_1': 0.2252497545145332, 'weight_xgb_class_2': 0.0013367724021986216, 'weight_cat_class_0': 0.043381833956501914, 'weight_cat_class_1': 0.8165176271620773, 'weight_cat_class_2': 0.5212121358907685}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 503. Best value: 0.949768:  42%|███████████████████████████████████████████████████████▌                                                                            | 842/2000 [00:27<00:41, 28.11it/s]

[I 2026-07-03 10:23:03,518] Trial 839 finished with value: 0.9491695785413498 and parameters: {'weight_lgbm_class_0': 0.09405485431698205, 'weight_lgbm_class_1': 0.8624115147589589, 'weight_lgbm_class_2': 0.6946762041386173, 'weight_xgb_class_0': 0.050282697493603576, 'weight_xgb_class_1': 0.23378434198839465, 'weight_xgb_class_2': 0.1896519561050844, 'weight_cat_class_0': 0.04175212530976607, 'weight_cat_class_1': 0.8156167500599215, 'weight_cat_class_2': 0.5286070110591112}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:03,595] Trial 840 finished with value: 0.9493262036668068 and parameters: {'weight_lgbm_class_0': 0.0896757115812671, 'weight_lgbm_class_1': 0.8672725494471244, 'weight_lgbm_class_2': 0.6757840122278069, 'weight_xgb_class_0': 0.05025360837886572, 'weight_xgb_class_1': 0.2427105520845707, 'weight_xgb_class_2': 0.4203507662736208, 'weight_cat_class_0': 0.043817937271093024, 'weight_cat_class_1': 0.8104661444780691, 'weight_cat_class_2': 0.5545534964852115}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:03,637] Trial 841 finished with value: 0.9494814966985774 and parameters: {'weight_lgbm_class_0': 0.0879210788008158, 'weight_lgbm_class_1': 0.8601162278846036, 'weight_lgbm_class_2': 0.6782966472341444, 'weight_xgb_class_0': 0.048209037862565585, 'weight_xgb_class_1': 0.23600517104092797, 'weight_xgb_class_2': 0.4862722937114882, 'weight_cat_class_0': 0.03831265582719911, 'weight_cat_class_1': 0.8146402912066167, 'weight_cat_class_2': 0.5689293993693294}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:03,758] Trial 842 finished with value: 0.949628891172475 and parameters: {'weight_lgbm_class_0': 0.08100911813637454, 'weight_lgbm_class_1': 0.8639679946645134, 'weight_lgbm_class_2': 0.6693428730065524, 'weight_xgb_class_0': 0.049061758273920925, 'weight_xgb_class_1': 0.24029677739996103, 'weight_xgb_class_2': 0.5250777625526836, 'weight_cat_class_0': 0.03343890613351924, 'weight_cat_class_1': 0.8178550689570703, 'weight_cat_class_2': 0.5625057377700454}. Best is trial 503 with value: 0.9497676925748403.

Best trial: 846. Best value: 0.949777:  42%|████████████████████████████████████████████████████████                                                                            | 849/2000 [00:28<00:55, 20.77it/s]

[I 2026-07-03 10:23:03,846] Trial 843 finished with value: 0.9494784758918721 and parameters: {'weight_lgbm_class_0': 0.09171278712967058, 'weight_lgbm_class_1': 0.8606027231113144, 'weight_lgbm_class_2': 0.7603690410954289, 'weight_xgb_class_0': 0.05266756067562028, 'weight_xgb_class_1': 0.2687577556650923, 'weight_xgb_class_2': 0.4806201878848735, 'weight_cat_class_0': 0.03497517178288993, 'weight_cat_class_1': 0.8164435064137665, 'weight_cat_class_2': 0.4997775005216278}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:03,912] Trial 844 finished with value: 0.9496508551233974 and parameters: {'weight_lgbm_class_0': 0.10286859377419667, 'weight_lgbm_class_1': 0.8652294749301978, 'weight_lgbm_class_2': 0.8019751261387812, 'weight_xgb_class_0': 0.04767294915229565, 'weight_xgb_class_1': 0.40919725644051375, 'weight_xgb_class_2': 0.48591391206693296, 'weight_cat_class_0': 0.0193467220998377, 'weight_cat_class_1': 0.8137204323176724, 'weight_cat_class_2': 0.5105446525783942}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:03,934] Trial 845 finished with value: 0.9486966883928866 and parameters: {'weight_lgbm_class_0': 0.08265558999707155, 'weight_lgbm_class_1': 0.8379981353879549, 'weight_lgbm_class_2': 0.2568569598752477, 'weight_xgb_class_0': 0.050245893002933445, 'weight_xgb_class_1': 0.266898970754878, 'weight_xgb_class_2': 0.2818085035901816, 'weight_cat_class_0': 0.031947629616473724, 'weight_cat_class_1': 0.7872436219839023, 'weight_cat_class_2': 0.47082265266501633}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:03,949] Trial 847 finished with value: 0.9496275130985826 and parameters: {'weight_lgbm_class_0': 0.0951687359964489, 'weight_lgbm_class_1': 0.8375010458384062, 'weight_lgbm_class_2': 0.8601942457648618, 'weight_xgb_class_0': 0.04982724897219565, 'weight_xgb_class_1': 0.26486435809291875, 'weight_xgb_class_2': 0.48502440379071604, 'weight_cat_class_0': 0.01736243415132855, 'weight_cat_class_1': 0.7855319255878211, 'weight_cat_class_2': 0.4909571580989371}. Best is trial 503 with value: 0.9497676925748403.
[I 2026-07-03 10:23:03,966] Trial 846 finished with value: 0.9497767056991938 and parameters: {'weight_lgbm_class_0': 0.08778151639579398, 'weight_lgbm_class_1': 0.8395522221284006, 'weight_lgbm_class_2': 0.6630402307728096, 'weight_xgb_class_0': 0.05020219961535049, 'weight_xgb_class_1': 0.37940891365800355, 'weight_xgb_class_2': 0.48461698982617235, 'weight_cat_class_0': 0.00022872622296717647, 'weight_cat_class_1': 0.7724661864714142, 'weight_cat_class_2': 0.5030794591026415}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:03,970] Trial 848 finished with value: 0.9496886633140673 and parameters: {'weight_lgbm_class_0': 0.12916567903562717, 'weight_lgbm_class_1': 0.8372723252201816, 'weight_lgbm_class_2': 0.937140096738186, 'weight_xgb_class_0': 0.00018354600813746307, 'weight_xgb_class_1': 0.42839563459587016, 'weight_xgb_class_2': 0.48245148269601706, 'weight_cat_class_0': 0.01760948345481214, 'weight_cat_class_1': 0.8303201783626609, 'weight_cat_class_2': 0.45546977503033814}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,024] Trial 850 finished with value: 0.9495853836318414 and parameters: {'weight_lgbm_class_0': 0.12454110065535026, 'weight_lgbm_class_1': 0.8379587738032197, 'weight_lgbm_class_2': 0.8866696879040603, 'weight_xgb_class_0': 0.04882499783601486, 'weight_xgb_class_1': 0.37733256420194794, 'weight_xgb_class_2': 0.4849344672253179, 'weight_cat_class_0': 0.00039878472253988134, 'weight_cat_class_1': 0.7847026240192219, 'weight_cat_class_2': 0.49173810222896647}. Best is trial 846 with value: 0.9497767056991938.

Best trial: 846. Best value: 0.949777:  43%|████████████████████████████████████████████████████████▍                                                                           | 855/2000 [00:28<00:46, 24.49it/s]

[I 2026-07-03 10:23:04,036] Trial 849 finished with value: 0.9497191019765957 and parameters: {'weight_lgbm_class_0': 0.12091175528858529, 'weight_lgbm_class_1': 0.8301140785207927, 'weight_lgbm_class_2': 0.8584009524936886, 'weight_xgb_class_0': 0.00022401763053275965, 'weight_xgb_class_1': 0.36548045661766293, 'weight_xgb_class_2': 0.4814732723062423, 'weight_cat_class_0': 0.01813201498484919, 'weight_cat_class_1': 0.7880483179665978, 'weight_cat_class_2': 0.558492868514074}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,038] Trial 852 finished with value: 0.9492803559627649 and parameters: {'weight_lgbm_class_0': 0.1259658884324934, 'weight_lgbm_class_1': 0.84365466050964, 'weight_lgbm_class_2': 0.865700361054319, 'weight_xgb_class_0': 0.05235620399346811, 'weight_xgb_class_1': 0.2577973572543609, 'weight_xgb_class_2': 0.3821938581037415, 'weight_cat_class_0': 0.025317330058181372, 'weight_cat_class_1': 0.8278808437087847, 'weight_cat_class_2': 0.4962353550117735}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,068] Trial 851 finished with value: 0.9495371909353443 and parameters: {'weight_lgbm_class_0': 0.1297404702270478, 'weight_lgbm_class_1': 0.8368358684640961, 'weight_lgbm_class_2': 0.8896869804270285, 'weight_xgb_class_0': 0.05154356105173971, 'weight_xgb_class_1': 0.2691414579029458, 'weight_xgb_class_2': 0.48270630873714965, 'weight_cat_class_0': 0.0005826241616979609, 'weight_cat_class_1': 0.7262344867776059, 'weight_cat_class_2': 0.5565049501552807}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,106] Trial 853 finished with value: 0.949555268417523 and parameters: {'weight_lgbm_class_0': 0.12541079472212646, 'weight_lgbm_class_1': 0.8325251010139499, 'weight_lgbm_class_2': 0.9988120702779274, 'weight_xgb_class_0': 0.04640866587947593, 'weight_xgb_class_1': 0.38876157698405384, 'weight_xgb_class_2': 0.4802488315195293, 'weight_cat_class_0': 0.016020251433383953, 'weight_cat_class_1': 0.7928669327714746, 'weight_cat_class_2': 0.4843836864794736}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,235] Trial 854 finished with value: 0.9496197958944782 and parameters: {'weight_lgbm_class_0': 0.13318179248871315, 'weight_lgbm_class_1': 0.8416135759048026, 'weight_lgbm_class_2': 0.7507038613435768, 'weight_xgb_class_0': 0.0009011107224111132, 'weight_xgb_class_1': 0.4285479010498352, 'weight_xgb_class_2': 0.2776681796041627, 'weight_cat_class_0': 0.019334107276159966, 'weight_cat_class_1': 0.7949973981187807, 'weight_cat_class_2': 0.47262999372731085}. Best is trial 846 with value: 0.9497767056991938.

Best trial: 846. Best value: 0.949777:  43%|████████████████████████████████████████████████████████▋                                                                           | 858/2000 [00:28<00:50, 22.64it/s]

[I 2026-07-03 10:23:04,267] Trial 855 finished with value: 0.9290675845469539 and parameters: {'weight_lgbm_class_0': 0.1201302104130856, 'weight_lgbm_class_1': 0.8368002488783878, 'weight_lgbm_class_2': 0.8849260493218644, 'weight_xgb_class_0': 0.0004705226874009227, 'weight_xgb_class_1': 0.372513946603648, 'weight_xgb_class_2': 0.38953037301754273, 'weight_cat_class_0': 0.6532190949414245, 'weight_cat_class_1': 0.7883803267384836, 'weight_cat_class_2': 0.5083634631219714}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,362] Trial 856 finished with value: 0.9496709204236898 and parameters: {'weight_lgbm_class_0': 0.1283581879246236, 'weight_lgbm_class_1': 0.8422175713460152, 'weight_lgbm_class_2': 0.802651850161102, 'weight_xgb_class_0': 8.480774172262007e-05, 'weight_xgb_class_1': 0.27294951195382466, 'weight_xgb_class_2': 0.4823349256242457, 'weight_cat_class_0': 0.0013923484164551467, 'weight_cat_class_1': 0.7929760756835761, 'weight_cat_class_2': 0.5524092797910969}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,409] Trial 858 finished with value: 0.9496824353942982 and parameters: {'weight_lgbm_class_0': 0.1259636296992993, 'weight_lgbm_class_1': 0.8351852401110471, 'weight_lgbm_class_2': 0.8984702799029805, 'weight_xgb_class_0': 0.03699460229477341, 'weight_xgb_class_1': 0.42311922340727515, 'weight_xgb_class_2': 0.4353672337796192, 'weight_cat_class_0': 0.0005326153687195156, 'weight_cat_class_1': 0.7678725289399014, 'weight_cat_class_2': 0.49295979196343276}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,427] Trial 857 finished with value: 0.9257481971551037 and parameters: {'weight_lgbm_class_0': 0.12704284528963267, 'weight_lgbm_class_1': 0.8312403688594089, 'weight_lgbm_class_2': 0.748164107206168, 'weight_xgb_class_0': 0.035527957757308076, 'weight_xgb_class_1': 0.5303099053958102, 'weight_xgb_class_2': 0.47568941260766995, 'weight_cat_class_0': 0.6634567400444216, 'weight_cat_class_1': 0.7316608062722432, 'weight_cat_class_2': 0.4926290422768929}. Best is trial 846 with value: 0.9497767056991938.

Best trial: 846. Best value: 0.949777:  43%|█████████████████████████████████████████████████████████▏                                                                          | 866/2000 [00:28<00:40, 28.15it/s]

[I 2026-07-03 10:23:04,470] Trial 859 finished with value: 0.9218158845282778 and parameters: {'weight_lgbm_class_0': 0.1265387607694938, 'weight_lgbm_class_1': 0.8336230243488336, 'weight_lgbm_class_2': 0.6597251063331055, 'weight_xgb_class_0': 0.03603433176269942, 'weight_xgb_class_1': 0.36655247359280446, 'weight_xgb_class_2': 0.4364596148833757, 'weight_cat_class_0': 0.6731821164152627, 'weight_cat_class_1': 0.763102389074394, 'weight_cat_class_2': 0.4740660806627714}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,495] Trial 860 finished with value: 0.9493313788088377 and parameters: {'weight_lgbm_class_0': 0.07644058008830423, 'weight_lgbm_class_1': 0.8311401679541274, 'weight_lgbm_class_2': 0.8622005285898467, 'weight_xgb_class_0': 0.0011335649045609835, 'weight_xgb_class_1': 0.37857998947533694, 'weight_xgb_class_2': 0.43450700348711424, 'weight_cat_class_0': 0.02133320786854781, 'weight_cat_class_1': 0.7754306671270362, 'weight_cat_class_2': 0.5372043720824994}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,516] Trial 861 finished with value: 0.9495716560482057 and parameters: {'weight_lgbm_class_0': 0.0741592188259401, 'weight_lgbm_class_1': 0.831797957135932, 'weight_lgbm_class_2': 0.8121193012609803, 'weight_xgb_class_0': 0.03324410472112512, 'weight_xgb_class_1': 0.38081581294937433, 'weight_xgb_class_2': 0.4372277496011244, 'weight_cat_class_0': 0.00033517399702318387, 'weight_cat_class_1': 0.7517968813566348, 'weight_cat_class_2': 0.4779549424010375}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,566] Trial 862 finished with value: 0.9495896724201933 and parameters: {'weight_lgbm_class_0': 0.07406374566693077, 'weight_lgbm_class_1': 0.8429936737501886, 'weight_lgbm_class_2': 0.7404682520723636, 'weight_xgb_class_0': 0.027523804024474092, 'weight_xgb_class_1': 0.3449274108706651, 'weight_xgb_class_2': 0.45459404960686767, 'weight_cat_class_0': 0.0651724652439836, 'weight_cat_class_1': 0.7416915012011452, 'weight_cat_class_2': 0.5015617731735263}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,572] Trial 863 finished with value: 0.9496515537055013 and parameters: {'weight_lgbm_class_0': 0.07116930505928876, 'weight_lgbm_class_1': 0.827610755055587, 'weight_lgbm_class_2': 0.8387433404830134, 'weight_xgb_class_0': 0.02969038236248063, 'weight_xgb_class_1': 0.399251182242472, 'weight_xgb_class_2': 0.436284182473285, 'weight_cat_class_0': 0.06286161141316082, 'weight_cat_class_1': 0.760781862925422, 'weight_cat_class_2': 0.49973282760136156}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,585] Trial 864 finished with value: 0.9134533319965864 and parameters: {'weight_lgbm_class_0': 0.07670161397363864, 'weight_lgbm_class_1': 0.827740299787236, 'weight_lgbm_class_2': 0.8254545211393328, 'weight_xgb_class_0': 0.029176469268428144, 'weight_xgb_class_1': 0.3891764440522605, 'weight_xgb_class_2': 0.10312534259894271, 'weight_cat_class_0': 0.8303403187271915, 'weight_cat_class_1': 0.7719177433181507, 'weight_cat_class_2': 0.5024914337452635}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,633] Trial 865 finished with value: 0.949278881494707 and parameters: {'weight_lgbm_class_0': 0.1041058329371358, 'weight_lgbm_class_1': 0.8301806609302067, 'weight_lgbm_class_2': 0.6548956108995189, 'weight_xgb_class_0': 0.025607160865334287, 'weight_xgb_class_1': 0.40954363124328963, 'weight_xgb_class_2': 0.39372006785103275, 'weight_cat_class_0': 0.05931548306843724, 'weight_cat_class_1': 0.7316555182792587, 'weight_cat_class_2': 0.5022216479490346}. Best is trial 846 with value: 0.9497767056991938.

Best trial: 846. Best value: 0.949777:  44%|█████████████████████████████████████████████████████████▍                                                                          | 870/2000 [00:29<00:51, 22.12it/s]

[I 2026-07-03 10:23:04,714] Trial 866 finished with value: 0.9495864214292004 and parameters: {'weight_lgbm_class_0': 0.0747878110267958, 'weight_lgbm_class_1': 0.7943471767827185, 'weight_lgbm_class_2': 0.9520541405494973, 'weight_xgb_class_0': 0.02840352497715263, 'weight_xgb_class_1': 0.3854991823069092, 'weight_xgb_class_2': 0.43877116144428535, 'weight_cat_class_0': 0.06332047553542397, 'weight_cat_class_1': 0.7408963600800752, 'weight_cat_class_2': 0.5052457483397842}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,771] Trial 867 finished with value: 0.9496459320705747 and parameters: {'weight_lgbm_class_0': 0.0721513292416309, 'weight_lgbm_class_1': 0.7947821035355913, 'weight_lgbm_class_2': 0.9748569481910607, 'weight_xgb_class_0': 0.030447708853973545, 'weight_xgb_class_1': 0.36770148023514865, 'weight_xgb_class_2': 0.43663128186893885, 'weight_cat_class_0': 0.0616684853748742, 'weight_cat_class_1': 0.7312014541942499, 'weight_cat_class_2': 0.5462690506405001}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,815] Trial 868 finished with value: 0.9495858435766639 and parameters: {'weight_lgbm_class_0': 0.07279089490671191, 'weight_lgbm_class_1': 0.8284142222109124, 'weight_lgbm_class_2': 0.8489832523545348, 'weight_xgb_class_0': 0.029311198349942297, 'weight_xgb_class_1': 0.3650081475768429, 'weight_xgb_class_2': 0.46084186684424666, 'weight_cat_class_0': 0.06322184405805649, 'weight_cat_class_1': 0.7281316282176925, 'weight_cat_class_2': 0.5005475305458837}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,904] Trial 869 finished with value: 0.9496963326871602 and parameters: {'weight_lgbm_class_0': 0.07423399552418011, 'weight_lgbm_class_1': 0.7925032763745524, 'weight_lgbm_class_2': 0.8234884391478305, 'weight_xgb_class_0': 0.020878020192112993, 'weight_xgb_class_1': 0.39941384861355544, 'weight_xgb_class_2': 0.5005548976846674, 'weight_cat_class_0': 0.05955501836669634, 'weight_cat_class_1': 0.7602581836724014, 'weight_cat_class_2': 0.4461567891609768}. Best is trial 846 with value: 0.9497767056991938.

[I 2026-07-03 10:23:04,955] Trial 870 finished with value: 0.9495516159341476 and parameters: {'weight_lgbm_class_0': 0.07297186648028951, 'weight_lgbm_class_1': 0.8036171990729313, 'weight_lgbm_class_2': 0.5998283225547492, 'weight_xgb_class_0': 0.022410859735575665, 'weight_xgb_class_1': 0.38399138350975986, 'weight_xgb_class_2': 0.4557235011954549, 'weight_cat_class_0': 0.061121451478311856, 'weight_cat_class_1': 0.7394851935549158, 'weight_cat_class_2': 0.510778316264813}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,963] Trial 871 finished with value: 0.9491362890641343 and parameters: {'weight_lgbm_class_0': 0.1022540314593101, 'weight_lgbm_class_1': 0.7963856151021773, 'weight_lgbm_class_2': 0.8547656323007087, 'weight_xgb_class_0': 0.021985591158942365, 'weight_xgb_class_1': 0.2897524111645943, 'weight_xgb_class_2': 0.12544771188302667, 'weight_cat_class_0': 0.06476222459317105, 'weight_cat_class_1': 0.7408917133696009, 'weight_cat_class_2': 0.5086665302396685}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:04,978] Trial 872 finished with value: 0.9494951505661362 and parameters: {'weight_lgbm_class_0': 0.1024934473147545, 'weight_lgbm_class_1': 0.814636732268516, 'weight_lgbm_class_2': 0.5939328461046078, 'weight_xgb_class_0': 9.910720522549087e-05, 'weight_xgb_class_1': 0.3953426120786973, 'weight_xgb_class_2': 0.4657204759889982, 'weight_cat_class_0': 0.0657754433215882, 'weight_cat_class_1': 0.75003519432137, 'weight_cat_class_2': 0.5443468729671224}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,018] Trial 873 finished with value: 0.9492977291163366 and parameters: {'weight_lgbm_class_0': 0.09605864805441622, 'weight_lgbm_class_1': 0.791721354372194, 'weight_lgbm_class_2': 0.5920037640708876, 'weight_xgb_class_0': 0.02378621677534172, 'weight_xgb_class_1': 0.2905700871044066, 'weight_xgb_class_2': 0.4652575397536679, 'weight_cat_class_0': 0.06010174084956295, 'weight_cat_class_1': 0.7323677569701128, 'weight_cat_class_2': 0.5414075827964572}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,074] Trial 875 finished with value: 0.9496374726815153 and parameters: {'weight_lgbm_class_0': 0.10366954500985004, 'weight_lgbm_class_1': 0.7940456265495965, 'weight_lgbm_class_2': 0.8608865945247723, 'weight_xgb_class_0': 0.01971904048128977, 'weight_xgb_class_1': 0.28895609937845834, 'weight_xgb_class_2': 0.5158866526056198, 'weight_cat_class_0': 0.032991802742589664, 'weight_cat_class_1': 0.7667480590789448, 'weight_cat_class_2': 0.44020395505439985}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,077] Trial 874 finished with value: 0.9495741155174556 and parameters: {'weight_lgbm_class_0': 0.09657003533326088, 'weight_lgbm_class_1': 0.792888822080082, 'weight_lgbm_class_2': 0.8643228619093465, 'weight_xgb_class_0': 3.359224946870658e-05, 'weight_xgb_class_1': 0.40603576038429745, 'weight_xgb_class_2': 0.5164238640466858, 'weight_cat_class_0': 0.03074358919144178, 'weight_cat_class_1': 0.7358268289556256, 'weight_cat_class_2': 0.5486177706793866}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,093] Trial 877 finished with value: 0.9496817313330554 and parameters: {'weight_lgbm_class_0': 0.10220410400223788, 'weight_lgbm_class_1': 0.7955310216787951, 'weight_lgbm_class_2': 0.9090861499373578, 'weight_xgb_class_0': 0.017224163926063664, 'weight_xgb_class_1': 0.35898545523288955, 'weight_xgb_class_2': 0.5008381181093482, 'weight_cat_class_0': 0.03117142151313914, 'weight_cat_class_1': 0.7525190969983224, 'weight_cat_class_2': 0.5426044503694455}. Best is trial 846 with value: 0.9497767056991938.

[I 2026-07-03 10:23:05,119] Trial 876 finished with value: 0.9496495295165365 and parameters: {'weight_lgbm_class_0': 0.10218956481340793, 'weight_lgbm_class_1': 0.8042815358422553, 'weight_lgbm_class_2': 0.5926552397825535, 'weight_xgb_class_0': 0.019240309636057287, 'weight_xgb_class_1': 0.34167848338849693, 'weight_xgb_class_2': 0.517794260115012, 'weight_cat_class_0': 0.033686898956772, 'weight_cat_class_1': 0.7541675152254222, 'weight_cat_class_2': 0.5367515760185013}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,213] Trial 878 finished with value: 0.9491389806428145 and parameters: {'weight_lgbm_class_0': 0.1012571293415654, 'weight_lgbm_class_1': 0.8686879746236503, 'weight_lgbm_class_2': 0.8597136387498446, 'weight_xgb_class_0': 0.01923729593919426, 'weight_xgb_class_1': 0.2958686792183486, 'weight_xgb_class_2': 0.517177328898589, 'weight_cat_class_0': 0.09832404024507224, 'weight_cat_class_1': 0.7454217733276737, 'weight_cat_class_2': 0.44464305595125647}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,258] Trial 879 finished with value: 0.949429726679253 and parameters: {'weight_lgbm_class_0': 0.10061384837514763, 'weight_lgbm_class_1': 0.8715354022689584, 'weight_lgbm_class_2': 0.9083311014890604, 'weight_xgb_class_0': 0.0007973696356413824, 'weight_xgb_class_1': 0.340467521437448, 'weight_xgb_class_2': 0.5206555687651067, 'weight_cat_class_0': 0.10227250947418137, 'weight_cat_class_1': 0.7940777589601313, 'weight_cat_class_2': 0.5367946068353885}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,306] Trial 880 finished with value: 0.9492859502063841 and parameters: {'weight_lgbm_class_0': 0.10273848719402102, 'weight_lgbm_class_1': 0.8702856162470569, 'weight_lgbm_class_2': 0.5978064366400849, 'weight_xgb_class_0': 0.05898179386337603, 'weight_xgb_class_1': 0.35675345414414616, 'weight_xgb_class_2': 0.5033521674387986, 'weight_cat_class_0': 0.030142378036860068, 'weight_cat_class_1': 0.7753483244491497, 'weight_cat_class_2': 0.5403736559076318}. Best is trial 846 with value: 0.9497767056991938.

Best trial: 846. Best value: 0.949777:  44%|██████████████████████████████████████████████████████████▌                                                                         | 887/2000 [00:29<00:45, 24.23it/s]

[I 2026-07-03 10:23:05,382] Trial 881 finished with value: 0.9491725626147568 and parameters: {'weight_lgbm_class_0': 0.10222010865141913, 'weight_lgbm_class_1': 0.8714328442672383, 'weight_lgbm_class_2': 0.5984697753188043, 'weight_xgb_class_0': 0.0013844239715488788, 'weight_xgb_class_1': 0.3041082762297096, 'weight_xgb_class_2': 0.5121935411626134, 'weight_cat_class_0': 0.10037925093077094, 'weight_cat_class_1': 0.7694560186051038, 'weight_cat_class_2': 0.5339419516159752}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,454] Trial 883 finished with value: 0.949568043896477 and parameters: {'weight_lgbm_class_0': 0.10268860651008059, 'weight_lgbm_class_1': 0.8683108484014368, 'weight_lgbm_class_2': 0.9144759719112259, 'weight_xgb_class_0': 0.001221640078859716, 'weight_xgb_class_1': 0.3480264238644937, 'weight_xgb_class_2': 0.5240025090195417, 'weight_cat_class_0': 0.029409346973527768, 'weight_cat_class_1': 0.7974825023264326, 'weight_cat_class_2': 0.6185858770208658}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,480] Trial 882 finished with value: 0.9495442894489958 and parameters: {'weight_lgbm_class_0': 0.10184710849230644, 'weight_lgbm_class_1': 0.8594951785344561, 'weight_lgbm_class_2': 0.8731694664391321, 'weight_xgb_class_0': 0.05768766070694844, 'weight_xgb_class_1': 0.34595805303565735, 'weight_xgb_class_2': 0.5153928683085972, 'weight_cat_class_0': 0.030855380558116877, 'weight_cat_class_1': 0.7726429448437321, 'weight_cat_class_2': 0.6205757441856249}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,518] Trial 885 finished with value: 0.9495564827062921 and parameters: {'weight_lgbm_class_0': 0.1036178490950278, 'weight_lgbm_class_1': 0.87198674184378, 'weight_lgbm_class_2': 0.8992411342283341, 'weight_xgb_class_0': 0.05572541069322108, 'weight_xgb_class_1': 0.2891522580145601, 'weight_xgb_class_2': 0.5168972481775328, 'weight_cat_class_0': 0.030829448363639524, 'weight_cat_class_1': 0.785820797682483, 'weight_cat_class_2': 0.6224237603697989}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,554] Trial 884 finished with value: 0.9496408335799065 and parameters: {'weight_lgbm_class_0': 0.10752640395501481, 'weight_lgbm_class_1': 0.8759536902306795, 'weight_lgbm_class_2': 0.9263278113356956, 'weight_xgb_class_0': 0.000606863493326823, 'weight_xgb_class_1': 0.3457374182669763, 'weight_xgb_class_2': 0.5109841649709072, 'weight_cat_class_0': 0.03225695737034549, 'weight_cat_class_1': 0.7817647365403984, 'weight_cat_class_2': 0.6180373143168163}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,578] Trial 886 finished with value: 0.9092494956408309 and parameters: {'weight_lgbm_class_0': 0.11032084559467809, 'weight_lgbm_class_1': 0.8782590983467523, 'weight_lgbm_class_2': 0.6560059151335995, 'weight_xgb_class_0': 0.059413993009873586, 'weight_xgb_class_1': 0.33845651545664696, 'weight_xgb_class_2': 0.522415679253552, 'weight_cat_class_0': 0.978196311733396, 'weight_cat_class_1': 0.7808065542660599, 'weight_cat_class_2': 0.6214464031566633}. Best is trial 846 with value: 0.9497767056991938.

[I 2026-07-03 10:23:05,617] Trial 887 finished with value: 0.9477825884447538 and parameters: {'weight_lgbm_class_0': 0.15838549852946807, 'weight_lgbm_class_1': 0.8645117270871736, 'weight_lgbm_class_2': 0.7764439730338085, 'weight_xgb_class_0': 0.058081727562277835, 'weight_xgb_class_1': 0.3521317768325834, 'weight_xgb_class_2': 0.498245768253612, 'weight_cat_class_0': 0.0976307104788704, 'weight_cat_class_1': 0.7906774412862609, 'weight_cat_class_2': 0.6224824854649266}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,657] Trial 888 finished with value: 0.9497480456159993 and parameters: {'weight_lgbm_class_0': 0.11411198327010952, 'weight_lgbm_class_1': 0.8681734792443531, 'weight_lgbm_class_2': 0.6244591425426339, 'weight_xgb_class_0': 0.0005399732059328108, 'weight_xgb_class_1': 0.26163495541985476, 'weight_xgb_class_2': 0.49609649342019146, 'weight_cat_class_0': 0.01832680772354639, 'weight_cat_class_1': 0.7933140234069554, 'weight_cat_class_2': 0.6183938541649834}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,683] Trial 889 finished with value: 0.9486169069709697 and parameters: {'weight_lgbm_class_0': 0.10798547710426402, 'weight_lgbm_class_1': 0.8727044529526048, 'weight_lgbm_class_2': 0.622977696967492, 'weight_xgb_class_0': 0.061352767366832095, 'weight_xgb_class_1': 0.3445861524815851, 'weight_xgb_class_2': 0.49675248775453307, 'weight_cat_class_0': 0.022075460193604672, 'weight_cat_class_1': 0.1094419376039169, 'weight_cat_class_2': 0.6228701567637991}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,734] Trial 890 finished with value: 0.9490161545102364 and parameters: {'weight_lgbm_class_0': 0.15994615229228326, 'weight_lgbm_class_1': 0.8724209362976446, 'weight_lgbm_class_2': 0.6253926533162208, 'weight_xgb_class_0': 0.050334562525727336, 'weight_xgb_class_1': 0.26930149502251116, 'weight_xgb_class_2': 0.4930373940305381, 'weight_cat_class_0': 0.01740294563229545, 'weight_cat_class_1': 0.7927892017949009, 'weight_cat_class_2': 0.6188878673797386}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,789] Trial 891 finished with value: 0.9492258798853325 and parameters: {'weight_lgbm_class_0': 0.15806283008878713, 'weight_lgbm_class_1': 0.8662429460683023, 'weight_lgbm_class_2': 0.8783117422483133, 'weight_xgb_class_0': 0.05541793272708746, 'weight_xgb_class_1': 0.4741161365649005, 'weight_xgb_class_2': 0.49375772841490884, 'weight_cat_class_0': 0.01554808216244694, 'weight_cat_class_1': 0.7782660266560371, 'weight_cat_class_2': 0.6212104316517069}. Best is trial 846 with value: 0.9497767056991938.

[I 2026-07-03 10:23:05,811] Trial 892 finished with value: 0.9491936052445951 and parameters: {'weight_lgbm_class_0': 0.1540252414239337, 'weight_lgbm_class_1': 0.8563267969901563, 'weight_lgbm_class_2': 0.6243305685813952, 'weight_xgb_class_0': 0.0570609752211196, 'weight_xgb_class_1': 0.4716659054391281, 'weight_xgb_class_2': 0.49394292987739485, 'weight_cat_class_0': 7.16867399598968e-05, 'weight_cat_class_1': 0.7880559341037546, 'weight_cat_class_2': 0.6193447383813078}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,926] Trial 893 finished with value: 0.9484399115579795 and parameters: {'weight_lgbm_class_0': 0.11986828199060902, 'weight_lgbm_class_1': 0.7473099588689651, 'weight_lgbm_class_2': 0.6270935893650609, 'weight_xgb_class_0': 0.05895488150823273, 'weight_xgb_class_1': 0.3397737602515471, 'weight_xgb_class_2': 0.47754840050509717, 'weight_cat_class_0': 0.015829065500960377, 'weight_cat_class_1': 0.192008300956181, 'weight_cat_class_2': 0.6221710605330729}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:05,997] Trial 894 finished with value: 0.948672197144972 and parameters: {'weight_lgbm_class_0': 0.15773825272625458, 'weight_lgbm_class_1': 0.8480828009375679, 'weight_lgbm_class_2': 0.6274252961418806, 'weight_xgb_class_0': 0.056824870886847755, 'weight_xgb_class_1': 0.20347095241365304, 'weight_xgb_class_2': 0.4098710580430542, 'weight_cat_class_0': 0.02105406328086212, 'weight_cat_class_1': 0.825886364735836, 'weight_cat_class_2': 0.5727419249438355}. Best is trial 846 with value: 0.9497767056991938.

Best trial: 846. Best value: 0.949777:  45%|███████████████████████████████████████████████████████████▍                                                                        | 901/2000 [00:30<00:45, 24.08it/s]

[I 2026-07-03 10:23:06,023] Trial 895 finished with value: 0.9490037433763184 and parameters: {'weight_lgbm_class_0': 0.1586851121856673, 'weight_lgbm_class_1': 0.8522290808344536, 'weight_lgbm_class_2': 0.6252009361788154, 'weight_xgb_class_0': 0.059517196941438574, 'weight_xgb_class_1': 0.47981258105842733, 'weight_xgb_class_2': 0.4932976071385893, 'weight_cat_class_0': 0.0006009910171118557, 'weight_cat_class_1': 0.6992435640739612, 'weight_cat_class_2': 0.5589243495598987}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,033] Trial 896 finished with value: 0.9493369960205857 and parameters: {'weight_lgbm_class_0': 0.12125935381902686, 'weight_lgbm_class_1': 0.849988467983821, 'weight_lgbm_class_2': 0.6284898971000472, 'weight_xgb_class_0': 0.057678125864111744, 'weight_xgb_class_1': 0.26117682034396417, 'weight_xgb_class_2': 0.49163169718361227, 'weight_cat_class_0': 0.014016049527011892, 'weight_cat_class_1': 0.8305602061113113, 'weight_cat_class_2': 0.5784838461302868}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,080] Trial 897 finished with value: 0.9487365958664458 and parameters: {'weight_lgbm_class_0': 0.15529074322802905, 'weight_lgbm_class_1': 0.7443130944641352, 'weight_lgbm_class_2': 0.6547851976360226, 'weight_xgb_class_0': 0.05513988582064142, 'weight_xgb_class_1': 0.20565177261917503, 'weight_xgb_class_2': 0.4122979361441933, 'weight_cat_class_0': 0.01596173979338478, 'weight_cat_class_1': 0.8328908570133272, 'weight_cat_class_2': 0.5733216312076387}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,116] Trial 899 finished with value: 0.9490598556997387 and parameters: {'weight_lgbm_class_0': 0.1602134276736633, 'weight_lgbm_class_1': 0.8481599851372413, 'weight_lgbm_class_2': 0.6249450737114941, 'weight_xgb_class_0': 0.043951566504565553, 'weight_xgb_class_1': 0.47556971847376206, 'weight_xgb_class_2': 0.47093336664620145, 'weight_cat_class_0': 0.01369613354912464, 'weight_cat_class_1': 0.8200360051239929, 'weight_cat_class_2': 0.5738820404698141}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,123] Trial 898 finished with value: 0.9489990460899228 and parameters: {'weight_lgbm_class_0': 0.1565571039660488, 'weight_lgbm_class_1': 0.8514974462316545, 'weight_lgbm_class_2': 0.6273167068459458, 'weight_xgb_class_0': 0.04794459972595266, 'weight_xgb_class_1': 0.2701519747075341, 'weight_xgb_class_2': 0.49193491399134354, 'weight_cat_class_0': 0.01942492700752, 'weight_cat_class_1': 0.8279786969160859, 'weight_cat_class_2': 0.5744486543557173}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,175] Trial 900 finished with value: 0.9497456335535425 and parameters: {'weight_lgbm_class_0': 0.08038314931521517, 'weight_lgbm_class_1': 0.7431015489833193, 'weight_lgbm_class_2': 0.6316632740427421, 'weight_xgb_class_0': 0.04498902220964198, 'weight_xgb_class_1': 0.19923381679237048, 'weight_xgb_class_2': 0.494859970693801, 'weight_cat_class_0': 0.017040333513612983, 'weight_cat_class_1': 0.8010569495186903, 'weight_cat_class_2': 0.5785082134032484}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,208] Trial 901 finished with value: 0.9496962721990672 and parameters: {'weight_lgbm_class_0': 0.0731601718921204, 'weight_lgbm_class_1': 0.8504821553763006, 'weight_lgbm_class_2': 0.6244238264530586, 'weight_xgb_class_0': 0.043073122338839635, 'weight_xgb_class_1': 0.24775458387966015, 'weight_xgb_class_2': 0.4893234858032971, 'weight_cat_class_0': 0.017146810457833443, 'weight_cat_class_1': 0.7035838397191363, 'weight_cat_class_2': 0.5812569635379339}. Best is trial 846 with value: 0.9497767056991938.

Best trial: 846. Best value: 0.949777:  45%|███████████████████████████████████████████████████████████▊                                                                        | 906/2000 [00:30<00:48, 22.51it/s]

[I 2026-07-03 10:23:06,241] Trial 902 finished with value: 0.9497414274376692 and parameters: {'weight_lgbm_class_0': 0.07916878836762115, 'weight_lgbm_class_1': 0.8518604965396549, 'weight_lgbm_class_2': 0.8346322512039408, 'weight_xgb_class_0': 0.040536366213925555, 'weight_xgb_class_1': 0.4621623191322721, 'weight_xgb_class_2': 0.47660946289360706, 'weight_cat_class_0': 0.014919373931542794, 'weight_cat_class_1': 0.8082974167424576, 'weight_cat_class_2': 0.4090816383492412}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,291] Trial 903 finished with value: 0.9442231298091053 and parameters: {'weight_lgbm_class_0': 0.3472189743853721, 'weight_lgbm_class_1': 0.8145815039863067, 'weight_lgbm_class_2': 0.6288397627034421, 'weight_xgb_class_0': 0.04190334030586372, 'weight_xgb_class_1': 0.2615378293683573, 'weight_xgb_class_2': 0.46288629783329355, 'weight_cat_class_0': 0.015297894813248432, 'weight_cat_class_1': 0.806645354410595, 'weight_cat_class_2': 0.5788368055436899}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,339] Trial 904 finished with value: 0.9494292588035993 and parameters: {'weight_lgbm_class_0': 0.07680988415363565, 'weight_lgbm_class_1': 0.7457377947653338, 'weight_lgbm_class_2': 0.6244792709132484, 'weight_xgb_class_0': 0.043226794146985784, 'weight_xgb_class_1': 0.19886367765398474, 'weight_xgb_class_2': 0.4698638501897066, 'weight_cat_class_0': 0.014891161530970184, 'weight_cat_class_1': 0.352931917659655, 'weight_cat_class_2': 0.5779931043348664}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,413] Trial 905 finished with value: 0.9495103283413381 and parameters: {'weight_lgbm_class_0': 0.08607341091320522, 'weight_lgbm_class_1': 0.8489633974643129, 'weight_lgbm_class_2': 0.6574156887573139, 'weight_xgb_class_0': 0.039515928586639854, 'weight_xgb_class_1': 0.2560209688892464, 'weight_xgb_class_2': 0.41061083707576446, 'weight_cat_class_0': 0.045017027726421674, 'weight_cat_class_1': 0.8720593637538021, 'weight_cat_class_2': 0.5769161132137203}. Best is trial 846 with value: 0.9497767056991938.

Best trial: 846. Best value: 0.949777:  46%|████████████████████████████████████████████████████████████▎                                                                       | 913/2000 [00:30<00:42, 25.39it/s]

[I 2026-07-03 10:23:06,520] Trial 906 finished with value: 0.9493648423947901 and parameters: {'weight_lgbm_class_0': 0.08619960192357617, 'weight_lgbm_class_1': 0.8164235739008204, 'weight_lgbm_class_2': 0.6565285074522005, 'weight_xgb_class_0': 0.03378008161025789, 'weight_xgb_class_1': 0.20527080924311222, 'weight_xgb_class_2': 0.15914072128051593, 'weight_cat_class_0': 0.04495212549606619, 'weight_cat_class_1': 0.8759559650753242, 'weight_cat_class_2': 0.5725395573001684}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,524] Trial 907 finished with value: 0.9495035543704868 and parameters: {'weight_lgbm_class_0': 0.07944771833879143, 'weight_lgbm_class_1': 0.8865776023887947, 'weight_lgbm_class_2': 0.6560091392766849, 'weight_xgb_class_0': 0.03662632086698701, 'weight_xgb_class_1': 0.25337247423511566, 'weight_xgb_class_2': 0.1697422812978457, 'weight_cat_class_0': 0.04411745987299952, 'weight_cat_class_1': 0.876983646662014, 'weight_cat_class_2': 0.5813481623714019}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,552] Trial 909 finished with value: 0.9495263672579211 and parameters: {'weight_lgbm_class_0': 0.07643307894640444, 'weight_lgbm_class_1': 0.8145240722456039, 'weight_lgbm_class_2': 0.656145064654601, 'weight_xgb_class_0': 0.03791989444045366, 'weight_xgb_class_1': 0.2541499765696428, 'weight_xgb_class_2': 0.533563709361871, 'weight_cat_class_0': 0.046238698953690996, 'weight_cat_class_1': 0.813549383733415, 'weight_cat_class_2': 0.410770515176037}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,594] Trial 908 finished with value: 0.9496530346319254 and parameters: {'weight_lgbm_class_0': 0.07885655340975503, 'weight_lgbm_class_1': 0.8116172853934848, 'weight_lgbm_class_2': 0.6578019494659002, 'weight_xgb_class_0': 0.03653489814855981, 'weight_xgb_class_1': 0.24791719558875716, 'weight_xgb_class_2': 0.5319335520279118, 'weight_cat_class_0': 0.045652384529928654, 'weight_cat_class_1': 0.8792304834298026, 'weight_cat_class_2': 0.5815230799554593}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,622] Trial 910 finished with value: 0.9360919032369686 and parameters: {'weight_lgbm_class_0': 0.4497005209747019, 'weight_lgbm_class_1': 0.3104315462860223, 'weight_lgbm_class_2': 0.6536787819797744, 'weight_xgb_class_0': 0.03494810532988099, 'weight_xgb_class_1': 0.25009655050694796, 'weight_xgb_class_2': 0.5293556466940247, 'weight_cat_class_0': 0.04773136068543358, 'weight_cat_class_1': 0.8741381384962786, 'weight_cat_class_2': 0.5991988305831379}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,640] Trial 911 finished with value: 0.9413475710770446 and parameters: {'weight_lgbm_class_0': 0.34510127407958835, 'weight_lgbm_class_1': 0.8186969566910938, 'weight_lgbm_class_2': 0.6645525023633807, 'weight_xgb_class_0': 0.020099860618410896, 'weight_xgb_class_1': 0.25219038326665755, 'weight_xgb_class_2': 0.528192363864642, 'weight_cat_class_0': 0.04484576268621229, 'weight_cat_class_1': 0.867762980540996, 'weight_cat_class_2': 0.13287802939548649}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,685] Trial 912 finished with value: 0.9316303429918816 and parameters: {'weight_lgbm_class_0': 0.48242545644652696, 'weight_lgbm_class_1': 0.31854854467412896, 'weight_lgbm_class_2': 0.5957334823451097, 'weight_xgb_class_0': 0.03833145835284951, 'weight_xgb_class_1': 0.19609619597930894, 'weight_xgb_class_2': 0.46058392844427753, 'weight_cat_class_0': 0.046555630581804286, 'weight_cat_class_1': 0.8033447026231335, 'weight_cat_class_2': 0.5833918002765223}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,698] Trial 913 finished with value: 0.9495960414267169 and parameters: {'weight_lgbm_class_0': 0.06771609449269773, 'weight_lgbm_class_1': 0.7544277341482453, 'weight_lgbm_class_2': 0.8387692891101303, 'weight_xgb_class_0': 0.038456182995197805, 'weight_xgb_class_1': 0.1932643111117653, 'weight_xgb_class_2': 0.4501599606561148, 'weight_cat_class_0': 0.04502546712912701, 'weight_cat_class_1': 0.7894523076950664, 'weight_cat_class_2': 0.3103216074513948}. Best is trial 846 with value: 0.9497767056991938.

Best trial: 846. Best value: 0.949777:  46%|████████████████████████████████████████████████████████████▌                                                                       | 917/2000 [00:31<00:41, 25.99it/s]

[I 2026-07-03 10:23:06,725] Trial 914 finished with value: 0.9438878203061677 and parameters: {'weight_lgbm_class_0': 0.07270926531880777, 'weight_lgbm_class_1': 0.7336713086652693, 'weight_lgbm_class_2': 0.8747034237384345, 'weight_xgb_class_0': 0.03553143626270072, 'weight_xgb_class_1': 0.4187327503525297, 'weight_xgb_class_2': 0.4619477788279841, 'weight_cat_class_0': 0.3434279765666639, 'weight_cat_class_1': 0.7669738518418044, 'weight_cat_class_2': 0.6054400268640234}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,788] Trial 915 finished with value: 0.9497369249926768 and parameters: {'weight_lgbm_class_0': 0.07113498262789328, 'weight_lgbm_class_1': 0.7200710851516829, 'weight_lgbm_class_2': 0.8895356382497749, 'weight_xgb_class_0': 0.037506253902517515, 'weight_xgb_class_1': 0.505749090056095, 'weight_xgb_class_2': 0.470601365612397, 'weight_cat_class_0': 0.04230471621877499, 'weight_cat_class_1': 0.7717205375517568, 'weight_cat_class_2': 0.4133283798375828}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,828] Trial 916 finished with value: 0.9496897126454584 and parameters: {'weight_lgbm_class_0': 0.072852860490309, 'weight_lgbm_class_1': 0.7377591475069948, 'weight_lgbm_class_2': 0.8184917680396201, 'weight_xgb_class_0': 0.03589929694151018, 'weight_xgb_class_1': 0.5219696640518148, 'weight_xgb_class_2': 0.448896284568439, 'weight_cat_class_0': 0.04483909565821623, 'weight_cat_class_1': 0.8032023576166537, 'weight_cat_class_2': 0.27555801792889645}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:06,934] Trial 917 finished with value: 0.9496949278102808 and parameters: {'weight_lgbm_class_0': 0.0722576956055517, 'weight_lgbm_class_1': 0.7518741742461561, 'weight_lgbm_class_2': 0.8368669728039853, 'weight_xgb_class_0': 0.03377941230022475, 'weight_xgb_class_1': 0.5112269598388335, 'weight_xgb_class_2': 0.45798072325062816, 'weight_cat_class_0': 0.044469933767311676, 'weight_cat_class_1': 0.8020672846256616, 'weight_cat_class_2': 0.3102853546931937}. Best is trial 846 with value: 0.9497767056991938.

Best trial: 846. Best value: 0.949777:  46%|████████████████████████████████████████████████████████████▊                                                                       | 922/2000 [00:31<00:52, 20.54it/s]

[I 2026-07-03 10:23:06,991] Trial 918 finished with value: 0.9428794888699596 and parameters: {'weight_lgbm_class_0': 0.06213573284534403, 'weight_lgbm_class_1': 0.7495278937145289, 'weight_lgbm_class_2': 0.8351373523859794, 'weight_xgb_class_0': 0.026917576473303548, 'weight_xgb_class_1': 0.4189722868725261, 'weight_xgb_class_2': 0.45714132410344527, 'weight_cat_class_0': 0.3637445909821715, 'weight_cat_class_1': 0.7993071577510902, 'weight_cat_class_2': 0.40023158180948565}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:07,050] Trial 920 finished with value: 0.9298714984881795 and parameters: {'weight_lgbm_class_0': 0.06043849508837196, 'weight_lgbm_class_1': 0.7498574984417608, 'weight_lgbm_class_2': 0.845247169016692, 'weight_xgb_class_0': 0.6004425624035162, 'weight_xgb_class_1': 0.44024667414354574, 'weight_xgb_class_2': 0.4455296979872156, 'weight_cat_class_0': 0.001097969012191036, 'weight_cat_class_1': 0.7972502224615384, 'weight_cat_class_2': 0.2672665109201229}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:07,095] Trial 919 finished with value: 0.9492970004291864 and parameters: {'weight_lgbm_class_0': 0.0685893170852448, 'weight_lgbm_class_1': 0.7664059902558696, 'weight_lgbm_class_2': 0.8005034968070046, 'weight_xgb_class_0': 0.021978148039971102, 'weight_xgb_class_1': 0.5157578613900001, 'weight_xgb_class_2': 0.47705784712395705, 'weight_cat_class_0': 0.0015477980666612984, 'weight_cat_class_1': 0.7931284702441015, 'weight_cat_class_2': 0.3955135751034705}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:07,142] Trial 921 finished with value: 0.9497222841987832 and parameters: {'weight_lgbm_class_0': 0.06649899029062575, 'weight_lgbm_class_1': 0.774202903885062, 'weight_lgbm_class_2': 0.8371339329079812, 'weight_xgb_class_0': 0.07100000510442878, 'weight_xgb_class_1': 0.1928318618103362, 'weight_xgb_class_2': 0.46103659438320943, 'weight_cat_class_0': 0.001888980384289753, 'weight_cat_class_1': 0.7707577169055072, 'weight_cat_class_2': 0.2019313327763482}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:07,143] Trial 922 finished with value: 0.9495577089943371 and parameters: {'weight_lgbm_class_0': 0.0847419694977925, 'weight_lgbm_class_1': 0.7347995502169209, 'weight_lgbm_class_2': 0.5947545364694957, 'weight_xgb_class_0': 0.06485214276440524, 'weight_xgb_class_1': 0.4972621024091365, 'weight_xgb_class_2': 0.46498123007205383, 'weight_cat_class_0': 0.017329045629016965, 'weight_cat_class_1': 0.7963615183836857, 'weight_cat_class_2': 0.6335811467000471}. Best is trial 846 with value: 0.9497767056991938.

Best trial: 928. Best value: 0.94978:  46%|█████████████████████████████████████████████████████████████▋                                                                       | 928/2000 [00:31<00:39, 26.92it/s]

[I 2026-07-03 10:23:07,153] Trial 923 finished with value: 0.9497381388084879 and parameters: {'weight_lgbm_class_0': 0.0621153982212804, 'weight_lgbm_class_1': 0.7259130681432882, 'weight_lgbm_class_2': 0.8795892822050673, 'weight_xgb_class_0': 0.0673503897895518, 'weight_xgb_class_1': 0.4069852069280808, 'weight_xgb_class_2': 0.4595883909749932, 'weight_cat_class_0': 0.014623167407449641, 'weight_cat_class_1': 0.8009953408043267, 'weight_cat_class_2': 0.318460534582405}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:07,185] Trial 924 finished with value: 0.9496605450127689 and parameters: {'weight_lgbm_class_0': 0.06006116693377895, 'weight_lgbm_class_1': 0.7206898152995533, 'weight_lgbm_class_2': 0.5886419007691431, 'weight_xgb_class_0': 0.06507463879520915, 'weight_xgb_class_1': 0.4497208077701231, 'weight_xgb_class_2': 0.4503082849466751, 'weight_cat_class_0': 0.0027510817044971575, 'weight_cat_class_1': 0.7960531535650204, 'weight_cat_class_2': 0.3227879711452769}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:07,206] Trial 925 finished with value: 0.9496657313340986 and parameters: {'weight_lgbm_class_0': 0.07261439967327665, 'weight_lgbm_class_1': 0.7163174437352796, 'weight_lgbm_class_2': 0.5904871075103999, 'weight_xgb_class_0': 0.06329874176210733, 'weight_xgb_class_1': 0.5405745972742197, 'weight_xgb_class_2': 0.44823394946509, 'weight_cat_class_0': 0.0006094842143358446, 'weight_cat_class_1': 0.8050208821344542, 'weight_cat_class_2': 0.35964955762749984}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:07,236] Trial 926 finished with value: 0.9497624810132189 and parameters: {'weight_lgbm_class_0': 0.06725875999186148, 'weight_lgbm_class_1': 0.7117067318344089, 'weight_lgbm_class_2': 0.8434199228441288, 'weight_xgb_class_0': 0.06836630002311729, 'weight_xgb_class_1': 0.5245943781118585, 'weight_xgb_class_2': 0.46789882608243355, 'weight_cat_class_0': 0.0029706231978110743, 'weight_cat_class_1': 0.8003192618127555, 'weight_cat_class_2': 0.34984438201855905}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:07,288] Trial 927 finished with value: 0.9497104024570445 and parameters: {'weight_lgbm_class_0': 0.0647229817160331, 'weight_lgbm_class_1': 0.7158129823396117, 'weight_lgbm_class_2': 0.8385333471181591, 'weight_xgb_class_0': 0.06665569860180122, 'weight_xgb_class_1': 0.5437502192611694, 'weight_xgb_class_2': 0.4487799983986909, 'weight_cat_class_0': 0.0001849015984370407, 'weight_cat_class_1': 0.7871230455062392, 'weight_cat_class_2': 0.36319573128629223}. Best is trial 846 with value: 0.9497767056991938.
[I 2026-07-03 10:23:07,302] Trial 928 finished with value: 0.9497802985501612 and parameters: {'weight_lgbm_class_0': 0.06973607538716145, 'weight_lgbm_class_1': 0.7146723473734121, 'weight_lgbm_class_2': 0.8467100779818046, 'weight_xgb_class_0': 0.00019009535649771626, 'weight_xgb_class_1': 0.49960636434262284, 'weight_xgb_class_2': 0.47024936409826434, 'weight_cat_class_0': 0.07530145262697151, 'weight_cat_class_1': 0.7648751404147452, 'weight_cat_class_2': 0.4528133435569439}. Best is trial 928 with value: 0.9497802985501612.

Best trial: 928. Best value: 0.94978:  47%|█████████████████████████████████████████████████████████████▉                                                                       | 932/2000 [00:31<00:48, 22.15it/s]

[I 2026-07-03 10:23:07,413] Trial 929 finished with value: 0.949299656466637 and parameters: {'weight_lgbm_class_0': 0.059807795729700505, 'weight_lgbm_class_1': 0.7743138579000105, 'weight_lgbm_class_2': 0.8811285969447397, 'weight_xgb_class_0': 0.06532824116626272, 'weight_xgb_class_1': 0.5213896990885262, 'weight_xgb_class_2': 0.4620766216790515, 'weight_cat_class_0': 0.07788218792195117, 'weight_cat_class_1': 0.7702401648834666, 'weight_cat_class_2': 0.41429213067784293}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:07,496] Trial 930 finished with value: 0.9493081234655714 and parameters: {'weight_lgbm_class_0': 0.06178864279444175, 'weight_lgbm_class_1': 0.7800323260835951, 'weight_lgbm_class_2': 0.8937260785617094, 'weight_xgb_class_0': 0.05952876399464238, 'weight_xgb_class_1': 0.44964299250543566, 'weight_xgb_class_2': 0.47990022412271865, 'weight_cat_class_0': 0.07819888382128201, 'weight_cat_class_1': 0.7773388142437951, 'weight_cat_class_2': 0.45928474691430315}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:07,516] Trial 931 finished with value: 0.9497367629806946 and parameters: {'weight_lgbm_class_0': 0.060838422865087186, 'weight_lgbm_class_1': 0.7065891519162503, 'weight_lgbm_class_2': 0.8999914197669584, 'weight_xgb_class_0': 0.000148226274844214, 'weight_xgb_class_1': 0.551207531787986, 'weight_xgb_class_2': 0.47485670498304505, 'weight_cat_class_0': 0.08029431725756732, 'weight_cat_class_1': 0.7608602583699717, 'weight_cat_class_2': 0.22448208504888473}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:07,545] Trial 932 finished with value: 0.9492969919993338 and parameters: {'weight_lgbm_class_0': 0.06284521515898213, 'weight_lgbm_class_1': 0.7065678582958176, 'weight_lgbm_class_2': 0.9246523215316197, 'weight_xgb_class_0': 0.0646312412618904, 'weight_xgb_class_1': 0.568910663062147, 'weight_xgb_class_2': 0.4786561969065057, 'weight_cat_class_0': 0.07658850793274584, 'weight_cat_class_1': 0.7635072211710742, 'weight_cat_class_2': 0.42172175128451517}. Best is trial 928 with value: 0.9497802985501612.

Best trial: 928. Best value: 0.94978:  47%|██████████████████████████████████████████████████████████████▌                                                                      | 940/2000 [00:32<00:44, 24.09it/s]

[I 2026-07-03 10:23:07,664] Trial 933 finished with value: 0.9497493180155064 and parameters: {'weight_lgbm_class_0': 0.05961960617108815, 'weight_lgbm_class_1': 0.688204614103335, 'weight_lgbm_class_2': 0.895847435442203, 'weight_xgb_class_0': 0.07076512685882547, 'weight_xgb_class_1': 0.5456323243436967, 'weight_xgb_class_2': 0.41378029271688, 'weight_cat_class_0': 0.0012171150338753864, 'weight_cat_class_1': 0.7643679077825762, 'weight_cat_class_2': 0.26363579176052165}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:07,681] Trial 934 finished with value: 0.9497303036841034 and parameters: {'weight_lgbm_class_0': 0.05910995543090967, 'weight_lgbm_class_1': 0.7071475247139891, 'weight_lgbm_class_2': 0.883411803278054, 'weight_xgb_class_0': 0.07174196675001604, 'weight_xgb_class_1': 0.5415842167391662, 'weight_xgb_class_2': 0.4191607126458936, 'weight_cat_class_0': 0.001436635720175045, 'weight_cat_class_1': 0.7662913456278971, 'weight_cat_class_2': 0.3575686455974675}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:07,715] Trial 935 finished with value: 0.9490305328169706 and parameters: {'weight_lgbm_class_0': 0.06540139301823437, 'weight_lgbm_class_1': 0.6879124150123251, 'weight_lgbm_class_2': 0.8737598258561776, 'weight_xgb_class_0': 0.07175862696178503, 'weight_xgb_class_1': 0.4615033620491679, 'weight_xgb_class_2': 0.42232756220944184, 'weight_cat_class_0': 0.07661924584412996, 'weight_cat_class_1': 0.7148308373621974, 'weight_cat_class_2': 0.35697882563508565}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:07,747] Trial 937 finished with value: 0.9209956348703834 and parameters: {'weight_lgbm_class_0': 0.8121518503617333, 'weight_lgbm_class_1': 0.6897494808772695, 'weight_lgbm_class_2': 0.8223302792452293, 'weight_xgb_class_0': 0.06875374461151149, 'weight_xgb_class_1': 0.571118297673046, 'weight_xgb_class_2': 0.4214741498407756, 'weight_cat_class_0': 0.0012089300602433622, 'weight_cat_class_1': 0.7675514133666888, 'weight_cat_class_2': 0.39493982139043904}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:07,747] Trial 936 finished with value: 0.9497388352188302 and parameters: {'weight_lgbm_class_0': 0.059769283793390415, 'weight_lgbm_class_1': 0.6996175925668497, 'weight_lgbm_class_2': 0.9289385317545872, 'weight_xgb_class_0': 0.07585860831081742, 'weight_xgb_class_1': 0.453565753067772, 'weight_xgb_class_2': 0.40703083491390185, 'weight_cat_class_0': 0.0007334224491576218, 'weight_cat_class_1': 0.7545322940976215, 'weight_cat_class_2': 0.19477465042594577}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:07,773] Trial 938 finished with value: 0.9497279152041599 and parameters: {'weight_lgbm_class_0': 0.06655342315951099, 'weight_lgbm_class_1': 0.6831134980912063, 'weight_lgbm_class_2': 0.9009995133852142, 'weight_xgb_class_0': 0.07629042697319573, 'weight_xgb_class_1': 0.5244407588044779, 'weight_xgb_class_2': 0.3998803929256514, 'weight_cat_class_0': 0.0023818618060932237, 'weight_cat_class_1': 0.7644916083697577, 'weight_cat_class_2': 0.35518503637272336}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:07,820] Trial 939 finished with value: 0.9491098806351354 and parameters: {'weight_lgbm_class_0': 0.06260779602707885, 'weight_lgbm_class_1': 0.6961668242540477, 'weight_lgbm_class_2': 0.8826515700850648, 'weight_xgb_class_0': 0.07062532860681991, 'weight_xgb_class_1': 0.5267878135694796, 'weight_xgb_class_2': 0.4189016174429119, 'weight_cat_class_0': 0.07893489605079745, 'weight_cat_class_1': 0.766878757775517, 'weight_cat_class_2': 0.37385321596377225}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:07,821] Trial 940 finished with value: 0.9483181545020519 and parameters: {'weight_lgbm_class_0': 0.059270654792703124, 'weight_lgbm_class_1': 0.666921167457846, 'weight_lgbm_class_2': 0.885220127215403, 'weight_xgb_class_0': 0.07273431449544922, 'weight_xgb_class_1': 0.4961968853380408, 'weight_xgb_class_2': 0.43818072612187114, 'weight_cat_class_0': 0.1341042039560696, 'weight_cat_class_1': 0.7628496267673031, 'weight_cat_class_2': 0.3888596034191364}. Best is trial 928 with value: 0.9497802985501612.

Best trial: 928. Best value: 0.94978:  47%|██████████████████████████████████████████████████████████████▋                                                                      | 943/2000 [00:32<00:44, 23.60it/s]

[I 2026-07-03 10:23:07,876] Trial 941 finished with value: 0.9490551738386862 and parameters: {'weight_lgbm_class_0': 0.05890143853922366, 'weight_lgbm_class_1': 0.7029852629920671, 'weight_lgbm_class_2': 0.895482085976919, 'weight_xgb_class_0': 0.0739330900380159, 'weight_xgb_class_1': 0.5236734837699525, 'weight_xgb_class_2': 0.4072766659665965, 'weight_cat_class_0': 0.08921360608624554, 'weight_cat_class_1': 0.7555752460061423, 'weight_cat_class_2': 0.4223977290456993}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:07,997] Trial 942 finished with value: 0.9296558794308475 and parameters: {'weight_lgbm_class_0': 0.057996381178827695, 'weight_lgbm_class_1': 0.6797452354325094, 'weight_lgbm_class_2': 0.8614043732934183, 'weight_xgb_class_0': 0.5189660899704566, 'weight_xgb_class_1': 0.54845065331682, 'weight_xgb_class_2': 0.4267030554459925, 'weight_cat_class_0': 0.10628995514477632, 'weight_cat_class_1': 0.7247521967447048, 'weight_cat_class_2': 0.3313687563232654}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,027] Trial 943 finished with value: 0.9473020974941236 and parameters: {'weight_lgbm_class_0': 0.05978993379210517, 'weight_lgbm_class_1': 0.6935288051090726, 'weight_lgbm_class_2': 0.8793438104931337, 'weight_xgb_class_0': 0.08268667783686665, 'weight_xgb_class_1': 0.5354674298213368, 'weight_xgb_class_2': 0.4262113356353208, 'weight_cat_class_0': 0.1395371642598753, 'weight_cat_class_1': 0.7076504299132159, 'weight_cat_class_2': 0.21915678657776402}. Best is trial 928 with value: 0.9497802985501612.

[I 2026-07-03 10:23:08,090] Trial 944 finished with value: 0.9485839576849093 and parameters: {'weight_lgbm_class_0': 0.05924423554130421, 'weight_lgbm_class_1': 0.6859127486624358, 'weight_lgbm_class_2': 0.898324740704524, 'weight_xgb_class_0': 0.07421186685151325, 'weight_xgb_class_1': 0.5557923598304507, 'weight_xgb_class_2': 0.42696486511572296, 'weight_cat_class_0': 0.0993479149830378, 'weight_cat_class_1': 0.7552640887691515, 'weight_cat_class_2': 0.21238484350888917}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,185] Trial 945 finished with value: 0.9482935392061518 and parameters: {'weight_lgbm_class_0': 0.06226276870078283, 'weight_lgbm_class_1': 0.6535377678702677, 'weight_lgbm_class_2': 0.9082724063465983, 'weight_xgb_class_0': 0.08057593709914504, 'weight_xgb_class_1': 0.5456153387351195, 'weight_xgb_class_2': 0.4019809631032523, 'weight_cat_class_0': 0.1076276201645468, 'weight_cat_class_1': 0.7480594423354898, 'weight_cat_class_2': 0.2365526008557447}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,188] Trial 946 finished with value: 0.9483301817740037 and parameters: {'weight_lgbm_class_0': 0.05811389226452362, 'weight_lgbm_class_1': 0.6756771458346952, 'weight_lgbm_class_2': 0.9107198149933695, 'weight_xgb_class_0': 0.08149401414387039, 'weight_xgb_class_1': 0.5404171059456448, 'weight_xgb_class_2': 0.3990591295029512, 'weight_cat_class_0': 0.10618010052327423, 'weight_cat_class_1': 0.7511362608832166, 'weight_cat_class_2': 0.21230141048018863}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,205] Trial 947 finished with value: 0.9493478101552775 and parameters: {'weight_lgbm_class_0': 0.056267259682174324, 'weight_lgbm_class_1': 0.6709818285420851, 'weight_lgbm_class_2': 0.8863505814848958, 'weight_xgb_class_0': 0.08760210821109077, 'weight_xgb_class_1': 0.5324085324770103, 'weight_xgb_class_2': 0.39906071032586315, 'weight_cat_class_0': 0.0316947151097353, 'weight_cat_class_1': 0.7497339272798262, 'weight_cat_class_2': 0.23331138061783097}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,257] Trial 948 finished with value: 0.9477747260444245 and parameters: {'weight_lgbm_class_0': 0.05856513330777549, 'weight_lgbm_class_1': 0.656529489410544, 'weight_lgbm_class_2': 0.9254360197185757, 'weight_xgb_class_0': 0.07925652175402828, 'weight_xgb_class_1': 0.5379559470303713, 'weight_xgb_class_2': 0.4095631822063918, 'weight_cat_class_0': 0.12763774932361793, 'weight_cat_class_1': 0.7141381947560946, 'weight_cat_class_2': 0.19029071012000714}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,297] Trial 949 finished with value: 0.9477235220888058 and parameters: {'weight_lgbm_class_0': 0.06406948274599415, 'weight_lgbm_class_1': 0.6605166129774451, 'weight_lgbm_class_2': 0.9377268857912301, 'weight_xgb_class_0': 0.0891153748858044, 'weight_xgb_class_1': 0.5360054957225754, 'weight_xgb_class_2': 0.3725094166012841, 'weight_cat_class_0': 0.11491724100141759, 'weight_cat_class_1': 0.7456128527516289, 'weight_cat_class_2': 0.2124832982352523}. Best is trial 928 with value: 0.9497802985501612.

Best trial: 928. Best value: 0.94978:  48%|███████████████████████████████████████████████████████████████▌                                                                     | 956/2000 [00:32<00:42, 24.52it/s]

[I 2026-07-03 10:23:08,339] Trial 950 finished with value: 0.9479700062816899 and parameters: {'weight_lgbm_class_0': 0.05937547155707546, 'weight_lgbm_class_1': 0.6801842703085752, 'weight_lgbm_class_2': 0.9362307660804725, 'weight_xgb_class_0': 0.08411110614287858, 'weight_xgb_class_1': 0.5487381489955201, 'weight_xgb_class_2': 0.36242936628182937, 'weight_cat_class_0': 0.11876942900478495, 'weight_cat_class_1': 0.7281164964998115, 'weight_cat_class_2': 0.2120997903638542}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,357] Trial 952 finished with value: 0.9476000929869418 and parameters: {'weight_lgbm_class_0': 0.05779446057879123, 'weight_lgbm_class_1': 0.6913715618618231, 'weight_lgbm_class_2': 0.9333891154841767, 'weight_xgb_class_0': 0.08563577965657618, 'weight_xgb_class_1': 0.5458986725543942, 'weight_xgb_class_2': 0.3740208397051201, 'weight_cat_class_0': 0.13386585517499303, 'weight_cat_class_1': 0.7372995664371591, 'weight_cat_class_2': 0.234900086822761}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,360] Trial 951 finished with value: 0.9476117870859658 and parameters: {'weight_lgbm_class_0': 0.05972705951125613, 'weight_lgbm_class_1': 0.6640853850070011, 'weight_lgbm_class_2': 0.941222925696165, 'weight_xgb_class_0': 0.08425185060771885, 'weight_xgb_class_1': 0.5471829014823953, 'weight_xgb_class_2': 0.38375399178974834, 'weight_cat_class_0': 0.12773046230933272, 'weight_cat_class_1': 0.7119433401273842, 'weight_cat_class_2': 0.2061156589598186}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,374] Trial 953 finished with value: 0.9333944844654777 and parameters: {'weight_lgbm_class_0': 0.055011630990181096, 'weight_lgbm_class_1': 0.6679067677089592, 'weight_lgbm_class_2': 0.9357106186553661, 'weight_xgb_class_0': 0.5337826215329164, 'weight_xgb_class_1': 0.5505504173331043, 'weight_xgb_class_2': 0.3769206652113304, 'weight_cat_class_0': 0.0014016172802239213, 'weight_cat_class_1': 0.7512199186996809, 'weight_cat_class_2': 0.22011825047495928}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,503] Trial 954 finished with value: 0.9469970304677754 and parameters: {'weight_lgbm_class_0': 0.05800239281207244, 'weight_lgbm_class_1': 0.6415421443680485, 'weight_lgbm_class_2': 0.9365401466932659, 'weight_xgb_class_0': 0.0731198051736707, 'weight_xgb_class_1': 0.4941929831293993, 'weight_xgb_class_2': 0.3763599056632527, 'weight_cat_class_0': 0.1563661912241852, 'weight_cat_class_1': 0.7409343382298843, 'weight_cat_class_2': 0.18545918170845127}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,542] Trial 955 finished with value: 0.9485438375575441 and parameters: {'weight_lgbm_class_0': 0.052632688071861486, 'weight_lgbm_class_1': 0.658802958137654, 'weight_lgbm_class_2': 0.9397108903061062, 'weight_xgb_class_0': 0.08316299487190351, 'weight_xgb_class_1': 0.5637931942397602, 'weight_xgb_class_2': 0.41724582025387374, 'weight_cat_class_0': 0.10207140984861271, 'weight_cat_class_1': 0.710783888626739, 'weight_cat_class_2': 0.19556074051507732}. Best is trial 928 with value: 0.9497802985501612.

Best trial: 928. Best value: 0.94978:  48%|███████████████████████████████████████████████████████████████▊                                                                     | 960/2000 [00:32<00:50, 20.53it/s]

[I 2026-07-03 10:23:08,586] Trial 956 finished with value: 0.9497343171429011 and parameters: {'weight_lgbm_class_0': 0.05820719396502195, 'weight_lgbm_class_1': 0.6666697732531521, 'weight_lgbm_class_2': 0.9223092917210898, 'weight_xgb_class_0': 0.08457111870334702, 'weight_xgb_class_1': 0.4955635317802105, 'weight_xgb_class_2': 0.3753026234170911, 'weight_cat_class_0': 0.00015520965623712704, 'weight_cat_class_1': 0.7384433610537465, 'weight_cat_class_2': 0.1944620670576525}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,728] Trial 957 finished with value: 0.949548311571233 and parameters: {'weight_lgbm_class_0': 0.052622291276441385, 'weight_lgbm_class_1': 0.718482379677007, 'weight_lgbm_class_2': 0.9304058768000557, 'weight_xgb_class_0': 0.07934798886829378, 'weight_xgb_class_1': 0.4990642020072357, 'weight_xgb_class_2': 0.3714869482891783, 'weight_cat_class_0': 0.02825176974736775, 'weight_cat_class_1': 0.7338138450791292, 'weight_cat_class_2': 0.19451215333610528}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,735] Trial 958 finished with value: 0.9496776998119087 and parameters: {'weight_lgbm_class_0': 0.05525272268546228, 'weight_lgbm_class_1': 0.6378586714814358, 'weight_lgbm_class_2': 0.9515395184666025, 'weight_xgb_class_0': 0.08851191566266822, 'weight_xgb_class_1': 0.5022545886040225, 'weight_xgb_class_2': 0.3700932176816053, 'weight_cat_class_0': 0.0025058383770190486, 'weight_cat_class_1': 0.7191231628637933, 'weight_cat_class_2': 0.34486105446834137}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,740] Trial 959 finished with value: 0.9461238691537245 and parameters: {'weight_lgbm_class_0': 0.052324812203249554, 'weight_lgbm_class_1': 0.70204839168315, 'weight_lgbm_class_2': 0.9448631907125641, 'weight_xgb_class_0': 0.08952971856364851, 'weight_xgb_class_1': 0.5034974502911573, 'weight_xgb_class_2': 0.37618784113249415, 'weight_cat_class_0': 0.18166327697538875, 'weight_cat_class_1': 0.731260378723884, 'weight_cat_class_2': 0.17554245956191117}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,755] Trial 960 finished with value: 0.9497224585802027 and parameters: {'weight_lgbm_class_0': 0.05710647194413643, 'weight_lgbm_class_1': 0.7206692115119258, 'weight_lgbm_class_2': 0.9240492287677851, 'weight_xgb_class_0': 0.0895585936795207, 'weight_xgb_class_1': 0.5913422825225018, 'weight_xgb_class_2': 0.3773564397206815, 'weight_cat_class_0': 0.001203130097673106, 'weight_cat_class_1': 0.7277278144856701, 'weight_cat_class_2': 0.3300042057592196}. Best is trial 928 with value: 0.9497802985501612.

Best trial: 928. Best value: 0.94978:  48%|████████████████████████████████████████████████████████████████▎                                                                    | 967/2000 [00:33<00:39, 25.90it/s]

[I 2026-07-03 10:23:08,830] Trial 961 finished with value: 0.9466503792777319 and parameters: {'weight_lgbm_class_0': 0.05318304502342374, 'weight_lgbm_class_1': 0.7246598608461489, 'weight_lgbm_class_2': 0.9344168525999343, 'weight_xgb_class_0': 0.07871613522802448, 'weight_xgb_class_1': 0.5018559004895565, 'weight_xgb_class_2': 0.37048408179733244, 'weight_cat_class_0': 0.17405496487420746, 'weight_cat_class_1': 0.7418145074002594, 'weight_cat_class_2': 0.16239465047371773}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,834] Trial 962 finished with value: 0.9112710810410457 and parameters: {'weight_lgbm_class_0': 0.08349817087219112, 'weight_lgbm_class_1': 0.7097410020743138, 'weight_lgbm_class_2': 0.9728460240756855, 'weight_xgb_class_0': 0.07069213241854015, 'weight_xgb_class_1': 0.487881606528307, 'weight_xgb_class_2': 0.3956012170349071, 'weight_cat_class_0': 0.9117462213178782, 'weight_cat_class_1': 0.7439273086057945, 'weight_cat_class_2': 0.3477221427595939}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,884] Trial 963 finished with value: 0.9493133720071096 and parameters: {'weight_lgbm_class_0': 0.08114645970508313, 'weight_lgbm_class_1': 0.714666063379477, 'weight_lgbm_class_2': 0.9559689649910247, 'weight_xgb_class_0': 0.07139945984436394, 'weight_xgb_class_1': 0.5067243644486059, 'weight_xgb_class_2': 0.3629746105099815, 'weight_cat_class_0': 0.027885413308229468, 'weight_cat_class_1': 0.7681163808209884, 'weight_cat_class_2': 0.17971052946030974}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,936] Trial 964 finished with value: 0.9183099627690806 and parameters: {'weight_lgbm_class_0': 0.07997068550171067, 'weight_lgbm_class_1': 0.7131705667705087, 'weight_lgbm_class_2': 0.9703689639165183, 'weight_xgb_class_0': 0.06720060380268347, 'weight_xgb_class_1': 0.501422018604072, 'weight_xgb_class_2': 0.3519812119190077, 'weight_cat_class_0': 0.725586017150062, 'weight_cat_class_1': 0.7714062116366553, 'weight_cat_class_2': 0.16804504999562}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,938] Trial 965 finished with value: 0.9308505156148286 and parameters: {'weight_lgbm_class_0': 0.5803321209694428, 'weight_lgbm_class_1': 0.7144783306401232, 'weight_lgbm_class_2': 0.9704972661140132, 'weight_xgb_class_0': 0.0711015532950111, 'weight_xgb_class_1': 0.5038313146430272, 'weight_xgb_class_2': 0.39294289497312096, 'weight_cat_class_0': 0.0015174131961026988, 'weight_cat_class_1': 0.715290622371327, 'weight_cat_class_2': 0.17941555618401125}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:08,983] Trial 966 finished with value: 0.9497240726751165 and parameters: {'weight_lgbm_class_0': 0.08111512000769669, 'weight_lgbm_class_1': 0.7145430307759518, 'weight_lgbm_class_2': 0.8595480852857954, 'weight_xgb_class_0': 0.07168054049686362, 'weight_xgb_class_1': 0.4895077064169406, 'weight_xgb_class_2': 0.400259663653924, 'weight_cat_class_0': 0.00042287318925521636, 'weight_cat_class_1': 0.7678268774051277, 'weight_cat_class_2': 0.3293503899598939}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,029] Trial 967 finished with value: 0.9493485384365591 and parameters: {'weight_lgbm_class_0': 0.08248743243534593, 'weight_lgbm_class_1': 0.7241287371675499, 'weight_lgbm_class_2': 0.8460118295415715, 'weight_xgb_class_0': 0.06852332124706569, 'weight_xgb_class_1': 0.5825287942882197, 'weight_xgb_class_2': 0.39783285439386323, 'weight_cat_class_0': 0.030861621783103012, 'weight_cat_class_1': 0.7701056917108021, 'weight_cat_class_2': 0.33883703127880743}. Best is trial 928 with value: 0.9497802985501612.

[I 2026-07-03 10:23:09,132] Trial 968 finished with value: 0.949734775594513 and parameters: {'weight_lgbm_class_0': 0.08036193476610722, 'weight_lgbm_class_1': 0.7113612091823462, 'weight_lgbm_class_2': 0.9601086495555244, 'weight_xgb_class_0': 0.06684752213034267, 'weight_xgb_class_1': 0.5054695439692495, 'weight_xgb_class_2': 0.3902900270193134, 'weight_cat_class_0': 0.00030368879889481877, 'weight_cat_class_1': 0.7235659478165342, 'weight_cat_class_2': 0.1681010397736709}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,227] Trial 969 finished with value: 0.9492948250658363 and parameters: {'weight_lgbm_class_0': 0.08636389844932736, 'weight_lgbm_class_1': 0.715913286320651, 'weight_lgbm_class_2': 0.9697408046453044, 'weight_xgb_class_0': 0.06598366684508652, 'weight_xgb_class_1': 0.5962612358819985, 'weight_xgb_class_2': 0.382954285375979, 'weight_cat_class_0': 0.028841506251263756, 'weight_cat_class_1': 0.6978653290414715, 'weight_cat_class_2': 0.1499437471368542}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,308] Trial 971 finished with value: 0.9495445331542293 and parameters: {'weight_lgbm_class_0': 0.08218783395607757, 'weight_lgbm_class_1': 0.7182153672196487, 'weight_lgbm_class_2': 0.9706657201353419, 'weight_xgb_class_0': 0.065560072810499, 'weight_xgb_class_1': 0.47141272012270774, 'weight_xgb_class_2': 0.3909391428033534, 'weight_cat_class_0': 0.03100692662242479, 'weight_cat_class_1': 0.7645475230023435, 'weight_cat_class_2': 0.37469948696123045}. Best is trial 928 with value: 0.9497802985501612.

Best trial: 928. Best value: 0.94978:  49%|█████████████████████████████████████████████████████████████████                                                                    | 979/2000 [00:33<00:38, 26.49it/s]

[I 2026-07-03 10:23:09,332] Trial 970 finished with value: 0.9058074818409102 and parameters: {'weight_lgbm_class_0': 0.08476169298109286, 'weight_lgbm_class_1': 0.7160325981589838, 'weight_lgbm_class_2': 0.9627227500392606, 'weight_xgb_class_0': 0.9939202400762713, 'weight_xgb_class_1': 0.4775071694022137, 'weight_xgb_class_2': 0.3472259838273723, 'weight_cat_class_0': 0.03391970366571664, 'weight_cat_class_1': 0.7603102732965094, 'weight_cat_class_2': 0.2998663685701337}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,333] Trial 972 finished with value: 0.9275866856165789 and parameters: {'weight_lgbm_class_0': 0.6351081645064787, 'weight_lgbm_class_1': 0.7003287907936054, 'weight_lgbm_class_2': 0.90805746495992, 'weight_xgb_class_0': 0.0633988636411448, 'weight_xgb_class_1': 0.46657904928394833, 'weight_xgb_class_2': 0.39764538802890204, 'weight_cat_class_0': 0.030568540345647873, 'weight_cat_class_1': 0.7663736281340208, 'weight_cat_class_2': 0.2970114838147751}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,339] Trial 973 finished with value: 0.9494433860877217 and parameters: {'weight_lgbm_class_0': 0.08624913835294155, 'weight_lgbm_class_1': 0.701839635146749, 'weight_lgbm_class_2': 0.9137324167718857, 'weight_xgb_class_0': 0.06043623847092633, 'weight_xgb_class_1': 0.45610982337524675, 'weight_xgb_class_2': 0.39448347976627646, 'weight_cat_class_0': 0.032376645949021746, 'weight_cat_class_1': 0.7766353204046579, 'weight_cat_class_2': 0.2970621597402536}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,387] Trial 974 finished with value: 0.949452566045391 and parameters: {'weight_lgbm_class_0': 0.08377154678450606, 'weight_lgbm_class_1': 0.6990791135177163, 'weight_lgbm_class_2': 0.8925969594520903, 'weight_xgb_class_0': 0.05529475674963299, 'weight_xgb_class_1': 0.4636147019861926, 'weight_xgb_class_2': 0.42737918932619434, 'weight_cat_class_0': 0.035213533568140484, 'weight_cat_class_1': 0.7710425168714241, 'weight_cat_class_2': 0.29164571057769734}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,423] Trial 975 finished with value: 0.940771598257995 and parameters: {'weight_lgbm_class_0': 0.08681944560271476, 'weight_lgbm_class_1': 0.7027381239809788, 'weight_lgbm_class_2': 0.9116814585901601, 'weight_xgb_class_0': 0.39160802938472217, 'weight_xgb_class_1': 0.5696725635810662, 'weight_xgb_class_2': 0.39681678686973804, 'weight_cat_class_0': 0.000848032204209636, 'weight_cat_class_1': 0.6972389041925086, 'weight_cat_class_2': 0.3738507109425691}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,445] Trial 976 finished with value: 0.9497291802611564 and parameters: {'weight_lgbm_class_0': 0.07980091098407456, 'weight_lgbm_class_1': 0.6914997863388265, 'weight_lgbm_class_2': 0.9046077852534171, 'weight_xgb_class_0': 0.06087413924870894, 'weight_xgb_class_1': 0.5799938273209293, 'weight_xgb_class_2': 0.3417544505844373, 'weight_cat_class_0': 0.0004756756280700769, 'weight_cat_class_1': 0.6848728719834952, 'weight_cat_class_2': 0.3108608337692749}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,451] Trial 977 finished with value: 0.9496876276266989 and parameters: {'weight_lgbm_class_0': 0.08499133815022185, 'weight_lgbm_class_1': 0.625148035470894, 'weight_lgbm_class_2': 0.9009348535344021, 'weight_xgb_class_0': 0.05428413607412294, 'weight_xgb_class_1': 0.4598862894798962, 'weight_xgb_class_2': 0.3380002474546926, 'weight_cat_class_0': 0.000537381283331779, 'weight_cat_class_1': 0.6995305894289047, 'weight_cat_class_2': 0.3041734016935081}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,508] Trial 979 finished with value: 0.9497015278442108 and parameters: {'weight_lgbm_class_0': 0.09221451343480114, 'weight_lgbm_class_1': 0.6913806078207588, 'weight_lgbm_class_2': 0.9053283774094554, 'weight_xgb_class_0': 0.05674425096533082, 'weight_xgb_class_1': 0.46439476806333774, 'weight_xgb_class_2': 0.40847963593295666, 'weight_cat_class_0': 0.0007175998174275833, 'weight_cat_class_1': 0.7581532716684368, 'weight_cat_class_2': 0.30383287465133907}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,509] Trial 978 finished with value: 0.9496712617899609 and parameters: {'weight_lgbm_class_0': 0.08693989782731648, 'weight_lgbm_class_1': 0.6266106039731055, 'weight_lgbm_class_2': 0.9046500176907496, 'weight_xgb_class_0': 0.05465244922986876, 'weight_xgb_class_1': 0.47011882918557474, 'weight_xgb_class_2': 0.39760482915471784, 'weight_cat_class_0': 0.0013606921561569027, 'weight_cat_class_1': 0.6995673396248471, 'weight_cat_class_2': 0.3691766380258076}. Best is trial 928 with value: 0.9497802985501612.

Best trial: 928. Best value: 0.94978:  49%|█████████████████████████████████████████████████████████████████▎                                                                   | 982/2000 [00:33<00:44, 22.95it/s]

[I 2026-07-03 10:23:09,639] Trial 980 finished with value: 0.9494832836817001 and parameters: {'weight_lgbm_class_0': 0.08620327045626702, 'weight_lgbm_class_1': 0.6250029038919231, 'weight_lgbm_class_2': 0.913724079628411, 'weight_xgb_class_0': 0.05981382591115212, 'weight_xgb_class_1': 0.4795873075062803, 'weight_xgb_class_2': 0.3387853229271278, 'weight_cat_class_0': 0.018789311030732163, 'weight_cat_class_1': 0.6966471567256542, 'weight_cat_class_2': 0.28949626293163355}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,688] Trial 981 finished with value: 0.949642132391494 and parameters: {'weight_lgbm_class_0': 0.08255927345492986, 'weight_lgbm_class_1': 0.6893776446343814, 'weight_lgbm_class_2': 0.9081779116972393, 'weight_xgb_class_0': 0.05181548423220498, 'weight_xgb_class_1': 0.45573349865407103, 'weight_xgb_class_2': 0.33575416045635564, 'weight_cat_class_0': 0.019275019423274944, 'weight_cat_class_1': 0.7143564334036613, 'weight_cat_class_2': 0.3797083328029864}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,818] Trial 982 finished with value: 0.9495429838624728 and parameters: {'weight_lgbm_class_0': 0.0911339128998635, 'weight_lgbm_class_1': 0.6720728686616869, 'weight_lgbm_class_2': 0.9111009887523153, 'weight_xgb_class_0': 0.05280459862011806, 'weight_xgb_class_1': 0.45571438937790243, 'weight_xgb_class_2': 0.34775491948098086, 'weight_cat_class_0': 0.0177471682504868, 'weight_cat_class_1': 0.7223301809191807, 'weight_cat_class_2': 0.266029502439401}. Best is trial 928 with value: 0.9497802985501612.

[I 2026-07-03 10:23:09,861] Trial 983 finished with value: 0.9489058912612499 and parameters: {'weight_lgbm_class_0': 0.08945425466883558, 'weight_lgbm_class_1': 0.6227189887277936, 'weight_lgbm_class_2': 0.9081291995942712, 'weight_xgb_class_0': 0.09356905445945599, 'weight_xgb_class_1': 0.5300586286710613, 'weight_xgb_class_2': 0.34185369541604427, 'weight_cat_class_0': 0.002044566773675375, 'weight_cat_class_1': 0.6926752357534484, 'weight_cat_class_2': 0.14807571239523698}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,895] Trial 984 finished with value: 0.9488464689312085 and parameters: {'weight_lgbm_class_0': 0.0913335885464058, 'weight_lgbm_class_1': 0.6245320796601882, 'weight_lgbm_class_2': 0.9026000909024228, 'weight_xgb_class_0': 0.09354332916382349, 'weight_xgb_class_1': 0.5117972951485895, 'weight_xgb_class_2': 0.3248853991701, 'weight_cat_class_0': 0.017040284699573766, 'weight_cat_class_1': 0.6898134926882273, 'weight_cat_class_2': 0.25699332612361114}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,917] Trial 985 finished with value: 0.9491818848440011 and parameters: {'weight_lgbm_class_0': 0.09209837597346608, 'weight_lgbm_class_1': 0.68450316123851, 'weight_lgbm_class_2': 0.9139806335023841, 'weight_xgb_class_0': 0.09614390116941685, 'weight_xgb_class_1': 0.5207295615349565, 'weight_xgb_class_2': 0.41739161385985607, 'weight_cat_class_0': 0.014519655471962043, 'weight_cat_class_1': 0.6764476573964754, 'weight_cat_class_2': 0.36125912890820033}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,939] Trial 986 finished with value: 0.9491125537325663 and parameters: {'weight_lgbm_class_0': 0.09333555897386231, 'weight_lgbm_class_1': 0.6692846073962081, 'weight_lgbm_class_2': 0.9181130362822547, 'weight_xgb_class_0': 0.0845138497498385, 'weight_xgb_class_1': 0.5218685199066535, 'weight_xgb_class_2': 0.32219755052744525, 'weight_cat_class_0': 0.00045429286683583425, 'weight_cat_class_1': 0.6450347386929407, 'weight_cat_class_2': 0.1529984102675334}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,964] Trial 987 finished with value: 0.9491402393490939 and parameters: {'weight_lgbm_class_0': 0.07028289040130775, 'weight_lgbm_class_1': 0.6837563744111304, 'weight_lgbm_class_2': 0.9002357880769503, 'weight_xgb_class_0': 0.08965110051906106, 'weight_xgb_class_1': 0.5149303276314605, 'weight_xgb_class_2': 0.3414648713995889, 'weight_cat_class_0': 0.015928368052037033, 'weight_cat_class_1': 0.7163871108590474, 'weight_cat_class_2': 0.12302430789370453}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:09,975] Trial 988 finished with value: 0.9493175367995424 and parameters: {'weight_lgbm_class_0': 0.09685661272440509, 'weight_lgbm_class_1': 0.6822796810181335, 'weight_lgbm_class_2': 0.9216787973010035, 'weight_xgb_class_0': 0.09238024650418157, 'weight_xgb_class_1': 0.5795597710967705, 'weight_xgb_class_2': 0.3530362743417004, 'weight_cat_class_0': 0.000473655241592149, 'weight_cat_class_1': 0.649448592211431, 'weight_cat_class_2': 0.3544607051394334}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:10,014] Trial 989 finished with value: 0.9489029344020166 and parameters: {'weight_lgbm_class_0': 0.09518869328669191, 'weight_lgbm_class_1': 0.6739311870972573, 'weight_lgbm_class_2': 0.9163953268343904, 'weight_xgb_class_0': 0.08507671430551014, 'weight_xgb_class_1': 0.5194191529194175, 'weight_xgb_class_2': 0.31672559664973177, 'weight_cat_class_0': 0.0183562652634527, 'weight_cat_class_1': 0.6662207549359137, 'weight_cat_class_2': 0.2603125529722745}. Best is trial 928 with value: 0.9497802985501612.

Best trial: 928. Best value: 0.94978:  50%|██████████████████████████████████████████████████████████████████                                                                   | 993/2000 [00:34<00:40, 24.75it/s]

[I 2026-07-03 10:23:10,058] Trial 991 finished with value: 0.9494706860358306 and parameters: {'weight_lgbm_class_0': 0.07052973023153475, 'weight_lgbm_class_1': 0.6776420781747317, 'weight_lgbm_class_2': 0.9163306319294304, 'weight_xgb_class_0': 0.08153655292886156, 'weight_xgb_class_1': 0.5193618292175686, 'weight_xgb_class_2': 0.34027412954585157, 'weight_cat_class_0': 0.01382182284499581, 'weight_cat_class_1': 0.6600560232472656, 'weight_cat_class_2': 0.25488249412467345}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:10,064] Trial 990 finished with value: 0.949279717354771 and parameters: {'weight_lgbm_class_0': 0.09997934794057602, 'weight_lgbm_class_1': 0.679754317165531, 'weight_lgbm_class_2': 0.9172592869284001, 'weight_xgb_class_0': 0.0922073381470952, 'weight_xgb_class_1': 0.6160074724864244, 'weight_xgb_class_2': 0.3321277523130565, 'weight_cat_class_0': 0.0004258416152921711, 'weight_cat_class_1': 0.6914923471362111, 'weight_cat_class_2': 0.35165932910381364}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:10,148] Trial 992 finished with value: 0.9493720318360346 and parameters: {'weight_lgbm_class_0': 0.07258941808956641, 'weight_lgbm_class_1': 0.6691128997768907, 'weight_lgbm_class_2': 0.8832125770738873, 'weight_xgb_class_0': 0.0914811160966624, 'weight_xgb_class_1': 0.5220119670489064, 'weight_xgb_class_2': 0.3103474059683115, 'weight_cat_class_0': 0.001115158694681695, 'weight_cat_class_1': 0.7188374046437171, 'weight_cat_class_2': 0.2562588018229463}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:10,217] Trial 993 finished with value: 0.9495989336266155 and parameters: {'weight_lgbm_class_0': 0.04927934821082938, 'weight_lgbm_class_1': 0.6797177483803435, 'weight_lgbm_class_2': 0.8765748736543689, 'weight_xgb_class_0': 0.08677192553423534, 'weight_xgb_class_1': 0.5141029651554364, 'weight_xgb_class_2': 0.3508924717183971, 'weight_cat_class_0': 0.017439262252492743, 'weight_cat_class_1': 0.6315785058827984, 'weight_cat_class_2': 0.27481315145709917}. Best is trial 928 with value: 0.9497802985501612.

Best trial: 928. Best value: 0.94978:  50%|██████████████████████████████████████████████████████████████████                                                                  | 1001/2000 [00:34<00:46, 21.59it/s]

[I 2026-07-03 10:23:10,337] Trial 995 finished with value: 0.9071249376373324 and parameters: {'weight_lgbm_class_0': 0.9740365260197181, 'weight_lgbm_class_1': 0.680007303319203, 'weight_lgbm_class_2': 0.8729815616546526, 'weight_xgb_class_0': 0.07863954210421911, 'weight_xgb_class_1': 0.5162302227430156, 'weight_xgb_class_2': 0.41381248850679, 'weight_cat_class_0': 0.0004632621750387542, 'weight_cat_class_1': 0.6753803648014758, 'weight_cat_class_2': 0.2569252147859766}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:10,369] Trial 994 finished with value: 0.9493653101550809 and parameters: {'weight_lgbm_class_0': 0.04685384633620089, 'weight_lgbm_class_1': 0.6548637839295239, 'weight_lgbm_class_2': 0.8812582914207133, 'weight_xgb_class_0': 0.09380179938907382, 'weight_xgb_class_1': 0.5200795706022023, 'weight_xgb_class_2': 0.3608743916258568, 'weight_cat_class_0': 0.01728278101282043, 'weight_cat_class_1': 0.6528892437415699, 'weight_cat_class_2': 0.14821684929164897}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:10,429] Trial 996 finished with value: 0.9496070288608044 and parameters: {'weight_lgbm_class_0': 0.06746517873838104, 'weight_lgbm_class_1': 0.6731684399957809, 'weight_lgbm_class_2': 0.8581304296992404, 'weight_xgb_class_0': 0.09073197926691481, 'weight_xgb_class_1': 0.5730543237110001, 'weight_xgb_class_2': 0.35428926583908, 'weight_cat_class_0': 0.0020190786738141023, 'weight_cat_class_1': 0.7192066817101462, 'weight_cat_class_2': 0.32156907127661655}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:10,445] Trial 997 finished with value: 0.9005081623640732 and parameters: {'weight_lgbm_class_0': 0.05032469531059389, 'weight_lgbm_class_1': 0.6486649679689876, 'weight_lgbm_class_2': 0.8745304687566892, 'weight_xgb_class_0': 0.4709588288008973, 'weight_xgb_class_1': 0.5205254949526311, 'weight_xgb_class_2': 0.4160542080167291, 'weight_cat_class_0': 0.5900065093571019, 'weight_cat_class_1': 0.6711240908277584, 'weight_cat_class_2': 0.12047976306585291}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:10,473] Trial 999 finished with value: 0.9496718784857862 and parameters: {'weight_lgbm_class_0': 0.04791011672562185, 'weight_lgbm_class_1': 0.6560865031098654, 'weight_lgbm_class_2': 0.9912042121691202, 'weight_xgb_class_0': 0.09403185641954473, 'weight_xgb_class_1': 0.6021561197341554, 'weight_xgb_class_2': 0.36511532320448514, 'weight_cat_class_0': 0.0174671507763139, 'weight_cat_class_1': 0.7368513802383158, 'weight_cat_class_2': 0.4069081203379797}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:10,476] Trial 998 finished with value: 0.9387390729429873 and parameters: {'weight_lgbm_class_0': 0.04703272806774629, 'weight_lgbm_class_1': 0.7338142533283497, 'weight_lgbm_class_2': 0.8750392266283434, 'weight_xgb_class_0': 0.4505055478132633, 'weight_xgb_class_1': 0.5719418400064148, 'weight_xgb_class_2': 0.35695351587348745, 'weight_cat_class_0': 0.0005600512472676545, 'weight_cat_class_1': 0.6757676589835786, 'weight_cat_class_2': 0.32264825350150694}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:10,513] Trial 1000 finished with value: 0.9496482039637332 and parameters: {'weight_lgbm_class_0': 0.04644758019805581, 'weight_lgbm_class_1': 0.6512856864507083, 'weight_lgbm_class_2': 0.8743885784072634, 'weight_xgb_class_0': 0.043279468803144094, 'weight_xgb_class_1': 0.5600946961792613, 'weight_xgb_class_2': 0.3683339800742265, 'weight_cat_class_0': 0.01823868926324402, 'weight_cat_class_1': 0.6702077347840323, 'weight_cat_class_2': 0.33193471964755555}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:10,527] Trial 1001 finished with value: 0.949577908475658 and parameters: {'weight_lgbm_class_0': 0.05712656876907178, 'weight_lgbm_class_1': 0.7341079491365521, 'weight_lgbm_class_2': 0.8788378405835349, 'weight_xgb_class_0': 0.04674037841755341, 'weight_xgb_class_1': 0.5771915936454725, 'weight_xgb_class_2': 0.3652852451186325, 'weight_cat_class_0': 0.0013806354147187804, 'weight_cat_class_1': 0.6780998835618413, 'weight_cat_class_2': 0.33062539179327344}. Best is trial 928 with value: 0.9497802985501612.

Best trial: 928. Best value: 0.94978:  50%|██████████████████████████████████████████████████████████████████▎                                                                 | 1005/2000 [00:34<00:37, 26.22it/s]

[I 2026-07-03 10:23:10,574] Trial 1002 finished with value: 0.9496357863714492 and parameters: {'weight_lgbm_class_0': 0.05099389896612853, 'weight_lgbm_class_1': 0.6456984873129364, 'weight_lgbm_class_2': 0.9944664606545537, 'weight_xgb_class_0': 0.04571277047535935, 'weight_xgb_class_1': 0.5707005087149822, 'weight_xgb_class_2': 0.4199229397917852, 'weight_cat_class_0': 0.016278766602348147, 'weight_cat_class_1': 0.6786687180115, 'weight_cat_class_2': 0.32558369063166065}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:10,603] Trial 1003 finished with value: 0.949576880357139 and parameters: {'weight_lgbm_class_0': 0.04349524558955255, 'weight_lgbm_class_1': 0.6546975636090001, 'weight_lgbm_class_2': 0.8820701936883254, 'weight_xgb_class_0': 0.04600368815938327, 'weight_xgb_class_1': 0.557439087309618, 'weight_xgb_class_2': 0.43575868515961375, 'weight_cat_class_0': 0.019131726894832203, 'weight_cat_class_1': 0.7275173384842646, 'weight_cat_class_2': 0.3917088895805204}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:10,654] Trial 1004 finished with value: 0.930420472497877 and parameters: {'weight_lgbm_class_0': 0.052697337432956, 'weight_lgbm_class_1': 0.7266129924867798, 'weight_lgbm_class_2': 0.873980998640228, 'weight_xgb_class_0': 0.049938846281462675, 'weight_xgb_class_1': 0.5640625548032037, 'weight_xgb_class_2': 0.35720205534423094, 'weight_cat_class_0': 0.6129633147109264, 'weight_cat_class_1': 0.7386816614178611, 'weight_cat_class_2': 0.4247324490127895}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:10,719] Trial 1005 finished with value: 0.9373172563363461 and parameters: {'weight_lgbm_class_0': 0.046325870765215806, 'weight_lgbm_class_1': 0.6980866767278674, 'weight_lgbm_class_2': 0.8663181777577976, 'weight_xgb_class_0': 0.4720967413907923, 'weight_xgb_class_1': 0.5628910795118186, 'weight_xgb_class_2': 0.42471025373717497, 'weight_cat_class_0': 0.021090987056001514, 'weight_cat_class_1': 0.7419240147226995, 'weight_cat_class_2': 0.32405489948631794}. Best is trial 928 with value: 0.9497802985501612.

Best trial: 928. Best value: 0.94978:  50%|██████████████████████████████████████████████████████████████████▋                                                                 | 1010/2000 [00:35<00:45, 21.75it/s]

[I 2026-07-03 10:23:10,849] Trial 1007 finished with value: 0.9273244415378116 and parameters: {'weight_lgbm_class_0': 0.04764843096405293, 'weight_lgbm_class_1': 0.7301833966999735, 'weight_lgbm_class_2': 0.9591681794248058, 'weight_xgb_class_0': 0.6998945434105164, 'weight_xgb_class_1': 0.5783786270052625, 'weight_xgb_class_2': 0.4375748718706031, 'weight_cat_class_0': 0.03389874229137667, 'weight_cat_class_1': 0.7464441642591774, 'weight_cat_class_2': 0.3999460496217352}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:10,857] Trial 1006 finished with value: 0.9384700244128434 and parameters: {'weight_lgbm_class_0': 0.04139065661987768, 'weight_lgbm_class_1': 0.7322964991969091, 'weight_lgbm_class_2': 0.8541515955846932, 'weight_xgb_class_0': 0.46843040648103396, 'weight_xgb_class_1': 0.5630396341073681, 'weight_xgb_class_2': 0.4356028884454896, 'weight_cat_class_0': 0.02929662124856318, 'weight_cat_class_1': 0.7457567484861627, 'weight_cat_class_2': 0.4143426404667482}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:10,939] Trial 1008 finished with value: 0.9497138332550041 and parameters: {'weight_lgbm_class_0': 0.04679912049920416, 'weight_lgbm_class_1': 0.7317964349218767, 'weight_lgbm_class_2': 0.9463980565062294, 'weight_xgb_class_0': 0.04489942076954979, 'weight_xgb_class_1': 0.5885341987480247, 'weight_xgb_class_2': 0.43330009702728406, 'weight_cat_class_0': 0.03305477327793193, 'weight_cat_class_1': 0.7416841268252194, 'weight_cat_class_2': 0.43070322003916567}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:10,951] Trial 1009 finished with value: 0.949780149141669 and parameters: {'weight_lgbm_class_0': 0.06544116852219856, 'weight_lgbm_class_1': 0.7376911592332648, 'weight_lgbm_class_2': 0.9604552691955369, 'weight_xgb_class_0': 0.044308953142615216, 'weight_xgb_class_1': 0.565765265547029, 'weight_xgb_class_2': 0.43957887223591086, 'weight_cat_class_0': 0.03682819663065328, 'weight_cat_class_1': 0.7310856805886446, 'weight_cat_class_2': 0.4270478901022802}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,026] Trial 1010 finished with value: 0.9495940360322438 and parameters: {'weight_lgbm_class_0': 0.06813554630275745, 'weight_lgbm_class_1': 0.7319953355192587, 'weight_lgbm_class_2': 0.7761950939217928, 'weight_xgb_class_0': 0.046762524956051876, 'weight_xgb_class_1': 0.43573022045960846, 'weight_xgb_class_2': 0.43652098373823317, 'weight_cat_class_0': 0.03459102107121832, 'weight_cat_class_1': 0.7483701983526727, 'weight_cat_class_2': 0.22781820272668624}. Best is trial 928 with value: 0.9497802985501612.

Best trial: 928. Best value: 0.94978:  51%|███████████████████████████████████████████████████████████████████▏                                                                | 1018/2000 [00:35<00:35, 27.56it/s]

[I 2026-07-03 10:23:11,037] Trial 1011 finished with value: 0.9496949585581707 and parameters: {'weight_lgbm_class_0': 0.06783296761992695, 'weight_lgbm_class_1': 0.7323693146750229, 'weight_lgbm_class_2': 0.8453610159346479, 'weight_xgb_class_0': 0.04757468657273159, 'weight_xgb_class_1': 0.48469173285268474, 'weight_xgb_class_2': 0.4319017970188537, 'weight_cat_class_0': 0.03537652465646498, 'weight_cat_class_1': 0.7421001905517193, 'weight_cat_class_2': 0.4324163500528473}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,065] Trial 1013 finished with value: 0.9493913177243704 and parameters: {'weight_lgbm_class_0': 0.11398526375085488, 'weight_lgbm_class_1': 0.7001956290748487, 'weight_lgbm_class_2': 0.9496216315923405, 'weight_xgb_class_0': 0.04623872278710559, 'weight_xgb_class_1': 0.4944774202017815, 'weight_xgb_class_2': 0.4377624482965996, 'weight_cat_class_0': 0.033738244043420344, 'weight_cat_class_1': 0.75025221505052, 'weight_cat_class_2': 0.4378722035302007}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,072] Trial 1012 finished with value: 0.9412848275793723 and parameters: {'weight_lgbm_class_0': 0.11125870729266643, 'weight_lgbm_class_1': 0.7345207538407512, 'weight_lgbm_class_2': 0.7784344450042368, 'weight_xgb_class_0': 0.3233138578167413, 'weight_xgb_class_1': 0.49028028236800075, 'weight_xgb_class_2': 0.43626902388123495, 'weight_cat_class_0': 0.03395230047712644, 'weight_cat_class_1': 0.7425902179854157, 'weight_cat_class_2': 0.4390424975016975}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,081] Trial 1014 finished with value: 0.9493175868148818 and parameters: {'weight_lgbm_class_0': 0.11232551195202103, 'weight_lgbm_class_1': 0.7028174635137958, 'weight_lgbm_class_2': 0.8607215208603706, 'weight_xgb_class_0': 0.04544727951659219, 'weight_xgb_class_1': 0.49810297688327704, 'weight_xgb_class_2': 0.4394368557503677, 'weight_cat_class_0': 0.03550362586622515, 'weight_cat_class_1': 0.7486876338657288, 'weight_cat_class_2': 0.43041153049611547}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,139] Trial 1015 finished with value: 0.9492505159134331 and parameters: {'weight_lgbm_class_0': 0.11462866686948703, 'weight_lgbm_class_1': 0.7376307707109971, 'weight_lgbm_class_2': 0.8243635790619701, 'weight_xgb_class_0': 0.04442598573996765, 'weight_xgb_class_1': 0.485299082856039, 'weight_xgb_class_2': 0.4369783082356324, 'weight_cat_class_0': 0.03837513453038155, 'weight_cat_class_1': 0.7473379973348122, 'weight_cat_class_2': 0.42766757653152915}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,176] Trial 1016 finished with value: 0.9422642468248886 and parameters: {'weight_lgbm_class_0': 0.0701055465642639, 'weight_lgbm_class_1': 0.7359453325336113, 'weight_lgbm_class_2': 0.8466354982097618, 'weight_xgb_class_0': 0.3183206905138074, 'weight_xgb_class_1': 0.4862342226305154, 'weight_xgb_class_2': 0.43410233388023833, 'weight_cat_class_0': 0.03554056524066049, 'weight_cat_class_1': 0.7479545672783172, 'weight_cat_class_2': 0.24033247123883397}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,192] Trial 1017 finished with value: 0.9492734562971908 and parameters: {'weight_lgbm_class_0': 0.11080313512644008, 'weight_lgbm_class_1': 0.7352581367158866, 'weight_lgbm_class_2': 0.9511673250882949, 'weight_xgb_class_0': 0.04355492704534157, 'weight_xgb_class_1': 0.4871834007288675, 'weight_xgb_class_2': 0.4294324691762797, 'weight_cat_class_0': 0.05250580107698681, 'weight_cat_class_1': 0.749533093285271, 'weight_cat_class_2': 0.3933246886733156}. Best is trial 928 with value: 0.9497802985501612.

[I 2026-07-03 10:23:11,401] Trial 1018 finished with value: 0.9486822834428805 and parameters: {'weight_lgbm_class_0': 0.11089603380336199, 'weight_lgbm_class_1': 0.7100458580195054, 'weight_lgbm_class_2': 0.7922114957392099, 'weight_xgb_class_0': 0.046209724526751435, 'weight_xgb_class_1': 0.4951085029363158, 'weight_xgb_class_2': 0.384842346887767, 'weight_cat_class_0': 0.060538039662651796, 'weight_cat_class_1': 0.7808599398716728, 'weight_cat_class_2': 0.2232538443383525}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,411] Trial 1019 finished with value: 0.9489117052858874 and parameters: {'weight_lgbm_class_0': 0.10990310885640908, 'weight_lgbm_class_1': 0.708320986562283, 'weight_lgbm_class_2': 0.8456456789267259, 'weight_xgb_class_0': 0.04488328739348218, 'weight_xgb_class_1': 0.48738423862471436, 'weight_xgb_class_2': 0.40790305138737176, 'weight_cat_class_0': 0.05463247496524043, 'weight_cat_class_1': 0.7735076937863491, 'weight_cat_class_2': 0.23576183692211355}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,439] Trial 1020 finished with value: 0.949414575884172 and parameters: {'weight_lgbm_class_0': 0.06908671668557297, 'weight_lgbm_class_1': 0.7083761381109199, 'weight_lgbm_class_2': 0.9557619277162145, 'weight_xgb_class_0': 0.06570354244956575, 'weight_xgb_class_1': 0.4956296810235893, 'weight_xgb_class_2': 0.3929656299284479, 'weight_cat_class_0': 0.05499729600557309, 'weight_cat_class_1': 0.7178262860353078, 'weight_cat_class_2': 0.44127908695382556}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,443] Trial 1021 finished with value: 0.9495416423857703 and parameters: {'weight_lgbm_class_0': 0.06879063923760051, 'weight_lgbm_class_1': 0.7013544640951703, 'weight_lgbm_class_2': 0.9555468473756757, 'weight_xgb_class_0': 0.062434291943477535, 'weight_xgb_class_1': 0.48373070253290174, 'weight_xgb_class_2': 0.3908932133867573, 'weight_cat_class_0': 0.054866610330463125, 'weight_cat_class_1': 0.7578152470230289, 'weight_cat_class_2': 0.44345886154433184}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,521] Trial 1022 finished with value: 0.940379065050983 and parameters: {'weight_lgbm_class_0': 0.06555749493050378, 'weight_lgbm_class_1': 0.7024886094403436, 'weight_lgbm_class_2': 0.9542456159667272, 'weight_xgb_class_0': 0.3172589579423915, 'weight_xgb_class_1': 0.4887541194098045, 'weight_xgb_class_2': 0.3891959657903905, 'weight_cat_class_0': 0.06083356737819599, 'weight_cat_class_1': 0.7801118003064301, 'weight_cat_class_2': 0.08898516818100366}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,544] Trial 1023 finished with value: 0.9493933711395549 and parameters: {'weight_lgbm_class_0': 0.06753975426602117, 'weight_lgbm_class_1': 0.6968959055548698, 'weight_lgbm_class_2': 0.9629462704388506, 'weight_xgb_class_0': 0.0694394933921086, 'weight_xgb_class_1': 0.6009882845249714, 'weight_xgb_class_2': 0.4096030899599466, 'weight_cat_class_0': 0.055392946176867554, 'weight_cat_class_1': 0.7157667430689196, 'weight_cat_class_2': 0.38036745821608053}. Best is trial 928 with value: 0.9497802985501612.

Best trial: 928. Best value: 0.94978:  51%|███████████████████████████████████████████████████████████████████▉                                                                | 1029/2000 [00:35<00:41, 23.36it/s]

[I 2026-07-03 10:23:11,603] Trial 1025 finished with value: 0.9196394250496714 and parameters: {'weight_lgbm_class_0': 0.07342807620841971, 'weight_lgbm_class_1': 0.714780953489655, 'weight_lgbm_class_2': 0.9481650805606273, 'weight_xgb_class_0': 0.7812619076086234, 'weight_xgb_class_1': 0.610587959471558, 'weight_xgb_class_2': 0.41083771054753493, 'weight_cat_class_0': 0.06292105758805325, 'weight_cat_class_1': 0.718990385289747, 'weight_cat_class_2': 0.39959516968796693}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,633] Trial 1026 finished with value: 0.9489117876166645 and parameters: {'weight_lgbm_class_0': 0.06873685403975667, 'weight_lgbm_class_1': 0.7042039207050086, 'weight_lgbm_class_2': 0.9514136088670682, 'weight_xgb_class_0': 0.06911011495535073, 'weight_xgb_class_1': 0.6052496482036539, 'weight_xgb_class_2': 0.40177746761550476, 'weight_cat_class_0': 0.057827879022612716, 'weight_cat_class_1': 0.7134996068801043, 'weight_cat_class_2': 0.0952818527247814}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,656] Trial 1024 finished with value: 0.9492845107679679 and parameters: {'weight_lgbm_class_0': 0.06960289949440952, 'weight_lgbm_class_1': 0.7031516101527218, 'weight_lgbm_class_2': 0.958404332370176, 'weight_xgb_class_0': 0.07503415467259643, 'weight_xgb_class_1': 0.5506657347783916, 'weight_xgb_class_2': 0.3900892320899495, 'weight_cat_class_0': 0.05962930707515746, 'weight_cat_class_1': 0.7203865658976815, 'weight_cat_class_2': 0.38805479860808406}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,688] Trial 1027 finished with value: 0.9493251151012202 and parameters: {'weight_lgbm_class_0': 0.07081268241154362, 'weight_lgbm_class_1': 0.7076843440893142, 'weight_lgbm_class_2': 0.9593460830880223, 'weight_xgb_class_0': 0.06907955810691763, 'weight_xgb_class_1': 0.5394601751184903, 'weight_xgb_class_2': 0.3878544553199901, 'weight_cat_class_0': 0.05148960875190997, 'weight_cat_class_1': 0.7166469451805306, 'weight_cat_class_2': 0.3511135961799059}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,727] Trial 1029 finished with value: 0.9135300732949544 and parameters: {'weight_lgbm_class_0': 0.0690592741796606, 'weight_lgbm_class_1': 0.7016788175359027, 'weight_lgbm_class_2': 0.9599867364694272, 'weight_xgb_class_0': 0.8826035566717412, 'weight_xgb_class_1': 0.6087398339805086, 'weight_xgb_class_2': 0.38131124235610103, 'weight_cat_class_0': 0.06694209838377224, 'weight_cat_class_1': 0.713061269340323, 'weight_cat_class_2': 0.3757302673917835}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,755] Trial 1028 finished with value: 0.949252084575436 and parameters: {'weight_lgbm_class_0': 0.06994220240197878, 'weight_lgbm_class_1': 0.7035900474919857, 'weight_lgbm_class_2': 0.9812043547032194, 'weight_xgb_class_0': 0.06830437182879023, 'weight_xgb_class_1': 0.5336336101633529, 'weight_xgb_class_2': 0.4058341744334223, 'weight_cat_class_0': 0.0685386685186855, 'weight_cat_class_1': 0.7839417690543231, 'weight_cat_class_2': 0.374638685086498}. Best is trial 928 with value: 0.9497802985501612.

Best trial: 928. Best value: 0.94978:  52%|████████████████████████████████████████████████████████████████████▎                                                               | 1035/2000 [00:36<00:43, 22.01it/s]

[I 2026-07-03 10:23:11,897] Trial 1030 finished with value: 0.949200030115758 and parameters: {'weight_lgbm_class_0': 0.07121148068191248, 'weight_lgbm_class_1': 0.7031324169825957, 'weight_lgbm_class_2': 0.946421172785241, 'weight_xgb_class_0': 0.07109184077106247, 'weight_xgb_class_1': 0.5473803908706834, 'weight_xgb_class_2': 0.4180953123409628, 'weight_cat_class_0': 0.06872198486801283, 'weight_cat_class_1': 0.7779457944348702, 'weight_cat_class_2': 0.3511711702324272}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,950] Trial 1031 finished with value: 0.9223455187414639 and parameters: {'weight_lgbm_class_0': 0.07542978322691618, 'weight_lgbm_class_1': 0.6902894100161499, 'weight_lgbm_class_2': 0.9892646831715407, 'weight_xgb_class_0': 0.7773637097994455, 'weight_xgb_class_1': 0.5382740852613641, 'weight_xgb_class_2': 0.41336878643293634, 'weight_cat_class_0': 0.00023159738969561524, 'weight_cat_class_1': 0.7181767145308896, 'weight_cat_class_2': 0.37685523573953955}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:11,994] Trial 1033 finished with value: 0.9491848859102993 and parameters: {'weight_lgbm_class_0': 0.07371928581607202, 'weight_lgbm_class_1': 0.6926880659521719, 'weight_lgbm_class_2': 0.9791916202850881, 'weight_xgb_class_0': 0.07021501984400834, 'weight_xgb_class_1': 0.611094679199895, 'weight_xgb_class_2': 0.4147735693857778, 'weight_cat_class_0': 0.07015439643717694, 'weight_cat_class_1': 0.7043660954876729, 'weight_cat_class_2': 0.37870009824096285}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:12,000] Trial 1032 finished with value: 0.9497127192435326 and parameters: {'weight_lgbm_class_0': 0.07012113040775757, 'weight_lgbm_class_1': 0.6860538447921436, 'weight_lgbm_class_2': 0.980052285200347, 'weight_xgb_class_0': 0.06680945326103199, 'weight_xgb_class_1': 0.6016228724648197, 'weight_xgb_class_2': 0.40708765383647755, 'weight_cat_class_0': 0.00030826662257399016, 'weight_cat_class_1': 0.7189811468904292, 'weight_cat_class_2': 0.38367613624148944}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:12,036] Trial 1034 finished with value: 0.9490402632768942 and parameters: {'weight_lgbm_class_0': 0.07509992630512564, 'weight_lgbm_class_1': 0.6912490901093921, 'weight_lgbm_class_2': 0.992754220987491, 'weight_xgb_class_0': 0.07282564546252838, 'weight_xgb_class_1': 0.5456099192145757, 'weight_xgb_class_2': 0.45791307791104136, 'weight_cat_class_0': 0.08327499722746046, 'weight_cat_class_1': 0.7820511428556928, 'weight_cat_class_2': 0.3556281252404103}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:12,085] Trial 1035 finished with value: 0.9489868881011736 and parameters: {'weight_lgbm_class_0': 0.0731389737064485, 'weight_lgbm_class_1': 0.6889318769068663, 'weight_lgbm_class_2': 0.9337562237187527, 'weight_xgb_class_0': 0.0705930644140835, 'weight_xgb_class_1': 0.5383057251892951, 'weight_xgb_class_2': 0.46464635150047023, 'weight_cat_class_0': 0.08307492145973505, 'weight_cat_class_1': 0.7080517756450364, 'weight_cat_class_2': 0.35600444402753534}. Best is trial 928 with value: 0.9497802985501612.

Best trial: 1038. Best value: 0.949787:  52%|███████████████████████████████████████████████████████████████████▋                                                              | 1041/2000 [00:36<00:40, 23.95it/s]

[I 2026-07-03 10:23:12,093] Trial 1036 finished with value: 0.9487235871395844 and parameters: {'weight_lgbm_class_0': 0.040588030111746276, 'weight_lgbm_class_1': 0.750436297778398, 'weight_lgbm_class_2': 0.9844369773881982, 'weight_xgb_class_0': 0.10802192769187616, 'weight_xgb_class_1': 0.538836417303349, 'weight_xgb_class_2': 0.4609537469763477, 'weight_cat_class_0': 0.08801997280046528, 'weight_cat_class_1': 0.7798527452250603, 'weight_cat_class_2': 0.18660762450305976}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:12,181] Trial 1037 finished with value: 0.9497475732732803 and parameters: {'weight_lgbm_class_0': 0.04154035289108804, 'weight_lgbm_class_1': 0.7483395168870169, 'weight_lgbm_class_2': 0.8911171914199889, 'weight_xgb_class_0': 0.10131545729595537, 'weight_xgb_class_1': 0.5279290105126964, 'weight_xgb_class_2': 0.45420201976355556, 'weight_cat_class_0': 0.0014513374345199092, 'weight_cat_class_1': 0.7794643530182346, 'weight_cat_class_2': 0.34465502318626745}. Best is trial 928 with value: 0.9497802985501612.
[I 2026-07-03 10:23:12,214] Trial 1038 finished with value: 0.9497869943740435 and parameters: {'weight_lgbm_class_0': 0.03861637013374024, 'weight_lgbm_class_1': 0.6874787232157537, 'weight_lgbm_class_2': 0.9890634302783754, 'weight_xgb_class_0': 0.10243254518136698, 'weight_xgb_class_1': 0.5348459286569691, 'weight_xgb_class_2': 0.45110332637255357, 'weight_cat_class_0': 0.001459891237662821, 'weight_cat_class_1': 0.7826754977022639, 'weight_cat_class_2': 0.2836168624996934}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:12,245] Trial 1040 finished with value: 0.949557891026657 and parameters: {'weight_lgbm_class_0': 0.039668505861942406, 'weight_lgbm_class_1': 0.6834251152128529, 'weight_lgbm_class_2': 0.8936099952764852, 'weight_xgb_class_0': 0.101632586696377, 'weight_xgb_class_1': 0.538102632591447, 'weight_xgb_class_2': 0.45584619183966857, 'weight_cat_class_0': 0.018872171302378643, 'weight_cat_class_1': 0.7761312829024712, 'weight_cat_class_2': 0.17178140194078131}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:12,246] Trial 1039 finished with value: 0.9497275035758729 and parameters: {'weight_lgbm_class_0': 0.04041976877142859, 'weight_lgbm_class_1': 0.6845860838513224, 'weight_lgbm_class_2': 0.8890158331456071, 'weight_xgb_class_0': 0.021231100047350997, 'weight_xgb_class_1': 0.5285156414756225, 'weight_xgb_class_2': 0.45559985046186463, 'weight_cat_class_0': 0.08536942904626008, 'weight_cat_class_1': 0.7756757360837522, 'weight_cat_class_2': 0.36322736335342387}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:12,274] Trial 1041 finished with value: 0.948596672765535 and parameters: {'weight_lgbm_class_0': 0.03740802356278494, 'weight_lgbm_class_1': 0.6763118090560656, 'weight_lgbm_class_2': 0.8973949668954702, 'weight_xgb_class_0': 0.10685027769390243, 'weight_xgb_class_1': 0.5314513791106825, 'weight_xgb_class_2': 0.4536645142977677, 'weight_cat_class_0': 0.08863596213018585, 'weight_cat_class_1': 0.7763605028446695, 'weight_cat_class_2': 0.1887467903759598}. Best is trial 1038 with value: 0.9497869943740435.

Best trial: 1038. Best value: 0.949787:  52%|████████████████████████████████████████████████████████████████████                                                              | 1048/2000 [00:36<00:39, 23.94it/s]

[I 2026-07-03 10:23:12,441] Trial 1042 finished with value: 0.949536950776393 and parameters: {'weight_lgbm_class_0': 0.04013706143373619, 'weight_lgbm_class_1': 0.6817355142675399, 'weight_lgbm_class_2': 0.8980721583530182, 'weight_xgb_class_0': 0.1009423146929446, 'weight_xgb_class_1': 0.5348056233086353, 'weight_xgb_class_2': 0.4566681836758572, 'weight_cat_class_0': 0.02074447006197677, 'weight_cat_class_1': 0.7767814487662669, 'weight_cat_class_2': 0.16215568260636534}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:12,458] Trial 1043 finished with value: 0.9497134553813079 and parameters: {'weight_lgbm_class_0': 0.04064630519591301, 'weight_lgbm_class_1': 0.740915344386756, 'weight_lgbm_class_2': 0.9331989284770315, 'weight_xgb_class_0': 0.10695356708162064, 'weight_xgb_class_1': 0.4394708405297002, 'weight_xgb_class_2': 0.4532346685084105, 'weight_cat_class_0': 0.0007843792383808168, 'weight_cat_class_1': 0.7833492824621545, 'weight_cat_class_2': 0.28491560244079134}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:12,513] Trial 1044 finished with value: 0.948469991395697 and parameters: {'weight_lgbm_class_0': 0.04264450873764294, 'weight_lgbm_class_1': 0.7420610482114252, 'weight_lgbm_class_2': 0.8949866773027688, 'weight_xgb_class_0': 0.021109869918578994, 'weight_xgb_class_1': 0.43604250035970155, 'weight_xgb_class_2': 0.459590480089687, 'weight_cat_class_0': 0.000123670134560468, 'weight_cat_class_1': 0.7815637812504371, 'weight_cat_class_2': 0.19170315639406452}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:12,536] Trial 1045 finished with value: 0.9496324312605869 and parameters: {'weight_lgbm_class_0': 0.03866420544626999, 'weight_lgbm_class_1': 0.7475077151963525, 'weight_lgbm_class_2': 0.8141250454781462, 'weight_xgb_class_0': 0.11113961107249636, 'weight_xgb_class_1': 0.4355663009331621, 'weight_xgb_class_2': 0.45421287448133785, 'weight_cat_class_0': 0.0003947885571897159, 'weight_cat_class_1': 0.7779718039623369, 'weight_cat_class_2': 0.1935137363132941}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:12,560] Trial 1046 finished with value: 0.9494380047604212 and parameters: {'weight_lgbm_class_0': 0.042683063592276166, 'weight_lgbm_class_1': 0.7556585675520593, 'weight_lgbm_class_2': 0.893586314680132, 'weight_xgb_class_0': 0.1064735822542902, 'weight_xgb_class_1': 0.4389544738538359, 'weight_xgb_class_2': 0.44846750024026694, 'weight_cat_class_0': 0.019653969520033596, 'weight_cat_class_1': 0.763900764651672, 'weight_cat_class_2': 0.1873707219719383}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:12,584] Trial 1047 finished with value: 0.9497336048550036 and parameters: {'weight_lgbm_class_0': 0.09693786942298685, 'weight_lgbm_class_1': 0.6642529761436431, 'weight_lgbm_class_2': 0.8909028421445357, 'weight_xgb_class_0': 0.020629008017788743, 'weight_xgb_class_1': 0.4429285311401456, 'weight_xgb_class_2': 0.4572669202448933, 'weight_cat_class_0': 4.7120362282246936e-05, 'weight_cat_class_1': 0.7629566784561291, 'weight_cat_class_2': 0.1953959324430999}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:12,611] Trial 1048 finished with value: 0.9487377359304726 and parameters: {'weight_lgbm_class_0': 0.041590010677403796, 'weight_lgbm_class_1': 0.7505942714586661, 'weight_lgbm_class_2': 0.8117344254971229, 'weight_xgb_class_0': 0.02409361563318031, 'weight_xgb_class_1': 0.4505220192399266, 'weight_xgb_class_2': 0.4507332259870631, 'weight_cat_class_0': 0.00036540714728790225, 'weight_cat_class_1': 0.7659895382255526, 'weight_cat_class_2': 0.17062075253708953}. Best is trial 1038 with value: 0.9497869943740435.

Best trial: 1038. Best value: 0.949787:  53%|████████████████████████████████████████████████████████████████████▌                                                             | 1054/2000 [00:36<00:35, 26.46it/s]

[I 2026-07-03 10:23:12,692] Trial 1050 finished with value: 0.9495410141067078 and parameters: {'weight_lgbm_class_0': 0.039838249486517555, 'weight_lgbm_class_1': 0.7490140279041532, 'weight_lgbm_class_2': 0.993012381465199, 'weight_xgb_class_0': 0.10662773858449331, 'weight_xgb_class_1': 0.43722617890412274, 'weight_xgb_class_2': 0.45078051533277713, 'weight_cat_class_0': 0.021582196907097635, 'weight_cat_class_1': 0.8005502199446268, 'weight_cat_class_2': 0.17106988392784817}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:12,700] Trial 1049 finished with value: 0.9496444767053983 and parameters: {'weight_lgbm_class_0': 0.03677587517662668, 'weight_lgbm_class_1': 0.7443958531425456, 'weight_lgbm_class_2': 0.893659973149282, 'weight_xgb_class_0': 0.10193626815501348, 'weight_xgb_class_1': 0.5901044978965735, 'weight_xgb_class_2': 0.4571476628921642, 'weight_cat_class_0': 0.022435215748854778, 'weight_cat_class_1': 0.8017647641912881, 'weight_cat_class_2': 0.2854274501893248}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:12,774] Trial 1052 finished with value: 0.9496022727851194 and parameters: {'weight_lgbm_class_0': 0.04774055424869961, 'weight_lgbm_class_1': 0.7526630090513962, 'weight_lgbm_class_2': 0.8040055415381482, 'weight_xgb_class_0': 0.09767830348989938, 'weight_xgb_class_1': 0.4395357337714577, 'weight_xgb_class_2': 0.4694549174382322, 'weight_cat_class_0': 0.021741281128829396, 'weight_cat_class_1': 0.8003967229952348, 'weight_cat_class_2': 0.4669671600825519}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:12,782] Trial 1053 finished with value: 0.9494240968302375 and parameters: {'weight_lgbm_class_0': 0.037230867311185474, 'weight_lgbm_class_1': 0.7571160519254408, 'weight_lgbm_class_2': 0.8111508768585103, 'weight_xgb_class_0': 0.11255970028882992, 'weight_xgb_class_1': 0.44694523621799376, 'weight_xgb_class_2': 0.4709190744981046, 'weight_cat_class_0': 0.02234362541119092, 'weight_cat_class_1': 0.805835996552204, 'weight_cat_class_2': 0.2944145021861474}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:12,784] Trial 1051 finished with value: 0.9494930255936046 and parameters: {'weight_lgbm_class_0': 0.03601859895550547, 'weight_lgbm_class_1': 0.7474731861606324, 'weight_lgbm_class_2': 0.8180690915199557, 'weight_xgb_class_0': 0.11297518003006574, 'weight_xgb_class_1': 0.4387716616930095, 'weight_xgb_class_2': 0.4688254990898089, 'weight_cat_class_0': 0.020067608877540725, 'weight_cat_class_1': 0.8027086469175182, 'weight_cat_class_2': 0.3093066870561277}. Best is trial 1038 with value: 0.9497869943740435.

Best trial: 1038. Best value: 0.949787:  53%|████████████████████████████████████████████████████████████████████▉                                                             | 1061/2000 [00:37<00:38, 24.59it/s]

[I 2026-07-03 10:23:12,955] Trial 1055 finished with value: 0.9172067467948847 and parameters: {'weight_lgbm_class_0': 0.039905963655275406, 'weight_lgbm_class_1': 0.753074982351564, 'weight_lgbm_class_2': 0.823020740550447, 'weight_xgb_class_0': 0.11900564865518833, 'weight_xgb_class_1': 0.43931723336454015, 'weight_xgb_class_2': 0.46970477134148664, 'weight_cat_class_0': 0.7643550967678769, 'weight_cat_class_1': 0.799580988508202, 'weight_cat_class_2': 0.2860372484144218}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:12,964] Trial 1054 finished with value: 0.9493660037435698 and parameters: {'weight_lgbm_class_0': 0.03588582755916257, 'weight_lgbm_class_1': 0.7483256792275752, 'weight_lgbm_class_2': 0.8071124051551206, 'weight_xgb_class_0': 0.11676199933404519, 'weight_xgb_class_1': 0.5131857218991721, 'weight_xgb_class_2': 0.47261117933552543, 'weight_cat_class_0': 0.021873237882781834, 'weight_cat_class_1': 0.8003807710061738, 'weight_cat_class_2': 0.2701658655053552}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:13,026] Trial 1056 finished with value: 0.949574677623227 and parameters: {'weight_lgbm_class_0': 0.033516453801805804, 'weight_lgbm_class_1': 0.7481030748697611, 'weight_lgbm_class_2': 0.9328754991863302, 'weight_xgb_class_0': 0.11756271883596034, 'weight_xgb_class_1': 0.5051026229179614, 'weight_xgb_class_2': 0.4712902789251488, 'weight_cat_class_0': 0.03124791362233347, 'weight_cat_class_1': 0.8098478863625109, 'weight_cat_class_2': 0.46086138251454606}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:13,061] Trial 1058 finished with value: 0.949533810391629 and parameters: {'weight_lgbm_class_0': 0.03498978618605472, 'weight_lgbm_class_1': 0.6542261592809022, 'weight_lgbm_class_2': 0.9261289111223847, 'weight_xgb_class_0': 0.11616577574271844, 'weight_xgb_class_1': 0.44490671131906, 'weight_xgb_class_2': 0.47194002470247176, 'weight_cat_class_0': 0.02041040322333674, 'weight_cat_class_1': 0.7986885423032261, 'weight_cat_class_2': 0.2825055494277612}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:13,063] Trial 1057 finished with value: 0.9494670214503822 and parameters: {'weight_lgbm_class_0': 0.03277249824443945, 'weight_lgbm_class_1': 0.7522743467664759, 'weight_lgbm_class_2': 0.9966807169235561, 'weight_xgb_class_0': 0.11519781008474807, 'weight_xgb_class_1': 0.5145952925354889, 'weight_xgb_class_2': 0.48173569040607866, 'weight_cat_class_0': 0.034674786170183915, 'weight_cat_class_1': 0.8043328368512502, 'weight_cat_class_2': 0.27479613413239046}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:13,106] Trial 1059 finished with value: 0.9494908020092678 and parameters: {'weight_lgbm_class_0': 0.03518299337324536, 'weight_lgbm_class_1': 0.6376142643519154, 'weight_lgbm_class_2': 0.9237645834665742, 'weight_xgb_class_0': 0.1148366059445379, 'weight_xgb_class_1': 0.4170858276494419, 'weight_xgb_class_2': 0.47339342394457723, 'weight_cat_class_0': 0.021708130171120058, 'weight_cat_class_1': 0.8028846132575312, 'weight_cat_class_2': 0.2854578916610458}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:13,139] Trial 1060 finished with value: 0.9495773045758842 and parameters: {'weight_lgbm_class_0': 0.032884082633871756, 'weight_lgbm_class_1': 0.6545228467793791, 'weight_lgbm_class_2': 0.9205216896660589, 'weight_xgb_class_0': 0.1094981649999853, 'weight_xgb_class_1': 0.41431903417914884, 'weight_xgb_class_2': 0.4658439887263659, 'weight_cat_class_0': 0.020188487007415382, 'weight_cat_class_1': 0.7965895902358195, 'weight_cat_class_2': 0.2720914108341916}. Best is trial 1038 with value: 0.9497869943740435.

Best trial: 1038. Best value: 0.949787:  53%|█████████████████████████████████████████████████████████████████████▏                                                            | 1065/2000 [00:37<00:40, 23.10it/s]

[I 2026-07-03 10:23:13,196] Trial 1061 finished with value: 0.9485075404244082 and parameters: {'weight_lgbm_class_0': 0.09718502406393759, 'weight_lgbm_class_1': 0.6537828625680339, 'weight_lgbm_class_2': 0.925752404397491, 'weight_xgb_class_0': 0.12502804159369713, 'weight_xgb_class_1': 0.4658787875647323, 'weight_xgb_class_2': 0.4735606478566778, 'weight_cat_class_0': 0.022362214313274797, 'weight_cat_class_1': 0.8033207138934869, 'weight_cat_class_2': 0.21107842410733962}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:13,235] Trial 1062 finished with value: 0.9486061862329817 and parameters: {'weight_lgbm_class_0': 0.09482509107621541, 'weight_lgbm_class_1': 0.6555091441109642, 'weight_lgbm_class_2': 0.8360260284339269, 'weight_xgb_class_0': 0.11374139808557632, 'weight_xgb_class_1': 0.4159041314048413, 'weight_xgb_class_2': 0.47495541949713616, 'weight_cat_class_0': 0.019936821931028425, 'weight_cat_class_1': 0.803347269729425, 'weight_cat_class_2': 0.21219169335141586}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:13,285] Trial 1063 finished with value: 0.9496074348453846 and parameters: {'weight_lgbm_class_0': 0.09295986430104287, 'weight_lgbm_class_1': 0.6380458606252452, 'weight_lgbm_class_2': 0.9286898221415256, 'weight_xgb_class_0': 0.028791550287940185, 'weight_xgb_class_1': 0.5081332151943295, 'weight_xgb_class_2': 0.4351658824760565, 'weight_cat_class_0': 0.03640609584429715, 'weight_cat_class_1': 0.7563031029224027, 'weight_cat_class_2': 0.208807137699266}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:13,313] Trial 1065 finished with value: 0.9496172903499396 and parameters: {'weight_lgbm_class_0': 0.09510438007661536, 'weight_lgbm_class_1': 0.6413992744282772, 'weight_lgbm_class_2': 0.9237831781214005, 'weight_xgb_class_0': 0.021450156217183727, 'weight_xgb_class_1': 0.506228772430261, 'weight_xgb_class_2': 0.4271902667354842, 'weight_cat_class_0': 0.039092699021128746, 'weight_cat_class_1': 0.7558371174622561, 'weight_cat_class_2': 0.20884580359946747}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:13,325] Trial 1064 finished with value: 0.9497001193848761 and parameters: {'weight_lgbm_class_0': 0.0904836209475317, 'weight_lgbm_class_1': 0.6529131733268655, 'weight_lgbm_class_2': 0.8481607626716101, 'weight_xgb_class_0': 0.01950628762254842, 'weight_xgb_class_1': 0.5081732434124485, 'weight_xgb_class_2': 0.4326418336642315, 'weight_cat_class_0': 0.00026318648316702554, 'weight_cat_class_1': 0.7585174162310333, 'weight_cat_class_2': 0.24064649018724404}. Best is trial 1038 with value: 0.9497869943740435.

Best trial: 1038. Best value: 0.949787:  54%|█████████████████████████████████████████████████████████████████████▋                                                            | 1072/2000 [00:37<00:40, 23.09it/s]

[I 2026-07-03 10:23:13,455] Trial 1066 finished with value: 0.9496874588402467 and parameters: {'weight_lgbm_class_0': 0.05540811641950932, 'weight_lgbm_class_1': 0.6543140302428172, 'weight_lgbm_class_2': 0.9358863161439759, 'weight_xgb_class_0': 0.02178166839955823, 'weight_xgb_class_1': 0.5068678890981239, 'weight_xgb_class_2': 0.43535847347338014, 'weight_cat_class_0': 0.035161898257781425, 'weight_cat_class_1': 0.7546934123562719, 'weight_cat_class_2': 0.2227615620045456}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:13,506] Trial 1067 finished with value: 0.9496630785528292 and parameters: {'weight_lgbm_class_0': 0.09222655714705442, 'weight_lgbm_class_1': 0.6409292814028558, 'weight_lgbm_class_2': 0.9999905882849581, 'weight_xgb_class_0': 0.022043413953271696, 'weight_xgb_class_1': 0.4711958615599356, 'weight_xgb_class_2': 0.43377329253520047, 'weight_cat_class_0': 0.034373361366316066, 'weight_cat_class_1': 0.7570770520706039, 'weight_cat_class_2': 0.22051944086135755}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:13,543] Trial 1068 finished with value: 0.9496586585414103 and parameters: {'weight_lgbm_class_0': 0.09543274443517649, 'weight_lgbm_class_1': 0.6382005861052598, 'weight_lgbm_class_2': 0.9274314861293372, 'weight_xgb_class_0': 0.019412488274112877, 'weight_xgb_class_1': 0.4186591297131754, 'weight_xgb_class_2': 0.4357346382184972, 'weight_cat_class_0': 0.03944348712302457, 'weight_cat_class_1': 0.7500299757998229, 'weight_cat_class_2': 0.23895227886561762}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:13,564] Trial 1070 finished with value: 0.9496057605089967 and parameters: {'weight_lgbm_class_0': 0.09703136652495484, 'weight_lgbm_class_1': 0.7212620707838805, 'weight_lgbm_class_2': 0.8505404320649743, 'weight_xgb_class_0': 0.020143938792597058, 'weight_xgb_class_1': 0.4719407666505291, 'weight_xgb_class_2': 0.4361360926616868, 'weight_cat_class_0': 0.039273115692907236, 'weight_cat_class_1': 0.7560890536309218, 'weight_cat_class_2': 0.22299285151427095}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:13,607] Trial 1069 finished with value: 0.9497226613939284 and parameters: {'weight_lgbm_class_0': 0.09070103814305817, 'weight_lgbm_class_1': 0.7227136174033465, 'weight_lgbm_class_2': 0.8693759763206975, 'weight_xgb_class_0': 0.02115816722507186, 'weight_xgb_class_1': 0.41201038584901256, 'weight_xgb_class_2': 0.4301524641463751, 'weight_cat_class_0': 0.00024243072713677857, 'weight_cat_class_1': 0.7577877366104343, 'weight_cat_class_2': 0.23956871253716022}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:13,611] Trial 1071 finished with value: 0.9497024255340426 and parameters: {'weight_lgbm_class_0': 0.09110695070495914, 'weight_lgbm_class_1': 0.7257933044512821, 'weight_lgbm_class_2': 0.8454476416274347, 'weight_xgb_class_0': 0.022576362793213393, 'weight_xgb_class_1': 0.46419973519831687, 'weight_xgb_class_2': 0.42347996626265466, 'weight_cat_class_0': 0.0007762880219431209, 'weight_cat_class_1': 0.7582781436590035, 'weight_cat_class_2': 0.40962336060116766}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:13,644] Trial 1072 finished with value: 0.9496611027214253 and parameters: {'weight_lgbm_class_0': 0.09031006226834343, 'weight_lgbm_class_1': 0.7235989353481277, 'weight_lgbm_class_2': 0.9740773538688223, 'weight_xgb_class_0': 0.030091082573772965, 'weight_xgb_class_1': 0.5639119074569889, 'weight_xgb_class_2': 0.43628659742687886, 'weight_cat_class_0': 0.0464801491730544, 'weight_cat_class_1': 0.7519481249021959, 'weight_cat_class_2': 0.22014462790390657}. Best is trial 1038 with value: 0.9497869943740435.

Best trial: 1074. Best value: 0.949788:  54%|██████████████████████████████████████████████████████████████████████                                                            | 1077/2000 [00:38<00:40, 22.62it/s]

[I 2026-07-03 10:23:13,715] Trial 1073 finished with value: 0.9497099514507398 and parameters: {'weight_lgbm_class_0': 0.059830891905267365, 'weight_lgbm_class_1': 0.7215078627768403, 'weight_lgbm_class_2': 0.8579696801447052, 'weight_xgb_class_0': 0.020643249934029526, 'weight_xgb_class_1': 0.47276114316140505, 'weight_xgb_class_2': 0.4347689188184809, 'weight_cat_class_0': 0.04918420496379809, 'weight_cat_class_1': 0.7576723722875764, 'weight_cat_class_2': 0.23351649630274687}. Best is trial 1038 with value: 0.9497869943740435.
[I 2026-07-03 10:23:13,772] Trial 1074 finished with value: 0.949788459361141 and parameters: {'weight_lgbm_class_0': 0.094941303473112, 'weight_lgbm_class_1': 0.7236226392481575, 'weight_lgbm_class_2': 0.8678287253788622, 'weight_xgb_class_0': 0.022016516231749557, 'weight_xgb_class_1': 0.4704603529669033, 'weight_xgb_class_2': 0.4328063403024424, 'weight_cat_class_0': 0.001044377460955516, 'weight_cat_class_1': 0.7565771835508217, 'weight_cat_class_2': 0.24365681267978923}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:13,851] Trial 1075 finished with value: 0.9497165416002366 and parameters: {'weight_lgbm_class_0': 0.05758170334678442, 'weight_lgbm_class_1': 0.7185354890263951, 'weight_lgbm_class_2': 0.8528829609595759, 'weight_xgb_class_0': 0.024836194018872843, 'weight_xgb_class_1': 0.558721217740677, 'weight_xgb_class_2': 0.43762285770440307, 'weight_cat_class_0': 0.04635738872470626, 'weight_cat_class_1': 0.7580968568141226, 'weight_cat_class_2': 0.1377871289225393}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:13,865] Trial 1076 finished with value: 0.949725530525297 and parameters: {'weight_lgbm_class_0': 0.0603591844161893, 'weight_lgbm_class_1': 0.7174404548426552, 'weight_lgbm_class_2': 0.9737747162661918, 'weight_xgb_class_0': 0.03639939630971567, 'weight_xgb_class_1': 0.5592819508906625, 'weight_xgb_class_2': 0.43315925493834867, 'weight_cat_class_0': 0.045751693215675085, 'weight_cat_class_1': 0.7415797408628871, 'weight_cat_class_2': 0.23821163209609725}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:13,904] Trial 1077 finished with value: 0.9493774985553363 and parameters: {'weight_lgbm_class_0': 0.055723065571450896, 'weight_lgbm_class_1': 0.7267218729464602, 'weight_lgbm_class_2': 0.8543782059217975, 'weight_xgb_class_0': 0.03769412590143202, 'weight_xgb_class_1': 0.4748403920161718, 'weight_xgb_class_2': 0.4394352048609999, 'weight_cat_class_0': 0.0008792788535963991, 'weight_cat_class_1': 0.7357613415517374, 'weight_cat_class_2': 0.4141297681586026}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  54%|██████████████████████████████████████████████████████████████████████▍                                                           | 1084/2000 [00:38<00:39, 23.43it/s]

[I 2026-07-03 10:23:13,980] Trial 1078 finished with value: 0.949645612148367 and parameters: {'weight_lgbm_class_0': 0.058103469694010285, 'weight_lgbm_class_1': 0.7205830254646831, 'weight_lgbm_class_2': 0.8581815337227781, 'weight_xgb_class_0': 0.0004488465208673313, 'weight_xgb_class_1': 0.5567097716053387, 'weight_xgb_class_2': 0.4429004899666415, 'weight_cat_class_0': 0.044578049979314936, 'weight_cat_class_1': 0.7404347173615365, 'weight_cat_class_2': 0.13791543677611548}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,013] Trial 1079 finished with value: 0.9176304505253007 and parameters: {'weight_lgbm_class_0': 0.19659908165277057, 'weight_lgbm_class_1': 0.7194639224423772, 'weight_lgbm_class_2': 0.9729663693134637, 'weight_xgb_class_0': 0.670437799189225, 'weight_xgb_class_1': 0.54818826430809, 'weight_xgb_class_2': 0.4206729943596663, 'weight_cat_class_0': 0.04608130290537635, 'weight_cat_class_1': 0.744155052081829, 'weight_cat_class_2': 0.23753490481617984}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,065] Trial 1080 finished with value: 0.935660006605138 and parameters: {'weight_lgbm_class_0': 0.520667563704977, 'weight_lgbm_class_1': 0.7141143622674292, 'weight_lgbm_class_2': 0.8603717228228287, 'weight_xgb_class_0': 0.08797036807610743, 'weight_xgb_class_1': 0.5579097818466604, 'weight_xgb_class_2': 0.4477005068223606, 'weight_cat_class_0': 0.016986376767521617, 'weight_cat_class_1': 0.7315567956549041, 'weight_cat_class_2': 0.4522600951738771}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,083] Trial 1081 finished with value: 0.9486224950593553 and parameters: {'weight_lgbm_class_0': 0.058273966453842765, 'weight_lgbm_class_1': 0.7185311926758065, 'weight_lgbm_class_2': 0.8691782346920955, 'weight_xgb_class_0': 4.71630474611108e-05, 'weight_xgb_class_1': 0.5523886076186988, 'weight_xgb_class_2': 0.4460360197546964, 'weight_cat_class_0': 0.014986689979813646, 'weight_cat_class_1': 0.7320298985285627, 'weight_cat_class_2': 0.4551395369570715}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,108] Trial 1082 finished with value: 0.9346469275921168 and parameters: {'weight_lgbm_class_0': 0.5133051535972064, 'weight_lgbm_class_1': 0.7228013199349608, 'weight_lgbm_class_2': 0.9758096126089439, 'weight_xgb_class_0': 0.08369318310576733, 'weight_xgb_class_1': 0.5568540598750933, 'weight_xgb_class_2': 0.4440143538869572, 'weight_cat_class_0': 8.880936926929767e-05, 'weight_cat_class_1': 0.7354616217385782, 'weight_cat_class_2': 0.1490535136248796}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,159] Trial 1084 finished with value: 0.9490879496782018 and parameters: {'weight_lgbm_class_0': 0.13033340297960183, 'weight_lgbm_class_1': 0.728421925876159, 'weight_lgbm_class_2': 0.8706731471827402, 'weight_xgb_class_0': 0.08401739753513532, 'weight_xgb_class_1': 0.5552717574978598, 'weight_xgb_class_2': 0.45168578615582844, 'weight_cat_class_0': 0.0016076858134951078, 'weight_cat_class_1': 0.7332532837536294, 'weight_cat_class_2': 0.41007155407180096}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,170] Trial 1083 finished with value: 0.9449964828191466 and parameters: {'weight_lgbm_class_0': 0.05876291220678696, 'weight_lgbm_class_1': 0.7205911939833629, 'weight_lgbm_class_2': 0.867220560553432, 'weight_xgb_class_0': 0.28313285298361485, 'weight_xgb_class_1': 0.550287915025936, 'weight_xgb_class_2': 0.4497627941686025, 'weight_cat_class_0': 0.0012018207434361726, 'weight_cat_class_1': 0.7270796534059891, 'weight_cat_class_2': 0.15226279077698784}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  54%|██████████████████████████████████████████████████████████████████████▋                                                           | 1088/2000 [00:38<00:37, 24.24it/s]

[I 2026-07-03 10:23:14,237] Trial 1085 finished with value: 0.9495234028916094 and parameters: {'weight_lgbm_class_0': 0.1348770109836461, 'weight_lgbm_class_1': 0.7202058250789679, 'weight_lgbm_class_2': 0.88802035416802, 'weight_xgb_class_0': 0.04981469718553924, 'weight_xgb_class_1': 0.546812925754516, 'weight_xgb_class_2': 0.4540895075398901, 'weight_cat_class_0': 0.001163771947163928, 'weight_cat_class_1': 0.732839524404007, 'weight_cat_class_2': 0.4136418338231235}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,326] Trial 1086 finished with value: 0.9497249049319795 and parameters: {'weight_lgbm_class_0': 0.1236158415330009, 'weight_lgbm_class_1': 0.7247342788114974, 'weight_lgbm_class_2': 0.8723520601191233, 'weight_xgb_class_0': 0.0009121154597260276, 'weight_xgb_class_1': 0.458216567055769, 'weight_xgb_class_2': 0.4475695319802041, 'weight_cat_class_0': 0.01938702564599292, 'weight_cat_class_1': 0.7353857471125332, 'weight_cat_class_2': 0.24995652560545403}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,400] Trial 1087 finished with value: 0.949697926260319 and parameters: {'weight_lgbm_class_0': 0.12895484079329567, 'weight_lgbm_class_1': 0.7287923687948532, 'weight_lgbm_class_2': 0.8699526377897552, 'weight_xgb_class_0': 0.00024022181625337857, 'weight_xgb_class_1': 0.4612217232596412, 'weight_xgb_class_2': 0.44983243358881153, 'weight_cat_class_0': 0.020072814156035457, 'weight_cat_class_1': 0.7322320088568753, 'weight_cat_class_2': 0.25670710290230325}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,421] Trial 1088 finished with value: 0.9497009201897001 and parameters: {'weight_lgbm_class_0': 0.132080392644498, 'weight_lgbm_class_1': 0.6708386428630135, 'weight_lgbm_class_2': 0.873079475043686, 'weight_xgb_class_0': 0.0015904850074551918, 'weight_xgb_class_1': 0.491371405056456, 'weight_xgb_class_2': 0.47988247325012445, 'weight_cat_class_0': 0.016498022048014295, 'weight_cat_class_1': 0.7330884115347845, 'weight_cat_class_2': 0.26086369975630097}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  55%|███████████████████████████████████████████████████████████████████████                                                           | 1094/2000 [00:38<00:43, 20.89it/s]

[I 2026-07-03 10:23:14,490] Trial 1089 finished with value: 0.9497663845033134 and parameters: {'weight_lgbm_class_0': 0.12702707889088025, 'weight_lgbm_class_1': 0.6072887376401224, 'weight_lgbm_class_2': 0.8909054446557529, 'weight_xgb_class_0': 0.0009564381955147153, 'weight_xgb_class_1': 0.46282086286065144, 'weight_xgb_class_2': 0.48163872102329397, 'weight_cat_class_0': 0.0005517745737269077, 'weight_cat_class_1': 0.7336670884053429, 'weight_cat_class_2': 0.24620608679240402}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,529] Trial 1090 finished with value: 0.9496863594804846 and parameters: {'weight_lgbm_class_0': 0.13237967714277582, 'weight_lgbm_class_1': 0.6685296440357338, 'weight_lgbm_class_2': 0.8815112246233552, 'weight_xgb_class_0': 0.001050965743695842, 'weight_xgb_class_1': 0.4639974687023047, 'weight_xgb_class_2': 0.48366981590000685, 'weight_cat_class_0': 0.01724275015657581, 'weight_cat_class_1': 0.7282519472013242, 'weight_cat_class_2': 0.25870764205520413}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,574] Trial 1091 finished with value: 0.9496834894726854 and parameters: {'weight_lgbm_class_0': 0.12869355491388007, 'weight_lgbm_class_1': 0.6726783736470366, 'weight_lgbm_class_2': 0.8910960768572808, 'weight_xgb_class_0': 0.001868191881255657, 'weight_xgb_class_1': 0.45229533425039403, 'weight_xgb_class_2': 0.480013801040803, 'weight_cat_class_0': 0.0186372478287145, 'weight_cat_class_1': 0.7323914271323437, 'weight_cat_class_2': 0.25923058470534144}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,609] Trial 1092 finished with value: 0.9494260742986739 and parameters: {'weight_lgbm_class_0': 0.10712346547075893, 'weight_lgbm_class_1': 0.6623531779778363, 'weight_lgbm_class_2': 0.8863499018208703, 'weight_xgb_class_0': 0.04519434520814429, 'weight_xgb_class_1': 0.4559949347410132, 'weight_xgb_class_2': 0.47913320884645527, 'weight_cat_class_0': 0.017755712672889275, 'weight_cat_class_1': 0.7819216686842704, 'weight_cat_class_2': 0.19867036216814268}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,615] Trial 1093 finished with value: 0.9491470343889951 and parameters: {'weight_lgbm_class_0': 0.12941784407229773, 'weight_lgbm_class_1': 0.6703268356877498, 'weight_lgbm_class_2': 0.890790656276483, 'weight_xgb_class_0': 0.04516377332317792, 'weight_xgb_class_1': 0.45895878915989424, 'weight_xgb_class_2': 0.48470627382335313, 'weight_cat_class_0': 0.017901340014407456, 'weight_cat_class_1': 0.7849112828564114, 'weight_cat_class_2': 0.18546149850888288}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,692] Trial 1094 finished with value: 0.9494823696003296 and parameters: {'weight_lgbm_class_0': 0.11046580488540947, 'weight_lgbm_class_1': 0.6679039239094249, 'weight_lgbm_class_2': 0.888254091814159, 'weight_xgb_class_0': 0.043131643604188905, 'weight_xgb_class_1': 0.4654060391381451, 'weight_xgb_class_2': 0.48257295814857176, 'weight_cat_class_0': 0.019527780091666107, 'weight_cat_class_1': 0.785795652076227, 'weight_cat_class_2': 0.25810978348773733}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  55%|███████████████████████████████████████████████████████████████████████▍                                                          | 1099/2000 [00:39<00:42, 21.34it/s]

[I 2026-07-03 10:23:14,699] Trial 1095 finished with value: 0.9466640458800367 and parameters: {'weight_lgbm_class_0': 0.24813938827606824, 'weight_lgbm_class_1': 0.6694099624102627, 'weight_lgbm_class_2': 0.8906816532144984, 'weight_xgb_class_0': 0.049223813802907454, 'weight_xgb_class_1': 0.4566925066544566, 'weight_xgb_class_2': 0.4833407524022374, 'weight_cat_class_0': 0.020377547204611827, 'weight_cat_class_1': 0.7814266870175917, 'weight_cat_class_2': 0.2655226211906034}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,730] Trial 1096 finished with value: 0.9490530453657503 and parameters: {'weight_lgbm_class_0': 0.13589755568188466, 'weight_lgbm_class_1': 0.604548081539767, 'weight_lgbm_class_2': 0.8317938347562822, 'weight_xgb_class_0': 0.0442668226167333, 'weight_xgb_class_1': 0.49949612099834584, 'weight_xgb_class_2': 0.4810801470137864, 'weight_cat_class_0': 0.01993163823521931, 'weight_cat_class_1': 0.7781720458064154, 'weight_cat_class_2': 0.24938322872507573}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,781] Trial 1097 finished with value: 0.9492007419514433 and parameters: {'weight_lgbm_class_0': 0.12945003253816476, 'weight_lgbm_class_1': 0.5975553047870918, 'weight_lgbm_class_2': 0.8355102101966143, 'weight_xgb_class_0': 0.043887959047978695, 'weight_xgb_class_1': 0.45816695440357375, 'weight_xgb_class_2': 0.482702319101161, 'weight_cat_class_0': 0.01960910969529332, 'weight_cat_class_1': 0.7841217496992159, 'weight_cat_class_2': 0.2643871956964194}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,885] Trial 1098 finished with value: 0.949741643450919 and parameters: {'weight_lgbm_class_0': 0.1200027263793165, 'weight_lgbm_class_1': 0.6774216086082225, 'weight_lgbm_class_2': 0.8336052053011835, 'weight_xgb_class_0': 0.0004252930131225102, 'weight_xgb_class_1': 0.4849898812323648, 'weight_xgb_class_2': 0.48509889232633135, 'weight_cat_class_0': 0.019056455681246132, 'weight_cat_class_1': 0.76733981349543, 'weight_cat_class_2': 0.2598880247881727}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  55%|███████████████████████████████████████████████████████████████████████▊                                                          | 1104/2000 [00:39<00:44, 20.07it/s]

[I 2026-07-03 10:23:14,952] Trial 1099 finished with value: 0.949422503092511 and parameters: {'weight_lgbm_class_0': 0.1129970582230926, 'weight_lgbm_class_1': 0.6737995911336448, 'weight_lgbm_class_2': 0.8990715548471504, 'weight_xgb_class_0': 0.04485237389985411, 'weight_xgb_class_1': 0.48308973976629577, 'weight_xgb_class_2': 0.48823104906586745, 'weight_cat_class_0': 0.019919592641598975, 'weight_cat_class_1': 0.7809999582142323, 'weight_cat_class_2': 0.20618175602594024}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:14,968] Trial 1100 finished with value: 0.9497050540286497 and parameters: {'weight_lgbm_class_0': 0.11115864761263247, 'weight_lgbm_class_1': 0.5979994901698161, 'weight_lgbm_class_2': 0.9171240645526658, 'weight_xgb_class_0': 0.035557341000267195, 'weight_xgb_class_1': 0.47620855459623446, 'weight_xgb_class_2': 0.48600819476004536, 'weight_cat_class_0': 1.7945841011211415e-05, 'weight_cat_class_1': 0.78017321529281, 'weight_cat_class_2': 0.19357034586590216}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,058] Trial 1102 finished with value: 0.9492005654600334 and parameters: {'weight_lgbm_class_0': 0.10701402061548276, 'weight_lgbm_class_1': 0.5852672617298041, 'weight_lgbm_class_2': 0.896840456149664, 'weight_xgb_class_0': 0.04440446878501485, 'weight_xgb_class_1': 0.4873975879632316, 'weight_xgb_class_2': 0.4930250900818378, 'weight_cat_class_0': 0.034429959896530395, 'weight_cat_class_1': 0.7803365520447393, 'weight_cat_class_2': 0.19397208823747158}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,075] Trial 1101 finished with value: 0.921964404941447 and parameters: {'weight_lgbm_class_0': 0.7246403161415299, 'weight_lgbm_class_1': 0.5632167630618465, 'weight_lgbm_class_2': 0.8993760103135051, 'weight_xgb_class_0': 0.046320716889507424, 'weight_xgb_class_1': 0.47410582307022797, 'weight_xgb_class_2': 0.4697637708067609, 'weight_cat_class_0': 0.03147820693238375, 'weight_cat_class_1': 0.7815181413118507, 'weight_cat_class_2': 0.20375035423054907}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,076] Trial 1103 finished with value: 0.9492733283279096 and parameters: {'weight_lgbm_class_0': 0.11104166817770972, 'weight_lgbm_class_1': 0.57439553847109, 'weight_lgbm_class_2': 0.9012422482553623, 'weight_xgb_class_0': 0.04150804380235865, 'weight_xgb_class_1': 0.47266650215717215, 'weight_xgb_class_2': 0.491344391431239, 'weight_cat_class_0': 0.03534454220373734, 'weight_cat_class_1': 0.7801741158441655, 'weight_cat_class_2': 0.3087961208342228}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,097] Trial 1104 finished with value: 0.949043089653383 and parameters: {'weight_lgbm_class_0': 0.11042556992408667, 'weight_lgbm_class_1': 0.5604339160772402, 'weight_lgbm_class_2': 0.8307574201558685, 'weight_xgb_class_0': 0.03943701299806975, 'weight_xgb_class_1': 0.4827260543320208, 'weight_xgb_class_2': 0.4932024601116186, 'weight_cat_class_0': 0.050044424845133065, 'weight_cat_class_1': 0.6974360331171927, 'weight_cat_class_2': 0.27528823813736064}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  55%|████████████████████████████████████████████████████████████████████████                                                          | 1109/2000 [00:39<00:37, 23.74it/s]

[I 2026-07-03 10:23:15,170] Trial 1105 finished with value: 0.9491784080991472 and parameters: {'weight_lgbm_class_0': 0.10546541360505438, 'weight_lgbm_class_1': 0.538113167152271, 'weight_lgbm_class_2': 0.8327726200911721, 'weight_xgb_class_0': 0.03737299482488264, 'weight_xgb_class_1': 0.4889872946533454, 'weight_xgb_class_2': 0.4965663153433458, 'weight_cat_class_0': 0.03831515612572797, 'weight_cat_class_1': 0.7735713062295506, 'weight_cat_class_2': 0.20510417819065752}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,230] Trial 1107 finished with value: 0.9492544405753739 and parameters: {'weight_lgbm_class_0': 0.10434572835490163, 'weight_lgbm_class_1': 0.6123096791367783, 'weight_lgbm_class_2': 0.9492761354903125, 'weight_xgb_class_0': 0.03399616363485359, 'weight_xgb_class_1': 0.490577699241766, 'weight_xgb_class_2': 0.49545686646580767, 'weight_cat_class_0': 0.05347382600402426, 'weight_cat_class_1': 0.691266737854096, 'weight_cat_class_2': 0.20144139415813625}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,236] Trial 1108 finished with value: 0.9403205126424612 and parameters: {'weight_lgbm_class_0': 0.40017133928803306, 'weight_lgbm_class_1': 0.6068374514051414, 'weight_lgbm_class_2': 0.9054497206298574, 'weight_xgb_class_0': 0.03248633341027304, 'weight_xgb_class_1': 0.4300295980352137, 'weight_xgb_class_2': 0.49780475092568655, 'weight_cat_class_0': 0.04926992910298557, 'weight_cat_class_1': 0.697085391321425, 'weight_cat_class_2': 0.3120453597816132}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,258] Trial 1106 finished with value: 0.9492554630501863 and parameters: {'weight_lgbm_class_0': 0.10283009568587813, 'weight_lgbm_class_1': 0.5865217212240501, 'weight_lgbm_class_2': 0.9131119372072386, 'weight_xgb_class_0': 0.03475763218139288, 'weight_xgb_class_1': 0.48470829370197055, 'weight_xgb_class_2': 0.4128514113373272, 'weight_cat_class_0': 0.049728301888196345, 'weight_cat_class_1': 0.6989718184281357, 'weight_cat_class_2': 0.30959770867214}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,305] Trial 1109 finished with value: 0.9493355827809431 and parameters: {'weight_lgbm_class_0': 0.10440264452841459, 'weight_lgbm_class_1': 0.5448441519699092, 'weight_lgbm_class_2': 0.9065487988358546, 'weight_xgb_class_0': 0.021115463695130253, 'weight_xgb_class_1': 0.4933260548581994, 'weight_xgb_class_2': 0.41452818994746216, 'weight_cat_class_0': 0.04858918650630125, 'weight_cat_class_1': 0.7720939376749636, 'weight_cat_class_2': 0.2052703192085643}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  56%|████████████████████████████████████████████████████████████████████████▎                                                         | 1113/2000 [00:39<00:43, 20.23it/s]

[I 2026-07-03 10:23:15,402] Trial 1110 finished with value: 0.9493137960617527 and parameters: {'weight_lgbm_class_0': 0.11301325842955283, 'weight_lgbm_class_1': 0.6142570338427433, 'weight_lgbm_class_2': 0.7962172570419882, 'weight_xgb_class_0': 0.01549351171886234, 'weight_xgb_class_1': 0.48036962956459006, 'weight_xgb_class_2': 0.8306398803124109, 'weight_cat_class_0': 0.060173781523898164, 'weight_cat_class_1': 0.7710065023530883, 'weight_cat_class_2': 0.24171027864917394}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,510] Trial 1111 finished with value: 0.9493169735910015 and parameters: {'weight_lgbm_class_0': 0.11173608158308171, 'weight_lgbm_class_1': 0.6934288410882189, 'weight_lgbm_class_2': 0.785007296765234, 'weight_xgb_class_0': 0.01829141297800213, 'weight_xgb_class_1': 0.5213787312468846, 'weight_xgb_class_2': 0.4979625328417294, 'weight_cat_class_0': 0.053939434926860874, 'weight_cat_class_1': 0.7682671968261297, 'weight_cat_class_2': 0.2836432696977085}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,542] Trial 1112 finished with value: 0.9409989287440915 and parameters: {'weight_lgbm_class_0': 0.4002650638421737, 'weight_lgbm_class_1': 0.6948663862511162, 'weight_lgbm_class_2': 0.7827849012227847, 'weight_xgb_class_0': 0.019094995684363562, 'weight_xgb_class_1': 0.5210772149955556, 'weight_xgb_class_2': 0.4986784267815881, 'weight_cat_class_0': 0.05544860526399618, 'weight_cat_class_1': 0.7665492056123376, 'weight_cat_class_2': 0.3071796379235918}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,597] Trial 1113 finished with value: 0.9495665498395479 and parameters: {'weight_lgbm_class_0': 0.07492683244732631, 'weight_lgbm_class_1': 0.6996879351759637, 'weight_lgbm_class_2': 0.8289047586718737, 'weight_xgb_class_0': 0.019656439096900447, 'weight_xgb_class_1': 0.5187472589505919, 'weight_xgb_class_2': 0.5044239118395318, 'weight_cat_class_0': 0.06908308704846133, 'weight_cat_class_1': 0.6966464799715559, 'weight_cat_class_2': 0.30192839196849175}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  56%|████████████████████████████████████████████████████████████████████████▋                                                         | 1119/2000 [00:39<00:38, 22.68it/s]

[I 2026-07-03 10:23:15,613] Trial 1115 finished with value: 0.9495391240939193 and parameters: {'weight_lgbm_class_0': 0.08492094291495683, 'weight_lgbm_class_1': 0.6994393400415786, 'weight_lgbm_class_2': 0.7948251502743799, 'weight_xgb_class_0': 0.02296802751699052, 'weight_xgb_class_1': 0.5092262562436433, 'weight_xgb_class_2': 0.8329131437413875, 'weight_cat_class_0': 0.06653150095240178, 'weight_cat_class_1': 0.6976730727571161, 'weight_cat_class_2': 0.30790023387994114}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,663] Trial 1114 finished with value: 0.9494491274937341 and parameters: {'weight_lgbm_class_0': 0.0832067980988378, 'weight_lgbm_class_1': 0.6936702522667535, 'weight_lgbm_class_2': 0.8437872750231715, 'weight_xgb_class_0': 0.025083741542554147, 'weight_xgb_class_1': 0.5164877516128185, 'weight_xgb_class_2': 0.49870764322837446, 'weight_cat_class_0': 0.06200011002189327, 'weight_cat_class_1': 0.6946426485324866, 'weight_cat_class_2': 0.2406382129596566}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,673] Trial 1117 finished with value: 0.9495732153884978 and parameters: {'weight_lgbm_class_0': 0.07813605452633995, 'weight_lgbm_class_1': 0.6923967517715951, 'weight_lgbm_class_2': 0.8314634233753586, 'weight_xgb_class_0': 0.014999311273168925, 'weight_xgb_class_1': 0.5211847473522424, 'weight_xgb_class_2': 0.4122711077779998, 'weight_cat_class_0': 0.06621896248735275, 'weight_cat_class_1': 0.7105381731256798, 'weight_cat_class_2': 0.2880288523808817}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,697] Trial 1116 finished with value: 0.949154239757 and parameters: {'weight_lgbm_class_0': 0.07968259387939584, 'weight_lgbm_class_1': 0.08921743693922113, 'weight_lgbm_class_2': 0.834745196102147, 'weight_xgb_class_0': 0.016883538417206464, 'weight_xgb_class_1': 0.5121856306938691, 'weight_xgb_class_2': 0.41076530904288716, 'weight_cat_class_0': 0.06482224704173141, 'weight_cat_class_1': 0.7614161596322091, 'weight_cat_class_2': 0.3116453118425917}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,785] Trial 1118 finished with value: 0.949464960869821 and parameters: {'weight_lgbm_class_0': 0.08039705431485797, 'weight_lgbm_class_1': 0.7045455473115492, 'weight_lgbm_class_2': 0.8435356521673332, 'weight_xgb_class_0': 0.01862970139483712, 'weight_xgb_class_1': 0.5265527261945645, 'weight_xgb_class_2': 0.41121345981021595, 'weight_cat_class_0': 0.06979553796275537, 'weight_cat_class_1': 0.7679613938324328, 'weight_cat_class_2': 0.2943038047749502}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,803] Trial 1119 finished with value: 0.9494869628083472 and parameters: {'weight_lgbm_class_0': 0.0803133688211459, 'weight_lgbm_class_1': 0.6990005212633759, 'weight_lgbm_class_2': 0.7994043244124213, 'weight_xgb_class_0': 0.01675854752556874, 'weight_xgb_class_1': 0.5198721974954753, 'weight_xgb_class_2': 0.4633731987423303, 'weight_cat_class_0': 0.06828812393762357, 'weight_cat_class_1': 0.7594390936029818, 'weight_cat_class_2': 0.2840134663001894}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  56%|████████████████████████████████████████████████████████████████████████▉                                                         | 1123/2000 [00:40<00:37, 23.66it/s]

[I 2026-07-03 10:23:15,855] Trial 1120 finished with value: 0.9109665911699282 and parameters: {'weight_lgbm_class_0': 0.8895293430732871, 'weight_lgbm_class_1': 0.6997083653518726, 'weight_lgbm_class_2': 0.8224470518654114, 'weight_xgb_class_0': 0.06176711849904598, 'weight_xgb_class_1': 0.52862793690115, 'weight_xgb_class_2': 0.46618973453724644, 'weight_cat_class_0': 0.07262121274460025, 'weight_cat_class_1': 0.7607574167324459, 'weight_cat_class_2': 0.2837285383254945}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,895] Trial 1121 finished with value: 0.9494951594018574 and parameters: {'weight_lgbm_class_0': 0.07621530607312149, 'weight_lgbm_class_1': 0.700495878717458, 'weight_lgbm_class_2': 0.7973177505122019, 'weight_xgb_class_0': 0.017541619663407393, 'weight_xgb_class_1': 0.5324696438727761, 'weight_xgb_class_2': 0.461605137196489, 'weight_cat_class_0': 0.07098720245063812, 'weight_cat_class_1': 0.7635607283884216, 'weight_cat_class_2': 0.2853860327911369}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:15,900] Trial 1122 finished with value: 0.9495310874149672 and parameters: {'weight_lgbm_class_0': 0.07971853479045742, 'weight_lgbm_class_1': 0.6944201074866, 'weight_lgbm_class_2': 0.8277046258861457, 'weight_xgb_class_0': 0.017854712097207282, 'weight_xgb_class_1': 0.5178752899034971, 'weight_xgb_class_2': 0.4713837651909444, 'weight_cat_class_0': 0.06796117722811751, 'weight_cat_class_1': 0.8140379872920749, 'weight_cat_class_2': 0.27369333551832203}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,017] Trial 1123 finished with value: 0.948869239384719 and parameters: {'weight_lgbm_class_0': 0.08019344354607316, 'weight_lgbm_class_1': 0.765544808288331, 'weight_lgbm_class_2': 0.8334000375056119, 'weight_xgb_class_0': 0.06278097706240346, 'weight_xgb_class_1': 0.5145946759394637, 'weight_xgb_class_2': 0.469186677010427, 'weight_cat_class_0': 0.06885909436405924, 'weight_cat_class_1': 0.8174074425220498, 'weight_cat_class_2': 0.24038963518057188}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  56%|█████████████████████████████████████████████████████████████████████████▍                                                        | 1129/2000 [00:40<00:40, 21.68it/s]

[I 2026-07-03 10:23:16,087] Trial 1124 finished with value: 0.9495362024463142 and parameters: {'weight_lgbm_class_0': 0.08218994925722689, 'weight_lgbm_class_1': 0.765669935212109, 'weight_lgbm_class_2': 0.8329596680453358, 'weight_xgb_class_0': 0.000167417750211371, 'weight_xgb_class_1': 0.5197364259098147, 'weight_xgb_class_2': 0.46268270680328033, 'weight_cat_class_0': 0.08207687003914436, 'weight_cat_class_1': 0.8178104694030524, 'weight_cat_class_2': 0.2436458937913766}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,140] Trial 1125 finished with value: 0.9486831303104273 and parameters: {'weight_lgbm_class_0': 0.07941781817803704, 'weight_lgbm_class_1': 0.7618651569057968, 'weight_lgbm_class_2': 0.8474086468062378, 'weight_xgb_class_0': 0.07179265843482383, 'weight_xgb_class_1': 0.5182986121118657, 'weight_xgb_class_2': 0.4643953152205224, 'weight_cat_class_0': 0.08492777843768991, 'weight_cat_class_1': 0.7532529030856187, 'weight_cat_class_2': 0.27278202080175107}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,165] Trial 1126 finished with value: 0.9495099240555617 and parameters: {'weight_lgbm_class_0': 0.07681795122154789, 'weight_lgbm_class_1': 0.7427484025291293, 'weight_lgbm_class_2': 0.9444832818449518, 'weight_xgb_class_0': 0.06429186980472447, 'weight_xgb_class_1': 0.5253169772505828, 'weight_xgb_class_2': 0.4669546834100452, 'weight_cat_class_0': 0.03463932402875694, 'weight_cat_class_1': 0.8155334445137582, 'weight_cat_class_2': 0.24108190941016572}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,201] Trial 1127 finished with value: 0.9495983200200081 and parameters: {'weight_lgbm_class_0': 0.07110836813798953, 'weight_lgbm_class_1': 0.7388072226370344, 'weight_lgbm_class_2': 0.9443200669855378, 'weight_xgb_class_0': 0.06632773900882569, 'weight_xgb_class_1': 0.5088983450953863, 'weight_xgb_class_2': 0.45983231850019013, 'weight_cat_class_0': 0.03373954282124264, 'weight_cat_class_1': 0.8177553749955219, 'weight_cat_class_2': 0.4594856254449797}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,204] Trial 1128 finished with value: 0.9495326665086982 and parameters: {'weight_lgbm_class_0': 0.079134222070463, 'weight_lgbm_class_1': 0.7435576298669891, 'weight_lgbm_class_2': 0.9418696977990375, 'weight_xgb_class_0': 0.05941966722334459, 'weight_xgb_class_1': 0.503942645967909, 'weight_xgb_class_2': 0.4661056836844488, 'weight_cat_class_0': 0.033491816027283024, 'weight_cat_class_1': 0.81124656324768, 'weight_cat_class_2': 0.22676394142730877}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,279] Trial 1129 finished with value: 0.9495657774539982 and parameters: {'weight_lgbm_class_0': 0.08158989418964357, 'weight_lgbm_class_1': 0.7641158869535956, 'weight_lgbm_class_2': 0.969390557982391, 'weight_xgb_class_0': 2.5988035471796733e-05, 'weight_xgb_class_1': 0.526294480498103, 'weight_xgb_class_2': 0.46488209152778925, 'weight_cat_class_0': 0.09556568110885602, 'weight_cat_class_1': 0.8143225001164619, 'weight_cat_class_2': 0.27539792578665534}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  57%|█████████████████████████████████████████████████████████████████████████▋                                                        | 1134/2000 [00:40<00:37, 22.99it/s]

[I 2026-07-03 10:23:16,302] Trial 1130 finished with value: 0.9496655289523052 and parameters: {'weight_lgbm_class_0': 0.06042865892467026, 'weight_lgbm_class_1': 0.7135428793741375, 'weight_lgbm_class_2': 0.9401592495352125, 'weight_xgb_class_0': 0.06400204537165544, 'weight_xgb_class_1': 0.5014408579703948, 'weight_xgb_class_2': 0.4625620545874245, 'weight_cat_class_0': 0.036248840938744004, 'weight_cat_class_1': 0.8174170939997668, 'weight_cat_class_2': 0.22995051970099684}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,342] Trial 1131 finished with value: 0.949666691526931 and parameters: {'weight_lgbm_class_0': 0.06455573162379113, 'weight_lgbm_class_1': 0.7426135903588738, 'weight_lgbm_class_2': 0.9520214827208665, 'weight_xgb_class_0': 0.0643569261355229, 'weight_xgb_class_1': 0.5794459404887713, 'weight_xgb_class_2': 0.46424488068768904, 'weight_cat_class_0': 0.03846864183685443, 'weight_cat_class_1': 0.8190566912887804, 'weight_cat_class_2': 0.24031352252146987}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,366] Trial 1132 finished with value: 0.9487229403744203 and parameters: {'weight_lgbm_class_0': 0.13901865211391468, 'weight_lgbm_class_1': 0.7384706953401153, 'weight_lgbm_class_2': 0.9593689124669915, 'weight_xgb_class_0': 0.061820141501102294, 'weight_xgb_class_1': 0.5044684687483934, 'weight_xgb_class_2': 0.4672621218134464, 'weight_cat_class_0': 0.03910545112494393, 'weight_cat_class_1': 0.8044222188421806, 'weight_cat_class_2': 0.22261327349968832}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,447] Trial 1133 finished with value: 0.9485902552653421 and parameters: {'weight_lgbm_class_0': 0.13864488721746915, 'weight_lgbm_class_1': 0.45538195872140563, 'weight_lgbm_class_2': 0.9433865226817788, 'weight_xgb_class_0': 0.06204580436686823, 'weight_xgb_class_1': 0.5796875436589517, 'weight_xgb_class_2': 0.46667141344538765, 'weight_cat_class_0': 0.03567785713104005, 'weight_cat_class_1': 0.8178013235531472, 'weight_cat_class_2': 0.2259378420458225}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,486] Trial 1134 finished with value: 0.9262026077247918 and parameters: {'weight_lgbm_class_0': 0.6906215668696576, 'weight_lgbm_class_1': 0.7432259281400602, 'weight_lgbm_class_2': 0.9394139601755156, 'weight_xgb_class_0': 0.06407954841162421, 'weight_xgb_class_1': 0.49149053427279876, 'weight_xgb_class_2': 0.4717729825525392, 'weight_cat_class_0': 0.03276731039930472, 'weight_cat_class_1': 0.8176040861948647, 'weight_cat_class_2': 0.24380793077416013}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  57%|██████████████████████████████████████████████████████████████████████████                                                        | 1139/2000 [00:40<00:41, 20.63it/s]

[I 2026-07-03 10:23:16,564] Trial 1135 finished with value: 0.9494657454143623 and parameters: {'weight_lgbm_class_0': 0.13740345154465605, 'weight_lgbm_class_1': 0.39939306599978225, 'weight_lgbm_class_2': 0.9578267443151012, 'weight_xgb_class_0': 0.001017941488179127, 'weight_xgb_class_1': 0.4993092825895791, 'weight_xgb_class_2': 0.45638565466159603, 'weight_cat_class_0': 0.03021558008736533, 'weight_cat_class_1': 0.8181004750719694, 'weight_cat_class_2': 0.3383540008787072}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,630] Trial 1136 finished with value: 0.9485522242662069 and parameters: {'weight_lgbm_class_0': 0.14077417138506093, 'weight_lgbm_class_1': 0.7624714874197704, 'weight_lgbm_class_2': 0.9601167643426415, 'weight_xgb_class_0': 0.08887472887143365, 'weight_xgb_class_1': 0.5852334243548656, 'weight_xgb_class_2': 0.4522119188525771, 'weight_cat_class_0': 0.036640246896735514, 'weight_cat_class_1': 0.7948762148503804, 'weight_cat_class_2': 0.3296536536306337}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,677] Trial 1137 finished with value: 0.9482337150010006 and parameters: {'weight_lgbm_class_0': 0.14521356567303745, 'weight_lgbm_class_1': 0.7372465527690154, 'weight_lgbm_class_2': 0.9478675330938222, 'weight_xgb_class_0': 0.08496491502407885, 'weight_xgb_class_1': 0.5856547524058591, 'weight_xgb_class_2': 0.4503498411801694, 'weight_cat_class_0': 0.03560243161036553, 'weight_cat_class_1': 0.7273903518417886, 'weight_cat_class_2': 0.22939840627361321}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,734] Trial 1138 finished with value: 0.9494840527724387 and parameters: {'weight_lgbm_class_0': 0.06022775698189185, 'weight_lgbm_class_1': 0.7394579248237938, 'weight_lgbm_class_2': 0.9710447994115075, 'weight_xgb_class_0': 0.08935369451827724, 'weight_xgb_class_1': 0.5762913840832392, 'weight_xgb_class_2': 0.44612681576189994, 'weight_cat_class_0': 0.03520472070676079, 'weight_cat_class_1': 0.7284851664885635, 'weight_cat_class_2': 0.3343437998694696}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,763] Trial 1140 finished with value: 0.9207943619119968 and parameters: {'weight_lgbm_class_0': 0.7862827076701219, 'weight_lgbm_class_1': 0.7379197414679473, 'weight_lgbm_class_2': 0.9574815375975009, 'weight_xgb_class_0': 0.08751976659683425, 'weight_xgb_class_1': 0.589788140390515, 'weight_xgb_class_2': 0.3834995634691378, 'weight_cat_class_0': 0.030363110149922053, 'weight_cat_class_1': 0.7255006751996697, 'weight_cat_class_2': 0.33914967306753224}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  57%|██████████████████████████████████████████████████████████████████████████▎                                                       | 1144/2000 [00:41<00:38, 22.18it/s]

[I 2026-07-03 10:23:16,787] Trial 1139 finished with value: 0.9477701557403689 and parameters: {'weight_lgbm_class_0': 0.14312935152014666, 'weight_lgbm_class_1': 0.7313884703660261, 'weight_lgbm_class_2': 0.9996872127909507, 'weight_xgb_class_0': 0.09212671606342157, 'weight_xgb_class_1': 0.49572778822501334, 'weight_xgb_class_2': 0.3799976039914969, 'weight_cat_class_0': 0.037284968231584614, 'weight_cat_class_1': 0.7949898200141108, 'weight_cat_class_2': 0.16535574428073066}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,816] Trial 1141 finished with value: 0.9346907014287038 and parameters: {'weight_lgbm_class_0': 0.1406947902974745, 'weight_lgbm_class_1': 0.7360256409237104, 'weight_lgbm_class_2': 0.9255245055261585, 'weight_xgb_class_0': 0.08819618684251013, 'weight_xgb_class_1': 0.5752062099092032, 'weight_xgb_class_2': 0.4985047562034608, 'weight_cat_class_0': 0.4069220541491971, 'weight_cat_class_1': 0.7910616477926737, 'weight_cat_class_2': 0.2297882132010954}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,865] Trial 1142 finished with value: 0.9487966310502062 and parameters: {'weight_lgbm_class_0': 0.14287243378286674, 'weight_lgbm_class_1': 0.7293015683067633, 'weight_lgbm_class_2': 0.9253398173560452, 'weight_xgb_class_0': 0.087776759799356, 'weight_xgb_class_1': 0.5760811186363627, 'weight_xgb_class_2': 0.49311242110000014, 'weight_cat_class_0': 0.01837661246974045, 'weight_cat_class_1': 0.727926238079044, 'weight_cat_class_2': 0.4319890498298672}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,926] Trial 1143 finished with value: 0.949191620742038 and parameters: {'weight_lgbm_class_0': 0.1828011473226738, 'weight_lgbm_class_1': 0.5005927876855284, 'weight_lgbm_class_2': 0.925447105063188, 'weight_xgb_class_0': 0.00015682858944612854, 'weight_xgb_class_1': 0.5793960296181502, 'weight_xgb_class_2': 0.42031102311351215, 'weight_cat_class_0': 0.0006355777259809195, 'weight_cat_class_1': 0.7252158107971981, 'weight_cat_class_2': 0.16939375274218837}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:16,959] Trial 1144 finished with value: 0.9485408457255874 and parameters: {'weight_lgbm_class_0': 0.1422283063049155, 'weight_lgbm_class_1': 0.6239684593379479, 'weight_lgbm_class_2': 0.9808340265387746, 'weight_xgb_class_0': 0.08111357348996633, 'weight_xgb_class_1': 0.4028398690342227, 'weight_xgb_class_2': 0.4981993019824389, 'weight_cat_class_0': 0.01973961686203028, 'weight_cat_class_1': 0.7334257723981454, 'weight_cat_class_2': 0.3286234040085554}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  57%|██████████████████████████████████████████████████████████████████████████▌                                                       | 1148/2000 [00:41<00:37, 22.70it/s]

[I 2026-07-03 10:23:17,007] Trial 1145 finished with value: 0.9496498494643423 and parameters: {'weight_lgbm_class_0': 0.05080088168565977, 'weight_lgbm_class_1': 0.7349722714365964, 'weight_lgbm_class_2': 0.9223648217788927, 'weight_xgb_class_0': 0.0855893907358697, 'weight_xgb_class_1': 0.41930478874136184, 'weight_xgb_class_2': 0.44570827391266477, 'weight_cat_class_0': 0.015024719555277084, 'weight_cat_class_1': 0.7255745007817828, 'weight_cat_class_2': 0.34041395460981627}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:17,043] Trial 1146 finished with value: 0.9494928927619645 and parameters: {'weight_lgbm_class_0': 0.05585993916023935, 'weight_lgbm_class_1': 0.5275116276379188, 'weight_lgbm_class_2': 0.8612087879435109, 'weight_xgb_class_0': 0.08848688428324737, 'weight_xgb_class_1': 0.41941582440637976, 'weight_xgb_class_2': 0.49916589107564285, 'weight_cat_class_0': 0.017678800025211924, 'weight_cat_class_1': 0.7350853723221458, 'weight_cat_class_2': 0.33953722695466043}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:17,133] Trial 1147 finished with value: 0.9496607149430161 and parameters: {'weight_lgbm_class_0': 0.05397990845195716, 'weight_lgbm_class_1': 0.7323790309248885, 'weight_lgbm_class_2': 0.8636007802842774, 'weight_xgb_class_0': 0.08648968496969626, 'weight_xgb_class_1': 0.5824904187554071, 'weight_xgb_class_2': 0.42097194323134124, 'weight_cat_class_0': 0.016993353457488806, 'weight_cat_class_1': 0.7297538702157664, 'weight_cat_class_2': 0.4189171299891909}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:17,155] Trial 1148 finished with value: 0.9497034930382929 and parameters: {'weight_lgbm_class_0': 0.027727710587460243, 'weight_lgbm_class_1': 0.6254925691226891, 'weight_lgbm_class_2': 0.8617772236373787, 'weight_xgb_class_0': 0.08776592996962854, 'weight_xgb_class_1': 0.4294854234604833, 'weight_xgb_class_2': 0.38137078495364046, 'weight_cat_class_0': 0.015476691861889528, 'weight_cat_class_1': 0.7368059261576546, 'weight_cat_class_2': 0.43477227088018194}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  58%|██████████████████████████████████████████████████████████████████████████▉                                                       | 1153/2000 [00:41<00:40, 21.03it/s]

[I 2026-07-03 10:23:17,252] Trial 1150 finished with value: 0.9442713966976201 and parameters: {'weight_lgbm_class_0': 0.029568206295871882, 'weight_lgbm_class_1': 0.6353948054490789, 'weight_lgbm_class_2': 0.8590912031295415, 'weight_xgb_class_0': 0.0005981767587130982, 'weight_xgb_class_1': 0.4790166625729979, 'weight_xgb_class_2': 0.4208791139337002, 'weight_cat_class_0': 1.3964951364995996e-05, 'weight_cat_class_1': 0.744096884557736, 'weight_cat_class_2': 0.43576639564878206}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:17,252] Trial 1149 finished with value: 0.9481064646350926 and parameters: {'weight_lgbm_class_0': 0.05593597482511806, 'weight_lgbm_class_1': 0.6304876120371683, 'weight_lgbm_class_2': 0.8538929171048554, 'weight_xgb_class_0': 0.00034246699882947707, 'weight_xgb_class_1': 0.42393693807609756, 'weight_xgb_class_2': 0.39032718323019905, 'weight_cat_class_0': 0.0002298146284703327, 'weight_cat_class_1': 0.7379937771547962, 'weight_cat_class_2': 0.43642283583193475}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:17,294] Trial 1151 finished with value: 0.948597851318583 and parameters: {'weight_lgbm_class_0': 0.05448655081653212, 'weight_lgbm_class_1': 0.6694949017240003, 'weight_lgbm_class_2': 0.8553644630760271, 'weight_xgb_class_0': 0.0016878572057274208, 'weight_xgb_class_1': 0.40490403012977444, 'weight_xgb_class_2': 0.4968923950023395, 'weight_cat_class_0': 0.014619504452395075, 'weight_cat_class_1': 0.7430932242693984, 'weight_cat_class_2': 0.4084925991823093}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:17,373] Trial 1152 finished with value: 0.9472638152653189 and parameters: {'weight_lgbm_class_0': 0.02732077155258903, 'weight_lgbm_class_1': 0.6766187222316393, 'weight_lgbm_class_2': 0.8762923758084367, 'weight_xgb_class_0': 0.001474894520263373, 'weight_xgb_class_1': 0.42521105627006583, 'weight_xgb_class_2': 0.41549523929796944, 'weight_cat_class_0': 0.018286381273952695, 'weight_cat_class_1': 0.7534583509383456, 'weight_cat_class_2': 0.4340305177392907}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:17,395] Trial 1153 finished with value: 0.9490562064035252 and parameters: {'weight_lgbm_class_0': 0.179389033991377, 'weight_lgbm_class_1': 0.6281246658726015, 'weight_lgbm_class_2': 0.9199283572929715, 'weight_xgb_class_0': 0.03641481465602761, 'weight_xgb_class_1': 0.42396231310923, 'weight_xgb_class_2': 0.4135581451241587, 'weight_cat_class_0': 0.0015603690176046927, 'weight_cat_class_1': 0.7468845297442234, 'weight_cat_class_2': 0.42717622531289606}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:17,479] Trial 1154 finished with value: 0.9486949928238122 and parameters: {'weight_lgbm_class_0': 0.05318957152436973, 'weight_lgbm_class_1': 0.5009258256963114, 'weight_lgbm_class_2': 0.8516136354145293, 'weight_xgb_class_0': 0.001005785863096277, 'weight_xgb_class_1': 0.43080860138465416, 'weight_xgb_class_2': 0.4162613043950396, 'weight_cat_class_0': 0.015691466795556552, 'weight_cat_class_1': 0.7435047766640324, 'weight_cat_class_2': 0.3999893754776199}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:17,488] Trial 1155 finished with value: 0.9484853071274099 and parameters: {'weight_lgbm_class_0': 0.05048802039101259, 'weight_lgbm_class_1': 0.6769386569800432, 'weight_lgbm_class_2': 0.8635709771777316, 'weight_xgb_class_0': 0.0002252701690084129, 'weight_xgb_class_1': 0.42951496051559934, 'weight_xgb_class_2': 0.41271165357303696, 'weight_cat_class_0': 0.01549722721509144, 'weight_cat_class_1': 0.746268676142019, 'weight_cat_class_2': 0.3945566376547056}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:17,513] Trial 1156 finished with value: 0.9460570051504007 and parameters: {'weight_lgbm_class_0': 0.02222278442663505, 'weight_lgbm_class_1': 0.7118755626839893, 'weight_lgbm_class_2': 0.8563215971375568, 'weight_xgb_class_0': 0.0007816673400600667, 'weight_xgb_class_1': 0.4739140586830234, 'weight_xgb_class_2': 0.423742185253393, 'weight_cat_class_0': 0.015559411492810489, 'weight_cat_class_1': 0.7524764973341587, 'weight_cat_class_2': 0.40481054968441027}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:17,561] Trial 1157 finished with value: 0.9480229611275806 and parameters: {'weight_lgbm_class_0': 0.023943784938809796, 'weight_lgbm_class_1': 0.6781640469365907, 'weight_lgbm_class_2': 0.8577463893512259, 'weight_xgb_class_0': 0.033008156210603344, 'weight_xgb_class_1': 0.4793341804974613, 'weight_xgb_class_2': 0.40216548434115973, 'weight_cat_class_0': 0.0004245129226173247, 'weight_cat_class_1': 0.754244742230923, 'weight_cat_class_2': 0.4063049356360176}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:17,570] Trial 1158 finished with value: 0.9469981410309698 and parameters: {'weight_lgbm_class_0': 0.024408756926113967, 'weight_lgbm_class_1': 0.6838685854425887, 'weight_lgbm_class_2': 0.8692414553919963, 'weight_xgb_class_0': 0.0002912377602960806, 'weight_xgb_class_1': 0.47641082070113006, 'weight_xgb_class_2': 0.40985878828942346, 'weight_cat_class_0': 0.01417932472170472, 'weight_cat_class_1': 0.2551216594466378, 'weight_cat_class_2': 0.45859763560721684}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:17,680] Trial 1159 finished with value: 0.9495502051746564 and parameters: {'weight_lgbm_class_0': 0.12143279399531239, 'weight_lgbm_class_1': 0.6773709982750818, 'weight_lgbm_class_2': 0.8713101832745067, 'weight_xgb_class_0': 0.03448566519088529, 'weight_xgb_class_1': 0.4807633874255361, 'weight_xgb_class_2': 0.4013715094103821, 'weight_cat_class_0': 0.015429183165587649, 'weight_cat_class_1': 0.7532643925275223, 'weight_cat_class_2': 0.4252555378538061}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:17,719] Trial 1160 finished with value: 0.9495422559513522 and parameters: {'weight_lgbm_class_0': 0.12055315696175632, 'weight_lgbm_class_1': 0.6852663262508613, 'weight_lgbm_class_2': 0.8836259407308391, 'weight_xgb_class_0': 0.037299097690923995, 'weight_xgb_class_1': 0.472930397015047, 'weight_xgb_class_2': 0.4005152158456943, 'weight_cat_class_0': 0.016557041114050885, 'weight_cat_class_1': 0.7491577560707007, 'weight_cat_class_2': 0.4522354808509437}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:17,783] Trial 1161 finished with value: 0.9496637149890615 and parameters: {'weight_lgbm_class_0': 0.11856254469193776, 'weight_lgbm_class_1': 0.6813964315008991, 'weight_lgbm_class_2': 0.8815269240485647, 'weight_xgb_class_0': 0.04357448180205452, 'weight_xgb_class_1': 0.5373500232693884, 'weight_xgb_class_2': 0.4836335977569717, 'weight_cat_class_0': 6.328906831859667e-05, 'weight_cat_class_1': 0.7899081499028573, 'weight_cat_class_2': 0.4050446768220514}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:17,849] Trial 1163 finished with value: 0.9497101634162902 and parameters: {'weight_lgbm_class_0': 0.11607355677130954, 'weight_lgbm_class_1': 0.6786682580221298, 'weight_lgbm_class_2': 0.8799470158683294, 'weight_xgb_class_0': 0.03302888688864811, 'weight_xgb_class_1': 0.4710126633525177, 'weight_xgb_class_2': 0.402259156284955, 'weight_cat_class_0': 0.0005486420270900683, 'weight_cat_class_1': 0.7838898447654403, 'weight_cat_class_2': 0.3998085271028139}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:17,892] Trial 1162 finished with value: 0.9492651775090121 and parameters: {'weight_lgbm_class_0': 0.09815439631417021, 'weight_lgbm_class_1': 0.6779466666907177, 'weight_lgbm_class_2': 0.8859561690278337, 'weight_xgb_class_0': 0.03710642316520435, 'weight_xgb_class_1': 0.4514167520735753, 'weight_xgb_class_2': 0.4020384315157862, 'weight_cat_class_0': 0.050816343387887784, 'weight_cat_class_1': 0.789683112679995, 'weight_cat_class_2': 0.26312834495417536}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  58%|████████████████████████████████████████████████████████████████████████████                                                      | 1170/2000 [00:42<00:36, 22.65it/s]

[I 2026-07-03 10:23:17,907] Trial 1164 finished with value: 0.9434695634180722 and parameters: {'weight_lgbm_class_0': 0.11868608841591943, 'weight_lgbm_class_1': 0.710724408324098, 'weight_lgbm_class_2': 0.8814044460222954, 'weight_xgb_class_0': 0.03674455158341808, 'weight_xgb_class_1': 0.5377890690987047, 'weight_xgb_class_2': 0.4809813948105908, 'weight_cat_class_0': 0.3068687639992704, 'weight_cat_class_1': 0.7800580845837496, 'weight_cat_class_2': 0.4651348027478738}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:17,952] Trial 1165 finished with value: 0.9448763754050851 and parameters: {'weight_lgbm_class_0': 0.11697886065163846, 'weight_lgbm_class_1': 0.711908378460076, 'weight_lgbm_class_2': 0.9994684426549891, 'weight_xgb_class_0': 0.03627699690160947, 'weight_xgb_class_1': 0.46132270482587684, 'weight_xgb_class_2': 0.48660249975624903, 'weight_cat_class_0': 0.24424521087569312, 'weight_cat_class_1': 0.7923766568011624, 'weight_cat_class_2': 0.26409721332778335}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:18,004] Trial 1166 finished with value: 0.9487699287978376 and parameters: {'weight_lgbm_class_0': 0.11555509841562027, 'weight_lgbm_class_1': 0.3473054324225049, 'weight_lgbm_class_2': 0.9118212644056819, 'weight_xgb_class_0': 0.03794475086479554, 'weight_xgb_class_1': 0.4757146086477469, 'weight_xgb_class_2': 0.48123840710985316, 'weight_cat_class_0': 0.05030464296805022, 'weight_cat_class_1': 0.7871813752354531, 'weight_cat_class_2': 0.17636428901611778}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:18,059] Trial 1168 finished with value: 0.9492887094718457 and parameters: {'weight_lgbm_class_0': 0.12023918341082358, 'weight_lgbm_class_1': 0.6930251407734, 'weight_lgbm_class_2': 0.9101736430816313, 'weight_xgb_class_0': 0.036347155961553086, 'weight_xgb_class_1': 0.5369103753548843, 'weight_xgb_class_2': 0.47789459353507957, 'weight_cat_class_0': 0.05155822745781478, 'weight_cat_class_1': 0.7929880052081358, 'weight_cat_class_2': 0.4623243673952946}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:18,084] Trial 1167 finished with value: 0.9496894332271792 and parameters: {'weight_lgbm_class_0': 0.10051747062700564, 'weight_lgbm_class_1': 0.7116417887316493, 'weight_lgbm_class_2': 0.7704045351500813, 'weight_xgb_class_0': 0.03437220887814145, 'weight_xgb_class_1': 0.5423418885041246, 'weight_xgb_class_2': 0.48072123668093014, 'weight_cat_class_0': 9.141442038227711e-05, 'weight_cat_class_1': 0.3937937791429524, 'weight_cat_class_2': 0.2555156757643392}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:18,114] Trial 1170 finished with value: 0.9477148810611947 and parameters: {'weight_lgbm_class_0': 0.10407331559416466, 'weight_lgbm_class_1': 0.23404832075946252, 'weight_lgbm_class_2': 0.9119313467902673, 'weight_xgb_class_0': 0.0509631752357377, 'weight_xgb_class_1': 0.5432017046923252, 'weight_xgb_class_2': 0.48208954305557167, 'weight_cat_class_0': 0.11023315158971458, 'weight_cat_class_1': 0.7787513120222568, 'weight_cat_class_2': 0.4639398563442299}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:18,134] Trial 1169 finished with value: 0.9143160032596902 and parameters: {'weight_lgbm_class_0': 0.11232381955845633, 'weight_lgbm_class_1': 0.7155365507431704, 'weight_lgbm_class_2': 0.7660874452784661, 'weight_xgb_class_0': 0.050527048187666866, 'weight_xgb_class_1': 0.5373314075196828, 'weight_xgb_class_2': 0.48256483490830987, 'weight_cat_class_0': 0.8747820613556505, 'weight_cat_class_1': 0.7897746131424874, 'weight_cat_class_2': 0.46707314461462524}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  59%|████████████████████████████████████████████████████████████████████████████▍                                                     | 1175/2000 [00:42<00:40, 20.52it/s]

[I 2026-07-03 10:23:18,252] Trial 1171 finished with value: 0.9484620449836099 and parameters: {'weight_lgbm_class_0': 0.10268699370380704, 'weight_lgbm_class_1': 0.7118296006744714, 'weight_lgbm_class_2': 0.9077758962032203, 'weight_xgb_class_0': 0.05082284305124507, 'weight_xgb_class_1': 0.4540716400092884, 'weight_xgb_class_2': 0.48294784580581446, 'weight_cat_class_0': 0.09830928076385925, 'weight_cat_class_1': 0.7850983078234893, 'weight_cat_class_2': 0.25424875188095614}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:18,271] Trial 1172 finished with value: 0.9491841325866056 and parameters: {'weight_lgbm_class_0': 0.09606739436851842, 'weight_lgbm_class_1': 0.716333021804975, 'weight_lgbm_class_2': 0.9093408383075029, 'weight_xgb_class_0': 0.05223815971767196, 'weight_xgb_class_1': 0.543224030498843, 'weight_xgb_class_2': 0.4843550299493134, 'weight_cat_class_0': 0.05266352583231214, 'weight_cat_class_1': 0.7853298989378538, 'weight_cat_class_2': 0.2609922672413796}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:18,319] Trial 1173 finished with value: 0.9484975669093427 and parameters: {'weight_lgbm_class_0': 0.10211778690942667, 'weight_lgbm_class_1': 0.7100361346915626, 'weight_lgbm_class_2': 0.9005036066619202, 'weight_xgb_class_0': 0.054373248401647686, 'weight_xgb_class_1': 0.5441938916395339, 'weight_xgb_class_2': 0.4848485574416971, 'weight_cat_class_0': 0.09733829588050529, 'weight_cat_class_1': 0.792125726434414, 'weight_cat_class_2': 0.2644827959357384}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:18,409] Trial 1174 finished with value: 0.9201659788473507 and parameters: {'weight_lgbm_class_0': 0.09396659551717415, 'weight_lgbm_class_1': 0.7090013256416994, 'weight_lgbm_class_2': 0.9029535903011388, 'weight_xgb_class_0': 0.6324617659712366, 'weight_xgb_class_1': 0.5405543870547542, 'weight_xgb_class_2': 0.5049967909981353, 'weight_cat_class_0': 0.05242790197131125, 'weight_cat_class_1': 0.31665028900837566, 'weight_cat_class_2': 0.2651243944284692}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  59%|████████████████████████████████████████████████████████████████████████████▊                                                     | 1181/2000 [00:42<00:35, 23.03it/s]

[I 2026-07-03 10:23:18,460] Trial 1175 finished with value: 0.9484902447107953 and parameters: {'weight_lgbm_class_0': 0.09473716984732623, 'weight_lgbm_class_1': 0.7143247096788685, 'weight_lgbm_class_2': 0.9056741861633588, 'weight_xgb_class_0': 0.0560271478299299, 'weight_xgb_class_1': 0.5433456030728648, 'weight_xgb_class_2': 0.513676271456676, 'weight_cat_class_0': 0.09944139644520793, 'weight_cat_class_1': 0.7728695294390793, 'weight_cat_class_2': 0.17416992298856443}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:18,484] Trial 1176 finished with value: 0.9493136020475751 and parameters: {'weight_lgbm_class_0': 0.09789553714042161, 'weight_lgbm_class_1': 0.7698668818691441, 'weight_lgbm_class_2': 0.7706079360650085, 'weight_xgb_class_0': 0.02103618729547438, 'weight_xgb_class_1': 0.5399668702217999, 'weight_xgb_class_2': 0.5086278678098543, 'weight_cat_class_0': 0.051962170973954155, 'weight_cat_class_1': 0.7770847848484719, 'weight_cat_class_2': 0.17421799145550748}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:18,512] Trial 1177 finished with value: 0.9487382096245102 and parameters: {'weight_lgbm_class_0': 0.09478266827433854, 'weight_lgbm_class_1': 0.7782570517709974, 'weight_lgbm_class_2': 0.9134611983767857, 'weight_xgb_class_0': 0.04907244483940125, 'weight_xgb_class_1': 0.5438886941644377, 'weight_xgb_class_2': 0.5062757293993944, 'weight_cat_class_0': 0.09245783431583193, 'weight_cat_class_1': 0.7698245259913358, 'weight_cat_class_2': 0.17415010571185022}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:18,569] Trial 1178 finished with value: 0.9489705262093384 and parameters: {'weight_lgbm_class_0': 0.10566147897909395, 'weight_lgbm_class_1': 0.7552977865274285, 'weight_lgbm_class_2': 0.912308978478215, 'weight_xgb_class_0': 0.06070353826424774, 'weight_xgb_class_1': 0.5357286597336848, 'weight_xgb_class_2': 0.4420122740254345, 'weight_cat_class_0': 0.04110054729934275, 'weight_cat_class_1': 0.5263120092018642, 'weight_cat_class_2': 0.2503848856317188}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:18,610] Trial 1179 finished with value: 0.9491004531016669 and parameters: {'weight_lgbm_class_0': 0.0963318982605993, 'weight_lgbm_class_1': 0.7127430501429519, 'weight_lgbm_class_2': 0.8128088602170248, 'weight_xgb_class_0': 0.05811935596292549, 'weight_xgb_class_1': 0.49526257377560823, 'weight_xgb_class_2': 0.5054762668314076, 'weight_cat_class_0': 0.04873367194548172, 'weight_cat_class_1': 0.7686720695837589, 'weight_cat_class_2': 0.2958175096861334}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:18,613] Trial 1180 finished with value: 0.9483865664072452 and parameters: {'weight_lgbm_class_0': 0.09375095378987586, 'weight_lgbm_class_1': 0.7705585602589643, 'weight_lgbm_class_2': 0.8114121471264105, 'weight_xgb_class_0': 0.06088026818611482, 'weight_xgb_class_1': 0.5000733239059632, 'weight_xgb_class_2': 0.5104691394731123, 'weight_cat_class_0': 0.10049394873545883, 'weight_cat_class_1': 0.7102880061960057, 'weight_cat_class_2': 0.2992546539523577}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:18,668] Trial 1181 finished with value: 0.9485720560048838 and parameters: {'weight_lgbm_class_0': 0.09353907691002562, 'weight_lgbm_class_1': 0.7722856940095073, 'weight_lgbm_class_2': 0.8175147605589932, 'weight_xgb_class_0': 0.058235945135971925, 'weight_xgb_class_1': 0.5016945816225518, 'weight_xgb_class_2': 0.5045564806370029, 'weight_cat_class_0': 0.09446162097175426, 'weight_cat_class_1': 0.7127388585514575, 'weight_cat_class_2': 0.30160342818153146}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  59%|████████████████████████████████████████████████████████████████████████████▉                                                     | 1184/2000 [00:43<00:39, 20.60it/s]

[I 2026-07-03 10:23:18,671] Trial 1182 finished with value: 0.932712187178354 and parameters: {'weight_lgbm_class_0': 0.09277173625743856, 'weight_lgbm_class_1': 0.7733899399268923, 'weight_lgbm_class_2': 0.8092628769135284, 'weight_xgb_class_0': 0.05875619472084985, 'weight_xgb_class_1': 0.5001875878070763, 'weight_xgb_class_2': 0.5068930229303172, 'weight_cat_class_0': 0.49976561402655284, 'weight_cat_class_1': 0.7702936210379504, 'weight_cat_class_2': 0.2535128165072837}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:18,815] Trial 1184 finished with value: 0.9496872956511577 and parameters: {'weight_lgbm_class_0': 0.09069014320680488, 'weight_lgbm_class_1': 0.7697738775100101, 'weight_lgbm_class_2': 0.9268439614997734, 'weight_xgb_class_0': 0.02170702238789151, 'weight_xgb_class_1': 0.4978417227613242, 'weight_xgb_class_2': 0.5104243220092818, 'weight_cat_class_0': 0.04828332919717889, 'weight_cat_class_1': 0.7701415747433642, 'weight_cat_class_2': 0.21574118318723398}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:18,823] Trial 1183 finished with value: 0.9496806163756685 and parameters: {'weight_lgbm_class_0': 0.05157100923555451, 'weight_lgbm_class_1': 0.7699144461220587, 'weight_lgbm_class_2': 0.9248546241558036, 'weight_xgb_class_0': 0.06103084461733726, 'weight_xgb_class_1': 0.5022014058180236, 'weight_xgb_class_2': 0.4408266846583714, 'weight_cat_class_0': 0.047141811615082144, 'weight_cat_class_1': 0.7067201787488704, 'weight_cat_class_2': 0.29568664179054305}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  60%|█████████████████████████████████████████████████████████████████████████████▎                                                    | 1190/2000 [00:43<00:37, 21.74it/s]

[I 2026-07-03 10:23:18,927] Trial 1185 finished with value: 0.9490500046512085 and parameters: {'weight_lgbm_class_0': 0.04904620578775672, 'weight_lgbm_class_1': 0.7686520454153701, 'weight_lgbm_class_2': 0.23478557641864256, 'weight_xgb_class_0': 0.02110927860884561, 'weight_xgb_class_1': 0.6298937745643671, 'weight_xgb_class_2': 0.5094581815656821, 'weight_cat_class_0': 0.0466489200210205, 'weight_cat_class_1': 0.7122710893597283, 'weight_cat_class_2': 0.11695675590158844}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:18,956] Trial 1186 finished with value: 0.9495421795779899 and parameters: {'weight_lgbm_class_0': 0.047894348532094, 'weight_lgbm_class_1': 0.7622627537791133, 'weight_lgbm_class_2': 0.9870370593000575, 'weight_xgb_class_0': 0.020408385489522778, 'weight_xgb_class_1': 0.5004202491511389, 'weight_xgb_class_2': 0.4413540258389895, 'weight_cat_class_0': 0.03726949140024897, 'weight_cat_class_1': 0.7684787059997679, 'weight_cat_class_2': 0.3008489290491955}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,011] Trial 1188 finished with value: 0.9496693701449921 and parameters: {'weight_lgbm_class_0': 0.0534858672559124, 'weight_lgbm_class_1': 0.7577216889080469, 'weight_lgbm_class_2': 0.8086520470370689, 'weight_xgb_class_0': 0.018719393048865926, 'weight_xgb_class_1': 0.5004381169314253, 'weight_xgb_class_2': 0.4434011687021435, 'weight_cat_class_0': 0.03595400204326479, 'weight_cat_class_1': 0.7065454290217807, 'weight_cat_class_2': 0.2939172939790281}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,016] Trial 1187 finished with value: 0.9494751464585516 and parameters: {'weight_lgbm_class_0': 0.04922027167876872, 'weight_lgbm_class_1': 0.6609087561789642, 'weight_lgbm_class_2': 0.9838592454117685, 'weight_xgb_class_0': 0.019813120891277444, 'weight_xgb_class_1': 0.6358108928022752, 'weight_xgb_class_2': 0.44747341554724474, 'weight_cat_class_0': 0.03473344469996859, 'weight_cat_class_1': 0.7670622807631613, 'weight_cat_class_2': 0.29952387046311035}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,059] Trial 1189 finished with value: 0.9484318748327446 and parameters: {'weight_lgbm_class_0': 0.045486789627295285, 'weight_lgbm_class_1': 0.7633874666594876, 'weight_lgbm_class_2': 0.8133684171804713, 'weight_xgb_class_0': 0.015754287343918986, 'weight_xgb_class_1': 0.5041679331219551, 'weight_xgb_class_2': 0.44267426466984283, 'weight_cat_class_0': 0.0003348526690935403, 'weight_cat_class_1': 0.7170279584328395, 'weight_cat_class_2': 0.21438081283045135}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,102] Trial 1190 finished with value: 0.9497603912397495 and parameters: {'weight_lgbm_class_0': 0.05615226064989502, 'weight_lgbm_class_1': 0.6424536108600651, 'weight_lgbm_class_2': 0.814009204917627, 'weight_xgb_class_0': 0.019358426028708717, 'weight_xgb_class_1': 0.49898452336311777, 'weight_xgb_class_2': 0.44089056283398254, 'weight_cat_class_0': 0.03153440298734079, 'weight_cat_class_1': 0.7619351064322593, 'weight_cat_class_2': 0.10969602665264527}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:19,184] Trial 1192 finished with value: 0.9221145233838 and parameters: {'weight_lgbm_class_0': 0.04859262752608007, 'weight_lgbm_class_1': 0.7621066360764088, 'weight_lgbm_class_2': 0.9696859612114253, 'weight_xgb_class_0': 0.7397162408101458, 'weight_xgb_class_1': 0.49818800827687526, 'weight_xgb_class_2': 0.4352785759297927, 'weight_cat_class_0': 0.03225632102674344, 'weight_cat_class_1': 0.7058681998276353, 'weight_cat_class_2': 0.2258360546211087}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,197] Trial 1191 finished with value: 0.9494725629316116 and parameters: {'weight_lgbm_class_0': 0.04528513999017073, 'weight_lgbm_class_1': 0.6507654043940418, 'weight_lgbm_class_2': 0.9714502392695579, 'weight_xgb_class_0': 0.017899730691350455, 'weight_xgb_class_1': 0.5026825836496506, 'weight_xgb_class_2': 0.43617073149610697, 'weight_cat_class_0': 0.03180954957199777, 'weight_cat_class_1': 0.756041124189713, 'weight_cat_class_2': 0.2129879530613181}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,211] Trial 1193 finished with value: 0.94953357587685 and parameters: {'weight_lgbm_class_0': 0.05217573038614695, 'weight_lgbm_class_1': 0.6578886161082205, 'weight_lgbm_class_2': 0.9642247425530507, 'weight_xgb_class_0': 0.015174049157802409, 'weight_xgb_class_1': 0.44942871280052127, 'weight_xgb_class_2': 0.4450360033351116, 'weight_cat_class_0': 0.033014049766743415, 'weight_cat_class_1': 0.7647314073864531, 'weight_cat_class_2': 0.22469011621856988}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,273] Trial 1194 finished with value: 0.9494409240770149 and parameters: {'weight_lgbm_class_0': 0.053424994821981805, 'weight_lgbm_class_1': 0.7545097952757759, 'weight_lgbm_class_2': 0.9840490650901921, 'weight_xgb_class_0': 0.020612355616663816, 'weight_xgb_class_1': 0.6317475220653965, 'weight_xgb_class_2': 0.4299318897809944, 'weight_cat_class_0': 0.030614129368322043, 'weight_cat_class_1': 0.7128377213921945, 'weight_cat_class_2': 0.3684866026745359}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  60%|█████████████████████████████████████████████████████████████████████████████▉                                                    | 1199/2000 [00:43<00:38, 21.01it/s]

[I 2026-07-03 10:23:19,389] Trial 1196 finished with value: 0.9490406706494926 and parameters: {'weight_lgbm_class_0': 0.06598950804814412, 'weight_lgbm_class_1': 0.6534715106629306, 'weight_lgbm_class_2': 0.96766646747356, 'weight_xgb_class_0': 0.017114846095090275, 'weight_xgb_class_1': 0.6398075919243775, 'weight_xgb_class_2': 0.4431036000572753, 'weight_cat_class_0': 9.533535518895577e-05, 'weight_cat_class_1': 0.762197241203186, 'weight_cat_class_2': 0.21612068801621442}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,394] Trial 1195 finished with value: 0.9088555653265299 and parameters: {'weight_lgbm_class_0': 0.06612833419372914, 'weight_lgbm_class_1': 0.6576081021859846, 'weight_lgbm_class_2': 0.9771492543834868, 'weight_xgb_class_0': 0.9589050799226561, 'weight_xgb_class_1': 0.4511983853923913, 'weight_xgb_class_2': 0.44193214915802703, 'weight_cat_class_0': 0.027834496026012002, 'weight_cat_class_1': 0.8025293829781625, 'weight_cat_class_2': 0.21396185949367766}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,482] Trial 1197 finished with value: 0.9490079821343693 and parameters: {'weight_lgbm_class_0': 0.06523397033184679, 'weight_lgbm_class_1': 0.6939421138835035, 'weight_lgbm_class_2': 0.9737905815095307, 'weight_xgb_class_0': 0.013996196148397439, 'weight_xgb_class_1': 0.45156940560508024, 'weight_xgb_class_2': 0.4492557652173359, 'weight_cat_class_0': 0.0005594148943432291, 'weight_cat_class_1': 0.7993341244689681, 'weight_cat_class_2': 0.20977096743610585}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,494] Trial 1198 finished with value: 0.9496443268036683 and parameters: {'weight_lgbm_class_0': 0.06686878714067912, 'weight_lgbm_class_1': 0.6522202551496032, 'weight_lgbm_class_2': 0.9567477547245158, 'weight_xgb_class_0': 0.018496199615054134, 'weight_xgb_class_1': 0.4459492250732994, 'weight_xgb_class_2': 0.4475951837026246, 'weight_cat_class_0': 0.027997995161716985, 'weight_cat_class_1': 0.8045505004935648, 'weight_cat_class_2': 0.31949170611659977}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,575] Trial 1199 finished with value: 0.9492991350187868 and parameters: {'weight_lgbm_class_0': 0.06819775560644117, 'weight_lgbm_class_1': 0.6452005695059314, 'weight_lgbm_class_2': 0.9690487870279955, 'weight_xgb_class_0': 0.020133638471714607, 'weight_xgb_class_1': 0.39284026381555204, 'weight_xgb_class_2': 0.45123293554116856, 'weight_cat_class_0': 0.0006892520583162837, 'weight_cat_class_1': 0.8000908416903578, 'weight_cat_class_2': 0.21806778955200234}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  60%|██████████████████████████████████████████████████████████████████████████████▎                                                   | 1205/2000 [00:43<00:36, 21.72it/s]

[I 2026-07-03 10:23:19,590] Trial 1200 finished with value: 0.9492491164003298 and parameters: {'weight_lgbm_class_0': 0.06874995293057752, 'weight_lgbm_class_1': 0.6600547418592738, 'weight_lgbm_class_2': 0.8387564005601396, 'weight_xgb_class_0': 0.09800369227031808, 'weight_xgb_class_1': 0.4492259345632125, 'weight_xgb_class_2': 0.4536779193440199, 'weight_cat_class_0': 0.02377990897912204, 'weight_cat_class_1': 0.8289529494881582, 'weight_cat_class_2': 0.37926431897234525}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,620] Trial 1202 finished with value: 0.9495352679001078 and parameters: {'weight_lgbm_class_0': 0.06891695105452599, 'weight_lgbm_class_1': 0.6151699178825049, 'weight_lgbm_class_2': 0.8371949845546119, 'weight_xgb_class_0': 0.019299979977336058, 'weight_xgb_class_1': 0.45072086561941005, 'weight_xgb_class_2': 0.9570242427344691, 'weight_cat_class_0': 0.08137838066885146, 'weight_cat_class_1': 0.7986650680487419, 'weight_cat_class_2': 0.1312247354349579}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,622] Trial 1201 finished with value: 0.9492294388297075 and parameters: {'weight_lgbm_class_0': 0.07053182309406135, 'weight_lgbm_class_1': 0.6010202243137531, 'weight_lgbm_class_2': 0.8328452599124039, 'weight_xgb_class_0': 0.020586722629666716, 'weight_xgb_class_1': 0.5621641473175552, 'weight_xgb_class_2': 0.45778487647346283, 'weight_cat_class_0': 0.08029796062453085, 'weight_cat_class_1': 0.7984114372254686, 'weight_cat_class_2': 0.1317986163315232}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,759] Trial 1204 finished with value: 0.9493859087099383 and parameters: {'weight_lgbm_class_0': 0.06957449140437197, 'weight_lgbm_class_1': 0.6399749180390343, 'weight_lgbm_class_2': 0.8267902127558927, 'weight_xgb_class_0': 0.01800746445185291, 'weight_xgb_class_1': 0.5616359329638396, 'weight_xgb_class_2': 0.4566694974085358, 'weight_cat_class_0': 0.06862677455042951, 'weight_cat_class_1': 0.8041288193006977, 'weight_cat_class_2': 0.06745494228195761}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,773] Trial 1205 finished with value: 0.9492607304479875 and parameters: {'weight_lgbm_class_0': 0.07144765213559831, 'weight_lgbm_class_1': 0.6404763411592913, 'weight_lgbm_class_2': 0.8398560066625089, 'weight_xgb_class_0': 0.01825936065530387, 'weight_xgb_class_1': 0.45088438899008376, 'weight_xgb_class_2': 0.45831114444203425, 'weight_cat_class_0': 0.07291514493277652, 'weight_cat_class_1': 0.8215625880955447, 'weight_cat_class_2': 0.06454507627719774}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,780] Trial 1203 finished with value: 0.9494696479300817 and parameters: {'weight_lgbm_class_0': 0.07130127454448788, 'weight_lgbm_class_1': 0.6411463368119317, 'weight_lgbm_class_2': 0.8463783808222323, 'weight_xgb_class_0': 0.01729481751253105, 'weight_xgb_class_1': 0.4463538739278908, 'weight_xgb_class_2': 0.45464476616255023, 'weight_cat_class_0': 0.0698981424491302, 'weight_cat_class_1': 0.8018637029415888, 'weight_cat_class_2': 0.13078398490368584}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  60%|██████████████████████████████████████████████████████████████████████████████▋                                                   | 1210/2000 [00:44<00:38, 20.50it/s]

[I 2026-07-03 10:23:19,814] Trial 1206 finished with value: 0.9495922409947478 and parameters: {'weight_lgbm_class_0': 0.06579339348912482, 'weight_lgbm_class_1': 0.5954265993805272, 'weight_lgbm_class_2': 0.8308108444917305, 'weight_xgb_class_0': 0.02241093419479133, 'weight_xgb_class_1': 0.40032397857344537, 'weight_xgb_class_2': 0.4539085081137773, 'weight_cat_class_0': 0.0680013252593657, 'weight_cat_class_1': 0.8058458686281689, 'weight_cat_class_2': 0.3284357386819733}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,941] Trial 1208 finished with value: 0.9497569605035611 and parameters: {'weight_lgbm_class_0': 0.026391666641101128, 'weight_lgbm_class_1': 0.6100252650747086, 'weight_lgbm_class_2': 0.8180349413304734, 'weight_xgb_class_0': 0.0004621071010566958, 'weight_xgb_class_1': 0.39494105237297283, 'weight_xgb_class_2': 0.45805618013668836, 'weight_cat_class_0': 0.08093018379023709, 'weight_cat_class_1': 0.8257297000757491, 'weight_cat_class_2': 0.09040120578424823}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:19,966] Trial 1207 finished with value: 0.9493962964700166 and parameters: {'weight_lgbm_class_0': 0.02426932551691434, 'weight_lgbm_class_1': 0.5922848461085013, 'weight_lgbm_class_2': 0.8265718512311895, 'weight_xgb_class_0': 0.0008008538154777314, 'weight_xgb_class_1': 0.39737140880262034, 'weight_xgb_class_2': 0.46162222558068, 'weight_cat_class_0': 0.07476078705053714, 'weight_cat_class_1': 0.8038064068055317, 'weight_cat_class_2': 0.4822852486560022}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:20,018] Trial 1209 finished with value: 0.9231537144792824 and parameters: {'weight_lgbm_class_0': 0.3195157766320019, 'weight_lgbm_class_1': 0.6305791437214795, 'weight_lgbm_class_2': 0.8385074280832245, 'weight_xgb_class_0': 0.03243115615903556, 'weight_xgb_class_1': 0.38802762092478793, 'weight_xgb_class_2': 0.9752550956045687, 'weight_cat_class_0': 0.5337441484015987, 'weight_cat_class_1': 0.8253108339505608, 'weight_cat_class_2': 0.13487424100406492}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:20,047] Trial 1210 finished with value: 0.9497337407835752 and parameters: {'weight_lgbm_class_0': 0.022830388699371415, 'weight_lgbm_class_1': 0.6192371236579206, 'weight_lgbm_class_2': 0.8494088588369466, 'weight_xgb_class_0': 0.03411000278756023, 'weight_xgb_class_1': 0.3981207757257779, 'weight_xgb_class_2': 0.46652517835812296, 'weight_cat_class_0': 0.07320027779653285, 'weight_cat_class_1': 0.7542769814580308, 'weight_cat_class_2': 0.049441972684823365}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  61%|██████████████████████████████████████████████████████████████████████████████▉                                                   | 1215/2000 [00:44<00:37, 20.77it/s]

[I 2026-07-03 10:23:20,139] Trial 1211 finished with value: 0.9495959835548838 and parameters: {'weight_lgbm_class_0': 0.07934085093380382, 'weight_lgbm_class_1': 0.6054790352214039, 'weight_lgbm_class_2': 0.8274601246602351, 'weight_xgb_class_0': 0.0004354248558695537, 'weight_xgb_class_1': 0.5591247094727901, 'weight_xgb_class_2': 0.9745644394567671, 'weight_cat_class_0': 0.07096921068024394, 'weight_cat_class_1': 0.8279422838777206, 'weight_cat_class_2': 0.050986161634558935}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:20,171] Trial 1212 finished with value: 0.9464676959001358 and parameters: {'weight_lgbm_class_0': 0.27509706472818546, 'weight_lgbm_class_1': 0.6154813599277627, 'weight_lgbm_class_2': 0.7867721070096186, 'weight_xgb_class_0': 0.000920315420157046, 'weight_xgb_class_1': 0.5589083206159395, 'weight_xgb_class_2': 0.4726498637146941, 'weight_cat_class_0': 0.06688088060900635, 'weight_cat_class_1': 0.7523850233540759, 'weight_cat_class_2': 0.48315369740772063}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:20,226] Trial 1213 finished with value: 0.9497395572188796 and parameters: {'weight_lgbm_class_0': 0.02676709690251174, 'weight_lgbm_class_1': 0.6092296477653646, 'weight_lgbm_class_2': 0.8489495649945024, 'weight_xgb_class_0': 0.038465303614206955, 'weight_xgb_class_1': 0.5160977389986209, 'weight_xgb_class_2': 0.4727960905536834, 'weight_cat_class_0': 0.07029202228760115, 'weight_cat_class_1': 0.8255740326516422, 'weight_cat_class_2': 0.07029712212975342}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:20,232] Trial 1214 finished with value: 0.9496078413695462 and parameters: {'weight_lgbm_class_0': 0.023581178123328172, 'weight_lgbm_class_1': 0.6375026083842061, 'weight_lgbm_class_2': 0.8230296119199471, 'weight_xgb_class_0': 0.03412589478471248, 'weight_xgb_class_1': 0.5682985751368168, 'weight_xgb_class_2': 0.4705468276471466, 'weight_cat_class_0': 0.057632520518829305, 'weight_cat_class_1': 0.8238490915037979, 'weight_cat_class_2': 0.040209127262352456}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:20,322] Trial 1215 finished with value: 0.9497100928381705 and parameters: {'weight_lgbm_class_0': 0.020991332467268503, 'weight_lgbm_class_1': 0.6104795846341492, 'weight_lgbm_class_2': 0.8510675960783943, 'weight_xgb_class_0': 0.036091181693637044, 'weight_xgb_class_1': 0.5192476626803522, 'weight_xgb_class_2': 0.4721209649008, 'weight_cat_class_0': 0.05879935130022353, 'weight_cat_class_1': 0.7542252168088801, 'weight_cat_class_2': 0.0897204219384158}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  61%|███████████████████████████████████████████████████████████████████████████████▎                                                  | 1221/2000 [00:44<00:37, 20.97it/s]

[I 2026-07-03 10:23:20,390] Trial 1216 finished with value: 0.9450322156158397 and parameters: {'weight_lgbm_class_0': 0.2732434417383507, 'weight_lgbm_class_1': 0.6195466256404708, 'weight_lgbm_class_2': 0.8695540208925975, 'weight_xgb_class_0': 0.04642572037196108, 'weight_xgb_class_1': 0.5255717897634793, 'weight_xgb_class_2': 0.4756088744666791, 'weight_cat_class_0': 0.05379922666237889, 'weight_cat_class_1': 0.8273774160643551, 'weight_cat_class_2': 0.2816159389767449}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:20,396] Trial 1217 finished with value: 0.9492039019381103 and parameters: {'weight_lgbm_class_0': 0.024657256408781438, 'weight_lgbm_class_1': 0.7329965928411555, 'weight_lgbm_class_2': 0.8543096269077037, 'weight_xgb_class_0': 0.0002287154463441375, 'weight_xgb_class_1': 0.5227254225827697, 'weight_xgb_class_2': 0.47389213184045814, 'weight_cat_class_0': 0.05509344583562556, 'weight_cat_class_1': 0.7533521707348542, 'weight_cat_class_2': 0.08849528766422117}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:20,434] Trial 1218 finished with value: 0.9496565406647705 and parameters: {'weight_lgbm_class_0': 0.027311774204277176, 'weight_lgbm_class_1': 0.6147708482033847, 'weight_lgbm_class_2': 0.8547338412226174, 'weight_xgb_class_0': 0.03966771175304312, 'weight_xgb_class_1': 0.5212183481240336, 'weight_xgb_class_2': 0.4767496952283709, 'weight_cat_class_0': 0.05484763654821641, 'weight_cat_class_1': 0.47886923746466264, 'weight_cat_class_2': 0.1046376116995465}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:20,492] Trial 1220 finished with value: 0.9496410524560351 and parameters: {'weight_lgbm_class_0': 0.01768099817933544, 'weight_lgbm_class_1': 0.6217507437787827, 'weight_lgbm_class_2': 0.8490961309103366, 'weight_xgb_class_0': 0.0007847395005987021, 'weight_xgb_class_1': 0.37500289071814585, 'weight_xgb_class_2': 0.4711339890066549, 'weight_cat_class_0': 0.13142200674030974, 'weight_cat_class_1': 0.8298452249772064, 'weight_cat_class_2': 0.2799527069195537}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:20,519] Trial 1219 finished with value: 0.9488022337593852 and parameters: {'weight_lgbm_class_0': 0.023243235951865192, 'weight_lgbm_class_1': 0.56634748166361, 'weight_lgbm_class_2': 0.7957188042944858, 'weight_xgb_class_0': 0.032737816692222435, 'weight_xgb_class_1': 0.3857375568661614, 'weight_xgb_class_2': 0.47540102954920815, 'weight_cat_class_0': 0.14113198403820065, 'weight_cat_class_1': 0.8349761701873414, 'weight_cat_class_2': 0.07865141630943259}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:20,586] Trial 1221 finished with value: 0.948781777953913 and parameters: {'weight_lgbm_class_0': 0.024530833661646666, 'weight_lgbm_class_1': 0.7352445461276641, 'weight_lgbm_class_2': 0.7932566141354562, 'weight_xgb_class_0': 0.03582992603857638, 'weight_xgb_class_1': 0.4179623474972848, 'weight_xgb_class_2': 0.4812312892098718, 'weight_cat_class_0': 0.12768063218803932, 'weight_cat_class_1': 0.8367676053587432, 'weight_cat_class_2': 0.012142467793886141}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  61%|███████████████████████████████████████████████████████████████████████████████▋                                                  | 1225/2000 [00:44<00:35, 21.60it/s]

[I 2026-07-03 10:23:20,636] Trial 1222 finished with value: 0.9495294065174164 and parameters: {'weight_lgbm_class_0': 0.033684086755123015, 'weight_lgbm_class_1': 0.577231442369781, 'weight_lgbm_class_2': 0.8042585453427866, 'weight_xgb_class_0': 0.0009176865570069752, 'weight_xgb_class_1': 0.3901923707228134, 'weight_xgb_class_2': 0.47192955520616325, 'weight_cat_class_0': 0.12510310576501615, 'weight_cat_class_1': 0.82540060381947, 'weight_cat_class_2': 0.27635549522331737}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:20,717] Trial 1223 finished with value: 0.9495913831197185 and parameters: {'weight_lgbm_class_0': 0.027897215447908838, 'weight_lgbm_class_1': 0.5841878709749188, 'weight_lgbm_class_2': 0.7991917689060212, 'weight_xgb_class_0': 0.00262340522533944, 'weight_xgb_class_1': 0.41878332156069087, 'weight_xgb_class_2': 0.47549644908564215, 'weight_cat_class_0': 0.10970261444244533, 'weight_cat_class_1': 0.8269324073493554, 'weight_cat_class_2': 0.08264287731716846}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:20,739] Trial 1224 finished with value: 0.9492980683031322 and parameters: {'weight_lgbm_class_0': 0.03315443431687129, 'weight_lgbm_class_1': 0.6305730590893257, 'weight_lgbm_class_2': 0.8052363954094073, 'weight_xgb_class_0': 0.0014272956034263407, 'weight_xgb_class_1': 0.39886860495627646, 'weight_xgb_class_2': 0.478736352417502, 'weight_cat_class_0': 0.11880338573152878, 'weight_cat_class_1': 0.8383438380526433, 'weight_cat_class_2': 0.016135060032060736}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:20,765] Trial 1225 finished with value: 0.9492059090386356 and parameters: {'weight_lgbm_class_0': 0.026311908555311174, 'weight_lgbm_class_1': 0.5918074760783948, 'weight_lgbm_class_2': 0.7879793793618212, 'weight_xgb_class_0': 0.042888494498605996, 'weight_xgb_class_1': 0.4081302302768504, 'weight_xgb_class_2': 0.4864577465261659, 'weight_cat_class_0': 0.09488324443547483, 'weight_cat_class_1': 0.8400491948230521, 'weight_cat_class_2': 0.08658906389806696}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  62%|████████████████████████████████████████████████████████████████████████████████                                                  | 1231/2000 [00:45<00:37, 20.60it/s]

[I 2026-07-03 10:23:20,856] Trial 1226 finished with value: 0.9489584659482501 and parameters: {'weight_lgbm_class_0': 0.021563269957977693, 'weight_lgbm_class_1': 0.5685597757161075, 'weight_lgbm_class_2': 0.7910462204335618, 'weight_xgb_class_0': 0.03951923430199767, 'weight_xgb_class_1': 0.4039953911379021, 'weight_xgb_class_2': 0.49330473027234206, 'weight_cat_class_0': 0.11874504684142262, 'weight_cat_class_1': 0.84267753046741, 'weight_cat_class_2': 0.09948145592657483}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:20,912] Trial 1227 finished with value: 0.9490171937723465 and parameters: {'weight_lgbm_class_0': 0.024187223520455683, 'weight_lgbm_class_1': 0.5812362263421236, 'weight_lgbm_class_2': 0.7943552156828504, 'weight_xgb_class_0': 0.05333354206201822, 'weight_xgb_class_1': 0.3756708964112487, 'weight_xgb_class_2': 0.49480582636868253, 'weight_cat_class_0': 0.098015848702869, 'weight_cat_class_1': 0.8140989395981767, 'weight_cat_class_2': 0.08076807581051305}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:20,964] Trial 1228 finished with value: 0.9494545030460722 and parameters: {'weight_lgbm_class_0': 0.020748080892952672, 'weight_lgbm_class_1': 0.6219643147097788, 'weight_lgbm_class_2': 0.8011582832723845, 'weight_xgb_class_0': 0.03359540643340508, 'weight_xgb_class_1': 0.36792511548272205, 'weight_xgb_class_2': 0.49250324746682705, 'weight_cat_class_0': 0.08957858146473094, 'weight_cat_class_1': 0.8142469106769645, 'weight_cat_class_2': 0.0289576568561154}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:20,981] Trial 1229 finished with value: 0.9229848921474287 and parameters: {'weight_lgbm_class_0': 0.5433307405331235, 'weight_lgbm_class_1': 0.5627441714286819, 'weight_lgbm_class_2': 0.8029678644691227, 'weight_xgb_class_0': 0.03729212650768542, 'weight_xgb_class_1': 0.38271230476307, 'weight_xgb_class_2': 0.4954136750237888, 'weight_cat_class_0': 0.11928485275203893, 'weight_cat_class_1': 0.8254017481875247, 'weight_cat_class_2': 0.032225942457079326}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:21,061] Trial 1230 finished with value: 0.9044359789111809 and parameters: {'weight_lgbm_class_0': 0.02827817405486982, 'weight_lgbm_class_1': 0.6126428792791451, 'weight_lgbm_class_2': 0.7970604843844978, 'weight_xgb_class_0': 0.912481867485189, 'weight_xgb_class_1': 0.4709242707766594, 'weight_xgb_class_2': 0.49621186293187297, 'weight_cat_class_0': 0.09119515629269545, 'weight_cat_class_1': 0.8405862359906711, 'weight_cat_class_2': 0.07246998382130539}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:21,085] Trial 1231 finished with value: 0.9487857648645219 and parameters: {'weight_lgbm_class_0': 0.024283399099468736, 'weight_lgbm_class_1': 0.5811715862049359, 'weight_lgbm_class_2': 0.8052402261860574, 'weight_xgb_class_0': 0.047524003549182695, 'weight_xgb_class_1': 0.36797013641848836, 'weight_xgb_class_2': 0.4989813496591565, 'weight_cat_class_0': 0.1164043938379669, 'weight_cat_class_1': 0.8335538866242886, 'weight_cat_class_2': 0.022809275414892943}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:21,105] Trial 1232 finished with value: 0.9487844523056496 and parameters: {'weight_lgbm_class_0': 0.020055235139758286, 'weight_lgbm_class_1': 0.6298888520914618, 'weight_lgbm_class_2': 0.7907722961045272, 'weight_xgb_class_0': 0.037024009060193604, 'weight_xgb_class_1': 0.40008682330284373, 'weight_xgb_class_2': 0.4997452069019086, 'weight_cat_class_0': 0.125804375932959, 'weight_cat_class_1': 0.8393664703921352, 'weight_cat_class_2': 0.004906376966272261}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:21,157] Trial 1233 finished with value: 0.949625245011357 and parameters: {'weight_lgbm_class_0': 0.021463312748659376, 'weight_lgbm_class_1': 0.5983582545968711, 'weight_lgbm_class_2': 0.8254943409213404, 'weight_xgb_class_0': 0.04202599202007439, 'weight_xgb_class_1': 0.4721902719073614, 'weight_xgb_class_2': 0.4952000701719095, 'weight_cat_class_0': 0.08075020106849885, 'weight_cat_class_1': 0.8348103468042329, 'weight_cat_class_2': 0.1055432828287834}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:21,168] Trial 1234 finished with value: 0.9490683508018433 and parameters: {'weight_lgbm_class_0': 0.028963070226806494, 'weight_lgbm_class_1': 0.589328696154255, 'weight_lgbm_class_2': 0.8150997244272903, 'weight_xgb_class_0': 0.04854632008663556, 'weight_xgb_class_1': 0.3733859610732173, 'weight_xgb_class_2': 0.49495224614860367, 'weight_cat_class_0': 0.0959938486974565, 'weight_cat_class_1': 0.8343913027591271, 'weight_cat_class_2': 0.06770884599172572}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  62%|████████████████████████████████████████████████████████████████████████████████▌                                                 | 1240/2000 [00:45<00:35, 21.25it/s]

[I 2026-07-03 10:23:21,301] Trial 1235 finished with value: 0.9488919445621148 and parameters: {'weight_lgbm_class_0': 0.01505475255288901, 'weight_lgbm_class_1': 0.5815076727432951, 'weight_lgbm_class_2': 0.7713623029636589, 'weight_xgb_class_0': 0.04860124263777767, 'weight_xgb_class_1': 0.47553810200688823, 'weight_xgb_class_2': 0.43415945651531035, 'weight_cat_class_0': 0.0993622689143829, 'weight_cat_class_1': 0.8120809605195597, 'weight_cat_class_2': 0.024032050557200313}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:21,339] Trial 1236 finished with value: 0.9496785019917192 and parameters: {'weight_lgbm_class_0': 0.01671039599051581, 'weight_lgbm_class_1': 0.61910801589872, 'weight_lgbm_class_2': 0.8285277954197893, 'weight_xgb_class_0': 0.03786046317592686, 'weight_xgb_class_1': 0.3633137664161484, 'weight_xgb_class_2': 0.4989183577456988, 'weight_cat_class_0': 0.04925402799903041, 'weight_cat_class_1': 0.8126258604002707, 'weight_cat_class_2': 0.10635179002758768}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:21,409] Trial 1237 finished with value: 0.9461039980703415 and parameters: {'weight_lgbm_class_0': 0.16538816296259198, 'weight_lgbm_class_1': 0.5944038170764164, 'weight_lgbm_class_2': 0.8384285949680207, 'weight_xgb_class_0': 0.03617279327950333, 'weight_xgb_class_1': 0.47443946365592304, 'weight_xgb_class_2': 0.42742341842424586, 'weight_cat_class_0': 0.09328543200065581, 'weight_cat_class_1': 0.8102539068925236, 'weight_cat_class_2': 0.05598863613025297}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:21,434] Trial 1238 finished with value: 0.9452512061138014 and parameters: {'weight_lgbm_class_0': 0.17988739118873534, 'weight_lgbm_class_1': 0.5957245757949658, 'weight_lgbm_class_2': 0.8177490839448072, 'weight_xgb_class_0': 0.046831893385706, 'weight_xgb_class_1': 0.47405852503700396, 'weight_xgb_class_2': 0.5007530938326188, 'weight_cat_class_0': 0.09901052081481372, 'weight_cat_class_1': 0.8088669951619568, 'weight_cat_class_2': 0.08169196448878624}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:21,472] Trial 1239 finished with value: 0.8811070014137341 and parameters: {'weight_lgbm_class_0': 0.17383952890485438, 'weight_lgbm_class_1': 0.6120844327587609, 'weight_lgbm_class_2': 0.8128876575764161, 'weight_xgb_class_0': 0.0327984139664911, 'weight_xgb_class_1': 0.36525454884969943, 'weight_xgb_class_2': 0.4987298876801694, 'weight_cat_class_0': 0.9964722823184642, 'weight_cat_class_1': 0.16580748887832197, 'weight_cat_class_2': 0.029157150912573787}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  62%|████████████████████████████████████████████████████████████████████████████████▊                                                 | 1244/2000 [00:45<00:37, 20.13it/s]

[I 2026-07-03 10:23:21,525] Trial 1240 finished with value: 0.9496197702429999 and parameters: {'weight_lgbm_class_0': 0.039723066365892803, 'weight_lgbm_class_1': 0.6084088864955252, 'weight_lgbm_class_2': 0.8366323918615334, 'weight_xgb_class_0': 0.053092825915133215, 'weight_xgb_class_1': 0.48108970143167684, 'weight_xgb_class_2': 0.43291635073756896, 'weight_cat_class_0': 0.048376990209989326, 'weight_cat_class_1': 0.7904948328773672, 'weight_cat_class_2': 0.06762719126691905}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:21,586] Trial 1241 finished with value: 0.9494396916718397 and parameters: {'weight_lgbm_class_0': 0.036380376338033, 'weight_lgbm_class_1': 0.5766178031640101, 'weight_lgbm_class_2': 0.814681583999176, 'weight_xgb_class_0': 0.0604962632001017, 'weight_xgb_class_1': 0.47161604262396545, 'weight_xgb_class_2': 0.4369696526829732, 'weight_cat_class_0': 0.050100357352461974, 'weight_cat_class_1': 0.7924039411235527, 'weight_cat_class_2': 0.0641065445299053}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:21,609] Trial 1242 finished with value: 0.9493259550422953 and parameters: {'weight_lgbm_class_0': 0.039043518503008426, 'weight_lgbm_class_1': 0.5635757794951339, 'weight_lgbm_class_2': 0.7520530016750107, 'weight_xgb_class_0': 0.05455493786824291, 'weight_xgb_class_1': 0.47919803196930055, 'weight_xgb_class_2': 0.42775939467408286, 'weight_cat_class_0': 0.05417677084471836, 'weight_cat_class_1': 0.7891175402231101, 'weight_cat_class_2': 0.09691247323304125}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:21,657] Trial 1243 finished with value: 0.9492033481767524 and parameters: {'weight_lgbm_class_0': 0.040412772664209576, 'weight_lgbm_class_1': 0.5636966854970544, 'weight_lgbm_class_2': 0.8192944351447057, 'weight_xgb_class_0': 0.07030140054555736, 'weight_xgb_class_1': 0.4772111628411541, 'weight_xgb_class_2': 0.4299660688946469, 'weight_cat_class_0': 0.04831032586299213, 'weight_cat_class_1': 0.7898180219308556, 'weight_cat_class_2': 0.05994408352029017}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:21,680] Trial 1244 finished with value: 0.947119330091799 and parameters: {'weight_lgbm_class_0': 0.1554765800074358, 'weight_lgbm_class_1': 0.5910611819068425, 'weight_lgbm_class_2': 0.872039850872809, 'weight_xgb_class_0': 0.06053431512005854, 'weight_xgb_class_1': 0.32190129897777925, 'weight_xgb_class_2': 0.5178951372295968, 'weight_cat_class_0': 0.04733584051644427, 'weight_cat_class_1': 0.8067265904731479, 'weight_cat_class_2': 0.04368141271104552}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  62%|█████████████████████████████████████████████████████████████████████████████████                                                 | 1247/2000 [00:46<00:34, 21.66it/s]

[I 2026-07-03 10:23:21,746] Trial 1245 finished with value: 0.9439457156205937 and parameters: {'weight_lgbm_class_0': 0.20625662983303472, 'weight_lgbm_class_1': 0.5943374676175172, 'weight_lgbm_class_2': 0.7524576600039516, 'weight_xgb_class_0': 0.07450528909387834, 'weight_xgb_class_1': 0.4777664455799967, 'weight_xgb_class_2': 0.42360784054065725, 'weight_cat_class_0': 0.04586004174100711, 'weight_cat_class_1': 0.7914786084179904, 'weight_cat_class_2': 0.044015189965923435}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:21,751] Trial 1246 finished with value: 0.9456845905277068 and parameters: {'weight_lgbm_class_0': 0.16621294385448313, 'weight_lgbm_class_1': 0.6009212747864289, 'weight_lgbm_class_2': 0.8242361691334992, 'weight_xgb_class_0': 0.07529028450036729, 'weight_xgb_class_1': 0.3227488143919893, 'weight_xgb_class_2': 0.42480642480010916, 'weight_cat_class_0': 0.04951867491323915, 'weight_cat_class_1': 0.7930979773881383, 'weight_cat_class_2': 0.05104198848523325}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:21,868] Trial 1247 finished with value: 0.9475864136040131 and parameters: {'weight_lgbm_class_0': 0.1676639153446258, 'weight_lgbm_class_1': 0.6127244719936149, 'weight_lgbm_class_2': 0.8458000657876571, 'weight_xgb_class_0': 0.01944309498780831, 'weight_xgb_class_1': 0.32218685723543566, 'weight_xgb_class_2': 0.42298826183935495, 'weight_cat_class_0': 0.0501607688365488, 'weight_cat_class_1': 0.789901677731647, 'weight_cat_class_2': 0.061255581326850994}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  63%|█████████████████████████████████████████████████████████████████████████████████▍                                                | 1253/2000 [00:46<00:33, 22.35it/s]

[I 2026-07-03 10:23:21,962] Trial 1248 finished with value: 0.946372035395668 and parameters: {'weight_lgbm_class_0': 0.1659056369229003, 'weight_lgbm_class_1': 0.595989569444, 'weight_lgbm_class_2': 0.8673681420762896, 'weight_xgb_class_0': 0.07434267166028599, 'weight_xgb_class_1': 0.33037620157170783, 'weight_xgb_class_2': 0.426951531374219, 'weight_cat_class_0': 0.04619106496610005, 'weight_cat_class_1': 0.7915733184464409, 'weight_cat_class_2': 0.11275021048915407}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:21,967] Trial 1250 finished with value: 0.9443138522007156 and parameters: {'weight_lgbm_class_0': 0.15864595351065108, 'weight_lgbm_class_1': 0.6029813731688286, 'weight_lgbm_class_2': 0.8761393748087016, 'weight_xgb_class_0': 0.0695776837415861, 'weight_xgb_class_1': 0.4300034512337044, 'weight_xgb_class_2': 0.42261872720339555, 'weight_cat_class_0': 0.04548019196468965, 'weight_cat_class_1': 0.1504970280915892, 'weight_cat_class_2': 0.11307510142349318}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:21,977] Trial 1249 finished with value: 0.9445412682034151 and parameters: {'weight_lgbm_class_0': 0.20759629069423924, 'weight_lgbm_class_1': 0.64851977661796, 'weight_lgbm_class_2': 0.7596374212653599, 'weight_xgb_class_0': 0.07126966197314105, 'weight_xgb_class_1': 0.4830205474846426, 'weight_xgb_class_2': 0.4261468889432216, 'weight_cat_class_0': 0.04701872530572054, 'weight_cat_class_1': 0.7881325727686076, 'weight_cat_class_2': 0.0823441786563005}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:22,013] Trial 1251 finished with value: 0.9493092864846954 and parameters: {'weight_lgbm_class_0': 0.03919916203796145, 'weight_lgbm_class_1': 0.6356736047816312, 'weight_lgbm_class_2': 0.8692499409591538, 'weight_xgb_class_0': 0.06683865133888836, 'weight_xgb_class_1': 0.3158954648646826, 'weight_xgb_class_2': 0.42810486303313705, 'weight_cat_class_0': 0.04937588922136539, 'weight_cat_class_1': 0.7889012651564136, 'weight_cat_class_2': 0.05606153293132793}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:22,072] Trial 1252 finished with value: 0.9496124058320156 and parameters: {'weight_lgbm_class_0': 0.04399838333159965, 'weight_lgbm_class_1': 0.6078041606868172, 'weight_lgbm_class_2': 0.86277851622804, 'weight_xgb_class_0': 0.07290902892887105, 'weight_xgb_class_1': 0.4395701068303141, 'weight_xgb_class_2': 0.42499567432272134, 'weight_cat_class_0': 0.032537893476765334, 'weight_cat_class_1': 0.7879378783180054, 'weight_cat_class_2': 0.3447887398628714}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:22,146] Trial 1254 finished with value: 0.9491113291433252 and parameters: {'weight_lgbm_class_0': 0.1513423592426062, 'weight_lgbm_class_1': 0.636545256989933, 'weight_lgbm_class_2': 0.8729540786540801, 'weight_xgb_class_0': 0.018361582353884066, 'weight_xgb_class_1': 0.33668376107154896, 'weight_xgb_class_2': 0.4521417305138069, 'weight_cat_class_0': 0.03076849377364163, 'weight_cat_class_1': 0.782753522121257, 'weight_cat_class_2': 0.3197663647012722}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  63%|█████████████████████████████████████████████████████████████████████████████████▊                                                | 1259/2000 [00:46<00:31, 23.36it/s]

[I 2026-07-03 10:23:22,169] Trial 1253 finished with value: 0.9486617178076747 and parameters: {'weight_lgbm_class_0': 0.12954656836888165, 'weight_lgbm_class_1': 0.6390614428245804, 'weight_lgbm_class_2': 0.8714123063505119, 'weight_xgb_class_0': 0.07317828795126573, 'weight_xgb_class_1': 0.42672359248321756, 'weight_xgb_class_2': 0.5182057126960189, 'weight_cat_class_0': 0.032100164586148054, 'weight_cat_class_1': 0.7828680065244633, 'weight_cat_class_2': 0.32001925228163225}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:22,224] Trial 1255 finished with value: 0.9492711189889477 and parameters: {'weight_lgbm_class_0': 0.1256427796092596, 'weight_lgbm_class_1': 0.6400546023170403, 'weight_lgbm_class_2': 0.8767508717865915, 'weight_xgb_class_0': 0.019091511959696227, 'weight_xgb_class_1': 0.43726723836097114, 'weight_xgb_class_2': 0.46132124326011104, 'weight_cat_class_0': 0.02839259896020708, 'weight_cat_class_1': 0.7840207115701191, 'weight_cat_class_2': 0.09862371999293108}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:22,234] Trial 1256 finished with value: 0.9462840564565963 and parameters: {'weight_lgbm_class_0': 0.0422229290406064, 'weight_lgbm_class_1': 0.6674771473623023, 'weight_lgbm_class_2': 0.8734637368556232, 'weight_xgb_class_0': 0.2250619679779455, 'weight_xgb_class_1': 0.4339761461643815, 'weight_xgb_class_2': 0.45255476447083903, 'weight_cat_class_0': 0.028537603647520785, 'weight_cat_class_1': 0.7753514305050409, 'weight_cat_class_2': 0.0926516997831674}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:22,303] Trial 1258 finished with value: 0.9494066907907919 and parameters: {'weight_lgbm_class_0': 0.04419396675201872, 'weight_lgbm_class_1': 0.6629715772350335, 'weight_lgbm_class_2': 0.8644991371963237, 'weight_xgb_class_0': 0.01769567243775766, 'weight_xgb_class_1': 0.43232792142317655, 'weight_xgb_class_2': 0.4524246757993614, 'weight_cat_class_0': 0.02576750100225197, 'weight_cat_class_1': 0.7789145896938414, 'weight_cat_class_2': 0.11239146446074615}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:22,322] Trial 1257 finished with value: 0.9495263137552091 and parameters: {'weight_lgbm_class_0': 0.04509353213232247, 'weight_lgbm_class_1': 0.6494374225190834, 'weight_lgbm_class_2': 0.8603581373819741, 'weight_xgb_class_0': 0.023081151269192208, 'weight_xgb_class_1': 0.4341450171579245, 'weight_xgb_class_2': 0.4581616396395049, 'weight_cat_class_0': 0.02532322361372389, 'weight_cat_class_1': 0.7767097211288667, 'weight_cat_class_2': 0.11177331280292176}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:22,426] Trial 1259 finished with value: 0.9492231591547696 and parameters: {'weight_lgbm_class_0': 0.13064264439283668, 'weight_lgbm_class_1': 0.6455142873617759, 'weight_lgbm_class_2': 0.8723276862286132, 'weight_xgb_class_0': 0.018625080742437992, 'weight_xgb_class_1': 0.4312126132858916, 'weight_xgb_class_2': 0.4568364344088498, 'weight_cat_class_0': 0.02558876243225279, 'weight_cat_class_1': 0.7752173819235363, 'weight_cat_class_2': 0.09443322404001708}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:22,516] Trial 1261 finished with value: 0.9495350302213078 and parameters: {'weight_lgbm_class_0': 0.12909296967396025, 'weight_lgbm_class_1': 0.6310732103499959, 'weight_lgbm_class_2': 0.856486808795468, 'weight_xgb_class_0': 0.016826243668459428, 'weight_xgb_class_1': 0.5214639829064796, 'weight_xgb_class_2': 0.4549717289337606, 'weight_cat_class_0': 0.02461063362957954, 'weight_cat_class_1': 0.7708620865114821, 'weight_cat_class_2': 0.3139886950191443}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:22,568] Trial 1260 finished with value: 0.9492713112758621 and parameters: {'weight_lgbm_class_0': 0.12772854631384145, 'weight_lgbm_class_1': 0.6669549880121569, 'weight_lgbm_class_2': 0.8648844657621474, 'weight_xgb_class_0': 0.019010217772759727, 'weight_xgb_class_1': 0.4381087817992992, 'weight_xgb_class_2': 0.45888446055346604, 'weight_cat_class_0': 0.019353665615619586, 'weight_cat_class_1': 0.5794963163610494, 'weight_cat_class_2': 0.1190028485065392}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:22,622] Trial 1263 finished with value: 0.9495923495937831 and parameters: {'weight_lgbm_class_0': 0.12010710375295319, 'weight_lgbm_class_1': 0.6586242426907598, 'weight_lgbm_class_2': 0.8498357143447394, 'weight_xgb_class_0': 0.02196770107151885, 'weight_xgb_class_1': 0.4326049415759644, 'weight_xgb_class_2': 0.45263758805734805, 'weight_cat_class_0': 0.021159885734367216, 'weight_cat_class_1': 0.7698064987015694, 'weight_cat_class_2': 0.3628709182644242}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  63%|██████████████████████████████████████████████████████████████████████████████████▍                                               | 1268/2000 [00:47<00:34, 21.42it/s]

[I 2026-07-03 10:23:22,623] Trial 1264 finished with value: 0.9495622177282755 and parameters: {'weight_lgbm_class_0': 0.12560121817324618, 'weight_lgbm_class_1': 0.5485408284835849, 'weight_lgbm_class_2': 0.882365630590076, 'weight_xgb_class_0': 0.018863631335877047, 'weight_xgb_class_1': 0.5192366469464877, 'weight_xgb_class_2': 0.5200998934116707, 'weight_cat_class_0': 0.02312348334621543, 'weight_cat_class_1': 0.7697246217090042, 'weight_cat_class_2': 0.31620027429425424}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:22,626] Trial 1262 finished with value: 0.9491714725892715 and parameters: {'weight_lgbm_class_0': 0.13947106901342848, 'weight_lgbm_class_1': 0.6618058536072181, 'weight_lgbm_class_2': 0.8487963030828556, 'weight_xgb_class_0': 0.01496108272181959, 'weight_xgb_class_1': 0.5212572850176459, 'weight_xgb_class_2': 0.4550756686231486, 'weight_cat_class_0': 0.02413298162117296, 'weight_cat_class_1': 0.7710177180864582, 'weight_cat_class_2': 0.11540940548680395}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:22,710] Trial 1265 finished with value: 0.9492419021222668 and parameters: {'weight_lgbm_class_0': 0.1331553288024867, 'weight_lgbm_class_1': 0.670283991635159, 'weight_lgbm_class_2': 0.8838873796870874, 'weight_xgb_class_0': 0.01949916718966285, 'weight_xgb_class_1': 0.5241716741545303, 'weight_xgb_class_2': 0.5207249833703349, 'weight_cat_class_0': 0.02706253786112177, 'weight_cat_class_1': 0.7695743587849292, 'weight_cat_class_2': 0.10411257817689656}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:22,729] Trial 1266 finished with value: 0.9493164103824606 and parameters: {'weight_lgbm_class_0': 0.12380904836028583, 'weight_lgbm_class_1': 0.6639913340676938, 'weight_lgbm_class_2': 0.8459721724226149, 'weight_xgb_class_0': 0.019923869613142582, 'weight_xgb_class_1': 0.5174284617116764, 'weight_xgb_class_2': 0.45478806785204356, 'weight_cat_class_0': 0.02278533769367002, 'weight_cat_class_1': 0.7744395336375423, 'weight_cat_class_2': 0.10350373972598241}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:22,795] Trial 1267 finished with value: 0.9497065032487022 and parameters: {'weight_lgbm_class_0': 0.13115974773896702, 'weight_lgbm_class_1': 0.6892945234339877, 'weight_lgbm_class_2': 0.8880809152888522, 'weight_xgb_class_0': 0.000691831762211247, 'weight_xgb_class_1': 0.5243093387526377, 'weight_xgb_class_2': 0.5226015843490607, 'weight_cat_class_0': 0.01961525269845773, 'weight_cat_class_1': 0.766070785842084, 'weight_cat_class_2': 0.37195471101593025}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:22,839] Trial 1268 finished with value: 0.9496319887072762 and parameters: {'weight_lgbm_class_0': 0.12944728453276963, 'weight_lgbm_class_1': 0.6900167736509165, 'weight_lgbm_class_2': 0.8530823536125727, 'weight_xgb_class_0': 0.017138279072075706, 'weight_xgb_class_1': 0.5278884934225656, 'weight_xgb_class_2': 0.516679186894708, 'weight_cat_class_0': 0.020226616918604726, 'weight_cat_class_1': 0.8180654248967317, 'weight_cat_class_2': 0.3824380059956644}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  64%|██████████████████████████████████████████████████████████████████████████████████▌                                               | 1271/2000 [00:47<00:34, 21.10it/s]

[I 2026-07-03 10:23:22,874] Trial 1269 finished with value: 0.9495866437980197 and parameters: {'weight_lgbm_class_0': 0.1282189787846792, 'weight_lgbm_class_1': 0.686951388530469, 'weight_lgbm_class_2': 0.8506160469598854, 'weight_xgb_class_0': 0.01892854979151798, 'weight_xgb_class_1': 0.515395998293145, 'weight_xgb_class_2': 0.4525399569728693, 'weight_cat_class_0': 0.019825515113003754, 'weight_cat_class_1': 0.8210329835050976, 'weight_cat_class_2': 0.36141323784380414}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:22,928] Trial 1270 finished with value: 0.9497326309023201 and parameters: {'weight_lgbm_class_0': 0.1176887505352876, 'weight_lgbm_class_1': 0.6940108721476482, 'weight_lgbm_class_2': 0.8486570885330514, 'weight_xgb_class_0': 0.000575425493706074, 'weight_xgb_class_1': 0.5227366772548134, 'weight_xgb_class_2': 0.5146187943243327, 'weight_cat_class_0': 0.018752876282385176, 'weight_cat_class_1': 0.8134890980822859, 'weight_cat_class_2': 0.39785586533396744}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,003] Trial 1271 finished with value: 0.9493243988476742 and parameters: {'weight_lgbm_class_0': 0.12423137507864607, 'weight_lgbm_class_1': 0.6909591218556979, 'weight_lgbm_class_2': 0.8446471577612237, 'weight_xgb_class_0': 0.001261722544421577, 'weight_xgb_class_1': 0.5236301439415589, 'weight_xgb_class_2': 0.5169721927751506, 'weight_cat_class_0': 0.07392349041203378, 'weight_cat_class_1': 0.8113406788496685, 'weight_cat_class_2': 0.4225173983006224}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  64%|███████████████████████████████████████████████████████████████████████████████████                                               | 1277/2000 [00:47<00:35, 20.18it/s]

[I 2026-07-03 10:23:23,087] Trial 1272 finished with value: 0.949659964099474 and parameters: {'weight_lgbm_class_0': 0.08436160396437956, 'weight_lgbm_class_1': 0.6887097431663128, 'weight_lgbm_class_2': 0.8457162694670836, 'weight_xgb_class_0': 0.00015991248604621923, 'weight_xgb_class_1': 0.515868162378702, 'weight_xgb_class_2': 0.47156687623704113, 'weight_cat_class_0': 0.0768706519982747, 'weight_cat_class_1': 0.8168570529951292, 'weight_cat_class_2': 0.39084352659160504}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,172] Trial 1273 finished with value: 0.949449986491813 and parameters: {'weight_lgbm_class_0': 0.08441825394608099, 'weight_lgbm_class_1': 0.6877553775115969, 'weight_lgbm_class_2': 0.8396453954144008, 'weight_xgb_class_0': 0.018368445472608956, 'weight_xgb_class_1': 0.29736789086176174, 'weight_xgb_class_2': 0.5170426071748654, 'weight_cat_class_0': 0.0730386334321749, 'weight_cat_class_1': 0.8232800729722294, 'weight_cat_class_2': 0.3462975581636927}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,196] Trial 1275 finished with value: 0.9493177960946872 and parameters: {'weight_lgbm_class_0': 0.0914971404888799, 'weight_lgbm_class_1': 0.6928496906010564, 'weight_lgbm_class_2': 0.8428326954839169, 'weight_xgb_class_0': 0.03690490099279556, 'weight_xgb_class_1': 0.5056434076117325, 'weight_xgb_class_2': 0.4772770325592282, 'weight_cat_class_0': 0.0656545437662357, 'weight_cat_class_1': 0.8150694194131396, 'weight_cat_class_2': 0.4186152786567177}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,206] Trial 1274 finished with value: 0.9491996058096438 and parameters: {'weight_lgbm_class_0': 0.09028905364935093, 'weight_lgbm_class_1': 0.6897293657619226, 'weight_lgbm_class_2': 0.8384209751629607, 'weight_xgb_class_0': 0.0337248255784036, 'weight_xgb_class_1': 0.28452164946571346, 'weight_xgb_class_2': 0.5193699501877888, 'weight_cat_class_0': 0.08006186678326745, 'weight_cat_class_1': 0.8173067853136989, 'weight_cat_class_2': 0.44748259544436286}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,207] Trial 1276 finished with value: 0.949708419447698 and parameters: {'weight_lgbm_class_0': 0.08452083105135476, 'weight_lgbm_class_1': 0.7379178247825117, 'weight_lgbm_class_2': 0.8370918471621166, 'weight_xgb_class_0': 0.033637432207052884, 'weight_xgb_class_1': 0.4958322040992067, 'weight_xgb_class_2': 0.5149732491517772, 'weight_cat_class_0': 0.016409132711505257, 'weight_cat_class_1': 0.8128680460770613, 'weight_cat_class_2': 0.4168615769083168}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,293] Trial 1277 finished with value: 0.9493092177776612 and parameters: {'weight_lgbm_class_0': 0.08315624259580105, 'weight_lgbm_class_1': 0.7282223559567402, 'weight_lgbm_class_2': 0.8362607438186097, 'weight_xgb_class_0': 0.03707151273269023, 'weight_xgb_class_1': 0.4923039869784798, 'weight_xgb_class_2': 0.47833593319598905, 'weight_cat_class_0': 0.07718627471837758, 'weight_cat_class_1': 0.8205040979831894, 'weight_cat_class_2': 0.3886681219833872}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  64%|███████████████████████████████████████████████████████████████████████████████████▎                                              | 1282/2000 [00:47<00:32, 21.98it/s]

[I 2026-07-03 10:23:23,324] Trial 1278 finished with value: 0.9496540981835593 and parameters: {'weight_lgbm_class_0': 0.07667330433670629, 'weight_lgbm_class_1': 0.6947568635170436, 'weight_lgbm_class_2': 0.8375205117534726, 'weight_xgb_class_0': 0.00015683557419622976, 'weight_xgb_class_1': 0.2933687118839781, 'weight_xgb_class_2': 0.5225410698432901, 'weight_cat_class_0': 0.06966111789562739, 'weight_cat_class_1': 0.8133697333803079, 'weight_cat_class_2': 0.4488950723777782}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,395] Trial 1280 finished with value: 0.9492213800899117 and parameters: {'weight_lgbm_class_0': 0.08535452332994882, 'weight_lgbm_class_1': 0.734655245542474, 'weight_lgbm_class_2': 0.834086796347908, 'weight_xgb_class_0': 0.03189684302113124, 'weight_xgb_class_1': 0.4944930193451753, 'weight_xgb_class_2': 0.4766813057196438, 'weight_cat_class_0': 0.08033042087015141, 'weight_cat_class_1': 0.8156792893591438, 'weight_cat_class_2': 0.34089836422387787}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,434] Trial 1279 finished with value: 0.9497404567180255 and parameters: {'weight_lgbm_class_0': 0.07985115539248364, 'weight_lgbm_class_1': 0.7417607206442195, 'weight_lgbm_class_2': 0.8365981326944301, 'weight_xgb_class_0': 0.001149320501246373, 'weight_xgb_class_1': 0.4928199848063222, 'weight_xgb_class_2': 0.4762730821030929, 'weight_cat_class_0': 0.07216612739695992, 'weight_cat_class_1': 0.8165474875742889, 'weight_cat_class_2': 0.4147910649094958}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,462] Trial 1281 finished with value: 0.9492217781229155 and parameters: {'weight_lgbm_class_0': 0.08548289704894818, 'weight_lgbm_class_1': 0.7364048184574881, 'weight_lgbm_class_2': 0.897280407559777, 'weight_xgb_class_0': 0.04844723838537946, 'weight_xgb_class_1': 0.2935375785320792, 'weight_xgb_class_2': 0.47333823452158624, 'weight_cat_class_0': 0.07442500709866429, 'weight_cat_class_1': 0.8147476807545938, 'weight_cat_class_2': 0.42758707822652126}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,508] Trial 1282 finished with value: 0.9492571582500308 and parameters: {'weight_lgbm_class_0': 0.08074515792498366, 'weight_lgbm_class_1': 0.7266588375070149, 'weight_lgbm_class_2': 0.8424232927296602, 'weight_xgb_class_0': 0.036497256718653066, 'weight_xgb_class_1': 0.2924189703085931, 'weight_xgb_class_2': 0.4835101916697186, 'weight_cat_class_0': 0.07776764027180373, 'weight_cat_class_1': 0.84332155109647, 'weight_cat_class_2': 0.4248185982822273}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  64%|███████████████████████████████████████████████████████████████████████████████████▌                                              | 1285/2000 [00:47<00:33, 21.59it/s]

[I 2026-07-03 10:23:23,571] Trial 1283 finished with value: 0.918103676036553 and parameters: {'weight_lgbm_class_0': 0.6422096030892567, 'weight_lgbm_class_1': 0.7313960900456844, 'weight_lgbm_class_2': 0.8850541853717381, 'weight_xgb_class_0': 0.048487575726700344, 'weight_xgb_class_1': 0.29970398282852606, 'weight_xgb_class_2': 0.4790300254198997, 'weight_cat_class_0': 0.07116956445004352, 'weight_cat_class_1': 0.22859640934489078, 'weight_cat_class_2': 0.3468956889872304}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,619] Trial 1284 finished with value: 0.949349587076833 and parameters: {'weight_lgbm_class_0': 0.08274022976508659, 'weight_lgbm_class_1': 0.7318522255172815, 'weight_lgbm_class_2': 0.8966172582412938, 'weight_xgb_class_0': 0.050228429962399, 'weight_xgb_class_1': 0.49944476454187703, 'weight_xgb_class_2': 0.4785896289524098, 'weight_cat_class_0': 0.065826979604622, 'weight_cat_class_1': 0.8462364176634258, 'weight_cat_class_2': 0.34848436292906115}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,768] Trial 1285 finished with value: 0.9330864930265896 and parameters: {'weight_lgbm_class_0': 0.05315071937405107, 'weight_lgbm_class_1': 0.7255403907764395, 'weight_lgbm_class_2': 0.8894638583403143, 'weight_xgb_class_0': 0.5824076940807571, 'weight_xgb_class_1': 0.4608679722217027, 'weight_xgb_class_2': 0.4916068185878781, 'weight_cat_class_0': 0.0011351901115056358, 'weight_cat_class_1': 0.8383369261403525, 'weight_cat_class_2': 0.2901650565694001}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  65%|███████████████████████████████████████████████████████████████████████████████████▉                                              | 1292/2000 [00:48<00:32, 21.90it/s]

[I 2026-07-03 10:23:23,812] Trial 1286 finished with value: 0.9495688307947664 and parameters: {'weight_lgbm_class_0': 0.05054697897941838, 'weight_lgbm_class_1': 0.72515895246876, 'weight_lgbm_class_2': 0.8232005517769486, 'weight_xgb_class_0': 0.052822503296882144, 'weight_xgb_class_1': 0.4985023831637641, 'weight_xgb_class_2': 0.4818697195577484, 'weight_cat_class_0': 0.0016034636798513205, 'weight_cat_class_1': 0.845775357309415, 'weight_cat_class_2': 0.2726634940797099}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,848] Trial 1289 finished with value: 0.9496941388763381 and parameters: {'weight_lgbm_class_0': 0.05356542173097824, 'weight_lgbm_class_1': 0.7276001066182285, 'weight_lgbm_class_2': 0.7747388304993723, 'weight_xgb_class_0': 0.09859005258468855, 'weight_xgb_class_1': 0.5630318679862857, 'weight_xgb_class_2': 0.48494264572838086, 'weight_cat_class_0': 0.000632357476015601, 'weight_cat_class_1': 0.8483757684307088, 'weight_cat_class_2': 0.34126060966883}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,849] Trial 1287 finished with value: 0.9490127268632657 and parameters: {'weight_lgbm_class_0': 0.06327251064590504, 'weight_lgbm_class_1': 0.7446781916972075, 'weight_lgbm_class_2': 0.8964432153079699, 'weight_xgb_class_0': 0.09804466588411118, 'weight_xgb_class_1': 0.4613779168567731, 'weight_xgb_class_2': 0.483954629221265, 'weight_cat_class_0': 0.06627787493228121, 'weight_cat_class_1': 0.7484340964663836, 'weight_cat_class_2': 0.44496194167474173}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,874] Trial 1288 finished with value: 0.9497488602424456 and parameters: {'weight_lgbm_class_0': 0.05002241443308383, 'weight_lgbm_class_1': 0.7355737317613316, 'weight_lgbm_class_2': 0.891317731844526, 'weight_xgb_class_0': 0.09908900654832146, 'weight_xgb_class_1': 0.46024210885919925, 'weight_xgb_class_2': 0.47948664657531376, 'weight_cat_class_0': 0.0003646511047702231, 'weight_cat_class_1': 0.8509898289843123, 'weight_cat_class_2': 0.4730692680719316}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,903] Trial 1290 finished with value: 0.9497149714734826 and parameters: {'weight_lgbm_class_0': 0.054121419902805425, 'weight_lgbm_class_1': 0.7288529567753079, 'weight_lgbm_class_2': 0.8984986995391978, 'weight_xgb_class_0': 0.10137942833024063, 'weight_xgb_class_1': 0.46078335173634694, 'weight_xgb_class_2': 0.4874929818719436, 'weight_cat_class_0': 2.4915219284056545e-05, 'weight_cat_class_1': 0.8419896799630145, 'weight_cat_class_2': 0.4694199670229118}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,963] Trial 1291 finished with value: 0.9493874596546209 and parameters: {'weight_lgbm_class_0': 0.05371423771738092, 'weight_lgbm_class_1': 0.7232482059516886, 'weight_lgbm_class_2': 0.8937607558500454, 'weight_xgb_class_0': 0.09655392074698324, 'weight_xgb_class_1': 0.457902508018128, 'weight_xgb_class_2': 0.4911775788148675, 'weight_cat_class_0': 0.00016397329503355443, 'weight_cat_class_1': 0.22652784703069895, 'weight_cat_class_2': 0.27911424814534985}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:23,997] Trial 1292 finished with value: 0.9496984632956846 and parameters: {'weight_lgbm_class_0': 0.05308157264337167, 'weight_lgbm_class_1': 0.7516140753765422, 'weight_lgbm_class_2': 0.7678881169352965, 'weight_xgb_class_0': 0.0014633082545590648, 'weight_xgb_class_1': 0.45331453052135395, 'weight_xgb_class_2': 0.4924366023140282, 'weight_cat_class_0': 0.061942826535508186, 'weight_cat_class_1': 0.842183699535989, 'weight_cat_class_2': 0.27140070930683485}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  65%|████████████████████████████████████████████████████████████████████████████████████▏                                             | 1296/2000 [00:48<00:30, 23.19it/s]

[I 2026-07-03 10:23:24,031] Trial 1293 finished with value: 0.9492516242276063 and parameters: {'weight_lgbm_class_0': 0.05271372574812863, 'weight_lgbm_class_1': 0.04725830387227259, 'weight_lgbm_class_2': 0.78050689804978, 'weight_xgb_class_0': 0.003510385322023943, 'weight_xgb_class_1': 0.4515302618170289, 'weight_xgb_class_2': 0.4918401417582294, 'weight_cat_class_0': 0.05950591709674582, 'weight_cat_class_1': 0.8454452362684832, 'weight_cat_class_2': 0.47920085751836394}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:24,082] Trial 1294 finished with value: 0.9479780248905794 and parameters: {'weight_lgbm_class_0': 0.053470276594230474, 'weight_lgbm_class_1': 0.7800318759738344, 'weight_lgbm_class_2': 0.8058082865936986, 'weight_xgb_class_0': 0.0030903392419651884, 'weight_xgb_class_1': 0.45020493048352955, 'weight_xgb_class_2': 0.4912334290907913, 'weight_cat_class_0': 0.2175309788428229, 'weight_cat_class_1': 0.8348799146361375, 'weight_cat_class_2': 0.2822687958835048}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:24,148] Trial 1295 finished with value: 0.949714608030475 and parameters: {'weight_lgbm_class_0': 0.05804524560386188, 'weight_lgbm_class_1': 0.7863702270389136, 'weight_lgbm_class_2': 0.819555582386076, 'weight_xgb_class_0': 0.014419424435999171, 'weight_xgb_class_1': 0.4667500228040637, 'weight_xgb_class_2': 0.43686918563507515, 'weight_cat_class_0': 0.05766939526229261, 'weight_cat_class_1': 0.8412158358046762, 'weight_cat_class_2': 0.2653319469585231}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:24,200] Trial 1296 finished with value: 0.9497026020664782 and parameters: {'weight_lgbm_class_0': 0.05521379086797663, 'weight_lgbm_class_1': 0.7806722039350301, 'weight_lgbm_class_2': 0.7791973450203309, 'weight_xgb_class_0': 0.015633097201032058, 'weight_xgb_class_1': 0.4584496429493958, 'weight_xgb_class_2': 0.4959379908101134, 'weight_cat_class_0': 0.059237026114189226, 'weight_cat_class_1': 0.8335680700556164, 'weight_cat_class_2': 0.2732202211940998}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:24,368] Trial 1297 finished with value: 0.9487178303883498 and parameters: {'weight_lgbm_class_0': 0.05253158397015845, 'weight_lgbm_class_1': 0.7878782694669845, 'weight_lgbm_class_2': 0.815260832129802, 'weight_xgb_class_0': 0.01885127389436972, 'weight_xgb_class_1': 0.46174532885335823, 'weight_xgb_class_2': 0.44208284693324545, 'weight_cat_class_0': 0.0004231880808137161, 'weight_cat_class_1': 0.8392455614033493, 'weight_cat_class_2': 0.2740938922998691}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:24,374] Trial 1298 finished with value: 0.9497678660388037 and parameters: {'weight_lgbm_class_0': 0.056828239939115524, 'weight_lgbm_class_1': 0.7799843641558886, 'weight_lgbm_class_2': 0.7755114600039008, 'weight_xgb_class_0': 0.01486326403430957, 'weight_xgb_class_1': 0.4661377856957304, 'weight_xgb_class_2': 0.444140259744081, 'weight_cat_class_0': 0.05530503131863907, 'weight_cat_class_1': 0.8490641757522605, 'weight_cat_class_2': 0.4830052929799385}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:24,399] Trial 1299 finished with value: 0.9497813145381482 and parameters: {'weight_lgbm_class_0': 0.012306137630917407, 'weight_lgbm_class_1': 0.7796479579896426, 'weight_lgbm_class_2': 0.8181786442684306, 'weight_xgb_class_0': 0.117929616260895, 'weight_xgb_class_1': 0.4630195043931707, 'weight_xgb_class_2': 0.4391959682558825, 'weight_cat_class_0': 0.017230407316463397, 'weight_cat_class_1': 0.8571743310946954, 'weight_cat_class_2': 0.4787796772024942}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:24,479] Trial 1300 finished with value: 0.9497389889013608 and parameters: {'weight_lgbm_class_0': 0.011866461836353351, 'weight_lgbm_class_1': 0.7799271245588449, 'weight_lgbm_class_2': 0.8134002276622029, 'weight_xgb_class_0': 0.11899176350921087, 'weight_xgb_class_1': 0.4575693402108722, 'weight_xgb_class_2': 0.44512190455698103, 'weight_cat_class_0': 0.00017222891944380762, 'weight_cat_class_1': 0.8299233558013106, 'weight_cat_class_2': 0.426955042132652}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:24,480] Trial 1301 finished with value: 0.9495989998819576 and parameters: {'weight_lgbm_class_0': 0.015166209558983748, 'weight_lgbm_class_1': 0.7543463046148626, 'weight_lgbm_class_2': 0.8226809294892877, 'weight_xgb_class_0': 0.12924039017762065, 'weight_xgb_class_1': 0.41140241185915194, 'weight_xgb_class_2': 0.4424796400331256, 'weight_cat_class_0': 0.017569875057039688, 'weight_cat_class_1': 0.8482653016652588, 'weight_cat_class_2': 0.4801885352340485}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:24,495] Trial 1302 finished with value: 0.9497226138587407 and parameters: {'weight_lgbm_class_0': 0.011749088615038736, 'weight_lgbm_class_1': 0.7539521503646521, 'weight_lgbm_class_2': 0.8195302733708032, 'weight_xgb_class_0': 0.10781881531870902, 'weight_xgb_class_1': 0.4671438761583815, 'weight_xgb_class_2': 0.4474437064374129, 'weight_cat_class_0': 0.01611884372546842, 'weight_cat_class_1': 0.8466628052304079, 'weight_cat_class_2': 0.4867737759961409}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:24,573] Trial 1303 finished with value: 0.9497366753068871 and parameters: {'weight_lgbm_class_0': 0.02234861094576709, 'weight_lgbm_class_1': 0.791511351897011, 'weight_lgbm_class_2': 0.7890108570848491, 'weight_xgb_class_0': 0.10457691608966767, 'weight_xgb_class_1': 0.41162399160916413, 'weight_xgb_class_2': 0.44240812029394083, 'weight_cat_class_0': 0.0008596225409196745, 'weight_cat_class_1': 0.8503526390348604, 'weight_cat_class_2': 0.4479055188779493}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  65%|█████████████████████████████████████████████████████████████████████████████████████                                             | 1308/2000 [00:48<00:30, 22.72it/s]

[I 2026-07-03 10:23:24,583] Trial 1304 finished with value: 0.9497075401619167 and parameters: {'weight_lgbm_class_0': 0.014489172366226634, 'weight_lgbm_class_1': 0.7545319481820626, 'weight_lgbm_class_2': 0.8103958779680334, 'weight_xgb_class_0': 0.10241206168337816, 'weight_xgb_class_1': 0.4626204333440157, 'weight_xgb_class_2': 0.4414113611420088, 'weight_cat_class_0': 0.01651505858865384, 'weight_cat_class_1': 0.8264019748568809, 'weight_cat_class_2': 0.4697103029005658}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:24,635] Trial 1305 finished with value: 0.9496329957567452 and parameters: {'weight_lgbm_class_0': 0.01737697308059322, 'weight_lgbm_class_1': 0.7615185180355895, 'weight_lgbm_class_2': 0.8160110117061824, 'weight_xgb_class_0': 0.11078730537610382, 'weight_xgb_class_1': 0.48476041783527407, 'weight_xgb_class_2': 0.441467740235096, 'weight_cat_class_0': 0.03632211528595258, 'weight_cat_class_1': 0.8457946237843067, 'weight_cat_class_2': 0.47285363399476965}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:24,693] Trial 1306 finished with value: 0.9497097226361205 and parameters: {'weight_lgbm_class_0': 0.03046261402120545, 'weight_lgbm_class_1': 0.752056026993863, 'weight_lgbm_class_2': 0.8190941711824877, 'weight_xgb_class_0': 0.12501243371928442, 'weight_xgb_class_1': 0.4826407268202485, 'weight_xgb_class_2': 0.45196196757270857, 'weight_cat_class_0': 0.0005801401456426818, 'weight_cat_class_1': 0.8487923818979133, 'weight_cat_class_2': 0.45643086130695026}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:24,701] Trial 1307 finished with value: 0.9495569129234772 and parameters: {'weight_lgbm_class_0': 0.014240985848640753, 'weight_lgbm_class_1': 0.7609256155776645, 'weight_lgbm_class_2': 0.8157064758527611, 'weight_xgb_class_0': 0.13669567991254933, 'weight_xgb_class_1': 0.4169102202087305, 'weight_xgb_class_2': 0.4427139475344228, 'weight_cat_class_0': 0.018783828710736482, 'weight_cat_class_1': 0.8498386507432987, 'weight_cat_class_2': 0.4707675502511253}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:24,749] Trial 1308 finished with value: 0.948992278639209 and parameters: {'weight_lgbm_class_0': 0.013302753729052617, 'weight_lgbm_class_1': 0.7547495142608147, 'weight_lgbm_class_2': 0.8271838200140254, 'weight_xgb_class_0': 0.12486571513311676, 'weight_xgb_class_1': 0.40220346205677404, 'weight_xgb_class_2': 0.4422063321858442, 'weight_cat_class_0': 0.0359314237839935, 'weight_cat_class_1': 0.7988360868551607, 'weight_cat_class_2': 0.07798878787580582}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  66%|█████████████████████████████████████████████████████████████████████████████████████▍                                            | 1315/2000 [00:49<00:34, 20.11it/s]

[I 2026-07-03 10:23:24,950] Trial 1310 finished with value: 0.9489631538926552 and parameters: {'weight_lgbm_class_0': 0.0008788523304437551, 'weight_lgbm_class_1': 0.7790920876134804, 'weight_lgbm_class_2': 0.8076155587079068, 'weight_xgb_class_0': 0.13285565439591462, 'weight_xgb_class_1': 0.48753470537276644, 'weight_xgb_class_2': 0.4460663866780829, 'weight_cat_class_0': 0.10189306012312256, 'weight_cat_class_1': 0.8432675595855099, 'weight_cat_class_2': 0.4785792425118461}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:24,976] Trial 1309 finished with value: 0.927050992273403 and parameters: {'weight_lgbm_class_0': 0.01328656604879718, 'weight_lgbm_class_1': 0.7920635798973927, 'weight_lgbm_class_2': 0.7851252185970012, 'weight_xgb_class_0': 0.16005643327219812, 'weight_xgb_class_1': 0.48607436533920917, 'weight_xgb_class_2': 0.43992805259164375, 'weight_cat_class_0': 0.6321023354748772, 'weight_cat_class_1': 0.8641606552598179, 'weight_cat_class_2': 0.48106708870857157}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,016] Trial 1311 finished with value: 0.9487694010349778 and parameters: {'weight_lgbm_class_0': 0.015792795779489745, 'weight_lgbm_class_1': 0.7822412069295737, 'weight_lgbm_class_2': 0.7840860743932072, 'weight_xgb_class_0': 0.1316042825656279, 'weight_xgb_class_1': 0.48774432627392056, 'weight_xgb_class_2': 0.4431666631302177, 'weight_cat_class_0': 0.09823271032223453, 'weight_cat_class_1': 0.8559094002846384, 'weight_cat_class_2': 0.4838052700199342}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,026] Trial 1312 finished with value: 0.9487094187168692 and parameters: {'weight_lgbm_class_0': 0.022315779517919347, 'weight_lgbm_class_1': 0.7877584071661464, 'weight_lgbm_class_2': 0.77874899394403, 'weight_xgb_class_0': 0.156678586249342, 'weight_xgb_class_1': 0.48590912754140875, 'weight_xgb_class_2': 0.9112604810409144, 'weight_cat_class_0': 0.10087507459989084, 'weight_cat_class_1': 0.8610598715998475, 'weight_cat_class_2': 0.476828636002613}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,071] Trial 1313 finished with value: 0.9496206698449426 and parameters: {'weight_lgbm_class_0': 0.001326353956635981, 'weight_lgbm_class_1': 0.7894045245534669, 'weight_lgbm_class_2': 0.7987510723944309, 'weight_xgb_class_0': 0.12470697030685746, 'weight_xgb_class_1': 0.4837324443502984, 'weight_xgb_class_2': 0.46388204717304343, 'weight_cat_class_0': 0.04407716581095444, 'weight_cat_class_1': 0.8453261638978211, 'weight_cat_class_2': 0.4649874325405082}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,127] Trial 1314 finished with value: 0.9483915658054366 and parameters: {'weight_lgbm_class_0': 0.005496323741837172, 'weight_lgbm_class_1': 0.7762831752133148, 'weight_lgbm_class_2': 0.8033190685215765, 'weight_xgb_class_0': 0.11479550919392795, 'weight_xgb_class_1': 0.48388384545754154, 'weight_xgb_class_2': 0.4654664054725686, 'weight_cat_class_0': 0.15325033161032503, 'weight_cat_class_1': 0.860268097469641, 'weight_cat_class_2': 0.4628642650948478}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,129] Trial 1315 finished with value: 0.9478174088352733 and parameters: {'weight_lgbm_class_0': 0.00972376439604225, 'weight_lgbm_class_1': 0.7821847097556393, 'weight_lgbm_class_2': 0.733181579478486, 'weight_xgb_class_0': 0.1369030854592838, 'weight_xgb_class_1': 0.48210187816406946, 'weight_xgb_class_2': 0.468853472894143, 'weight_cat_class_0': 0.14461109753330886, 'weight_cat_class_1': 0.8533385574291911, 'weight_cat_class_2': 0.4655025789192781}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  66%|█████████████████████████████████████████████████████████████████████████████████████▊                                            | 1321/2000 [00:49<00:27, 24.50it/s]

[I 2026-07-03 10:23:25,185] Trial 1317 finished with value: 0.9477589196484585 and parameters: {'weight_lgbm_class_0': 0.043312061659689614, 'weight_lgbm_class_1': 0.7653749735980878, 'weight_lgbm_class_2': 0.7744010049298801, 'weight_xgb_class_0': 0.15361775720873877, 'weight_xgb_class_1': 0.48116515727729325, 'weight_xgb_class_2': 0.46182540339571015, 'weight_cat_class_0': 0.10222011229916773, 'weight_cat_class_1': 0.8613224599157788, 'weight_cat_class_2': 0.4707543440739507}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,204] Trial 1316 finished with value: 0.948519280668206 and parameters: {'weight_lgbm_class_0': 0.006299023874957156, 'weight_lgbm_class_1': 0.7839408541150694, 'weight_lgbm_class_2': 0.7752214218354564, 'weight_xgb_class_0': 0.1564111750162262, 'weight_xgb_class_1': 0.48368232642627995, 'weight_xgb_class_2': 0.4646360682994013, 'weight_cat_class_0': 0.09642163794234689, 'weight_cat_class_1': 0.8555532173263345, 'weight_cat_class_2': 0.4680388156690651}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,276] Trial 1319 finished with value: 0.9487446481194158 and parameters: {'weight_lgbm_class_0': 0.007485272169895585, 'weight_lgbm_class_1': 0.7863812792221927, 'weight_lgbm_class_2': 0.7780887569343157, 'weight_xgb_class_0': 0.13256913553428223, 'weight_xgb_class_1': 0.49611830711270155, 'weight_xgb_class_2': 0.46387084144907687, 'weight_cat_class_0': 0.10632064301174002, 'weight_cat_class_1': 0.861513003179787, 'weight_cat_class_2': 0.45121325495827547}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,305] Trial 1320 finished with value: 0.9495529519857685 and parameters: {'weight_lgbm_class_0': 0.002038905594693132, 'weight_lgbm_class_1': 0.7868094483087096, 'weight_lgbm_class_2': 0.7966201626580842, 'weight_xgb_class_0': 0.00039098155201086436, 'weight_xgb_class_1': 0.48992831056829245, 'weight_xgb_class_2': 0.4618368155542682, 'weight_cat_class_0': 0.10777769429831939, 'weight_cat_class_1': 0.8300411323930547, 'weight_cat_class_2': 0.4825347901923997}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,316] Trial 1318 finished with value: 0.9484789764395556 and parameters: {'weight_lgbm_class_0': 0.0019313607560677015, 'weight_lgbm_class_1': 0.7891026130067661, 'weight_lgbm_class_2': 0.8107242722374314, 'weight_xgb_class_0': 0.1545892396982, 'weight_xgb_class_1': 0.48408903065596404, 'weight_xgb_class_2': 0.4618780472889904, 'weight_cat_class_0': 0.11185683951245795, 'weight_cat_class_1': 0.8573582021687212, 'weight_cat_class_2': 0.4845184951353728}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  66%|██████████████████████████████████████████████████████████████████████████████████████▏                                           | 1326/2000 [00:49<00:35, 18.78it/s]

[I 2026-07-03 10:23:25,518] Trial 1321 finished with value: 0.9466308474047516 and parameters: {'weight_lgbm_class_0': 0.001688240987074409, 'weight_lgbm_class_1': 0.8016499183941587, 'weight_lgbm_class_2': 0.7734634968120946, 'weight_xgb_class_0': 0.25723026094920354, 'weight_xgb_class_1': 0.48940482299347565, 'weight_xgb_class_2': 0.4678215134092199, 'weight_cat_class_0': 0.09339394093921355, 'weight_cat_class_1': 0.8585907290429561, 'weight_cat_class_2': 0.502507448172996}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,581] Trial 1322 finished with value: 0.9466504344922794 and parameters: {'weight_lgbm_class_0': 0.0336126353394313, 'weight_lgbm_class_1': 0.7826351762836986, 'weight_lgbm_class_2': 0.7510505204073998, 'weight_xgb_class_0': 0.15973512935460926, 'weight_xgb_class_1': 0.4798942275698814, 'weight_xgb_class_2': 0.41957842232519293, 'weight_cat_class_0': 0.14898136360627903, 'weight_cat_class_1': 0.8612145734493769, 'weight_cat_class_2': 0.49896261532330155}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,595] Trial 1323 finished with value: 0.9476402166147117 and parameters: {'weight_lgbm_class_0': 0.03613290538574494, 'weight_lgbm_class_1': 0.7942583746688997, 'weight_lgbm_class_2': 0.7748908544045285, 'weight_xgb_class_0': 0.1504527421794275, 'weight_xgb_class_1': 0.499846933527307, 'weight_xgb_class_2': 0.46202715294550956, 'weight_cat_class_0': 0.11651380518345023, 'weight_cat_class_1': 0.8627325504759659, 'weight_cat_class_2': 0.44934720535636286}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,647] Trial 1324 finished with value: 0.9176603216121578 and parameters: {'weight_lgbm_class_0': 0.6098515092769423, 'weight_lgbm_class_1': 0.8006144182824599, 'weight_lgbm_class_2': 0.7607974467860528, 'weight_xgb_class_0': 0.2518640754089463, 'weight_xgb_class_1': 0.5637657918614892, 'weight_xgb_class_2': 0.41812524951726804, 'weight_cat_class_0': 0.10861423951347314, 'weight_cat_class_1': 0.860628389114336, 'weight_cat_class_2': 0.44838117299262403}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,686] Trial 1325 finished with value: 0.9482602277139708 and parameters: {'weight_lgbm_class_0': 0.03735693885267004, 'weight_lgbm_class_1': 0.8038303300479063, 'weight_lgbm_class_2': 0.793282218154938, 'weight_xgb_class_0': 0.15913118443608487, 'weight_xgb_class_1': 0.5441290663994065, 'weight_xgb_class_2': 0.46831772817214656, 'weight_cat_class_0': 0.08581207642796167, 'weight_cat_class_1': 0.864625882467195, 'weight_cat_class_2': 0.44571135431577835}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,712] Trial 1326 finished with value: 0.9496644188987684 and parameters: {'weight_lgbm_class_0': 0.03146353618451729, 'weight_lgbm_class_1': 0.8121285509063746, 'weight_lgbm_class_2': 0.7661935484095855, 'weight_xgb_class_0': 0.0010228959683275835, 'weight_xgb_class_1': 0.560757491708742, 'weight_xgb_class_2': 0.4203528792306419, 'weight_cat_class_0': 0.09108745742012672, 'weight_cat_class_1': 0.829884472974542, 'weight_cat_class_2': 0.4429696782435938}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  67%|██████████████████████████████████████████████████████████████████████████████████████▌                                           | 1332/2000 [00:50<00:32, 20.71it/s]

[I 2026-07-03 10:23:25,777] Trial 1327 finished with value: 0.9496961595648985 and parameters: {'weight_lgbm_class_0': 0.03506554516597557, 'weight_lgbm_class_1': 0.8076565807944628, 'weight_lgbm_class_2': 0.7329742808276345, 'weight_xgb_class_0': 0.0008473201174745172, 'weight_xgb_class_1': 0.5363145651572016, 'weight_xgb_class_2': 0.41003491197064923, 'weight_cat_class_0': 0.11238702697306402, 'weight_cat_class_1': 0.8227472839760805, 'weight_cat_class_2': 0.4489113360860071}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,791] Trial 1328 finished with value: 0.9497110207488769 and parameters: {'weight_lgbm_class_0': 0.031955939173369655, 'weight_lgbm_class_1': 0.8113452173656619, 'weight_lgbm_class_2': 0.758258068154406, 'weight_xgb_class_0': 0.02375121980109445, 'weight_xgb_class_1': 0.5569429830917377, 'weight_xgb_class_2': 0.42530755995636055, 'weight_cat_class_0': 0.08505533511453026, 'weight_cat_class_1': 0.826190050060345, 'weight_cat_class_2': 0.4960565304208095}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,848] Trial 1330 finished with value: 0.9497173367536401 and parameters: {'weight_lgbm_class_0': 0.03429928705697373, 'weight_lgbm_class_1': 0.797214223705971, 'weight_lgbm_class_2': 0.7560446522318766, 'weight_xgb_class_0': 0.028648798395436992, 'weight_xgb_class_1': 0.5584867395044175, 'weight_xgb_class_2': 0.412000310854741, 'weight_cat_class_0': 0.08841698188479091, 'weight_cat_class_1': 0.8271391165928752, 'weight_cat_class_2': 0.48900320642137196}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,860] Trial 1329 finished with value: 0.9497007181008691 and parameters: {'weight_lgbm_class_0': 0.038438806297454435, 'weight_lgbm_class_1': 0.8047658670059139, 'weight_lgbm_class_2': 0.8254834344472991, 'weight_xgb_class_0': 0.025548226014561328, 'weight_xgb_class_1': 0.5570719067602301, 'weight_xgb_class_2': 0.41210387314792574, 'weight_cat_class_0': 0.058572941424127806, 'weight_cat_class_1': 0.8272830667672798, 'weight_cat_class_2': 0.4926854578108946}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,898] Trial 1331 finished with value: 0.949611850287407 and parameters: {'weight_lgbm_class_0': 0.03948646586078153, 'weight_lgbm_class_1': 0.7983345154434207, 'weight_lgbm_class_2': 0.8291432041843254, 'weight_xgb_class_0': 0.02759293386645513, 'weight_xgb_class_1': 0.5658899086020229, 'weight_xgb_class_2': 0.41917821674424766, 'weight_cat_class_0': 0.049260909758416266, 'weight_cat_class_1': 0.8275231729595444, 'weight_cat_class_2': 0.49922919880227423}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:25,924] Trial 1332 finished with value: 0.9497327136442836 and parameters: {'weight_lgbm_class_0': 0.03510565668125308, 'weight_lgbm_class_1': 0.8068951751863347, 'weight_lgbm_class_2': 0.8255108260392936, 'weight_xgb_class_0': 0.03154604104774183, 'weight_xgb_class_1': 0.5431625482134912, 'weight_xgb_class_2': 0.42460041059479836, 'weight_cat_class_0': 0.07737674097401494, 'weight_cat_class_1': 0.8262759538248716, 'weight_cat_class_2': 0.5038235532770621}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  67%|██████████████████████████████████████████████████████████████████████████████████████▉                                           | 1337/2000 [00:50<00:34, 19.03it/s]

[I 2026-07-03 10:23:26,087] Trial 1333 finished with value: 0.9300586315430602 and parameters: {'weight_lgbm_class_0': 0.601153565024995, 'weight_lgbm_class_1': 0.767790760362883, 'weight_lgbm_class_2': 0.7367438598920544, 'weight_xgb_class_0': 0.030809370839533473, 'weight_xgb_class_1': 0.5582296150625043, 'weight_xgb_class_2': 0.4186338994185776, 'weight_cat_class_0': 0.08361575627575077, 'weight_cat_class_1': 0.8342930149100733, 'weight_cat_class_2': 0.44082984171454404}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:26,163] Trial 1334 finished with value: 0.9215750896904137 and parameters: {'weight_lgbm_class_0': 0.03951847256880338, 'weight_lgbm_class_1': 0.8129001195528386, 'weight_lgbm_class_2': 0.8295835796221237, 'weight_xgb_class_0': 0.02702354229225342, 'weight_xgb_class_1': 0.5579256187586429, 'weight_xgb_class_2': 0.4205536199552731, 'weight_cat_class_0': 0.8453924737863774, 'weight_cat_class_1': 0.8300664788396612, 'weight_cat_class_2': 0.4271515965805641}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:26,193] Trial 1335 finished with value: 0.9497073681293929 and parameters: {'weight_lgbm_class_0': 0.03656542605569318, 'weight_lgbm_class_1': 0.8079701015770548, 'weight_lgbm_class_2': 0.833191593215256, 'weight_xgb_class_0': 0.028557351896446086, 'weight_xgb_class_1': 0.5562972803407743, 'weight_xgb_class_2': 0.41811172756580545, 'weight_cat_class_0': 0.0849894124296465, 'weight_cat_class_1': 0.8265993863685741, 'weight_cat_class_2': 0.4514516984154542}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:26,235] Trial 1336 finished with value: 0.9497075920121684 and parameters: {'weight_lgbm_class_0': 0.03402843357764934, 'weight_lgbm_class_1': 0.7490123022237799, 'weight_lgbm_class_2': 0.7346914475984896, 'weight_xgb_class_0': 0.000640826009036814, 'weight_xgb_class_1': 0.5415388740725442, 'weight_xgb_class_2': 0.4208970674519059, 'weight_cat_class_0': 0.08344768962621987, 'weight_cat_class_1': 0.8082396547506933, 'weight_cat_class_2': 0.4401345760203073}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:26,291] Trial 1337 finished with value: 0.9495905634793774 and parameters: {'weight_lgbm_class_0': 0.032343106960171314, 'weight_lgbm_class_1': 0.7508841668396555, 'weight_lgbm_class_2': 0.8254486825531021, 'weight_xgb_class_0': 0.028533307173570104, 'weight_xgb_class_1': 0.5393868207319649, 'weight_xgb_class_2': 0.5040420705154083, 'weight_cat_class_0': 0.057570323147461945, 'weight_cat_class_1': 0.8212618736457432, 'weight_cat_class_2': 0.49408003970713826}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  67%|███████████████████████████████████████████████████████████████████████████████████████▎                                          | 1344/2000 [00:50<00:28, 23.42it/s]

[I 2026-07-03 10:23:26,340] Trial 1338 finished with value: 0.9497409218543426 and parameters: {'weight_lgbm_class_0': 0.036675045099339436, 'weight_lgbm_class_1': 0.7558525583551285, 'weight_lgbm_class_2': 0.8244147555503356, 'weight_xgb_class_0': 0.028641465976320404, 'weight_xgb_class_1': 0.5442244398134279, 'weight_xgb_class_2': 0.4193037437032124, 'weight_cat_class_0': 0.06224945070590109, 'weight_cat_class_1': 0.8312092486596416, 'weight_cat_class_2': 0.4882046524091471}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:26,351] Trial 1339 finished with value: 0.9496616957449726 and parameters: {'weight_lgbm_class_0': 0.0364318382100563, 'weight_lgbm_class_1': 0.7434277385211608, 'weight_lgbm_class_2': 0.8252652573629558, 'weight_xgb_class_0': 0.027734954880040144, 'weight_xgb_class_1': 0.5095724894698394, 'weight_xgb_class_2': 0.5030240803147908, 'weight_cat_class_0': 0.05541872581532076, 'weight_cat_class_1': 0.8085094006385942, 'weight_cat_class_2': 0.48790502307483147}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:26,369] Trial 1340 finished with value: 0.9495965749206526 and parameters: {'weight_lgbm_class_0': 0.034450439233559955, 'weight_lgbm_class_1': 0.740926259117972, 'weight_lgbm_class_2': 0.8332191729685356, 'weight_xgb_class_0': 0.02636929065084779, 'weight_xgb_class_1': 0.5128397268483046, 'weight_xgb_class_2': 0.4960029579844589, 'weight_cat_class_0': 0.055169890468041646, 'weight_cat_class_1': 0.8123361111440234, 'weight_cat_class_2': 0.5065666860298063}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:26,424] Trial 1342 finished with value: 0.9497187642955766 and parameters: {'weight_lgbm_class_0': 0.03463745747596689, 'weight_lgbm_class_1': 0.7648241716036545, 'weight_lgbm_class_2': 0.8363892433699113, 'weight_xgb_class_0': 0.0811898470064384, 'weight_xgb_class_1': 0.5113570638659055, 'weight_xgb_class_2': 0.5054491453030105, 'weight_cat_class_0': 0.041863256670788156, 'weight_cat_class_1': 0.7990153959079556, 'weight_cat_class_2': 0.5130916125868642}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:26,458] Trial 1341 finished with value: 0.9419439092149552 and parameters: {'weight_lgbm_class_0': 0.37166498923256497, 'weight_lgbm_class_1': 0.7568275224518152, 'weight_lgbm_class_2': 0.8199522579714236, 'weight_xgb_class_0': 0.08531802607665168, 'weight_xgb_class_1': 0.5048748209852408, 'weight_xgb_class_2': 0.5045590666651075, 'weight_cat_class_0': 0.04142244721043021, 'weight_cat_class_1': 0.8014881775795147, 'weight_cat_class_2': 0.5108225264029737}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:26,478] Trial 1343 finished with value: 0.9494162281027979 and parameters: {'weight_lgbm_class_0': 0.06444851140247941, 'weight_lgbm_class_1': 0.7439357540385267, 'weight_lgbm_class_2': 0.8459109435583774, 'weight_xgb_class_0': 0.08623468384500022, 'weight_xgb_class_1': 0.512713069806042, 'weight_xgb_class_2': 0.49886520833944425, 'weight_cat_class_0': 0.04040444473478433, 'weight_cat_class_1': 0.802249445693816, 'weight_cat_class_2': 0.44230682778567065}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:26,510] Trial 1344 finished with value: 0.9188082379112578 and parameters: {'weight_lgbm_class_0': 0.06498199382120085, 'weight_lgbm_class_1': 0.7652614877259942, 'weight_lgbm_class_2': 0.8471627210906615, 'weight_xgb_class_0': 0.00036771173021948704, 'weight_xgb_class_1': 0.5082685127196794, 'weight_xgb_class_2': 0.5064462922343675, 'weight_cat_class_0': 0.9408565442846666, 'weight_cat_class_1': 0.8011012551373339, 'weight_cat_class_2': 0.5115568354779562}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  67%|███████████████████████████████████████████████████████████████████████████████████████▌                                          | 1348/2000 [00:51<00:36, 17.84it/s]

[I 2026-07-03 10:23:26,660] Trial 1345 finished with value: 0.9493418073779073 and parameters: {'weight_lgbm_class_0': 0.06145472046217726, 'weight_lgbm_class_1': 0.7523027039612152, 'weight_lgbm_class_2': 0.8525155352303355, 'weight_xgb_class_0': 0.0002348657214468682, 'weight_xgb_class_1': 0.5113970212835216, 'weight_xgb_class_2': 0.5026219798331829, 'weight_cat_class_0': 0.04037426699790006, 'weight_cat_class_1': 0.8031515400457493, 'weight_cat_class_2': 0.5135733437339819}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:26,768] Trial 1346 finished with value: 0.949464420874098 and parameters: {'weight_lgbm_class_0': 0.06804181449445355, 'weight_lgbm_class_1': 0.758356808120966, 'weight_lgbm_class_2': 0.8482373821431641, 'weight_xgb_class_0': 0.0004843357859885787, 'weight_xgb_class_1': 0.5105859254359519, 'weight_xgb_class_2': 0.5008066819051173, 'weight_cat_class_0': 0.03933093691592401, 'weight_cat_class_1': 0.8004588754556939, 'weight_cat_class_2': 0.5134065270753411}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:26,776] Trial 1347 finished with value: 0.9494697515639613 and parameters: {'weight_lgbm_class_0': 0.06754182494247288, 'weight_lgbm_class_1': 0.7455723224279067, 'weight_lgbm_class_2': 0.845988433260147, 'weight_xgb_class_0': 0.08797631660768493, 'weight_xgb_class_1': 0.5158236601212727, 'weight_xgb_class_2': 0.5028131022382855, 'weight_cat_class_0': 0.039310207817087384, 'weight_cat_class_1': 0.8038433641811632, 'weight_cat_class_2': 0.5132049722769682}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:26,840] Trial 1348 finished with value: 0.9495022063326216 and parameters: {'weight_lgbm_class_0': 0.06726314970759785, 'weight_lgbm_class_1': 0.7562687241517887, 'weight_lgbm_class_2': 0.8544358323007544, 'weight_xgb_class_0': 0.0861157240445806, 'weight_xgb_class_1': 0.5040949253828967, 'weight_xgb_class_2': 0.5005927048022164, 'weight_cat_class_0': 0.039859586065645665, 'weight_cat_class_1': 0.8043978056794102, 'weight_cat_class_2': 0.5110641857012272}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  68%|████████████████████████████████████████████████████████████████████████████████████████                                          | 1355/2000 [00:51<00:31, 20.49it/s]

[I 2026-07-03 10:23:26,884] Trial 1349 finished with value: 0.9494695717777403 and parameters: {'weight_lgbm_class_0': 0.06828943221930524, 'weight_lgbm_class_1': 0.7614227214846249, 'weight_lgbm_class_2': 0.8490483782920736, 'weight_xgb_class_0': 0.08126171244484726, 'weight_xgb_class_1': 0.5938761761911105, 'weight_xgb_class_2': 0.4976038281979064, 'weight_cat_class_0': 0.04083459122478148, 'weight_cat_class_1': 0.8013971264199341, 'weight_cat_class_2': 0.5108496145551129}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:26,935] Trial 1350 finished with value: 0.94948753095405 and parameters: {'weight_lgbm_class_0': 0.0688670678031499, 'weight_lgbm_class_1': 0.7647907733958397, 'weight_lgbm_class_2': 0.8043113976024325, 'weight_xgb_class_0': 0.0015593591232268204, 'weight_xgb_class_1': 0.5921775313895005, 'weight_xgb_class_2': 0.4010166118383579, 'weight_cat_class_0': 0.03694692470016067, 'weight_cat_class_1': 0.7971623246781407, 'weight_cat_class_2': 0.5092711196797697}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:26,991] Trial 1352 finished with value: 0.9261457546763155 and parameters: {'weight_lgbm_class_0': 0.06507516560334578, 'weight_lgbm_class_1': 0.763632634291398, 'weight_lgbm_class_2': 0.7975662119591481, 'weight_xgb_class_0': 0.0003129940192139771, 'weight_xgb_class_1': 0.4467451432266759, 'weight_xgb_class_2': 0.3925082483069832, 'weight_cat_class_0': 0.7425894590393022, 'weight_cat_class_1': 0.7963456800719573, 'weight_cat_class_2': 0.5167896193282295}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:27,024] Trial 1351 finished with value: 0.9496999755250074 and parameters: {'weight_lgbm_class_0': 0.06722212569659361, 'weight_lgbm_class_1': 0.7652300474224544, 'weight_lgbm_class_2': 0.7984732680630274, 'weight_xgb_class_0': 0.053688847929362835, 'weight_xgb_class_1': 0.604918461649867, 'weight_xgb_class_2': 0.4390381260214114, 'weight_cat_class_0': 0.03709617251727919, 'weight_cat_class_1': 0.7993782966530302, 'weight_cat_class_2': 0.5188995501681405}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:27,041] Trial 1353 finished with value: 0.9496786359825821 and parameters: {'weight_lgbm_class_0': 0.06084112821181142, 'weight_lgbm_class_1': 0.7574620484444834, 'weight_lgbm_class_2': 0.8152341210345371, 'weight_xgb_class_0': 0.057487738821609576, 'weight_xgb_class_1': 0.45056866750262453, 'weight_xgb_class_2': 0.404592176570674, 'weight_cat_class_0': 0.037912660161666625, 'weight_cat_class_1': 0.8024855896532382, 'weight_cat_class_2': 0.46961948557810335}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:27,051] Trial 1354 finished with value: 0.9493134449601887 and parameters: {'weight_lgbm_class_0': 0.0653483751569985, 'weight_lgbm_class_1': 0.7567830586955353, 'weight_lgbm_class_2': 0.8609462497425662, 'weight_xgb_class_0': 0.0016987390032410787, 'weight_xgb_class_1': 0.5881948059339014, 'weight_xgb_class_2': 0.39430229928492616, 'weight_cat_class_0': 0.03145226488045001, 'weight_cat_class_1': 0.8760785457279171, 'weight_cat_class_2': 0.46599917997425166}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:27,057] Trial 1355 finished with value: 0.9496402298495529 and parameters: {'weight_lgbm_class_0': 0.07634642204331105, 'weight_lgbm_class_1': 0.763012521928006, 'weight_lgbm_class_2': 0.8130699884766373, 'weight_xgb_class_0': 0.054216676788761374, 'weight_xgb_class_1': 0.604554339007782, 'weight_xgb_class_2': 0.4014860238092927, 'weight_cat_class_0': 0.03427747803583088, 'weight_cat_class_1': 0.8016614697209824, 'weight_cat_class_2': 0.4698174410475785}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  68%|████████████████████████████████████████████████████████████████████████████████████████▎                                         | 1358/2000 [00:51<00:31, 20.25it/s]

[I 2026-07-03 10:23:27,104] Trial 1356 finished with value: 0.9496186274087814 and parameters: {'weight_lgbm_class_0': 0.07605068317745477, 'weight_lgbm_class_1': 0.7729177222912289, 'weight_lgbm_class_2': 0.798182519263153, 'weight_xgb_class_0': 0.05702646745792634, 'weight_xgb_class_1': 0.5963406793706585, 'weight_xgb_class_2': 0.3986460583100982, 'weight_cat_class_0': 0.03644241029568129, 'weight_cat_class_1': 0.8721311429836704, 'weight_cat_class_2': 0.46758726189097055}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:27,277] Trial 1357 finished with value: 0.9496665464335026 and parameters: {'weight_lgbm_class_0': 0.07262740021361518, 'weight_lgbm_class_1': 0.7641407574318198, 'weight_lgbm_class_2': 0.7975363434549716, 'weight_xgb_class_0': 0.05709707298176183, 'weight_xgb_class_1': 0.5703329059486918, 'weight_xgb_class_2': 0.4068688448665484, 'weight_cat_class_0': 0.03516345099929795, 'weight_cat_class_1': 0.8644092752159434, 'weight_cat_class_2': 0.46112367180869224}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  68%|████████████████████████████████████████████████████████████████████████████████████████▌                                         | 1363/2000 [00:51<00:32, 19.86it/s]

[I 2026-07-03 10:23:27,391] Trial 1359 finished with value: 0.9493216004715591 and parameters: {'weight_lgbm_class_0': 0.10815844029241618, 'weight_lgbm_class_1': 0.7411633062490557, 'weight_lgbm_class_2': 0.7980944552014657, 'weight_xgb_class_0': 0.052422046438002357, 'weight_xgb_class_1': 0.538390125088215, 'weight_xgb_class_2': 0.397823646832481, 'weight_cat_class_0': 0.03377939267792715, 'weight_cat_class_1': 0.873747853761303, 'weight_cat_class_2': 0.46630066537908377}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:27,401] Trial 1358 finished with value: 0.9493590623510824 and parameters: {'weight_lgbm_class_0': 0.1022220642380467, 'weight_lgbm_class_1': 0.762923816576141, 'weight_lgbm_class_2': 0.7976735904213862, 'weight_xgb_class_0': 0.056967042141070054, 'weight_xgb_class_1': 0.4513883511793722, 'weight_xgb_class_2': 0.4408859994650354, 'weight_cat_class_0': 0.034724066978980395, 'weight_cat_class_1': 0.8743419237444124, 'weight_cat_class_2': 0.46679765797116257}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:27,438] Trial 1360 finished with value: 0.9493808542284553 and parameters: {'weight_lgbm_class_0': 0.09810083211960458, 'weight_lgbm_class_1': 0.771745554327356, 'weight_lgbm_class_2': 0.8052620884358705, 'weight_xgb_class_0': 0.055524224173003164, 'weight_xgb_class_1': 0.5828676831810549, 'weight_xgb_class_2': 0.39605702582066277, 'weight_cat_class_0': 0.03436679684060032, 'weight_cat_class_1': 0.8738350691309266, 'weight_cat_class_2': 0.47617944137973717}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:27,497] Trial 1362 finished with value: 0.9496238621494432 and parameters: {'weight_lgbm_class_0': 0.09693763979620221, 'weight_lgbm_class_1': 0.7791015116484277, 'weight_lgbm_class_2': 0.8039951066977035, 'weight_xgb_class_0': 0.054183142653723794, 'weight_xgb_class_1': 0.5987330994232565, 'weight_xgb_class_2': 0.40452187783425164, 'weight_cat_class_0': 0.020928568330012227, 'weight_cat_class_1': 0.8626638265007954, 'weight_cat_class_2': 0.4567459385970473}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:27,528] Trial 1361 finished with value: 0.9494336581412615 and parameters: {'weight_lgbm_class_0': 0.10634609821290555, 'weight_lgbm_class_1': 0.772858931505386, 'weight_lgbm_class_2': 0.8279152715839211, 'weight_xgb_class_0': 0.05587455612857934, 'weight_xgb_class_1': 0.6038845976370006, 'weight_xgb_class_2': 0.3910182617672397, 'weight_cat_class_0': 0.024921668511435673, 'weight_cat_class_1': 0.8499252262601874, 'weight_cat_class_2': 0.4671741764351245}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:27,584] Trial 1363 finished with value: 0.9495773458298397 and parameters: {'weight_lgbm_class_0': 0.10169437248007428, 'weight_lgbm_class_1': 0.7781814994632266, 'weight_lgbm_class_2': 0.8093674098900956, 'weight_xgb_class_0': 0.055210564937403984, 'weight_xgb_class_1': 0.59236930691551, 'weight_xgb_class_2': 0.43617545087679727, 'weight_cat_class_0': 0.02148437377330271, 'weight_cat_class_1': 0.8751629437740066, 'weight_cat_class_2': 0.4762650580825147}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  68%|████████████████████████████████████████████████████████████████████████████████████████▉                                         | 1369/2000 [00:51<00:29, 21.48it/s]

[I 2026-07-03 10:23:27,627] Trial 1365 finished with value: 0.9495932503931126 and parameters: {'weight_lgbm_class_0': 0.10068480610316657, 'weight_lgbm_class_1': 0.77690369594746, 'weight_lgbm_class_2': 0.7962237216383075, 'weight_xgb_class_0': 0.05256539286436536, 'weight_xgb_class_1': 0.5371272161129048, 'weight_xgb_class_2': 0.43206455207375194, 'weight_cat_class_0': 0.018104650315795303, 'weight_cat_class_1': 0.8715417899176049, 'weight_cat_class_2': 0.40873199754425643}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:27,653] Trial 1364 finished with value: 0.949644511398191 and parameters: {'weight_lgbm_class_0': 0.0997578156404861, 'weight_lgbm_class_1': 0.8191376649673561, 'weight_lgbm_class_2': 0.7915704061059508, 'weight_xgb_class_0': 0.05052610455973526, 'weight_xgb_class_1': 0.5355741225520377, 'weight_xgb_class_2': 0.43586878594392586, 'weight_cat_class_0': 0.019006232298641592, 'weight_cat_class_1': 0.8730748764084707, 'weight_cat_class_2': 0.4826651710860979}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:27,698] Trial 1366 finished with value: 0.9494257661730104 and parameters: {'weight_lgbm_class_0': 0.10808276592010585, 'weight_lgbm_class_1': 0.7392173388822274, 'weight_lgbm_class_2': 0.7890858336647039, 'weight_xgb_class_0': 0.052006179417119804, 'weight_xgb_class_1': 0.5324961306034289, 'weight_xgb_class_2': 0.44428901069715604, 'weight_cat_class_0': 0.020492198689296685, 'weight_cat_class_1': 0.8743364262326674, 'weight_cat_class_2': 0.4136669815658617}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:27,700] Trial 1368 finished with value: 0.9497487204843339 and parameters: {'weight_lgbm_class_0': 0.10086428378440429, 'weight_lgbm_class_1': 0.820597588036238, 'weight_lgbm_class_2': 0.8184366920151948, 'weight_xgb_class_0': 0.021672680844422875, 'weight_xgb_class_1': 0.5794314991274603, 'weight_xgb_class_2': 0.43529574444105223, 'weight_cat_class_0': 0.016998429558179744, 'weight_cat_class_1': 0.849895654791131, 'weight_cat_class_2': 0.48493248764349745}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:27,710] Trial 1367 finished with value: 0.9176852951470048 and parameters: {'weight_lgbm_class_0': 0.8438299300534975, 'weight_lgbm_class_1': 0.8211996990863897, 'weight_lgbm_class_2': 0.7890542465287305, 'weight_xgb_class_0': 0.12245188537561286, 'weight_xgb_class_1': 0.46445376177683506, 'weight_xgb_class_2': 0.4318823102213886, 'weight_cat_class_0': 0.017657063740767205, 'weight_cat_class_1': 0.8537635700787086, 'weight_cat_class_2': 0.48423952068826115}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:27,823] Trial 1369 finished with value: 0.9496078740913183 and parameters: {'weight_lgbm_class_0': 0.10156443922285018, 'weight_lgbm_class_1': 0.8222447413385002, 'weight_lgbm_class_2': 0.7863169738220793, 'weight_xgb_class_0': 0.017570447825021658, 'weight_xgb_class_1': 0.5351863365017268, 'weight_xgb_class_2': 0.7878426014185682, 'weight_cat_class_0': 0.06130720174186709, 'weight_cat_class_1': 0.8527633585747887, 'weight_cat_class_2': 0.4827568829831825}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  69%|█████████████████████████████████████████████████████████████████████████████████████████▎                                        | 1374/2000 [00:52<00:32, 19.41it/s]

[I 2026-07-03 10:23:27,953] Trial 1370 finished with value: 0.9495354113690695 and parameters: {'weight_lgbm_class_0': 0.09920581911976122, 'weight_lgbm_class_1': 0.7788745272587855, 'weight_lgbm_class_2': 0.8289199556126599, 'weight_xgb_class_0': 0.016107451278358623, 'weight_xgb_class_1': 0.46799844793074635, 'weight_xgb_class_2': 0.4327107999269551, 'weight_cat_class_0': 0.061687514338023546, 'weight_cat_class_1': 0.8379967153768437, 'weight_cat_class_2': 0.41924072702872545}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:27,975] Trial 1371 finished with value: 0.9489910830372826 and parameters: {'weight_lgbm_class_0': 0.09946672218332267, 'weight_lgbm_class_1': 0.7176750860991125, 'weight_lgbm_class_2': 0.8187767007271406, 'weight_xgb_class_0': 0.1132622400781342, 'weight_xgb_class_1': 0.4668866943983614, 'weight_xgb_class_2': 0.4334361806156151, 'weight_cat_class_0': 0.016251490531383354, 'weight_cat_class_1': 0.8527821925907467, 'weight_cat_class_2': 0.4807221337222564}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,026] Trial 1372 finished with value: 0.948268771441001 and parameters: {'weight_lgbm_class_0': 0.10012364894340481, 'weight_lgbm_class_1': 0.818651722681421, 'weight_lgbm_class_2': 0.8653689620475974, 'weight_xgb_class_0': 0.1156971737374398, 'weight_xgb_class_1': 0.46503990852149296, 'weight_xgb_class_2': 0.43995626239396185, 'weight_cat_class_0': 0.06397753664979343, 'weight_cat_class_1': 0.8415963441390918, 'weight_cat_class_2': 0.41057266253668734}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,050] Trial 1373 finished with value: 0.9497345865203588 and parameters: {'weight_lgbm_class_0': 0.04833336864901268, 'weight_lgbm_class_1': 0.8211742112286712, 'weight_lgbm_class_2': 0.8563210544628328, 'weight_xgb_class_0': 0.0172141923239839, 'weight_xgb_class_1': 0.46497728537175176, 'weight_xgb_class_2': 0.4385276554761528, 'weight_cat_class_0': 0.06122642632373002, 'weight_cat_class_1': 0.7484629703663958, 'weight_cat_class_2': 0.4043396772385594}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,087] Trial 1374 finished with value: 0.9495863347549 and parameters: {'weight_lgbm_class_0': 0.09458296143130615, 'weight_lgbm_class_1': 0.8250980850051183, 'weight_lgbm_class_2': 0.8670688753331107, 'weight_xgb_class_0': 0.01801210321092972, 'weight_xgb_class_1': 0.46185160623862404, 'weight_xgb_class_2': 0.4347949111557842, 'weight_cat_class_0': 0.06107708119498483, 'weight_cat_class_1': 0.7576690776853371, 'weight_cat_class_2': 0.42557706059616707}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  69%|█████████████████████████████████████████████████████████████████████████████████████████▋                                        | 1380/2000 [00:52<00:29, 21.16it/s]

[I 2026-07-03 10:23:28,193] Trial 1375 finished with value: 0.9490547479081055 and parameters: {'weight_lgbm_class_0': 0.04764222582708902, 'weight_lgbm_class_1': 0.8214915375703041, 'weight_lgbm_class_2': 0.8238384904563073, 'weight_xgb_class_0': 0.11583225159231048, 'weight_xgb_class_1': 0.45448477540527876, 'weight_xgb_class_2': 0.4531972102800822, 'weight_cat_class_0': 0.061113274091903494, 'weight_cat_class_1': 0.8414469227733805, 'weight_cat_class_2': 0.4246963604603512}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,219] Trial 1377 finished with value: 0.9488123994585683 and parameters: {'weight_lgbm_class_0': 0.04650558264629043, 'weight_lgbm_class_1': 0.7147745547117572, 'weight_lgbm_class_2': 0.8631165160307364, 'weight_xgb_class_0': 0.12343778989649218, 'weight_xgb_class_1': 0.46565582578265513, 'weight_xgb_class_2': 0.46138316492583964, 'weight_cat_class_0': 0.06708000222292489, 'weight_cat_class_1': 0.8425899892046398, 'weight_cat_class_2': 0.4009621285137754}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,227] Trial 1376 finished with value: 0.9489672182432228 and parameters: {'weight_lgbm_class_0': 0.04645380557199183, 'weight_lgbm_class_1': 0.8184799266079806, 'weight_lgbm_class_2': 0.8592951134661332, 'weight_xgb_class_0': 0.1226327909495893, 'weight_xgb_class_1': 0.46326215521066705, 'weight_xgb_class_2': 0.45254513701817833, 'weight_cat_class_0': 0.06540402665083865, 'weight_cat_class_1': 0.8416809815207454, 'weight_cat_class_2': 0.4373806642649869}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,307] Trial 1379 finished with value: 0.9154492010074979 and parameters: {'weight_lgbm_class_0': 0.9627546382867428, 'weight_lgbm_class_1': 0.8208547434316225, 'weight_lgbm_class_2': 0.864474604379229, 'weight_xgb_class_0': 0.09963521136327738, 'weight_xgb_class_1': 0.5762930810316713, 'weight_xgb_class_2': 0.4220679441988919, 'weight_cat_class_0': 0.016615221025655224, 'weight_cat_class_1': 0.8380273087145386, 'weight_cat_class_2': 0.5284156043869132}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,314] Trial 1378 finished with value: 0.9484979828526936 and parameters: {'weight_lgbm_class_0': 0.1463625935191636, 'weight_lgbm_class_1': 0.8184830939384117, 'weight_lgbm_class_2': 0.8235490267687037, 'weight_xgb_class_0': 0.10837065663947465, 'weight_xgb_class_1': 0.5779853841712552, 'weight_xgb_class_2': 0.42400198005259637, 'weight_cat_class_0': 0.015797818873192586, 'weight_cat_class_1': 0.8481162629549618, 'weight_cat_class_2': 0.4800852369330465}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,340] Trial 1380 finished with value: 0.9491372162962897 and parameters: {'weight_lgbm_class_0': 0.0927052490427374, 'weight_lgbm_class_1': 0.8258281016804025, 'weight_lgbm_class_2': 0.8215087834346994, 'weight_xgb_class_0': 0.10940984995105504, 'weight_xgb_class_1': 0.566405079443272, 'weight_xgb_class_2': 0.42689305474486294, 'weight_cat_class_0': 0.017963213461739475, 'weight_cat_class_1': 0.8407168065248354, 'weight_cat_class_2': 0.49754184859780515}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  69%|██████████████████████████████████████████████████████████████████████████████████████████                                        | 1386/2000 [00:52<00:33, 18.51it/s]

[I 2026-07-03 10:23:28,465] Trial 1381 finished with value: 0.948071871272088 and parameters: {'weight_lgbm_class_0': 0.14895079174247042, 'weight_lgbm_class_1': 0.8404888661364298, 'weight_lgbm_class_2': 0.7044511493422715, 'weight_xgb_class_0': 0.11085893309011391, 'weight_xgb_class_1': 0.5816215584945217, 'weight_xgb_class_2': 0.427680304293229, 'weight_cat_class_0': 0.01678204272616269, 'weight_cat_class_1': 0.8436722833645834, 'weight_cat_class_2': 0.445355498162058}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,560] Trial 1383 finished with value: 0.9493793215878882 and parameters: {'weight_lgbm_class_0': 0.15069299491691246, 'weight_lgbm_class_1': 0.8365817765173943, 'weight_lgbm_class_2': 0.5946968499642943, 'weight_xgb_class_0': 0.035683974335021365, 'weight_xgb_class_1': 0.5780030754619154, 'weight_xgb_class_2': 0.4517082053369486, 'weight_cat_class_0': 0.0005363951986161394, 'weight_cat_class_1': 0.8427133707520891, 'weight_cat_class_2': 0.5356502200515635}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,562] Trial 1382 finished with value: 0.9485740708851699 and parameters: {'weight_lgbm_class_0': 0.15543543358450007, 'weight_lgbm_class_1': 0.8259697149798143, 'weight_lgbm_class_2': 0.8634554297945731, 'weight_xgb_class_0': 0.10624659682796928, 'weight_xgb_class_1': 0.5755832054234881, 'weight_xgb_class_2': 0.4568513692788026, 'weight_cat_class_0': 0.015775699638287156, 'weight_cat_class_1': 0.842045389776722, 'weight_cat_class_2': 0.49228656347213073}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,590] Trial 1384 finished with value: 0.9488271965305071 and parameters: {'weight_lgbm_class_0': 0.14740540575248615, 'weight_lgbm_class_1': 0.837890900462942, 'weight_lgbm_class_2': 0.8205032681937348, 'weight_xgb_class_0': 0.10276904368840216, 'weight_xgb_class_1': 0.5770622786957187, 'weight_xgb_class_2': 0.45018614503496324, 'weight_cat_class_0': 0.0010439009813893972, 'weight_cat_class_1': 0.8438267486496305, 'weight_cat_class_2': 0.49711147368338193}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,635] Trial 1386 finished with value: 0.9272417173090091 and parameters: {'weight_lgbm_class_0': 0.14754377028530238, 'weight_lgbm_class_1': 0.8354214592045242, 'weight_lgbm_class_2': 0.7090873787592561, 'weight_xgb_class_0': 0.10200772590441798, 'weight_xgb_class_1': 0.5397771897997866, 'weight_xgb_class_2': 0.4576886978431964, 'weight_cat_class_0': 0.47418266045286905, 'weight_cat_class_1': 0.3769217649337876, 'weight_cat_class_2': 0.4835783269619017}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,639] Trial 1385 finished with value: 0.9489193008145089 and parameters: {'weight_lgbm_class_0': 0.1407943381080659, 'weight_lgbm_class_1': 0.8194561176313937, 'weight_lgbm_class_2': 0.8180581648145006, 'weight_xgb_class_0': 0.09892539728209356, 'weight_xgb_class_1': 0.5778485387838828, 'weight_xgb_class_2': 0.456811644237889, 'weight_cat_class_0': 0.00032979312305302826, 'weight_cat_class_1': 0.7444486645105526, 'weight_cat_class_2': 0.5019246393355948}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  70%|██████████████████████████████████████████████████████████████████████████████████████████▍                                       | 1392/2000 [00:53<00:31, 19.57it/s]

[I 2026-07-03 10:23:28,798] Trial 1388 finished with value: 0.9493108485570761 and parameters: {'weight_lgbm_class_0': 0.14933819306285712, 'weight_lgbm_class_1': 0.8499810270756272, 'weight_lgbm_class_2': 0.6071832947193625, 'weight_xgb_class_0': 0.0358796875505781, 'weight_xgb_class_1': 0.5585701026230964, 'weight_xgb_class_2': 0.42370334135002263, 'weight_cat_class_0': 0.0010587451710912694, 'weight_cat_class_1': 0.7399343933054774, 'weight_cat_class_2': 0.49853870016042395}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,839] Trial 1389 finished with value: 0.9492905793330403 and parameters: {'weight_lgbm_class_0': 0.13989892649204622, 'weight_lgbm_class_1': 0.8454949233743004, 'weight_lgbm_class_2': 0.5943370347490107, 'weight_xgb_class_0': 0.03506207424346122, 'weight_xgb_class_1': 0.6267859570375514, 'weight_xgb_class_2': 0.4596178836463119, 'weight_cat_class_0': 0.015059702345682133, 'weight_cat_class_1': 0.7403520586439981, 'weight_cat_class_2': 0.49373618104457623}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,852] Trial 1387 finished with value: 0.947545907831897 and parameters: {'weight_lgbm_class_0': 0.018410706123674972, 'weight_lgbm_class_1': 0.8401290212269483, 'weight_lgbm_class_2': 0.8192501201509687, 'weight_xgb_class_0': 0.0355785140818231, 'weight_xgb_class_1': 0.572247483480396, 'weight_xgb_class_2': 0.41228037045032434, 'weight_cat_class_0': 0.0007390057700241249, 'weight_cat_class_1': 0.7499811277189824, 'weight_cat_class_2': 0.4934201429238629}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,892] Trial 1390 finished with value: 0.9493097129625713 and parameters: {'weight_lgbm_class_0': 0.15091635510550325, 'weight_lgbm_class_1': 0.8475191571114875, 'weight_lgbm_class_2': 0.5982179201165131, 'weight_xgb_class_0': 0.034026866088015716, 'weight_xgb_class_1': 0.5678872919696476, 'weight_xgb_class_2': 0.46423302313095705, 'weight_cat_class_0': 0.0012983973549677227, 'weight_cat_class_1': 0.7462850426347133, 'weight_cat_class_2': 0.4975560949797468}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,939] Trial 1392 finished with value: 0.9494241436535623 and parameters: {'weight_lgbm_class_0': 0.1506372891156791, 'weight_lgbm_class_1': 0.796967622422823, 'weight_lgbm_class_2': 0.7036049287718912, 'weight_xgb_class_0': 0.03341614448524891, 'weight_xgb_class_1': 0.5745528967898659, 'weight_xgb_class_2': 0.4739015079737139, 'weight_cat_class_0': 0.0019386393420858725, 'weight_cat_class_1': 0.7475471736539817, 'weight_cat_class_2': 0.5280631036494495}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:28,947] Trial 1391 finished with value: 0.89691666441473 and parameters: {'weight_lgbm_class_0': 0.7701086578402567, 'weight_lgbm_class_1': 0.7914883557883401, 'weight_lgbm_class_2': 0.5875175406167273, 'weight_xgb_class_0': 0.5442537779840964, 'weight_xgb_class_1': 0.569621112885521, 'weight_xgb_class_2': 0.46230216776058014, 'weight_cat_class_0': 0.013149823494092282, 'weight_cat_class_1': 0.7523401270445499, 'weight_cat_class_2': 0.48865007582865877}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:29,078] Trial 1393 finished with value: 0.9483186928149253 and parameters: {'weight_lgbm_class_0': 0.02157333030239493, 'weight_lgbm_class_1': 0.8464235105107811, 'weight_lgbm_class_2': 0.5957458855754064, 'weight_xgb_class_0': 0.03340057477073274, 'weight_xgb_class_1': 0.614762212721013, 'weight_xgb_class_2': 0.4649880719048724, 'weight_cat_class_0': 0.015920306939386637, 'weight_cat_class_1': 0.9989750003090903, 'weight_cat_class_2': 0.4936084457386145}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:29,181] Trial 1395 finished with value: 0.949395841338348 and parameters: {'weight_lgbm_class_0': 0.015460882402896683, 'weight_lgbm_class_1': 0.8527043447820913, 'weight_lgbm_class_2': 0.1611378395075953, 'weight_xgb_class_0': 0.07582296720249782, 'weight_xgb_class_1': 0.9122569768598732, 'weight_xgb_class_2': 0.4700140945502837, 'weight_cat_class_0': 0.01765401016393567, 'weight_cat_class_1': 0.7474706837221976, 'weight_cat_class_2': 0.49538463194399085}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:29,185] Trial 1394 finished with value: 0.9495957421623725 and parameters: {'weight_lgbm_class_0': 0.021500138410081804, 'weight_lgbm_class_1': 0.8522516793607158, 'weight_lgbm_class_2': 0.27472627374576153, 'weight_xgb_class_0': 0.07791255466232108, 'weight_xgb_class_1': 0.6154879822090389, 'weight_xgb_class_2': 0.4731082561389075, 'weight_cat_class_0': 0.0006106077284265374, 'weight_cat_class_1': 0.7470827900166824, 'weight_cat_class_2': 0.4933532154696031}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:29,240] Trial 1397 finished with value: 0.9494000461052985 and parameters: {'weight_lgbm_class_0': 0.014472681781173787, 'weight_lgbm_class_1': 0.7966576239208342, 'weight_lgbm_class_2': 0.7472960029737737, 'weight_xgb_class_0': 0.07220512318739022, 'weight_xgb_class_1': 0.6254817304402355, 'weight_xgb_class_2': 0.47471258661646165, 'weight_cat_class_0': 0.016658045551442967, 'weight_cat_class_1': 0.7767926459878328, 'weight_cat_class_2': 0.5227623163198445}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:29,240] Trial 1396 finished with value: 0.9253227606074006 and parameters: {'weight_lgbm_class_0': 0.8171698636539727, 'weight_lgbm_class_1': 0.8585838235967495, 'weight_lgbm_class_2': 0.7633176386648599, 'weight_xgb_class_0': 0.034594890812841186, 'weight_xgb_class_1': 0.6091379155207395, 'weight_xgb_class_2': 0.4827832825245173, 'weight_cat_class_0': 0.016698176037443627, 'weight_cat_class_1': 0.7743538807828251, 'weight_cat_class_2': 0.5283563196850115}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  70%|███████████████████████████████████████████████████████████████████████████████████████████▏                                      | 1402/2000 [00:53<00:30, 19.66it/s]

[I 2026-07-03 10:23:29,283] Trial 1398 finished with value: 0.9367495636069947 and parameters: {'weight_lgbm_class_0': 0.4378603961933305, 'weight_lgbm_class_1': 0.8387714119258866, 'weight_lgbm_class_2': 0.9980003735055837, 'weight_xgb_class_0': 0.07768383525830612, 'weight_xgb_class_1': 0.5628176698121743, 'weight_xgb_class_2': 0.46666621734400726, 'weight_cat_class_0': 0.0007773401451133637, 'weight_cat_class_1': 0.013627692134517144, 'weight_cat_class_2': 0.4598115662588375}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:29,386] Trial 1399 finished with value: 0.9485173827888141 and parameters: {'weight_lgbm_class_0': 0.019254823763816976, 'weight_lgbm_class_1': 0.7938823558855075, 'weight_lgbm_class_2': 0.7453436063762671, 'weight_xgb_class_0': 0.03464586628663594, 'weight_xgb_class_1': 0.5544406172813985, 'weight_xgb_class_2': 0.4723155808752988, 'weight_cat_class_0': 0.01632512186632972, 'weight_cat_class_1': 0.7720813764880998, 'weight_cat_class_2': 0.4543939999193193}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:29,440] Trial 1400 finished with value: 0.9495648125016034 and parameters: {'weight_lgbm_class_0': 0.08262064144675321, 'weight_lgbm_class_1': 0.7942667558439638, 'weight_lgbm_class_2': 0.843666772251314, 'weight_xgb_class_0': 0.07362989491700567, 'weight_xgb_class_1': 0.5546205935527138, 'weight_xgb_class_2': 0.47886732402514276, 'weight_cat_class_0': 0.02102289170444246, 'weight_cat_class_1': 0.7731985836044551, 'weight_cat_class_2': 0.5189286856312274}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:29,467] Trial 1402 finished with value: 0.9492922483625712 and parameters: {'weight_lgbm_class_0': 0.08230320492154519, 'weight_lgbm_class_1': 0.8561258410445917, 'weight_lgbm_class_2': 0.7532810717514649, 'weight_xgb_class_0': 0.07083195029352413, 'weight_xgb_class_1': 0.5486051163800773, 'weight_xgb_class_2': 0.4772250928811722, 'weight_cat_class_0': 0.03511463339732098, 'weight_cat_class_1': 0.2708608657948096, 'weight_cat_class_2': 0.5225989352057248}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:29,507] Trial 1401 finished with value: 0.9247011031262492 and parameters: {'weight_lgbm_class_0': 0.08248919374902028, 'weight_lgbm_class_1': 0.7870723957264125, 'weight_lgbm_class_2': 0.9977868299947515, 'weight_xgb_class_0': 0.8379840642994434, 'weight_xgb_class_1': 0.6483339750134975, 'weight_xgb_class_2': 0.4758613218332742, 'weight_cat_class_0': 0.03332949221181114, 'weight_cat_class_1': 0.9994474233305488, 'weight_cat_class_2': 0.5262825987888766}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  70%|███████████████████████████████████████████████████████████████████████████████████████████▍                                      | 1406/2000 [00:53<00:27, 21.27it/s]

[I 2026-07-03 10:23:29,528] Trial 1404 finished with value: 0.9492965699108592 and parameters: {'weight_lgbm_class_0': 0.08454647200930775, 'weight_lgbm_class_1': 0.8095645028526403, 'weight_lgbm_class_2': 0.7840585483011682, 'weight_xgb_class_0': 0.07353599410443899, 'weight_xgb_class_1': 0.61312093775242, 'weight_xgb_class_2': 0.3839141230798121, 'weight_cat_class_0': 0.037626885247742735, 'weight_cat_class_1': 0.7759526896645484, 'weight_cat_class_2': 0.45378306168235166}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:29,538] Trial 1403 finished with value: 0.9404214499325988 and parameters: {'weight_lgbm_class_0': 0.08154607797168464, 'weight_lgbm_class_1': 0.7948862963973069, 'weight_lgbm_class_2': 0.7803991728248535, 'weight_xgb_class_0': 0.4052582926450403, 'weight_xgb_class_1': 0.5466728561089729, 'weight_xgb_class_2': 0.4773239925998524, 'weight_cat_class_0': 0.03583264693707355, 'weight_cat_class_1': 0.7788123267455506, 'weight_cat_class_2': 0.5294106424817594}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:29,644] Trial 1405 finished with value: 0.9483936285118815 and parameters: {'weight_lgbm_class_0': 0.08380684479217328, 'weight_lgbm_class_1': 0.797954474584916, 'weight_lgbm_class_2': 0.7709398178107937, 'weight_xgb_class_0': 0.07528731229237769, 'weight_xgb_class_1': 0.5441300622587965, 'weight_xgb_class_2': 0.38496290453179777, 'weight_cat_class_0': 0.03980600890958451, 'weight_cat_class_1': 0.015624927735388039, 'weight_cat_class_2': 0.4543506884916578}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  71%|███████████████████████████████████████████████████████████████████████████████████████████▊                                      | 1412/2000 [00:54<00:28, 20.71it/s]

[I 2026-07-03 10:23:29,783] Trial 1406 finished with value: 0.9485735252278559 and parameters: {'weight_lgbm_class_0': 0.08159504116028873, 'weight_lgbm_class_1': 0.16402451120483297, 'weight_lgbm_class_2': 0.7431218482253292, 'weight_xgb_class_0': 0.07382461181459352, 'weight_xgb_class_1': 0.435967113500014, 'weight_xgb_class_2': 0.40847636148739314, 'weight_cat_class_0': 0.04108615902589191, 'weight_cat_class_1': 0.7747669486810282, 'weight_cat_class_2': 0.4563121962485609}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:29,785] Trial 1407 finished with value: 0.9495003493596998 and parameters: {'weight_lgbm_class_0': 0.07572184983946707, 'weight_lgbm_class_1': 0.7911361626323826, 'weight_lgbm_class_2': 0.8392295455652303, 'weight_xgb_class_0': 0.07552778539003872, 'weight_xgb_class_1': 0.9787117227562886, 'weight_xgb_class_2': 0.4110870709741328, 'weight_cat_class_0': 0.03929228551285377, 'weight_cat_class_1': 0.7779082002294289, 'weight_cat_class_2': 0.45810134891825294}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:29,861] Trial 1408 finished with value: 0.9476230471859441 and parameters: {'weight_lgbm_class_0': 0.07773821435971165, 'weight_lgbm_class_1': 0.18791262648668072, 'weight_lgbm_class_2': 0.7798985613429784, 'weight_xgb_class_0': 0.018748506130610635, 'weight_xgb_class_1': 0.5520720425769275, 'weight_xgb_class_2': 0.40639221347318144, 'weight_cat_class_0': 0.042952541477925425, 'weight_cat_class_1': 0.05892755368155672, 'weight_cat_class_2': 0.4599053154517975}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:29,919] Trial 1410 finished with value: 0.9497230137676822 and parameters: {'weight_lgbm_class_0': 0.08040872040565727, 'weight_lgbm_class_1': 0.8061940373863877, 'weight_lgbm_class_2': 0.8488154042215323, 'weight_xgb_class_0': 0.022565302192565206, 'weight_xgb_class_1': 0.43878518403816946, 'weight_xgb_class_2': 0.41484060498904896, 'weight_cat_class_0': 0.04423445963421448, 'weight_cat_class_1': 0.7821804286920053, 'weight_cat_class_2': 0.43895988622315596}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:29,922] Trial 1409 finished with value: 0.9487843827839558 and parameters: {'weight_lgbm_class_0': 0.19038906069366057, 'weight_lgbm_class_1': 0.709359924407135, 'weight_lgbm_class_2': 0.8344199260833063, 'weight_xgb_class_0': 0.017273788700219755, 'weight_xgb_class_1': 0.6580657517204392, 'weight_xgb_class_2': 0.4081274878390644, 'weight_cat_class_0': 0.0419296642126413, 'weight_cat_class_1': 0.7846896739088545, 'weight_cat_class_2': 0.4605953263733946}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:29,962] Trial 1411 finished with value: 0.9494778174406742 and parameters: {'weight_lgbm_class_0': 0.1148176006781193, 'weight_lgbm_class_1': 0.799661406055185, 'weight_lgbm_class_2': 0.7747016028809716, 'weight_xgb_class_0': 0.02011381127935822, 'weight_xgb_class_1': 0.5327702181702919, 'weight_xgb_class_2': 0.3903413864097985, 'weight_cat_class_0': 0.04099969325982314, 'weight_cat_class_1': 0.7843866092467924, 'weight_cat_class_2': 0.4504636369372157}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  71%|████████████████████████████████████████████████████████████████████████████████████████████                                      | 1416/2000 [00:54<00:30, 18.98it/s]

[I 2026-07-03 10:23:30,022] Trial 1413 finished with value: 0.949461710734513 and parameters: {'weight_lgbm_class_0': 0.11407185357073307, 'weight_lgbm_class_1': 0.8027499621440479, 'weight_lgbm_class_2': 0.7814691562776394, 'weight_xgb_class_0': 0.017964744593366458, 'weight_xgb_class_1': 0.5322000029435983, 'weight_xgb_class_2': 0.3919524162960364, 'weight_cat_class_0': 0.046017590492083815, 'weight_cat_class_1': 0.7851229027236304, 'weight_cat_class_2': 0.45198206650762096}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:30,028] Trial 1412 finished with value: 0.9496209411190836 and parameters: {'weight_lgbm_class_0': 0.04742967680225188, 'weight_lgbm_class_1': 0.8015245150193735, 'weight_lgbm_class_2': 0.7749760356595212, 'weight_xgb_class_0': 0.01707164577852896, 'weight_xgb_class_1': 0.4425062658029659, 'weight_xgb_class_2': 0.37715234959028243, 'weight_cat_class_0': 0.043896118899116765, 'weight_cat_class_1': 0.8222395774157252, 'weight_cat_class_2': 0.4512820998594268}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:30,148] Trial 1415 finished with value: 0.9480457195219739 and parameters: {'weight_lgbm_class_0': 0.1885308092457662, 'weight_lgbm_class_1': 0.70967633218316, 'weight_lgbm_class_2': 0.6389891346340085, 'weight_xgb_class_0': 0.02149911193267915, 'weight_xgb_class_1': 0.43986139511495326, 'weight_xgb_class_2': 0.410600473376919, 'weight_cat_class_0': 0.05072328557263985, 'weight_cat_class_1': 0.8769914900905369, 'weight_cat_class_2': 0.4444773768605166}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:30,166] Trial 1414 finished with value: 0.9497399234350011 and parameters: {'weight_lgbm_class_0': 0.047536776070537246, 'weight_lgbm_class_1': 0.7089104168003654, 'weight_lgbm_class_2': 0.6435703524778158, 'weight_xgb_class_0': 0.019672121251163154, 'weight_xgb_class_1': 0.4360881264354919, 'weight_xgb_class_2': 0.40990262380018266, 'weight_cat_class_0': 0.049215891944069654, 'weight_cat_class_1': 0.8217130524929113, 'weight_cat_class_2': 0.5535411219212014}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:30,175] Trial 1416 finished with value: 0.9496775292238562 and parameters: {'weight_lgbm_class_0': 0.048552986251307745, 'weight_lgbm_class_1': 0.7149849648435881, 'weight_lgbm_class_2': 0.834007323397151, 'weight_xgb_class_0': 0.01806687023942856, 'weight_xgb_class_1': 0.5333308918391435, 'weight_xgb_class_2': 0.4095331690129711, 'weight_cat_class_0': 0.04903360206802203, 'weight_cat_class_1': 0.8215147758468594, 'weight_cat_class_2': 0.44816731971562995}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:30,264] Trial 1417 finished with value: 0.9494891624684692 and parameters: {'weight_lgbm_class_0': 0.11792921192324955, 'weight_lgbm_class_1': 0.7142909114365673, 'weight_lgbm_class_2': 0.834493410653865, 'weight_xgb_class_0': 0.01882841334651587, 'weight_xgb_class_1': 0.4369435191106716, 'weight_xgb_class_2': 0.4434488313794534, 'weight_cat_class_0': 0.04872758900506155, 'weight_cat_class_1': 0.8161809309605556, 'weight_cat_class_2': 0.4438794474356932}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:30,344] Trial 1418 finished with value: 0.9492366059142845 and parameters: {'weight_lgbm_class_0': 0.11911870215917429, 'weight_lgbm_class_1': 0.7122559282793082, 'weight_lgbm_class_2': 0.648315415352791, 'weight_xgb_class_0': 0.017623937200674383, 'weight_xgb_class_1': 0.43635887412634, 'weight_xgb_class_2': 0.4374761284532754, 'weight_cat_class_0': 0.05206675213671287, 'weight_cat_class_1': 0.8233747377345391, 'weight_cat_class_2': 0.4443151749872221}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:30,401] Trial 1420 finished with value: 0.949441147345406 and parameters: {'weight_lgbm_class_0': 0.11443385375130449, 'weight_lgbm_class_1': 0.717343402897443, 'weight_lgbm_class_2': 0.8764744946681587, 'weight_xgb_class_0': 0.017454801623057133, 'weight_xgb_class_1': 0.43080728562801723, 'weight_xgb_class_2': 0.44322066503760216, 'weight_cat_class_0': 0.05805269787347718, 'weight_cat_class_1': 0.8215862193249165, 'weight_cat_class_2': 0.5438698100388372}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:30,430] Trial 1419 finished with value: 0.9446859254517594 and parameters: {'weight_lgbm_class_0': 0.18974540878721985, 'weight_lgbm_class_1': 0.48046906274456397, 'weight_lgbm_class_2': 0.6368623877349178, 'weight_xgb_class_0': 0.0175693668723339, 'weight_xgb_class_1': 0.5309611878350591, 'weight_xgb_class_2': 0.4395457965890159, 'weight_cat_class_0': 0.04865592264738047, 'weight_cat_class_1': 0.03775868239315755, 'weight_cat_class_2': 0.5484895633270991}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:30,445] Trial 1421 finished with value: 0.9489405454559794 and parameters: {'weight_lgbm_class_0': 0.11376726603447782, 'weight_lgbm_class_1': 0.7163277438161733, 'weight_lgbm_class_2': 0.6456838025147514, 'weight_xgb_class_0': 0.01795998920829187, 'weight_xgb_class_1': 0.5303866708908489, 'weight_xgb_class_2': 0.4462723932687104, 'weight_cat_class_0': 0.05583134606562862, 'weight_cat_class_1': 0.8185656649709366, 'weight_cat_class_2': 0.24647987963967508}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  71%|████████████████████████████████████████████████████████████████████████████████████████████▋                                     | 1425/2000 [00:54<00:27, 21.24it/s]

[I 2026-07-03 10:23:30,498] Trial 1422 finished with value: 0.9496988081213346 and parameters: {'weight_lgbm_class_0': 0.048671589372893675, 'weight_lgbm_class_1': 0.7339748388306441, 'weight_lgbm_class_2': 0.6343396335356087, 'weight_xgb_class_0': 0.020443177481174336, 'weight_xgb_class_1': 0.276182585052104, 'weight_xgb_class_2': 0.44565559196065324, 'weight_cat_class_0': 0.0531472590583378, 'weight_cat_class_1': 0.8246589096905572, 'weight_cat_class_2': 0.43680730290235265}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:30,541] Trial 1423 finished with value: 0.9495542815737051 and parameters: {'weight_lgbm_class_0': 0.04910885712165492, 'weight_lgbm_class_1': 0.47744393748939534, 'weight_lgbm_class_2': 0.644390388001835, 'weight_xgb_class_0': 0.019456852287894344, 'weight_xgb_class_1': 0.2817118145273555, 'weight_xgb_class_2': 0.43385915950338294, 'weight_cat_class_0': 0.05122805969165421, 'weight_cat_class_1': 0.8169145210577271, 'weight_cat_class_2': 0.553063718124798}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:30,601] Trial 1424 finished with value: 0.9367857352545172 and parameters: {'weight_lgbm_class_0': 0.04332808793871136, 'weight_lgbm_class_1': 0.7348983202562724, 'weight_lgbm_class_2': 0.8765657922932827, 'weight_xgb_class_0': 0.045626612064035704, 'weight_xgb_class_1': 0.5289549191573826, 'weight_xgb_class_2': 0.442786221829347, 'weight_cat_class_0': 0.5574747003514289, 'weight_cat_class_1': 0.8195693495722143, 'weight_cat_class_2': 0.5501403380788278}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:30,686] Trial 1425 finished with value: 0.9338623988108288 and parameters: {'weight_lgbm_class_0': 0.04914606287653008, 'weight_lgbm_class_1': 0.7212156478704757, 'weight_lgbm_class_2': 0.6451092419162802, 'weight_xgb_class_0': 0.04623250632822661, 'weight_xgb_class_1': 0.5236475328202085, 'weight_xgb_class_2': 0.43972000240283066, 'weight_cat_class_0': 0.5625322523016079, 'weight_cat_class_1': 0.8670174188924121, 'weight_cat_class_2': 0.5517946774292014}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  72%|█████████████████████████████████████████████████████████████████████████████████████████████                                     | 1431/2000 [00:55<00:29, 19.04it/s]

[I 2026-07-03 10:23:30,785] Trial 1427 finished with value: 0.9495683616725211 and parameters: {'weight_lgbm_class_0': 0.050503389047137096, 'weight_lgbm_class_1': 0.732164188924956, 'weight_lgbm_class_2': 0.87699924128324, 'weight_xgb_class_0': 0.0467335869205073, 'weight_xgb_class_1': 0.2668916180492946, 'weight_xgb_class_2': 0.4408141849897258, 'weight_cat_class_0': 0.018904948892257627, 'weight_cat_class_1': 0.862065124817016, 'weight_cat_class_2': 0.4816527519015824}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:30,808] Trial 1426 finished with value: 0.9496086731896246 and parameters: {'weight_lgbm_class_0': 0.11399407826095836, 'weight_lgbm_class_1': 0.7782327670328846, 'weight_lgbm_class_2': 0.8809277133829433, 'weight_xgb_class_0': 0.04527709954827716, 'weight_xgb_class_1': 0.5226711303589823, 'weight_xgb_class_2': 0.4479264444926911, 'weight_cat_class_0': 0.02009078884190373, 'weight_cat_class_1': 0.8739954110875461, 'weight_cat_class_2': 0.5538490870392292}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:30,837] Trial 1428 finished with value: 0.9274798664601592 and parameters: {'weight_lgbm_class_0': 0.1121457928499741, 'weight_lgbm_class_1': 0.7419407877596252, 'weight_lgbm_class_2': 0.8796898864441542, 'weight_xgb_class_0': 0.04527327857205012, 'weight_xgb_class_1': 0.530856572226942, 'weight_xgb_class_2': 0.4424864205816583, 'weight_cat_class_0': 0.5755060330479786, 'weight_cat_class_1': 0.7241768055925388, 'weight_cat_class_2': 0.24806833429086195}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:30,881] Trial 1429 finished with value: 0.9495164410521699 and parameters: {'weight_lgbm_class_0': 0.11399301711340577, 'weight_lgbm_class_1': 0.7383917237847646, 'weight_lgbm_class_2': 0.8795479907588306, 'weight_xgb_class_0': 0.0005257978684278519, 'weight_xgb_class_1': 0.5333074499120369, 'weight_xgb_class_2': 0.5279303238316477, 'weight_cat_class_0': 0.0006461567920959616, 'weight_cat_class_1': 0.7619583396604843, 'weight_cat_class_2': 0.5426793819552072}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:30,964] Trial 1430 finished with value: 0.9491480681468341 and parameters: {'weight_lgbm_class_0': 0.05323277975187392, 'weight_lgbm_class_1': 0.12217262581634075, 'weight_lgbm_class_2': 0.8773423903080201, 'weight_xgb_class_0': 0.044978915710860365, 'weight_xgb_class_1': 0.27362424697218085, 'weight_xgb_class_2': 0.4460620215726878, 'weight_cat_class_0': 0.02028581841356343, 'weight_cat_class_1': 0.8759177909629149, 'weight_cat_class_2': 0.5454829788680474}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:30,990] Trial 1431 finished with value: 0.9496837338077307 and parameters: {'weight_lgbm_class_0': 0.047565239377352936, 'weight_lgbm_class_1': 0.7463897315029034, 'weight_lgbm_class_2': 0.8084551237955782, 'weight_xgb_class_0': 0.04351305994008522, 'weight_xgb_class_1': 0.2714098680506356, 'weight_xgb_class_2': 0.5223032880190275, 'weight_cat_class_0': 0.019453230641499474, 'weight_cat_class_1': 0.8652963549122654, 'weight_cat_class_2': 0.24582543969373377}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:31,076] Trial 1433 finished with value: 0.949204752203265 and parameters: {'weight_lgbm_class_0': 0.05207386810336324, 'weight_lgbm_class_1': 0.750909419182558, 'weight_lgbm_class_2': 0.8111335367257372, 'weight_xgb_class_0': 0.043674854936850874, 'weight_xgb_class_1': 0.5110822097709465, 'weight_xgb_class_2': 0.5206472580037875, 'weight_cat_class_0': 0.00031372092704240164, 'weight_cat_class_1': 0.7227043716606796, 'weight_cat_class_2': 0.5516337110020983}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:31,090] Trial 1432 finished with value: 0.9495136076415607 and parameters: {'weight_lgbm_class_0': 0.05078754072551454, 'weight_lgbm_class_1': 0.7436397082358212, 'weight_lgbm_class_2': 0.8129913730265355, 'weight_xgb_class_0': 0.045134494883790136, 'weight_xgb_class_1': 0.2703276937716632, 'weight_xgb_class_2': 0.4865868422313646, 'weight_cat_class_0': 0.01684634862290554, 'weight_cat_class_1': 0.8632310327213133, 'weight_cat_class_2': 0.559459274219995}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:31,094] Trial 1434 finished with value: 0.9495654118474084 and parameters: {'weight_lgbm_class_0': 0.05141500050211357, 'weight_lgbm_class_1': 0.7378356528715843, 'weight_lgbm_class_2': 0.8785434257192998, 'weight_xgb_class_0': 0.04779882146855355, 'weight_xgb_class_1': 0.2808193465296179, 'weight_xgb_class_2': 0.48925728479084796, 'weight_cat_class_0': 0.01885536865751508, 'weight_cat_class_1': 0.8587917134383868, 'weight_cat_class_2': 0.4750982938034301}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:31,181] Trial 1436 finished with value: 0.9408947507481278 and parameters: {'weight_lgbm_class_0': 0.0009064921762840621, 'weight_lgbm_class_1': 0.7401712116213897, 'weight_lgbm_class_2': 0.19893073837131459, 'weight_xgb_class_0': 7.178308001515657e-05, 'weight_xgb_class_1': 0.27220117649697334, 'weight_xgb_class_2': 0.528199754746228, 'weight_cat_class_0': 0.02076944705406691, 'weight_cat_class_1': 0.8636001578325972, 'weight_cat_class_2': 0.4768667730308276}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:31,183] Trial 1435 finished with value: 0.9496199651258944 and parameters: {'weight_lgbm_class_0': 0.0574119100698927, 'weight_lgbm_class_1': 0.7338051516168048, 'weight_lgbm_class_2': 0.8779467889864647, 'weight_xgb_class_0': 0.047584585158960066, 'weight_xgb_class_1': 0.5086658414159506, 'weight_xgb_class_2': 0.529853597375091, 'weight_cat_class_0': 0.00013557969340180498, 'weight_cat_class_1': 0.43238963204462433, 'weight_cat_class_2': 0.24936550023037615}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  72%|█████████████████████████████████████████████████████████████████████████████████████████████▋                                    | 1441/2000 [00:55<00:30, 18.61it/s]

[I 2026-07-03 10:23:31,277] Trial 1437 finished with value: 0.9496743270016106 and parameters: {'weight_lgbm_class_0': 0.060420694476587544, 'weight_lgbm_class_1': 0.7407016372953946, 'weight_lgbm_class_2': 0.8109239516076222, 'weight_xgb_class_0': 0.046118369909529035, 'weight_xgb_class_1': 0.5025066433857895, 'weight_xgb_class_2': 0.48197927207854535, 'weight_cat_class_0': 0.020873159153747333, 'weight_cat_class_1': 0.7301423596066055, 'weight_cat_class_2': 0.47691108968841917}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:31,387] Trial 1438 finished with value: 0.9163336199124505 and parameters: {'weight_lgbm_class_0': 0.06352343283401513, 'weight_lgbm_class_1': 0.7459511018759858, 'weight_lgbm_class_2': 0.809928970190586, 'weight_xgb_class_0': 0.05027578986107084, 'weight_xgb_class_1': 0.49432665224280514, 'weight_xgb_class_2': 0.5327639506627622, 'weight_cat_class_0': 0.9013149422305755, 'weight_cat_class_1': 0.7284652977433332, 'weight_cat_class_2': 0.47689570096649514}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:31,435] Trial 1439 finished with value: 0.9418583582652228 and parameters: {'weight_lgbm_class_0': 0.026826359159430255, 'weight_lgbm_class_1': 0.8657990964317707, 'weight_lgbm_class_2': 0.8113166106329994, 'weight_xgb_class_0': 0.000688163596668425, 'weight_xgb_class_1': 0.5090296605937307, 'weight_xgb_class_2': 0.48664372315100574, 'weight_cat_class_0': 0.0005932902375133613, 'weight_cat_class_1': 0.7963445788000123, 'weight_cat_class_2': 0.473158590090454}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:31,448] Trial 1440 finished with value: 0.9495372723332377 and parameters: {'weight_lgbm_class_0': 0.02908501072348026, 'weight_lgbm_class_1': 0.7459982851807931, 'weight_lgbm_class_2': 0.8118162665624054, 'weight_xgb_class_0': 0.06323651245083638, 'weight_xgb_class_1': 0.49872243783007497, 'weight_xgb_class_2': 0.5334102344117234, 'weight_cat_class_0': 0.021526982725830278, 'weight_cat_class_1': 0.8606181123835541, 'weight_cat_class_2': 0.4755436229008828}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:31,463] Trial 1441 finished with value: 0.9232344526935625 and parameters: {'weight_lgbm_class_0': 0.06240359151814404, 'weight_lgbm_class_1': 0.8648221324082298, 'weight_lgbm_class_2': 0.8079885327390287, 'weight_xgb_class_0': 0.06503530049902226, 'weight_xgb_class_1': 0.595919034575097, 'weight_xgb_class_2': 0.528440951876434, 'weight_cat_class_0': 0.7956641066829904, 'weight_cat_class_1': 0.7276278437055124, 'weight_cat_class_2': 0.4846439790657643}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  72%|█████████████████████████████████████████████████████████████████████████████████████████████▉                                    | 1446/2000 [00:55<00:28, 19.65it/s]

[I 2026-07-03 10:23:31,553] Trial 1442 finished with value: 0.9495691100359117 and parameters: {'weight_lgbm_class_0': 0.03231229936927094, 'weight_lgbm_class_1': 0.8758924993876369, 'weight_lgbm_class_2': 0.8087270665213684, 'weight_xgb_class_0': 0.05721187978008786, 'weight_xgb_class_1': 0.4968636352633426, 'weight_xgb_class_2': 0.49450216342966996, 'weight_cat_class_0': 0.023554441792208492, 'weight_cat_class_1': 0.7953352614672313, 'weight_cat_class_2': 0.47446184335678726}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:31,614] Trial 1443 finished with value: 0.9445029417241241 and parameters: {'weight_lgbm_class_0': 0.029922792640543712, 'weight_lgbm_class_1': 0.8717783460885162, 'weight_lgbm_class_2': 0.20153253621234496, 'weight_xgb_class_0': 5.915432590860789e-05, 'weight_xgb_class_1': 0.4989344240613864, 'weight_xgb_class_2': 0.48801218835553095, 'weight_cat_class_0': 0.0008344532892740817, 'weight_cat_class_1': 0.7273321713550007, 'weight_cat_class_2': 0.48760316906530093}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:31,674] Trial 1444 finished with value: 0.9445671083462162 and parameters: {'weight_lgbm_class_0': 0.02973380713588221, 'weight_lgbm_class_1': 0.8635935781536997, 'weight_lgbm_class_2': 0.8538594513279057, 'weight_xgb_class_0': 0.37252320192539434, 'weight_xgb_class_1': 0.49003045283802815, 'weight_xgb_class_2': 0.5294121941454009, 'weight_cat_class_0': 0.02586259783162858, 'weight_cat_class_1': 0.7609113543878051, 'weight_cat_class_2': 0.5087120039899488}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:31,715] Trial 1446 finished with value: 0.9496315603993404 and parameters: {'weight_lgbm_class_0': 0.030994642804830115, 'weight_lgbm_class_1': 0.8290137921364797, 'weight_lgbm_class_2': 0.6116714656032692, 'weight_xgb_class_0': 0.08904441151605497, 'weight_xgb_class_1': 0.4925113791867709, 'weight_xgb_class_2': 0.4835974462530977, 'weight_cat_class_0': 0.025986377245667845, 'weight_cat_class_1': 0.7904602814490221, 'weight_cat_class_2': 0.3765799016683464}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:31,750] Trial 1445 finished with value: 0.9496980620991259 and parameters: {'weight_lgbm_class_0': 0.025742844826986213, 'weight_lgbm_class_1': 0.8694398298880658, 'weight_lgbm_class_2': 0.5812299453286642, 'weight_xgb_class_0': 0.06544715347203531, 'weight_xgb_class_1': 0.4927795340175777, 'weight_xgb_class_2': 0.5305845194245851, 'weight_cat_class_0': 0.026602607589693, 'weight_cat_class_1': 0.7617650870225462, 'weight_cat_class_2': 0.4800923696959368}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  72%|██████████████████████████████████████████████████████████████████████████████████████████████▎                                   | 1450/2000 [00:56<00:26, 20.58it/s]

[I 2026-07-03 10:23:31,810] Trial 1447 finished with value: 0.9496420714511887 and parameters: {'weight_lgbm_class_0': 0.030414602651807975, 'weight_lgbm_class_1': 0.8696919625502902, 'weight_lgbm_class_2': 0.8512878007151177, 'weight_xgb_class_0': 0.09237656140427207, 'weight_xgb_class_1': 0.4912367988131104, 'weight_xgb_class_2': 0.4870669311270282, 'weight_cat_class_0': 0.0003003726729578571, 'weight_cat_class_1': 0.5022588022663801, 'weight_cat_class_2': 0.5164828609101114}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:31,840] Trial 1448 finished with value: 0.9494037273858232 and parameters: {'weight_lgbm_class_0': 0.027448370336592667, 'weight_lgbm_class_1': 0.24797311798253574, 'weight_lgbm_class_2': 0.8523498448294834, 'weight_xgb_class_0': 0.09165049972319407, 'weight_xgb_class_1': 0.4905198375220011, 'weight_xgb_class_2': 0.48725425429589697, 'weight_cat_class_0': 0.025784147473366034, 'weight_cat_class_1': 0.7614799708067436, 'weight_cat_class_2': 0.39046400091419675}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:31,893] Trial 1449 finished with value: 0.9442965461061048 and parameters: {'weight_lgbm_class_0': 0.22832576195344229, 'weight_lgbm_class_1': 0.8758190969928662, 'weight_lgbm_class_2': 0.5833084831037448, 'weight_xgb_class_0': 0.08686303222299098, 'weight_xgb_class_1': 0.48404069055505816, 'weight_xgb_class_2': 0.4639229722479793, 'weight_cat_class_0': 0.02919364717670355, 'weight_cat_class_1': 0.3398247592856718, 'weight_cat_class_2': 0.38552250297628005}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:31,986] Trial 1450 finished with value: 0.9496758392024742 and parameters: {'weight_lgbm_class_0': 0.025236954910773855, 'weight_lgbm_class_1': 0.8640256907452555, 'weight_lgbm_class_2': 0.5817388167660175, 'weight_xgb_class_0': 0.09404888372314638, 'weight_xgb_class_1': 0.4742351684984039, 'weight_xgb_class_2': 0.48800490574740163, 'weight_cat_class_0': 0.02961237252244796, 'weight_cat_class_1': 0.7938628969637143, 'weight_cat_class_2': 0.5097527612109162}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  73%|██████████████████████████████████████████████████████████████████████████████████████████████▌                                   | 1455/2000 [00:56<00:28, 19.18it/s]

[I 2026-07-03 10:23:32,044] Trial 1451 finished with value: 0.9467286965951702 and parameters: {'weight_lgbm_class_0': 0.09584666664330607, 'weight_lgbm_class_1': 0.8253071280073206, 'weight_lgbm_class_2': 0.8450484215234744, 'weight_xgb_class_0': 0.1934769949286655, 'weight_xgb_class_1': 0.30815147736014814, 'weight_xgb_class_2': 0.45748086076090333, 'weight_cat_class_0': 0.03201928280052301, 'weight_cat_class_1': 0.7601827077523116, 'weight_cat_class_2': 0.3921886258409558}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:32,077] Trial 1452 finished with value: 0.9130826302832152 and parameters: {'weight_lgbm_class_0': 0.8725279606672947, 'weight_lgbm_class_1': 0.8301406828534337, 'weight_lgbm_class_2': 0.8530997892673894, 'weight_xgb_class_0': 0.1950820132491587, 'weight_xgb_class_1': 0.4866553865683232, 'weight_xgb_class_2': 0.46232611342708907, 'weight_cat_class_0': 0.031137397839998058, 'weight_cat_class_1': 0.7652735351099967, 'weight_cat_class_2': 0.5119350123275432}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:32,100] Trial 1453 finished with value: 0.949477020868863 and parameters: {'weight_lgbm_class_0': 0.09115329010581508, 'weight_lgbm_class_1': 0.7801900337529588, 'weight_lgbm_class_2': 0.6143446772052626, 'weight_xgb_class_0': 5.181838677940424e-05, 'weight_xgb_class_1': 0.3094701212724721, 'weight_xgb_class_2': 0.46597672674261115, 'weight_cat_class_0': 5.8731864282800944e-05, 'weight_cat_class_1': 0.7603815636897642, 'weight_cat_class_2': 0.3879897131668367}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:32,191] Trial 1454 finished with value: 0.9364781786708255 and parameters: {'weight_lgbm_class_0': 0.0953938688221561, 'weight_lgbm_class_1': 0.8272249054115052, 'weight_lgbm_class_2': 0.6075408966328362, 'weight_xgb_class_0': 0.07917529059717475, 'weight_xgb_class_1': 0.4737802485714088, 'weight_xgb_class_2': 0.46062217052791776, 'weight_cat_class_0': 0.3751716275132551, 'weight_cat_class_1': 0.7630442303862924, 'weight_cat_class_2': 0.3921464566738591}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:32,209] Trial 1455 finished with value: 0.9433340478563466 and parameters: {'weight_lgbm_class_0': 0.0010616516088653369, 'weight_lgbm_class_1': 0.7763502121691843, 'weight_lgbm_class_2': 0.8380658137048066, 'weight_xgb_class_0': 0.0907362050986318, 'weight_xgb_class_1': 0.4724929264936392, 'weight_xgb_class_2': 0.4626152141975962, 'weight_cat_class_0': 0.3742595798072497, 'weight_cat_class_1': 0.7954192587668797, 'weight_cat_class_2': 0.5042583271278553}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  73%|██████████████████████████████████████████████████████████████████████████████████████████████▉                                   | 1461/2000 [00:56<00:26, 20.31it/s]

[I 2026-07-03 10:23:32,301] Trial 1456 finished with value: 0.9490224952823333 and parameters: {'weight_lgbm_class_0': 0.09528698746484224, 'weight_lgbm_class_1': 0.8291483579310747, 'weight_lgbm_class_2': 0.8412741193490234, 'weight_xgb_class_0': 0.09624834337568683, 'weight_xgb_class_1': 0.47266484418500876, 'weight_xgb_class_2': 0.46286521324755564, 'weight_cat_class_0': 0.03014129945809315, 'weight_cat_class_1': 0.7657326538660316, 'weight_cat_class_2': 0.39306921022459734}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:32,309] Trial 1457 finished with value: 0.9287601888473426 and parameters: {'weight_lgbm_class_0': 0.0005423425575067312, 'weight_lgbm_class_1': 0.7770654347285, 'weight_lgbm_class_2': 0.8447125489514251, 'weight_xgb_class_0': 0.7162667426842044, 'weight_xgb_class_1': 0.5950301658546545, 'weight_xgb_class_2': 0.4616314181932308, 'weight_cat_class_0': 0.030958408718332546, 'weight_cat_class_1': 0.7578627208265665, 'weight_cat_class_2': 0.42639042649167064}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:32,360] Trial 1458 finished with value: 0.946293875205582 and parameters: {'weight_lgbm_class_0': 0.08564388004251254, 'weight_lgbm_class_1': 0.0946213839732088, 'weight_lgbm_class_2': 0.8439500255541049, 'weight_xgb_class_0': 0.13515273479820783, 'weight_xgb_class_1': 0.5930912374622175, 'weight_xgb_class_2': 0.4620109199750451, 'weight_cat_class_0': 0.07600820147097559, 'weight_cat_class_1': 0.7603654609864958, 'weight_cat_class_2': 0.5262788132576741}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:32,405] Trial 1459 finished with value: 0.9462113654829166 and parameters: {'weight_lgbm_class_0': 0.09586926480781985, 'weight_lgbm_class_1': 0.6627192182634558, 'weight_lgbm_class_2': 0.6109527445820565, 'weight_xgb_class_0': 0.13466545976713185, 'weight_xgb_class_1': 0.3130489822221364, 'weight_xgb_class_2': 0.46198754222661365, 'weight_cat_class_0': 0.07378676417853883, 'weight_cat_class_1': 0.763217396519794, 'weight_cat_class_2': 0.3820478219965168}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:32,465] Trial 1460 finished with value: 0.9491669029637672 and parameters: {'weight_lgbm_class_0': 0.09118571948004253, 'weight_lgbm_class_1': 0.7732722595780459, 'weight_lgbm_class_2': 0.6730827650406772, 'weight_xgb_class_0': 0.0318332593554035, 'weight_xgb_class_1': 0.5936369462157005, 'weight_xgb_class_2': 0.4603022545256657, 'weight_cat_class_0': 0.07583486796760085, 'weight_cat_class_1': 0.8060330965539594, 'weight_cat_class_2': 0.4216771283834039}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  73%|███████████████████████████████████████████████████████████████████████████████████████████████▏                                  | 1465/2000 [00:56<00:29, 18.29it/s]

[I 2026-07-03 10:23:32,530] Trial 1461 finished with value: 0.9488394592761852 and parameters: {'weight_lgbm_class_0': 0.0005913829469294599, 'weight_lgbm_class_1': 0.6798811911809589, 'weight_lgbm_class_2': 0.6101243851847924, 'weight_xgb_class_0': 0.131262403748248, 'weight_xgb_class_1': 0.31059017406552114, 'weight_xgb_class_2': 0.4227934294919911, 'weight_cat_class_0': 0.07281383470172435, 'weight_cat_class_1': 0.7953928974298085, 'weight_cat_class_2': 0.42763315916794886}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:32,574] Trial 1462 finished with value: 0.9489253633507518 and parameters: {'weight_lgbm_class_0': 0.0005699329214641363, 'weight_lgbm_class_1': 0.6765854718357636, 'weight_lgbm_class_2': 0.6721330523113251, 'weight_xgb_class_0': 0.0007128774495832758, 'weight_xgb_class_1': 0.5933714911170728, 'weight_xgb_class_2': 0.4242490435664409, 'weight_cat_class_0': 0.0746763690234359, 'weight_cat_class_1': 0.8369000095604733, 'weight_cat_class_2': 0.36911467633218276}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:32,681] Trial 1463 finished with value: 0.9475579126207169 and parameters: {'weight_lgbm_class_0': 0.09067139841630588, 'weight_lgbm_class_1': 0.7801963710996183, 'weight_lgbm_class_2': 0.6680302252863981, 'weight_xgb_class_0': 0.12881929602921813, 'weight_xgb_class_1': 0.5885959346423647, 'weight_xgb_class_2': 0.4268696767224702, 'weight_cat_class_0': 0.07195244679275048, 'weight_cat_class_1': 0.8346682469466747, 'weight_cat_class_2': 0.43440831369675936}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:32,693] Trial 1465 finished with value: 0.9496814813181301 and parameters: {'weight_lgbm_class_0': 0.07647108872908666, 'weight_lgbm_class_1': 0.6702756618328795, 'weight_lgbm_class_2': 0.6646695065298784, 'weight_xgb_class_0': 0.0005733260870618446, 'weight_xgb_class_1': 0.41377677963126247, 'weight_xgb_class_2': 0.42782448952371993, 'weight_cat_class_0': 0.056920385151571426, 'weight_cat_class_1': 0.8371091873462821, 'weight_cat_class_2': 0.43411204527904373}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:32,706] Trial 1464 finished with value: 0.948007888077926 and parameters: {'weight_lgbm_class_0': 0.07452199193682855, 'weight_lgbm_class_1': 0.6772958499221202, 'weight_lgbm_class_2': 0.8363697247644366, 'weight_xgb_class_0': 0.13375404400964622, 'weight_xgb_class_1': 0.5521022604944618, 'weight_xgb_class_2': 0.4239021681159045, 'weight_cat_class_0': 0.07434259230846185, 'weight_cat_class_1': 0.804648296453575, 'weight_cat_class_2': 0.419375150804992}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  74%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                  | 1470/2000 [00:57<00:27, 19.50it/s]

[I 2026-07-03 10:23:32,788] Trial 1466 finished with value: 0.9476700835413677 and parameters: {'weight_lgbm_class_0': 0.07324307723027093, 'weight_lgbm_class_1': 0.6766127260049056, 'weight_lgbm_class_2': 0.6766451168415333, 'weight_xgb_class_0': 0.12754714969015865, 'weight_xgb_class_1': 0.4184884656554722, 'weight_xgb_class_2': 0.42395548445440046, 'weight_cat_class_0': 0.07137446590179405, 'weight_cat_class_1': 0.8366003819058822, 'weight_cat_class_2': 0.429836142398344}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:32,799] Trial 1467 finished with value: 0.9473909380190749 and parameters: {'weight_lgbm_class_0': 0.07660552769126444, 'weight_lgbm_class_1': 0.6538056044806198, 'weight_lgbm_class_2': 0.6741134554185872, 'weight_xgb_class_0': 0.13186994151028547, 'weight_xgb_class_1': 0.4210980802970185, 'weight_xgb_class_2': 0.4265075560288131, 'weight_cat_class_0': 0.07155225825966423, 'weight_cat_class_1': 0.8361076693358953, 'weight_cat_class_2': 0.4204934089676804}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:32,928] Trial 1470 finished with value: 0.9494253850252489 and parameters: {'weight_lgbm_class_0': 0.07027918672947484, 'weight_lgbm_class_1': 0.6674707343053905, 'weight_lgbm_class_2': 0.8273781891268458, 'weight_xgb_class_0': 0.030642452460169868, 'weight_xgb_class_1': 0.3349443197112129, 'weight_xgb_class_2': 0.42406955256293477, 'weight_cat_class_0': 0.06415835104250195, 'weight_cat_class_1': 0.8415072436871005, 'weight_cat_class_2': 0.2543081985140208}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:32,936] Trial 1468 finished with value: 0.9494706257533307 and parameters: {'weight_lgbm_class_0': 0.07691621853788055, 'weight_lgbm_class_1': 0.647623014156528, 'weight_lgbm_class_2': 0.7258229147140194, 'weight_xgb_class_0': 0.03204517427164263, 'weight_xgb_class_1': 0.5502156742613158, 'weight_xgb_class_2': 0.42597929067218254, 'weight_cat_class_0': 0.0674040218251318, 'weight_cat_class_1': 0.8359279680239852, 'weight_cat_class_2': 0.5332716226250184}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:32,970] Trial 1469 finished with value: 0.9488431875576344 and parameters: {'weight_lgbm_class_0': 0.07674916321886126, 'weight_lgbm_class_1': 0.673900310428333, 'weight_lgbm_class_2': 0.6699361075593355, 'weight_xgb_class_0': 0.03257219921639639, 'weight_xgb_class_1': 0.41919789641925326, 'weight_xgb_class_2': 0.42493558762454586, 'weight_cat_class_0': 0.06670704089660326, 'weight_cat_class_1': 0.19828104660909945, 'weight_cat_class_2': 0.4279233637778897}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  74%|███████████████████████████████████████████████████████████████████████████████████████████████▊                                  | 1474/2000 [00:57<00:25, 20.70it/s]

[I 2026-07-03 10:23:32,971] Trial 1471 finished with value: 0.949288737916718 and parameters: {'weight_lgbm_class_0': 0.0673904630753549, 'weight_lgbm_class_1': 0.6802993492657465, 'weight_lgbm_class_2': 0.7196611899621341, 'weight_xgb_class_0': 0.03186131994894762, 'weight_xgb_class_1': 0.4170425000836474, 'weight_xgb_class_2': 0.4271800116282767, 'weight_cat_class_0': 0.06711575989644836, 'weight_cat_class_1': 0.8349386080224619, 'weight_cat_class_2': 0.24850872319992412}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:33,047] Trial 1472 finished with value: 0.9496226379019036 and parameters: {'weight_lgbm_class_0': 0.06848565052183368, 'weight_lgbm_class_1': 0.6753797238715865, 'weight_lgbm_class_2': 0.862248424804706, 'weight_xgb_class_0': 0.030072941017091678, 'weight_xgb_class_1': 0.450342198462557, 'weight_xgb_class_2': 0.4295928250104789, 'weight_cat_class_0': 0.05691965504875648, 'weight_cat_class_1': 0.8327829219333204, 'weight_cat_class_2': 0.26065955010676445}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:33,125] Trial 1473 finished with value: 0.9493002982381862 and parameters: {'weight_lgbm_class_0': 0.0736829246228899, 'weight_lgbm_class_1': 0.6329304753134316, 'weight_lgbm_class_2': 0.7179855124345557, 'weight_xgb_class_0': 0.030427349186351788, 'weight_xgb_class_1': 0.3456033001455912, 'weight_xgb_class_2': 0.425651574874483, 'weight_cat_class_0': 0.061711977258280135, 'weight_cat_class_1': 0.8324467482678586, 'weight_cat_class_2': 0.26275278103728555}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  74%|████████████████████████████████████████████████████████████████████████████████████████████████▏                                 | 1480/2000 [00:57<00:25, 20.68it/s]

[I 2026-07-03 10:23:33,231] Trial 1474 finished with value: 0.9496038907018592 and parameters: {'weight_lgbm_class_0': 0.06849988022135395, 'weight_lgbm_class_1': 0.6399893185990896, 'weight_lgbm_class_2': 0.8649480427980958, 'weight_xgb_class_0': 0.0004067559649296112, 'weight_xgb_class_1': 0.34624308486763256, 'weight_xgb_class_2': 0.419418703493968, 'weight_cat_class_0': 0.05765647229655314, 'weight_cat_class_1': 0.8326746058488648, 'weight_cat_class_2': 0.5339730681336468}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:33,268] Trial 1475 finished with value: 0.9496666782733493 and parameters: {'weight_lgbm_class_0': 0.12634111673428217, 'weight_lgbm_class_1': 0.6439431993603745, 'weight_lgbm_class_2': 0.862905187630287, 'weight_xgb_class_0': 0.03196147519589383, 'weight_xgb_class_1': 0.45394914549598486, 'weight_xgb_class_2': 0.5097781753719414, 'weight_cat_class_0': 0.001241531945435437, 'weight_cat_class_1': 0.8789039709972194, 'weight_cat_class_2': 0.25620737847879066}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:33,288] Trial 1476 finished with value: 0.9491257760258377 and parameters: {'weight_lgbm_class_0': 0.12801498074862405, 'weight_lgbm_class_1': 0.7016398433847362, 'weight_lgbm_class_2': 0.3107346131110461, 'weight_xgb_class_0': 0.03186988723994175, 'weight_xgb_class_1': 0.4490387703653533, 'weight_xgb_class_2': 0.5042612999960486, 'weight_cat_class_0': 0.016422930910345697, 'weight_cat_class_1': 0.8854741923199824, 'weight_cat_class_2': 0.5346949934097943}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:33,347] Trial 1477 finished with value: 0.949278764504449 and parameters: {'weight_lgbm_class_0': 0.12897420408432425, 'weight_lgbm_class_1': 0.8104362403744239, 'weight_lgbm_class_2': 0.7239520928110935, 'weight_xgb_class_0': 0.03465241825340137, 'weight_xgb_class_1': 0.448351482774888, 'weight_xgb_class_2': 0.5147786108285282, 'weight_cat_class_0': 0.018182167370318407, 'weight_cat_class_1': 0.8802146938821996, 'weight_cat_class_2': 0.2582106464117121}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:33,378] Trial 1478 finished with value: 0.9495218094830182 and parameters: {'weight_lgbm_class_0': 0.13197311630867486, 'weight_lgbm_class_1': 0.6272063430715057, 'weight_lgbm_class_2': 0.8274257206568482, 'weight_xgb_class_0': 0.03150284963123918, 'weight_xgb_class_1': 0.34605234933131335, 'weight_xgb_class_2': 0.5093036785110991, 'weight_cat_class_0': 0.0005318037170721482, 'weight_cat_class_1': 0.7888131023730787, 'weight_cat_class_2': 0.5339156848134581}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:33,426] Trial 1479 finished with value: 0.94952635135962 and parameters: {'weight_lgbm_class_0': 0.12597117220218065, 'weight_lgbm_class_1': 0.7007806134312812, 'weight_lgbm_class_2': 0.7081627521819083, 'weight_xgb_class_0': 0.032463990010445275, 'weight_xgb_class_1': 0.5561005611336047, 'weight_xgb_class_2': 0.5031580101328842, 'weight_cat_class_0': 0.000384278826269784, 'weight_cat_class_1': 0.7850390280684696, 'weight_cat_class_2': 0.2564515730892681}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  74%|████████████████████████████████████████████████████████████████████████████████████████████████▍                                 | 1484/2000 [00:57<00:25, 19.85it/s]

[I 2026-07-03 10:23:33,499] Trial 1480 finished with value: 0.9492388360139064 and parameters: {'weight_lgbm_class_0': 0.12387182022569188, 'weight_lgbm_class_1': 0.7073300206579761, 'weight_lgbm_class_2': 0.7930207266363531, 'weight_xgb_class_0': 0.06470993546236503, 'weight_xgb_class_1': 0.45314034608183673, 'weight_xgb_class_2': 0.8103696777899686, 'weight_cat_class_0': 0.01747586811937261, 'weight_cat_class_1': 0.8885023252414274, 'weight_cat_class_2': 0.3045698902412141}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:33,572] Trial 1482 finished with value: 0.949039181066877 and parameters: {'weight_lgbm_class_0': 0.12338083954512953, 'weight_lgbm_class_1': 0.697306307759872, 'weight_lgbm_class_2': 0.8647164563906311, 'weight_xgb_class_0': 0.07343183412356365, 'weight_xgb_class_1': 0.4496239574256347, 'weight_xgb_class_2': 0.4989135458088784, 'weight_cat_class_0': 0.01908034143956737, 'weight_cat_class_1': 0.8818939415852436, 'weight_cat_class_2': 0.29664724275058246}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:33,585] Trial 1481 finished with value: 0.9492345639510811 and parameters: {'weight_lgbm_class_0': 0.12777104910312567, 'weight_lgbm_class_1': 0.7080379911270236, 'weight_lgbm_class_2': 0.8662397194073272, 'weight_xgb_class_0': 0.06773125545618501, 'weight_xgb_class_1': 0.45946976883787033, 'weight_xgb_class_2': 0.5098760809418463, 'weight_cat_class_0': 0.0012005756298861352, 'weight_cat_class_1': 0.8780644486115154, 'weight_cat_class_2': 0.2850810196327437}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:33,609] Trial 1483 finished with value: 0.9496149320011059 and parameters: {'weight_lgbm_class_0': 0.11348674778200628, 'weight_lgbm_class_1': 0.8497510397704757, 'weight_lgbm_class_2': 0.8931916334509746, 'weight_xgb_class_0': 0.06708014370590437, 'weight_xgb_class_1': 0.4515527880085243, 'weight_xgb_class_2': 0.5128431855224387, 'weight_cat_class_0': 0.0006652032764285637, 'weight_cat_class_1': 0.8817924417097985, 'weight_cat_class_2': 0.5666491508874886}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:33,664] Trial 1484 finished with value: 0.9493822350498636 and parameters: {'weight_lgbm_class_0': 0.12659051938347082, 'weight_lgbm_class_1': 0.7020204285996263, 'weight_lgbm_class_2': 0.8631432132830528, 'weight_xgb_class_0': 0.0727400009201916, 'weight_xgb_class_1': 0.556762726299174, 'weight_xgb_class_2': 0.4888428150748942, 'weight_cat_class_0': 0.0010832198354462643, 'weight_cat_class_1': 0.875729203444306, 'weight_cat_class_2': 0.5024175168099677}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:33,714] Trial 1485 finished with value: 0.9492629400953393 and parameters: {'weight_lgbm_class_0': 0.12723958369623956, 'weight_lgbm_class_1': 0.7050489049083392, 'weight_lgbm_class_2': 0.9982714035606699, 'weight_xgb_class_0': 0.06489269574235533, 'weight_xgb_class_1': 0.4497239052259002, 'weight_xgb_class_2': 0.5084573375018255, 'weight_cat_class_0': 0.01693155817411706, 'weight_cat_class_1': 0.878076777047792, 'weight_cat_class_2': 0.3056827572881265}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:33,851] Trial 1486 finished with value: 0.9491575984344244 and parameters: {'weight_lgbm_class_0': 0.1260822106600838, 'weight_lgbm_class_1': 0.8098648343152617, 'weight_lgbm_class_2': 0.8902293916759543, 'weight_xgb_class_0': 0.06727745416012978, 'weight_xgb_class_1': 0.5686512022539958, 'weight_xgb_class_2': 0.5091862938913865, 'weight_cat_class_0': 0.017365144178759735, 'weight_cat_class_1': 0.7887816462316845, 'weight_cat_class_2': 0.28996012065370846}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:33,896] Trial 1488 finished with value: 0.9492189680607668 and parameters: {'weight_lgbm_class_0': 0.11142303047078701, 'weight_lgbm_class_1': 0.8073601369082082, 'weight_lgbm_class_2': 0.7897650994439104, 'weight_xgb_class_0': 0.06979536674141548, 'weight_xgb_class_1': 0.557464704347668, 'weight_xgb_class_2': 0.5088178654519723, 'weight_cat_class_0': 0.018215244423925026, 'weight_cat_class_1': 0.7847489129863457, 'weight_cat_class_2': 0.2988613276506422}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  75%|████████████████████████████████████████████████████████████████████████████████████████████████▉                                 | 1492/2000 [00:58<00:25, 19.65it/s]

[I 2026-07-03 10:23:33,896] Trial 1487 finished with value: 0.9492088502336206 and parameters: {'weight_lgbm_class_0': 0.11398647853378462, 'weight_lgbm_class_1': 0.6976698409344592, 'weight_lgbm_class_2': 0.7885487589599377, 'weight_xgb_class_0': 0.06265431075154547, 'weight_xgb_class_1': 0.5579553859997669, 'weight_xgb_class_2': 0.5040331387987765, 'weight_cat_class_0': 0.01835769266584545, 'weight_cat_class_1': 0.8108907862948939, 'weight_cat_class_2': 0.2875419564834822}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:33,953] Trial 1489 finished with value: 0.9492716028531328 and parameters: {'weight_lgbm_class_0': 0.11089283260238143, 'weight_lgbm_class_1': 0.6978534424089453, 'weight_lgbm_class_2': 0.7959717129762017, 'weight_xgb_class_0': 0.06824140305865192, 'weight_xgb_class_1': 0.54910394396714, 'weight_xgb_class_2': 0.4795113670744605, 'weight_cat_class_0': 0.033350419050559785, 'weight_cat_class_1': 0.7916891819849728, 'weight_cat_class_2': 0.5635891638510794}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:34,009] Trial 1490 finished with value: 0.9494996586215235 and parameters: {'weight_lgbm_class_0': 0.11073379025752773, 'weight_lgbm_class_1': 0.7104978204354985, 'weight_lgbm_class_2': 0.8965058793113209, 'weight_xgb_class_0': 0.0670301762851385, 'weight_xgb_class_1': 0.5248018505272392, 'weight_xgb_class_2': 0.4842954584909463, 'weight_cat_class_0': 0.0001257017832264687, 'weight_cat_class_1': 0.7868237731908669, 'weight_cat_class_2': 0.3178016241992319}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:34,064] Trial 1491 finished with value: 0.9493030542088369 and parameters: {'weight_lgbm_class_0': 0.111559793100335, 'weight_lgbm_class_1': 0.8139928840270755, 'weight_lgbm_class_2': 0.7878539547602909, 'weight_xgb_class_0': 0.06499503981609858, 'weight_xgb_class_1': 0.5236832491826975, 'weight_xgb_class_2': 0.48103077548424783, 'weight_cat_class_0': 0.034830748045898335, 'weight_cat_class_1': 0.8089595287605842, 'weight_cat_class_2': 0.5670104348431807}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:34,120] Trial 1492 finished with value: 0.9254013652710879 and parameters: {'weight_lgbm_class_0': 0.11026118365324769, 'weight_lgbm_class_1': 0.8434916850093586, 'weight_lgbm_class_2': 0.8970213821435931, 'weight_xgb_class_0': 0.0002751524313679025, 'weight_xgb_class_1': 0.5272590522245328, 'weight_xgb_class_2': 0.3784762013010967, 'weight_cat_class_0': 0.6931857456745442, 'weight_cat_class_1': 0.8139060770794295, 'weight_cat_class_2': 0.2944092938000439}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  75%|█████████████████████████████████████████████████████████████████████████████████████████████████▎                                | 1498/2000 [00:58<00:23, 21.07it/s]

[I 2026-07-03 10:23:34,193] Trial 1493 finished with value: 0.9491869226742945 and parameters: {'weight_lgbm_class_0': 0.10475106089609218, 'weight_lgbm_class_1': 0.8430347951084511, 'weight_lgbm_class_2': 0.7912089308717309, 'weight_xgb_class_0': 0.06323527986146801, 'weight_xgb_class_1': 0.5222841460866547, 'weight_xgb_class_2': 0.47511413550458814, 'weight_cat_class_0': 0.048036270878290196, 'weight_cat_class_1': 0.8074713149674146, 'weight_cat_class_2': 0.49850701597283353}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:34,230] Trial 1494 finished with value: 0.94902379662813 and parameters: {'weight_lgbm_class_0': 0.16716661040454714, 'weight_lgbm_class_1': 0.8096972394305855, 'weight_lgbm_class_2': 0.7915158320631211, 'weight_xgb_class_0': 0.014943906193088738, 'weight_xgb_class_1': 0.5234953846150587, 'weight_xgb_class_2': 0.38424572712461186, 'weight_cat_class_0': 0.041839829369625846, 'weight_cat_class_1': 0.8097003214956927, 'weight_cat_class_2': 0.5006199622705716}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:34,241] Trial 1495 finished with value: 0.9495951168851589 and parameters: {'weight_lgbm_class_0': 0.09926147866773095, 'weight_lgbm_class_1': 0.8030188408567814, 'weight_lgbm_class_2': 0.5792057505171071, 'weight_xgb_class_0': 0.017027655295243676, 'weight_xgb_class_1': 0.532140099214938, 'weight_xgb_class_2': 0.38377239308466654, 'weight_cat_class_0': 0.03728253303891153, 'weight_cat_class_1': 0.7388397572942447, 'weight_cat_class_2': 0.49997950134038555}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:34,249] Trial 1496 finished with value: 0.9493316914498403 and parameters: {'weight_lgbm_class_0': 0.17186978944269626, 'weight_lgbm_class_1': 0.8105301349630802, 'weight_lgbm_class_2': 0.998082212758723, 'weight_xgb_class_0': 0.01517717527447389, 'weight_xgb_class_1': 0.5199032499318357, 'weight_xgb_class_2': 0.4768253327387676, 'weight_cat_class_0': 0.03511525443513484, 'weight_cat_class_1': 0.739767124476632, 'weight_cat_class_2': 0.5655013934424591}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:34,337] Trial 1497 finished with value: 0.9439019833984186 and parameters: {'weight_lgbm_class_0': 0.16858886687507235, 'weight_lgbm_class_1': 0.8117390074039595, 'weight_lgbm_class_2': 0.7926760891508015, 'weight_xgb_class_0': 0.020920308480203462, 'weight_xgb_class_1': 0.5258443288663962, 'weight_xgb_class_2': 0.3836598409980699, 'weight_cat_class_0': 0.2611997742546732, 'weight_cat_class_1': 0.8095237155465267, 'weight_cat_class_2': 0.5676673296950953}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  75%|█████████████████████████████████████████████████████████████████████████████████████████████████▋                                | 1503/2000 [00:58<00:26, 18.53it/s]

[I 2026-07-03 10:23:34,465] Trial 1498 finished with value: 0.9492554558848098 and parameters: {'weight_lgbm_class_0': 0.16700556496553365, 'weight_lgbm_class_1': 0.8395374596559148, 'weight_lgbm_class_2': 0.8297459604012597, 'weight_xgb_class_0': 0.0013669359117555902, 'weight_xgb_class_1': 0.5136504801491515, 'weight_xgb_class_2': 0.38857285466026414, 'weight_cat_class_0': 0.041114806280257286, 'weight_cat_class_1': 0.8092813772609921, 'weight_cat_class_2': 0.4681458019698577}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:34,511] Trial 1499 finished with value: 0.9489533000719423 and parameters: {'weight_lgbm_class_0': 0.042499468255215805, 'weight_lgbm_class_1': 0.8439890991265158, 'weight_lgbm_class_2': 0.8328051686231094, 'weight_xgb_class_0': 0.0164707472699172, 'weight_xgb_class_1': 0.5214451987541897, 'weight_xgb_class_2': 0.7616710576762092, 'weight_cat_class_0': 0.03703601613531897, 'weight_cat_class_1': 0.6892744690670318, 'weight_cat_class_2': 0.5703025376837548}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:34,535] Trial 1501 finished with value: 0.9492679214519274 and parameters: {'weight_lgbm_class_0': 0.1667460723432113, 'weight_lgbm_class_1': 0.7625679546585097, 'weight_lgbm_class_2': 0.8312784631919722, 'weight_xgb_class_0': 0.00029263279293035476, 'weight_xgb_class_1': 0.5145859971557178, 'weight_xgb_class_2': 0.4521612982051132, 'weight_cat_class_0': 0.04561054181597134, 'weight_cat_class_1': 0.7395578057866451, 'weight_cat_class_2': 0.4939428574116386}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:34,542] Trial 1500 finished with value: 0.941096704888805 and parameters: {'weight_lgbm_class_0': 0.05116507541324786, 'weight_lgbm_class_1': 0.8422175729491866, 'weight_lgbm_class_2': 0.5865650474382912, 'weight_xgb_class_0': 0.0011632330998155582, 'weight_xgb_class_1': 0.5206735628451257, 'weight_xgb_class_2': 0.4475978437592643, 'weight_cat_class_0': 0.42218979028629133, 'weight_cat_class_1': 0.7355893756150151, 'weight_cat_class_2': 0.4652749543957834}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:34,616] Trial 1502 finished with value: 0.9488384674180068 and parameters: {'weight_lgbm_class_0': 0.17747425181817794, 'weight_lgbm_class_1': 0.8448909399293636, 'weight_lgbm_class_2': 0.6239027520484877, 'weight_xgb_class_0': 0.00014671796238350534, 'weight_xgb_class_1': 0.5216576711704826, 'weight_xgb_class_2': 0.38020427029236425, 'weight_cat_class_0': 0.03991957644671661, 'weight_cat_class_1': 0.7437178384474338, 'weight_cat_class_2': 0.4675367076321888}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:34,634] Trial 1503 finished with value: 0.9493582645867368 and parameters: {'weight_lgbm_class_0': 0.045802806735426686, 'weight_lgbm_class_1': 0.7596598502338365, 'weight_lgbm_class_2': 0.583706422780014, 'weight_xgb_class_0': 0.00045461066667892185, 'weight_xgb_class_1': 0.5250952029360745, 'weight_xgb_class_2': 0.3872017551204448, 'weight_cat_class_0': 0.042959207398977343, 'weight_cat_class_1': 0.7403761983212015, 'weight_cat_class_2': 0.4620731547743323}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  75%|█████████████████████████████████████████████████████████████████████████████████████████████████▉                                | 1507/2000 [00:59<00:27, 17.76it/s]

[I 2026-07-03 10:23:34,717] Trial 1504 finished with value: 0.9497544931855311 and parameters: {'weight_lgbm_class_0': 0.05448315146033192, 'weight_lgbm_class_1': 0.7569598309356667, 'weight_lgbm_class_2': 0.5800521536499744, 'weight_xgb_class_0': 0.02028502101399281, 'weight_xgb_class_1': 0.5113365964484851, 'weight_xgb_class_2': 0.4498169118794287, 'weight_cat_class_0': 0.04018375209112692, 'weight_cat_class_1': 0.7234807344778844, 'weight_cat_class_2': 0.46170137308332637}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:34,789] Trial 1505 finished with value: 0.9493537550665984 and parameters: {'weight_lgbm_class_0': 0.0430267895824864, 'weight_lgbm_class_1': 0.7738711952067291, 'weight_lgbm_class_2': 0.581614067730715, 'weight_xgb_class_0': 0.016232368775159343, 'weight_xgb_class_1': 0.2154541790076675, 'weight_xgb_class_2': 0.7689391889040492, 'weight_cat_class_0': 0.03835403433816589, 'weight_cat_class_1': 0.8610641218189706, 'weight_cat_class_2': 0.46837086710318154}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:34,880] Trial 1507 finished with value: 0.9343936698172973 and parameters: {'weight_lgbm_class_0': 0.5756439826753492, 'weight_lgbm_class_1': 0.760857457960967, 'weight_lgbm_class_2': 0.8215360389636376, 'weight_xgb_class_0': 0.01641411380313587, 'weight_xgb_class_1': 0.2114245279116588, 'weight_xgb_class_2': 0.4498435943635268, 'weight_cat_class_0': 0.03799062883337355, 'weight_cat_class_1': 0.851691746503287, 'weight_cat_class_2': 0.4572140262154654}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:34,881] Trial 1506 finished with value: 0.9496570931254794 and parameters: {'weight_lgbm_class_0': 0.047462201394744274, 'weight_lgbm_class_1': 0.763416412805313, 'weight_lgbm_class_2': 0.6113686289671971, 'weight_xgb_class_0': 0.016592115741125815, 'weight_xgb_class_1': 0.2521986507668047, 'weight_xgb_class_2': 0.45203469876766883, 'weight_cat_class_0': 0.03752743383218188, 'weight_cat_class_1': 0.6851768738751057, 'weight_cat_class_2': 0.457878084568536}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:34,895] Trial 1508 finished with value: 0.9493488044656139 and parameters: {'weight_lgbm_class_0': 0.051550963465812526, 'weight_lgbm_class_1': 0.4305169980413709, 'weight_lgbm_class_2': 0.823587659244319, 'weight_xgb_class_0': 0.015052170215462707, 'weight_xgb_class_1': 0.21488541189373828, 'weight_xgb_class_2': 0.4528649699992365, 'weight_cat_class_0': 0.03813047073164608, 'weight_cat_class_1': 0.8542475353967062, 'weight_cat_class_2': 0.4693695539578033}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:34,938] Trial 1509 finished with value: 0.9489613153860207 and parameters: {'weight_lgbm_class_0': 0.03778697670210571, 'weight_lgbm_class_1': 0.7695448114656932, 'weight_lgbm_class_2': 0.8281211157335103, 'weight_xgb_class_0': 0.0010064350336100375, 'weight_xgb_class_1': 0.21415040925754902, 'weight_xgb_class_2': 0.4489633075950389, 'weight_cat_class_0': 0.03746720779261522, 'weight_cat_class_1': 0.7148939817390487, 'weight_cat_class_2': 0.3573606717807605}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:35,063] Trial 1510 finished with value: 0.9491725630877145 and parameters: {'weight_lgbm_class_0': 0.04316795364310004, 'weight_lgbm_class_1': 0.7592935025025427, 'weight_lgbm_class_2': 0.6313609953450527, 'weight_xgb_class_0': 0.10023207976435392, 'weight_xgb_class_1': 0.23123188457648153, 'weight_xgb_class_2': 0.4479187827896721, 'weight_cat_class_0': 0.03797627524004754, 'weight_cat_class_1': 0.6838823083652847, 'weight_cat_class_2': 0.4638634008676604}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  76%|██████████████████████████████████████████████████████████████████████████████████████████████████▌                               | 1517/2000 [00:59<00:25, 19.29it/s]

[I 2026-07-03 10:23:35,129] Trial 1511 finished with value: 0.9497027636672737 and parameters: {'weight_lgbm_class_0': 0.03989204440509818, 'weight_lgbm_class_1': 0.7674460036272633, 'weight_lgbm_class_2': 0.6272135385754202, 'weight_xgb_class_0': 0.045562556742455, 'weight_xgb_class_1': 0.2129390764452025, 'weight_xgb_class_2': 0.45302452316133895, 'weight_cat_class_0': 0.029126322925574898, 'weight_cat_class_1': 0.8502621534823266, 'weight_cat_class_2': 0.45687949366556624}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:35,146] Trial 1512 finished with value: 0.9494730657625698 and parameters: {'weight_lgbm_class_0': 0.017836856837001668, 'weight_lgbm_class_1': 0.36319867484908963, 'weight_lgbm_class_2': 0.6073265481365189, 'weight_xgb_class_0': 0.04721469150444926, 'weight_xgb_class_1': 0.23075740237137793, 'weight_xgb_class_2': 0.4517041483860317, 'weight_cat_class_0': 0.033184602701095654, 'weight_cat_class_1': 0.8535287377709677, 'weight_cat_class_2': 0.45974976994955113}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:35,186] Trial 1513 finished with value: 0.9492480324224896 and parameters: {'weight_lgbm_class_0': 0.017615602575352832, 'weight_lgbm_class_1': 0.7275479951703057, 'weight_lgbm_class_2': 0.6251011742400426, 'weight_xgb_class_0': 0.039768224490975494, 'weight_xgb_class_1': 0.2147371309178462, 'weight_xgb_class_2': 0.45094988092778876, 'weight_cat_class_0': 0.03268344712116712, 'weight_cat_class_1': 0.8576307935494852, 'weight_cat_class_2': 0.595081770595338}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:35,231] Trial 1514 finished with value: 0.9496171026328873 and parameters: {'weight_lgbm_class_0': 0.017353280440674898, 'weight_lgbm_class_1': 0.725678681331788, 'weight_lgbm_class_2': 0.8136814547295074, 'weight_xgb_class_0': 0.10054387726582333, 'weight_xgb_class_1': 0.21995038068588285, 'weight_xgb_class_2': 0.4477070409650761, 'weight_cat_class_0': 0.019284527850135978, 'weight_cat_class_1': 0.7742386550396424, 'weight_cat_class_2': 0.596305350598699}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:35,261] Trial 1515 finished with value: 0.9494065635280554 and parameters: {'weight_lgbm_class_0': 0.05916005863902854, 'weight_lgbm_class_1': 0.7258201002294186, 'weight_lgbm_class_2': 0.6275208102171417, 'weight_xgb_class_0': 0.09613327896976769, 'weight_xgb_class_1': 0.4708490631133052, 'weight_xgb_class_2': 0.4519669764948809, 'weight_cat_class_0': 0.021799745535062972, 'weight_cat_class_1': 0.8553251506120645, 'weight_cat_class_2': 0.5929024693065729}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:35,285] Trial 1516 finished with value: 0.9104150699172381 and parameters: {'weight_lgbm_class_0': 0.06147531418956169, 'weight_lgbm_class_1': 0.7600163579715236, 'weight_lgbm_class_2': 0.6262324493228864, 'weight_xgb_class_0': 0.908941785832124, 'weight_xgb_class_1': 0.47528268986741273, 'weight_xgb_class_2': 0.4510882352718608, 'weight_cat_class_0': 0.019784333998959146, 'weight_cat_class_1': 0.7232622037278263, 'weight_cat_class_2': 0.44207987421255673}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:35,334] Trial 1517 finished with value: 0.949528244387289 and parameters: {'weight_lgbm_class_0': 0.08876282396444003, 'weight_lgbm_class_1': 0.7312124223711706, 'weight_lgbm_class_2': 0.5745862008092015, 'weight_xgb_class_0': 0.04614324876053915, 'weight_xgb_class_1': 0.4766628954571767, 'weight_xgb_class_2': 0.4524583200664561, 'weight_cat_class_0': 0.018893906150269715, 'weight_cat_class_1': 0.7165892682367148, 'weight_cat_class_2': 0.4461429770810759}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  76%|██████████████████████████████████████████████████████████████████████████████████████████████████▉                               | 1523/2000 [00:59<00:26, 18.31it/s]

[I 2026-07-03 10:23:35,527] Trial 1519 finished with value: 0.949050579495053 and parameters: {'weight_lgbm_class_0': 0.0867121899803378, 'weight_lgbm_class_1': 0.010833927959711331, 'weight_lgbm_class_2': 0.5985460928832859, 'weight_xgb_class_0': 0.045531822001041077, 'weight_xgb_class_1': 0.4726581595235367, 'weight_xgb_class_2': 0.4743668111056818, 'weight_cat_class_0': 0.01578240371610595, 'weight_cat_class_1': 0.7319696291667719, 'weight_cat_class_2': 0.41458455736604544}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:35,529] Trial 1518 finished with value: 0.9497319252860955 and parameters: {'weight_lgbm_class_0': 0.06468765890710028, 'weight_lgbm_class_1': 0.7272660153944935, 'weight_lgbm_class_2': 0.5993582546217737, 'weight_xgb_class_0': 0.04659932437430751, 'weight_xgb_class_1': 0.46384992003304576, 'weight_xgb_class_2': 0.4731627626363882, 'weight_cat_class_0': 0.022726774345893555, 'weight_cat_class_1': 0.7197151995804669, 'weight_cat_class_2': 0.5910098281924469}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:35,531] Trial 1520 finished with value: 0.9497085037238976 and parameters: {'weight_lgbm_class_0': 0.08563567873721922, 'weight_lgbm_class_1': 0.7275115646521662, 'weight_lgbm_class_2': 0.5974817718781557, 'weight_xgb_class_0': 0.04601846289812488, 'weight_xgb_class_1': 0.4762251233193132, 'weight_xgb_class_2': 0.47569836785078334, 'weight_cat_class_0': 0.00011973295990058003, 'weight_cat_class_1': 0.7140963954666647, 'weight_cat_class_2': 0.4101833352381655}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:35,574] Trial 1521 finished with value: 0.949649799449003 and parameters: {'weight_lgbm_class_0': 0.09366090213026484, 'weight_lgbm_class_1': 0.7293166993020118, 'weight_lgbm_class_2': 0.5883996660566572, 'weight_xgb_class_0': 0.045026770573401736, 'weight_xgb_class_1': 0.47575824000318373, 'weight_xgb_class_2': 0.48038043877751896, 'weight_cat_class_0': 0.01756691192429043, 'weight_cat_class_1': 0.7396089890589469, 'weight_cat_class_2': 0.5993055156274152}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:35,665] Trial 1522 finished with value: 0.949634140186971 and parameters: {'weight_lgbm_class_0': 0.08596694537916609, 'weight_lgbm_class_1': 0.7270190056637129, 'weight_lgbm_class_2': 0.6019503386986788, 'weight_xgb_class_0': 0.04456387061618885, 'weight_xgb_class_1': 0.4779318684576687, 'weight_xgb_class_2': 0.4740517072102438, 'weight_cat_class_0': 0.018799601082416458, 'weight_cat_class_1': 0.7121243722451636, 'weight_cat_class_2': 0.44071410440099024}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:35,706] Trial 1523 finished with value: 0.9494360837815833 and parameters: {'weight_lgbm_class_0': 0.08676794789401539, 'weight_lgbm_class_1': 0.28527695038957385, 'weight_lgbm_class_2': 0.6070108303340395, 'weight_xgb_class_0': 0.04492322216496908, 'weight_xgb_class_1': 0.4690224118368171, 'weight_xgb_class_2': 0.47685568220391844, 'weight_cat_class_0': 0.0004445279179768756, 'weight_cat_class_1': 0.7033337731880083, 'weight_cat_class_2': 0.5951710193842057}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  76%|███████████████████████████████████████████████████████████████████████████████████████████████████▍                              | 1529/2000 [01:00<00:24, 19.23it/s]

[I 2026-07-03 10:23:35,771] Trial 1524 finished with value: 0.9234121793173368 and parameters: {'weight_lgbm_class_0': 0.09283374490764025, 'weight_lgbm_class_1': 0.7292899090160534, 'weight_lgbm_class_2': 0.5732606609648812, 'weight_xgb_class_0': 0.6254980657033513, 'weight_xgb_class_1': 0.47022244386047846, 'weight_xgb_class_2': 0.4788419863852831, 'weight_cat_class_0': 0.01603493609651263, 'weight_cat_class_1': 0.7064691228417855, 'weight_cat_class_2': 0.4052745920208768}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:35,833] Trial 1525 finished with value: 0.9496886160588103 and parameters: {'weight_lgbm_class_0': 0.0857841458321276, 'weight_lgbm_class_1': 0.7865135034842153, 'weight_lgbm_class_2': 0.5877794685124026, 'weight_xgb_class_0': 0.04295850567038078, 'weight_xgb_class_1': 0.4714872287439362, 'weight_xgb_class_2': 0.4761930621827914, 'weight_cat_class_0': 0.015171741238090721, 'weight_cat_class_1': 0.7348695060342664, 'weight_cat_class_2': 0.4307576392323367}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:35,873] Trial 1526 finished with value: 0.9497224268738312 and parameters: {'weight_lgbm_class_0': 0.07933711134013262, 'weight_lgbm_class_1': 0.2963906117112372, 'weight_lgbm_class_2': 0.5869285713071499, 'weight_xgb_class_0': 0.04531614814799287, 'weight_xgb_class_1': 0.8509234817605102, 'weight_xgb_class_2': 0.4796478618566586, 'weight_cat_class_0': 8.597968614341978e-05, 'weight_cat_class_1': 0.7046434051278756, 'weight_cat_class_2': 0.41115983231643655}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:35,886] Trial 1529 finished with value: 0.9493567216736909 and parameters: {'weight_lgbm_class_0': 0.09561451127075178, 'weight_lgbm_class_1': 0.6180764438059917, 'weight_lgbm_class_2': 0.5740871646756958, 'weight_xgb_class_0': 0.04441104765275908, 'weight_xgb_class_1': 0.47209478239712216, 'weight_xgb_class_2': 0.47781629709930856, 'weight_cat_class_0': 0.017798747617024973, 'weight_cat_class_1': 0.6985306517026506, 'weight_cat_class_2': 0.40780379483948975}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:35,898] Trial 1528 finished with value: 0.949638172152616 and parameters: {'weight_lgbm_class_0': 0.08747199471019373, 'weight_lgbm_class_1': 0.7939466124646289, 'weight_lgbm_class_2': 0.5832267014589116, 'weight_xgb_class_0': 0.04661266499575497, 'weight_xgb_class_1': 0.4819262022568308, 'weight_xgb_class_2': 0.4796595920351893, 'weight_cat_class_0': 0.0001478543160666141, 'weight_cat_class_1': 0.7093126749845723, 'weight_cat_class_2': 0.40747866617257145}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:35,907] Trial 1527 finished with value: 0.9496914045094664 and parameters: {'weight_lgbm_class_0': 0.0774736034217343, 'weight_lgbm_class_1': 0.780796289491034, 'weight_lgbm_class_2': 0.5761228892261995, 'weight_xgb_class_0': 0.04968256304479457, 'weight_xgb_class_1': 0.476440690862666, 'weight_xgb_class_2': 0.4777714440758906, 'weight_cat_class_0': 0.0004907510515656474, 'weight_cat_class_1': 0.7029518452069545, 'weight_cat_class_2': 0.43703687008037684}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  77%|███████████████████████████████████████████████████████████████████████████████████████████████████▊                              | 1535/2000 [01:00<00:22, 20.88it/s]

[I 2026-07-03 10:23:36,115] Trial 1530 finished with value: 0.9493180825470869 and parameters: {'weight_lgbm_class_0': 0.08923288067127141, 'weight_lgbm_class_1': 0.7920292766229439, 'weight_lgbm_class_2': 0.5862640139467641, 'weight_xgb_class_0': 0.019668945690037, 'weight_xgb_class_1': 0.49562363456712166, 'weight_xgb_class_2': 0.4869495465722147, 'weight_cat_class_0': 0.05428898823992719, 'weight_cat_class_1': 0.7088934053651661, 'weight_cat_class_2': 0.2709053922252708}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:36,156] Trial 1531 finished with value: 0.9226478108054451 and parameters: {'weight_lgbm_class_0': 0.07021967962924754, 'weight_lgbm_class_1': 0.7884369431287191, 'weight_lgbm_class_2': 0.5722750038614994, 'weight_xgb_class_0': 0.616673288859876, 'weight_xgb_class_1': 0.4991555477606114, 'weight_xgb_class_2': 0.4820808197920824, 'weight_cat_class_0': 0.016951515508496204, 'weight_cat_class_1': 0.7229920681655998, 'weight_cat_class_2': 0.23506240040016968}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:36,171] Trial 1533 finished with value: 0.9495958984278515 and parameters: {'weight_lgbm_class_0': 0.06853785937374458, 'weight_lgbm_class_1': 0.8870134893309474, 'weight_lgbm_class_2': 0.5765493551935662, 'weight_xgb_class_0': 0.020410343251777752, 'weight_xgb_class_1': 0.4932811325234773, 'weight_xgb_class_2': 0.48593339385977935, 'weight_cat_class_0': 0.016316414636980296, 'weight_cat_class_1': 0.7232182988149912, 'weight_cat_class_2': 0.43550227072326475}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:36,213] Trial 1532 finished with value: 0.949395464349262 and parameters: {'weight_lgbm_class_0': 0.06687184389576828, 'weight_lgbm_class_1': 0.7889835632849035, 'weight_lgbm_class_2': 0.5691937095423456, 'weight_xgb_class_0': 0.022757950099902512, 'weight_xgb_class_1': 0.4917232869005233, 'weight_xgb_class_2': 0.4888803978717332, 'weight_cat_class_0': 0.0008848431055717499, 'weight_cat_class_1': 0.6822296119857822, 'weight_cat_class_2': 0.44435955270927097}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:36,248] Trial 1534 finished with value: 0.9492907858194518 and parameters: {'weight_lgbm_class_0': 0.06833852338079215, 'weight_lgbm_class_1': 0.21970909629771695, 'weight_lgbm_class_2': 0.5683742569377102, 'weight_xgb_class_0': 0.017602446950998336, 'weight_xgb_class_1': 0.5049313042141774, 'weight_xgb_class_2': 0.4856860428339319, 'weight_cat_class_0': 0.05376915273072464, 'weight_cat_class_1': 0.7518546728644868, 'weight_cat_class_2': 0.23644379701209134}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  77%|████████████████████████████████████████████████████████████████████████████████████████████████████                              | 1539/2000 [01:00<00:23, 19.55it/s]

[I 2026-07-03 10:23:36,332] Trial 1535 finished with value: 0.9496160118053085 and parameters: {'weight_lgbm_class_0': 0.06592309593524945, 'weight_lgbm_class_1': 0.7867719576772277, 'weight_lgbm_class_2': 0.5776972045343417, 'weight_xgb_class_0': 0.01936273763279861, 'weight_xgb_class_1': 0.5012430730057351, 'weight_xgb_class_2': 0.4890151162764855, 'weight_cat_class_0': 0.053990132592185956, 'weight_cat_class_1': 0.6990718798776954, 'weight_cat_class_2': 0.33312252354290184}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:36,396] Trial 1536 finished with value: 0.9496360243789189 and parameters: {'weight_lgbm_class_0': 0.06585869474391844, 'weight_lgbm_class_1': 0.619965740909979, 'weight_lgbm_class_2': 0.6473370561228923, 'weight_xgb_class_0': 0.022710592733574748, 'weight_xgb_class_1': 0.4986289062425304, 'weight_xgb_class_2': 0.4944575302261592, 'weight_cat_class_0': 0.05824656969050511, 'weight_cat_class_1': 0.6928644259709156, 'weight_cat_class_2': 0.4362377095202835}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:36,438] Trial 1537 finished with value: 0.9490709292584355 and parameters: {'weight_lgbm_class_0': 0.06468899941902345, 'weight_lgbm_class_1': 0.8794119562628206, 'weight_lgbm_class_2': 0.6434159392383455, 'weight_xgb_class_0': 0.016201024796784577, 'weight_xgb_class_1': 0.5028933525485034, 'weight_xgb_class_2': 0.49678706013505053, 'weight_cat_class_0': 0.0002709017038190764, 'weight_cat_class_1': 0.6947603884911736, 'weight_cat_class_2': 0.4342392737538886}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:36,511] Trial 1539 finished with value: 0.9497252403794656 and parameters: {'weight_lgbm_class_0': 0.06113319345611048, 'weight_lgbm_class_1': 0.8844477355271155, 'weight_lgbm_class_2': 0.6516843185603617, 'weight_xgb_class_0': 0.0251466504510042, 'weight_xgb_class_1': 0.49468908250579774, 'weight_xgb_class_2': 0.49600852159658676, 'weight_cat_class_0': 0.05439090514543318, 'weight_cat_class_1': 0.7552651855741186, 'weight_cat_class_2': 0.32066154200967756}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:36,511] Trial 1538 finished with value: 0.9496233498736976 and parameters: {'weight_lgbm_class_0': 0.06177823988066454, 'weight_lgbm_class_1': 0.8834659779176564, 'weight_lgbm_class_2': 0.6525821947415417, 'weight_xgb_class_0': 0.020095679419765117, 'weight_xgb_class_1': 0.49602895432803873, 'weight_xgb_class_2': 0.4982209593136552, 'weight_cat_class_0': 0.05517912097086673, 'weight_cat_class_1': 0.758325151130358, 'weight_cat_class_2': 0.2360465726945923}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  77%|████████████████████████████████████████████████████████████████████████████████████████████████████▏                             | 1542/2000 [01:00<00:22, 20.44it/s]

[I 2026-07-03 10:23:36,522] Trial 1540 finished with value: 0.9495335339443435 and parameters: {'weight_lgbm_class_0': 0.0617012725555991, 'weight_lgbm_class_1': 0.882126879911826, 'weight_lgbm_class_2': 0.9140395391201886, 'weight_xgb_class_0': 0.00026066589311297874, 'weight_xgb_class_1': 0.5003500191808283, 'weight_xgb_class_2': 0.49979470181190433, 'weight_cat_class_0': 0.051877099716610475, 'weight_cat_class_1': 0.6775498910952495, 'weight_cat_class_2': 0.5261293516032287}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:36,589] Trial 1541 finished with value: 0.9496507234891439 and parameters: {'weight_lgbm_class_0': 0.06581113100039578, 'weight_lgbm_class_1': 0.5734153496737919, 'weight_lgbm_class_2': 0.6565650159984394, 'weight_xgb_class_0': 0.019071637107789714, 'weight_xgb_class_1': 0.49673661429718885, 'weight_xgb_class_2': 0.4928746693676379, 'weight_cat_class_0': 0.050444008483385705, 'weight_cat_class_1': 0.6789095250760294, 'weight_cat_class_2': 0.2405857800743277}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:36,764] Trial 1542 finished with value: 0.9495364545919757 and parameters: {'weight_lgbm_class_0': 0.06142618395006429, 'weight_lgbm_class_1': 0.21555501137716243, 'weight_lgbm_class_2': 0.6562961667405897, 'weight_xgb_class_0': 0.00021042481353569618, 'weight_xgb_class_1': 0.42945690589865015, 'weight_xgb_class_2': 0.49661859514794915, 'weight_cat_class_0': 0.0541737012200537, 'weight_cat_class_1': 0.7511100943369932, 'weight_cat_class_2': 0.33195349361860205}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  77%|████████████████████████████████████████████████████████████████████████████████████████████████████▌                             | 1548/2000 [01:01<00:22, 19.66it/s]

[I 2026-07-03 10:23:36,772] Trial 1543 finished with value: 0.9489206307364336 and parameters: {'weight_lgbm_class_0': 0.061401686584274286, 'weight_lgbm_class_1': 0.6542582401158787, 'weight_lgbm_class_2': 0.6554258076879187, 'weight_xgb_class_0': 0.08706457298097642, 'weight_xgb_class_1': 0.43191448356771833, 'weight_xgb_class_2': 0.4993753923205559, 'weight_cat_class_0': 0.05246548265456275, 'weight_cat_class_1': 0.753910099518202, 'weight_cat_class_2': 0.3579830575233164}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:36,792] Trial 1544 finished with value: 0.945275605755572 and parameters: {'weight_lgbm_class_0': 0.14357942955932193, 'weight_lgbm_class_1': 0.8878043904978185, 'weight_lgbm_class_2': 0.647997395780631, 'weight_xgb_class_0': 0.08994139829807558, 'weight_xgb_class_1': 0.4287687352882437, 'weight_xgb_class_2': 0.49492167754488836, 'weight_cat_class_0': 0.05246266388401176, 'weight_cat_class_1': 0.7566131564462275, 'weight_cat_class_2': 0.0016944307448861495}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:36,798] Trial 1545 finished with value: 0.9302461246954074 and parameters: {'weight_lgbm_class_0': 0.0635703790251057, 'weight_lgbm_class_1': 0.6293277379782499, 'weight_lgbm_class_2': 0.6435485865830608, 'weight_xgb_class_0': 0.4937723077815806, 'weight_xgb_class_1': 0.3938230138331099, 'weight_xgb_class_2': 0.5261847752502686, 'weight_cat_class_0': 0.05833214916171213, 'weight_cat_class_1': 0.7606587725020473, 'weight_cat_class_2': 0.3289058428792261}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:36,837] Trial 1546 finished with value: 0.9488284483623812 and parameters: {'weight_lgbm_class_0': 0.05835138510226104, 'weight_lgbm_class_1': 0.6365592285098349, 'weight_lgbm_class_2': 0.7009410164385705, 'weight_xgb_class_0': 0.09141990947588396, 'weight_xgb_class_1': 0.4285068691045583, 'weight_xgb_class_2': 0.5217946777202894, 'weight_cat_class_0': 0.05167099785882111, 'weight_cat_class_1': 0.5486235684764758, 'weight_cat_class_2': 0.3391562181530072}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:36,951] Trial 1547 finished with value: 0.9472804781917173 and parameters: {'weight_lgbm_class_0': 0.14567377975565166, 'weight_lgbm_class_1': 0.6490661498850336, 'weight_lgbm_class_2': 0.6550646122565181, 'weight_xgb_class_0': 0.09967868340472118, 'weight_xgb_class_1': 0.3889481708966078, 'weight_xgb_class_2': 0.5311971168743067, 'weight_cat_class_0': 0.053119489088493496, 'weight_cat_class_1': 0.7511064117001396, 'weight_cat_class_2': 0.5315287118817097}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:36,967] Trial 1548 finished with value: 0.9488872681343233 and parameters: {'weight_lgbm_class_0': 0.14484225966109476, 'weight_lgbm_class_1': 0.5541883300200232, 'weight_lgbm_class_2': 0.658159745129649, 'weight_xgb_class_0': 6.543280989455835e-05, 'weight_xgb_class_1': 0.2560486097073312, 'weight_xgb_class_2': 0.5257269678935527, 'weight_cat_class_0': 0.05201671681448061, 'weight_cat_class_1': 0.7568758306879658, 'weight_cat_class_2': 0.3596541414671093}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  78%|█████████████████████████████████████████████████████████████████████████████████████████████████████                             | 1554/2000 [01:01<00:21, 20.82it/s]

[I 2026-07-03 10:23:37,036] Trial 1549 finished with value: 0.9436462374531533 and parameters: {'weight_lgbm_class_0': 0.14433169659815875, 'weight_lgbm_class_1': 0.5746722177760194, 'weight_lgbm_class_2': 0.9091887634474667, 'weight_xgb_class_0': 0.10339089637637158, 'weight_xgb_class_1': 0.43168710049794984, 'weight_xgb_class_2': 0.5272747620207653, 'weight_cat_class_0': 0.05228371855622503, 'weight_cat_class_1': 0.11234524081339081, 'weight_cat_class_2': 0.3228994541908137}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:37,135] Trial 1552 finished with value: 0.9478331151262234 and parameters: {'weight_lgbm_class_0': 0.14598737305868864, 'weight_lgbm_class_1': 0.8256994103830089, 'weight_lgbm_class_2': 0.691530288171127, 'weight_xgb_class_0': 0.09650246897568451, 'weight_xgb_class_1': 0.25968003659261957, 'weight_xgb_class_2': 0.5333997959246886, 'weight_cat_class_0': 0.029516358789740318, 'weight_cat_class_1': 0.7706310482061811, 'weight_cat_class_2': 0.37304897771117235}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:37,140] Trial 1550 finished with value: 0.9473994196286929 and parameters: {'weight_lgbm_class_0': 0.1461580672347939, 'weight_lgbm_class_1': 0.5277653578304885, 'weight_lgbm_class_2': 0.6101803410934614, 'weight_xgb_class_0': 0.08471685698136107, 'weight_xgb_class_1': 0.3941216356261331, 'weight_xgb_class_2': 0.5297380018800968, 'weight_cat_class_0': 0.033352756292021404, 'weight_cat_class_1': 0.7683177996108895, 'weight_cat_class_2': 0.36926643328453024}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:37,145] Trial 1551 finished with value: 0.9476682200072832 and parameters: {'weight_lgbm_class_0': 0.10444495175758559, 'weight_lgbm_class_1': 0.6442305760464739, 'weight_lgbm_class_2': 0.6091586397902832, 'weight_xgb_class_0': 0.09305690101849601, 'weight_xgb_class_1': 0.25738913441488925, 'weight_xgb_class_2': 0.5232127283766435, 'weight_cat_class_0': 0.02667001841460146, 'weight_cat_class_1': 0.7661097105193547, 'weight_cat_class_2': 0.13739439790703722}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:37,211] Trial 1553 finished with value: 0.9484823852920347 and parameters: {'weight_lgbm_class_0': 0.10325326845683236, 'weight_lgbm_class_1': 0.5272940486618969, 'weight_lgbm_class_2': 0.6146983840888494, 'weight_xgb_class_0': 0.0895078364535038, 'weight_xgb_class_1': 0.4271886750482405, 'weight_xgb_class_2': 0.5306450818069984, 'weight_cat_class_0': 0.03205780975319901, 'weight_cat_class_1': 0.7611066176380051, 'weight_cat_class_2': 0.3606472191000035}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  78%|█████████████████████████████████████████████████████████████████████████████████████████████████████▎                            | 1559/2000 [01:01<00:22, 19.34it/s]

[I 2026-07-03 10:23:37,372] Trial 1554 finished with value: 0.9483968224582671 and parameters: {'weight_lgbm_class_0': 0.1415745648546271, 'weight_lgbm_class_1': 0.8256564290075993, 'weight_lgbm_class_2': 0.7005830241513129, 'weight_xgb_class_0': 0.0963659190282718, 'weight_xgb_class_1': 0.38049607072209657, 'weight_xgb_class_2': 0.5261162993672186, 'weight_cat_class_0': 0.030004914225052116, 'weight_cat_class_1': 0.7798155192072524, 'weight_cat_class_2': 0.5754641412311597}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:37,382] Trial 1555 finished with value: 0.9487860300658855 and parameters: {'weight_lgbm_class_0': 0.10623410845499551, 'weight_lgbm_class_1': 0.8310819535510264, 'weight_lgbm_class_2': 0.9345504617664764, 'weight_xgb_class_0': 0.11538593081855042, 'weight_xgb_class_1': 0.26536153283847796, 'weight_xgb_class_2': 0.43509442649752933, 'weight_cat_class_0': 0.025781672342102064, 'weight_cat_class_1': 0.7787704885860408, 'weight_cat_class_2': 0.5567630734510302}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:37,399] Trial 1556 finished with value: 0.8871825290060755 and parameters: {'weight_lgbm_class_0': 0.48598760254095763, 'weight_lgbm_class_1': 0.82717164761722, 'weight_lgbm_class_2': 0.6135456145015855, 'weight_xgb_class_0': 0.8021149378265275, 'weight_xgb_class_1': 0.2661469964681611, 'weight_xgb_class_2': 0.4380387454830531, 'weight_cat_class_0': 0.031571445794996426, 'weight_cat_class_1': 0.7720235905312248, 'weight_cat_class_2': 0.13914989699234617}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:37,439] Trial 1557 finished with value: 0.9489085274149369 and parameters: {'weight_lgbm_class_0': 0.10376501945404193, 'weight_lgbm_class_1': 0.749535124724239, 'weight_lgbm_class_2': 0.9293319364591662, 'weight_xgb_class_0': 0.10664330174157004, 'weight_xgb_class_1': 0.28257091846691684, 'weight_xgb_class_2': 0.43657111607927007, 'weight_cat_class_0': 0.025689982421630196, 'weight_cat_class_1': 0.7795554975094043, 'weight_cat_class_2': 0.576600436873143}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:37,500] Trial 1558 finished with value: 0.9473514697581376 and parameters: {'weight_lgbm_class_0': 0.10779936787297763, 'weight_lgbm_class_1': 0.8537073588437355, 'weight_lgbm_class_2': 0.6928539477727431, 'weight_xgb_class_0': 0.10587037025929161, 'weight_xgb_class_1': 0.26666843549752295, 'weight_xgb_class_2': 0.44294988955483183, 'weight_cat_class_0': 0.030561519897071815, 'weight_cat_class_1': 0.76894111784777, 'weight_cat_class_2': 0.13915422069652056}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:37,570] Trial 1559 finished with value: 0.9488574233018222 and parameters: {'weight_lgbm_class_0': 0.021427220361366593, 'weight_lgbm_class_1': 0.854634226496537, 'weight_lgbm_class_2': 0.6073128389746676, 'weight_xgb_class_0': 0.11521312789234399, 'weight_xgb_class_1': 0.27723827427219155, 'weight_xgb_class_2': 0.4371651881789736, 'weight_cat_class_0': 0.030135301923888247, 'weight_cat_class_1': 0.7739736226255283, 'weight_cat_class_2': 0.1392424523111111}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  78%|█████████████████████████████████████████████████████████████████████████████████████████████████████▌                            | 1563/2000 [01:01<00:24, 17.51it/s]

[I 2026-07-03 10:23:37,591] Trial 1560 finished with value: 0.9467319456866184 and parameters: {'weight_lgbm_class_0': 0.10356605477890474, 'weight_lgbm_class_1': 0.6933071093846427, 'weight_lgbm_class_2': 0.611264643130223, 'weight_xgb_class_0': 0.1148430597668359, 'weight_xgb_class_1': 0.27070439145990577, 'weight_xgb_class_2': 0.4366605783814148, 'weight_cat_class_0': 0.02895364658206644, 'weight_cat_class_1': 0.7765831155304461, 'weight_cat_class_2': 0.13955566634245098}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:37,672] Trial 1561 finished with value: 0.9490330270123248 and parameters: {'weight_lgbm_class_0': 0.1053711006686734, 'weight_lgbm_class_1': 0.8291073878401956, 'weight_lgbm_class_2': 0.6160491970040705, 'weight_xgb_class_0': 0.07998397864709599, 'weight_xgb_class_1': 0.2511603527110455, 'weight_xgb_class_2': 0.43359263703095297, 'weight_cat_class_0': 0.026016292322332157, 'weight_cat_class_1': 0.7795477884252511, 'weight_cat_class_2': 0.5587656628150923}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:37,768] Trial 1562 finished with value: 0.9496955175467306 and parameters: {'weight_lgbm_class_0': 0.02129413728633805, 'weight_lgbm_class_1': 0.857577822872677, 'weight_lgbm_class_2': 0.8796727610939494, 'weight_xgb_class_0': 0.11666871172116454, 'weight_xgb_class_1': 0.5413390143178836, 'weight_xgb_class_2': 0.43231739941677577, 'weight_cat_class_0': 0.0008773902453357704, 'weight_cat_class_1': 0.7337554213487157, 'weight_cat_class_2': 0.5595678653783946}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:37,787] Trial 1564 finished with value: 0.9491357520495143 and parameters: {'weight_lgbm_class_0': 0.019036809473238034, 'weight_lgbm_class_1': 0.8561282056804451, 'weight_lgbm_class_2': 0.8857097530297773, 'weight_xgb_class_0': 0.11965532389460712, 'weight_xgb_class_1': 0.2757041848407106, 'weight_xgb_class_2': 0.43943279929914614, 'weight_cat_class_0': 0.0854484834023933, 'weight_cat_class_1': 0.7818349093297289, 'weight_cat_class_2': 0.5605827599037128}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  78%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊                            | 1567/2000 [01:02<00:21, 19.91it/s]

[I 2026-07-03 10:23:37,802] Trial 1563 finished with value: 0.9490265051997012 and parameters: {'weight_lgbm_class_0': 0.015308534589134221, 'weight_lgbm_class_1': 0.74867105556163, 'weight_lgbm_class_2': 0.6091237875047169, 'weight_xgb_class_0': 0.11814415630493363, 'weight_xgb_class_1': 0.5768229884684022, 'weight_xgb_class_2': 0.4369689746787181, 'weight_cat_class_0': 0.08477282012177939, 'weight_cat_class_1': 0.7833165699134957, 'weight_cat_class_2': 0.5811387586040597}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:37,840] Trial 1565 finished with value: 0.9300725795673218 and parameters: {'weight_lgbm_class_0': 0.035029902243071585, 'weight_lgbm_class_1': 0.6918582564627701, 'weight_lgbm_class_2': 0.9362310856282731, 'weight_xgb_class_0': 0.6804180947354316, 'weight_xgb_class_1': 0.36043928101560374, 'weight_xgb_class_2': 0.43596576784288454, 'weight_cat_class_0': 0.017776397385196208, 'weight_cat_class_1': 0.7833725319731418, 'weight_cat_class_2': 0.5809827037272706}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:38,003] Trial 1567 finished with value: 0.9376619986396371 and parameters: {'weight_lgbm_class_0': 0.021013977758028594, 'weight_lgbm_class_1': 0.6877574172610035, 'weight_lgbm_class_2': 0.887387049822813, 'weight_xgb_class_0': 0.0002495999640080123, 'weight_xgb_class_1': 0.5521271438461955, 'weight_xgb_class_2': 0.46033224242444754, 'weight_cat_class_0': 0.0010876779097982053, 'weight_cat_class_1': 0.7349357755961463, 'weight_cat_class_2': 0.5797681523533336}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:38,013] Trial 1566 finished with value: 0.9496221780729096 and parameters: {'weight_lgbm_class_0': 0.01970366429918592, 'weight_lgbm_class_1': 0.8556715063880783, 'weight_lgbm_class_2': 0.883037206150373, 'weight_xgb_class_0': 0.061514213980588976, 'weight_xgb_class_1': 0.30070230853445584, 'weight_xgb_class_2': 0.4624584522121457, 'weight_cat_class_0': 0.023242779685253873, 'weight_cat_class_1': 0.7341905404609363, 'weight_cat_class_2': 0.26761694544119685}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  79%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏                           | 1573/2000 [01:02<00:20, 20.69it/s]

[I 2026-07-03 10:23:38,053] Trial 1568 finished with value: 0.949615122013462 and parameters: {'weight_lgbm_class_0': 0.020778281816155646, 'weight_lgbm_class_1': 0.6881625273257379, 'weight_lgbm_class_2': 0.8943902449981107, 'weight_xgb_class_0': 0.06312422833888094, 'weight_xgb_class_1': 0.5500951558306336, 'weight_xgb_class_2': 0.461417041269607, 'weight_cat_class_0': 0.08238808075914913, 'weight_cat_class_1': 0.7902625565972947, 'weight_cat_class_2': 0.48141804906694996}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:38,082] Trial 1569 finished with value: 0.9495843903962808 and parameters: {'weight_lgbm_class_0': 0.019700185009070083, 'weight_lgbm_class_1': 0.8553479728453621, 'weight_lgbm_class_2': 0.9008568151231358, 'weight_xgb_class_0': 0.0001876662003438348, 'weight_xgb_class_1': 0.30235767259500945, 'weight_xgb_class_2': 0.45727281088488053, 'weight_cat_class_0': 0.08459585279532902, 'weight_cat_class_1': 0.782150877270514, 'weight_cat_class_2': 0.27124020503123114}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:38,109] Trial 1570 finished with value: 0.9495334763191292 and parameters: {'weight_lgbm_class_0': 0.026817832210371075, 'weight_lgbm_class_1': 0.691621771023134, 'weight_lgbm_class_2': 0.8882965412842755, 'weight_xgb_class_0': 0.05900064600727386, 'weight_xgb_class_1': 0.5425848390354872, 'weight_xgb_class_2': 0.46036610621730667, 'weight_cat_class_0': 0.019309994099106182, 'weight_cat_class_1': 0.7299200017317687, 'weight_cat_class_2': 0.2760265806631843}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:38,184] Trial 1571 finished with value: 0.9495752370229736 and parameters: {'weight_lgbm_class_0': 0.016773605013607217, 'weight_lgbm_class_1': 0.7499940186360233, 'weight_lgbm_class_2': 0.8914921225686792, 'weight_xgb_class_0': 0.05944751469407028, 'weight_xgb_class_1': 0.5392228457588427, 'weight_xgb_class_2': 0.46544577760567984, 'weight_cat_class_0': 0.0892931753836036, 'weight_cat_class_1': 0.6559317806644998, 'weight_cat_class_2': 0.4835269048814526}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:38,192] Trial 1572 finished with value: 0.9493729129234162 and parameters: {'weight_lgbm_class_0': 0.03539408440929867, 'weight_lgbm_class_1': 0.7528635615703543, 'weight_lgbm_class_2': 0.8821638546663007, 'weight_xgb_class_0': 0.06304832605717536, 'weight_xgb_class_1': 0.5418853324942849, 'weight_xgb_class_2': 0.4609505388791228, 'weight_cat_class_0': 0.08611557954836575, 'weight_cat_class_1': 0.7278814339453193, 'weight_cat_class_2': 0.2798319741908769}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:38,251] Trial 1573 finished with value: 0.9490954328660827 and parameters: {'weight_lgbm_class_0': 0.027155563454601205, 'weight_lgbm_class_1': 0.6893912331732168, 'weight_lgbm_class_2': 0.8912429433892894, 'weight_xgb_class_0': 0.0628626854284684, 'weight_xgb_class_1': 0.5387515344931137, 'weight_xgb_class_2': 0.4646862302993136, 'weight_cat_class_0': 0.0008533353055993397, 'weight_cat_class_1': 0.725251188623684, 'weight_cat_class_2': 0.5104600799674262}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  79%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 1578/2000 [01:02<00:20, 20.21it/s]

[I 2026-07-03 10:23:38,401] Trial 1574 finished with value: 0.9494037629806445 and parameters: {'weight_lgbm_class_0': 0.041029380483939365, 'weight_lgbm_class_1': 0.6877515569986425, 'weight_lgbm_class_2': 0.8633856235395146, 'weight_xgb_class_0': 0.05831192468490449, 'weight_xgb_class_1': 0.5453397702264443, 'weight_xgb_class_2': 0.4629666172054884, 'weight_cat_class_0': 0.0006263136402747982, 'weight_cat_class_1': 0.6558374881403334, 'weight_cat_class_2': 0.47651830391997674}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:38,420] Trial 1575 finished with value: 0.9494424926029091 and parameters: {'weight_lgbm_class_0': 0.04014198348895745, 'weight_lgbm_class_1': 0.6954390110306723, 'weight_lgbm_class_2': 0.8991284773811509, 'weight_xgb_class_0': 0.06598770411040772, 'weight_xgb_class_1': 0.3026497186773877, 'weight_xgb_class_2': 0.40529524191699123, 'weight_cat_class_0': 0.001282218438374727, 'weight_cat_class_1': 0.7288371427925042, 'weight_cat_class_2': 0.5191522079746473}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:38,453] Trial 1576 finished with value: 0.9494769806351603 and parameters: {'weight_lgbm_class_0': 0.03640506683145025, 'weight_lgbm_class_1': 0.7168361368231057, 'weight_lgbm_class_2': 0.8631278364813666, 'weight_xgb_class_0': 0.05647766500744211, 'weight_xgb_class_1': 0.3030013863367409, 'weight_xgb_class_2': 0.4635652427921037, 'weight_cat_class_0': 0.00023300440793700848, 'weight_cat_class_1': 0.7399511158024232, 'weight_cat_class_2': 0.2805179133111404}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:38,492] Trial 1577 finished with value: 0.949391513738028 and parameters: {'weight_lgbm_class_0': 0.04022662926668536, 'weight_lgbm_class_1': 0.7157055781003389, 'weight_lgbm_class_2': 0.8625041051635897, 'weight_xgb_class_0': 0.061124545737507086, 'weight_xgb_class_1': 0.3087688503882662, 'weight_xgb_class_2': 0.9992873994084872, 'weight_cat_class_0': 0.08383290833512692, 'weight_cat_class_1': 0.7395534026438059, 'weight_cat_class_2': 0.4904549370787928}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  79%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉                           | 1583/2000 [01:03<00:24, 16.97it/s]

[I 2026-07-03 10:23:38,634] Trial 1578 finished with value: 0.9479580742523949 and parameters: {'weight_lgbm_class_0': 0.03870736508357398, 'weight_lgbm_class_1': 0.7139378667176617, 'weight_lgbm_class_2': 0.8602802703485436, 'weight_xgb_class_0': 0.17317618136866386, 'weight_xgb_class_1': 0.5444052961351216, 'weight_xgb_class_2': 0.4611608140064475, 'weight_cat_class_0': 0.08515514642202188, 'weight_cat_class_1': 0.8003116154842134, 'weight_cat_class_2': 0.5055715710158839}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:38,665] Trial 1579 finished with value: 0.9406789758107834 and parameters: {'weight_lgbm_class_0': 0.04145503608993016, 'weight_lgbm_class_1': 0.7476550933910525, 'weight_lgbm_class_2': 0.8462091279704458, 'weight_xgb_class_0': 0.42940293698636484, 'weight_xgb_class_1': 0.45311172764569785, 'weight_xgb_class_2': 0.46503872410438085, 'weight_cat_class_0': 0.015626873383375036, 'weight_cat_class_1': 0.6586700048293075, 'weight_cat_class_2': 0.4899480616496222}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:38,737] Trial 1581 finished with value: 0.9493523340114872 and parameters: {'weight_lgbm_class_0': 0.04622398602612229, 'weight_lgbm_class_1': 0.7485007597578625, 'weight_lgbm_class_2': 0.8628438320112224, 'weight_xgb_class_0': 0.038076683100901926, 'weight_xgb_class_1': 0.4605457773441165, 'weight_xgb_class_2': 0.4032155329804829, 'weight_cat_class_0': 0.014319740261387416, 'weight_cat_class_1': 0.807387098019591, 'weight_cat_class_2': 0.5220655248739888}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:38,758] Trial 1580 finished with value: 0.9489130324737937 and parameters: {'weight_lgbm_class_0': 0.050707947530588604, 'weight_lgbm_class_1': 0.7472301734904464, 'weight_lgbm_class_2': 0.8712165972018943, 'weight_xgb_class_0': 0.032617360866859395, 'weight_xgb_class_1': 0.4557295307037287, 'weight_xgb_class_2': 0.40576368852638306, 'weight_cat_class_0': 0.0009727443745703114, 'weight_cat_class_1': 0.8064049429882104, 'weight_cat_class_2': 0.5217405019374937}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:38,776] Trial 1582 finished with value: 0.948721023844359 and parameters: {'weight_lgbm_class_0': 0.04366585922932137, 'weight_lgbm_class_1': 0.7439894844435151, 'weight_lgbm_class_2': 0.8510757873685231, 'weight_xgb_class_0': 0.030897805011640623, 'weight_xgb_class_1': 0.44607628143525835, 'weight_xgb_class_2': 0.4055465972095937, 'weight_cat_class_0': 0.0012249306154085606, 'weight_cat_class_1': 0.8016238337121787, 'weight_cat_class_2': 0.48822571148222793}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:38,834] Trial 1583 finished with value: 0.9492082194338467 and parameters: {'weight_lgbm_class_0': 0.04819251464563551, 'weight_lgbm_class_1': 0.7136869310818912, 'weight_lgbm_class_2': 0.8608890747966677, 'weight_xgb_class_0': 0.03511986744375866, 'weight_xgb_class_1': 0.45320423658784104, 'weight_xgb_class_2': 0.468494965828871, 'weight_cat_class_0': 0.012575169515255606, 'weight_cat_class_1': 0.8128374914586045, 'weight_cat_class_2': 0.5087888708833467}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  79%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏                          | 1587/2000 [01:03<00:20, 20.49it/s]

[I 2026-07-03 10:23:38,852] Trial 1584 finished with value: 0.9485997811823469 and parameters: {'weight_lgbm_class_0': 0.043008652313075324, 'weight_lgbm_class_1': 0.7196915072599583, 'weight_lgbm_class_2': 0.8605744645842404, 'weight_xgb_class_0': 0.029289013791495032, 'weight_xgb_class_1': 0.461506174151628, 'weight_xgb_class_2': 0.40334759077350446, 'weight_cat_class_0': 0.000416257241650439, 'weight_cat_class_1': 0.8112496680556549, 'weight_cat_class_2': 0.4907178320295703}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:38,858] Trial 1585 finished with value: 0.9486482386815869 and parameters: {'weight_lgbm_class_0': 0.04082291426131389, 'weight_lgbm_class_1': 0.7198641487695437, 'weight_lgbm_class_2': 0.8550972467904536, 'weight_xgb_class_0': 0.034508758319269354, 'weight_xgb_class_1': 0.5130754885247689, 'weight_xgb_class_2': 0.4102267785223889, 'weight_cat_class_0': 0.0002896342577034458, 'weight_cat_class_1': 0.8060833603287326, 'weight_cat_class_2': 0.5212786975084582}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:39,029] Trial 1587 finished with value: 0.9488823049815106 and parameters: {'weight_lgbm_class_0': 0.04453356108241088, 'weight_lgbm_class_1': 0.7185752198679092, 'weight_lgbm_class_2': 0.9997520709089326, 'weight_xgb_class_0': 0.02860120057163876, 'weight_xgb_class_1': 0.4516341086102016, 'weight_xgb_class_2': 0.403894633828677, 'weight_cat_class_0': 0.016655386367705444, 'weight_cat_class_1': 0.8068281563585185, 'weight_cat_class_2': 0.6025541955926934}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:39,039] Trial 1586 finished with value: 0.9497359953831666 and parameters: {'weight_lgbm_class_0': 0.09181521448780214, 'weight_lgbm_class_1': 0.776186579408551, 'weight_lgbm_class_2': 0.7632566487271024, 'weight_xgb_class_0': 0.03207556463631356, 'weight_xgb_class_1': 0.44448586849457344, 'weight_xgb_class_2': 0.41126805916452674, 'weight_cat_class_0': 0.016566303068235037, 'weight_cat_class_1': 0.8052848693180659, 'weight_cat_class_2': 0.4532991387263511}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:39,102] Trial 1588 finished with value: 0.9497169405096709 and parameters: {'weight_lgbm_class_0': 0.08550777574754952, 'weight_lgbm_class_1': 0.8096631299450316, 'weight_lgbm_class_2': 0.850325622869612, 'weight_xgb_class_0': 0.03511558852177841, 'weight_xgb_class_1': 0.45014318112523194, 'weight_xgb_class_2': 0.4074055555640101, 'weight_cat_class_0': 0.018675513136109143, 'weight_cat_class_1': 0.8251733139976758, 'weight_cat_class_2': 0.6103093267527999}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:39,117] Trial 1589 finished with value: 0.9496932183906591 and parameters: {'weight_lgbm_class_0': 0.08230928089796093, 'weight_lgbm_class_1': 0.8049765065314777, 'weight_lgbm_class_2': 0.8470472241990568, 'weight_xgb_class_0': 0.03647542167026826, 'weight_xgb_class_1': 0.45294610687573134, 'weight_xgb_class_2': 0.4011414848810279, 'weight_cat_class_0': 0.00019104193180546902, 'weight_cat_class_1': 0.7980283794389291, 'weight_cat_class_2': 0.507328743380203}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:39,269] Trial 1590 finished with value: 0.9495617961952751 and parameters: {'weight_lgbm_class_0': 0.08113669306571192, 'weight_lgbm_class_1': 0.6064744886762294, 'weight_lgbm_class_2': 0.9839376865618858, 'weight_xgb_class_0': 0.03522988965498624, 'weight_xgb_class_1': 0.45997617693184495, 'weight_xgb_class_2': 0.4043940378436045, 'weight_cat_class_0': 0.016070036691265492, 'weight_cat_class_1': 0.8061750672142395, 'weight_cat_class_2': 0.6127623407883285}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋                          | 1595/2000 [01:03<00:24, 16.39it/s]

[I 2026-07-03 10:23:39,286] Trial 1591 finished with value: 0.9496316639511688 and parameters: {'weight_lgbm_class_0': 0.08536523097878179, 'weight_lgbm_class_1': 0.6651857052829113, 'weight_lgbm_class_2': 0.9174127083370232, 'weight_xgb_class_0': 0.0325091674230657, 'weight_xgb_class_1': 0.575367795953241, 'weight_xgb_class_2': 0.4063152885908372, 'weight_cat_class_0': 0.01776822802569998, 'weight_cat_class_1': 0.8096535799007007, 'weight_cat_class_2': 0.6120782830547142}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:39,393] Trial 1592 finished with value: 0.9496282598326541 and parameters: {'weight_lgbm_class_0': 0.08488752005074023, 'weight_lgbm_class_1': 0.6612689545501269, 'weight_lgbm_class_2': 0.6298615105803249, 'weight_xgb_class_0': 0.03211245326751514, 'weight_xgb_class_1': 0.5760330082887323, 'weight_xgb_class_2': 0.4227724267334517, 'weight_cat_class_0': 0.03503792847077738, 'weight_cat_class_1': 0.46378215643406895, 'weight_cat_class_2': 0.6059716783525677}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:39,395] Trial 1593 finished with value: 0.9496178648048682 and parameters: {'weight_lgbm_class_0': 0.08267580393338941, 'weight_lgbm_class_1': 0.5990736990797242, 'weight_lgbm_class_2': 0.6360157421525966, 'weight_xgb_class_0': 0.031878693666201004, 'weight_xgb_class_1': 0.5097967638164378, 'weight_xgb_class_2': 0.4113261471088439, 'weight_cat_class_0': 0.03930993828504598, 'weight_cat_class_1': 0.8212151659783741, 'weight_cat_class_2': 0.5465970870629495}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:39,433] Trial 1594 finished with value: 0.9497452388153498 and parameters: {'weight_lgbm_class_0': 0.07754514162912965, 'weight_lgbm_class_1': 0.6652092660132011, 'weight_lgbm_class_2': 0.6322452317796238, 'weight_xgb_class_0': 0.03153941867595319, 'weight_xgb_class_1': 0.5074747568736744, 'weight_xgb_class_2': 0.41133021505733924, 'weight_cat_class_0': 0.03123914299873021, 'weight_cat_class_1': 0.8211782560223124, 'weight_cat_class_2': 0.5969338252383557}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:39,506] Trial 1595 finished with value: 0.9497591985624734 and parameters: {'weight_lgbm_class_0': 0.08830215006101659, 'weight_lgbm_class_1': 0.6116844997998601, 'weight_lgbm_class_2': 0.6339502645495874, 'weight_xgb_class_0': 0.018799743789122136, 'weight_xgb_class_1': 0.5110203569372055, 'weight_xgb_class_2': 0.5095824964003772, 'weight_cat_class_0': 0.038578648828142104, 'weight_cat_class_1': 0.8215572895293861, 'weight_cat_class_2': 0.600069268031209}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████                          | 1600/2000 [01:03<00:20, 19.52it/s]

[I 2026-07-03 10:23:39,534] Trial 1597 finished with value: 0.9407832320176004 and parameters: {'weight_lgbm_class_0': 0.08765360350430906, 'weight_lgbm_class_1': 0.8082641426137634, 'weight_lgbm_class_2': 0.7585883007513509, 'weight_xgb_class_0': 0.14886576304957502, 'weight_xgb_class_1': 0.5090034635667768, 'weight_xgb_class_2': 0.5071678782903443, 'weight_cat_class_0': 0.28994229940720107, 'weight_cat_class_1': 0.8905709386980015, 'weight_cat_class_2': 0.44934555337486876}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:39,550] Trial 1596 finished with value: 0.9495730457540744 and parameters: {'weight_lgbm_class_0': 0.08778947078296764, 'weight_lgbm_class_1': 0.6623426956652805, 'weight_lgbm_class_2': 0.6362729159495946, 'weight_xgb_class_0': 0.02115213643702195, 'weight_xgb_class_1': 0.33243516940056583, 'weight_xgb_class_2': 0.5071614843522613, 'weight_cat_class_0': 0.03885235518941767, 'weight_cat_class_1': 0.7438879401715591, 'weight_cat_class_2': 0.5480218310632793}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:39,689] Trial 1600 finished with value: 0.9495939257344048 and parameters: {'weight_lgbm_class_0': 0.11876970272668778, 'weight_lgbm_class_1': 0.6070870245765293, 'weight_lgbm_class_2': 0.6326634310412584, 'weight_xgb_class_0': 0.0008480312895376807, 'weight_xgb_class_1': 0.5743524851876877, 'weight_xgb_class_2': 0.5034793371494345, 'weight_cat_class_0': 0.0375401245010957, 'weight_cat_class_1': 0.891753818009649, 'weight_cat_class_2': 0.39319427989481287}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:39,690] Trial 1598 finished with value: 0.9496217058614467 and parameters: {'weight_lgbm_class_0': 0.08255998963738803, 'weight_lgbm_class_1': 0.6623493875645619, 'weight_lgbm_class_2': 0.922634042510193, 'weight_xgb_class_0': 0.017327650030962, 'weight_xgb_class_1': 0.5778121455003731, 'weight_xgb_class_2': 0.509822045712094, 'weight_cat_class_0': 0.04072052573685127, 'weight_cat_class_1': 0.8949590017081777, 'weight_cat_class_2': 0.6126852834029406}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:39,707] Trial 1599 finished with value: 0.9497668958949145 and parameters: {'weight_lgbm_class_0': 0.0852766454871508, 'weight_lgbm_class_1': 0.600052190420401, 'weight_lgbm_class_2': 0.6249856982429818, 'weight_xgb_class_0': 0.016447696904096143, 'weight_xgb_class_1': 0.5770618446338814, 'weight_xgb_class_2': 0.5065563685799083, 'weight_cat_class_0': 0.03935823397279919, 'weight_cat_class_1': 0.7472581908507702, 'weight_cat_class_2': 0.60300764120408}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                         | 1603/2000 [01:04<00:21, 18.49it/s]

[I 2026-07-03 10:23:39,729] Trial 1601 finished with value: 0.9396016294480298 and parameters: {'weight_lgbm_class_0': 0.12008264809649846, 'weight_lgbm_class_1': 0.6012478633631296, 'weight_lgbm_class_2': 0.6363526815166877, 'weight_xgb_class_0': 0.019562976230668355, 'weight_xgb_class_1': 0.5685662764207006, 'weight_xgb_class_2': 0.510869765240391, 'weight_cat_class_0': 0.3200079525683308, 'weight_cat_class_1': 0.745580367400457, 'weight_cat_class_2': 0.2386057310899539}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:39,883] Trial 1602 finished with value: 0.947020958291851 and parameters: {'weight_lgbm_class_0': 0.12004362785394929, 'weight_lgbm_class_1': 0.7758895053914426, 'weight_lgbm_class_2': 0.6293368804228452, 'weight_xgb_class_0': 0.14992032360416555, 'weight_xgb_class_1': 0.2370659670422547, 'weight_xgb_class_2': 0.507208128226876, 'weight_cat_class_0': 0.04219179020936392, 'weight_cat_class_1': 0.8887945452413617, 'weight_cat_class_2': 0.5433361193112562}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:39,917] Trial 1603 finished with value: 0.9494938518365998 and parameters: {'weight_lgbm_class_0': 0.1213325999312267, 'weight_lgbm_class_1': 0.782104212942642, 'weight_lgbm_class_2': 0.6730284878963333, 'weight_xgb_class_0': 0.015567243625411382, 'weight_xgb_class_1': 0.5102294954393243, 'weight_xgb_class_2': 0.5063700834122778, 'weight_cat_class_0': 0.04135722966306768, 'weight_cat_class_1': 0.8939488654566656, 'weight_cat_class_2': 0.5444689218457419}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋                         | 1610/2000 [01:04<00:18, 21.03it/s]

[I 2026-07-03 10:23:40,068] Trial 1604 finished with value: 0.9469858076294465 and parameters: {'weight_lgbm_class_0': 0.11615630696889517, 'weight_lgbm_class_1': 0.66227230376946, 'weight_lgbm_class_2': 0.6358125241922536, 'weight_xgb_class_0': 0.1428260004957907, 'weight_xgb_class_1': 0.5125751789540993, 'weight_xgb_class_2': 0.41970099455044035, 'weight_cat_class_0': 0.06093195177521701, 'weight_cat_class_1': 0.8546906045560041, 'weight_cat_class_2': 0.5766796467048325}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:40,077] Trial 1605 finished with value: 0.9471575249788544 and parameters: {'weight_lgbm_class_0': 0.11128909042091581, 'weight_lgbm_class_1': 0.6753481763738156, 'weight_lgbm_class_2': 0.6265523169117432, 'weight_xgb_class_0': 0.1439417924082115, 'weight_xgb_class_1': 0.5227891403115126, 'weight_xgb_class_2': 0.42755351744525494, 'weight_cat_class_0': 0.06429952590074187, 'weight_cat_class_1': 0.8931105590953643, 'weight_cat_class_2': 0.592123781543382}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:40,109] Trial 1607 finished with value: 0.94904197285337 and parameters: {'weight_lgbm_class_0': 0.06377054319511201, 'weight_lgbm_class_1': 0.6265371490530752, 'weight_lgbm_class_2': 0.628654924920349, 'weight_xgb_class_0': 0.07853599825296076, 'weight_xgb_class_1': 0.5265009163965217, 'weight_xgb_class_2': 0.4237098804886791, 'weight_cat_class_0': 0.07385054163048152, 'weight_cat_class_1': 0.8581849893383777, 'weight_cat_class_2': 0.5856336583311657}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:40,126] Trial 1606 finished with value: 0.9493110979962469 and parameters: {'weight_lgbm_class_0': 0.11994973280975756, 'weight_lgbm_class_1': 0.6496792654587259, 'weight_lgbm_class_2': 0.6370025269618194, 'weight_xgb_class_0': 0.0008102938233694166, 'weight_xgb_class_1': 0.5120941942582864, 'weight_xgb_class_2': 0.4192591020119901, 'weight_cat_class_0': 0.06586159157124837, 'weight_cat_class_1': 0.8890956572871568, 'weight_cat_class_2': 0.5800527017094319}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:40,163] Trial 1609 finished with value: 0.9491516977639458 and parameters: {'weight_lgbm_class_0': 0.06251859617032815, 'weight_lgbm_class_1': 0.6154048858277786, 'weight_lgbm_class_2': 0.6309074218133095, 'weight_xgb_class_0': 0.07879023547999961, 'weight_xgb_class_1': 0.5125471924019005, 'weight_xgb_class_2': 0.4252282258657271, 'weight_cat_class_0': 0.06269530815709012, 'weight_cat_class_1': 0.854654091144966, 'weight_cat_class_2': 0.5937726869594562}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:40,191] Trial 1608 finished with value: 0.949027905288559 and parameters: {'weight_lgbm_class_0': 0.06494706797404767, 'weight_lgbm_class_1': 0.5886285658894705, 'weight_lgbm_class_2': 0.6305052202829493, 'weight_xgb_class_0': 0.08170827815362854, 'weight_xgb_class_1': 0.5266630790261989, 'weight_xgb_class_2': 0.42305935939726785, 'weight_cat_class_0': 0.07144025121635589, 'weight_cat_class_1': 0.8524437123785261, 'weight_cat_class_2': 0.5919527492601735}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                         | 1616/2000 [01:04<00:18, 21.15it/s]

[I 2026-07-03 10:23:40,331] Trial 1610 finished with value: 0.9492094904376218 and parameters: {'weight_lgbm_class_0': 0.058604327380726795, 'weight_lgbm_class_1': 0.590279675290718, 'weight_lgbm_class_2': 0.6701955005220046, 'weight_xgb_class_0': 0.07253889088363041, 'weight_xgb_class_1': 0.5998965507922365, 'weight_xgb_class_2': 0.42742474509763934, 'weight_cat_class_0': 0.06811405594634834, 'weight_cat_class_1': 0.8303248470712772, 'weight_cat_class_2': 0.576093742995811}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:40,339] Trial 1612 finished with value: 0.9204107421514026 and parameters: {'weight_lgbm_class_0': 0.7089476888378254, 'weight_lgbm_class_1': 0.5539340013754871, 'weight_lgbm_class_2': 0.6278535615518405, 'weight_xgb_class_0': 0.08505314696667679, 'weight_xgb_class_1': 0.5694816942624221, 'weight_xgb_class_2': 0.3589956835734529, 'weight_cat_class_0': 0.0674531515142415, 'weight_cat_class_1': 0.8308395190258228, 'weight_cat_class_2': 0.5903818263798959}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:40,350] Trial 1611 finished with value: 0.9491865580749258 and parameters: {'weight_lgbm_class_0': 0.057657250807268634, 'weight_lgbm_class_1': 0.5506860425770861, 'weight_lgbm_class_2': 0.6627485288825781, 'weight_xgb_class_0': 0.07974924887820517, 'weight_xgb_class_1': 0.6232399390454862, 'weight_xgb_class_2': 0.4242042756916185, 'weight_cat_class_0': 0.06997191697160357, 'weight_cat_class_1': 0.8276344367479227, 'weight_cat_class_2': 0.5945861296931242}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:40,372] Trial 1613 finished with value: 0.9491862453542678 and parameters: {'weight_lgbm_class_0': 0.06130420432109387, 'weight_lgbm_class_1': 0.5901921178098462, 'weight_lgbm_class_2': 0.6691190591035797, 'weight_xgb_class_0': 0.07697702886543155, 'weight_xgb_class_1': 0.6017133011229687, 'weight_xgb_class_2': 0.8643009880207639, 'weight_cat_class_0': 0.08403480098971361, 'weight_cat_class_1': 0.8311236377211406, 'weight_cat_class_2': 0.5883255346392542}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:40,479] Trial 1614 finished with value: 0.9493770558939106 and parameters: {'weight_lgbm_class_0': 0.0559921973235272, 'weight_lgbm_class_1': 0.5856507337524555, 'weight_lgbm_class_2': 0.6673754143752831, 'weight_xgb_class_0': 0.07828028997528834, 'weight_xgb_class_1': 0.5906895233860893, 'weight_xgb_class_2': 0.8870670004836998, 'weight_cat_class_0': 0.06845095440180993, 'weight_cat_class_1': 0.82780588473014, 'weight_cat_class_2': 0.5863730863883345}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:40,514] Trial 1615 finished with value: 0.9490470657954142 and parameters: {'weight_lgbm_class_0': 0.05935409583852612, 'weight_lgbm_class_1': 0.5782007165644616, 'weight_lgbm_class_2': 0.6718043340899029, 'weight_xgb_class_0': 0.0813319097323332, 'weight_xgb_class_1': 0.6057127132669103, 'weight_xgb_class_2': 0.3651449922339, 'weight_cat_class_0': 0.07126986768905505, 'weight_cat_class_1': 0.824582734497672, 'weight_cat_class_2': 0.6086507268196959}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▎                        | 1621/2000 [01:05<00:21, 17.80it/s]

[I 2026-07-03 10:23:40,678] Trial 1617 finished with value: 0.9486778369576103 and parameters: {'weight_lgbm_class_0': 0.06002626341808561, 'weight_lgbm_class_1': 0.581041806995064, 'weight_lgbm_class_2': 0.6629094092824416, 'weight_xgb_class_0': 0.07300354072082509, 'weight_xgb_class_1': 0.6021245615344649, 'weight_xgb_class_2': 0.04149346160664624, 'weight_cat_class_0': 0.06916920715724997, 'weight_cat_class_1': 0.8282454233598682, 'weight_cat_class_2': 0.5901802587153179}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:40,731] Trial 1616 finished with value: 0.9490599692923888 and parameters: {'weight_lgbm_class_0': 0.06016660317499049, 'weight_lgbm_class_1': 0.5632317114079808, 'weight_lgbm_class_2': 0.6664303291788651, 'weight_xgb_class_0': 0.08249234827804303, 'weight_xgb_class_1': 0.6024632609694187, 'weight_xgb_class_2': 0.3709272516348452, 'weight_cat_class_0': 0.06901788754658081, 'weight_cat_class_1': 0.8270078564108813, 'weight_cat_class_2': 0.5978324103465852}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:40,737] Trial 1619 finished with value: 0.949118371422176 and parameters: {'weight_lgbm_class_0': 0.06126843099437772, 'weight_lgbm_class_1': 0.583212461905476, 'weight_lgbm_class_2': 0.6720439108434771, 'weight_xgb_class_0': 0.0779257768688387, 'weight_xgb_class_1': 0.5860308763359028, 'weight_xgb_class_2': 0.38350683440172884, 'weight_cat_class_0': 0.07200609795696919, 'weight_cat_class_1': 0.8282013620570121, 'weight_cat_class_2': 0.6314105520997474}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:40,752] Trial 1618 finished with value: 0.9490665190025896 and parameters: {'weight_lgbm_class_0': 0.0602136249304798, 'weight_lgbm_class_1': 0.5795075717441956, 'weight_lgbm_class_2': 0.676409771617461, 'weight_xgb_class_0': 0.08124657495555028, 'weight_xgb_class_1': 0.6158006394525343, 'weight_xgb_class_2': 0.37811904911524874, 'weight_cat_class_0': 0.06935815434301706, 'weight_cat_class_1': 0.8294161087212131, 'weight_cat_class_2': 0.6014316660950753}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:40,756] Trial 1620 finished with value: 0.9491614569027943 and parameters: {'weight_lgbm_class_0': 0.0606274005723604, 'weight_lgbm_class_1': 0.5527820811743916, 'weight_lgbm_class_2': 0.6820378808013531, 'weight_xgb_class_0': 0.05765261867671191, 'weight_xgb_class_1': 0.586986173524723, 'weight_xgb_class_2': 0.35778832390642706, 'weight_cat_class_0': 0.08762907187380414, 'weight_cat_class_1': 0.8273988034070046, 'weight_cat_class_2': 0.6305664872505133}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:40,804] Trial 1621 finished with value: 0.9486281278605486 and parameters: {'weight_lgbm_class_0': 0.058053838351969866, 'weight_lgbm_class_1': 0.5965921874081694, 'weight_lgbm_class_2': 0.6726840149530455, 'weight_xgb_class_0': 0.06135404987672231, 'weight_xgb_class_1': 0.6105951950765031, 'weight_xgb_class_2': 0.039787940763563234, 'weight_cat_class_0': 0.09296826729733726, 'weight_cat_class_1': 0.8300943029682594, 'weight_cat_class_2': 0.6283516169403512}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊                        | 1627/2000 [01:05<00:19, 19.46it/s]

[I 2026-07-03 10:23:40,955] Trial 1622 finished with value: 0.9491339972172614 and parameters: {'weight_lgbm_class_0': 0.06896811151010923, 'weight_lgbm_class_1': 0.5788815746239859, 'weight_lgbm_class_2': 0.649499988504155, 'weight_xgb_class_0': 0.05386246621314191, 'weight_xgb_class_1': 0.5868173806309954, 'weight_xgb_class_2': 0.45029786567045327, 'weight_cat_class_0': 0.09179674452473706, 'weight_cat_class_1': 0.826779641657749, 'weight_cat_class_2': 0.618841621288904}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:40,996] Trial 1623 finished with value: 0.9489778826277208 and parameters: {'weight_lgbm_class_0': 0.05512009948355459, 'weight_lgbm_class_1': 0.5779271454814802, 'weight_lgbm_class_2': 0.5966230167599198, 'weight_xgb_class_0': 0.05711921516215325, 'weight_xgb_class_1': 0.5929831161809779, 'weight_xgb_class_2': 0.4405021626146257, 'weight_cat_class_0': 0.10494644564513667, 'weight_cat_class_1': 0.7535388134896024, 'weight_cat_class_2': 0.6051649777357795}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:41,025] Trial 1624 finished with value: 0.9495208730295531 and parameters: {'weight_lgbm_class_0': 0.0037492887352960688, 'weight_lgbm_class_1': 0.6080240997404757, 'weight_lgbm_class_2': 0.6532336516021072, 'weight_xgb_class_0': 0.051621640763352974, 'weight_xgb_class_1': 0.6267426794571763, 'weight_xgb_class_2': 0.3689587071293915, 'weight_cat_class_0': 0.04989322377804474, 'weight_cat_class_1': 0.7105527946901896, 'weight_cat_class_2': 0.6254944609554264}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:41,087] Trial 1625 finished with value: 0.9495166983811464 and parameters: {'weight_lgbm_class_0': 4.1297018109960615e-05, 'weight_lgbm_class_1': 0.6212298098139072, 'weight_lgbm_class_2': 0.6032293395562954, 'weight_xgb_class_0': 0.05060741049473482, 'weight_xgb_class_1': 0.6255824950985442, 'weight_xgb_class_2': 0.38591960009790305, 'weight_cat_class_0': 0.05346401126541875, 'weight_cat_class_1': 0.7422214315905279, 'weight_cat_class_2': 0.6197651579638406}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:41,099] Trial 1626 finished with value: 0.9494766432084739 and parameters: {'weight_lgbm_class_0': 0.005384976491877063, 'weight_lgbm_class_1': 0.5663745772231605, 'weight_lgbm_class_2': 0.610956517894166, 'weight_xgb_class_0': 0.05364452659658199, 'weight_xgb_class_1': 0.6219753221075309, 'weight_xgb_class_2': 0.37429280498597006, 'weight_cat_class_0': 0.1035445689287432, 'weight_cat_class_1': 0.70917074349554, 'weight_cat_class_2': 0.6152513071374811}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:41,131] Trial 1627 finished with value: 0.9487203107027063 and parameters: {'weight_lgbm_class_0': 0.07242505194564124, 'weight_lgbm_class_1': 0.5630099640548581, 'weight_lgbm_class_2': 0.6036212050080529, 'weight_xgb_class_0': 0.056253984051420014, 'weight_xgb_class_1': 0.5668823721024333, 'weight_xgb_class_2': 0.37981894103093505, 'weight_cat_class_0': 0.09487622268461776, 'weight_cat_class_1': 0.7127488087808821, 'weight_cat_class_2': 0.5649764860760078}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▏                       | 1633/2000 [01:05<00:18, 19.35it/s]

[I 2026-07-03 10:23:41,327] Trial 1628 finished with value: 0.949667489563959 and parameters: {'weight_lgbm_class_0': 0.004964287001502262, 'weight_lgbm_class_1': 0.62270932147879, 'weight_lgbm_class_2': 0.6021612306978681, 'weight_xgb_class_0': 0.05242528074926428, 'weight_xgb_class_1': 0.5566967249490178, 'weight_xgb_class_2': 0.39085336947087645, 'weight_cat_class_0': 0.09264822915219964, 'weight_cat_class_1': 0.7549520024063582, 'weight_cat_class_2': 0.6129904637936809}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:41,334] Trial 1630 finished with value: 0.9494885950066353 and parameters: {'weight_lgbm_class_0': 0.013100873580289066, 'weight_lgbm_class_1': 0.6188611153612211, 'weight_lgbm_class_2': 0.6182702024734662, 'weight_xgb_class_0': 0.05139790366558308, 'weight_xgb_class_1': 0.6490435573610618, 'weight_xgb_class_2': 0.44531164624372827, 'weight_cat_class_0': 0.09966326835402041, 'weight_cat_class_1': 0.7061663094156232, 'weight_cat_class_2': 0.6187337354597297}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:41,376] Trial 1629 finished with value: 0.9495809057485896 and parameters: {'weight_lgbm_class_0': 0.0006076042662420955, 'weight_lgbm_class_1': 0.6092783578757346, 'weight_lgbm_class_2': 0.6076680221800469, 'weight_xgb_class_0': 0.04284848098737032, 'weight_xgb_class_1': 0.5685108162570042, 'weight_xgb_class_2': 0.5409681704446079, 'weight_cat_class_0': 0.11422731902210673, 'weight_cat_class_1': 0.7478884106670678, 'weight_cat_class_2': 0.6141742319776701}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:41,428] Trial 1631 finished with value: 0.9495559251544895 and parameters: {'weight_lgbm_class_0': 0.005729416743814733, 'weight_lgbm_class_1': 0.6171072339602589, 'weight_lgbm_class_2': 0.6115033330176916, 'weight_xgb_class_0': 0.05376466088952282, 'weight_xgb_class_1': 0.5235857605935543, 'weight_xgb_class_2': 0.4505838404528318, 'weight_cat_class_0': 0.046282193101131915, 'weight_cat_class_1': 0.7170511515711518, 'weight_cat_class_2': 0.6223682023252012}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:41,431] Trial 1632 finished with value: 0.9491998234522124 and parameters: {'weight_lgbm_class_0': 0.09435784839514755, 'weight_lgbm_class_1': 0.6178872789305201, 'weight_lgbm_class_2': 0.5955131769166574, 'weight_xgb_class_0': 0.05198327396616518, 'weight_xgb_class_1': 0.559785302287931, 'weight_xgb_class_2': 0.44608247388783906, 'weight_cat_class_0': 0.04849835154943557, 'weight_cat_class_1': 0.7152566937324302, 'weight_cat_class_2': 0.5598578136428662}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:41,472] Trial 1633 finished with value: 0.949418962845149 and parameters: {'weight_lgbm_class_0': 0.005122174954882889, 'weight_lgbm_class_1': 0.6228905300377344, 'weight_lgbm_class_2': 0.610130369871532, 'weight_xgb_class_0': 0.045880345125641285, 'weight_xgb_class_1': 0.5511254866320482, 'weight_xgb_class_2': 0.44438845782340086, 'weight_cat_class_0': 0.04408428586232479, 'weight_cat_class_1': 0.7177354601829127, 'weight_cat_class_2': 0.5570097762476472}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:41,574] Trial 1634 finished with value: 0.9494030748302689 and parameters: {'weight_lgbm_class_0': 0.0008530565962621209, 'weight_lgbm_class_1': 0.620389860242817, 'weight_lgbm_class_2': 0.6376918296563017, 'weight_xgb_class_0': 0.047094748805133035, 'weight_xgb_class_1': 0.5601493523267812, 'weight_xgb_class_2': 0.44324442761372573, 'weight_cat_class_0': 0.04869046111195195, 'weight_cat_class_1': 0.7244372644961697, 'weight_cat_class_2': 0.567171899794713}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:41,615] Trial 1635 finished with value: 0.9491458129633091 and parameters: {'weight_lgbm_class_0': 0.097987558328855, 'weight_lgbm_class_1': 0.6050142730102193, 'weight_lgbm_class_2': 0.5962319724903073, 'weight_xgb_class_0': 0.045844546680772834, 'weight_xgb_class_1': 0.5609794276693388, 'weight_xgb_class_2': 0.3921811411041421, 'weight_cat_class_0': 0.049352764662463924, 'weight_cat_class_1': 0.7229453927132707, 'weight_cat_class_2': 0.5610352265457865}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:41,672] Trial 1636 finished with value: 0.9493860310639723 and parameters: {'weight_lgbm_class_0': 0.09631472387828742, 'weight_lgbm_class_1': 0.6380771639810532, 'weight_lgbm_class_2': 0.6047949652343627, 'weight_xgb_class_0': 0.04167316335216083, 'weight_xgb_class_1': 0.5644093113899942, 'weight_xgb_class_2': 0.5389608289160185, 'weight_cat_class_0': 0.04103150091653794, 'weight_cat_class_1': 0.7200351450657944, 'weight_cat_class_2': 0.5654970908933303}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:41,717] Trial 1638 finished with value: 0.9496016141283282 and parameters: {'weight_lgbm_class_0': 0.09458018983393635, 'weight_lgbm_class_1': 0.610624818065722, 'weight_lgbm_class_2': 0.5951088786409828, 'weight_xgb_class_0': 0.01852490461078292, 'weight_xgb_class_1': 0.5288194618662322, 'weight_xgb_class_2': 0.4422175631486535, 'weight_cat_class_0': 0.04396444827925606, 'weight_cat_class_1': 0.9991092154953719, 'weight_cat_class_2': 0.5648984389287983}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:41,768] Trial 1639 finished with value: 0.9495875334127323 and parameters: {'weight_lgbm_class_0': 0.09620595722612531, 'weight_lgbm_class_1': 0.6238614498047413, 'weight_lgbm_class_2': 0.6066817658923713, 'weight_xgb_class_0': 0.019914302993173087, 'weight_xgb_class_1': 0.5581556315269226, 'weight_xgb_class_2': 0.4443279638197642, 'weight_cat_class_0': 0.041067386321775604, 'weight_cat_class_1': 0.7946918882772244, 'weight_cat_class_2': 0.5643332415519734}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:41,772] Trial 1637 finished with value: 0.9496931636978085 and parameters: {'weight_lgbm_class_0': 0.09412810630782656, 'weight_lgbm_class_1': 0.6242074129783292, 'weight_lgbm_class_2': 0.6044502628026579, 'weight_xgb_class_0': 0.019716897397641237, 'weight_xgb_class_1': 0.5461484029553579, 'weight_xgb_class_2': 0.39809658937039993, 'weight_cat_class_0': 0.03717511003016304, 'weight_cat_class_1': 0.7884660710845792, 'weight_cat_class_2': 0.608132572008658}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                       | 1644/2000 [01:06<00:21, 16.66it/s]

[I 2026-07-03 10:23:41,908] Trial 1640 finished with value: 0.9495770597191417 and parameters: {'weight_lgbm_class_0': 0.0954856338193394, 'weight_lgbm_class_1': 0.6417619675890573, 'weight_lgbm_class_2': 0.6447857233701387, 'weight_xgb_class_0': 0.020434806556386322, 'weight_xgb_class_1': 0.5476847489391089, 'weight_xgb_class_2': 0.4446472335601015, 'weight_cat_class_0': 0.044649453087334465, 'weight_cat_class_1': 0.7883802121472586, 'weight_cat_class_2': 0.5650215655271065}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:42,008] Trial 1641 finished with value: 0.9494670604582388 and parameters: {'weight_lgbm_class_0': 0.09622876392771477, 'weight_lgbm_class_1': 0.6102059873293186, 'weight_lgbm_class_2': 0.5969113654720507, 'weight_xgb_class_0': 0.021770439839675724, 'weight_xgb_class_1': 0.5490445919544542, 'weight_xgb_class_2': 0.44753906008454547, 'weight_cat_class_0': 0.049474133986039455, 'weight_cat_class_1': 0.789722937078957, 'weight_cat_class_2': 0.5624649488511481}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:42,017] Trial 1642 finished with value: 0.9496305169867342 and parameters: {'weight_lgbm_class_0': 0.09483943531287342, 'weight_lgbm_class_1': 0.5725313847457866, 'weight_lgbm_class_2': 0.6972124357587691, 'weight_xgb_class_0': 0.019761579285275874, 'weight_xgb_class_1': 0.54444278502773, 'weight_xgb_class_2': 0.44810499998469777, 'weight_cat_class_0': 0.042608592034040584, 'weight_cat_class_1': 0.7914284527448272, 'weight_cat_class_2': 0.557475433392727}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:42,037] Trial 1643 finished with value: 0.949554376219862 and parameters: {'weight_lgbm_class_0': 0.1000794042181644, 'weight_lgbm_class_1': 0.6326573539246997, 'weight_lgbm_class_2': 0.5889011612429335, 'weight_xgb_class_0': 0.01926712614876417, 'weight_xgb_class_1': 0.543940571934279, 'weight_xgb_class_2': 0.540558936441392, 'weight_cat_class_0': 0.04503224494682831, 'weight_cat_class_1': 0.7978894734654974, 'weight_cat_class_2': 0.5701609906164453}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:42,104] Trial 1644 finished with value: 0.9497737836355498 and parameters: {'weight_lgbm_class_0': 0.09081129965970099, 'weight_lgbm_class_1': 0.6081378582151243, 'weight_lgbm_class_2': 0.6997179760870819, 'weight_xgb_class_0': 0.01930022343801722, 'weight_xgb_class_1': 0.5410644694898907, 'weight_xgb_class_2': 0.4684387822735112, 'weight_cat_class_0': 0.03712261606191546, 'weight_cat_class_1': 0.7896398581732565, 'weight_cat_class_2': 0.5589647702065043}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████                       | 1648/2000 [01:06<00:18, 19.48it/s]

[I 2026-07-03 10:23:42,149] Trial 1645 finished with value: 0.9496960969745286 and parameters: {'weight_lgbm_class_0': 0.09632544111253089, 'weight_lgbm_class_1': 0.6369580059493063, 'weight_lgbm_class_2': 0.6419826306638743, 'weight_xgb_class_0': 0.017295410377713052, 'weight_xgb_class_1': 0.5421654543472276, 'weight_xgb_class_2': 0.40824620079253365, 'weight_cat_class_0': 0.037655958825016454, 'weight_cat_class_1': 0.7913873938036031, 'weight_cat_class_2': 0.5730154721822796}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:42,166] Trial 1646 finished with value: 0.9496445647083412 and parameters: {'weight_lgbm_class_0': 0.09737337382009738, 'weight_lgbm_class_1': 0.6369320094203834, 'weight_lgbm_class_2': 0.7024022498703822, 'weight_xgb_class_0': 0.0211126274138857, 'weight_xgb_class_1': 0.5330493181007627, 'weight_xgb_class_2': 0.40056185059425164, 'weight_cat_class_0': 0.036888753153749995, 'weight_cat_class_1': 0.7878957308724216, 'weight_cat_class_2': 0.5681321043208327}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:42,209] Trial 1647 finished with value: 0.9490913815635033 and parameters: {'weight_lgbm_class_0': 0.032709609125587694, 'weight_lgbm_class_1': 0.6335218703551092, 'weight_lgbm_class_2': 0.6959163158120203, 'weight_xgb_class_0': 0.019676730711511086, 'weight_xgb_class_1': 0.5341414932656973, 'weight_xgb_class_2': 0.4208530570736086, 'weight_cat_class_0': 0.03306632791328693, 'weight_cat_class_1': 0.7920370383015262, 'weight_cat_class_2': 0.5718197607036284}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:42,339] Trial 1648 finished with value: 0.9496729017342324 and parameters: {'weight_lgbm_class_0': 0.07958833740825313, 'weight_lgbm_class_1': 0.6265467564613514, 'weight_lgbm_class_2': 0.6449862470229135, 'weight_xgb_class_0': 0.01691575059212926, 'weight_xgb_class_1': 0.5404219332700713, 'weight_xgb_class_2': 0.47272960275442416, 'weight_cat_class_0': 0.029376728549292904, 'weight_cat_class_1': 0.7890026659074749, 'weight_cat_class_2': 0.5802272429198156}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                      | 1653/2000 [01:06<00:18, 19.27it/s]

[I 2026-07-03 10:23:42,350] Trial 1649 finished with value: 0.9492266120758094 and parameters: {'weight_lgbm_class_0': 0.03372922430744898, 'weight_lgbm_class_1': 0.6372337550055889, 'weight_lgbm_class_2': 0.6389104603266094, 'weight_xgb_class_0': 0.024293508823191902, 'weight_xgb_class_1': 0.5405267045536312, 'weight_xgb_class_2': 0.46876792854810956, 'weight_cat_class_0': 0.03367420560727821, 'weight_cat_class_1': 0.7993186903688636, 'weight_cat_class_2': 0.5778947585427883}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:42,378] Trial 1651 finished with value: 0.9488617831880607 and parameters: {'weight_lgbm_class_0': 0.03088195352425191, 'weight_lgbm_class_1': 0.6343996585497996, 'weight_lgbm_class_2': 0.6875773920391468, 'weight_xgb_class_0': 0.017570709568096657, 'weight_xgb_class_1': 0.5320928343709406, 'weight_xgb_class_2': 0.4701524096120397, 'weight_cat_class_0': 0.029957111946668096, 'weight_cat_class_1': 0.7902792314293992, 'weight_cat_class_2': 0.5451976099087575}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:42,382] Trial 1650 finished with value: 0.9497331543216565 and parameters: {'weight_lgbm_class_0': 0.07766326886463643, 'weight_lgbm_class_1': 0.5988035823225404, 'weight_lgbm_class_2': 0.6434154778216558, 'weight_xgb_class_0': 0.02113098706834158, 'weight_xgb_class_1': 0.5435979840464817, 'weight_xgb_class_2': 0.47163726780909654, 'weight_cat_class_0': 0.0336009451484048, 'weight_cat_class_1': 0.790819357392767, 'weight_cat_class_2': 0.5870392600641295}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:42,536] Trial 1652 finished with value: 0.9488569964672827 and parameters: {'weight_lgbm_class_0': 0.03300718576447064, 'weight_lgbm_class_1': 0.6416377553549724, 'weight_lgbm_class_2': 0.7016130123085976, 'weight_xgb_class_0': 0.01698739569271114, 'weight_xgb_class_1': 0.5398662585510415, 'weight_xgb_class_2': 0.4679806619994356, 'weight_cat_class_0': 0.02848471995141405, 'weight_cat_class_1': 0.7706330876122831, 'weight_cat_class_2': 0.5375060520809984}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 1658/2000 [01:07<00:18, 18.44it/s]

[I 2026-07-03 10:23:42,645] Trial 1653 finished with value: 0.9495367400781799 and parameters: {'weight_lgbm_class_0': 0.043380754488030526, 'weight_lgbm_class_1': 0.6378996014898652, 'weight_lgbm_class_2': 0.6455252008377705, 'weight_xgb_class_0': 0.032387405262620406, 'weight_xgb_class_1': 0.5268737361684077, 'weight_xgb_class_2': 0.4658793849094337, 'weight_cat_class_0': 0.029411176256219983, 'weight_cat_class_1': 0.768536822387442, 'weight_cat_class_2': 0.5826734898133027}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:42,646] Trial 1654 finished with value: 0.9147731744804014 and parameters: {'weight_lgbm_class_0': 0.03681061874856, 'weight_lgbm_class_1': 0.596743212540021, 'weight_lgbm_class_2': 0.5658244234797074, 'weight_xgb_class_0': 0.8613019884882331, 'weight_xgb_class_1': 0.5084650047124549, 'weight_xgb_class_2': 0.4705521128502501, 'weight_cat_class_0': 0.026717331730404952, 'weight_cat_class_1': 0.7664099605651534, 'weight_cat_class_2': 0.5788525752739703}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:42,705] Trial 1655 finished with value: 0.9488325012325084 and parameters: {'weight_lgbm_class_0': 0.035770759367104686, 'weight_lgbm_class_1': 0.596289668502965, 'weight_lgbm_class_2': 0.6284994949757264, 'weight_xgb_class_0': 0.12391342996861798, 'weight_xgb_class_1': 0.5334547333258576, 'weight_xgb_class_2': 0.4162688651584416, 'weight_cat_class_0': 0.06053393626615264, 'weight_cat_class_1': 0.7676411227183668, 'weight_cat_class_2': 0.5436490757001835}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:42,710] Trial 1656 finished with value: 0.9494461869773 and parameters: {'weight_lgbm_class_0': 0.07617355190041636, 'weight_lgbm_class_1': 0.5950829602924267, 'weight_lgbm_class_2': 0.6905963609472746, 'weight_xgb_class_0': 0.03568475978970162, 'weight_xgb_class_1': 0.5270052590680693, 'weight_xgb_class_2': 0.41054213393225547, 'weight_cat_class_0': 0.06069888586567719, 'weight_cat_class_1': 0.7655636793567991, 'weight_cat_class_2': 0.5388018863315414}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:42,810] Trial 1657 finished with value: 0.9494833502454321 and parameters: {'weight_lgbm_class_0': 0.07468644734905666, 'weight_lgbm_class_1': 0.592140255888964, 'weight_lgbm_class_2': 0.6856382039986842, 'weight_xgb_class_0': 0.035331005328547056, 'weight_xgb_class_1': 0.5295800132028395, 'weight_xgb_class_2': 0.4681219245206437, 'weight_cat_class_0': 0.06398637934096381, 'weight_cat_class_1': 0.7609090993530654, 'weight_cat_class_2': 0.5361541880368116}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:42,815] Trial 1659 finished with value: 0.9487133316927764 and parameters: {'weight_lgbm_class_0': 0.07630352966017272, 'weight_lgbm_class_1': 0.6004401658104555, 'weight_lgbm_class_2': 0.7294633171821306, 'weight_xgb_class_0': 0.035510775728278585, 'weight_xgb_class_1': 0.5314087671813074, 'weight_xgb_class_2': 0.46930382528147635, 'weight_cat_class_0': 0.12909322147891383, 'weight_cat_class_1': 0.774307016721414, 'weight_cat_class_2': 0.527337407908624}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 1662/2000 [01:07<00:18, 18.51it/s]

[I 2026-07-03 10:23:42,836] Trial 1658 finished with value: 0.9494545813986345 and parameters: {'weight_lgbm_class_0': 0.07923303766170883, 'weight_lgbm_class_1': 0.5995791098820795, 'weight_lgbm_class_2': 0.7216931626523978, 'weight_xgb_class_0': 0.03359923530491056, 'weight_xgb_class_1': 0.573247351660314, 'weight_xgb_class_2': 0.47170339355387253, 'weight_cat_class_0': 0.06627311652539163, 'weight_cat_class_1': 0.7506411597864132, 'weight_cat_class_2': 0.5344944291975602}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:43,004] Trial 1661 finished with value: 0.9487361083657478 and parameters: {'weight_lgbm_class_0': 0.07319223026926061, 'weight_lgbm_class_1': 0.5937449450608974, 'weight_lgbm_class_2': 0.6905527717488406, 'weight_xgb_class_0': 0.10493214553347259, 'weight_xgb_class_1': 0.5760188005434104, 'weight_xgb_class_2': 0.4237751912311398, 'weight_cat_class_0': 0.057887029709028176, 'weight_cat_class_1': 0.7615736361077069, 'weight_cat_class_2': 0.5326764174398488}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:43,011] Trial 1660 finished with value: 0.9490287648623923 and parameters: {'weight_lgbm_class_0': 0.07316153393100774, 'weight_lgbm_class_1': 0.5719945509434704, 'weight_lgbm_class_2': 0.9444265377481824, 'weight_xgb_class_0': 0.09974634613474179, 'weight_xgb_class_1': 0.5747647230946694, 'weight_xgb_class_2': 0.4205010026555535, 'weight_cat_class_0': 0.06166046818583355, 'weight_cat_class_1': 0.7637780269234854, 'weight_cat_class_2': 0.5284125129406368}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                     | 1665/2000 [01:07<00:17, 19.19it/s]

[I 2026-07-03 10:23:43,085] Trial 1663 finished with value: 0.9437511021181 and parameters: {'weight_lgbm_class_0': 0.30067318012037125, 'weight_lgbm_class_1': 0.6582485991457114, 'weight_lgbm_class_2': 0.6193358804226391, 'weight_xgb_class_0': 0.038074966885559794, 'weight_xgb_class_1': 0.5107262431923447, 'weight_xgb_class_2': 0.4226241187204328, 'weight_cat_class_0': 0.06693025967642327, 'weight_cat_class_1': 0.7638016031929534, 'weight_cat_class_2': 0.5454312575781617}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:43,093] Trial 1662 finished with value: 0.9486393638448102 and parameters: {'weight_lgbm_class_0': 0.07841982171993248, 'weight_lgbm_class_1': 0.648029715042947, 'weight_lgbm_class_2': 0.7143859352403628, 'weight_xgb_class_0': 0.10512851329326522, 'weight_xgb_class_1': 0.5711694956158906, 'weight_xgb_class_2': 0.4279021642613539, 'weight_cat_class_0': 0.060527627956535934, 'weight_cat_class_1': 0.7614760630498475, 'weight_cat_class_2': 0.5279337347247846}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:43,158] Trial 1664 finished with value: 0.9486619515541378 and parameters: {'weight_lgbm_class_0': 0.07599399346241947, 'weight_lgbm_class_1': 0.5536019967688652, 'weight_lgbm_class_2': 0.7490412386796015, 'weight_xgb_class_0': 0.10154935952532504, 'weight_xgb_class_1': 0.5765928807994373, 'weight_xgb_class_2': 0.42734175334328317, 'weight_cat_class_0': 0.06300729391422777, 'weight_cat_class_1': 0.7619094866924018, 'weight_cat_class_2': 0.5089055175241503}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                     | 1670/2000 [01:07<00:16, 19.41it/s]

[I 2026-07-03 10:23:43,303] Trial 1665 finished with value: 0.9484490329903968 and parameters: {'weight_lgbm_class_0': 0.07569103505009614, 'weight_lgbm_class_1': 0.559724298475562, 'weight_lgbm_class_2': 0.6215397401014374, 'weight_xgb_class_0': 0.10376265092560065, 'weight_xgb_class_1': 0.5668154179382097, 'weight_xgb_class_2': 0.4194770686853244, 'weight_cat_class_0': 0.06149207518934011, 'weight_cat_class_1': 0.7522209576149066, 'weight_cat_class_2': 0.5307787955957474}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:43,321] Trial 1666 finished with value: 0.9470265698652103 and parameters: {'weight_lgbm_class_0': 0.0754326689266109, 'weight_lgbm_class_1': 0.5381744725441897, 'weight_lgbm_class_2': 0.6240594950991158, 'weight_xgb_class_0': 0.10187233338857675, 'weight_xgb_class_1': 0.5821392212816234, 'weight_xgb_class_2': 0.4235030642997068, 'weight_cat_class_0': 0.12407518162993078, 'weight_cat_class_1': 0.7484278462374021, 'weight_cat_class_2': 0.5298757182045991}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:43,356] Trial 1667 finished with value: 0.9479388010244677 and parameters: {'weight_lgbm_class_0': 0.07430590703912976, 'weight_lgbm_class_1': 0.6002363542989475, 'weight_lgbm_class_2': 0.7243763032720112, 'weight_xgb_class_0': 0.10132057789785544, 'weight_xgb_class_1': 0.5671878114936248, 'weight_xgb_class_2': 0.9350815390221715, 'weight_cat_class_0': 0.1253835702115566, 'weight_cat_class_1': 0.7537376032326749, 'weight_cat_class_2': 0.510585068121217}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:43,364] Trial 1668 finished with value: 0.9484176135056321 and parameters: {'weight_lgbm_class_0': 0.07650620242768827, 'weight_lgbm_class_1': 0.5732563908421365, 'weight_lgbm_class_2': 0.7471159448374438, 'weight_xgb_class_0': 0.09665503118348062, 'weight_xgb_class_1': 0.5680567075610246, 'weight_xgb_class_2': 0.4296890085649404, 'weight_cat_class_0': 0.08208235359583188, 'weight_cat_class_1': 0.7462525353321555, 'weight_cat_class_2': 0.530636630370136}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:43,442] Trial 1670 finished with value: 0.9416565893481703 and parameters: {'weight_lgbm_class_0': 0.29912244495058055, 'weight_lgbm_class_1': 0.5598489334956334, 'weight_lgbm_class_2': 0.7488045173448785, 'weight_xgb_class_0': 0.10407018163139148, 'weight_xgb_class_1': 0.5750655486292681, 'weight_xgb_class_2': 0.4255453319517857, 'weight_cat_class_0': 0.07880739387111126, 'weight_cat_class_1': 0.7554037191352247, 'weight_cat_class_2': 0.6397868439865562}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:43,454] Trial 1669 finished with value: 0.9485638477537993 and parameters: {'weight_lgbm_class_0': 0.07436568369100391, 'weight_lgbm_class_1': 0.541220260698887, 'weight_lgbm_class_2': 0.6209616641988239, 'weight_xgb_class_0': 0.0982156855119097, 'weight_xgb_class_1': 0.5709377513296316, 'weight_xgb_class_2': 0.4301679318634485, 'weight_cat_class_0': 0.058045485736849714, 'weight_cat_class_1': 0.7433960967676594, 'weight_cat_class_2': 0.5160387443520947}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                     | 1673/2000 [01:07<00:16, 19.43it/s]

[I 2026-07-03 10:23:43,524] Trial 1671 finished with value: 0.9489272584290358 and parameters: {'weight_lgbm_class_0': 0.04809463708605623, 'weight_lgbm_class_1': 0.5834183216072933, 'weight_lgbm_class_2': 0.7486280283535003, 'weight_xgb_class_0': 0.09873096730783268, 'weight_xgb_class_1': 0.5676232252690477, 'weight_xgb_class_2': 0.41976530113649213, 'weight_cat_class_0': 0.0773611213026509, 'weight_cat_class_1': 0.7460357469829993, 'weight_cat_class_2': 0.5181158071743031}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:43,597] Trial 1672 finished with value: 0.9490910043630402 and parameters: {'weight_lgbm_class_0': 0.05029687299939711, 'weight_lgbm_class_1': 0.5536169076770006, 'weight_lgbm_class_2': 0.7300484588690043, 'weight_xgb_class_0': 0.07391636969025034, 'weight_xgb_class_1': 0.511009943327836, 'weight_xgb_class_2': 0.44709374174935773, 'weight_cat_class_0': 0.08359502654357916, 'weight_cat_class_1': 0.7386910804670427, 'weight_cat_class_2': 0.5032378318236984}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:43,631] Trial 1673 finished with value: 0.9490294347371119 and parameters: {'weight_lgbm_class_0': 0.05169820321466197, 'weight_lgbm_class_1': 0.5680881172779982, 'weight_lgbm_class_2': 0.6551553249124273, 'weight_xgb_class_0': 0.06538012062851384, 'weight_xgb_class_1': 0.5116578705321424, 'weight_xgb_class_2': 0.43212931551416367, 'weight_cat_class_0': 0.08913751040398431, 'weight_cat_class_1': 0.7502077589544546, 'weight_cat_class_2': 0.4960843313206564}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████                     | 1678/2000 [01:08<00:19, 16.68it/s]

[I 2026-07-03 10:23:43,754] Trial 1674 finished with value: 0.9051827313407625 and parameters: {'weight_lgbm_class_0': 0.9371556991769325, 'weight_lgbm_class_1': 0.5323282770133734, 'weight_lgbm_class_2': 0.6587532089700663, 'weight_xgb_class_0': 0.06873871872350401, 'weight_xgb_class_1': 0.5051079957285805, 'weight_xgb_class_2': 0.44209872227839314, 'weight_cat_class_0': 0.08387120239204948, 'weight_cat_class_1': 0.7426576544338928, 'weight_cat_class_2': 0.49990527437401755}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:43,783] Trial 1675 finished with value: 0.9489264957966633 and parameters: {'weight_lgbm_class_0': 0.05186227163342521, 'weight_lgbm_class_1': 0.65226396379841, 'weight_lgbm_class_2': 0.566232517012351, 'weight_xgb_class_0': 0.06774623751839401, 'weight_xgb_class_1': 0.4921846647917094, 'weight_xgb_class_2': 0.43400734868584556, 'weight_cat_class_0': 0.08526236963892904, 'weight_cat_class_1': 0.7422046940442242, 'weight_cat_class_2': 0.4878797013979094}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:43,803] Trial 1676 finished with value: 0.9491453630057166 and parameters: {'weight_lgbm_class_0': 0.050064508489858495, 'weight_lgbm_class_1': 0.550388449504293, 'weight_lgbm_class_2': 0.5694386231012829, 'weight_xgb_class_0': 0.06938697638642405, 'weight_xgb_class_1': 0.49926170639695877, 'weight_xgb_class_2': 0.4451822932245894, 'weight_cat_class_0': 0.08211402540003848, 'weight_cat_class_1': 0.7360514627434681, 'weight_cat_class_2': 0.6416525977873109}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:43,942] Trial 1677 finished with value: 0.9491704745067796 and parameters: {'weight_lgbm_class_0': 0.04905237346256759, 'weight_lgbm_class_1': 0.603788820303776, 'weight_lgbm_class_2': 0.5734987639429031, 'weight_xgb_class_0': 0.060222417380182316, 'weight_xgb_class_1': 0.4932046288548654, 'weight_xgb_class_2': 0.44942007847784693, 'weight_cat_class_0': 0.09075640756673381, 'weight_cat_class_1': 0.7365434636260443, 'weight_cat_class_2': 0.6417818570240379}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:43,961] Trial 1678 finished with value: 0.9492617007926176 and parameters: {'weight_lgbm_class_0': 0.04538788646136517, 'weight_lgbm_class_1': 0.6035298699182706, 'weight_lgbm_class_2': 0.6546659392692183, 'weight_xgb_class_0': 0.06182435536028907, 'weight_xgb_class_1': 0.506998123024628, 'weight_xgb_class_2': 0.44798891136519503, 'weight_cat_class_0': 0.07948974910115211, 'weight_cat_class_1': 0.6818460376006283, 'weight_cat_class_2': 0.6334644650566156}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:43,990] Trial 1680 finished with value: 0.9466608492320129 and parameters: {'weight_lgbm_class_0': 0.04971075305084452, 'weight_lgbm_class_1': 0.6241214689659462, 'weight_lgbm_class_2': 0.5636580938897595, 'weight_xgb_class_0': 0.06314807720423932, 'weight_xgb_class_1': 0.5086791600514874, 'weight_xgb_class_2': 0.44766489454118413, 'weight_cat_class_0': 0.1953034813665711, 'weight_cat_class_1': 0.8068466798637713, 'weight_cat_class_2': 0.47298731631499336}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:44,020] Trial 1679 finished with value: 0.9487949349662171 and parameters: {'weight_lgbm_class_0': 0.04805109648346781, 'weight_lgbm_class_1': 0.6091534110794506, 'weight_lgbm_class_2': 0.9806949696560184, 'weight_xgb_class_0': 0.06324286379061757, 'weight_xgb_class_1': 0.5090789221585538, 'weight_xgb_class_2': 0.4918730454803927, 'weight_cat_class_0': 0.09079774654011113, 'weight_cat_class_1': 0.6817040348911596, 'weight_cat_class_2': 0.04024118061318012}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:44,055] Trial 1681 finished with value: 0.9493432587026325 and parameters: {'weight_lgbm_class_0': 0.04666124051758318, 'weight_lgbm_class_1': 0.6014909631182931, 'weight_lgbm_class_2': 0.9793956529952568, 'weight_xgb_class_0': 0.0668600754521633, 'weight_xgb_class_1': 0.5136798997904487, 'weight_xgb_class_2': 0.44866154147158216, 'weight_cat_class_0': 0.08704502158631436, 'weight_cat_class_1': 0.811753831583895, 'weight_cat_class_2': 0.4740636667029565}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:44,106] Trial 1682 finished with value: 0.9497347285245693 and parameters: {'weight_lgbm_class_0': 0.04577505405839286, 'weight_lgbm_class_1': 0.6233884741406892, 'weight_lgbm_class_2': 0.5857490876278627, 'weight_xgb_class_0': 0.059973433317006185, 'weight_xgb_class_1': 0.5034718594649371, 'weight_xgb_class_2': 0.49044517805569016, 'weight_cat_class_0': 0.02174759071952533, 'weight_cat_class_1': 0.8015941663820653, 'weight_cat_class_2': 0.4864993283165071}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                    | 1686/2000 [01:08<00:15, 19.64it/s]

[I 2026-07-03 10:23:44,191] Trial 1683 finished with value: 0.9497124151322569 and parameters: {'weight_lgbm_class_0': 0.05464145622919027, 'weight_lgbm_class_1': 0.6048908856406385, 'weight_lgbm_class_2': 0.6667646203349388, 'weight_xgb_class_0': 0.06401160338501402, 'weight_xgb_class_1': 0.5065425353698708, 'weight_xgb_class_2': 0.44982128034206387, 'weight_cat_class_0': 0.019803219032619064, 'weight_cat_class_1': 0.6911634302227727, 'weight_cat_class_2': 0.4765925118285939}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:44,245] Trial 1684 finished with value: 0.9497130993092703 and parameters: {'weight_lgbm_class_0': 0.04809890776306113, 'weight_lgbm_class_1': 0.6528061961487927, 'weight_lgbm_class_2': 0.5708787044411602, 'weight_xgb_class_0': 0.061891551770880876, 'weight_xgb_class_1': 0.5052497270186839, 'weight_xgb_class_2': 0.4903075529495892, 'weight_cat_class_0': 0.024172115448794926, 'weight_cat_class_1': 0.6860878642822281, 'weight_cat_class_2': 0.48138944964411506}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:44,287] Trial 1685 finished with value: 0.9496988803287733 and parameters: {'weight_lgbm_class_0': 0.046804641678857395, 'weight_lgbm_class_1': 0.6434123846555195, 'weight_lgbm_class_2': 0.5678396442771108, 'weight_xgb_class_0': 0.0599851297648088, 'weight_xgb_class_1': 0.5052932687929121, 'weight_xgb_class_2': 0.4854422934458685, 'weight_cat_class_0': 0.018785034437903116, 'weight_cat_class_1': 0.8131376915401024, 'weight_cat_class_2': 0.47419629984510675}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:44,397] Trial 1686 finished with value: 0.949503793185368 and parameters: {'weight_lgbm_class_0': 0.02574068241822644, 'weight_lgbm_class_1': 0.612346356666234, 'weight_lgbm_class_2': 0.975761764792358, 'weight_xgb_class_0': 0.05513328398875246, 'weight_xgb_class_1': 0.4903859574569098, 'weight_xgb_class_2': 0.48900936860800015, 'weight_cat_class_0': 0.017057190542540058, 'weight_cat_class_1': 0.8114462409036223, 'weight_cat_class_2': 0.12039261544378926}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:44,466] Trial 1688 finished with value: 0.9489321703850767 and parameters: {'weight_lgbm_class_0': 0.028506375938278324, 'weight_lgbm_class_1': 0.608104496357624, 'weight_lgbm_class_2': 0.9848711869158661, 'weight_xgb_class_0': 0.04485030553316008, 'weight_xgb_class_1': 0.5104366558854384, 'weight_xgb_class_2': 0.4862032831072008, 'weight_cat_class_0': 0.018329113260299307, 'weight_cat_class_1': 0.6818958793889008, 'weight_cat_class_2': 0.6011983321484106}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:44,502] Trial 1687 finished with value: 0.9488585840550332 and parameters: {'weight_lgbm_class_0': 0.020992606495495898, 'weight_lgbm_class_1': 0.6049915626639266, 'weight_lgbm_class_2': 0.9759837827346975, 'weight_xgb_class_0': 0.04785273051940347, 'weight_xgb_class_1': 0.5119704513100695, 'weight_xgb_class_2': 0.4911853314462026, 'weight_cat_class_0': 0.02206281624537439, 'weight_cat_class_1': 0.8115932402026699, 'weight_cat_class_2': 0.591383786439536}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:44,604] Trial 1691 finished with value: 0.9485858350256544 and parameters: {'weight_lgbm_class_0': 0.022326999934748758, 'weight_lgbm_class_1': 0.6184743649303841, 'weight_lgbm_class_2': 0.9101890243237659, 'weight_xgb_class_0': 0.03908589076140598, 'weight_xgb_class_1': 0.4855075800090822, 'weight_xgb_class_2': 0.4889656914861949, 'weight_cat_class_0': 0.018748419294150012, 'weight_cat_class_1': 0.8131352950597963, 'weight_cat_class_2': 0.6024081409663785}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:44,612] Trial 1689 finished with value: 0.9491625117601336 and parameters: {'weight_lgbm_class_0': 0.02535855888626143, 'weight_lgbm_class_1': 0.6559925547852034, 'weight_lgbm_class_2': 0.9305595358618105, 'weight_xgb_class_0': 0.0396010422174579, 'weight_xgb_class_1': 0.5174231419487294, 'weight_xgb_class_2': 0.4871265430998281, 'weight_cat_class_0': 0.01708195434747205, 'weight_cat_class_1': 0.812964359687467, 'weight_cat_class_2': 0.03820852853036247}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:44,626] Trial 1690 finished with value: 0.9474937005661187 and parameters: {'weight_lgbm_class_0': 0.025740516885312918, 'weight_lgbm_class_1': 0.6236092039572485, 'weight_lgbm_class_2': 0.6575168830836372, 'weight_xgb_class_0': 0.0002645913419075691, 'weight_xgb_class_1': 0.36609082970935625, 'weight_xgb_class_2': 0.485524152836174, 'weight_cat_class_0': 0.016369706018179532, 'weight_cat_class_1': 0.8132727218230587, 'weight_cat_class_2': 0.033419883762245785}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:44,662] Trial 1693 finished with value: 0.9485976369650415 and parameters: {'weight_lgbm_class_0': 0.025380852720815757, 'weight_lgbm_class_1': 0.6475201726770337, 'weight_lgbm_class_2': 0.9429391114888055, 'weight_xgb_class_0': 0.17558018483457993, 'weight_xgb_class_1': 0.3572796425339028, 'weight_xgb_class_2': 0.4920698516044626, 'weight_cat_class_0': 0.019883440313826828, 'weight_cat_class_1': 0.7840287075046518, 'weight_cat_class_2': 0.08578649960835859}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:44,689] Trial 1692 finished with value: 0.9496294466273186 and parameters: {'weight_lgbm_class_0': 0.10379023325229611, 'weight_lgbm_class_1': 0.6582588536856745, 'weight_lgbm_class_2': 0.9418151480940911, 'weight_xgb_class_0': 0.04096329832198591, 'weight_xgb_class_1': 0.548497518675454, 'weight_xgb_class_2': 0.48755401969719686, 'weight_cat_class_0': 0.019247418865909287, 'weight_cat_class_1': 0.7826821029461958, 'weight_cat_class_2': 0.6077032069818863}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:44,754] Trial 1694 finished with value: 0.9493334279089586 and parameters: {'weight_lgbm_class_0': 0.023804622198335755, 'weight_lgbm_class_1': 0.6505099972404068, 'weight_lgbm_class_2': 0.9182645924495582, 'weight_xgb_class_0': 0.0374940613149506, 'weight_xgb_class_1': 0.3578522267234293, 'weight_xgb_class_2': 0.48859361101263343, 'weight_cat_class_0': 0.022974186221663, 'weight_cat_class_1': 0.7780645614971394, 'weight_cat_class_2': 0.07675324114384789}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:44,844] Trial 1695 finished with value: 0.9491419958058133 and parameters: {'weight_lgbm_class_0': 0.02621825124182165, 'weight_lgbm_class_1': 0.6175392034676306, 'weight_lgbm_class_2': 0.9096432039723377, 'weight_xgb_class_0': 0.17213509605421348, 'weight_xgb_class_1': 0.5427857361935723, 'weight_xgb_class_2': 0.48697707324092443, 'weight_cat_class_0': 0.02068828224490531, 'weight_cat_class_1': 0.7830696835394158, 'weight_cat_class_2': 0.5972623076991262}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:44,888] Trial 1696 finished with value: 0.9494999194229109 and parameters: {'weight_lgbm_class_0': 0.020733746206975122, 'weight_lgbm_class_1': 0.6451803785479319, 'weight_lgbm_class_2': 0.9451569940256043, 'weight_xgb_class_0': 0.036487325725318445, 'weight_xgb_class_1': 0.36153508498243225, 'weight_xgb_class_2': 0.07020318156733757, 'weight_cat_class_0': 0.04311887515284061, 'weight_cat_class_1': 0.7770806064302633, 'weight_cat_class_2': 0.6037937153239681}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:44,917] Trial 1697 finished with value: 0.9358608322457989 and parameters: {'weight_lgbm_class_0': 0.02841440671138057, 'weight_lgbm_class_1': 0.6574929166694775, 'weight_lgbm_class_2': 0.9425145346601305, 'weight_xgb_class_0': 0.5591546750635127, 'weight_xgb_class_1': 0.5442726329841283, 'weight_xgb_class_2': 0.39927202786115734, 'weight_cat_class_0': 0.05057252246379448, 'weight_cat_class_1': 0.7814345221800395, 'weight_cat_class_2': 0.6053838573406435}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:45,007] Trial 1698 finished with value: 0.9492165277513172 and parameters: {'weight_lgbm_class_0': 0.10532275157927116, 'weight_lgbm_class_1': 0.6665958337859529, 'weight_lgbm_class_2': 0.6442570530111204, 'weight_xgb_class_0': 0.03657236024212869, 'weight_xgb_class_1': 0.3715891198456207, 'weight_xgb_class_2': 0.3993240527640121, 'weight_cat_class_0': 0.045082062120015635, 'weight_cat_class_1': 0.7851741660843374, 'weight_cat_class_2': 0.6037567456978152}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:45,106] Trial 1700 finished with value: 0.9474889754945864 and parameters: {'weight_lgbm_class_0': 0.10110764171075136, 'weight_lgbm_class_1': 0.6571214256195095, 'weight_lgbm_class_2': 0.947059495711008, 'weight_xgb_class_0': 0.13023564977267824, 'weight_xgb_class_1': 0.5485111624928312, 'weight_xgb_class_2': 0.46727941790409816, 'weight_cat_class_0': 0.042203966124525524, 'weight_cat_class_1': 0.7854533377188911, 'weight_cat_class_2': 0.08967166462612004}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:45,111] Trial 1699 finished with value: 0.9483027296524681 and parameters: {'weight_lgbm_class_0': 0.10496400388996599, 'weight_lgbm_class_1': 0.5805587349686591, 'weight_lgbm_class_2': 0.938385691805685, 'weight_xgb_class_0': 0.12517780394630146, 'weight_xgb_class_1': 0.5409427908438131, 'weight_xgb_class_2': 0.5156840844904073, 'weight_cat_class_0': 0.04800443949396651, 'weight_cat_class_1': 0.7789535446714309, 'weight_cat_class_2': 0.6077092229552776}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:45,270] Trial 1702 finished with value: 0.948036429973476 and parameters: {'weight_lgbm_class_0': 0.10570462697774666, 'weight_lgbm_class_1': 0.6664167336866063, 'weight_lgbm_class_2': 0.6293798277196658, 'weight_xgb_class_0': 0.13015495182070816, 'weight_xgb_class_1': 0.5554828089573891, 'weight_xgb_class_2': 0.5170515112045962, 'weight_cat_class_0': 0.049515852739084376, 'weight_cat_class_1': 0.784000682862012, 'weight_cat_class_2': 0.6086157158528611}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                   | 1707/2000 [01:09<00:14, 20.03it/s]

[I 2026-07-03 10:23:45,311] Trial 1701 finished with value: 0.9449235291624191 and parameters: {'weight_lgbm_class_0': 0.10503618870972745, 'weight_lgbm_class_1': 0.6671775696070171, 'weight_lgbm_class_2': 0.6224826365208935, 'weight_xgb_class_0': 0.1359637638709403, 'weight_xgb_class_1': 0.5949693908997945, 'weight_xgb_class_2': 0.4605072745408756, 'weight_cat_class_0': 0.05092903230343137, 'weight_cat_class_1': 0.7853012049204612, 'weight_cat_class_2': 0.06797522143255855}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:45,324] Trial 1704 finished with value: 0.9449134482095318 and parameters: {'weight_lgbm_class_0': 0.10451405958588982, 'weight_lgbm_class_1': 0.7361119197964964, 'weight_lgbm_class_2': 0.13491057729795392, 'weight_xgb_class_0': 0.03521001473602259, 'weight_xgb_class_1': 0.5528678913410475, 'weight_xgb_class_2': 0.5157023051665788, 'weight_cat_class_0': 0.04719068558760825, 'weight_cat_class_1': 0.7746722544363077, 'weight_cat_class_2': 0.07225702919997415}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:45,364] Trial 1705 finished with value: 0.9466809635302532 and parameters: {'weight_lgbm_class_0': 0.10480843737762195, 'weight_lgbm_class_1': 0.5775133995983318, 'weight_lgbm_class_2': 0.6223068342750753, 'weight_xgb_class_0': 0.1298063474713559, 'weight_xgb_class_1': 0.5420678563846975, 'weight_xgb_class_2': 0.3952224270463123, 'weight_cat_class_0': 0.04910643333822759, 'weight_cat_class_1': 0.40242946708807725, 'weight_cat_class_2': 0.6011351062160476}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:45,364] Trial 1703 finished with value: 0.945884245389358 and parameters: {'weight_lgbm_class_0': 0.09419467789187806, 'weight_lgbm_class_1': 0.6753661820091867, 'weight_lgbm_class_2': 0.11086071961008415, 'weight_xgb_class_0': 0.13221697641425545, 'weight_xgb_class_1': 0.5937882735135162, 'weight_xgb_class_2': 0.46586985696630484, 'weight_cat_class_0': 0.053893518646742425, 'weight_cat_class_1': 0.7884067028951541, 'weight_cat_class_2': 0.5954613100537341}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:45,377] Trial 1706 finished with value: 0.8997996107652749 and parameters: {'weight_lgbm_class_0': 0.10963219645676511, 'weight_lgbm_class_1': 0.5830593438074699, 'weight_lgbm_class_2': 0.5894666360737388, 'weight_xgb_class_0': 0.1253771311325416, 'weight_xgb_class_1': 0.5363917037276215, 'weight_xgb_class_2': 0.40173533802214023, 'weight_cat_class_0': 0.9625376235689184, 'weight_cat_class_1': 0.7770160286665774, 'weight_cat_class_2': 0.5544825375111405}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:45,483] Trial 1707 finished with value: 0.9471568053277007 and parameters: {'weight_lgbm_class_0': 0.10329961909447519, 'weight_lgbm_class_1': 0.5775668513222286, 'weight_lgbm_class_2': 0.6206453408746724, 'weight_xgb_class_0': 0.1341678555444682, 'weight_xgb_class_1': 0.5529818773260261, 'weight_xgb_class_2': 0.4011989961001574, 'weight_cat_class_0': 0.04819260824907205, 'weight_cat_class_1': 0.7886103012048137, 'weight_cat_class_2': 0.46556215022503394}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 1710/2000 [01:09<00:14, 20.33it/s]

[I 2026-07-03 10:23:45,538] Trial 1709 finished with value: 0.9495332393676197 and parameters: {'weight_lgbm_class_0': 0.10487919058548577, 'weight_lgbm_class_1': 0.5759996992615258, 'weight_lgbm_class_2': 0.6230331355989018, 'weight_xgb_class_0': 0.0004099615032646456, 'weight_xgb_class_1': 0.5556036832189327, 'weight_xgb_class_2': 0.40041042124005055, 'weight_cat_class_0': 0.04980504254803363, 'weight_cat_class_1': 0.794971200374745, 'weight_cat_class_2': 0.4600416948091052}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:45,542] Trial 1708 finished with value: 0.9356932255737186 and parameters: {'weight_lgbm_class_0': 0.549566069880367, 'weight_lgbm_class_1': 0.5807907613154446, 'weight_lgbm_class_2': 0.628203138687079, 'weight_xgb_class_0': 0.01604062874568416, 'weight_xgb_class_1': 0.5915062558810894, 'weight_xgb_class_2': 0.5146360967938379, 'weight_cat_class_0': 0.045909357289764155, 'weight_cat_class_1': 0.7904152935454253, 'weight_cat_class_2': 0.5520060702863229}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:45,648] Trial 1710 finished with value: 0.9474805957123951 and parameters: {'weight_lgbm_class_0': 0.1041042641318661, 'weight_lgbm_class_1': 0.57593316307259, 'weight_lgbm_class_2': 0.6222770681476173, 'weight_xgb_class_0': 0.1323029834832698, 'weight_xgb_class_1': 0.48196034491803624, 'weight_xgb_class_2': 0.46377017844664975, 'weight_cat_class_0': 0.05012005287702838, 'weight_cat_class_1': 0.7960870395718722, 'weight_cat_class_2': 0.5536775608897475}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                  | 1714/2000 [01:10<00:17, 16.13it/s]

[I 2026-07-03 10:23:45,746] Trial 1711 finished with value: 0.9496910279851587 and parameters: {'weight_lgbm_class_0': 0.08323615975449189, 'weight_lgbm_class_1': 0.6782214160175967, 'weight_lgbm_class_2': 0.6245796980183757, 'weight_xgb_class_0': 0.014419705933097583, 'weight_xgb_class_1': 0.5284642279569184, 'weight_xgb_class_2': 0.4643702869649351, 'weight_cat_class_0': 0.05016045342013893, 'weight_cat_class_1': 0.7989630071929033, 'weight_cat_class_2': 0.5501805962366646}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:45,748] Trial 1712 finished with value: 0.9496499945910823 and parameters: {'weight_lgbm_class_0': 0.08128583861992453, 'weight_lgbm_class_1': 0.7355007177463276, 'weight_lgbm_class_2': 0.6329158038927629, 'weight_xgb_class_0': 0.014646323051941537, 'weight_xgb_class_1': 0.48338442308564594, 'weight_xgb_class_2': 0.45929306789909236, 'weight_cat_class_0': 0.042574552753356205, 'weight_cat_class_1': 0.7951607696991063, 'weight_cat_class_2': 0.4541847469015573}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:45,914] Trial 1714 finished with value: 0.949390324954054 and parameters: {'weight_lgbm_class_0': 0.07957661032747777, 'weight_lgbm_class_1': 0.7016284450366754, 'weight_lgbm_class_2': 0.6867686672829061, 'weight_xgb_class_0': 0.012014206615180316, 'weight_xgb_class_1': 0.48137220152036364, 'weight_xgb_class_2': 0.4647807111827182, 'weight_cat_class_0': 0.000733121615751715, 'weight_cat_class_1': 0.7247410669126089, 'weight_cat_class_2': 0.45580641485425377}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:45,925] Trial 1713 finished with value: 0.949693801051497 and parameters: {'weight_lgbm_class_0': 0.0774657341902721, 'weight_lgbm_class_1': 0.7293894344137737, 'weight_lgbm_class_2': 0.621599797118584, 'weight_xgb_class_0': 0.016807035112798914, 'weight_xgb_class_1': 0.48526663629910494, 'weight_xgb_class_2': 0.4580053922097342, 'weight_cat_class_0': 0.050672553304507505, 'weight_cat_class_1': 0.8070214695725113, 'weight_cat_class_2': 0.45691800012317424}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                  | 1721/2000 [01:10<00:12, 21.79it/s]

[I 2026-07-03 10:23:45,995] Trial 1715 finished with value: 0.9489907938967422 and parameters: {'weight_lgbm_class_0': 0.07594880802391571, 'weight_lgbm_class_1': 0.7423283202564708, 'weight_lgbm_class_2': 0.5895404461027938, 'weight_xgb_class_0': 0.0012910449327559253, 'weight_xgb_class_1': 0.4826068021132042, 'weight_xgb_class_2': 0.4622040925610289, 'weight_cat_class_0': 0.00013761348250684798, 'weight_cat_class_1': 0.7293334992013252, 'weight_cat_class_2': 0.45268964406882617}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:46,024] Trial 1716 finished with value: 0.9487488004912764 and parameters: {'weight_lgbm_class_0': 0.07701957187634113, 'weight_lgbm_class_1': 0.7021410037746538, 'weight_lgbm_class_2': 0.6831224105237407, 'weight_xgb_class_0': 0.0002826001258612286, 'weight_xgb_class_1': 0.48447076027734237, 'weight_xgb_class_2': 0.45479691992510013, 'weight_cat_class_0': 0.0005257409121855947, 'weight_cat_class_1': 0.8425754803969105, 'weight_cat_class_2': 0.6380828236357453}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:46,042] Trial 1718 finished with value: 0.949745111969118 and parameters: {'weight_lgbm_class_0': 0.07825389885203847, 'weight_lgbm_class_1': 0.7023117920182554, 'weight_lgbm_class_2': 0.6494017433570446, 'weight_xgb_class_0': 0.016535582939948678, 'weight_xgb_class_1': 0.4815804670311852, 'weight_xgb_class_2': 0.45944916552219267, 'weight_cat_class_0': 0.03518669598016816, 'weight_cat_class_1': 0.7279370622158509, 'weight_cat_class_2': 0.45850259990679537}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:46,087] Trial 1717 finished with value: 0.9489211458523824 and parameters: {'weight_lgbm_class_0': 0.07462800888217044, 'weight_lgbm_class_1': 0.7011928486936069, 'weight_lgbm_class_2': 0.6751560428072366, 'weight_xgb_class_0': 0.0013683116463476842, 'weight_xgb_class_1': 0.48685227445903256, 'weight_xgb_class_2': 0.46362790022660966, 'weight_cat_class_0': 0.00044159691295653225, 'weight_cat_class_1': 0.7269668398520032, 'weight_cat_class_2': 0.45852694237825564}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:46,126] Trial 1719 finished with value: 0.9490513560002437 and parameters: {'weight_lgbm_class_0': 0.07140559692797696, 'weight_lgbm_class_1': 0.73651495527463, 'weight_lgbm_class_2': 0.6789182850447776, 'weight_xgb_class_0': 0.016017525046178323, 'weight_xgb_class_1': 0.48834261930753625, 'weight_xgb_class_2': 0.5431277014979521, 'weight_cat_class_0': 0.0008845958722007857, 'weight_cat_class_1': 0.817714994527625, 'weight_cat_class_2': 0.5500025665496373}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:46,150] Trial 1720 finished with value: 0.9497668455711853 and parameters: {'weight_lgbm_class_0': 0.07505360237093592, 'weight_lgbm_class_1': 0.7087227220943725, 'weight_lgbm_class_2': 0.5951657962092187, 'weight_xgb_class_0': 0.02150592101884207, 'weight_xgb_class_1': 0.4814625621586639, 'weight_xgb_class_2': 0.4607054728979316, 'weight_cat_class_0': 0.0333779377241531, 'weight_cat_class_1': 0.7266846638298812, 'weight_cat_class_2': 0.5527501148515984}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:46,201] Trial 1721 finished with value: 0.9496854548646471 and parameters: {'weight_lgbm_class_0': 0.07146075039582822, 'weight_lgbm_class_1': 0.7031276901008997, 'weight_lgbm_class_2': 0.6918088816026928, 'weight_xgb_class_0': 0.012572102673374268, 'weight_xgb_class_1': 0.4858481905048704, 'weight_xgb_class_2': 0.4597783017864942, 'weight_cat_class_0': 0.030202586271095837, 'weight_cat_class_1': 0.728263953340007, 'weight_cat_class_2': 0.5521400185865372}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                  | 1724/2000 [01:10<00:13, 21.02it/s]

[I 2026-07-03 10:23:46,263] Trial 1722 finished with value: 0.9490559901205152 and parameters: {'weight_lgbm_class_0': 0.070643507960755, 'weight_lgbm_class_1': 0.7391409952094063, 'weight_lgbm_class_2': 0.6501442243930761, 'weight_xgb_class_0': 0.019313200913653395, 'weight_xgb_class_1': 0.4830123670615801, 'weight_xgb_class_2': 0.6217132965215728, 'weight_cat_class_0': 0.0003584806518922082, 'weight_cat_class_1': 0.985893936247574, 'weight_cat_class_2': 0.457180277462421}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:46,388] Trial 1723 finished with value: 0.9489056258344789 and parameters: {'weight_lgbm_class_0': 0.06895863713322374, 'weight_lgbm_class_1': 0.6989300343196244, 'weight_lgbm_class_2': 0.6814991223168848, 'weight_xgb_class_0': 0.014602551944028843, 'weight_xgb_class_1': 0.41019264908286274, 'weight_xgb_class_2': 0.5352739981995703, 'weight_cat_class_0': 0.0008513966713803098, 'weight_cat_class_1': 0.9843555098786504, 'weight_cat_class_2': 0.58203944104019}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:46,455] Trial 1724 finished with value: 0.9485624145454805 and parameters: {'weight_lgbm_class_0': 0.06878037050771045, 'weight_lgbm_class_1': 0.7070366882219177, 'weight_lgbm_class_2': 0.6902475415065517, 'weight_xgb_class_0': 0.0005008920094899151, 'weight_xgb_class_1': 0.4867600862538006, 'weight_xgb_class_2': 0.4579135250340392, 'weight_cat_class_0': 0.000706093043093714, 'weight_cat_class_1': 0.7232422049221824, 'weight_cat_class_2': 0.5835030592865943}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                 | 1730/2000 [01:10<00:16, 16.59it/s]

[I 2026-07-03 10:23:46,568] Trial 1725 finished with value: 0.9487850912220335 and parameters: {'weight_lgbm_class_0': 0.06430588947040197, 'weight_lgbm_class_1': 0.759012818308449, 'weight_lgbm_class_2': 0.5912989237715875, 'weight_xgb_class_0': 0.07767126098615133, 'weight_xgb_class_1': 0.5318209732820969, 'weight_xgb_class_2': 0.5376288733441195, 'weight_cat_class_0': 0.11337337819470472, 'weight_cat_class_1': 0.9763345651601073, 'weight_cat_class_2': 0.6307714586093529}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:46,603] Trial 1726 finished with value: 0.9494855440277945 and parameters: {'weight_lgbm_class_0': 0.0653443097717714, 'weight_lgbm_class_1': 0.75498264351846, 'weight_lgbm_class_2': 0.67660488593569, 'weight_xgb_class_0': 0.07856308841613832, 'weight_xgb_class_1': 0.5278254881516498, 'weight_xgb_class_2': 0.43936450179586445, 'weight_cat_class_0': 0.030614180113076987, 'weight_cat_class_1': 0.7309327041214194, 'weight_cat_class_2': 0.5774954295734603}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:46,649] Trial 1728 finished with value: 0.9481351610090171 and parameters: {'weight_lgbm_class_0': 0.05801406700160527, 'weight_lgbm_class_1': 0.760280943253317, 'weight_lgbm_class_2': 0.3356593070784618, 'weight_xgb_class_0': 0.08698401438367684, 'weight_xgb_class_1': 0.5262919273241106, 'weight_xgb_class_2': 0.5333126619001727, 'weight_cat_class_0': 0.1089486044003163, 'weight_cat_class_1': 0.8422062118645767, 'weight_cat_class_2': 0.5844839192211043}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:46,695] Trial 1727 finished with value: 0.9487697073590406 and parameters: {'weight_lgbm_class_0': 0.059450629276695234, 'weight_lgbm_class_1': 0.7632775380481372, 'weight_lgbm_class_2': 0.6716928871555763, 'weight_xgb_class_0': 0.08298878901582062, 'weight_xgb_class_1': 0.4047358979969531, 'weight_xgb_class_2': 0.5406790721789778, 'weight_cat_class_0': 0.11099938462191178, 'weight_cat_class_1': 0.9854325650611824, 'weight_cat_class_2': 0.5771908498679167}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:46,718] Trial 1730 finished with value: 0.9496103501755844 and parameters: {'weight_lgbm_class_0': 0.06008284351997423, 'weight_lgbm_class_1': 0.7604508238586384, 'weight_lgbm_class_2': 0.5901099583440996, 'weight_xgb_class_0': 0.08375486467719041, 'weight_xgb_class_1': 0.5202343830005157, 'weight_xgb_class_2': 0.4352627268119134, 'weight_cat_class_0': 2.4374896791194006e-05, 'weight_cat_class_1': 0.9810231623703572, 'weight_cat_class_2': 0.5825401316801786}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:46,740] Trial 1729 finished with value: 0.9496654201476766 and parameters: {'weight_lgbm_class_0': 0.0593944560204523, 'weight_lgbm_class_1': 0.7619322166092902, 'weight_lgbm_class_2': 0.7697155319123041, 'weight_xgb_class_0': 0.07853457276602192, 'weight_xgb_class_1': 0.616255491544877, 'weight_xgb_class_2': 0.5351236536365791, 'weight_cat_class_0': 0.030505072274614364, 'weight_cat_class_1': 0.8414321853956698, 'weight_cat_class_2': 0.4959174128358037}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                 | 1735/2000 [01:11<00:12, 21.17it/s]

[I 2026-07-03 10:23:46,802] Trial 1732 finished with value: 0.9494988562284062 and parameters: {'weight_lgbm_class_0': 0.05202509529645037, 'weight_lgbm_class_1': 0.7529784524741268, 'weight_lgbm_class_2': 0.5869944587613528, 'weight_xgb_class_0': 0.08265384225970004, 'weight_xgb_class_1': 0.41385869289243105, 'weight_xgb_class_2': 0.5154325093660714, 'weight_cat_class_0': 0.02777197367018104, 'weight_cat_class_1': 0.7188490009763873, 'weight_cat_class_2': 0.524072645659707}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:46,803] Trial 1731 finished with value: 0.9103652619743184 and parameters: {'weight_lgbm_class_0': 0.059508948151595104, 'weight_lgbm_class_1': 0.7636566651250117, 'weight_lgbm_class_2': 0.5829277774595136, 'weight_xgb_class_0': 0.9675810935356346, 'weight_xgb_class_1': 0.6376293598317176, 'weight_xgb_class_2': 0.5142770860587701, 'weight_cat_class_0': 0.027329922955028153, 'weight_cat_class_1': 0.704713511623551, 'weight_cat_class_2': 0.5132986990665995}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:46,859] Trial 1733 finished with value: 0.9484040020150782 and parameters: {'weight_lgbm_class_0': 0.06089193178456356, 'weight_lgbm_class_1': 0.7620451776873378, 'weight_lgbm_class_2': 0.5864298379502559, 'weight_xgb_class_0': 0.07832393161108517, 'weight_xgb_class_1': 0.4093512958659079, 'weight_xgb_class_2': 0.5109033655293214, 'weight_cat_class_0': 0.10921769834569783, 'weight_cat_class_1': 0.7412964125178118, 'weight_cat_class_2': 0.5148326413832449}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:46,920] Trial 1734 finished with value: 0.9483924275225721 and parameters: {'weight_lgbm_class_0': 0.0526514322979692, 'weight_lgbm_class_1': 0.7631732886928679, 'weight_lgbm_class_2': 0.5891919579173928, 'weight_xgb_class_0': 0.08323391464923102, 'weight_xgb_class_1': 0.3915571401823899, 'weight_xgb_class_2': 0.5182981501360179, 'weight_cat_class_0': 0.11288189655611675, 'weight_cat_class_1': 0.696954220998785, 'weight_cat_class_2': 0.5193044313071568}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:47,034] Trial 1735 finished with value: 0.9492683666832692 and parameters: {'weight_lgbm_class_0': 0.03353389302595683, 'weight_lgbm_class_1': 0.7513765441104128, 'weight_lgbm_class_2': 0.5738397909865701, 'weight_xgb_class_0': 0.03418207755265847, 'weight_xgb_class_1': 0.6223217434481737, 'weight_xgb_class_2': 0.509614505866042, 'weight_cat_class_0': 0.11461862202705281, 'weight_cat_class_1': 0.703576439160389, 'weight_cat_class_2': 0.5137784056052913}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:47,139] Trial 1736 finished with value: 0.9495724271664182 and parameters: {'weight_lgbm_class_0': 0.05517448856878273, 'weight_lgbm_class_1': 0.7617415686252984, 'weight_lgbm_class_2': 0.5930041616152105, 'weight_xgb_class_0': 0.08147193264724739, 'weight_xgb_class_1': 0.8786673600522932, 'weight_xgb_class_2': 0.5144880590011633, 'weight_cat_class_0': 0.029607922903657973, 'weight_cat_class_1': 0.6895417487878677, 'weight_cat_class_2': 0.5383988173527584}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 1741/2000 [01:11<00:15, 17.00it/s]

[I 2026-07-03 10:23:47,236] Trial 1738 finished with value: 0.9495777772810506 and parameters: {'weight_lgbm_class_0': 0.04132696888049947, 'weight_lgbm_class_1': 0.5085598380870561, 'weight_lgbm_class_2': 0.5682118414478647, 'weight_xgb_class_0': 0.035882481656371326, 'weight_xgb_class_1': 0.41465214358619595, 'weight_xgb_class_2': 0.5084070336889475, 'weight_cat_class_0': 0.029741775288306797, 'weight_cat_class_1': 0.7129075631719785, 'weight_cat_class_2': 0.5150230662747729}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:47,281] Trial 1737 finished with value: 0.9496557287163553 and parameters: {'weight_lgbm_class_0': 0.04598723756716627, 'weight_lgbm_class_1': 0.7304721882400984, 'weight_lgbm_class_2': 0.5694060493944515, 'weight_xgb_class_0': 0.035479167647894716, 'weight_xgb_class_1': 0.334639439339886, 'weight_xgb_class_2': 0.5079106867225162, 'weight_cat_class_0': 0.031468003132872915, 'weight_cat_class_1': 0.7085680908071244, 'weight_cat_class_2': 0.5290147849291988}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:47,297] Trial 1739 finished with value: 0.9496416508559246 and parameters: {'weight_lgbm_class_0': 0.04227221416351094, 'weight_lgbm_class_1': 0.7324954269451251, 'weight_lgbm_class_2': 0.5577679702092324, 'weight_xgb_class_0': 0.041117811963607184, 'weight_xgb_class_1': 0.6377464168058269, 'weight_xgb_class_2': 0.5136596213596335, 'weight_cat_class_0': 0.029556956403612347, 'weight_cat_class_1': 0.7117152593166644, 'weight_cat_class_2': 0.5183143068234224}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:47,340] Trial 1740 finished with value: 0.9496045049793042 and parameters: {'weight_lgbm_class_0': 0.0419064264087265, 'weight_lgbm_class_1': 0.7024193655172772, 'weight_lgbm_class_2': 0.7707596382687134, 'weight_xgb_class_0': 0.03564340516456462, 'weight_xgb_class_1': 0.4635127226603838, 'weight_xgb_class_2': 0.47592817512963376, 'weight_cat_class_0': 0.032395340922844934, 'weight_cat_class_1': 0.687374666798353, 'weight_cat_class_2': 0.5137338768935604}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:47,358] Trial 1741 finished with value: 0.9495504683249392 and parameters: {'weight_lgbm_class_0': 0.038505331832429344, 'weight_lgbm_class_1': 0.7325867115758949, 'weight_lgbm_class_2': 0.5974527875067306, 'weight_xgb_class_0': 0.0351407038167772, 'weight_xgb_class_1': 0.46714851411304337, 'weight_xgb_class_2': 0.5021501738177989, 'weight_cat_class_0': 0.02776508913976868, 'weight_cat_class_1': 0.7088007387529038, 'weight_cat_class_2': 0.5197537301944781}. Best is trial 1074 with value: 0.949788459361141.

[I 2026-07-03 10:23:47,396] Trial 1742 finished with value: 0.9496232700361039 and parameters: {'weight_lgbm_class_0': 0.03754188550164535, 'weight_lgbm_class_1': 0.7308511806650481, 'weight_lgbm_class_2': 0.5537819591196722, 'weight_xgb_class_0': 0.03578218962866689, 'weight_xgb_class_1': 0.40434821431396334, 'weight_xgb_class_2': 0.49701097613912704, 'weight_cat_class_0': 0.027724705110530837, 'weight_cat_class_1': 0.7047513958548138, 'weight_cat_class_2': 0.5129143072619915}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:47,492] Trial 1743 finished with value: 0.9496816230139508 and parameters: {'weight_lgbm_class_0': 0.040859692869412274, 'weight_lgbm_class_1': 0.7259175381261515, 'weight_lgbm_class_2': 0.5492581911505848, 'weight_xgb_class_0': 0.03046345403010408, 'weight_xgb_class_1': 0.5640962318282138, 'weight_xgb_class_2': 0.5043386781739125, 'weight_cat_class_0': 0.06850427947467055, 'weight_cat_class_1': 0.6860278309343553, 'weight_cat_class_2': 0.5108472116227196}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:47,499] Trial 1744 finished with value: 0.9496440655833807 and parameters: {'weight_lgbm_class_0': 0.04185140385144943, 'weight_lgbm_class_1': 0.725376787138241, 'weight_lgbm_class_2': 0.5647530052416213, 'weight_xgb_class_0': 0.03660685559960625, 'weight_xgb_class_1': 0.8781929118993067, 'weight_xgb_class_2': 0.47439360994131724, 'weight_cat_class_0': 0.06440493279976305, 'weight_cat_class_1': 0.7011504621153639, 'weight_cat_class_2': 0.5389388461401863}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:47,532] Trial 1745 finished with value: 0.9496468460206889 and parameters: {'weight_lgbm_class_0': 0.03446963960649197, 'weight_lgbm_class_1': 0.7269894750593885, 'weight_lgbm_class_2': 0.5509473764415457, 'weight_xgb_class_0': 0.03973825881134306, 'weight_xgb_class_1': 0.4623719765897008, 'weight_xgb_class_2': 0.4836035468051248, 'weight_cat_class_0': 0.0665087906315303, 'weight_cat_class_1': 0.6949679608089377, 'weight_cat_class_2': 0.5301772279076867}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:47,561] Trial 1746 finished with value: 0.9496496832400928 and parameters: {'weight_lgbm_class_0': 0.03619849718603131, 'weight_lgbm_class_1': 0.7200682600127237, 'weight_lgbm_class_2': 0.5585399355898191, 'weight_xgb_class_0': 0.04271395293558637, 'weight_xgb_class_1': 0.4609904496387864, 'weight_xgb_class_2': 0.4740939302692022, 'weight_cat_class_0': 0.07095761580304663, 'weight_cat_class_1': 0.696822095476063, 'weight_cat_class_2': 0.5396427492560096}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                | 1748/2000 [01:11<00:12, 20.57it/s]

[I 2026-07-03 10:23:47,644] Trial 1747 finished with value: 0.9494950251233503 and parameters: {'weight_lgbm_class_0': 0.03131554020483378, 'weight_lgbm_class_1': 0.7176634183643285, 'weight_lgbm_class_2': 0.6018399714630319, 'weight_xgb_class_0': 0.045628967106004795, 'weight_xgb_class_1': 0.46809221562567616, 'weight_xgb_class_2': 0.47206816243578387, 'weight_cat_class_0': 0.020969013636412383, 'weight_cat_class_1': 0.7025879562329063, 'weight_cat_class_2': 0.5475886618921432}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:47,778] Trial 1748 finished with value: 0.9496656465516292 and parameters: {'weight_lgbm_class_0': 0.03629312041860155, 'weight_lgbm_class_1': 0.722659141956196, 'weight_lgbm_class_2': 0.5671627528523047, 'weight_xgb_class_0': 0.03751543130348188, 'weight_xgb_class_1': 0.4665765923589279, 'weight_xgb_class_2': 0.47318453973618596, 'weight_cat_class_0': 0.0730180007179018, 'weight_cat_class_1': 0.7020120831303148, 'weight_cat_class_2': 0.5580048629212094}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                | 1751/2000 [01:12<00:14, 16.72it/s]

[I 2026-07-03 10:23:47,882] Trial 1749 finished with value: 0.9487560897518222 and parameters: {'weight_lgbm_class_0': 0.12647434896415802, 'weight_lgbm_class_1': 0.7288735492430193, 'weight_lgbm_class_2': 0.5633378109554651, 'weight_xgb_class_0': 0.03749477293904331, 'weight_xgb_class_1': 0.6778594144418468, 'weight_xgb_class_2': 0.47855345504111957, 'weight_cat_class_0': 0.06954882519473773, 'weight_cat_class_1': 0.749170612723797, 'weight_cat_class_2': 0.5524498165314106}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:47,937] Trial 1750 finished with value: 0.9489662139412699 and parameters: {'weight_lgbm_class_0': 0.12741200243753942, 'weight_lgbm_class_1': 0.7270585803262941, 'weight_lgbm_class_2': 0.9147876016226039, 'weight_xgb_class_0': 0.047554687734120166, 'weight_xgb_class_1': 0.4677008860674269, 'weight_xgb_class_2': 0.47354195858840525, 'weight_cat_class_0': 0.06737226706715706, 'weight_cat_class_1': 0.7412050574547975, 'weight_cat_class_2': 0.5458775701756036}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:48,008] Trial 1751 finished with value: 0.9222368133338361 and parameters: {'weight_lgbm_class_0': 0.7423981367005779, 'weight_lgbm_class_1': 0.735524589617236, 'weight_lgbm_class_2': 0.5538491200960474, 'weight_xgb_class_0': 0.000796505592831509, 'weight_xgb_class_1': 0.4682791281288426, 'weight_xgb_class_2': 0.46821046017162643, 'weight_cat_class_0': 0.06346353131907503, 'weight_cat_class_1': 0.7449149654647345, 'weight_cat_class_2': 0.4936373644322322}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎               | 1759/2000 [01:12<00:12, 18.94it/s]

[I 2026-07-03 10:23:48,099] Trial 1753 finished with value: 0.9424935130017782 and parameters: {'weight_lgbm_class_0': 0.12003520538072529, 'weight_lgbm_class_1': 0.7170208760498422, 'weight_lgbm_class_2': 0.9117423522808443, 'weight_xgb_class_0': 0.29335954422291266, 'weight_xgb_class_1': 0.5783829723212964, 'weight_xgb_class_2': 0.4687964468507357, 'weight_cat_class_0': 0.06775432705920675, 'weight_cat_class_1': 0.7435034654671082, 'weight_cat_class_2': 0.4962455507413565}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:48,114] Trial 1754 finished with value: 0.9496150560254843 and parameters: {'weight_lgbm_class_0': 0.12197935435626446, 'weight_lgbm_class_1': 0.7353868334097443, 'weight_lgbm_class_2': 0.9112002958575739, 'weight_xgb_class_0': 0.0008109207248107146, 'weight_xgb_class_1': 0.5815902042870535, 'weight_xgb_class_2': 0.4740180007616346, 'weight_cat_class_0': 0.055010718598117014, 'weight_cat_class_1': 0.7462998469254778, 'weight_cat_class_2': 0.5517142311621003}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:48,123] Trial 1752 finished with value: 0.9420497827892262 and parameters: {'weight_lgbm_class_0': 0.09382695977161534, 'weight_lgbm_class_1': 0.719260537234562, 'weight_lgbm_class_2': 0.913918146945927, 'weight_xgb_class_0': 0.33737415722406805, 'weight_xgb_class_1': 0.5851749959652875, 'weight_xgb_class_2': 0.47708706176146, 'weight_cat_class_0': 0.06433645045572241, 'weight_cat_class_1': 0.7392095627095672, 'weight_cat_class_2': 0.5432314402168764}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:48,188] Trial 1755 finished with value: 0.9497465666967689 and parameters: {'weight_lgbm_class_0': 0.09257007211943116, 'weight_lgbm_class_1': 0.7208610138611635, 'weight_lgbm_class_2': 0.9023153939492582, 'weight_xgb_class_0': 0.0017449585943487421, 'weight_xgb_class_1': 0.6002453189212518, 'weight_xgb_class_2': 0.47507514837630394, 'weight_cat_class_0': 0.06391050946530286, 'weight_cat_class_1': 0.7403674687923896, 'weight_cat_class_2': 0.5525187560034006}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:48,203] Trial 1756 finished with value: 0.9494688304484703 and parameters: {'weight_lgbm_class_0': 0.12881848884283634, 'weight_lgbm_class_1': 0.7131619506305912, 'weight_lgbm_class_2': 0.9608483268698054, 'weight_xgb_class_0': 0.0561164730315356, 'weight_xgb_class_1': 0.5935429742682852, 'weight_xgb_class_2': 0.4770145620598558, 'weight_cat_class_0': 0.01735752905166542, 'weight_cat_class_1': 0.7579506480370504, 'weight_cat_class_2': 0.4916319180492046}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:48,225] Trial 1757 finished with value: 0.9494567484064693 and parameters: {'weight_lgbm_class_0': 0.1295893776514447, 'weight_lgbm_class_1': 0.7790523942592945, 'weight_lgbm_class_2': 0.8940642503602667, 'weight_xgb_class_0': 0.05296199309433677, 'weight_xgb_class_1': 0.58844064291669, 'weight_xgb_class_2': 0.4737325717609946, 'weight_cat_class_0': 0.01565367008473918, 'weight_cat_class_1': 0.7455889743640983, 'weight_cat_class_2': 0.490665827497241}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:48,243] Trial 1758 finished with value: 0.9152075525256264 and parameters: {'weight_lgbm_class_0': 0.999363914197602, 'weight_lgbm_class_1': 0.7746739745016998, 'weight_lgbm_class_2': 0.9090025797635123, 'weight_xgb_class_0': 0.05290896844645512, 'weight_xgb_class_1': 0.5888733524560693, 'weight_xgb_class_2': 0.4406751775806047, 'weight_cat_class_0': 0.016704083463067017, 'weight_cat_class_1': 0.7503921497934263, 'weight_cat_class_2': 0.48550680028595716}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:48,309] Trial 1759 finished with value: 0.9497170007921708 and parameters: {'weight_lgbm_class_0': 0.12659780109398566, 'weight_lgbm_class_1': 0.7823944230707724, 'weight_lgbm_class_2': 0.9135937908535886, 'weight_xgb_class_0': 0.0016792839291975767, 'weight_xgb_class_1': 0.5908773841336441, 'weight_xgb_class_2': 0.44927265513707293, 'weight_cat_class_0': 0.018075164986910943, 'weight_cat_class_1': 0.748053596241667, 'weight_cat_class_2': 0.4901527424753385}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1074. Best value: 0.949788:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋               | 1764/2000 [01:12<00:13, 17.09it/s]

[I 2026-07-03 10:23:48,484] Trial 1760 finished with value: 0.9495784374228728 and parameters: {'weight_lgbm_class_0': 0.12559308878712805, 'weight_lgbm_class_1': 0.7422584751297691, 'weight_lgbm_class_2': 0.8971033751103565, 'weight_xgb_class_0': 0.016731029175681537, 'weight_xgb_class_1': 0.5844310095800264, 'weight_xgb_class_2': 0.44500305115742833, 'weight_cat_class_0': 0.015218760510580628, 'weight_cat_class_1': 0.6666154936761044, 'weight_cat_class_2': 0.11807844808174754}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:48,501] Trial 1761 finished with value: 0.9215040766896349 and parameters: {'weight_lgbm_class_0': 0.08884243867099308, 'weight_lgbm_class_1': 0.7802818870719442, 'weight_lgbm_class_2': 0.9013819471304735, 'weight_xgb_class_0': 0.7572877585692881, 'weight_xgb_class_1': 0.5946917914419865, 'weight_xgb_class_2': 0.44329084930657087, 'weight_cat_class_0': 0.018684418310185094, 'weight_cat_class_1': 0.7577469972251814, 'weight_cat_class_2': 0.30968189030578774}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:48,571] Trial 1762 finished with value: 0.9496235114952388 and parameters: {'weight_lgbm_class_0': 0.088149498593591, 'weight_lgbm_class_1': 0.7787943800861507, 'weight_lgbm_class_2': 0.9120694593192631, 'weight_xgb_class_0': 0.015473499040752556, 'weight_xgb_class_1': 0.5972021141399743, 'weight_xgb_class_2': 0.4442055115345166, 'weight_cat_class_0': 0.0184611607791963, 'weight_cat_class_1': 0.7683925339407535, 'weight_cat_class_2': 0.48028528190282}. Best is trial 1074 with value: 0.949788459361141.
[I 2026-07-03 10:23:48,642] Trial 1763 finished with value: 0.9496365504685729 and parameters: {'weight_lgbm_class_0': 0.08546781969031603, 'weight_lgbm_class_1': 0.7722117753013371, 'weight_lgbm_class_2': 0.8072450130310832, 'weight_xgb_class_0': 0.015083535095936091, 'weight_xgb_class_1': 0.5969746741603807, 'weight_xgb_class_2': 0.4429507718535705, 'weight_cat_class_0': 0.015928473413409444, 'weight_cat_class_1': 0.7526736871758046, 'weight_cat_class_2': 0.4733034228974145}. Best is trial 1074 with value: 0.949788459361141.

Best trial: 1765. Best value: 0.949792:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 1771/2000 [01:13<00:12, 18.61it/s]

[I 2026-07-03 10:23:48,795] Trial 1765 finished with value: 0.9497917773888238 and parameters: {'weight_lgbm_class_0': 0.0960592117408375, 'weight_lgbm_class_1': 0.7720394466369802, 'weight_lgbm_class_2': 0.9992620359277073, 'weight_xgb_class_0': 0.0008310891044752133, 'weight_xgb_class_1': 0.4390144704192221, 'weight_xgb_class_2': 0.4408463205116877, 'weight_cat_class_0': 0.025354311969688355, 'weight_cat_class_1': 0.7627788630690802, 'weight_cat_class_2': 0.11526141784675017}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:48,814] Trial 1764 finished with value: 0.9198304856591673 and parameters: {'weight_lgbm_class_0': 0.0008606099193127978, 'weight_lgbm_class_1': 0.7800436842224644, 'weight_lgbm_class_2': 0.9648957149446468, 'weight_xgb_class_0': 0.01874788057942147, 'weight_xgb_class_1': 0.5262400389396684, 'weight_xgb_class_2': 0.4362821643847845, 'weight_cat_class_0': 0.8136440944141254, 'weight_cat_class_1': 0.29292708646829113, 'weight_cat_class_2': 0.31052586879395766}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:48,836] Trial 1766 finished with value: 0.9497770125295263 and parameters: {'weight_lgbm_class_0': 0.09058587267631052, 'weight_lgbm_class_1': 0.6874947191679157, 'weight_lgbm_class_2': 0.8885449626296028, 'weight_xgb_class_0': 0.00010295493831820665, 'weight_xgb_class_1': 0.5215986701331168, 'weight_xgb_class_2': 0.4513318840981778, 'weight_cat_class_0': 0.018215344101560477, 'weight_cat_class_1': 0.6649284512908894, 'weight_cat_class_2': 0.11029139840879373}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:48,872] Trial 1767 finished with value: 0.9494206005790291 and parameters: {'weight_lgbm_class_0': 0.09253561564486516, 'weight_lgbm_class_1': 0.6747622618568478, 'weight_lgbm_class_2': 0.8947830190875153, 'weight_xgb_class_0': 0.0006399535650644696, 'weight_xgb_class_1': 0.5867490765974942, 'weight_xgb_class_2': 0.4451699724096095, 'weight_cat_class_0': 0.100754769269601, 'weight_cat_class_1': 0.7301953940164864, 'weight_cat_class_2': 0.4802631413672045}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:48,921] Trial 1769 finished with value: 0.9493503115160085 and parameters: {'weight_lgbm_class_0': 0.09151524090776646, 'weight_lgbm_class_1': 0.6920682517828783, 'weight_lgbm_class_2': 0.895680365077045, 'weight_xgb_class_0': 0.017434691908243503, 'weight_xgb_class_1': 0.607838361795231, 'weight_xgb_class_2': 0.4448812035115912, 'weight_cat_class_0': 0.09075929019100146, 'weight_cat_class_1': 0.730454875841084, 'weight_cat_class_2': 0.4740244038853342}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:48,928] Trial 1768 finished with value: 0.9491922228271794 and parameters: {'weight_lgbm_class_0': 0.08795031762133278, 'weight_lgbm_class_1': 0.7064621992937018, 'weight_lgbm_class_2': 0.8975187340595439, 'weight_xgb_class_0': 0.0024052733214149705, 'weight_xgb_class_1': 0.5963768851039116, 'weight_xgb_class_2': 0.44044450893490267, 'weight_cat_class_0': 0.093685670693701, 'weight_cat_class_1': 0.7227785462107247, 'weight_cat_class_2': 0.11346476821886156}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:48,936] Trial 1770 finished with value: 0.9486182423151144 and parameters: {'weight_lgbm_class_0': 0.08962032590320526, 'weight_lgbm_class_1': 0.6873238155912609, 'weight_lgbm_class_2': 0.8943339427680452, 'weight_xgb_class_0': 0.015015801776005283, 'weight_xgb_class_1': 0.6096580315247419, 'weight_xgb_class_2': 0.4442280123470001, 'weight_cat_class_0': 0.14286049736659284, 'weight_cat_class_1': 0.7183584472096167, 'weight_cat_class_2': 0.3116471449567205}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:48,964] Trial 1771 finished with value: 0.9488014671821099 and parameters: {'weight_lgbm_class_0': 0.0911011340322741, 'weight_lgbm_class_1': 0.6874216312192907, 'weight_lgbm_class_2': 0.8919808184778789, 'weight_xgb_class_0': 0.018556048930679477, 'weight_xgb_class_1': 0.6451949540739107, 'weight_xgb_class_2': 0.4392117360381713, 'weight_cat_class_0': 0.09913923619954432, 'weight_cat_class_1': 0.7200956418536931, 'weight_cat_class_2': 0.1068206415267566}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍              | 1776/2000 [01:13<00:12, 18.49it/s]

[I 2026-07-03 10:23:49,192] Trial 1772 finished with value: 0.9489767241341062 and parameters: {'weight_lgbm_class_0': 0.0939802416010177, 'weight_lgbm_class_1': 0.6919143278225823, 'weight_lgbm_class_2': 0.8977521366518075, 'weight_xgb_class_0': 0.0020840700400655203, 'weight_xgb_class_1': 0.616357432922214, 'weight_xgb_class_2': 0.4363458997866246, 'weight_cat_class_0': 0.09660350706763918, 'weight_cat_class_1': 0.7254845289357443, 'weight_cat_class_2': 0.09902368905829873}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:49,200] Trial 1773 finished with value: 0.9489273174856896 and parameters: {'weight_lgbm_class_0': 0.08996735725777186, 'weight_lgbm_class_1': 0.6819233421172698, 'weight_lgbm_class_2': 0.8829032078350504, 'weight_xgb_class_0': 0.0007073577925719481, 'weight_xgb_class_1': 0.5693569279329556, 'weight_xgb_class_2': 0.4404346794408525, 'weight_cat_class_0': 0.15206995426717812, 'weight_cat_class_1': 0.7268710188796437, 'weight_cat_class_2': 0.47628793578443646}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:49,238] Trial 1774 finished with value: 0.9491476728657332 and parameters: {'weight_lgbm_class_0': 0.0927329411577713, 'weight_lgbm_class_1': 0.7108516672293077, 'weight_lgbm_class_2': 0.9283963609702995, 'weight_xgb_class_0': 0.0023714582526573, 'weight_xgb_class_1': 0.5982172182308892, 'weight_xgb_class_2': 0.4348335392853434, 'weight_cat_class_0': 0.09293905131286817, 'weight_cat_class_1': 0.7245626572073761, 'weight_cat_class_2': 0.10077654713927094}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:49,306] Trial 1775 finished with value: 0.9496221070913172 and parameters: {'weight_lgbm_class_0': 0.016240557605071336, 'weight_lgbm_class_1': 0.703722379526103, 'weight_lgbm_class_2': 0.888347067011897, 'weight_xgb_class_0': 0.0012840873435478607, 'weight_xgb_class_1': 0.6425560602142176, 'weight_xgb_class_2': 0.4324109779279859, 'weight_cat_class_0': 0.09462619755073721, 'weight_cat_class_1': 0.729734844304386, 'weight_cat_class_2': 0.3089481371372019}. Best is trial 1765 with value: 0.9497917773888238.

[I 2026-07-03 10:23:49,415] Trial 1776 finished with value: 0.9475303586384426 and parameters: {'weight_lgbm_class_0': 0.10317985681960797, 'weight_lgbm_class_1': 0.79392145525384, 'weight_lgbm_class_2': 0.9699168710156595, 'weight_xgb_class_0': 0.00022991750299799693, 'weight_xgb_class_1': 0.4274056800384457, 'weight_xgb_class_2': 0.4294600585899869, 'weight_cat_class_0': 0.17301503963740564, 'weight_cat_class_1': 0.7308322810250457, 'weight_cat_class_2': 0.11029472770389777}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:49,438] Trial 1777 finished with value: 0.9493866791577791 and parameters: {'weight_lgbm_class_0': 0.10497932012738452, 'weight_lgbm_class_1': 0.6737745161148863, 'weight_lgbm_class_2': 0.9944159397081909, 'weight_xgb_class_0': 0.014528842858480622, 'weight_xgb_class_1': 0.4295269924719183, 'weight_xgb_class_2': 0.4263671981513209, 'weight_cat_class_0': 0.04873756691193299, 'weight_cat_class_1': 0.724197749737518, 'weight_cat_class_2': 0.08665837365564777}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:49,513] Trial 1779 finished with value: 0.9491643180748724 and parameters: {'weight_lgbm_class_0': 0.11914367010590127, 'weight_lgbm_class_1': 0.6770385777035154, 'weight_lgbm_class_2': 0.9899483963190109, 'weight_xgb_class_0': 0.01695600894781313, 'weight_xgb_class_1': 0.424572853000612, 'weight_xgb_class_2': 0.42635118367291963, 'weight_cat_class_0': 0.04754160278736337, 'weight_cat_class_1': 0.5981968220573326, 'weight_cat_class_2': 0.10001051929440131}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:49,554] Trial 1778 finished with value: 0.9493833933094257 and parameters: {'weight_lgbm_class_0': 0.1127596727579384, 'weight_lgbm_class_1': 0.689716645143719, 'weight_lgbm_class_2': 0.9809111766291884, 'weight_xgb_class_0': 0.01505487868213368, 'weight_xgb_class_1': 0.4322322127975845, 'weight_xgb_class_2': 0.4253662441102021, 'weight_cat_class_0': 0.045213117632458014, 'weight_cat_class_1': 0.676796900120871, 'weight_cat_class_2': 0.147200250416131}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:49,608] Trial 1781 finished with value: 0.9488518252160971 and parameters: {'weight_lgbm_class_0': 0.1099582804192932, 'weight_lgbm_class_1': 0.6249571881086309, 'weight_lgbm_class_2': 0.7762990385013991, 'weight_xgb_class_0': 0.01881870348600776, 'weight_xgb_class_1': 0.39463272800207483, 'weight_xgb_class_2': 0.42298957778930585, 'weight_cat_class_0': 0.04715159068047661, 'weight_cat_class_1': 0.6657946883904716, 'weight_cat_class_2': 0.10121823568916355}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉              | 1783/2000 [01:13<00:10, 19.73it/s]

[I 2026-07-03 10:23:49,614] Trial 1782 finished with value: 0.9494817019717089 and parameters: {'weight_lgbm_class_0': 0.11296088817872228, 'weight_lgbm_class_1': 0.6126649843844245, 'weight_lgbm_class_2': 0.9903155493942258, 'weight_xgb_class_0': 0.0009643694132418744, 'weight_xgb_class_1': 0.41012748941125043, 'weight_xgb_class_2': 0.42185624682480394, 'weight_cat_class_0': 0.047550819956302545, 'weight_cat_class_1': 0.6642300318691532, 'weight_cat_class_2': 0.10371223759878728}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:49,663] Trial 1780 finished with value: 0.9495028063772576 and parameters: {'weight_lgbm_class_0': 0.11252821520642135, 'weight_lgbm_class_1': 0.621571187491549, 'weight_lgbm_class_2': 0.9919743489808085, 'weight_xgb_class_0': 0.0021809164030684378, 'weight_xgb_class_1': 0.4425872834658756, 'weight_xgb_class_2': 0.4202212573505694, 'weight_cat_class_0': 0.046536234018795634, 'weight_cat_class_1': 0.6845077032960007, 'weight_cat_class_2': 0.10861448675793262}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:49,668] Trial 1783 finished with value: 0.9486120314943601 and parameters: {'weight_lgbm_class_0': 0.1142785723568706, 'weight_lgbm_class_1': 0.06870490304673849, 'weight_lgbm_class_2': 0.9809924107024043, 'weight_xgb_class_0': 0.0014473591463288501, 'weight_xgb_class_1': 0.43512091390133445, 'weight_xgb_class_2': 0.43129322611255516, 'weight_cat_class_0': 0.0469469810114338, 'weight_cat_class_1': 0.6216775086618936, 'weight_cat_class_2': 0.09621481616246469}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎             | 1789/2000 [01:14<00:11, 17.84it/s]

[I 2026-07-03 10:23:49,917] Trial 1785 finished with value: 0.9490931106154176 and parameters: {'weight_lgbm_class_0': 0.12141172903457406, 'weight_lgbm_class_1': 0.6381570340271944, 'weight_lgbm_class_2': 0.9547873650844317, 'weight_xgb_class_0': 0.016859388152736215, 'weight_xgb_class_1': 0.3887115508581491, 'weight_xgb_class_2': 0.4181367818870277, 'weight_cat_class_0': 0.04564437945207697, 'weight_cat_class_1': 0.6265518418879403, 'weight_cat_class_2': 0.09023365225112664}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:49,934] Trial 1784 finished with value: 0.9494716756194507 and parameters: {'weight_lgbm_class_0': 0.11894713604539955, 'weight_lgbm_class_1': 0.628910988408103, 'weight_lgbm_class_2': 0.9989198701445575, 'weight_xgb_class_0': 0.001308437419843423, 'weight_xgb_class_1': 0.4285995246171904, 'weight_xgb_class_2': 0.42367250618512464, 'weight_cat_class_0': 0.044155627634462624, 'weight_cat_class_1': 0.6891013477182615, 'weight_cat_class_2': 0.08815775847667842}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:49,955] Trial 1786 finished with value: 0.9495548753037971 and parameters: {'weight_lgbm_class_0': 0.11358570495203532, 'weight_lgbm_class_1': 0.6310613928463585, 'weight_lgbm_class_2': 0.9920027340574326, 'weight_xgb_class_0': 0.0001635110376347424, 'weight_xgb_class_1': 0.42690509957587985, 'weight_xgb_class_2': 0.4223022401049005, 'weight_cat_class_0': 0.046947962811115906, 'weight_cat_class_1': 0.6302054389360177, 'weight_cat_class_2': 0.44100182591543197}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:50,004] Trial 1787 finished with value: 0.9491554548729945 and parameters: {'weight_lgbm_class_0': 0.11987632401665244, 'weight_lgbm_class_1': 0.6212053762364269, 'weight_lgbm_class_2': 0.9941160836848155, 'weight_xgb_class_0': 0.016773027925478246, 'weight_xgb_class_1': 0.4323607175305695, 'weight_xgb_class_2': 0.4177566911743186, 'weight_cat_class_0': 0.05112737881701206, 'weight_cat_class_1': 0.6662199699241224, 'weight_cat_class_2': 0.11181260549972552}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:50,069] Trial 1788 finished with value: 0.9328462137828891 and parameters: {'weight_lgbm_class_0': 0.11021658857602068, 'weight_lgbm_class_1': 0.6253511468723152, 'weight_lgbm_class_2': 0.9852566543128962, 'weight_xgb_class_0': 7.444599318087372e-05, 'weight_xgb_class_1': 0.430502151288498, 'weight_xgb_class_2': 0.4224252039831331, 'weight_cat_class_0': 0.48662760665370314, 'weight_cat_class_1': 0.6698930822409528, 'weight_cat_class_2': 0.11755879157297944}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:50,106] Trial 1789 finished with value: 0.9302030342211743 and parameters: {'weight_lgbm_class_0': 0.11838745390042557, 'weight_lgbm_class_1': 0.6300541845095513, 'weight_lgbm_class_2': 0.9465819590594959, 'weight_xgb_class_0': 0.0003205145784383563, 'weight_xgb_class_1': 0.4327815956259014, 'weight_xgb_class_2': 0.4166127052492521, 'weight_cat_class_0': 0.5301185128582804, 'weight_cat_class_1': 0.7645217126876466, 'weight_cat_class_2': 0.13096847665661174}. Best is trial 1765 with value: 0.9497917773888238.

[I 2026-07-03 10:23:50,139] Trial 1790 finished with value: 0.9492673830802051 and parameters: {'weight_lgbm_class_0': 0.11697826811525697, 'weight_lgbm_class_1': 0.6230874389566305, 'weight_lgbm_class_2': 0.9802649883638115, 'weight_xgb_class_0': 0.01812597427734488, 'weight_xgb_class_1': 0.4387329166334188, 'weight_xgb_class_2': 0.41599165514837494, 'weight_cat_class_0': 0.04202237518160234, 'weight_cat_class_1': 0.6377280921342834, 'weight_cat_class_2': 0.1280538748618168}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:50,225] Trial 1791 finished with value: 0.9489808600087088 and parameters: {'weight_lgbm_class_0': 0.13552805731498635, 'weight_lgbm_class_1': 0.6245568222225566, 'weight_lgbm_class_2': 0.9946831033712316, 'weight_xgb_class_0': 0.022174964411015876, 'weight_xgb_class_1': 0.435997710820729, 'weight_xgb_class_2': 0.41885372296101014, 'weight_cat_class_0': 0.040804617110227766, 'weight_cat_class_1': 0.6408194866189775, 'weight_cat_class_2': 0.13129271551132504}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:50,246] Trial 1793 finished with value: 0.9491789394367488 and parameters: {'weight_lgbm_class_0': 0.136001885348041, 'weight_lgbm_class_1': 0.6272501942398448, 'weight_lgbm_class_2': 0.9816122528886354, 'weight_xgb_class_0': 0.0007573998853649562, 'weight_xgb_class_1': 0.43308326478429116, 'weight_xgb_class_2': 0.41785336755389646, 'weight_cat_class_0': 0.03999632818832178, 'weight_cat_class_1': 0.5720592209497237, 'weight_cat_class_2': 0.07049521244603901}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:50,253] Trial 1792 finished with value: 0.9490752034051876 and parameters: {'weight_lgbm_class_0': 0.14048201240459057, 'weight_lgbm_class_1': 0.6214442709351996, 'weight_lgbm_class_2': 0.9812475715565827, 'weight_xgb_class_0': 0.0165203008823822, 'weight_xgb_class_1': 0.45821070545291165, 'weight_xgb_class_2': 0.45593502691223076, 'weight_cat_class_0': 0.04029672831007673, 'weight_cat_class_1': 0.6555101531149408, 'weight_cat_class_2': 0.12686314251969258}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:50,336] Trial 1795 finished with value: 0.9488449394826556 and parameters: {'weight_lgbm_class_0': 0.131279746493824, 'weight_lgbm_class_1': 0.5907905854479699, 'weight_lgbm_class_2': 0.9623220600926912, 'weight_xgb_class_0': 0.028062251695564568, 'weight_xgb_class_1': 0.4399047721789633, 'weight_xgb_class_2': 0.40868823413076144, 'weight_cat_class_0': 0.03836528004472166, 'weight_cat_class_1': 0.7656707165028097, 'weight_cat_class_2': 0.07468175375134004}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋             | 1795/2000 [01:14<00:10, 20.01it/s]

[I 2026-07-03 10:23:50,355] Trial 1794 finished with value: 0.9262520963241195 and parameters: {'weight_lgbm_class_0': 0.6532134953369291, 'weight_lgbm_class_1': 0.5902260247733844, 'weight_lgbm_class_2': 0.9618830337885235, 'weight_xgb_class_0': 0.022937794577021123, 'weight_xgb_class_1': 0.43809887624335864, 'weight_xgb_class_2': 0.4538218294077086, 'weight_cat_class_0': 0.03666294224659547, 'weight_cat_class_1': 0.7716392800976325, 'weight_cat_class_2': 0.12384945548222942}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏            | 1802/2000 [01:14<00:11, 17.09it/s]

[I 2026-07-03 10:23:50,613] Trial 1796 finished with value: 0.9298381174187221 and parameters: {'weight_lgbm_class_0': 0.13648058092781162, 'weight_lgbm_class_1': 0.6407619537137192, 'weight_lgbm_class_2': 0.9870103372442695, 'weight_xgb_class_0': 0.026326926566353284, 'weight_xgb_class_1': 0.4347760508427664, 'weight_xgb_class_2': 0.4610529772464609, 'weight_cat_class_0': 0.4891084607480867, 'weight_cat_class_1': 0.5714615590797855, 'weight_cat_class_2': 0.1588283989635952}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:50,624] Trial 1797 finished with value: 0.949226092089788 and parameters: {'weight_lgbm_class_0': 0.12949804820023436, 'weight_lgbm_class_1': 0.5904155138260089, 'weight_lgbm_class_2': 0.9986011595686785, 'weight_xgb_class_0': 0.026619851439466064, 'weight_xgb_class_1': 0.4398574328290588, 'weight_xgb_class_2': 0.40715366917785345, 'weight_cat_class_0': 0.0318022281927232, 'weight_cat_class_1': 0.7622584729421076, 'weight_cat_class_2': 0.15985072753396226}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:50,695] Trial 1799 finished with value: 0.9490438764155638 and parameters: {'weight_lgbm_class_0': 0.14289170471271107, 'weight_lgbm_class_1': 0.5974573072379117, 'weight_lgbm_class_2': 0.9789658080221353, 'weight_xgb_class_0': 0.02748212533476635, 'weight_xgb_class_1': 0.4459666203660241, 'weight_xgb_class_2': 0.4560559773913954, 'weight_cat_class_0': 0.03216034844736107, 'weight_cat_class_1': 0.763789722679277, 'weight_cat_class_2': 0.14630504161633195}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:50,710] Trial 1798 finished with value: 0.9491662261577236 and parameters: {'weight_lgbm_class_0': 0.13315313920680763, 'weight_lgbm_class_1': 0.5971885328049582, 'weight_lgbm_class_2': 0.9525718236614718, 'weight_xgb_class_0': 0.02321891393802604, 'weight_xgb_class_1': 0.4549092384352753, 'weight_xgb_class_2': 0.45675519137738585, 'weight_cat_class_0': 0.03404226359460365, 'weight_cat_class_1': 0.6441717093953261, 'weight_cat_class_2': 0.15446728689079614}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:50,756] Trial 1801 finished with value: 0.9491937743934944 and parameters: {'weight_lgbm_class_0': 0.07973250818484852, 'weight_lgbm_class_1': 0.5975117874314095, 'weight_lgbm_class_2': 0.9604597220454133, 'weight_xgb_class_0': 0.02822879628247813, 'weight_xgb_class_1': 0.44871919360231277, 'weight_xgb_class_2': 0.45794506143984204, 'weight_cat_class_0': 0.07587001737712513, 'weight_cat_class_1': 0.7678318473493659, 'weight_cat_class_2': 0.12655184758613205}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:50,762] Trial 1800 finished with value: 0.9491001066466981 and parameters: {'weight_lgbm_class_0': 0.13668342713479661, 'weight_lgbm_class_1': 0.5951778978677454, 'weight_lgbm_class_2': 0.9961548367035589, 'weight_xgb_class_0': 0.025322304962846695, 'weight_xgb_class_1': 0.45974256304458816, 'weight_xgb_class_2': 0.45397882516093047, 'weight_cat_class_0': 0.035737806924752535, 'weight_cat_class_1': 0.7681027547548208, 'weight_cat_class_2': 0.12578132141906564}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:50,811] Trial 1802 finished with value: 0.9482721871045888 and parameters: {'weight_lgbm_class_0': 0.07658649704517104, 'weight_lgbm_class_1': 0.1465912340862875, 'weight_lgbm_class_2': 0.9637027247254958, 'weight_xgb_class_0': 0.02995273985098482, 'weight_xgb_class_1': 0.4505864476242926, 'weight_xgb_class_2': 0.4557844360130561, 'weight_cat_class_0': 0.07769974493235149, 'weight_cat_class_1': 0.6117468664273532, 'weight_cat_class_2': 0.10287293828909881}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 1807/2000 [01:15<00:09, 20.80it/s]

[I 2026-07-03 10:23:50,867] Trial 1803 finished with value: 0.9492463258396832 and parameters: {'weight_lgbm_class_0': 0.08006022457913126, 'weight_lgbm_class_1': 0.5959827190698336, 'weight_lgbm_class_2': 0.9747169023091303, 'weight_xgb_class_0': 0.029677736186425226, 'weight_xgb_class_1': 0.47561657271884755, 'weight_xgb_class_2': 0.45549543241654916, 'weight_cat_class_0': 0.06706712063380149, 'weight_cat_class_1': 0.7715265032546228, 'weight_cat_class_2': 0.061884413117340276}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:50,917] Trial 1804 finished with value: 0.9492772263514312 and parameters: {'weight_lgbm_class_0': 0.0782124111457411, 'weight_lgbm_class_1': 0.5891944062916197, 'weight_lgbm_class_2': 0.999120861148518, 'weight_xgb_class_0': 0.023551823337788103, 'weight_xgb_class_1': 0.4685347143677273, 'weight_xgb_class_2': 0.45647759292092105, 'weight_cat_class_0': 0.06845756083198852, 'weight_cat_class_1': 0.6734659589061114, 'weight_cat_class_2': 0.050954062126421784}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:50,933] Trial 1805 finished with value: 0.9492309333465626 and parameters: {'weight_lgbm_class_0': 0.080295728582316, 'weight_lgbm_class_1': 0.5954189020778806, 'weight_lgbm_class_2': 0.965917874385107, 'weight_xgb_class_0': 0.028606757887920685, 'weight_xgb_class_1': 0.46949058421848816, 'weight_xgb_class_2': 0.451230683955371, 'weight_cat_class_0': 0.07355105205936943, 'weight_cat_class_1': 0.6546609805404122, 'weight_cat_class_2': 0.1363689330810487}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:50,981] Trial 1806 finished with value: 0.9493211602671439 and parameters: {'weight_lgbm_class_0': 0.07687937261945638, 'weight_lgbm_class_1': 0.675440853570321, 'weight_lgbm_class_2': 0.9780384067545379, 'weight_xgb_class_0': 0.02939784682810092, 'weight_xgb_class_1': 0.4749804758635894, 'weight_xgb_class_2': 0.4575310216313071, 'weight_cat_class_0': 0.07337959581248327, 'weight_cat_class_1': 0.7676048694165215, 'weight_cat_class_2': 0.1360707718521403}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:51,038] Trial 1807 finished with value: 0.9492712948302661 and parameters: {'weight_lgbm_class_0': 0.07697203311490242, 'weight_lgbm_class_1': 0.6785329680585322, 'weight_lgbm_class_2': 0.9586296858436438, 'weight_xgb_class_0': 0.030701069628557467, 'weight_xgb_class_1': 0.46808691084772125, 'weight_xgb_class_2': 0.46180374083462694, 'weight_cat_class_0': 0.07435408269359868, 'weight_cat_class_1': 0.6777565818528741, 'weight_cat_class_2': 0.13639627623454112}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊            | 1813/2000 [01:15<00:11, 16.19it/s]

[I 2026-07-03 10:23:51,289] Trial 1808 finished with value: 0.948993368767491 and parameters: {'weight_lgbm_class_0': 0.07833817190534584, 'weight_lgbm_class_1': 0.6962615311834301, 'weight_lgbm_class_2': 0.8088825142806457, 'weight_xgb_class_0': 0.0321389441247731, 'weight_xgb_class_1': 0.4737041169432048, 'weight_xgb_class_2': 0.4596289190253825, 'weight_cat_class_0': 0.07448454157381669, 'weight_cat_class_1': 0.6038198976082104, 'weight_cat_class_2': 0.15319993890792108}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:51,317] Trial 1809 finished with value: 0.9491921281887362 and parameters: {'weight_lgbm_class_0': 0.08026844839449676, 'weight_lgbm_class_1': 0.6793186575120761, 'weight_lgbm_class_2': 0.965985161555482, 'weight_xgb_class_0': 0.032128012131887346, 'weight_xgb_class_1': 0.38685799025276374, 'weight_xgb_class_2': 0.6279871938612889, 'weight_cat_class_0': 0.07795894763154124, 'weight_cat_class_1': 0.6671577924175716, 'weight_cat_class_2': 0.0785497461037273}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:51,374] Trial 1810 finished with value: 0.9492576646480172 and parameters: {'weight_lgbm_class_0': 0.07435340646534552, 'weight_lgbm_class_1': 0.6917745613302095, 'weight_lgbm_class_2': 0.9976120794914999, 'weight_xgb_class_0': 0.03377764741893595, 'weight_xgb_class_1': 0.47710052546094767, 'weight_xgb_class_2': 0.4574713662302066, 'weight_cat_class_0': 0.07386157266031149, 'weight_cat_class_1': 0.6168839919980413, 'weight_cat_class_2': 0.1257542236453039}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:51,408] Trial 1812 finished with value: 0.9491209304824585 and parameters: {'weight_lgbm_class_0': 0.08130644527426147, 'weight_lgbm_class_1': 0.6830180177436987, 'weight_lgbm_class_2': 0.9639496114312845, 'weight_xgb_class_0': 0.028712286718226128, 'weight_xgb_class_1': 0.4872309865613641, 'weight_xgb_class_2': 0.49238254189589514, 'weight_cat_class_0': 0.07347136311076642, 'weight_cat_class_1': 0.6376218514493692, 'weight_cat_class_2': 0.05825417897385323}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:51,442] Trial 1813 finished with value: 0.9496631358078823 and parameters: {'weight_lgbm_class_0': 0.08913877384303104, 'weight_lgbm_class_1': 0.6940997560765181, 'weight_lgbm_class_2': 0.9595390477711363, 'weight_xgb_class_0': 0.035549318259632534, 'weight_xgb_class_1': 0.4850780150508922, 'weight_xgb_class_2': 0.49330050709080264, 'weight_cat_class_0': 0.01738501207730999, 'weight_cat_class_1': 0.6327188434997869, 'weight_cat_class_2': 0.15204700252206416}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:51,442] Trial 1811 finished with value: 0.9492009197304707 and parameters: {'weight_lgbm_class_0': 0.07959247294446532, 'weight_lgbm_class_1': 0.6816413465109304, 'weight_lgbm_class_2': 0.9984394644716389, 'weight_xgb_class_0': 0.0309044345560764, 'weight_xgb_class_1': 0.49197338458201073, 'weight_xgb_class_2': 0.48934047261910224, 'weight_cat_class_0': 0.07343190942052834, 'weight_cat_class_1': 0.6618785065317623, 'weight_cat_class_2': 0.06976584678726475}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏           | 1819/2000 [01:15<00:08, 20.69it/s]

[I 2026-07-03 10:23:51,521] Trial 1814 finished with value: 0.9497081813654255 and parameters: {'weight_lgbm_class_0': 0.08907545663453625, 'weight_lgbm_class_1': 0.6911250816557746, 'weight_lgbm_class_2': 0.8717827075810175, 'weight_xgb_class_0': 0.033496669778483285, 'weight_xgb_class_1': 0.4956712603798888, 'weight_xgb_class_2': 0.4933960527315627, 'weight_cat_class_0': 0.01769657326577814, 'weight_cat_class_1': 0.6629993249171062, 'weight_cat_class_2': 0.07843450162008496}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:51,524] Trial 1815 finished with value: 0.9493792056183485 and parameters: {'weight_lgbm_class_0': 0.09074781724066057, 'weight_lgbm_class_1': 0.680003491875204, 'weight_lgbm_class_2': 0.8721111122180174, 'weight_xgb_class_0': 0.0003798309522382373, 'weight_xgb_class_1': 0.495750529651593, 'weight_xgb_class_2': 0.6211509111102713, 'weight_cat_class_0': 0.000392125938756413, 'weight_cat_class_1': 0.6954628860700351, 'weight_cat_class_2': 0.09219345487057973}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:51,564] Trial 1816 finished with value: 0.9496833925312246 and parameters: {'weight_lgbm_class_0': 0.098766338979581, 'weight_lgbm_class_1': 0.6839710556715443, 'weight_lgbm_class_2': 0.8055697289365303, 'weight_xgb_class_0': 0.04295107856712638, 'weight_xgb_class_1': 0.4951933618409687, 'weight_xgb_class_2': 0.6365372884734496, 'weight_cat_class_0': 0.00015437555167745545, 'weight_cat_class_1': 0.6747068182547451, 'weight_cat_class_2': 0.08150084734800288}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:51,625] Trial 1817 finished with value: 0.949737807750403 and parameters: {'weight_lgbm_class_0': 0.06506569588741053, 'weight_lgbm_class_1': 0.685130105252783, 'weight_lgbm_class_2': 0.803693379307715, 'weight_xgb_class_0': 0.04648800568843156, 'weight_xgb_class_1': 0.4911932941568529, 'weight_xgb_class_2': 0.4886019938938343, 'weight_cat_class_0': 0.01555820355657746, 'weight_cat_class_1': 0.707052637594496, 'weight_cat_class_2': 0.07462098281379492}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:51,657] Trial 1818 finished with value: 0.9496811341846101 and parameters: {'weight_lgbm_class_0': 0.09581784234120339, 'weight_lgbm_class_1': 0.676208666379871, 'weight_lgbm_class_2': 0.7650661835610464, 'weight_xgb_class_0': 0.0006027536218989327, 'weight_xgb_class_1': 0.38779416402603284, 'weight_xgb_class_2': 0.48064518742015133, 'weight_cat_class_0': 0.01731567499145134, 'weight_cat_class_1': 0.6125259227693531, 'weight_cat_class_2': 0.0718194708877899}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:51,709] Trial 1819 finished with value: 0.9496628924033247 and parameters: {'weight_lgbm_class_0': 0.09920812007588353, 'weight_lgbm_class_1': 0.6853216018585423, 'weight_lgbm_class_2': 0.9985183997262163, 'weight_xgb_class_0': 5.362483048824973e-06, 'weight_xgb_class_1': 0.4079196964022247, 'weight_xgb_class_2': 0.4868485448699323, 'weight_cat_class_0': 0.017354094129710163, 'weight_cat_class_1': 0.6951810806292219, 'weight_cat_class_2': 0.15719417564539467}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋           | 1825/2000 [01:16<00:10, 17.23it/s]

[I 2026-07-03 10:23:51,930] Trial 1820 finished with value: 0.9495320781216368 and parameters: {'weight_lgbm_class_0': 0.0969623288917872, 'weight_lgbm_class_1': 0.6502191011629926, 'weight_lgbm_class_2': 0.8462931507556609, 'weight_xgb_class_0': 0.050128993122650685, 'weight_xgb_class_1': 0.49599083475794775, 'weight_xgb_class_2': 0.4880480310644713, 'weight_cat_class_0': 0.0010067467332166777, 'weight_cat_class_1': 0.6520055479647281, 'weight_cat_class_2': 0.06448777285141741}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:51,976] Trial 1821 finished with value: 0.9497170142513456 and parameters: {'weight_lgbm_class_0': 0.10140859898498808, 'weight_lgbm_class_1': 0.6501546640663125, 'weight_lgbm_class_2': 0.8754020708375189, 'weight_xgb_class_0': 1.338185818718573e-06, 'weight_xgb_class_1': 0.4982889490190392, 'weight_xgb_class_2': 0.48995394906479467, 'weight_cat_class_0': 0.0197300820349021, 'weight_cat_class_1': 0.5946910734794928, 'weight_cat_class_2': 0.0924882218156522}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:52,017] Trial 1823 finished with value: 0.9495058844105566 and parameters: {'weight_lgbm_class_0': 0.09617020076887174, 'weight_lgbm_class_1': 0.7965753994140969, 'weight_lgbm_class_2': 0.8355605750209804, 'weight_xgb_class_0': 0.050296528218957866, 'weight_xgb_class_1': 0.5011183546072482, 'weight_xgb_class_2': 0.3919812322347719, 'weight_cat_class_0': 0.0006997013841688465, 'weight_cat_class_1': 0.5846266123369508, 'weight_cat_class_2': 0.09264067865639719}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:52,028] Trial 1822 finished with value: 0.9496444082990401 and parameters: {'weight_lgbm_class_0': 0.09952427524494366, 'weight_lgbm_class_1': 0.6501235414320138, 'weight_lgbm_class_2': 0.8391157686674758, 'weight_xgb_class_0': 0.0003876532005971968, 'weight_xgb_class_1': 0.4980774935404113, 'weight_xgb_class_2': 0.4818462807191643, 'weight_cat_class_0': 0.021365401351577, 'weight_cat_class_1': 0.7054784713645998, 'weight_cat_class_2': 0.07758288337783305}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:52,108] Trial 1824 finished with value: 0.9497631085519592 and parameters: {'weight_lgbm_class_0': 0.10188908777739579, 'weight_lgbm_class_1': 0.6532012696439242, 'weight_lgbm_class_2': 0.8423861629953543, 'weight_xgb_class_0': 4.77461467956345e-05, 'weight_xgb_class_1': 0.5013388495291333, 'weight_xgb_class_2': 0.40139986292965396, 'weight_cat_class_0': 0.025624404721351413, 'weight_cat_class_1': 0.5821858762043548, 'weight_cat_class_2': 0.09858848977816331}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉           | 1829/2000 [01:16<00:09, 18.75it/s]

[I 2026-07-03 10:23:52,147] Trial 1825 finished with value: 0.9492508216617416 and parameters: {'weight_lgbm_class_0': 0.100548396485618, 'weight_lgbm_class_1': 0.6520191622739795, 'weight_lgbm_class_2': 0.8737776206495584, 'weight_xgb_class_0': 0.0518206998934752, 'weight_xgb_class_1': 0.5131279288597851, 'weight_xgb_class_2': 0.4794130519879174, 'weight_cat_class_0': 0.018213450754440134, 'weight_cat_class_1': 0.5999494016700502, 'weight_cat_class_2': 0.10827392713381147}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:52,167] Trial 1827 finished with value: 0.9050960278765134 and parameters: {'weight_lgbm_class_0': 0.9609612262319394, 'weight_lgbm_class_1': 0.6493790563889068, 'weight_lgbm_class_2': 0.8321003434290098, 'weight_xgb_class_0': 0.00047239741835104765, 'weight_xgb_class_1': 0.5210326920466869, 'weight_xgb_class_2': 0.4017063544027992, 'weight_cat_class_0': 0.017263024633010653, 'weight_cat_class_1': 0.602683367145624, 'weight_cat_class_2': 0.09657697241807467}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:52,242] Trial 1828 finished with value: 0.9164956490865291 and parameters: {'weight_lgbm_class_0': 0.059824472601694774, 'weight_lgbm_class_1': 0.6501038060200224, 'weight_lgbm_class_2': 0.7677646483351638, 'weight_xgb_class_0': 0.053170504737260316, 'weight_xgb_class_1': 0.40326678959105433, 'weight_xgb_class_2': 0.3897968186194984, 'weight_cat_class_0': 0.8799705324753122, 'weight_cat_class_1': 0.537169380950384, 'weight_cat_class_2': 0.9842125677561359}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:52,250] Trial 1826 finished with value: 0.9495907892945438 and parameters: {'weight_lgbm_class_0': 0.059564669260206565, 'weight_lgbm_class_1': 0.387795162238685, 'weight_lgbm_class_2': 0.7675121505943558, 'weight_xgb_class_0': 0.048903208968612444, 'weight_xgb_class_1': 0.5207168036572939, 'weight_xgb_class_2': 0.39049753427036765, 'weight_cat_class_0': 0.022428407442126104, 'weight_cat_class_1': 0.7463985172898709, 'weight_cat_class_2': 0.1081835853929676}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:52,318] Trial 1829 finished with value: 0.9497371867395138 and parameters: {'weight_lgbm_class_0': 0.10160717419760622, 'weight_lgbm_class_1': 0.6564307297377739, 'weight_lgbm_class_2': 0.8372802183226441, 'weight_xgb_class_0': 0.0006736649033236544, 'weight_xgb_class_1': 0.4106406042033811, 'weight_xgb_class_2': 0.3971084545312273, 'weight_cat_class_0': 0.01801509501384538, 'weight_cat_class_1': 0.6426606348749637, 'weight_cat_class_2': 0.10334126235772614}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████           | 1831/2000 [01:16<00:08, 19.91it/s]

[I 2026-07-03 10:23:52,362] Trial 1830 finished with value: 0.9489727792226272 and parameters: {'weight_lgbm_class_0': 0.061871785473542135, 'weight_lgbm_class_1': 0.6515859956063358, 'weight_lgbm_class_2': 0.22715301722741504, 'weight_xgb_class_0': 0.01743321236502972, 'weight_xgb_class_1': 0.5104403526283264, 'weight_xgb_class_2': 0.39161379697277243, 'weight_cat_class_0': 0.01701327014915209, 'weight_cat_class_1': 0.7516180774828919, 'weight_cat_class_2': 0.09055697324472226}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:52,388] Trial 1831 finished with value: 0.9496546195957021 and parameters: {'weight_lgbm_class_0': 0.061136009317592006, 'weight_lgbm_class_1': 0.651971241309653, 'weight_lgbm_class_2': 0.8421998674295622, 'weight_xgb_class_0': 0.05263552099437784, 'weight_xgb_class_1': 0.5125169360869799, 'weight_xgb_class_2': 0.39153492608918206, 'weight_cat_class_0': 0.01785121057975842, 'weight_cat_class_1': 0.5947158052025151, 'weight_cat_class_2': 0.5028888832882432}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎          | 1836/2000 [01:17<00:10, 15.19it/s]

[I 2026-07-03 10:23:52,631] Trial 1834 finished with value: 0.949364323393314 and parameters: {'weight_lgbm_class_0': 0.058806060611647504, 'weight_lgbm_class_1': 0.7959919055718198, 'weight_lgbm_class_2': 0.9367316385604944, 'weight_xgb_class_0': 0.05651352446532798, 'weight_xgb_class_1': 0.5139247314748271, 'weight_xgb_class_2': 0.3975634881346979, 'weight_cat_class_0': 0.05612156253775783, 'weight_cat_class_1': 0.7449187059212897, 'weight_cat_class_2': 0.12608016134502886}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:52,633] Trial 1832 finished with value: 0.9497034614472843 and parameters: {'weight_lgbm_class_0': 0.058242648288712784, 'weight_lgbm_class_1': 0.7880906613518284, 'weight_lgbm_class_2': 0.8388409715101668, 'weight_xgb_class_0': 0.05417957955246596, 'weight_xgb_class_1': 0.5209230034487551, 'weight_xgb_class_2': 0.3966913715546154, 'weight_cat_class_0': 0.01755584216900945, 'weight_cat_class_1': 0.7434579790686535, 'weight_cat_class_2': 0.12539649371281467}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:52,655] Trial 1833 finished with value: 0.9488997310900333 and parameters: {'weight_lgbm_class_0': 0.06210300878146845, 'weight_lgbm_class_1': 0.5608283721088275, 'weight_lgbm_class_2': 0.836503071155625, 'weight_xgb_class_0': 0.057113253248773324, 'weight_xgb_class_1': 0.5167750302138157, 'weight_xgb_class_2': 0.39171878139409344, 'weight_cat_class_0': 0.05642724917662807, 'weight_cat_class_1': 0.5837979102140024, 'weight_cat_class_2': 0.1132267713834787}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:52,787] Trial 1835 finished with value: 0.9496148670874384 and parameters: {'weight_lgbm_class_0': 0.059503720372728025, 'weight_lgbm_class_1': 0.7151091985451993, 'weight_lgbm_class_2': 0.9301713705518511, 'weight_xgb_class_0': 0.0002449642094196976, 'weight_xgb_class_1': 0.514080152195423, 'weight_xgb_class_2': 0.7472931418296379, 'weight_cat_class_0': 0.05655722699435955, 'weight_cat_class_1': 0.7452410463382773, 'weight_cat_class_2': 0.1008119662785844}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:52,826] Trial 1837 finished with value: 0.949682542027165 and parameters: {'weight_lgbm_class_0': 0.06075526266919372, 'weight_lgbm_class_1': 0.6617174950797906, 'weight_lgbm_class_2': 0.849116514486202, 'weight_xgb_class_0': 0.017911055153003872, 'weight_xgb_class_1': 0.523427542311395, 'weight_xgb_class_2': 0.3803695708220328, 'weight_cat_class_0': 0.054965807611080636, 'weight_cat_class_1': 0.4989516435542663, 'weight_cat_class_2': 0.12641473451909296}. Best is trial 1765 with value: 0.9497917773888238.

[I 2026-07-03 10:23:52,840] Trial 1836 finished with value: 0.9489162564586019 and parameters: {'weight_lgbm_class_0': 0.05833537442862, 'weight_lgbm_class_1': 0.6503871539760073, 'weight_lgbm_class_2': 0.8242147099145705, 'weight_xgb_class_0': 0.054279218307344015, 'weight_xgb_class_1': 0.5209432592450892, 'weight_xgb_class_2': 0.3787138893886167, 'weight_cat_class_0': 0.05958744170658028, 'weight_cat_class_1': 0.5520084828362744, 'weight_cat_class_2': 0.09168803348083315}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:52,841] Trial 1838 finished with value: 0.9491896554041337 and parameters: {'weight_lgbm_class_0': 0.06029332576785773, 'weight_lgbm_class_1': 0.6622711551289291, 'weight_lgbm_class_2': 0.8257336048366006, 'weight_xgb_class_0': 0.04594173735467734, 'weight_xgb_class_1': 0.5083824608346794, 'weight_xgb_class_2': 0.39254949190533717, 'weight_cat_class_0': 0.05552649488023287, 'weight_cat_class_1': 0.45722987838305695, 'weight_cat_class_2': 0.12731175670330533}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:52,913] Trial 1839 finished with value: 0.9496470068193913 and parameters: {'weight_lgbm_class_0': 0.06375262803318815, 'weight_lgbm_class_1': 0.6344334166004307, 'weight_lgbm_class_2': 0.8168515478722649, 'weight_xgb_class_0': 0.01772237033712271, 'weight_xgb_class_1': 0.5145586146608256, 'weight_xgb_class_2': 0.37772506686196317, 'weight_cat_class_0': 0.05685962670811838, 'weight_cat_class_1': 0.742676170608965, 'weight_cat_class_2': 0.1227888427725947}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:52,936] Trial 1840 finished with value: 0.9496365355031555 and parameters: {'weight_lgbm_class_0': 0.061859707815234206, 'weight_lgbm_class_1': 0.6658594272770777, 'weight_lgbm_class_2': 0.8504708417136083, 'weight_xgb_class_0': 0.02089943120103952, 'weight_xgb_class_1': 0.5166370102257223, 'weight_xgb_class_2': 0.38225912235471193, 'weight_cat_class_0': 0.056337619965156266, 'weight_cat_class_1': 0.4972836195202886, 'weight_cat_class_2': 0.12114599601480992}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:52,955] Trial 1841 finished with value: 0.949725160562152 and parameters: {'weight_lgbm_class_0': 0.06327975058628967, 'weight_lgbm_class_1': 0.6415805113096386, 'weight_lgbm_class_2': 0.8177560744782191, 'weight_xgb_class_0': 0.01860919156012019, 'weight_xgb_class_1': 0.5133211414902734, 'weight_xgb_class_2': 0.3568324513430422, 'weight_cat_class_0': 0.04571711243691254, 'weight_cat_class_1': 0.7379362330798416, 'weight_cat_class_2': 0.13954905939310466}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:53,051] Trial 1843 finished with value: 0.9492452411832919 and parameters: {'weight_lgbm_class_0': 0.0003995423797971409, 'weight_lgbm_class_1': 0.6663006987630584, 'weight_lgbm_class_2': 0.8226919564747308, 'weight_xgb_class_0': 0.018528514365807405, 'weight_xgb_class_1': 0.52006077337965, 'weight_xgb_class_2': 0.37241119864742456, 'weight_cat_class_0': 0.06031423070900288, 'weight_cat_class_1': 0.7366285118551895, 'weight_cat_class_2': 0.1190479364203593}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊          | 1843/2000 [01:17<00:07, 20.48it/s]

[I 2026-07-03 10:23:53,076] Trial 1842 finished with value: 0.9495956075291319 and parameters: {'weight_lgbm_class_0': 0.01323324821293111, 'weight_lgbm_class_1': 0.6624330438817609, 'weight_lgbm_class_2': 0.8192574539564013, 'weight_xgb_class_0': 0.01964496548039416, 'weight_xgb_class_1': 0.5272877338437542, 'weight_xgb_class_2': 0.3795018757393602, 'weight_cat_class_0': 0.05739153050035621, 'weight_cat_class_1': 0.5816358848223384, 'weight_cat_class_2': 0.11693622156856452}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 1848/2000 [01:17<00:09, 15.47it/s]

[I 2026-07-03 10:23:53,298] Trial 1844 finished with value: 0.9494884997688309 and parameters: {'weight_lgbm_class_0': 0.016583964935185304, 'weight_lgbm_class_1': 0.6627695339254348, 'weight_lgbm_class_2': 0.3623983553010569, 'weight_xgb_class_0': 0.018745538475564944, 'weight_xgb_class_1': 0.5347579950643271, 'weight_xgb_class_2': 0.3724957666592118, 'weight_cat_class_0': 0.05628111857183204, 'weight_cat_class_1': 0.47639877072131936, 'weight_cat_class_2': 0.11582738802505654}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:53,352] Trial 1845 finished with value: 0.9495802941747739 and parameters: {'weight_lgbm_class_0': 0.016239452036923785, 'weight_lgbm_class_1': 0.7053780089855564, 'weight_lgbm_class_2': 0.8553581180371883, 'weight_xgb_class_0': 0.018886881404112137, 'weight_xgb_class_1': 0.5288158010405906, 'weight_xgb_class_2': 0.3756023102735371, 'weight_cat_class_0': 0.05685098797067513, 'weight_cat_class_1': 0.5446306477959504, 'weight_cat_class_2': 0.11866894889445012}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:53,353] Trial 1846 finished with value: 0.9492995095769262 and parameters: {'weight_lgbm_class_0': 0.00042825033664543877, 'weight_lgbm_class_1': 0.7062491979746206, 'weight_lgbm_class_2': 0.864652847755994, 'weight_xgb_class_0': 0.019929926773869427, 'weight_xgb_class_1': 0.5357519727702554, 'weight_xgb_class_2': 0.3586949935429777, 'weight_cat_class_0': 0.058800413212298064, 'weight_cat_class_1': 0.6469500952321331, 'weight_cat_class_2': 0.11499382425513457}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:53,457] Trial 1848 finished with value: 0.9491964518730786 and parameters: {'weight_lgbm_class_0': 0.016278323466613037, 'weight_lgbm_class_1': 0.6680008074600013, 'weight_lgbm_class_2': 0.8092065705461227, 'weight_xgb_class_0': 0.019523645087560142, 'weight_xgb_class_1': 0.5544484171241749, 'weight_xgb_class_2': 0.36593819254778864, 'weight_cat_class_0': 0.03705835564626588, 'weight_cat_class_1': 0.6028480775780354, 'weight_cat_class_2': 0.11585530301531799}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:53,498] Trial 1847 finished with value: 0.9494942059144756 and parameters: {'weight_lgbm_class_0': 0.02492099785177545, 'weight_lgbm_class_1': 0.635852288315894, 'weight_lgbm_class_2': 0.7916858464681925, 'weight_xgb_class_0': 0.020641509036750355, 'weight_xgb_class_1': 0.46761643511372086, 'weight_xgb_class_2': 0.41127394171013554, 'weight_cat_class_0': 0.032569129897706856, 'weight_cat_class_1': 0.4746924455410857, 'weight_cat_class_2': 0.05650047394607165}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍         | 1853/2000 [01:17<00:08, 18.07it/s]

[I 2026-07-03 10:23:53,522] Trial 1849 finished with value: 0.9491565182576648 and parameters: {'weight_lgbm_class_0': 0.015721406528733203, 'weight_lgbm_class_1': 0.6331221064548903, 'weight_lgbm_class_2': 0.8052757931666602, 'weight_xgb_class_0': 0.0188934832190482, 'weight_xgb_class_1': 0.5552307375669769, 'weight_xgb_class_2': 0.4140463998850794, 'weight_cat_class_0': 0.03420736443635004, 'weight_cat_class_1': 0.5499333711680822, 'weight_cat_class_2': 0.04173830075984688}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:53,577] Trial 1850 finished with value: 0.9367649004258313 and parameters: {'weight_lgbm_class_0': 0.4227708302957112, 'weight_lgbm_class_1': 0.6672604026024673, 'weight_lgbm_class_2': 0.8634165668021044, 'weight_xgb_class_0': 0.018999775464588232, 'weight_xgb_class_1': 0.4726236227778931, 'weight_xgb_class_2': 0.40737680255240866, 'weight_cat_class_0': 0.03573168193113173, 'weight_cat_class_1': 0.7168399389748743, 'weight_cat_class_2': 0.026792443296293933}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:53,641] Trial 1851 finished with value: 0.9491907709141337 and parameters: {'weight_lgbm_class_0': 0.01748651236692034, 'weight_lgbm_class_1': 0.7091924712483386, 'weight_lgbm_class_2': 0.8697350380829769, 'weight_xgb_class_0': 0.024626227154066108, 'weight_xgb_class_1': 0.4743429454052064, 'weight_xgb_class_2': 0.3600122627552471, 'weight_cat_class_0': 0.03538168178492529, 'weight_cat_class_1': 0.7231503551571191, 'weight_cat_class_2': 0.16145705884345185}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:53,650] Trial 1852 finished with value: 0.9486539624904943 and parameters: {'weight_lgbm_class_0': 0.00028225151927173744, 'weight_lgbm_class_1': 0.6986576907899797, 'weight_lgbm_class_2': 0.8062225076560131, 'weight_xgb_class_0': 0.01871567704437157, 'weight_xgb_class_1': 0.5566028772171814, 'weight_xgb_class_2': 0.37143267252703227, 'weight_cat_class_0': 0.03768750995969991, 'weight_cat_class_1': 0.5335284652304083, 'weight_cat_class_2': 0.027637652481736594}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:53,680] Trial 1853 finished with value: 0.9488355181869982 and parameters: {'weight_lgbm_class_0': 0.0014641470357708575, 'weight_lgbm_class_1': 0.7057679733423778, 'weight_lgbm_class_2': 0.8134576449865913, 'weight_xgb_class_0': 0.022288963729293926, 'weight_xgb_class_1': 0.5549000015650042, 'weight_xgb_class_2': 0.40980309921521324, 'weight_cat_class_0': 0.03704495918121948, 'weight_cat_class_1': 0.5123475500986848, 'weight_cat_class_2': 0.04149963359770503}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋         | 1856/2000 [01:17<00:06, 21.19it/s]

[I 2026-07-03 10:23:53,737] Trial 1855 finished with value: 0.9496508789655613 and parameters: {'weight_lgbm_class_0': 0.027904003130929986, 'weight_lgbm_class_1': 0.6203476590692081, 'weight_lgbm_class_2': 0.8653676840380808, 'weight_xgb_class_0': 0.03309549271929042, 'weight_xgb_class_1': 0.5553361835580942, 'weight_xgb_class_2': 0.4084366136566621, 'weight_cat_class_0': 0.03442712279518527, 'weight_cat_class_1': 0.5821390937771813, 'weight_cat_class_2': 0.05288166717971178}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:53,751] Trial 1854 finished with value: 0.9495592710797495 and parameters: {'weight_lgbm_class_0': 0.02409260475182108, 'weight_lgbm_class_1': 0.7095555311496413, 'weight_lgbm_class_2': 0.8663601661337694, 'weight_xgb_class_0': 0.0356730791907636, 'weight_xgb_class_1': 0.4712286096770032, 'weight_xgb_class_2': 0.4322320659190377, 'weight_cat_class_0': 0.034254030364016176, 'weight_cat_class_1': 0.6185309735733246, 'weight_cat_class_2': 0.16746975686433185}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 1859/2000 [01:18<00:09, 15.00it/s]

[I 2026-07-03 10:23:53,988] Trial 1856 finished with value: 0.9496210560403765 and parameters: {'weight_lgbm_class_0': 0.018477938267337835, 'weight_lgbm_class_1': 0.639949052933445, 'weight_lgbm_class_2': 0.8691132575711297, 'weight_xgb_class_0': 0.036833049384789096, 'weight_xgb_class_1': 0.47372541159313664, 'weight_xgb_class_2': 0.41094047650734045, 'weight_cat_class_0': 0.03556375198952522, 'weight_cat_class_1': 0.5067071686244806, 'weight_cat_class_2': 0.04100508141408471}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:54,063] Trial 1857 finished with value: 0.9487721843274511 and parameters: {'weight_lgbm_class_0': 0.1124651752117421, 'weight_lgbm_class_1': 0.6150130297880899, 'weight_lgbm_class_2': 0.7966230570381514, 'weight_xgb_class_0': 0.040478692378031304, 'weight_xgb_class_1': 0.5538145034993425, 'weight_xgb_class_2': 0.4112950140245704, 'weight_cat_class_0': 0.03050582669271956, 'weight_cat_class_1': 0.5625154100015732, 'weight_cat_class_2': 0.0661522481962108}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:54,106] Trial 1858 finished with value: 0.9487502749125252 and parameters: {'weight_lgbm_class_0': 0.11069485000914063, 'weight_lgbm_class_1': 0.6149134133417444, 'weight_lgbm_class_2': 0.8649813826583325, 'weight_xgb_class_0': 0.03736626519797974, 'weight_xgb_class_1': 0.4783080448920231, 'weight_xgb_class_2': 0.40953147816379926, 'weight_cat_class_0': 0.03472566199667386, 'weight_cat_class_1': 0.5256027028832919, 'weight_cat_class_2': 0.037598642208854574}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:54,146] Trial 1859 finished with value: 0.9495364543786686 and parameters: {'weight_lgbm_class_0': 0.041837095056468876, 'weight_lgbm_class_1': 0.6175038612482558, 'weight_lgbm_class_2': 0.8679704372289568, 'weight_xgb_class_0': 0.0360910528897489, 'weight_xgb_class_1': 0.5517071440753347, 'weight_xgb_class_2': 0.4093516444238263, 'weight_cat_class_0': 0.00044446187821925627, 'weight_cat_class_1': 0.1323869038083293, 'weight_cat_class_2': 0.044646068474840886}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎        | 1867/2000 [01:18<00:06, 19.44it/s]

[I 2026-07-03 10:23:54,258] Trial 1862 finished with value: 0.9487985768866084 and parameters: {'weight_lgbm_class_0': 0.11321546538997682, 'weight_lgbm_class_1': 0.7066026895062948, 'weight_lgbm_class_2': 0.7874994516986291, 'weight_xgb_class_0': 0.0418793664550844, 'weight_xgb_class_1': 0.4858818129831163, 'weight_xgb_class_2': 0.4358854168516835, 'weight_cat_class_0': 0.034918227564858816, 'weight_cat_class_1': 0.530794610503745, 'weight_cat_class_2': 0.14651560053342588}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:54,259] Trial 1860 finished with value: 0.9494349404252019 and parameters: {'weight_lgbm_class_0': 0.11028177371047994, 'weight_lgbm_class_1': 0.706744068776352, 'weight_lgbm_class_2': 0.8691518530071646, 'weight_xgb_class_0': 0.04163333754723718, 'weight_xgb_class_1': 0.478695817995587, 'weight_xgb_class_2': 0.43514004363498304, 'weight_cat_class_0': 7.483633781274479e-05, 'weight_cat_class_1': 0.49104265242556544, 'weight_cat_class_2': 0.06474476592446231}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:54,260] Trial 1861 finished with value: 0.9487838151575542 and parameters: {'weight_lgbm_class_0': 0.11267107544359067, 'weight_lgbm_class_1': 0.7054674678925341, 'weight_lgbm_class_2': 0.7960355743637911, 'weight_xgb_class_0': 0.046469733548768655, 'weight_xgb_class_1': 0.4806894919854663, 'weight_xgb_class_2': 0.43699360664437875, 'weight_cat_class_0': 0.03105359414050632, 'weight_cat_class_1': 0.5432408050176045, 'weight_cat_class_2': 0.08423790476246217}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:54,303] Trial 1863 finished with value: 0.9495450206264678 and parameters: {'weight_lgbm_class_0': 0.11163408891095805, 'weight_lgbm_class_1': 0.6217091402590919, 'weight_lgbm_class_2': 0.8752575291294488, 'weight_xgb_class_0': 0.0441232647598278, 'weight_xgb_class_1': 0.4869799078571242, 'weight_xgb_class_2': 0.4357868362924298, 'weight_cat_class_0': 0.000771911143578545, 'weight_cat_class_1': 0.8502207262964452, 'weight_cat_class_2': 0.1567665284748528}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:54,337] Trial 1864 finished with value: 0.9488912123026187 and parameters: {'weight_lgbm_class_0': 0.11017650552876232, 'weight_lgbm_class_1': 0.6218142503766432, 'weight_lgbm_class_2': 0.8721990683614866, 'weight_xgb_class_0': 0.04640993588647585, 'weight_xgb_class_1': 0.4848569688083711, 'weight_xgb_class_2': 0.43369838819239737, 'weight_cat_class_0': 0.0338850549352939, 'weight_cat_class_1': 0.5817724031455059, 'weight_cat_class_2': 0.15206808444726305}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:54,355] Trial 1865 finished with value: 0.9495139498427712 and parameters: {'weight_lgbm_class_0': 0.10893318459955126, 'weight_lgbm_class_1': 0.6170664232962378, 'weight_lgbm_class_2': 0.789372588349241, 'weight_xgb_class_0': 0.042076603475389066, 'weight_xgb_class_1': 0.4919749409756968, 'weight_xgb_class_2': 0.43606090592555213, 'weight_cat_class_0': 0.0006432674059652727, 'weight_cat_class_1': 0.8474377993880509, 'weight_cat_class_2': 0.1520966403311415}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:54,391] Trial 1866 finished with value: 0.9487089409408892 and parameters: {'weight_lgbm_class_0': 0.11380878622998987, 'weight_lgbm_class_1': 0.611933420427696, 'weight_lgbm_class_2': 0.7860014385955502, 'weight_xgb_class_0': 0.06417015455320242, 'weight_xgb_class_1': 0.49138988924229554, 'weight_xgb_class_2': 0.43346097524277366, 'weight_cat_class_0': 0.015765362966215814, 'weight_cat_class_1': 0.7092587640267408, 'weight_cat_class_2': 0.07231120119974396}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:54,437] Trial 1867 finished with value: 0.9491502475569522 and parameters: {'weight_lgbm_class_0': 0.10978191298588302, 'weight_lgbm_class_1': 0.745846374026398, 'weight_lgbm_class_2': 0.8511490946321364, 'weight_xgb_class_0': 0.04926569249683781, 'weight_xgb_class_1': 0.4886473688654341, 'weight_xgb_class_2': 0.4343257721206497, 'weight_cat_class_0': 0.014936545545486462, 'weight_cat_class_1': 0.579580828061602, 'weight_cat_class_2': 0.08904799434901356}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌        | 1870/2000 [01:18<00:07, 16.67it/s]

[I 2026-07-03 10:23:54,649] Trial 1868 finished with value: 0.9490238730478358 and parameters: {'weight_lgbm_class_0': 0.11009622896191573, 'weight_lgbm_class_1': 0.7442526588634767, 'weight_lgbm_class_2': 0.7805483579740825, 'weight_xgb_class_0': 0.0649841417204842, 'weight_xgb_class_1': 0.4926746725970272, 'weight_xgb_class_2': 0.43092966244636205, 'weight_cat_class_0': 0.0016500076147980998, 'weight_cat_class_1': 0.5611229788040837, 'weight_cat_class_2': 0.15091262394935162}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:54,750] Trial 1869 finished with value: 0.9489747507418285 and parameters: {'weight_lgbm_class_0': 0.11093205123262859, 'weight_lgbm_class_1': 0.7459404140169313, 'weight_lgbm_class_2': 0.7854262866953301, 'weight_xgb_class_0': 0.05358015533590528, 'weight_xgb_class_1': 0.4896905296051048, 'weight_xgb_class_2': 0.43616960322517306, 'weight_cat_class_0': 0.016739625951456623, 'weight_cat_class_1': 0.5281592277025655, 'weight_cat_class_2': 0.157579084741443}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:54,817] Trial 1870 finished with value: 0.9492847776445283 and parameters: {'weight_lgbm_class_0': 0.08450030211206846, 'weight_lgbm_class_1': 0.7475115409507327, 'weight_lgbm_class_2': 0.8464857537621442, 'weight_xgb_class_0': 0.06082257508728494, 'weight_xgb_class_1': 0.4914216105818135, 'weight_xgb_class_2': 0.4345583322105857, 'weight_cat_class_0': 0.015798886005126404, 'weight_cat_class_1': 0.6323035962119038, 'weight_cat_class_2': 0.08268192964339599}. Best is trial 1765 with value: 0.9497917773888238.

[I 2026-07-03 10:23:54,865] Trial 1871 finished with value: 0.9481947657415395 and parameters: {'weight_lgbm_class_0': 0.0800407460665669, 'weight_lgbm_class_1': 0.7463303831628378, 'weight_lgbm_class_2': 0.8377127690269577, 'weight_xgb_class_0': 0.06385348038279784, 'weight_xgb_class_1': 0.4920128642908327, 'weight_xgb_class_2': 0.43416503904241277, 'weight_cat_class_0': 0.08829430104696687, 'weight_cat_class_1': 0.8538636838173831, 'weight_cat_class_2': 0.08786850331475675}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:54,958] Trial 1873 finished with value: 0.9480434137429684 and parameters: {'weight_lgbm_class_0': 0.08463867345648063, 'weight_lgbm_class_1': 0.7486710856328307, 'weight_lgbm_class_2': 0.8431378513659018, 'weight_xgb_class_0': 0.063733110260725, 'weight_xgb_class_1': 0.4565801454717149, 'weight_xgb_class_2': 0.44311108132160426, 'weight_cat_class_0': 0.08801774146031523, 'weight_cat_class_1': 0.6336242933490629, 'weight_cat_class_2': 0.10524680305884036}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:54,979] Trial 1872 finished with value: 0.9478723668440344 and parameters: {'weight_lgbm_class_0': 0.08426158620203253, 'weight_lgbm_class_1': 0.6791486194789473, 'weight_lgbm_class_2': 0.8491473652697228, 'weight_xgb_class_0': 0.06471057512940137, 'weight_xgb_class_1': 0.45084513843354695, 'weight_xgb_class_2': 0.4385613104078996, 'weight_cat_class_0': 0.09047070479849462, 'weight_cat_class_1': 0.711397734616185, 'weight_cat_class_2': 0.0865675562140813}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:55,004] Trial 1875 finished with value: 0.9491303436108365 and parameters: {'weight_lgbm_class_0': 0.0802950216483435, 'weight_lgbm_class_1': 0.7478846476935253, 'weight_lgbm_class_2': 0.8435213689524471, 'weight_xgb_class_0': 0.0005539392633046036, 'weight_xgb_class_1': 0.4477137276567823, 'weight_xgb_class_2': 0.44009792685324073, 'weight_cat_class_0': 0.09232072744404689, 'weight_cat_class_1': 0.5703771898036759, 'weight_cat_class_2': 0.09147051856826588}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:55,014] Trial 1874 finished with value: 0.9486545944572046 and parameters: {'weight_lgbm_class_0': 0.08141827303000485, 'weight_lgbm_class_1': 0.7470416613179499, 'weight_lgbm_class_2': 0.8412769859117628, 'weight_xgb_class_0': 0.06787328624722146, 'weight_xgb_class_1': 0.37416370272960864, 'weight_xgb_class_2': 0.6514165609696427, 'weight_cat_class_0': 0.08477429272282702, 'weight_cat_class_1': 0.7631977937815433, 'weight_cat_class_2': 0.18727041081006474}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:55,041] Trial 1877 finished with value: 0.9402744062099795 and parameters: {'weight_lgbm_class_0': 0.0732068553679627, 'weight_lgbm_class_1': 0.7449917511449062, 'weight_lgbm_class_2': 0.733423128476819, 'weight_xgb_class_0': 0.0005247870964795662, 'weight_xgb_class_1': 0.44738745476302155, 'weight_xgb_class_2': 0.4453166515802115, 'weight_cat_class_0': 0.3479991297329357, 'weight_cat_class_1': 0.7643719575508223, 'weight_cat_class_2': 0.07734645132755735}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎       | 1881/2000 [01:19<00:06, 18.64it/s]

[I 2026-07-03 10:23:55,074] Trial 1876 finished with value: 0.9481919015087029 and parameters: {'weight_lgbm_class_0': 0.0802473301731029, 'weight_lgbm_class_1': 0.7465692345505532, 'weight_lgbm_class_2': 0.8422147858799056, 'weight_xgb_class_0': 0.05998718774967341, 'weight_xgb_class_1': 0.45142958397794514, 'weight_xgb_class_2': 0.447060837112802, 'weight_cat_class_0': 0.08821514084880419, 'weight_cat_class_1': 0.6416516069168618, 'weight_cat_class_2': 0.08418876784751178}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:55,098] Trial 1879 finished with value: 0.9493845429721715 and parameters: {'weight_lgbm_class_0': 0.07917368323041588, 'weight_lgbm_class_1': 0.740792178405606, 'weight_lgbm_class_2': 0.923460393596072, 'weight_xgb_class_0': 0.0006549442023462901, 'weight_xgb_class_1': 0.5384173607521229, 'weight_xgb_class_2': 0.44631670884210123, 'weight_cat_class_0': 0.0885978926439018, 'weight_cat_class_1': 0.715454846795634, 'weight_cat_class_2': 0.10871108605024454}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:55,105] Trial 1878 finished with value: 0.9480551626120416 and parameters: {'weight_lgbm_class_0': 0.07962429151181871, 'weight_lgbm_class_1': 0.7389404071472688, 'weight_lgbm_class_2': 0.8402024618403716, 'weight_xgb_class_0': 0.06720418630870667, 'weight_xgb_class_1': 0.45411615616714884, 'weight_xgb_class_2': 0.4494695980310372, 'weight_cat_class_0': 0.08825223890401873, 'weight_cat_class_1': 0.4312538845333975, 'weight_cat_class_2': 0.1823369122394658}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:55,311] Trial 1880 finished with value: 0.9493565058042632 and parameters: {'weight_lgbm_class_0': 0.0854328007956828, 'weight_lgbm_class_1': 0.6743548609797421, 'weight_lgbm_class_2': 0.8379389712338036, 'weight_xgb_class_0': 1.3880751119119128e-05, 'weight_xgb_class_1': 0.45909662937390056, 'weight_xgb_class_2': 0.44829344060465737, 'weight_cat_class_0': 0.08164161098230036, 'weight_cat_class_1': 0.7621683300912442, 'weight_cat_class_2': 0.19192321724725175}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍       | 1884/2000 [01:19<00:07, 15.76it/s]

[I 2026-07-03 10:23:55,397] Trial 1881 finished with value: 0.9076672019514502 and parameters: {'weight_lgbm_class_0': 0.08318768446819642, 'weight_lgbm_class_1': 0.7735816749554371, 'weight_lgbm_class_2': 0.8409776521687696, 'weight_xgb_class_0': 0.00012780413090591005, 'weight_xgb_class_1': 0.45014811064023913, 'weight_xgb_class_2': 0.4500032238782294, 'weight_cat_class_0': 0.9223929537749349, 'weight_cat_class_1': 0.7185901819647464, 'weight_cat_class_2': 0.09503337955970574}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:55,515] Trial 1882 finished with value: 0.9471000980720105 and parameters: {'weight_lgbm_class_0': 0.043726733080661474, 'weight_lgbm_class_1': 0.6790600986296138, 'weight_lgbm_class_2': 0.8334018366283817, 'weight_xgb_class_0': 6.365746180768525e-05, 'weight_xgb_class_1': 0.45019327846325535, 'weight_xgb_class_2': 0.6631496823968437, 'weight_cat_class_0': 5.4296894220574876e-05, 'weight_cat_class_1': 0.6203713225925961, 'weight_cat_class_2': 0.2351335492867352}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:55,563] Trial 1883 finished with value: 0.9492792269578825 and parameters: {'weight_lgbm_class_0': 0.05045986121411223, 'weight_lgbm_class_1': 0.6678648572693217, 'weight_lgbm_class_2': 0.9245469768002346, 'weight_xgb_class_0': 0.06966141977855841, 'weight_xgb_class_1': 0.4522345097323324, 'weight_xgb_class_2': 0.4497351765712349, 'weight_cat_class_0': 0.08217866882520872, 'weight_cat_class_1': 0.7579295050310421, 'weight_cat_class_2': 0.4720078042852405}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 1889/2000 [01:20<00:06, 18.28it/s]

[I 2026-07-03 10:23:55,643] Trial 1884 finished with value: 0.9484076761872059 and parameters: {'weight_lgbm_class_0': 0.04402487028065851, 'weight_lgbm_class_1': 0.5674482870397607, 'weight_lgbm_class_2': 0.7384825820571266, 'weight_xgb_class_0': 0.001525124096135106, 'weight_xgb_class_1': 0.5367351286616627, 'weight_xgb_class_2': 0.46080998091129893, 'weight_cat_class_0': 0.017885442195675855, 'weight_cat_class_1': 0.7639264592020745, 'weight_cat_class_2': 0.4634665098035957}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:55,690] Trial 1885 finished with value: 0.9482297704606143 and parameters: {'weight_lgbm_class_0': 0.04283499557800313, 'weight_lgbm_class_1': 0.566206984214145, 'weight_lgbm_class_2': 0.9345621402259884, 'weight_xgb_class_0': 0.01642523617403026, 'weight_xgb_class_1': 0.5375814740685981, 'weight_xgb_class_2': 0.4571036230437148, 'weight_cat_class_0': 0.00036224144337082195, 'weight_cat_class_1': 0.4245950027474097, 'weight_cat_class_2': 0.473755812841795}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:55,730] Trial 1887 finished with value: 0.9496154019587563 and parameters: {'weight_lgbm_class_0': 0.04169421436189166, 'weight_lgbm_class_1': 0.6749162445683581, 'weight_lgbm_class_2': 0.9203565054768917, 'weight_xgb_class_0': 0.013577153257194989, 'weight_xgb_class_1': 0.5462155436016509, 'weight_xgb_class_2': 0.4619999167179717, 'weight_cat_class_0': 0.052253264812203035, 'weight_cat_class_1': 0.7563201486258437, 'weight_cat_class_2': 0.18371957405838718}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:55,757] Trial 1888 finished with value: 0.9497637818450322 and parameters: {'weight_lgbm_class_0': 0.04454404745610187, 'weight_lgbm_class_1': 0.7752432210013033, 'weight_lgbm_class_2': 0.9282680861875351, 'weight_xgb_class_0': 0.01759530266285918, 'weight_xgb_class_1': 0.5321225762588873, 'weight_xgb_class_2': 0.467054782848718, 'weight_cat_class_0': 0.06104705103450725, 'weight_cat_class_1': 0.7623384964384077, 'weight_cat_class_2': 0.22064192492355827}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:55,764] Trial 1886 finished with value: 0.9483955941452048 and parameters: {'weight_lgbm_class_0': 0.047768243152371374, 'weight_lgbm_class_1': 0.6735620873936757, 'weight_lgbm_class_2': 0.9270219803554979, 'weight_xgb_class_0': 0.015269244860066852, 'weight_xgb_class_1': 0.5393598591335239, 'weight_xgb_class_2': 0.4636223699586666, 'weight_cat_class_0': 3.347918755947782e-05, 'weight_cat_class_1': 0.762799076097383, 'weight_cat_class_2': 0.1850944631652227}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:55,821] Trial 1890 finished with value: 0.9493386187794046 and parameters: {'weight_lgbm_class_0': 0.04308385934208625, 'weight_lgbm_class_1': 0.5393561123930611, 'weight_lgbm_class_2': 0.9274983445412686, 'weight_xgb_class_0': 0.0009424408522714298, 'weight_xgb_class_1': 0.4153073672154676, 'weight_xgb_class_2': 0.4714516644075952, 'weight_cat_class_0': 0.05580181244912171, 'weight_cat_class_1': 0.7662720170996421, 'weight_cat_class_2': 0.4391565934857795}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 1892/2000 [01:20<00:05, 19.77it/s]

[I 2026-07-03 10:23:55,886] Trial 1889 finished with value: 0.9470819743547665 and parameters: {'weight_lgbm_class_0': 0.044722605144862246, 'weight_lgbm_class_1': 0.5729125095823813, 'weight_lgbm_class_2': 0.939101747263002, 'weight_xgb_class_0': 0.2216583809490142, 'weight_xgb_class_1': 0.5481353458476829, 'weight_xgb_class_2': 0.46125050193471706, 'weight_cat_class_0': 0.05770759281149819, 'weight_cat_class_1': 0.7619230648535037, 'weight_cat_class_2': 0.4957192460599086}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:55,911] Trial 1891 finished with value: 0.9234265691739965 and parameters: {'weight_lgbm_class_0': 0.04034695429046238, 'weight_lgbm_class_1': 0.7755610785209434, 'weight_lgbm_class_2': 0.9260262394465252, 'weight_xgb_class_0': 0.017039746195338327, 'weight_xgb_class_1': 0.41619860288214156, 'weight_xgb_class_2': 0.41241297834105584, 'weight_cat_class_0': 0.8525571742955178, 'weight_cat_class_1': 0.9984965873570248, 'weight_cat_class_2': 0.43596124908032774}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:56,007] Trial 1892 finished with value: 0.9476664012052876 and parameters: {'weight_lgbm_class_0': 0.0504347673183139, 'weight_lgbm_class_1': 0.7745713041060129, 'weight_lgbm_class_2': 0.9293161700227178, 'weight_xgb_class_0': 0.2252302882233327, 'weight_xgb_class_1': 0.40755689243657556, 'weight_xgb_class_2': 0.46999471875842924, 'weight_cat_class_0': 0.05586533139478615, 'weight_cat_class_1': 0.7329597672476481, 'weight_cat_class_2': 0.8790553433744213}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 1895/2000 [01:20<00:06, 15.03it/s]

[I 2026-07-03 10:23:56,123] Trial 1893 finished with value: 0.9485915862876406 and parameters: {'weight_lgbm_class_0': 0.041618549228887844, 'weight_lgbm_class_1': 0.6425337683230877, 'weight_lgbm_class_2': 0.7147911990802527, 'weight_xgb_class_0': 0.024032200306384355, 'weight_xgb_class_1': 0.41527451797822923, 'weight_xgb_class_2': 0.4673165461236464, 'weight_cat_class_0': 2.5125123821251674e-05, 'weight_cat_class_1': 0.6887860400918663, 'weight_cat_class_2': 0.4325302498306578}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:56,224] Trial 1894 finished with value: 0.9276046425796359 and parameters: {'weight_lgbm_class_0': 0.6871014708996296, 'weight_lgbm_class_1': 0.5769760739088363, 'weight_lgbm_class_2': 0.7350784714241877, 'weight_xgb_class_0': 0.017454732166820246, 'weight_xgb_class_1': 0.5370902983607642, 'weight_xgb_class_2': 0.467113543116119, 'weight_cat_class_0': 0.06207743651651164, 'weight_cat_class_1': 0.9978650132604526, 'weight_cat_class_2': 0.4325443568127742}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:56,332] Trial 1896 finished with value: 0.9403537336515475 and parameters: {'weight_lgbm_class_0': 0.4667652640742651, 'weight_lgbm_class_1': 0.717560600076315, 'weight_lgbm_class_2': 0.7159116147529547, 'weight_xgb_class_0': 0.018178373358635105, 'weight_xgb_class_1': 0.3810859247767474, 'weight_xgb_class_2': 0.4685837692806156, 'weight_cat_class_0': 0.0003160969177027906, 'weight_cat_class_1': 0.6966300510206017, 'weight_cat_class_2': 0.49475115194890046}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 1900/2000 [01:20<00:06, 16.30it/s]

[I 2026-07-03 10:23:56,344] Trial 1895 finished with value: 0.9464598896400505 and parameters: {'weight_lgbm_class_0': 0.04296141149720725, 'weight_lgbm_class_1': 0.57214363732024, 'weight_lgbm_class_2': 0.7429637604592598, 'weight_xgb_class_0': 5.566824239144723e-05, 'weight_xgb_class_1': 0.5368910320758362, 'weight_xgb_class_2': 0.46734746678938877, 'weight_cat_class_0': 0.0003897952292504772, 'weight_cat_class_1': 0.9997864817640043, 'weight_cat_class_2': 0.44482905466522754}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:56,420] Trial 1897 finished with value: 0.948704091555404 and parameters: {'weight_lgbm_class_0': 0.15301374407024532, 'weight_lgbm_class_1': 0.6419797444897811, 'weight_lgbm_class_2': 0.8151568555940454, 'weight_xgb_class_0': 0.034743371086755896, 'weight_xgb_class_1': 0.5060223672169841, 'weight_xgb_class_2': 0.46866979159129496, 'weight_cat_class_0': 0.05185363764288991, 'weight_cat_class_1': 0.732148932799529, 'weight_cat_class_2': 0.44558587733099864}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:56,445] Trial 1899 finished with value: 0.9491264517039794 and parameters: {'weight_lgbm_class_0': 0.038278638435074924, 'weight_lgbm_class_1': 0.7720012824751428, 'weight_lgbm_class_2': 0.9435335036141581, 'weight_xgb_class_0': 0.037204579378816466, 'weight_xgb_class_1': 0.5022466792903382, 'weight_xgb_class_2': 0.4705321729020831, 'weight_cat_class_0': 0.12949973299434606, 'weight_cat_class_1': 0.7285164597733578, 'weight_cat_class_2': 0.23848090424286997}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:56,446] Trial 1898 finished with value: 0.948801531808133 and parameters: {'weight_lgbm_class_0': 0.14730330388135932, 'weight_lgbm_class_1': 0.7123607136258345, 'weight_lgbm_class_2': 0.8176542016984002, 'weight_xgb_class_0': 0.030094056027355782, 'weight_xgb_class_1': 0.5655033003319127, 'weight_xgb_class_2': 0.4071229413330249, 'weight_cat_class_0': 0.05525812859471749, 'weight_cat_class_1': 0.7285480621158228, 'weight_cat_class_2': 0.4309993138412761}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:56,532] Trial 1900 finished with value: 0.9494112365948779 and parameters: {'weight_lgbm_class_0': 0.03214495428292535, 'weight_lgbm_class_1': 0.3301599416894864, 'weight_lgbm_class_2': 0.9573460686396296, 'weight_xgb_class_0': 1.6314755808311682e-05, 'weight_xgb_class_1': 0.5093981693461748, 'weight_xgb_class_2': 0.47435879053835245, 'weight_cat_class_0': 0.061761340468918464, 'weight_cat_class_1': 0.7351668731062048, 'weight_cat_class_2': 0.19149290064275426}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 1904/2000 [01:20<00:05, 17.97it/s]

[I 2026-07-03 10:23:56,549] Trial 1901 finished with value: 0.9494403518218414 and parameters: {'weight_lgbm_class_0': 0.045374548034493284, 'weight_lgbm_class_1': 0.7255841980253733, 'weight_lgbm_class_2': 0.9711134289458507, 'weight_xgb_class_0': 0.0319719911127959, 'weight_xgb_class_1': 0.5083602406250793, 'weight_xgb_class_2': 0.47177778645468477, 'weight_cat_class_0': 0.10170333286788706, 'weight_cat_class_1': 0.7478119698950502, 'weight_cat_class_2': 0.22418116220726425}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:56,635] Trial 1903 finished with value: 0.9493553539697558 and parameters: {'weight_lgbm_class_0': 0.023854939714679807, 'weight_lgbm_class_1': 0.779631707472826, 'weight_lgbm_class_2': 0.9610084542012495, 'weight_xgb_class_0': 0.034917047250782283, 'weight_xgb_class_1': 0.5109386681116449, 'weight_xgb_class_2': 0.4706605533707342, 'weight_cat_class_0': 0.13273144379937832, 'weight_cat_class_1': 0.7347122781352872, 'weight_cat_class_2': 0.21533618889775685}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:56,638] Trial 1902 finished with value: 0.9492999577970851 and parameters: {'weight_lgbm_class_0': 0.02901445912482178, 'weight_lgbm_class_1': 0.7713877041526722, 'weight_lgbm_class_2': 0.9401221258369635, 'weight_xgb_class_0': 0.03363398950428644, 'weight_xgb_class_1': 0.5077588199587975, 'weight_xgb_class_2': 0.4722439059996743, 'weight_cat_class_0': 0.130277708833967, 'weight_cat_class_1': 0.7357374124157496, 'weight_cat_class_2': 0.24626055475999437}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:56,734] Trial 1904 finished with value: 0.9493257784147769 and parameters: {'weight_lgbm_class_0': 0.026109125344947543, 'weight_lgbm_class_1': 0.7192328031786366, 'weight_lgbm_class_2': 0.944009789013699, 'weight_xgb_class_0': 0.03441775408205073, 'weight_xgb_class_1': 0.5116100394013436, 'weight_xgb_class_2': 0.4730775048526676, 'weight_cat_class_0': 0.12696460425230305, 'weight_cat_class_1': 0.7343123772604837, 'weight_cat_class_2': 0.24308558570522895}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████      | 1908/2000 [01:21<00:05, 15.76it/s]

[I 2026-07-03 10:23:56,831] Trial 1905 finished with value: 0.9496224442376072 and parameters: {'weight_lgbm_class_0': 0.016518572273931664, 'weight_lgbm_class_1': 0.7659912670613722, 'weight_lgbm_class_2': 0.9561160811649155, 'weight_xgb_class_0': 0.03589341723151839, 'weight_xgb_class_1': 0.969476365565128, 'weight_xgb_class_2': 0.47928552311178796, 'weight_cat_class_0': 0.06824814590031424, 'weight_cat_class_1': 0.7436758144018774, 'weight_cat_class_2': 0.24458852355271188}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:56,931] Trial 1906 finished with value: 0.9495069444284744 and parameters: {'weight_lgbm_class_0': 0.029523510113556854, 'weight_lgbm_class_1': 0.7211298297374811, 'weight_lgbm_class_2': 0.9550048280466282, 'weight_xgb_class_0': 0.04222507724245721, 'weight_xgb_class_1': 0.519623443960937, 'weight_xgb_class_2': 0.47504284031794364, 'weight_cat_class_0': 0.10017231495225394, 'weight_cat_class_1': 0.7331926291889996, 'weight_cat_class_2': 0.24355102219097088}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:56,995] Trial 1907 finished with value: 0.9495973786911521 and parameters: {'weight_lgbm_class_0': 0.022181802243885912, 'weight_lgbm_class_1': 0.7697084910305749, 'weight_lgbm_class_2': 0.9500637040697829, 'weight_xgb_class_0': 0.03492509237145178, 'weight_xgb_class_1': 0.5014653021334337, 'weight_xgb_class_2': 0.4866197132113552, 'weight_cat_class_0': 0.10980459969911266, 'weight_cat_class_1': 0.7350669587065031, 'weight_cat_class_2': 0.24442838674481518}. Best is trial 1765 with value: 0.9497917773888238.

[I 2026-07-03 10:23:57,113] Trial 1908 finished with value: 0.9496017930998898 and parameters: {'weight_lgbm_class_0': 0.021567800702825584, 'weight_lgbm_class_1': 0.7254497437510564, 'weight_lgbm_class_2': 0.9524825849620917, 'weight_xgb_class_0': 0.034387636023586375, 'weight_xgb_class_1': 0.5018443822906665, 'weight_xgb_class_2': 0.4800483064397502, 'weight_cat_class_0': 0.11329202988536219, 'weight_cat_class_1': 0.7476849696800825, 'weight_cat_class_2': 0.23506084927546544}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:57,151] Trial 1910 finished with value: 0.9488407456695961 and parameters: {'weight_lgbm_class_0': 0.03346809466787305, 'weight_lgbm_class_1': 0.7686335285923614, 'weight_lgbm_class_2': 0.942266237892276, 'weight_xgb_class_0': 0.07981939669315222, 'weight_xgb_class_1': 0.5121879625819662, 'weight_xgb_class_2': 0.5011328237151625, 'weight_cat_class_0': 0.115137139137378, 'weight_cat_class_1': 0.7408490025158858, 'weight_cat_class_2': 0.21697526689922406}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:57,205] Trial 1909 finished with value: 0.9493654523238594 and parameters: {'weight_lgbm_class_0': 0.02439046354086994, 'weight_lgbm_class_1': 0.7619798850351451, 'weight_lgbm_class_2': 0.9613881969752692, 'weight_xgb_class_0': 0.07825367610965209, 'weight_xgb_class_1': 0.5066700542281887, 'weight_xgb_class_2': 0.4936942046091092, 'weight_cat_class_0': 0.08060804050823696, 'weight_cat_class_1': 0.7459691943165107, 'weight_cat_class_2': 0.19932469580374976}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:57,238] Trial 1911 finished with value: 0.9480313687711149 and parameters: {'weight_lgbm_class_0': 0.056517431639592386, 'weight_lgbm_class_1': 0.766106071004406, 'weight_lgbm_class_2': 0.9120434992487668, 'weight_xgb_class_0': 0.0819579862334357, 'weight_xgb_class_1': 0.5061284890872035, 'weight_xgb_class_2': 0.49285737869165513, 'weight_cat_class_0': 0.1364370451503999, 'weight_cat_class_1': 0.7722319386276342, 'weight_cat_class_2': 0.20699286400369626}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:57,240] Trial 1912 finished with value: 0.923118513450787 and parameters: {'weight_lgbm_class_0': 0.018842140697970692, 'weight_lgbm_class_1': 0.7700480610962549, 'weight_lgbm_class_2': 0.8902440309857954, 'weight_xgb_class_0': 0.08648074812779319, 'weight_xgb_class_1': 0.5006495168898338, 'weight_xgb_class_2': 0.49082550638222655, 'weight_cat_class_0': 0.733938390845441, 'weight_cat_class_1': 0.7718916409893016, 'weight_cat_class_2': 0.24460321234544738}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:57,267] Trial 1913 finished with value: 0.9494861424764233 and parameters: {'weight_lgbm_class_0': 0.017014223669098355, 'weight_lgbm_class_1': 0.7639190637911278, 'weight_lgbm_class_2': 0.9094490541098441, 'weight_xgb_class_0': 0.08570794369405697, 'weight_xgb_class_1': 0.5240951947824211, 'weight_xgb_class_2': 0.5033362962802695, 'weight_cat_class_0': 0.07146797900954892, 'weight_cat_class_1': 0.7755692590960996, 'weight_cat_class_2': 0.2199125795131876}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 1917/2000 [01:21<00:03, 21.16it/s]

[I 2026-07-03 10:23:57,336] Trial 1915 finished with value: 0.94905733462706 and parameters: {'weight_lgbm_class_0': 0.022955434421070828, 'weight_lgbm_class_1': 0.7250715301927194, 'weight_lgbm_class_2': 0.946134557290198, 'weight_xgb_class_0': 0.08101505214961878, 'weight_xgb_class_1': 0.5223951162929502, 'weight_xgb_class_2': 0.5046931992412855, 'weight_cat_class_0': 0.11257421624536812, 'weight_cat_class_1': 0.7772454709016093, 'weight_cat_class_2': 0.23819206347580885}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:57,352] Trial 1914 finished with value: 0.94946071751438 and parameters: {'weight_lgbm_class_0': 0.022610314822338974, 'weight_lgbm_class_1': 0.6952660110983595, 'weight_lgbm_class_2': 0.9405744494107533, 'weight_xgb_class_0': 0.08366193505277666, 'weight_xgb_class_1': 0.5241443440152822, 'weight_xgb_class_2': 0.4988543523847576, 'weight_cat_class_0': 0.07322228119217586, 'weight_cat_class_1': 0.7680610557142867, 'weight_cat_class_2': 0.22853575250781472}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:57,409] Trial 1916 finished with value: 0.9491786539761424 and parameters: {'weight_lgbm_class_0': 0.060035770159149605, 'weight_lgbm_class_1': 0.6947967538075591, 'weight_lgbm_class_2': 0.9537681856455912, 'weight_xgb_class_0': 0.07608735802489514, 'weight_xgb_class_1': 0.5286154682239635, 'weight_xgb_class_2': 0.49854280081168095, 'weight_cat_class_0': 0.07111523501015972, 'weight_cat_class_1': 0.7695005993449987, 'weight_cat_class_2': 0.25230685338793096}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:57,517] Trial 1917 finished with value: 0.9484726895249039 and parameters: {'weight_lgbm_class_0': 0.06283648289208642, 'weight_lgbm_class_1': 0.6929498328204727, 'weight_lgbm_class_2': 0.9579153566869059, 'weight_xgb_class_0': 0.08882478988139213, 'weight_xgb_class_1': 0.5230688088923094, 'weight_xgb_class_2': 0.5004163931898147, 'weight_cat_class_0': 0.10739933663436138, 'weight_cat_class_1': 0.7730408861468809, 'weight_cat_class_2': 0.2579024651511472}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 1920/2000 [01:21<00:04, 17.83it/s]

[I 2026-07-03 10:23:57,572] Trial 1918 finished with value: 0.9489585041414471 and parameters: {'weight_lgbm_class_0': 0.06211559588623097, 'weight_lgbm_class_1': 0.6963100407806336, 'weight_lgbm_class_2': 0.9180166981768652, 'weight_xgb_class_0': 0.08189445468287011, 'weight_xgb_class_1': 0.5258245355076324, 'weight_xgb_class_2': 0.49463692984352103, 'weight_cat_class_0': 0.06905447745609634, 'weight_cat_class_1': 0.7708082387772707, 'weight_cat_class_2': 0.2142873987990189}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:57,679] Trial 1919 finished with value: 0.9489883380741148 and parameters: {'weight_lgbm_class_0': 0.0630986835615447, 'weight_lgbm_class_1': 0.6924653725112699, 'weight_lgbm_class_2': 0.9135808366329112, 'weight_xgb_class_0': 0.07822457623675932, 'weight_xgb_class_1': 0.5341656965681061, 'weight_xgb_class_2': 0.5076134226096148, 'weight_cat_class_0': 0.07816117815681173, 'weight_cat_class_1': 0.7806077553407285, 'weight_cat_class_2': 0.26601792858282924}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:57,767] Trial 1920 finished with value: 0.9492389568462705 and parameters: {'weight_lgbm_class_0': 0.06170278307113915, 'weight_lgbm_class_1': 0.6978440416613617, 'weight_lgbm_class_2': 0.9219341883677006, 'weight_xgb_class_0': 0.0840386318087446, 'weight_xgb_class_1': 0.5319536801716495, 'weight_xgb_class_2': 0.7944006830222632, 'weight_cat_class_0': 0.06725659438618212, 'weight_cat_class_1': 0.7731228366838192, 'weight_cat_class_2': 0.21283469682067385}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎    | 1927/2000 [01:22<00:04, 15.15it/s]

[I 2026-07-03 10:23:57,895] Trial 1921 finished with value: 0.9493705111773248 and parameters: {'weight_lgbm_class_0': 0.06351394656924822, 'weight_lgbm_class_1': 0.6970454105494006, 'weight_lgbm_class_2': 0.9075227191725851, 'weight_xgb_class_0': 0.07974932589784367, 'weight_xgb_class_1': 0.5315420872726802, 'weight_xgb_class_2': 0.4984436056644961, 'weight_cat_class_0': 0.0747945973685621, 'weight_cat_class_1': 0.7760600768517841, 'weight_cat_class_2': 0.8533766561523373}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:57,913] Trial 1922 finished with value: 0.9492885970022451 and parameters: {'weight_lgbm_class_0': 0.062219141071796345, 'weight_lgbm_class_1': 0.6959863283644034, 'weight_lgbm_class_2': 0.9122776507601409, 'weight_xgb_class_0': 0.05502294477714466, 'weight_xgb_class_1': 0.5332170351216301, 'weight_xgb_class_2': 0.5071974983409707, 'weight_cat_class_0': 0.07277320758285226, 'weight_cat_class_1': 0.7759117833167011, 'weight_cat_class_2': 0.21895878073240121}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:57,986] Trial 1924 finished with value: 0.9493630657072872 and parameters: {'weight_lgbm_class_0': 0.0650862201854091, 'weight_lgbm_class_1': 0.6884688965347064, 'weight_lgbm_class_2': 0.9153620245295426, 'weight_xgb_class_0': 0.05463302698610832, 'weight_xgb_class_1': 0.5325669273783848, 'weight_xgb_class_2': 0.6074861497754619, 'weight_cat_class_0': 0.07549353631560377, 'weight_cat_class_1': 0.7748718731589748, 'weight_cat_class_2': 0.2631303695489623}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:57,986] Trial 1925 finished with value: 0.9495655945785592 and parameters: {'weight_lgbm_class_0': 0.06359059471336537, 'weight_lgbm_class_1': 0.6970329766173733, 'weight_lgbm_class_2': 0.9124033250526485, 'weight_xgb_class_0': 0.0502749424738794, 'weight_xgb_class_1': 0.48131525733993485, 'weight_xgb_class_2': 0.42016620085049433, 'weight_cat_class_0': 0.038990400718218306, 'weight_cat_class_1': 0.7028895217835035, 'weight_cat_class_2': 0.10602152366179281}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:57,986] Trial 1926 finished with value: 0.9496822195248705 and parameters: {'weight_lgbm_class_0': 0.055878139534268775, 'weight_lgbm_class_1': 0.6985568194642262, 'weight_lgbm_class_2': 0.921332409422067, 'weight_xgb_class_0': 0.054243755857783585, 'weight_xgb_class_1': 0.4748154686188459, 'weight_xgb_class_2': 0.41916196682011814, 'weight_cat_class_0': 0.03840905789956856, 'weight_cat_class_1': 0.6970415995110597, 'weight_cat_class_2': 0.2614180739844792}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:58,024] Trial 1923 finished with value: 0.9495006229701702 and parameters: {'weight_lgbm_class_0': 0.0628858705391398, 'weight_lgbm_class_1': 0.6953844847644461, 'weight_lgbm_class_2': 0.9202834905747304, 'weight_xgb_class_0': 0.0002692848506063751, 'weight_xgb_class_1': 0.5308169128432212, 'weight_xgb_class_2': 0.41971276427413984, 'weight_cat_class_0': 0.03826538667870181, 'weight_cat_class_1': 0.775283900726559, 'weight_cat_class_2': 0.24662262922559644}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:58,060] Trial 1927 finished with value: 0.9416339423196769 and parameters: {'weight_lgbm_class_0': 0.36035913790863794, 'weight_lgbm_class_1': 0.6982234174700341, 'weight_lgbm_class_2': 0.8985131612245163, 'weight_xgb_class_0': 0.052952575095316756, 'weight_xgb_class_1': 0.4687364488365068, 'weight_xgb_class_2': 0.41486308002491623, 'weight_cat_class_0': 0.03577824327111938, 'weight_cat_class_1': 0.7131814208258771, 'weight_cat_class_2': 0.2623775258337572}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 1931/2000 [01:22<00:03, 19.42it/s]

[I 2026-07-03 10:23:58,133] Trial 1928 finished with value: 0.9408500880934813 and parameters: {'weight_lgbm_class_0': 0.06270764170693806, 'weight_lgbm_class_1': 0.6053386672053033, 'weight_lgbm_class_2': 0.9053922946714734, 'weight_xgb_class_0': 0.0002767574614555915, 'weight_xgb_class_1': 0.47007863036929803, 'weight_xgb_class_2': 0.4198918509943665, 'weight_cat_class_0': 0.39752252298508095, 'weight_cat_class_1': 0.7031346748965658, 'weight_cat_class_2': 0.27068329109160555}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:58,233] Trial 1930 finished with value: 0.9495413479866461 and parameters: {'weight_lgbm_class_0': 0.06482731050923464, 'weight_lgbm_class_1': 0.6024675939765075, 'weight_lgbm_class_2': 0.885555279047426, 'weight_xgb_class_0': 0.05641427304500604, 'weight_xgb_class_1': 0.47588352518332894, 'weight_xgb_class_2': 0.41936333331636994, 'weight_cat_class_0': 0.03741144497976358, 'weight_cat_class_1': 0.7098073349646848, 'weight_cat_class_2': 0.2659221552429714}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:58,252] Trial 1929 finished with value: 0.9496542210974545 and parameters: {'weight_lgbm_class_0': 0.060031367569394714, 'weight_lgbm_class_1': 0.6940645994170052, 'weight_lgbm_class_2': 0.89115259505495, 'weight_xgb_class_0': 0.05426085088089083, 'weight_xgb_class_1': 0.477124747128253, 'weight_xgb_class_2': 0.4211045222808798, 'weight_cat_class_0': 0.0375097492509647, 'weight_cat_class_1': 0.7103280048621043, 'weight_cat_class_2': 0.22359007997192362}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 1932/2000 [01:22<00:03, 19.42it/s]

[I 2026-07-03 10:23:58,367] Trial 1931 finished with value: 0.9171609604741214 and parameters: {'weight_lgbm_class_0': 0.060199066508554236, 'weight_lgbm_class_1': 0.5967707025927576, 'weight_lgbm_class_2': 0.8899743680822464, 'weight_xgb_class_0': 0.059741068288078736, 'weight_xgb_class_1': 0.4635384602380066, 'weight_xgb_class_2': 0.4206575955658917, 'weight_cat_class_0': 0.7601951417240398, 'weight_cat_class_1': 0.6849691997325713, 'weight_cat_class_2': 0.2794129659275669}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:58,422] Trial 1932 finished with value: 0.9495708694785864 and parameters: {'weight_lgbm_class_0': 0.06403650707958966, 'weight_lgbm_class_1': 0.642077394865823, 'weight_lgbm_class_2': 0.8897341150661111, 'weight_xgb_class_0': 0.05670478574308469, 'weight_xgb_class_1': 0.471087910806259, 'weight_xgb_class_2': 0.4250324384342942, 'weight_cat_class_0': 0.039373596725275815, 'weight_cat_class_1': 0.6855004236507941, 'weight_cat_class_2': 0.2759822466931212}. Best is trial 1765 with value: 0.9497917773888238.

[I 2026-07-03 10:23:58,582] Trial 1933 finished with value: 0.9494525140976607 and parameters: {'weight_lgbm_class_0': 0.0002629665720570856, 'weight_lgbm_class_1': 0.6395463312394928, 'weight_lgbm_class_2': 0.8817624522366828, 'weight_xgb_class_0': 0.053929178514178354, 'weight_xgb_class_1': 0.46126212154552604, 'weight_xgb_class_2': 0.41993863861436653, 'weight_cat_class_0': 0.03727224306703128, 'weight_cat_class_1': 0.7089179997842774, 'weight_cat_class_2': 0.26640463867491393}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:58,585] Trial 1934 finished with value: 0.9496844486785768 and parameters: {'weight_lgbm_class_0': 0.05130319789669038, 'weight_lgbm_class_1': 0.6030148340607558, 'weight_lgbm_class_2': 0.8944710412103948, 'weight_xgb_class_0': 0.0529677707213614, 'weight_xgb_class_1': 0.4653766414183434, 'weight_xgb_class_2': 0.41705699536076646, 'weight_cat_class_0': 0.038328187791285884, 'weight_cat_class_1': 0.7061003537908918, 'weight_cat_class_2': 0.2569593529907093}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:58,658] Trial 1936 finished with value: 0.943832229913726 and parameters: {'weight_lgbm_class_0': 0.33853248063494823, 'weight_lgbm_class_1': 0.5993960476196047, 'weight_lgbm_class_2': 0.8862890318404097, 'weight_xgb_class_0': 0.01726994571287758, 'weight_xgb_class_1': 0.4688007961635623, 'weight_xgb_class_2': 0.45074812753333254, 'weight_cat_class_0': 0.0376511291372964, 'weight_cat_class_1': 0.7168858740828418, 'weight_cat_class_2': 0.2804910039557684}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:58,709] Trial 1935 finished with value: 0.9495436678136128 and parameters: {'weight_lgbm_class_0': 0.04736781502460834, 'weight_lgbm_class_1': 0.5171974704991056, 'weight_lgbm_class_2': 0.8843392934797746, 'weight_xgb_class_0': 0.016997446006068496, 'weight_xgb_class_1': 0.46060470305430523, 'weight_xgb_class_2': 0.44875057986833333, 'weight_cat_class_0': 0.04161323962475627, 'weight_cat_class_1': 0.7138358911276931, 'weight_cat_class_2': 0.26916199882525216}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:58,710] Trial 1939 finished with value: 0.9495440546668523 and parameters: {'weight_lgbm_class_0': 0.041443783955726024, 'weight_lgbm_class_1': 0.6312179251830107, 'weight_lgbm_class_2': 0.9791046849782977, 'weight_xgb_class_0': 0.02507761718290647, 'weight_xgb_class_1': 0.4672932429458031, 'weight_xgb_class_2': 0.45065252877840634, 'weight_cat_class_0': 0.03759262032060346, 'weight_cat_class_1': 0.7521830497457235, 'weight_cat_class_2': 0.27627412188777184}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:58,757] Trial 1938 finished with value: 0.9497593735529589 and parameters: {'weight_lgbm_class_0': 0.04239227219103667, 'weight_lgbm_class_1': 0.6369355584348916, 'weight_lgbm_class_2': 0.8810997682418368, 'weight_xgb_class_0': 0.03248588800517485, 'weight_xgb_class_1': 0.4649259665954664, 'weight_xgb_class_2': 0.4499330993916759, 'weight_cat_class_0': 0.033683548345034, 'weight_cat_class_1': 0.7545643997173739, 'weight_cat_class_2': 0.12568995301402558}. Best is trial 1765 with value: 0.9497917773888238.

[I 2026-07-03 10:23:58,758] Trial 1937 finished with value: 0.949546076478462 and parameters: {'weight_lgbm_class_0': 0.044484011533699394, 'weight_lgbm_class_1': 0.600459368684152, 'weight_lgbm_class_2': 0.8875408823142571, 'weight_xgb_class_0': 0.018357969247679344, 'weight_xgb_class_1': 0.47279126988180875, 'weight_xgb_class_2': 0.4502147191315513, 'weight_cat_class_0': 0.03438364099902412, 'weight_cat_class_1': 0.7971367916709852, 'weight_cat_class_2': 0.26643529326799537}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:58,813] Trial 1940 finished with value: 0.9495859242626943 and parameters: {'weight_lgbm_class_0': 0.04403830727387384, 'weight_lgbm_class_1': 0.6371063462533597, 'weight_lgbm_class_2': 0.8890002690092842, 'weight_xgb_class_0': 0.01984279646344921, 'weight_xgb_class_1': 0.4668575153018737, 'weight_xgb_class_2': 0.4516036793332567, 'weight_cat_class_0': 0.03879521086677258, 'weight_cat_class_1': 0.7949177782699189, 'weight_cat_class_2': 0.28242651092844445}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:58,940] Trial 1941 finished with value: 0.9484832211627349 and parameters: {'weight_lgbm_class_0': 0.0010060832247786033, 'weight_lgbm_class_1': 0.5150927834598116, 'weight_lgbm_class_2': 0.9722076111566123, 'weight_xgb_class_0': 0.01834966485655122, 'weight_xgb_class_1': 0.7023345515608771, 'weight_xgb_class_2': 0.451598064963049, 'weight_cat_class_0': 0.04954874150926673, 'weight_cat_class_1': 0.7541714124266505, 'weight_cat_class_2': 0.28024288297266864}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍   | 1945/2000 [01:23<00:03, 18.08it/s]

[I 2026-07-03 10:23:58,994] Trial 1942 finished with value: 0.9496359219506054 and parameters: {'weight_lgbm_class_0': 0.040904004389572216, 'weight_lgbm_class_1': 0.63631202239547, 'weight_lgbm_class_2': 0.9703998151901336, 'weight_xgb_class_0': 0.02079480526064561, 'weight_xgb_class_1': 0.5587355017627738, 'weight_xgb_class_2': 0.45073293525712593, 'weight_cat_class_0': 0.0525993350880501, 'weight_cat_class_1': 0.7528413372046476, 'weight_cat_class_2': 0.2863451697652417}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:59,054] Trial 1943 finished with value: 0.9119968949990117 and parameters: {'weight_lgbm_class_0': 0.8885833620987347, 'weight_lgbm_class_1': 0.6428539048251725, 'weight_lgbm_class_2': 0.9759490576971792, 'weight_xgb_class_0': 0.01974652670937522, 'weight_xgb_class_1': 0.5512755368388301, 'weight_xgb_class_2': 0.44994910271316435, 'weight_cat_class_0': 0.05372064575081606, 'weight_cat_class_1': 0.7526978768763193, 'weight_cat_class_2': 0.060532619945620425}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:59,120] Trial 1944 finished with value: 0.949748450901283 and parameters: {'weight_lgbm_class_0': 0.09049644247013697, 'weight_lgbm_class_1': 0.6346422845949523, 'weight_lgbm_class_2': 0.8775029876416895, 'weight_xgb_class_0': 0.0003057799817228167, 'weight_xgb_class_1': 0.5579944495980131, 'weight_xgb_class_2': 0.447042447969316, 'weight_cat_class_0': 0.052839362393278654, 'weight_cat_class_1': 0.8000372209186202, 'weight_cat_class_2': 0.13461124998715573}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 1951/2000 [01:23<00:02, 18.47it/s]

[I 2026-07-03 10:23:59,305] Trial 1945 finished with value: 0.9496494690207297 and parameters: {'weight_lgbm_class_0': 0.038992028906131716, 'weight_lgbm_class_1': 0.657662943536931, 'weight_lgbm_class_2': 0.9719564110431388, 'weight_xgb_class_0': 0.016872843968185624, 'weight_xgb_class_1': 0.55100535707295, 'weight_xgb_class_2': 0.449338668771795, 'weight_cat_class_0': 0.05433384090198891, 'weight_cat_class_1': 0.7550002946659955, 'weight_cat_class_2': 0.14241424164684138}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:59,323] Trial 1946 finished with value: 0.947806314874038 and parameters: {'weight_lgbm_class_0': 1.1955822321677023e-05, 'weight_lgbm_class_1': 0.51607395012055, 'weight_lgbm_class_2': 0.9730387316218267, 'weight_xgb_class_0': 7.934571780477326e-05, 'weight_xgb_class_1': 0.5532002227331942, 'weight_xgb_class_2': 0.4469385776187531, 'weight_cat_class_0': 0.0537546870125993, 'weight_cat_class_1': 0.753270062206785, 'weight_cat_class_2': 0.2867902054665775}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:59,336] Trial 1947 finished with value: 0.913831729273455 and parameters: {'weight_lgbm_class_0': 0.911552878731791, 'weight_lgbm_class_1': 0.7317715433699609, 'weight_lgbm_class_2': 0.9979362616109737, 'weight_xgb_class_0': 0.018345669210748403, 'weight_xgb_class_1': 0.5580807771590004, 'weight_xgb_class_2': 0.45151675310473827, 'weight_cat_class_0': 0.05686259662249628, 'weight_cat_class_1': 0.746534257858834, 'weight_cat_class_2': 0.14059782383830643}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:59,399] Trial 1948 finished with value: 0.9491530806258598 and parameters: {'weight_lgbm_class_0': 0.0178371788418177, 'weight_lgbm_class_1': 0.6493441611721781, 'weight_lgbm_class_2': 0.9364485405500693, 'weight_xgb_class_0': 0.10941606298230427, 'weight_xgb_class_1': 0.43956046155711626, 'weight_xgb_class_2': 0.4420574432384644, 'weight_cat_class_0': 0.05831305659361801, 'weight_cat_class_1': 0.7487934993668881, 'weight_cat_class_2': 0.14660314618345574}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:59,436] Trial 1949 finished with value: 0.9488377849397972 and parameters: {'weight_lgbm_class_0': 0.03558805802422878, 'weight_lgbm_class_1': 0.6552173941839974, 'weight_lgbm_class_2': 0.8865470520409351, 'weight_xgb_class_0': 0.1104391981366422, 'weight_xgb_class_1': 0.43151903431997357, 'weight_xgb_class_2': 0.40025894581440064, 'weight_cat_class_0': 0.05904472057549019, 'weight_cat_class_1': 0.7522026924080525, 'weight_cat_class_2': 0.14302060207873166}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:59,462] Trial 1950 finished with value: 0.9488721728670324 and parameters: {'weight_lgbm_class_0': 0.03210246107896423, 'weight_lgbm_class_1': 0.656248113923364, 'weight_lgbm_class_2': 0.87702788177257, 'weight_xgb_class_0': 0.10754093165130628, 'weight_xgb_class_1': 0.42660967136667344, 'weight_xgb_class_2': 0.39375340655085606, 'weight_cat_class_0': 0.05563277917246842, 'weight_cat_class_1': 0.7509826190214334, 'weight_cat_class_2': 0.12942227999958414}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:59,471] Trial 1951 finished with value: 0.9488508103511597 and parameters: {'weight_lgbm_class_0': 0.015615135596252841, 'weight_lgbm_class_1': 0.6475440811088936, 'weight_lgbm_class_2': 0.8999183112767971, 'weight_xgb_class_0': 0.11978515266006025, 'weight_xgb_class_1': 0.4407423249725472, 'weight_xgb_class_2': 0.40020034118998826, 'weight_cat_class_0': 0.057631037628693885, 'weight_cat_class_1': 0.7500755400145742, 'weight_cat_class_2': 0.1409687816878273}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 1954/2000 [01:23<00:02, 18.01it/s]

[I 2026-07-03 10:23:59,548] Trial 1952 finished with value: 0.9337777797576092 and parameters: {'weight_lgbm_class_0': 0.029775230550034126, 'weight_lgbm_class_1': 0.6599664732526883, 'weight_lgbm_class_2': 0.9345559052465087, 'weight_xgb_class_0': 0.10783011768831796, 'weight_xgb_class_1': 0.4929340381474331, 'weight_xgb_class_2': 0.4403259731053888, 'weight_cat_class_0': 0.45769632320828996, 'weight_cat_class_1': 0.7561864207470702, 'weight_cat_class_2': 0.12967981923148364}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:59,662] Trial 1954 finished with value: 0.949267389708457 and parameters: {'weight_lgbm_class_0': 0.018541982943234225, 'weight_lgbm_class_1': 0.6675746699146254, 'weight_lgbm_class_2': 0.8717950645320179, 'weight_xgb_class_0': 0.042299208993870144, 'weight_xgb_class_1': 0.43666709785043223, 'weight_xgb_class_2': 0.38973335320032965, 'weight_cat_class_0': 0.018035622651801347, 'weight_cat_class_1': 0.7406516627094183, 'weight_cat_class_2': 0.11749077327010454}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:59,682] Trial 1953 finished with value: 0.9488025565290442 and parameters: {'weight_lgbm_class_0': 0.03272294675441886, 'weight_lgbm_class_1': 0.6550743210573359, 'weight_lgbm_class_2': 0.8783854830655999, 'weight_xgb_class_0': 0.11158713262340413, 'weight_xgb_class_1': 0.4915374937148198, 'weight_xgb_class_2': 0.4396939780484456, 'weight_cat_class_0': 0.06082566889544434, 'weight_cat_class_1': 0.7562525632492578, 'weight_cat_class_2': 0.11964186192674006}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 1957/2000 [01:24<00:02, 16.82it/s]

[I 2026-07-03 10:23:59,798] Trial 1955 finished with value: 0.9496500215634897 and parameters: {'weight_lgbm_class_0': 0.04218789267640637, 'weight_lgbm_class_1': 0.6554254189247947, 'weight_lgbm_class_2': 0.8783076541948897, 'weight_xgb_class_0': 0.045555062286020215, 'weight_xgb_class_1': 0.7797514942077324, 'weight_xgb_class_2': 0.39212271283424305, 'weight_cat_class_0': 0.01872820403655904, 'weight_cat_class_1': 0.7570561088908461, 'weight_cat_class_2': 0.13174092830474943}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:59,819] Trial 1956 finished with value: 0.924340439048352 and parameters: {'weight_lgbm_class_0': 0.030097410349508184, 'weight_lgbm_class_1': 0.6565306417438895, 'weight_lgbm_class_2': 0.8765058912495493, 'weight_xgb_class_0': 0.6451785552973052, 'weight_xgb_class_1': 0.4434762186317879, 'weight_xgb_class_2': 0.40055719618922453, 'weight_cat_class_0': 0.017371803230749258, 'weight_cat_class_1': 0.7533074597649622, 'weight_cat_class_2': 0.12861072998263354}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:23:59,981] Trial 1957 finished with value: 0.9494596325853063 and parameters: {'weight_lgbm_class_0': 0.015804458962621448, 'weight_lgbm_class_1': 0.6579506540170748, 'weight_lgbm_class_2': 0.8716083863133677, 'weight_xgb_class_0': 0.11585407510508292, 'weight_xgb_class_1': 0.4293985920291176, 'weight_xgb_class_2': 0.3972205554060333, 'weight_cat_class_0': 0.02032797053111604, 'weight_cat_class_1': 0.728423502607443, 'weight_cat_class_2': 0.12435619925975255}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 1963/2000 [01:24<00:02, 17.29it/s]

[I 2026-07-03 10:24:00,051] Trial 1958 finished with value: 0.948723503924663 and parameters: {'weight_lgbm_class_0': 0.03053022482928645, 'weight_lgbm_class_1': 0.6637120971916152, 'weight_lgbm_class_2': 0.8767331597581239, 'weight_xgb_class_0': 0.15552243053330594, 'weight_xgb_class_1': 0.4415030586252204, 'weight_xgb_class_2': 0.40571010139852565, 'weight_cat_class_0': 0.017659793412560305, 'weight_cat_class_1': 0.7259140379740457, 'weight_cat_class_2': 0.11353560260853372}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:00,088] Trial 1960 finished with value: 0.9497470903960362 and parameters: {'weight_lgbm_class_0': 0.00012425293064355358, 'weight_lgbm_class_1': 0.6651888749761193, 'weight_lgbm_class_2': 0.874199825005699, 'weight_xgb_class_0': 0.0416810535160667, 'weight_xgb_class_1': 0.5001562870646947, 'weight_xgb_class_2': 0.4014545225012684, 'weight_cat_class_0': 0.08989352513858886, 'weight_cat_class_1': 0.7283807190101959, 'weight_cat_class_2': 0.11141959558271057}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:00,095] Trial 1959 finished with value: 0.9494751569182737 and parameters: {'weight_lgbm_class_0': 0.01888528064461476, 'weight_lgbm_class_1': 0.655204821743953, 'weight_lgbm_class_2': 0.87063775559518, 'weight_xgb_class_0': 0.11177952731230281, 'weight_xgb_class_1': 0.44171475311872654, 'weight_xgb_class_2': 0.3956008732185898, 'weight_cat_class_0': 0.018545690550310193, 'weight_cat_class_1': 0.740458771846054, 'weight_cat_class_2': 0.09723516598790427}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:00,160] Trial 1961 finished with value: 0.949016901174823 and parameters: {'weight_lgbm_class_0': 0.00013167501676387972, 'weight_lgbm_class_1': 0.6168489313005189, 'weight_lgbm_class_2': 0.8755703170384075, 'weight_xgb_class_0': 0.15854512050899894, 'weight_xgb_class_1': 0.49739171429045265, 'weight_xgb_class_2': 0.4317229035924796, 'weight_cat_class_0': 0.020275908794059636, 'weight_cat_class_1': 0.7209716880757023, 'weight_cat_class_2': 0.10662122908838315}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:00,203] Trial 1963 finished with value: 0.949570740000667 and parameters: {'weight_lgbm_class_0': 0.030916865489497444, 'weight_lgbm_class_1': 0.6151520981958393, 'weight_lgbm_class_2': 0.8612034329274859, 'weight_xgb_class_0': 0.04276371397035957, 'weight_xgb_class_1': 0.49354473193544346, 'weight_xgb_class_2': 0.43165045875298763, 'weight_cat_class_0': 0.019410930453569963, 'weight_cat_class_1': 0.728081314720923, 'weight_cat_class_2': 0.06450151107623886}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:00,213] Trial 1962 finished with value: 0.9487479609478903 and parameters: {'weight_lgbm_class_0': 0.031780357465466216, 'weight_lgbm_class_1': 0.6670601979849498, 'weight_lgbm_class_2': 0.871110957676309, 'weight_xgb_class_0': 0.15366628566334112, 'weight_xgb_class_1': 0.4934253093244211, 'weight_xgb_class_2': 0.4324451027205849, 'weight_cat_class_0': 0.019481370505989446, 'weight_cat_class_1': 0.7325714128642391, 'weight_cat_class_2': 0.1060808085700061}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 1966/2000 [01:24<00:01, 19.13it/s]

[I 2026-07-03 10:24:00,230] Trial 1964 finished with value: 0.9496244493647158 and parameters: {'weight_lgbm_class_0': 0.03886908672238924, 'weight_lgbm_class_1': 0.6103350339832087, 'weight_lgbm_class_2': 0.8704237547327598, 'weight_xgb_class_0': 0.04203207096464284, 'weight_xgb_class_1': 0.44642527368173796, 'weight_xgb_class_2': 0.430935868793269, 'weight_cat_class_0': 0.020247647975475565, 'weight_cat_class_1': 0.7371194108065859, 'weight_cat_class_2': 0.16761226249836458}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:00,366] Trial 1965 finished with value: 0.94971145498045 and parameters: {'weight_lgbm_class_0': 0.047208712907321745, 'weight_lgbm_class_1': 0.6677691189186853, 'weight_lgbm_class_2': 0.8628924561320968, 'weight_xgb_class_0': 0.06647931146574204, 'weight_xgb_class_1': 0.491247902170982, 'weight_xgb_class_2': 0.4314519591288405, 'weight_cat_class_0': 0.019636593898404824, 'weight_cat_class_1': 0.7367929754623461, 'weight_cat_class_2': 0.08974652090388305}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:00,399] Trial 1966 finished with value: 0.9496729617493678 and parameters: {'weight_lgbm_class_0': 0.03908206252111918, 'weight_lgbm_class_1': 0.6136401102985944, 'weight_lgbm_class_2': 0.8604078167093652, 'weight_xgb_class_0': 0.06689423405525291, 'weight_xgb_class_1': 0.4956486724922571, 'weight_xgb_class_2': 0.4305787270134366, 'weight_cat_class_0': 0.018380521068919124, 'weight_cat_class_1': 0.7335630274849401, 'weight_cat_class_2': 0.17075930930356453}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 1968/2000 [01:24<00:02, 15.88it/s]

[I 2026-07-03 10:24:00,524] Trial 1967 finished with value: 0.9479497703933447 and parameters: {'weight_lgbm_class_0': 0.07090826446816285, 'weight_lgbm_class_1': 0.613345693033911, 'weight_lgbm_class_2': 0.9260604722260906, 'weight_xgb_class_0': 0.06495392543100453, 'weight_xgb_class_1': 0.49505437534938895, 'weight_xgb_class_2': 0.20749945709556805, 'weight_cat_class_0': 0.08483521776214331, 'weight_cat_class_1': 0.7321864766605931, 'weight_cat_class_2': 0.10826113979743449}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:00,550] Trial 1968 finished with value: 0.9485559030511523 and parameters: {'weight_lgbm_class_0': 0.07357266388934199, 'weight_lgbm_class_1': 0.6323602171029149, 'weight_lgbm_class_2': 0.9293993313679876, 'weight_xgb_class_0': 0.06583050794507672, 'weight_xgb_class_1': 0.4842361643898045, 'weight_xgb_class_2': 0.4679051817002376, 'weight_cat_class_0': 0.09550353532762179, 'weight_cat_class_1': 0.7167315579168069, 'weight_cat_class_2': 0.17130352201843854}. Best is trial 1765 with value: 0.9497917773888238.

[I 2026-07-03 10:24:00,764] Trial 1969 finished with value: 0.9333793807277745 and parameters: {'weight_lgbm_class_0': 0.045085529838244764, 'weight_lgbm_class_1': 0.6311531093676328, 'weight_lgbm_class_2': 0.908351059924582, 'weight_xgb_class_0': 0.44831310552229897, 'weight_xgb_class_1': 0.49607885998257756, 'weight_xgb_class_2': 0.43106640930090184, 'weight_cat_class_0': 0.08541324087121285, 'weight_cat_class_1': 0.7306517026141564, 'weight_cat_class_2': 0.1791420315078318}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:00,767] Trial 1970 finished with value: 0.9486489565538158 and parameters: {'weight_lgbm_class_0': 0.07259972499105963, 'weight_lgbm_class_1': 0.6109835939645516, 'weight_lgbm_class_2': 0.9077165186681239, 'weight_xgb_class_0': 0.06759852891123716, 'weight_xgb_class_1': 0.496863290179568, 'weight_xgb_class_2': 0.43174423041493026, 'weight_cat_class_0': 0.08375838539579764, 'weight_cat_class_1': 0.7761242378439724, 'weight_cat_class_2': 0.17500976452983819}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:00,807] Trial 1971 finished with value: 0.948396978427922 and parameters: {'weight_lgbm_class_0': 0.07318023675790747, 'weight_lgbm_class_1': 0.6229434942408433, 'weight_lgbm_class_2': 0.9031013658969765, 'weight_xgb_class_0': 0.06957877763879747, 'weight_xgb_class_1': 0.4965577751799238, 'weight_xgb_class_2': 0.47117889208916564, 'weight_cat_class_0': 0.10067573258851266, 'weight_cat_class_1': 0.782863084699437, 'weight_cat_class_2': 0.17446205322377212}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:00,814] Trial 1972 finished with value: 0.9484262942765697 and parameters: {'weight_lgbm_class_0': 0.07423764173975879, 'weight_lgbm_class_1': 0.6160074485544317, 'weight_lgbm_class_2': 0.9230841436228548, 'weight_xgb_class_0': 0.06618854784135583, 'weight_xgb_class_1': 0.49484144883564685, 'weight_xgb_class_2': 0.4628635956437681, 'weight_cat_class_0': 0.09060890657828663, 'weight_cat_class_1': 0.7819402485667406, 'weight_cat_class_2': 0.09582851214525147}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:00,880] Trial 1973 finished with value: 0.9484202723007694 and parameters: {'weight_lgbm_class_0': 0.0731006620141121, 'weight_lgbm_class_1': 0.6149940784936588, 'weight_lgbm_class_2': 0.9374159472942099, 'weight_xgb_class_0': 0.060172016924991134, 'weight_xgb_class_1': 0.4928620704892326, 'weight_xgb_class_2': 0.4685982814746555, 'weight_cat_class_0': 0.09650265992157933, 'weight_cat_class_1': 0.7833338038585771, 'weight_cat_class_2': 0.06283181705941981}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:00,929] Trial 1974 finished with value: 0.9485560533771009 and parameters: {'weight_lgbm_class_0': 0.07292064166926442, 'weight_lgbm_class_1': 0.6139368598144301, 'weight_lgbm_class_2': 0.9043406104730647, 'weight_xgb_class_0': 0.06390434457415484, 'weight_xgb_class_1': 0.4851973293013809, 'weight_xgb_class_2': 0.4689024619559004, 'weight_cat_class_0': 0.09489579905513869, 'weight_cat_class_1': 0.7857113773513247, 'weight_cat_class_2': 0.16216113731752235}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 1979/2000 [01:25<00:01, 19.75it/s]

[I 2026-07-03 10:24:00,955] Trial 1976 finished with value: 0.948510417466328 and parameters: {'weight_lgbm_class_0': 0.07499873997554793, 'weight_lgbm_class_1': 0.6193397117518348, 'weight_lgbm_class_2': 0.9353504984157839, 'weight_xgb_class_0': 0.0675023369529721, 'weight_xgb_class_1': 0.4864925556413787, 'weight_xgb_class_2': 0.4723019353453114, 'weight_cat_class_0': 0.08811675568601054, 'weight_cat_class_1': 0.7823406433207727, 'weight_cat_class_2': 0.09424128588079589}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:00,957] Trial 1975 finished with value: 0.9484574001975575 and parameters: {'weight_lgbm_class_0': 0.06946403635793624, 'weight_lgbm_class_1': 0.5813956518682888, 'weight_lgbm_class_2': 0.9100446515921018, 'weight_xgb_class_0': 0.06586954895394674, 'weight_xgb_class_1': 0.9214856005662053, 'weight_xgb_class_2': 0.47471117591715645, 'weight_cat_class_0': 0.09380076697625443, 'weight_cat_class_1': 0.559438436729027, 'weight_cat_class_2': 0.0785485264179836}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:01,059] Trial 1977 finished with value: 0.9123472346938661 and parameters: {'weight_lgbm_class_0': 0.07142687439179256, 'weight_lgbm_class_1': 0.7241249568768201, 'weight_lgbm_class_2': 0.922199206105332, 'weight_xgb_class_0': 0.8015676780556839, 'weight_xgb_class_1': 0.48354017512669495, 'weight_xgb_class_2': 0.46392083180664884, 'weight_cat_class_0': 0.10101825334147736, 'weight_cat_class_1': 0.7864390994619755, 'weight_cat_class_2': 0.16125072203474472}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:01,109] Trial 1978 finished with value: 0.948541583019724 and parameters: {'weight_lgbm_class_0': 0.07119359960294613, 'weight_lgbm_class_1': 0.6335534097545301, 'weight_lgbm_class_2': 0.9014757584921761, 'weight_xgb_class_0': 0.0632437963196942, 'weight_xgb_class_1': 0.45866853745698694, 'weight_xgb_class_2': 0.4680953462601721, 'weight_cat_class_0': 0.09865057149045242, 'weight_cat_class_1': 0.7825891806909658, 'weight_cat_class_2': 0.16767529637062617}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 1981/2000 [01:25<00:00, 19.75it/s]

[I 2026-07-03 10:24:01,269] Trial 1979 finished with value: 0.9497248281421123 and parameters: {'weight_lgbm_class_0': 0.07176024054347935, 'weight_lgbm_class_1': 0.6309075098196315, 'weight_lgbm_class_2': 0.8975863167827928, 'weight_xgb_class_0': 0.03730898578758822, 'weight_xgb_class_1': 0.4117244048264458, 'weight_xgb_class_2': 0.4677812422470753, 'weight_cat_class_0': 0.032519238300964155, 'weight_cat_class_1': 0.7827276177852278, 'weight_cat_class_2': 0.07060547751902466}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:01,281] Trial 1980 finished with value: 0.9488489085905664 and parameters: {'weight_lgbm_class_0': 0.07582114728320069, 'weight_lgbm_class_1': 0.6316980992438728, 'weight_lgbm_class_2': 0.8991961897039942, 'weight_xgb_class_0': 0.03687617235466189, 'weight_xgb_class_1': 0.4611183275052401, 'weight_xgb_class_2': 0.46908607064779917, 'weight_cat_class_0': 0.08789967930698539, 'weight_cat_class_1': 0.7898002280289367, 'weight_cat_class_2': 0.07645236343520287}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:01,449] Trial 1981 finished with value: 0.9171368166875262 and parameters: {'weight_lgbm_class_0': 0.0560095065328067, 'weight_lgbm_class_1': 0.7213844686127119, 'weight_lgbm_class_2': 0.9000978618231642, 'weight_xgb_class_0': 0.7181611950548773, 'weight_xgb_class_1': 0.4077679277195369, 'weight_xgb_class_2': 0.4752326600039574, 'weight_cat_class_0': 0.036898389681173586, 'weight_cat_class_1': 0.6809421914533209, 'weight_cat_class_2': 0.05833889637276829}. Best is trial 1765 with value: 0.9497917773888238.

[I 2026-07-03 10:24:01,493] Trial 1982 finished with value: 0.9267983537127246 and parameters: {'weight_lgbm_class_0': 0.05819990642571027, 'weight_lgbm_class_1': 0.5837038407342856, 'weight_lgbm_class_2': 0.8996001925407435, 'weight_xgb_class_0': 0.037689956844074946, 'weight_xgb_class_1': 0.40539823850596185, 'weight_xgb_class_2': 0.6001178951559664, 'weight_cat_class_0': 0.6124665097044395, 'weight_cat_class_1': 0.792797345012107, 'weight_cat_class_2': 0.055605310639855146}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:01,549] Trial 1983 finished with value: 0.9495562253078308 and parameters: {'weight_lgbm_class_0': 0.05738236742684648, 'weight_lgbm_class_1': 0.5472971677517445, 'weight_lgbm_class_2': 0.9030816342772289, 'weight_xgb_class_0': 0.046696466002688966, 'weight_xgb_class_1': 0.4130911445999446, 'weight_xgb_class_2': 0.7196372118638074, 'weight_cat_class_0': 0.03344827405067569, 'weight_cat_class_1': 0.7802848168820665, 'weight_cat_class_2': 0.057514484712224506}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:01,571] Trial 1984 finished with value: 0.9297734449323807 and parameters: {'weight_lgbm_class_0': 0.05061721956754837, 'weight_lgbm_class_1': 0.5800246154574589, 'weight_lgbm_class_2': 0.9062150218219925, 'weight_xgb_class_0': 0.5108078714040152, 'weight_xgb_class_1': 0.4160541377911489, 'weight_xgb_class_2': 0.4763121136306444, 'weight_cat_class_0': 0.0345153630326669, 'weight_cat_class_1': 0.6738674842832096, 'weight_cat_class_2': 0.0846034922031576}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:01,613] Trial 1985 finished with value: 0.9172846780646934 and parameters: {'weight_lgbm_class_0': 0.05140685242849017, 'weight_lgbm_class_1': 0.7194923406107638, 'weight_lgbm_class_2': 0.852692122909164, 'weight_xgb_class_0': 0.8106469247309979, 'weight_xgb_class_1': 0.5200857693164942, 'weight_xgb_class_2': 0.47622282366376345, 'weight_cat_class_0': 0.00011092581176102905, 'weight_cat_class_1': 0.9659074203569962, 'weight_cat_class_2': 0.08155790133515116}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:01,622] Trial 1986 finished with value: 0.9493869197047756 and parameters: {'weight_lgbm_class_0': 0.04928829373260842, 'weight_lgbm_class_1': 0.4106393007900666, 'weight_lgbm_class_2': 0.901537243059267, 'weight_xgb_class_0': 0.03893391950157203, 'weight_xgb_class_1': 0.40798934567798084, 'weight_xgb_class_2': 0.45994735563523226, 'weight_cat_class_0': 5.6572582006498943e-05, 'weight_cat_class_1': 0.9691641556748443, 'weight_cat_class_2': 0.09302516001111444}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:01,694] Trial 1988 finished with value: 0.9497608201977771 and parameters: {'weight_lgbm_class_0': 0.04451335642009165, 'weight_lgbm_class_1': 0.7225713590386496, 'weight_lgbm_class_2': 0.8918021641746421, 'weight_xgb_class_0': 0.035514291310284773, 'weight_xgb_class_1': 0.4167672576242193, 'weight_xgb_class_2': 0.4578483632824507, 'weight_cat_class_0': 0.0335713889254802, 'weight_cat_class_1': 0.6844921140063792, 'weight_cat_class_2': 0.06169062733493165}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 1991/2000 [01:26<00:00, 18.65it/s]

[I 2026-07-03 10:24:01,694] Trial 1987 finished with value: 0.9497049039005807 and parameters: {'weight_lgbm_class_0': 0.05158189861476428, 'weight_lgbm_class_1': 0.7224883841528768, 'weight_lgbm_class_2': 0.8976123214801294, 'weight_xgb_class_0': 0.03942335560901475, 'weight_xgb_class_1': 0.4099662701129907, 'weight_xgb_class_2': 0.5902266489287339, 'weight_cat_class_0': 0.03150015337539688, 'weight_cat_class_1': 0.7663494362087383, 'weight_cat_class_2': 0.07846674274127997}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:01,834] Trial 1989 finished with value: 0.9497286238068053 and parameters: {'weight_lgbm_class_0': 0.0522593295028281, 'weight_lgbm_class_1': 0.7187155600676031, 'weight_lgbm_class_2': 0.9010387443831286, 'weight_xgb_class_0': 0.03479939075657576, 'weight_xgb_class_1': 0.4552341652454819, 'weight_xgb_class_2': 0.5911465638773743, 'weight_cat_class_0': 0.03401826067864696, 'weight_cat_class_1': 0.6648944848927323, 'weight_cat_class_2': 0.08329289256658173}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:01,870] Trial 1990 finished with value: 0.9496459068843404 and parameters: {'weight_lgbm_class_0': 0.05063178380799302, 'weight_lgbm_class_1': 0.5867730317591089, 'weight_lgbm_class_2': 0.9511704803698048, 'weight_xgb_class_0': 0.03452598313688397, 'weight_xgb_class_1': 0.45519104342766703, 'weight_xgb_class_2': 0.5961595019374686, 'weight_cat_class_0': 0.03360539368036429, 'weight_cat_class_1': 0.6838936587655018, 'weight_cat_class_2': 0.2033340748552257}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 1997/2000 [01:26<00:00, 16.48it/s]

[I 2026-07-03 10:24:01,960] Trial 1991 finished with value: 0.9497101647372191 and parameters: {'weight_lgbm_class_0': 0.04689999110244088, 'weight_lgbm_class_1': 0.5891656211724923, 'weight_lgbm_class_2': 0.8516680893876082, 'weight_xgb_class_0': 0.03275408568076724, 'weight_xgb_class_1': 0.41740024655859675, 'weight_xgb_class_2': 0.45156049235982454, 'weight_cat_class_0': 0.032182936093434485, 'weight_cat_class_1': 0.9671913713271669, 'weight_cat_class_2': 0.09742613383060438}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:02,011] Trial 1992 finished with value: 0.9496722965931849 and parameters: {'weight_lgbm_class_0': 0.05108275308326486, 'weight_lgbm_class_1': 0.7223669571092621, 'weight_lgbm_class_2': 0.8567170059299749, 'weight_xgb_class_0': 0.0327434240936472, 'weight_xgb_class_1': 0.5167210962834698, 'weight_xgb_class_2': 0.5973670466875604, 'weight_cat_class_0': 0.03418214983095687, 'weight_cat_class_1': 0.6844723575011473, 'weight_cat_class_2': 0.22604874699233488}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:02,103] Trial 1993 finished with value: 0.9496555821297162 and parameters: {'weight_lgbm_class_0': 0.04468563796225781, 'weight_lgbm_class_1': 0.6777105425238441, 'weight_lgbm_class_2': 0.8505940309696616, 'weight_xgb_class_0': 0.03438654531437555, 'weight_xgb_class_1': 0.513959499269921, 'weight_xgb_class_2': 0.7144458316228453, 'weight_cat_class_0': 0.034892672928392605, 'weight_cat_class_1': 0.6651346781152326, 'weight_cat_class_2': 0.10000523834719685}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:02,139] Trial 1994 finished with value: 0.9497732357828671 and parameters: {'weight_lgbm_class_0': 0.04612113520952417, 'weight_lgbm_class_1': 0.6804333064014134, 'weight_lgbm_class_2': 0.9486324833251969, 'weight_xgb_class_0': 0.03499490319405899, 'weight_xgb_class_1': 0.520684201828815, 'weight_xgb_class_2': 0.29792833188303686, 'weight_cat_class_0': 0.0287683654022005, 'weight_cat_class_1': 0.7628716994555812, 'weight_cat_class_2': 0.11584550887326034}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:02,142] Trial 1996 finished with value: 0.9490949847173388 and parameters: {'weight_lgbm_class_0': 0.09226430135768789, 'weight_lgbm_class_1': 0.6779468676324008, 'weight_lgbm_class_2': 0.9994689906782779, 'weight_xgb_class_0': 0.03326624666908001, 'weight_xgb_class_1': 0.4622048754620682, 'weight_xgb_class_2': 0.4500471022456564, 'weight_cat_class_0': 0.06532439756339779, 'weight_cat_class_1': 0.7549998685692447, 'weight_cat_class_2': 0.1033962535437513}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:02,143] Trial 1995 finished with value: 0.9497121980369831 and parameters: {'weight_lgbm_class_0': 0.018684690025711978, 'weight_lgbm_class_1': 0.6780636814488525, 'weight_lgbm_class_2': 0.8508020666813747, 'weight_xgb_class_0': 0.03140700129457477, 'weight_xgb_class_1': 0.5204954736406319, 'weight_xgb_class_2': 0.45091723430893876, 'weight_cat_class_0': 0.06824835256279102, 'weight_cat_class_1': 0.33941770974278407, 'weight_cat_class_2': 0.10272515938755399}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:02,165] Trial 1997 finished with value: 0.9485306063257549 and parameters: {'weight_lgbm_class_0': 0.0949322321132236, 'weight_lgbm_class_1': 0.680907715472069, 'weight_lgbm_class_2': 0.9998732829442468, 'weight_xgb_class_0': 0.09488318668949619, 'weight_xgb_class_1': 0.4627824803628977, 'weight_xgb_class_2': 0.6573295390260564, 'weight_cat_class_0': 0.06421251631508697, 'weight_cat_class_1': 0.7658457308283605, 'weight_cat_class_2': 0.10647986146599892}. Best is trial 1765 with value: 0.9497917773888238.

Best trial: 1765. Best value: 0.949792: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2000/2000 [01:26<00:00, 23.16it/s]

[I 2026-07-03 10:24:02,187] Trial 1999 finished with value: 0.9497460205839158 and parameters: {'weight_lgbm_class_0': 0.01749520504140869, 'weight_lgbm_class_1': 0.6709760762759878, 'weight_lgbm_class_2': 0.8558541251621312, 'weight_xgb_class_0': 0.030866146882310794, 'weight_xgb_class_1': 0.5417621275010274, 'weight_xgb_class_2': 0.4139053899480577, 'weight_cat_class_0': 0.0681610410285528, 'weight_cat_class_1': 0.6677604097668918, 'weight_cat_class_2': 0.041784694666791335}. Best is trial 1765 with value: 0.9497917773888238.
[I 2026-07-03 10:24:02,191] Trial 1998 finished with value: 0.948502256141365 and parameters: {'weight_lgbm_class_0': 0.09161373121216802, 'weight_lgbm_class_1': 0.7451618114699561, 'weight_lgbm_class_2': 0.8567622297331116, 'weight_xgb_class_0': 0.09420475386401642, 'weight_xgb_class_1': 0.46593431860774287, 'weight_xgb_class_2': 0.6532249588901197, 'weight_cat_class_0': 0.06760819035388299, 'weight_cat_class_1': 0.766827066154781, 'weight_cat_class_2': 0.19827879673915147}. Best is trial 1765 with value: 0.9497917773888238.

Best trial score:
0.9497917773888238

Best params:
{'weight_lgbm_class_0': 0.0960592117408375, 'weight_lgbm_class_1': 0.7720394466369802, 'weight_lgbm_class_2': 0.9992620359277073, 'weight_xgb_class_0': 0.0008310891044752133, 'weight_xgb_class_1': 0.4390144704192221, 'weight_xgb_class_2': 0.4408463205116877, 'weight_cat_class_0': 0.025354311969688355, 'weight_cat_class_1': 0.7627788630690802, 'weight_cat_class_2': 0.11526141784675017}

In [33]:
best_params = study.best_params

w_lgbm = np.array([best_params['weight_lgbm_class_0'], best_params['weight_lgbm_class_1'], best_params['weight_lgbm_class_2']])
w_xgb  = np.array([best_params['weight_xgb_class_0'],  best_params['weight_xgb_class_1'],  best_params['weight_xgb_class_2']])
w_cat  = np.array([best_params['weight_cat_class_0'],  best_params['weight_cat_class_1'],  best_params['weight_cat_class_2']])

proba_lgbm_test = X_test[['lgbm_0', 'lgbm_1', 'lgbm_2']].to_numpy()
proba_xgb_test  = X_test[['xgb_0', 'xgb_1', 'xgb_2']].to_numpy()
proba_cat_test  = X_test[['cat_0', 'cat_1', 'cat_2']].to_numpy()

blend_proba_test = (proba_lgbm_test * w_lgbm) + (proba_xgb_test * w_xgb) + (proba_cat_test * w_cat)

pred = np.argmax(blend_proba_test, axis=1)

In [38]:
w_lgbm

array([0.09605921, 0.77203945, 0.99926204])

In [39]:
w_xgb

array([0.00083109, 0.43901447, 0.44084632])

In [40]:
w_cat

array([0.02535431, 0.76277886, 0.11526142])

In [34]:
sub_labels = label_encoder.inverse_transform(pred)

In [35]:
np.unique(pred)

array([0, 1, 2])

# Submission

In [36]:
submission = pd.read_csv('../data/submission/sample_submission.csv')
submission['health_condition'] = sub_labels

submission.to_csv('../data/submission/submission_from_5.3.0_xgboost_lightgbm_catboost_submission.csv', index=False)

In [37]:
submission.head()

       id health_condition
0  690088        unhealthy
1  690089        unhealthy
2  690090          at-risk
3  690091          at-risk
4  690092        unhealthy